In [1]:
# Import necessary libraries
import camelot
import pandas as pd

In [2]:
# Define the extraction function
def extract_tables_from_pdf(file_path):
    """
    Extract useful financial tables (like income statements) from a PDF.
    We only scan page range 170-end to avoid unnecessary noise.
    """
    try:
        # Focus on financial statements pages
        tables = camelot.read_pdf(file_path, pages='170-end', flavor='stream')

        if tables.n == 0:
            print(f"No tables found in {file_path}")
            return []

        useful_tables = []
        keywords = ['total revenue', 'cost of sales', 'operating expenses', 'gross profit','earnings per share', 'net asset']

        for i, table in enumerate(tables):
            df = table.df
            # Flatten table text
            table_text = ' '.join(df.apply(lambda row: ' '.join(row), axis=1).tolist()).lower()

            if any(keyword in table_text for keyword in keywords):
                print(f"Selected table {i} (financial content detected)")
                useful_tables.append(df)
            else:
                print(f"Skipped table {i} (non-financial content)")

        if not useful_tables:
            print(f"No financial tables found in {file_path}")

    
        return useful_tables

    except Exception as e:
        print(f"Error extracting tables from {file_path}: {str(e)}")
        return []

In [3]:
# Now, in your Jupyter Notebook:
# Extract the tables from the PDF (replace 'your_pdf_file.pdf' with your actual file path)
file_path = '508_1590052852777.pdf'
tables = extract_tables_from_pdf(file_path)

C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (32.66969999999998, 697.6179999999999, 550.4245999999999, 843.6490504950496)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.276, 841.89)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.276, 841.89)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.276, 841.89)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)

Skipped table 0 (non-financial content)
Skipped table 1 (non-financial content)
Skipped table 2 (non-financial content)
Skipped table 3 (non-financial content)
Skipped table 4 (non-financial content)
Skipped table 5 (non-financial content)
Skipped table 6 (non-financial content)
Skipped table 7 (non-financial content)
Skipped table 8 (non-financial content)
Skipped table 9 (non-financial content)
Skipped table 10 (non-financial content)
Selected table 11 (financial content detected)
Skipped table 12 (non-financial content)
Skipped table 13 (non-financial content)
Skipped table 14 (non-financial content)
Skipped table 15 (non-financial content)
Skipped table 16 (non-financial content)
Skipped table 17 (non-financial content)
Skipped table 18 (non-financial content)
Skipped table 19 (non-financial content)
Skipped table 20 (non-financial content)
Skipped table 21 (non-financial content)
Selected table 22 (financial content detected)
Skipped table 23 (non-financial content)
Skipped table 24 (non-financial content)
Skipped table 25 (non-financial content)
Skipped table 26 (non-financial content)
Skipped table 27 (non-financial content)
Skipped table 28 (non-financial content)
Skipped table 29 (non-financial content)
Skipped table 30 (non-financial content)
Skipped table 31 (non-financial content)
Skipped table 32 (non-financial content)
Skipped table 33 (non-financial content)
Skipped table 34 (non-financial content)
Skipped table 35 (non-financial content)
Skipped table 36 (non-financial content)
Skipped table 37 (non-financial content)
Skipped table 38 (non-financial content)
Skipped table 39 (non-financial content)
Skipped table 40 (non-financial content)
Skipped table 41 (non-financial content)
Skipped table 42 (non-financial content)
Skipped table 43 (non-financial content)
Selected table 44 (financial content detected)
Skipped table 45 (non-financial content)
Selected table 46 (financial content detected)
Skipped table 47 (non-financial content)
Skipped table 48 (non-financial content)
Skipped table 49 (non-financial content)
Skipped table 50 (non-financial content)
Skipped table 51 (non-financial content)
Skipped table 52 (non-financial content)
Skipped table 53 (non-financial content)
Skipped table 54 (non-financial content)
Skipped table 55 (non-financial content)
Skipped table 56 (non-financial content)
Skipped table 57 (non-financial content)
Skipped table 58 (non-financial content)
Skipped table 59 (non-financial content)
Skipped table 60 (non-financial content)
Skipped table 61 (non-financial content)
Skipped table 62 (non-financial content)
Skipped table 63 (non-financial content)
Skipped table 64 (non-financial content)
Skipped table 65 (non-financial content)
Skipped table 66 (non-financial content)
Skipped table 67 (non-financial content)
Skipped table 68 (non-financial content)
Skipped table 69 (non-financial content)
Skipped table 70 (non-financial content)
Skipped table 71 (non-financial content)
Selected table 72 (financial content detected)
Selected table 73 (financial content detected)
Skipped table 74 (non-financial content)
Selected table 75 (financial content detected)
Skipped table 76 (non-financial content)
Skipped table 77 (non-financial content)
Selected table 78 (financial content detected)
Skipped table 79 (non-financial content)
Skipped table 80 (non-financial content)
Skipped table 81 (non-financial content)
Skipped table 82 (non-financial content)
Skipped table 83 (non-financial content)
Skipped table 84 (non-financial content)
Skipped table 85 (non-financial content)
Skipped table 86 (non-financial content)
Skipped table 87 (non-financial content)
Skipped table 88 (non-financial content)
Skipped table 89 (non-financial content)
Skipped table 90 (non-financial content)
Skipped table 91 (non-financial content)
Skipped table 92 (non-financial content)
Skipped table 93 (non-financial content)
Skipped table 94 (non-financial content)
Skipped table 95 (non-financial content)
Selected table 96 (financial content detected)
Skipped table 97 (non-financial content)
Skipped table 98 (non-financial content)
Skipped table 99 (non-financial content)
Skipped table 100 (non-financial content)
Skipped table 101 (non-financial content)
Skipped table 102 (non-financial content)
Skipped table 103 (non-financial content)
Skipped table 104 (non-financial content)
Skipped table 105 (non-financial content)
Skipped table 106 (non-financial content)
Selected table 107 (financial content detected)
Selected table 108 (financial content detected)
Selected table 109 (financial content detected)
Skipped table 110 (non-financial content)
Skipped table 111 (non-financial content)
Skipped table 112 (non-financial content)
Skipped table 113 (non-financial content)
Skipped table 114 (non-financial content)
Skipped table 115 (non-financial content)
Selected table 116 (financial content detected)
Skipped table 117 (non-financial content)
Skipped table 118 (non-financial content)
Skipped table 119 (non-financial content)
Skipped table 120 (non-financial content)
Selected table 121 (financial content detected)
Skipped table 122 (non-financial content)
Skipped table 123 (non-financial content)
Skipped table 124 (non-financial content)
Selected table 125 (financial content detected)
Skipped table 126 (non-financial content)
Skipped table 127 (non-financial content)
Skipped table 128 (non-financial content)
Skipped table 129 (non-financial content)
Skipped table 130 (non-financial content)
Skipped table 131 (non-financial content)
Skipped table 132 (non-financial content)
Skipped table 133 (non-financial content)
Skipped table 134 (non-financial content)
Skipped table 135 (non-financial content)
Skipped table 136 (non-financial content)
Skipped table 137 (non-financial content)
Skipped table 138 (non-financial content)
Skipped table 139 (non-financial content)
Skipped table 140 (non-financial content)
Skipped table 141 (non-financial content)
Selected table 142 (financial content detected)
Skipped table 143 (non-financial content)
Skipped table 144 (non-financial content)
Selected table 145 (financial content detected)
Skipped table 146 (non-financial content)
Skipped table 147 (non-financial content)
Skipped table 148 (non-financial content)
Skipped table 149 (non-financial content)
Selected table 150 (financial content detected)
Skipped table 151 (non-financial content)
Skipped table 152 (non-financial content)
Skipped table 153 (non-financial content)
Skipped table 154 (non-financial content)
Skipped table 155 (non-financial content)
Skipped table 156 (non-financial content)
Skipped table 157 (non-financial content)
Skipped table 158 (non-financial content)
Skipped table 159 (non-financial content)
Skipped table 160 (non-financial content)
Skipped table 161 (non-financial content)
Skipped table 162 (non-financial content)
Skipped table 163 (non-financial content)
Skipped table 164 (non-financial content)
Skipped table 165 (non-financial content)
Skipped table 166 (non-financial content)
Skipped table 167 (non-financial content)
Skipped table 168 (non-financial content)
Skipped table 169 (non-financial content)
Skipped table 170 (non-financial content)

In [4]:
# Show each table in a DataFrame
if tables:
    for i, table in enumerate(tables):
        print(f"Table {i + 1}:")
        display(table)  # This will display the table in a Jupyter notebook cell
else:
    print("No tables to display.")

Table 1:

,0,1,2
0,Financial Results and Appropriations,Additions of intangible assets of the Company,Share Information
1,Revenue,and Group during the year amounted to LKR.,The distribution and composition of
2,Revenue generated by the Company,34 Mn (2019 - LKR. 62 Mn) and LKR. 387 Mn,shareholders and the information relating
3,"amounted to LKR. 1,462 Mn (2019 – LKR.","(2019 - LKR. 1,810 Mn), respectively, and all","to earnings, dividends, net assets, market"
4,"1,722 Mn), whilst Group revenue amounted",other related movements are disclosed in Note,value per share and share trading is given
5,"to LKR. 140,043 Mn (2019– LKR. 135,456 Mn).",25 to the Financial Statements.,in the Share Information section of the
6,"Contribution to Group revenue, from the",,"Annual Report. As additional disclosures, the"
7,"different business segments, is provided in","Valuation of Land, Buildings and",Company’s Board of Directors’ (including their
8,Note 8 to the Financial Statements.,Investment Properties,"close family members) shareholdings, options"
9,,All land and buildings owned by Group,available under the employee share option
10,Profit and Appropriations,companies were revalued as at 31 December,"(ESOP) plans as at 31 March 2020, market"
11,The profit after tax of the Company was LKR.,2019 and the carrying value amounted to,"capitalisation, public holding percentage and"
12,"8,640 Mn (2019 – LKR. 12,002 Mn) whilst the","LKR. 87,185 Mn (2019 - LKR. 75,948 Mn). All",number of public shareholders are given in
13,Group profit attributable to equity holders,information related to revaluation is given in,the Share Information section of the Annual
14,"of the parent for the year was LKR. 9,414 Mn",Note 22.3 to the Financial Statements.,Report.
15,"(2019 - LKR. 15,254 Mn).",,
16,,"Investment properties of business units, when",Major Shareholders
17,The Company’s total comprehensive,"significantly occupied by Group companies,",Details of the twenty largest shareholders
18,"income net of tax was LKR. 8,662 Mn (2019","are classified as property, plant and equipment",of the Company and the percentages held
19,"- LKR. 11,977 Mn), and the Group total",in the consolidated financial statements in,by each of them are disclosed in the Share
20,comprehensive income attributable to parent,compliance with LKAS 40.,Information section of the Annual Report.
21,"was LKR. 16,581 Mn (2019 - LKR. 23,208 Mn).",,
22,,The Group revalued all its investment,Equitable Treatment of Shareholders
23,Dividend and Reserves,"properties as at 31 December 2019, and the",The Company has at all times ensured that all
24,As required by Section 56(2) of the Companies,"carrying value amounted to LKR. 15,008 Mn",shareholders are treated equitably.
25,"Act No 7 of 2007, the Board of Directors have","(2019- LKR. 13,985 Mn). All information related",
26,confirmed that the Company satisfies the,to revaluation of the investment properties,The Board of Directors
27,solvency test in accordance with Section 57,is provided in Note 24 to the Financial,The Board of Directors of the Company as
28,"of the Companies Act No 7 of 2007, and has",Statements.,at 31 March 2020 and their brief profiles are
29,"obtained certificates from the auditors, prior to",,given in the Corporate Governance section of
30,declaring all dividends.,Details of the Group’s real estate as at 31 March,the Annual Report.
31,,"2020, are disclosed in the Group Real Estate",
32,Accounting Policies,Portfolio in the Supplementary Information,Retirement and Re-Election of Directors
33,All the significant accounting policies,section of the Annual Report.,In accordance with Article 84 of the Articles
34,adopted by the Company and Group are,,"of Association of the Company, D A Cabraal"
35,mentioned in the Notes to the Financial,Investments,"and A N Fonseka retire by rotation, and, being"
36,Statements. There have been no changes,Detailed description of the long-term,"eligible, offer themselves for re-election."
37,in the accounting policies adopted by the,"investments held as at the reporting date, is",
38,Group during the year under review except,"given in Notes 26, 27 and 28 to the Financial",Review of the Performance of the Board
39,for SLFRS 16 Leases standard adopted with,Statements.,The performance of the board has been
40,effect from 1 April 2019. For all periods up to,,"appraised through a formalised process,"
41,"and including the year ended 31 March 2020,",Stated Capital,where each individual Director anonymously
42,the Group prepared its financial statements,Stated Capital as at 31 March 2020 for the,comments on the dynamics of the Board.
43,in accordance with Sri Lanka Accounting,"Company amounted to LKR. 62,881 Mn",The process is described in the Corporate
44,Standards (SLFRS/LKAS) which have materially,"(2019 - LKR. 62,806 Mn). The movement and",Governance Commentary section of the
45,converged with the International Financial,composition of the Stated Capital is disclosed,Annual Report.
46,Reporting Standards (IFRS) as issued by the,in the Statement of Changes in Equity and in,
47,International Accounting Standards Board,Note 34.1 to the Financial Statements.,Board Committees
48,(IASB).,,Information relating to members of the
49,,Revenue Reserves,"Audit Committee, Human Resources and"
50,Capital Expenditure,Revenue reserves as at 31 March 2020 for the,"Compensation Committee, Nominations"
51,The Company’s and Group’s capital,"Company and Group amounted to LKR. 59,631","Committee, Related Party Transactions Review"
52,"expenditure on property, plant and equipment","Mn (2019 - LKR. 55,598 Mn) and LKR. 87,885",Committee and Project Risk Assessment
53,amounted to LKR. 24 Mn (2019 - LKR. 80 Mn),"Mn (2019 - LKR. 82,834 Mn), respectively. The","Committee, including reports of each of"
54,"and LKR. 15,212 Mn (2019 - LKR. 12,020 Mn),",movement of the revenue reserve is disclosed,"the committees, where applicable, and"
55,"respectively, and all other related information",in the Statement of Changes in Equity.,attendance of Directors for each of the
56,and movements have been disclosed in Note,,"committee meetings, are disclosed in the"
57,22 to the Financial Statements.,,

Table 2:

,0,1,2,3,4,5
0,For the year ended 31 March,Note,2020,2019,2020,2019
1,In LKR '000s,,,,,
2,Continuing operations,,,,,
3,Revenue from contracts with customers,,"128,921,632","124,818,922","1,462,190","1,721,687"
4,Revenue from insurance contracts,,"11,120,928","10,637,226",-,-
5,Total revenue,14,"140,042,560","135,456,148","1,462,190","1,721,687"
6,Cost of sales,,"(113,960,929)","(107,668,833)","(995,038)","(839,306)"
7,Gross profit,,"26,081,631","27,787,315","467,152","882,381"
8,Dividend income,15,-,-,"6,367,610","7,187,071"
9,Other operating income,16.1,"2,241,751","1,925,698","45,737","266,834"
10,Selling and distribution expenses,,"(5,518,526)","(5,939,294)",-,-
11,Administrative expenses,,"(13,143,112)","(12,411,130)","(1,186,005)","(1,263,484)"
12,Other operating expenses,16.2,"(2,872,908)","(3,705,496)","(25,939)","(98,354)"
13,Results from operating activities,,"6,788,836","7,657,093","5,668,555","6,974,448"
14,Finance cost,17,"(3,165,519)","(2,722,289)","(237,046)","(184,544)"
15,Finance income,17,"9,357,342","12,051,601","3,822,342","6,351,370"
16,Change in insurance contract liabilities,36.2,"(5,617,431)","(3,422,893)",-,-
17,Change in fair value of investment property,24,"573,373","324,653",-,-
18,Share of results of equity accounted investees...,27.3,"4,466,457","4,727,345",-,-
19,Profit before tax,,"12,403,058","18,615,510","9,253,851","13,141,274"
20,Tax expense,21.1,"(2,662,263)","(2,378,114)","(614,311)","(1,139,058)"
21,Profit for the year,,"9,740,795","16,237,396","8,639,540","12,002,216"
22,Attributable to:,,,,,
23,Equity holders of the parent,,"9,413,788","15,254,126",,
24,Non-controlling interests,,"327,007","983,270",,
25,,,"9,740,795","16,237,396",,
26,,,LKR.,LKR.,,
27,Earnings per share,,,,,
28,Basic,19.1,7.14,11.13,,
29,Diluted,19.2,7.14,11.13,,
30,Dividend per share,20,3.50,6.00,,

Table 3:

,0,1
0,9. \n Basis of consolidation and material part...,The Group re-assesses whether or not it contro...
1,subsidiaries,circumstances indicate that there are changes ...
2,Accounting policy,three elements of control. Consolidation of a ...
3,,Group obtains control over the subsidiary and ...
4,Basis of consolidation,
...,...,...
61,Mack Air Services Maldives (Pte) Ltd.\n49.00,"consolidated statement of financial position, ..."
62,,attributable to the shareholders of the parent.
63,Tea Smallholder Factories PLC.\n37.62,
64,,The Consolidated Statement of Cash Flow includ...
65,,Company and its subsidiaries.

Table 4:

,0,1,2,3,4
0,Names of material partly-owned subsidiaries an...,,,,"Accounting judgements, estimates and assumptions"
1,owned by non-controlling interest:,,,,Consolidation of entities in which the Group h...
2,,,,majority of voting right (de facto control).,
3,Material partly-owned subsidiary,2020,2019,,
4,,,,,The Group considers that it controls some subs...
...,...,...,...,...,...
67,,,,,asset or liability that is a financial instrum...
68,Yala Village (Pvt) Ltd.,24.67%,24.67%,,
69,,,,,"SLFRS 9 Financial Instruments, is measured at ..."
70,,,,,in fair value recognised in the Income Stateme...
71,,,,SLFRS 9.,

Table 5:

,0,1
0,"NOTES TO THE INCOME STATEMENT, STATEMENT OF",Services transferred over time
1,COMPREHENSIVE INCOME AND STATEMENT OF FINANCIAL,"Under SLFRS 15, the Group determines, at contr..."
2,POSITION,satisfies the performance obligation over time...
3,,each performance obligation satisfied over tim...
4,14. \nRevenue,
5,,the revenue over time by measuring the progres...
6,Accounting policy,
7,,satisfaction of that performance obligation.
8,14.1 Total revenue,
9,14.1.1 Revenue from contract with customers,
10,,14.1.2 Revenue from insurance contracts
11,Revenue from contracts with customers is recog...,
12,,Revenue from insurance contracts comprise of g...
13,the goods or services is transferred to the cu...,
14,,net of premium ceded to reinsurers.
15,reflects the consideration to which the Group ...,
16,exchange for those goods or services.,
17,,14.2 Disaggregation of revenue
18,,The Group presented disaggregated revenue with...
19,Goods transferred at a point in time,
20,,segments based on timing of revenue recognitio...
21,"Under SLFRS 15, revenue is recognised upon sat...",
22,,region in the operating segment information se...
23,performance obligation. The revenue recognitio...,
24,time when control of the asset is transferred ...,
25,on delivery of the goods.,

Table 6:

,0,1
0,,GROUP\nCOMPANY
1,For the year ended 31 March,Note\n2020\n2019\n2020\n2019
2,In LKR ‘000s,
3,Timing of revenue recognition,
4,Goods transferred at a point in time,"107,459,688 \n 96,923,799 \n - \n-"
5,Services transferred over time,"21,461,944 \n 27,895,123 \n 1,462,190 \n1,721,687"
6,Total revenue from contracts with customers,"14.1.1\n 128,921,632 \n 124,818,922 \n 1,462,1..."
7,Revenue from insurance contracts,"14.1.2\n 11,120,928 \n 10,637,226 \n - \n-"
8,Total revenue,"140,042,560 \n 135,456,148 \n 1,462,190 \n1,72..."
9,14.3 Reconciliation of revenue,14.5 Performance obligations and significant...
10,Reconciliation between Revenue from contracts ...,The Group’s performance obligations and signif...
11,revenue information that is disclosed for each...,summarised below:
12,been provided in the operating segment informa...,
13,,Transportation
14,,This operating segment provides an array of tr...
15,14.4 Contract balances,
16,,"services, which primarily include a marine bun..."
17,Contract assets,
18,,logistics and air transportation multinational...
19,Contract assets are the Group’s right to consi...,
20,,"services. In providing airline services, net r..."
21,goods or services that the Group has transferr...,
22,,in time upon the sale of tickets as the entity...
23,rights that are conditional on some criteria o...,
24,,Total transaction price is comprised of cost a...
25,"time. Upon satisfaction of the conditions, the...",
26,,equal to the total ticketing service fee.
27,contract assets are reclassified to trade rece...,
28,,"In providing Marine Services, the principal ac..."
29,Contract liabilities,"supply bunker services to their customers, in ..."
30,Contract liabilities are the Group's obligatio...,fee. The performance obligation can be termed ...
31,services to a customer for which the Group has...,"Revenue is recognised at a point in time, upon..."
32,(or the amount is due) from the customer. Cont...,the vessels. Transaction price shall comprise ...
33,long-term advances received to deliver goods a...,equal to total bunkering fee.
34,advances received to render certain services a...,
35,,Consumer Foods
36,"allocated to unexpired service warranties, and...",
37,,Consumer Foods segment focuses on manufacturin...
38,redeemed.,
39,,"of beverages, frozen confectionary, processed ..."
40,Contract liabilities of the Group have been di...,Revenue is recognised at the point in time whe...
41,"liabilities, trade and other payables and othe...","is transferred to the customer, which is gener..."
42,"40, 41 and 43 respectively.",goods. Revenue is measured based on actual sal...
43,,output method is used for revenue recognition.

Table 7:

,0,1,2,3,4
0,15. \nDividend income,,,,
1,Accounting policy,,,,
2,Dividend,,,,
3,Dividend income is recognised when right to re...,,,,
4,,,,COMPANY,
5,For the year ended 31 March,,,2020,2019
6,In LKR ‘000s,,,,
7,Dividend income from investments in subsidiari...,,,"6,367,610","7,187,071"
8,16. \nOther operating income and other operat...,Gains and losses arising from activities incid...,,,
9,Accounting policy,generating activities and those arising from a...,,,
10,Gains and losses,"transactions, which are not material are aggre...",,,
11,Net gains and losses of a revenue nature arisi...,presented on a net basis.,,,
12,"property, plant and equipment and other non-cu...",,,,
13,,Any losses arising from guaranteed rentals are...,,,
14,"investments in subsidiaries, joint ventures an...",,,,
15,,year of incurring the same. A provision is rec...,,,
16,"in the income statement, after deducting from ...",,,,
17,,indicates a loss.,,,
18,the carrying amount of such assets and the rel...,,,,
19,Other income and expenses,,,,
20,Other income and expenses are recognised on an...,,,,
21,16.1 Other operating income,,,,
22,,Group,,Company,
23,For the year ended 31 March,2020,2019,2020,2019
24,In LKR '000s,,,,
25,Promotional income and commission fee,"1,610,234","1,389,652",-,-
26,Exchange gains,"25,178",-,-,-
27,"Profit on sale of property, plant and equipment",-,-,"1,646",-
28,Profit on sale of non current investments,-,-,"2,008","234,845"
29,Write back of dealer deposits,"10,850","9,278",-,-
30,Sundry income,"595,489","526,768","42,083","31,989"
31,,"2,241,751","1,925,698","45,737","266,834"
32,16.2 Other operating expenses,,,,
33,,Group,,Company,
34,For the year ended 31 March,2020,2019,2020,2019
35,In LKR '000s,,,,
36,Nation building tax,"916,107","1,323,895","20,324","34,820"
37,"Loss on sale of property, plant and equipment ...","97,007","58,546",-,"9,999"
38,Impairment losses on non financial assets,"1,108","174,700",-,"46,600"
39,"Heat, light and power","648,780","789,600",-,-
40,Exchange losses,-,"270,387",-,-
41,Other overheads,"1,209,906","1,088,368","5,615","6,935"
42,,"2,872,908","3,705,496","25,939","98,354"

Table 8:

,0,1
0,19. \nEarnings per share,parent (after adjusting for outstanding share ...
1,Accounting policy,average number of ordinary shares outstanding ...
2,Basic EPS is calculated by dividing the profit...,the weighted average number of ordinary shares...
3,ordinary equity holders of the parent by the w...,on conversion of all the dilutive potential or...
4,of ordinary shares outstanding during the year...,shares.
5,by dividing the profit attributable to ordinar...,

Table 9:

,0,1,2,3
0,24. \nInvestment property,,,"Accounting judgments, estimates and assumptions"
1,Accounting policy,,,
2,,,,Fair value of the investment property is ascer...
3,Investment properties are measured initially a...,,,
4,,,,valuations carried out by Chartered valuation ...
...,...,...,...,...
69,Freehold property,"14,581,020","13,522,700",
70,Leasehold property,"426,976","462,679",
71,,"15,007,996","13,985,379",
72,Rental income earned,"629,168","602,883",
73,Direct operating expenses incurred,"211,590","197,299",

Table 10:

,0,1
0,The income statement reflects the Group’s shar...,Upon loss of significant influence over the as...
1,operations of the associate or joint venture. ...,"over the joint venture, the Group measures and..."
2,investees is presented as part of the Group’s ...,investment at its fair value. Any difference b...
3,has been a change recognised directly in the e...,of the associate or joint venture upon loss of...
4,"or joint venture, the Group recognises its sha...",control and the fair value of the retained inv...
5,"applicable, in the statement of changes in equ...",disposal is recognised in income statement.
6,Unrealised gains and losses resulting from tra...,The accounting policies of associate companies...
7,Group and the associate or joint venture are e...,conform to those used for similar transactions...
8,the interest in the associate or joint venture.,policies that are specific to the business of ...
9,,discussed below.
10,The aggregate of the Group’s share of profit o...,
11,and a joint venture is shown on the face of th...,Equity method of accounting has been applied f...
12,outside operating profit and represents profit...,ventures using their corresponding/matching 12...
13,controlling interests in the subsidiaries of t...,"period. In the case of associates, where the r..."
14,,"to Group reporting dates, adjustments are made..."
15,"After application of the equity method, the Gr...",
16,,transactions or events up to 31 March.
17,it is necessary to recognise an impairment los...,
18,in its associate or joint venture. At each rep...,
19,,Investments in equity accounted investees are ...
20,determines whether there is objective evidence...,
21,,any accumulated impairment losses. The Group h...
22,the associate or joint venture is impaired. If...,
23,,impairment as at the reporting date due to the...
24,Group calculates the amount of impairment as t...,
25,the recoverable amount of the associate or joi...,
26,"carrying value, and then recognises the loss a...",
27,accounted investees’ in the Income Statement.,
28,GROUP,COMPANY
29,As at 31 March\nNumber of\nEffective,2020\n2019\nNumber of\nEffective \n2020\n2019
30,shares\nHolding,In LKR \nIn LKR \n shares\nHolding \nIn LKR \n...
31,%,‘000s\n‘000s\n%\n‘000s\n‘000s
32,27.1 \nInvestments in joint ventures,
33,Braybrooke Residential Properties (Pvt) Ltd.\n...,"1,804,500 \n 1,804,500 \n-\n-\n - \n-"
34,"DHL Keells (Pvt) Ltd.\n 1,000,000 \n 50.00","10,000 \n 10,000 \n 1,000,000 \n 50.00 \n 10,0..."
35,"Sentinel Reality (Pvt) Ltd.\n6,037,500\n40.16","63,324 \n 60,924 \n-\n-\n-\n-"
36,27.2 \nInvestments in associates,
37,Quoted,
38,"Nations Trust Bank PLC.- Voting shares\n 72,27...","1,699,620 \n 1,699,620 \n 48,347,078 \n 19.74 ..."
39,Nations Trust Bank PLC.- Non voting shares\n 2...,"1,759,237 \n 1,663,848\n 16,000,788 \n 41.06 \..."
40,Unquoted,
41,"Capitol Hotel Holdings (Pvt) Ltd.\n 3,249,232 ...","325,483 \n 325,483 \n3,254,832\n 19.47 \n 325,..."
42,"Fairfirst Insurance Ltd.\n 68,902,870 \n 19.80","689,718 \n 689,718 \n-\n-\n-\n-"
43,Indra Hotels and Resorts Kandy (Pvt) Ltd.\n 67...,"565,361 \n 420,561 \n-\n-\n - \n -"
44,"Maersk Lanka (Pvt) Ltd.\n 30,000 \n 30.00","150 \n 150 \n 30,000 \n 30.00 \n 150 \n 150"
45,"Saffron Aviation (Pvt) Ltd.\n 24,887,160 \n 40.00","248,872 \n 248,872 \n 24,887,160 \n 40.00 \n -..."
46,Saffron Aviation (Pvt) Ltd. - Preference \n 21...,"217,748 \n 217,748 \n 21,774,750 \n 40.00 \n 2..."
47,shares,
48,"South Asia Gateway Terminals (Pvt) Ltd.\n 159,...","7,346,367 \n 7,346,367 \n 159,826,750 \n 42.19..."
49,Cumulative profit accruing to the Group net,"8,491,290\n 6,373,231"
50,of dividend,
51,Share of net assets of equity accounted,"5,107,822 \n 4,308,072"
52,investees,
53,,"28,329,492 \n25,169,094 \n 10,381,881\n 10,286..."

Table 11:

,0,1,2,3,4,5,6,7,8
0,Tax expense,"294,246","(3,912)","(748,705)","(659,014)","(98,075)","(79,683)","(552,534)","(742,609)"
1,Share of results of equity,"2,680,367","2,907,898","1,504,066","1,649,426","282,024","170,021","4,466,457","4,727,345"
2,accounted investees,,,,,,,,
3,Other comprehensive,"565,341","832,203","234,964","294,310",(498),"16,764","799,807","1,143,277"
4,income,,,,,,,,
5,Group share of;,,,,,,,,
6,Total assets,"12,300,550","9,093,504","112,555,107","118,035,323","5,230,906","3,007,778","130,086,563","130,136,605"
7,Total liabilities,"(4,368,156)","(2,681,409)","(99,471,192)","(106,406,232)","(2,660,973)","(623,120)","(106,500,321)","(109,710,761)"
8,Net assets,"7,932,394","6,412,095","13,083,915","11,629,091","2,569,933","2,384,658","23,586,242","20,425,844"
9,Goodwill,"4,674,278","4,674,278","55,712","55,712","13,260","13,260","4,743,250","4,743,250"
10,,"12,606,672","11,086,373","13,139,627","11,684,803","2,583,193","2,397,918","28,329,492","25,169,094"

Table 12:

,0,1,2,3,4,5,6,7,8
0,As at 31 March,2020,2019,2020,2019,2020,2019,2020,2019
1,In LKR ‘000s,,,,,,,,
2,Group share of;,,,,,,,,
3,Revenue,"6,960,626","6,688,598","9,062,151","9,031,584","2,854,639","2,019,181","18,877,416","17,739,363"
4,Operating expenses,"(4,482,461)","(3,858,010)","(5,935,617)","(6,725,599)","(2,463,494)","(1,797,382)","(12,881,572)","(12,380,991)"
5,including cost of sales,,,,,,,,
6,Net finance income,"(92,044)","81,222","(873,763)","2,455","(11,046)","27,905","(976,853)","111,582"
7,Tax expense,"294,246","(3,912)","(748,705)","(659,014)","(98,075)","(79,683)","(552,534)","(742,609)"
8,Share of results of equity,"2,680,367","2,907,898","1,504,066","1,649,426","282,024","170,021","4,466,457","4,727,345"
9,accounted investees,,,,,,,,
10,Other comprehensive,"565,341","832,203","234,964","294,310",(498),"16,764","799,807","1,143,277"
11,income,,,,,,,,
12,Group share of;,,,,,,,,
13,Total assets,"12,300,550","9,093,504","112,555,107","118,035,323","5,230,906","3,007,778","130,086,563","130,136,605"
14,Total liabilities,"(4,368,156)","(2,681,409)","(99,471,192)","(106,406,232)","(2,660,973)","(623,120)","(106,500,321)","(109,710,761)"
15,Net assets,"7,932,394","6,412,095","13,083,915","11,629,091","2,569,933","2,384,658","23,586,242","20,425,844"
16,Goodwill,"4,674,278","4,674,278","55,712","55,712","13,260","13,260","4,743,250","4,743,250"
17,,"12,606,672","11,086,373","13,139,627","11,684,803","2,583,193","2,397,918","28,329,492","25,169,094"
18,Contingent liabilities,-,-,-,-,-,-,-,-
19,Capital commitments,-,-,"199,359","273,019","13,484,547","8,099,056","13,683,906","8,372,075"
20,Other commitments and,-,-,"624,094","61,297,752",-,-,"624,094","61,297,752"
21,Guarantees,,,,,,,,
22,Dividend received,"1,725,410","2,700,712","522,987","562,063","100,000",-,"2,348,397","3,262,775"

Table 13:

,0,1
0,35. \nShare-based payment plans,Where the terms of an equity-settled transacti...
1,Accounting Policy,the minimum expense recognised is the expense ...
2,Employee share option plan - Equity-settled tr...,"been modified, if the original terms of the aw..."
3,Employees of the Group receive remuneration in...,expense is recognised for any modification tha...
4,"based payment transactions, whereby employees ...","value of the share-based payment transaction, ..."
5,consideration for equity instruments (equity-s...,to the employee as measured at the date of mod...
6,The Group applies SLFRS 2 Share Based Payments...,The dilutive effect of outstanding options is ...
7,employee remuneration in the form of shares fr...,dilution in the computation of diluted earning...
8,,are given in Note 19.2).
9,The cost of equity-settled transactions is rec...,
10,a corresponding increase in other capital rese...,Employee share option scheme
11,period in which the performance and service co...,Under the John Keells Group’s Employees share ...
12,The cumulative expense recognised for equity-s...,share options of the parent are granted to exe...
13,each reporting date until the vesting date ref...,generally with more than 12 months of service....
14,the vesting period has expired and the Group’s...,share options is equal to the 30 days volume w...
15,number of equity instruments that will ultimat...,price of the underlying shares on the date of ...
16,credit to the income statement for a period re...,vest over a period of four years and is depend...
17,in cumulative expense recognised as at the beg...,criteria and a service criteria. The performan...
18,period and is recognised in employee benefits ...,performance achievement of “Met Expectations” ...
19,,being that the employee has to be in employmen...
20,No expense is recognised for awards that do no...,options vest. The fair value of the share opti...
21,except for equity-settled transactions where v...,"date using a binomial option pricing model, ta..."
22,"upon a market or non-vesting condition, which ...",terms and conditions upon which the share opti...
23,irrespective of whether or not the market or n...,
24,"satisfied, provided that all other performance...",The contractual term for each option granted i...
25,satisfied.,cash settlement alternatives. The Group does n...
26,,cash settlement for these share options.
27,Share-based payment plans,
28,,GROUP\nCOMPANY
29,For the year ended 31 March,2020\n2019\n2020\n2019
30,In LKR '000s,
31,Total expense arising from share-based payment...,"328,425\n 475,629\n 87,085\n 144,665"
32,Movements in the year,
33,The following table illustrates the number (No...,
34,GROUP,COMPANY
35,2020\nAs at 31 March,2019\n2020\n2019
36,No.\nWAEP,No.\nWAEP\nNo.\nWAEP\nNo.\nWAEP
37,Outstanding at the beginning of the year \n 45...,"44,893,817 \n 166.69 \n 16,231,867 \n 159.80 \..."
38,"Granted during the year\n 6,568,000 \n 136.97","10,381,395 \n 154.10 \n 2,124,000 \n 137 \n3,0..."
39,Transfers\n - \n -,"- \n - \n (173,386)\n 159.13 \n753,927\n161.88"
40,"Exercised during the year\n (377,489)\n 147.21","(21,054)\n 146.14 \n (101,311)\n 149 \n (21,05..."
41,"Expired during the year\n (10,363,498)\n 172.01","(9,517,702)\n 188.70 \n (3,661,230)\n 174.61 \..."
42,"Outstanding at the end of the year\n 41,563,46...","45,736,456\n 159.26 \n 14,419,940 \n 152.76 \n..."
43,"Exercisable at the end of the year\n 23,800,84...","26,310,276 \n 160.44 \n 9,199,686 \n 154.43 \n..."

Table 14:

,0,1,2
0,Liability adequacy test (LAT) - Life insurance...,36.2 Change in life insurance contract liabi...,
1,"As at 31 December 2019, liability adequacy tes...",The results of Union Assurance PLC’s (UA) life...,
2,"appointed actuary Mr. Vivek Jalan FIA, FIAI of...",consolidated into the Group’s Consolidated Inc...,
3,"Private Limited who concluded that, the liabil...",change in life insurance contract liabilities ...,
4,"meet future benefits and expenses. Hence, no p...","the Life Fund, the difference between all inco...",
5,be made for any premium deficiency.,attributable to life policy holders during the...,
6,Summarised financial information,,
7,For the year ended 31 March,2020,2019
8,In LKR '000s,,
9,Total Revenue,"11,120,928","10,637,226"
10,Cost of sales,"(5,290,054)","(5,190,123)"
11,Gross profit,"5,830,874","5,447,103"
12,Operating expenses including distribution and ...,"(3,681,724)","(2,547,119)"
13,Net finance income,"4,523,686","3,484,369"
14,Profit attributable to shareholders of UA,"(1,055,405)","(2,961,460)"
15,Change in insurance contract liabilities,"5,617,431","3,422,893"
16,,Union Assurance PLC follows a risk mitigation ...,
17,liabilities.,,
18,Following table describs headline risks and re...,,
19,Headline risk,Risk response,
20,Investment return on underlying items failing ...,Management discretion to determine amount and ...,
21,rates,holders bonuses (within limits),
22,Insufficient fees to cover cost of guarantees ...,Hedging programme,
23,Differences in duration and yield of assets an...,• Matching of assets and liabilities cash flows,
24,,• Investing in investment grade assets,
25,Policy holder behavioural risk,Surrender penalty,
26,37. \nInterest-bearing loans and borrowings,,
27,37.1 Movement,,
28,,GROUP\nCOMPANY,
29,As at 31 March,2020\n2019\n2020,2019
30,In LKR '000s,,
31,At the beginning of the year,"24,481,117 \n 20,583,499 \n 852,882",-
32,Cash movement,,
33,Loans obtained,"33,268,809\n 3,797,498 \n -","898,125"
34,Repayments,"(7,086,683)\n (1,992,028)\n (300,468)","(24,458)"
35,Non cash movement,,
36,SLFRS 16 initial recognition,"13,629,028 \n-\n-",-
37,Leases obtained,"7,607,634\n-\n-",-
38,Accrued Interest,"1,621,534 \n 57,308 \n-",-
39,Exchange rate adjustments,"3,902,713 \n 2,034,840 \n 53,333","(20,785)"
40,At the end of the year,"77,424,152 \n 24,481,117 \n 605,747","852,882"
41,Repayable within one year,"6,588,682 \n 3,204,613 \n 316,042","293,500"
42,Repayable after one year,"70,835,470 \n 21,276,504 \n 289,705","559,382"
43,,"77,424,152 \n 24,481,117 \n 605,747","852,882"

Table 15:

,0,1,2,3,4,5
0,NOTES TO THE FINANCIAL STATEMENTS,,,,,
1,38. \nEmployee benefit liabilities (Contd.),,,,,
2,38.1 Employee benefit liabilities,,,,,
3,,,Group,,Company,
4,As a31 March,Note,2020,2019,2020,2019
5,In LKR '000s,,,,,
6,Employee defined benefit plan - gratuity,38.2,"2,073,046","1,990,197","107,318","135,630"
7,Other long term employee benefit,38.3,"270,865","95,629","64,132","21,379"
8,At the end of the year,,"2,343,911","2,085,826","171,450","157,009"
9,38.2 Employee defined benefit plan - gratuity,,,,,
10,,,Group,,Company,
11,As at 31 March,,2020,2019,2020,2019
12,In LKR '000s,,,,,
13,At the beginning of the year,,"1,990,197","1,971,420","135,630","208,788"
14,Current service cost,,"235,405","196,458","8,254","12,535"
15,Transfers,,-,-,"(21,640)","2,634"
16,Interest cost on benefit obligation,,"195,095","185,512","14,919","21,923"
17,Payments,,"(238,597)","(334,143)","(22,005)","(109,256)"
18,(Gain)/Loss arising from changes in assumptions,,"(109,054)","(29,050)","(7,840)",(994)
19,At the end of the year,,"2,073,046","1,990,197","107,318","135,630"
20,The expenses are recognised in the income stat...,,,,,
21,items;,,,,,
22,Cost of sales,,"205,689","200,862","2,171","9,458"
23,Selling and distribution expenses,,"25,895","28,139",-,-
24,Administrative expenses,,"198,916","152,969","21,002","25,000"
25,,,"430,500","381,970","23,173","34,458"
26,38.3 Other long term employee benefits,,,,,
27,,,GROUP,,COMPANY,
28,As at 31 March,,2020,2019,2020,2019
29,In LKR '000s,,,,,
30,At the beginning of the year,,"95,629",-,"21,379",-
31,Current service cost,,"161,640","95,629","40,829","21,379"
32,Interest cost,,"13,596",-,"1,924",-
33,At the end of the year,,"270,865","95,629","64,132","21,379"
34,"Accounting judgements , estimates and assumptions",,,,,
35,Employee benefit liability - gratuity,,,,,
36,The employee benefit liability of the Group is...,,,,,
37,valuation carried out by Independent actuarial...,,,,,
38,valuations involve making assumptions about di...,,,,,
39,future salary increases. The complexity of the...,,,,,
40,"assumptions and its long term nature, the defi...",,,,,
41,highly sensitive to changes in these assumptio...,,,,,
42,reviewed at each reporting date.,,,,,
43,JOHN KEELLS HOLDINGS PLC | ANNUAL REPORT 201...,,,,,

Table 16:

,0,1,2,3,4,5,6,7,8,9,10
0,31 March,2020,2019,2018,2017,2016,2015,2014,2013,2012,2011*
1,LKR Mn,,,,,,,,,,
2,OPERATING RESULTS,,,,,,,,,,
3,Group revenue,"140,043","135,456","121,215","106,273","93,710","91,852","86,706","85,408","75,924","60,500"
4,EBIT,"15,508","20,198","28,155","23,324","20,192","19,226","16,537","16,677","14,192","11,425"
5,Finance cost,"(3,166)","(2,722)",(521),(436),(994),(668),"(1,217)","(1,081)","(1,416)",(796)
6,Share of results of equity accounted,"4,466","4,727","3,596","3,303","2,781","2,778","3,089","3,440","2,809","2,641"
7,investees (net of tax),,,,,,,,,,
8,Profit before tax,"12,403","18,616","27,634","22,888","19,198","18,557","15,320","15,595","12,778","10,629"
9,Tax expense,"(2,662)","(2,378)","(4,515)","(4,771)","(3,406)","(2,812)","(2,362)","(2,162)","(1,827)","(1,566)"
10,Profit after tax,"9,741","16,237","23,120","18,117","15,792","15,745","12,958","13,433","10,951","9,063"
11,Attributable to:,,,,,,,,,,
12,Equity holders of the parent,"9,414","15,254","21,021","16,275","14,070","14,348","11,721","12,113","9,689","8,245"
13,Non-controlling interests,327,983,"2,099","1,842","1,722","1,397","1,237","1,320","1,262",818
14,,"9,741","16,237","23,120","18,117","15,792","15,745","12,958","13,433","10,951","9,063"
15,CAPITAL EMPLOYED,,,,,,,,,,
16,Stated capital,"62,881","62,806","62,802","62,790","58,702","50,703","49,749","26,480","25,111","24,612"
17,Capital reserves and other components,"66,085","58,646","49,852","38,652","28,715","24,501","21,845","20,635","13,226","9,560"
18,of equity,,,,,,,,,,
19,Revenue reserves,"87,885","82,834","87,266","77,193","67,565","62,594","51,304","42,704","33,001","25,415"
20,,"216,851","204,286","199,920","178,635","154,982","137,798","122,898","89,819","71,338","59,587"
21,Non-controlling interest,"26,872","26,072","24,944","15,696","13,499","12,279","11,421","11,152","8,624","7,608"
22,Total equity,"243,723","230,358","224,864","194,331","168,481","150,077","134,319","100,971","79,962","67,195"
23,Total debt,"100,907","54,513","29,722","22,766","20,750","23,934","26,139","20,107","20,054","14,641"
24,,"344,630","284,871","254,586","217,097","189,231","174,011","160,458","121,078","100,016","81,836"
25,ASSETS EMPLOYED,,,,,,,,,,
26,"Property, plant and equipment (PP&E)","111,534","97,688","87,260","64,396","52,737","49,563","47,406","49,200","34,246","28,628"
27,Non-current assets other than PP&E,"204,360","170,687","136,427","107,912","93,376","78,030","71,969","59,787","52,397","47,436"
28,Current assets,"121,050","95,421","98,762","104,964","94,863","90,493","82,206","49,934","47,412","34,228"
29,Liabilities net of debt,"(92,314)","(78,925)","(67,862)","(60,175)","(51,745)","(44,075)","(41,123)","(37,843)","(34,039)","(28,456)"
30,,"344,630","284,871","254,587","217,097","189,231","174,011","160,458","121,078","100,016","81,836"
31,CASH FLOWS,,,,,,,,,,
32,Net cash flows from operating activities,"(10,350)","(4,743)","16,012","21,020","20,513","20,855","8,041","14,568","16,476","8,501"
33,Net cash flows from / (used in) investing,"(27,039)","(8,452)","(16,640)","(17,670)","(9,567)","(1,255)","(19,710)","(16,199)","(9,003)","(4,469)"
34,activities,,,,,,,,,,
35,Net cash flows from / (used in) financing,"18,431","(11,000)","(4,587)","(4,105)","(7,717)","(4,838)","25,446","(1,320)",496,"(6,791)"
36,activities,,,,,,,,,,
37,Net increase / (decrease) in cash and cash,"(18,959)","(14,709)","(5,215)",(755),"3,229","14,762","13,777","(2,951)","7,969","(2,759)"
38,equivalents,,,,,,,,,,
39,KEY INDICATORS,,,,,,,,,,
40,Basic earnings per share (Rs.),7.10,11.13,15.20,11.9,10.5,12.6,10.5,10.7,9.5,8.2
41,Interest cover (no. of times),4.9,7.8,54,52.8,51.5,27.7,13.6,15.4,10.0,14.4
42,Net assets per share** (Rs.),164.5,154.9,151.7,135.5,117.6,104.5,93.2,68.1,54.1,45.2
43,Enterprise value (EV),"207,528","210,020","187,926","136,022","124,182","155,675","124,182","203,615","166,143","175,672"
44,EV / EBITDA,9 .4,8.5,5.8,5.0,5.0,6.6,10.0,10.0,13.1,13.1
45,ROE (%),4.5,7.5,11.1,9.8,9.6,11. 0,11.0,15.0,14.7,15.1
46,Debt / equity ratio (%),41.4,23.7,13.2,11.7,12.3,15.9,19.5,19.9,25.0,21.8
47,Dividend payout (Rs. Mn),"4,614","8,186","8,325","7,280","8,038","3,476","3,267","2,982","2,314","1,844"
48,Current ratio (no. of times),2.1,1.7,3.0,3.7,4.0,2.6,2.4,2.0,2.0,1.8
49,Market price per share unadjusted (Rs.),115.4,156.0,159.6,137.9,148.0,199.4,227.0,247.0,206.0,285.6
50,Market price per share diluted (Rs.),115.4,156.0,159.6,137.9,129.5,192.7,173.8,238.2,152.6,34.6
51,Revenue growth rate (%),3.4,11.8,14.1,13.4,1.6,5.9,4.1,9.7,25.5,26.1
52,USD closing rate (Rs.),189.6,175.5,155.9,151.9,147.7,133.5,130.7,126.8,128.1,110.4
53,USD average rate (Rs.),179.4,168.6,153.6,148.0,139.2,131.2,130.1,129.9,112.6,112.1

Table 17:

,0,1,2,3,4
0,In USD '000s,,,,
1,Continuing operations,,,,
2,Revenue from contracts with customers,"679,877","711,422","7,711","9,813"
3,Revenue from Insurance Contracts,"58,647","60,628",-,-
4,Total Revenue,"738,524","772,050","7,711","9,813"
5,Cost of sales,"(600,981)","(613,672)","(5,247)","(4,784)"
6,Gross profit,"137,543","158,378","2,464","5,029"
7,Dividend income,-,-,"33,580","40,964"
8,Other operating income,"11,822","10,976",241,"1,521"
9,Selling and distribution expenses,"(29,102)","(33,852)",-,-
10,Administrative expenses,"(69,311)","(70,739)","(6,254)","(7,201)"
11,Other operating expenses,"(15,150)","(21,120)",(137),(561)
12,Results from operating activities,"35,802","43,643","29,894","39,752"
13,Finance cost,"(16,694)","(15,516)","(1,250)","(1,052)"
14,Finance income,"49,347","68,690","20,157","36,200"
15,Change in insurance contract liabilities,"(29,624)","(19,509)",-,-
16,Change in fair value of investment property,"3,024","1,850",-,-
17,Share of results of equity accounted investees...,"23,554","26,944",-,-
18,Profit before tax,"65,409","106,102","48,801","74,900"
19,Tax expense,"(14,040)","(13,554)","(3,240)","(6,492)"
20,Profit for the year,"51,369","92,548","45,561","68,408"
21,Attributable to:,,,,
22,Equity holders of the parent,"49,645","86,944",,
23,Non-controlling interests,"1,724","5,604",,
24,,"51,369","92,548",,

Table 18:

,0,1,2
0,GLOSSARY,,
1,ACCRUAL BASIS,DIVIDEND YIELD,PRICE EARNINGS RATIO
2,Recording revenues and expenses in the period,Dividends adjusted for changes in number of,Market price per share (diluted) over diluted
3,in which they are earned or incurred regardless,shares in issue as a percentage of the share p...,earnings per share.
4,of whether cash is received or disbursed in that,(diluted) at the end of the period.,
...,...,...,...
102,,Profit after tax attributable to equity holders,
103,Dividend paid as a percentage of Group profits,,
104,,of the parent divided by total revenue equity,
105,adjusted for non-cash gains items.,,
106,,accounted investees.,

In [9]:
keywords_1 = ['for the year ended 31 march','total revenue', 'cost of sales', 'gross profit','other operating income','basic']
keywords_2 = ['net assets per share** (rs.)','net assets per share* (rs.)']
# Loop through all the tables
for i, table in enumerate(tables):
    # Convert all cells to lowercase for matching
    table_lower = table.astype(str).apply(lambda col: col.str.lower())
  
    # Dictionary to store matched values
    matched_rows = {}

    for keyword in keywords_1:
        # Find rows containing the keyword
        row = table[table_lower.apply(lambda r: keyword in ' '.join(r), axis=1)]
        if not row.empty:
            matched_rows[keyword] = row.iloc[0, 3]

    if matched_rows:
        print(f"\n✅ Table {i+1} contains financial rows:")
        for k, v in matched_rows.items():
            print(f"{k.title()} (column 3): {v}")
        #display(table)  # Show the full table (optional)
        break
    else:
        print(f"Table {i+1} does not contain any of the target keywords.")



# Loop through all the tables
for i, table in enumerate(tables):
    # Convert all cells to lowercase for matching
    table_lower = table.astype(str).apply(lambda col: col.str.lower())
  
    # Dictionary to store matched values
    matched_rows = {}

    for keyword in keywords_2:
        # Find rows containing the keyword
        row = table[table_lower.apply(lambda r: keyword in ' '.join(r), axis=1)]
        if not row.empty:
            matched_rows[keyword] = row.iloc[0, 1]

    if matched_rows:
        print(f"\n✅ Table {i+1} contains financial rows:")
        for k, v in matched_rows.items():
            print(f"{k.title()} {k.title()}(column 1): {v}")
        #display(table)  # Show the full table (optional)
        break
    else:
        print(f"Table {i+1} does not contain any of the target keywords.")

Table 1 does not contain any of the target keywords.

✅ Table 2 contains financial rows:
For The Year Ended 31 March (column 3): 2019
Total Revenue (column 3): 135,456,148
Cost Of Sales (column 3): (107,668,833)
Gross Profit (column 3): 27,787,315
Other Operating Income (column 3): 1,925,698
Basic (column 3): 11.13
Table 1 does not contain any of the target keywords.
Table 2 does not contain any of the target keywords.
Table 3 does not contain any of the target keywords.
Table 4 does not contain any of the target keywords.
Table 5 does not contain any of the target keywords.
Table 6 does not contain any of the target keywords.
Table 7 does not contain any of the target keywords.
Table 8 does not contain any of the target keywords.
Table 9 does not contain any of the target keywords.
Table 10 does not contain any of the target keywords.
Table 11 does not contain any of the target keywords.
Table 12 does not contain any of the target keywords.
Table 13 does not contain any of the target keywords.
Table 14 does not contain any of the target keywords.
Table 15 does not contain any of the target keywords.

✅ Table 16 contains financial rows:
Net Assets Per Share** (Rs.) Net Assets Per Share** (Rs.)(column 1): 164.5

In [6]:
tables[13].iloc[42,0]

'Repayable after one year'