In [1]:
# Import necessary libraries
import camelot
import pandas as pd

In [2]:
# Define the extraction function
def extract_tables_from_pdf(file_path):
    """
    Extract useful financial tables (like income statements) from a PDF.
    We only scan page range 170-end to avoid unnecessary noise.
    """
    try:
        # Focus on financial statements pages
        tables = camelot.read_pdf(file_path, pages='130-end', flavor='stream')

        if tables.n == 0:
            print(f"No tables found in {file_path}")
            return []

        useful_tables = []
        keywords = ['total revenue', 'cost of sales', 'operating expenses', 'gross profit','earnings per share', 'net asset','number of shares','%','top twenty shareholders of the company']

        for i, table in enumerate(tables):  
            df = table.df
            # Flatten table text
            table_text = ' '.join(df.apply(lambda row: ' '.join(row), axis=1).tolist()).lower()

            if any(keyword in table_text for keyword in keywords):
                print(f"Selected table {i} (financial content detected)")
                useful_tables.append(df)
            else:
                print(f"Skipped table {i} (non-financial content)")

        if not useful_tables:
            print(f"No financial tables found in {file_path}")

    
        return useful_tables

    except Exception as e:
        print(f"Error extracting tables from {file_path}: {str(e)}")
        return []

In [3]:
# Now, in your Jupyter Notebook:
# Extract the tables from the PDF (replace 'your_pdf_file.pdf' with your actual file path)
file_path = '508_1684842640428.pdf'
tables = extract_tables_from_pdf(file_path)

C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (32.5197, 635.055, 559.1095, 753.5146609195402)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (39.460899999999995, 418.89150000000006, 381.5097500000002, 552.7021712962962)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (32.6796, 716.774, 124.0236, 840.5848129496403)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (33.3774128, 189.9233701, 62.9185936, 378.52732392924526)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (32.5197, 662.677, 468.2589000000003, 839.8995655172414)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (112.83, 435.4660000000001, 485.3710000000001, 642.1254523809523)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (128.673, 242.2815, 464.39615000000003, 458.2054523809524)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (32.5197, 663.2515, 538.0974999999999, 784.8953275862069)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (216.77199999999996, 414.71200000000005, 557.4141000000002, 536.529123931624)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (32.5197, 650.876, 560.8435000000002, 784.3356402863636)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (32.5197, 674.9655, 371.85535000000016, 843.0352272727273)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.276, 841.89)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (304.6387, 529.1446000000002, 560.5893500000001, 647.5846000000001)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.276, 841.89)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.276, 841.89)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.276, 841.89)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)

Skipped table 0 (non-financial content)
Skipped table 1 (non-financial content)
Skipped table 2 (non-financial content)
Skipped table 3 (non-financial content)
Skipped table 4 (non-financial content)
Skipped table 5 (non-financial content)
Skipped table 6 (non-financial content)
Skipped table 7 (non-financial content)
Skipped table 8 (non-financial content)
Skipped table 9 (non-financial content)
Skipped table 10 (non-financial content)
Skipped table 11 (non-financial content)
Skipped table 12 (non-financial content)
Selected table 13 (financial content detected)
Selected table 14 (financial content detected)
Selected table 15 (financial content detected)
Selected table 16 (financial content detected)
Selected table 17 (financial content detected)
Skipped table 18 (non-financial content)
Skipped table 19 (non-financial content)
Skipped table 20 (non-financial content)
Skipped table 21 (non-financial content)
Skipped table 22 (non-financial content)
Selected table 23 (financial content detected)
Skipped table 24 (non-financial content)
Skipped table 25 (non-financial content)
Skipped table 26 (non-financial content)
Skipped table 27 (non-financial content)
Selected table 28 (financial content detected)
Skipped table 29 (non-financial content)
Selected table 30 (financial content detected)
Skipped table 31 (non-financial content)
Skipped table 32 (non-financial content)
Selected table 33 (financial content detected)
Selected table 34 (financial content detected)
Skipped table 35 (non-financial content)
Selected table 36 (financial content detected)
Selected table 37 (financial content detected)
Selected table 38 (financial content detected)
Selected table 39 (financial content detected)
Skipped table 40 (non-financial content)
Selected table 41 (financial content detected)
Skipped table 42 (non-financial content)
Skipped table 43 (non-financial content)
Selected table 44 (financial content detected)
Selected table 45 (financial content detected)
Selected table 46 (financial content detected)
Selected table 47 (financial content detected)
Skipped table 48 (non-financial content)
Skipped table 49 (non-financial content)
Skipped table 50 (non-financial content)
Selected table 51 (financial content detected)
Skipped table 52 (non-financial content)
Skipped table 53 (non-financial content)
Skipped table 54 (non-financial content)
Selected table 55 (financial content detected)
Selected table 56 (financial content detected)
Selected table 57 (financial content detected)
Selected table 58 (financial content detected)
Selected table 59 (financial content detected)
Skipped table 60 (non-financial content)
Selected table 61 (financial content detected)
Skipped table 62 (non-financial content)
Selected table 63 (financial content detected)
Selected table 64 (financial content detected)
Selected table 65 (financial content detected)
Selected table 66 (financial content detected)
Selected table 67 (financial content detected)
Selected table 68 (financial content detected)
Selected table 69 (financial content detected)
Selected table 70 (financial content detected)
Selected table 71 (financial content detected)
Selected table 72 (financial content detected)
Selected table 73 (financial content detected)
Skipped table 74 (non-financial content)
Selected table 75 (financial content detected)
Skipped table 76 (non-financial content)
Selected table 77 (financial content detected)
Selected table 78 (financial content detected)
Skipped table 79 (non-financial content)
Skipped table 80 (non-financial content)
Skipped table 81 (non-financial content)
Skipped table 82 (non-financial content)
Skipped table 83 (non-financial content)
Skipped table 84 (non-financial content)
Skipped table 85 (non-financial content)
Selected table 86 (financial content detected)
Skipped table 87 (non-financial content)
Skipped table 88 (non-financial content)
Skipped table 89 (non-financial content)
Skipped table 90 (non-financial content)
Skipped table 91 (non-financial content)
Selected table 92 (financial content detected)
Skipped table 93 (non-financial content)
Skipped table 94 (non-financial content)
Skipped table 95 (non-financial content)
Skipped table 96 (non-financial content)
Skipped table 97 (non-financial content)
Skipped table 98 (non-financial content)
Skipped table 99 (non-financial content)
Skipped table 100 (non-financial content)
Skipped table 101 (non-financial content)
Skipped table 102 (non-financial content)
Skipped table 103 (non-financial content)
Skipped table 104 (non-financial content)
Skipped table 105 (non-financial content)
Skipped table 106 (non-financial content)
Skipped table 107 (non-financial content)
Skipped table 108 (non-financial content)
Skipped table 109 (non-financial content)
Skipped table 110 (non-financial content)
Skipped table 111 (non-financial content)
Skipped table 112 (non-financial content)
Skipped table 113 (non-financial content)
Skipped table 114 (non-financial content)
Skipped table 115 (non-financial content)
Skipped table 116 (non-financial content)
Skipped table 117 (non-financial content)
Skipped table 118 (non-financial content)
Skipped table 119 (non-financial content)
Skipped table 120 (non-financial content)
Selected table 121 (financial content detected)
Skipped table 122 (non-financial content)
Skipped table 123 (non-financial content)
Skipped table 124 (non-financial content)
Skipped table 125 (non-financial content)
Skipped table 126 (non-financial content)
Skipped table 127 (non-financial content)
Skipped table 128 (non-financial content)
Skipped table 129 (non-financial content)
Skipped table 130 (non-financial content)
Skipped table 131 (non-financial content)
Skipped table 132 (non-financial content)
Skipped table 133 (non-financial content)
Skipped table 134 (non-financial content)
Skipped table 135 (non-financial content)
Skipped table 136 (non-financial content)
Skipped table 137 (non-financial content)
Skipped table 138 (non-financial content)
Skipped table 139 (non-financial content)
Skipped table 140 (non-financial content)
Selected table 141 (financial content detected)
Skipped table 142 (non-financial content)
Skipped table 143 (non-financial content)
Skipped table 144 (non-financial content)
Skipped table 145 (non-financial content)
Skipped table 146 (non-financial content)
Skipped table 147 (non-financial content)
Selected table 148 (financial content detected)
Selected table 149 (financial content detected)
Selected table 150 (financial content detected)
Skipped table 151 (non-financial content)
Skipped table 152 (non-financial content)
Selected table 153 (financial content detected)
Skipped table 154 (non-financial content)
Skipped table 155 (non-financial content)
Skipped table 156 (non-financial content)
Skipped table 157 (non-financial content)
Skipped table 158 (non-financial content)
Skipped table 159 (non-financial content)
Skipped table 160 (non-financial content)
Skipped table 161 (non-financial content)
Skipped table 162 (non-financial content)
Skipped table 163 (non-financial content)
Skipped table 164 (non-financial content)
Skipped table 165 (non-financial content)
Skipped table 166 (non-financial content)
Skipped table 167 (non-financial content)
Skipped table 168 (non-financial content)
Skipped table 169 (non-financial content)
Skipped table 170 (non-financial content)
Skipped table 171 (non-financial content)
Skipped table 172 (non-financial content)
Selected table 173 (financial content detected)
Skipped table 174 (non-financial content)
Selected table 175 (financial content detected)
Selected table 176 (financial content detected)
Selected table 177 (financial content detected)
Selected table 178 (financial content detected)
Selected table 179 (financial content detected)
Selected table 180 (financial content detected)
Selected table 181 (financial content detected)
Skipped table 182 (non-financial content)
Skipped table 183 (non-financial content)
Skipped table 184 (non-financial content)
Skipped table 185 (non-financial content)
Skipped table 186 (non-financial content)
Skipped table 187 (non-financial content)
Selected table 188 (financial content detected)
Selected table 189 (financial content detected)
Skipped table 190 (non-financial content)
Skipped table 191 (non-financial content)
Skipped table 192 (non-financial content)
Skipped table 193 (non-financial content)
Skipped table 194 (non-financial content)
Skipped table 195 (non-financial content)
Skipped table 196 (non-financial content)
Skipped table 197 (non-financial content)
Skipped table 198 (non-financial content)
Selected table 199 (financial content detected)
Skipped table 200 (non-financial content)
Selected table 201 (financial content detected)
Skipped table 202 (non-financial content)
Skipped table 203 (non-financial content)
Skipped table 204 (non-financial content)
Skipped table 205 (non-financial content)
Skipped table 206 (non-financial content)
Skipped table 207 (non-financial content)
Skipped table 208 (non-financial content)
Skipped table 209 (non-financial content)
Skipped table 210 (non-financial content)
Skipped table 211 (non-financial content)
Skipped table 212 (non-financial content)
Selected table 213 (financial content detected)
Selected table 214 (financial content detected)
Skipped table 215 (non-financial content)
Skipped table 216 (non-financial content)
Skipped table 217 (non-financial content)
Skipped table 218 (non-financial content)
Skipped table 219 (non-financial content)
Skipped table 220 (non-financial content)
Skipped table 221 (non-financial content)
Skipped table 222 (non-financial content)
Selected table 223 (financial content detected)
Skipped table 224 (non-financial content)
Skipped table 225 (non-financial content)
Skipped table 226 (non-financial content)
Skipped table 227 (non-financial content)
Skipped table 228 (non-financial content)
Skipped table 229 (non-financial content)
Selected table 230 (financial content detected)
Selected table 231 (financial content detected)
Selected table 232 (financial content detected)
Skipped table 233 (non-financial content)
Selected table 234 (financial content detected)
Selected table 235 (financial content detected)
Selected table 236 (financial content detected)
Skipped table 237 (non-financial content)
Skipped table 238 (non-financial content)
Skipped table 239 (non-financial content)
Skipped table 240 (non-financial content)
Skipped table 241 (non-financial content)
Skipped table 242 (non-financial content)
Selected table 243 (financial content detected)
Skipped table 244 (non-financial content)
Selected table 245 (financial content detected)
Skipped table 246 (non-financial content)
Selected table 247 (financial content detected)
Skipped table 248 (non-financial content)
Skipped table 249 (non-financial content)
Skipped table 250 (non-financial content)
Skipped table 251 (non-financial content)
Skipped table 252 (non-financial content)
Skipped table 253 (non-financial content)
Skipped table 254 (non-financial content)
Selected table 255 (financial content detected)
Selected table 256 (financial content detected)
Skipped table 257 (non-financial content)
Selected table 258 (financial content detected)
Skipped table 259 (non-financial content)
Skipped table 260 (non-financial content)
Skipped table 261 (non-financial content)
Skipped table 262 (non-financial content)
Selected table 263 (financial content detected)
Skipped table 264 (non-financial content)
Skipped table 265 (non-financial content)
Skipped table 266 (non-financial content)
Selected table 267 (financial content detected)
Selected table 268 (financial content detected)
Skipped table 269 (non-financial content)
Skipped table 270 (non-financial content)
Selected table 271 (financial content detected)
Skipped table 272 (non-financial content)
Skipped table 273 (non-financial content)
Skipped table 274 (non-financial content)
Selected table 275 (financial content detected)
Skipped table 276 (non-financial content)
Skipped table 277 (non-financial content)
Skipped table 278 (non-financial content)
Skipped table 279 (non-financial content)
Selected table 280 (financial content detected)
Selected table 281 (financial content detected)
Selected table 282 (financial content detected)
Selected table 283 (financial content detected)
Selected table 284 (financial content detected)
Selected table 285 (financial content detected)
Selected table 286 (financial content detected)
Selected table 287 (financial content detected)
Selected table 288 (financial content detected)
Selected table 289 (financial content detected)
Skipped table 290 (non-financial content)
Skipped table 291 (non-financial content)
Skipped table 292 (non-financial content)
Skipped table 293 (non-financial content)
Skipped table 294 (non-financial content)
Skipped table 295 (non-financial content)
Skipped table 296 (non-financial content)
Skipped table 297 (non-financial content)
Skipped table 298 (non-financial content)
Skipped table 299 (non-financial content)
Skipped table 300 (non-financial content)
Skipped table 301 (non-financial content)
Skipped table 302 (non-financial content)
Skipped table 303 (non-financial content)
Skipped table 304 (non-financial content)
Skipped table 305 (non-financial content)
Skipped table 306 (non-financial content)
Skipped table 307 (non-financial content)
Skipped table 308 (non-financial content)
Skipped table 309 (non-financial content)
Skipped table 310 (non-financial content)
Skipped table 311 (non-financial content)
Skipped table 312 (non-financial content)

In [4]:
# Show each table in a DataFrame
if tables:
    for i, table in enumerate(tables):
        print(f"Table {i + 1}:")
        display(table)  # This will display the table in a Jupyter notebook cell
else:
    print("No tables to display.")

Table 1:

,0,1,2
0,"brand strategy aims at remaining relevant, whi...",,
1,"of the Group. To this end, the Group engaged i...",,
2,,,connected to each of the industry groups are d...
3,during the year under review:,,
4,y,The ONE JKH brand and initiative thereunder re...,
...,...,...,...
56,y,JKH was placed first for the third consecutive...,
57,,,Plantation Services
58,,in Corporate Reporting Assessment by Transpare...,
59,,,Other
60,,"Lanka, obtaining a 100% score for transparency...",

Table 2:

,0,1
0,OUTLOOK,
1,The section that ensues entails a discussion o...,
2,to navigating through the current socio-econom...,
3,landscape. The section highlights industry-spe...,
4,well as the way forward for the Group.,
...,...,...
75,,public deposits will be paramount
76,(2.0),
77,(4)\n(3)\n(2)\n(1)\n0\n1\n2\n3\n4,in any kind of debt optimisation
78,,programme.
79,International Monetary Fund\nAsian Development...,

Table 3:

,0,1
0,OUTLOOK,
1,In pursuit of the Government’s goal of achievi...,GROUP OUTLOOK
2,"CY2027, the Government has already implemented...",
3,,The recent developments on the economic
4,"sustained revenue generation, including upward...",
...,...,...
95,,assuming a proactive stance
96,Despite the short-term challenges as outlined ...,
97,,in shaping and propelling the
98,growth prospects in the medium to long-term re...,
99,Group Strategy and Outlook section.,nation’s economic revival.

Table 4:

,0,1,2
0,,,Global interest rates are likely to edge up on
1,and appreciated by ~10% as a result of fiscal ...,,
2,,,"the back of escalating inflation worldwide,"
3,the exchange rate have the following implicati...,,
4,,,with most major Central Banks adopting
5,optimally managed.,,
6,,,contractionary monetary policy measures. This
7,y,"Gross debt will record a movement, primarily g...",
8,,,will have implications on the Group’s foreign
9,,million long-term loan facility at the Holding...,
10,,,"currency borrowing portfolio, and the costs"
11,,loan facility at Waterfront Properties (Privat...,
12,,,"of funds therein; however, it is noted that"
13,,,interest rate swap agreements are in place
14,y,Any translation impact on the USD 175 million ...,
15,,,for a sizeable portion of the facilities with the
16,,debt level as the Holding Company maintains a ...,
17,,,aim of mitigating the Group’s exposure to rate
18,,date of the Report. Any exchange impact stemmi...,
19,,,fluctuations.
20,,"if applicable, is likely to be immaterial as t...",
21,,such impacts.,
22,,,"In March 2021, the Financial Conduct"
23,y,The foreign currency cash holdings include the...,
24,,,"Authority (FCA), the regulatory body"
25,,of the ‘Cinnamon Life Integrated Resort’ proje...,
26,,,overseeing the London Interbank Offered
27,,investment pipeline via the debt drawdown of t...,
28,,,"Rate (LIBOR), officially confirmed that the"
29,,"International Finance Corporation (IFC), the p...",
30,,,cessation date for LIBOR settings related to
31,,Asian Development Bank as well as the converti...,
32,,,all major currencies and two settings for USD
33,,,would no longer be considered representative
34,y,"At a Group level, the translation risk is also...",
35,,,"after December 2021, whilst the remaining"
36,,conscious strategy of matching liabilities aga...,
37,,,LIBOR settings for USD would cease after June
38,,"revenue streams, to the extent possible.",
39,,,"2023. Accordingly, all LIBOR linked loans and"
40,y,It is pertinent to note that the pressures on ...,
41,,,instruments of the Group will be transitioned
42,,‘Cinnamon Life Integrated Resort’ project is m...,
43,,,to identified benchmark rates based on the
44,,currency of Waterfront Properties (Private) Li...,
45,,,Secured Overnight Financing Rate (SOFR)
46,,"Accordingly, the risk is largely hedged ‘natur...",
47,,,during the ensuing year.
48,,linked revenue streams.,
49,,,"Looking towards the medium to long-term,"
50,y,The Group will continue to manage its foreign ...,
51,,,growth in consumption and trade in this
52,,"optimally, by matching liabilities against cor...",
53,,,"region, including Sri Lanka, is expected to pick-"
54,,given the ongoing constraints in the domestic ...,
55,,,up supported by strong under-penetration

Table 5:

,0,1
0,,A majority of such facilities were obtained
1,,at the time on a fixed/capped rate basis. The
2,INSIGHTS,
3,,Group will continue to place emphasis on
4,Managing the Group’s foreign currency exposure,the yield curve and rate expectations when
...,...,...
97,,a ‘re-rating’ of the Group’s performance and
98,attached to domestic debt as a result of this ...,
99,,investment thesis.
100,"risk of increasing LKR interest rates, to an e...",
101,short-term facilities into long-term facilitie...,

Table 6:

                                                    0        1
0   to long run, supported by economic recovery, i...
1   investments. This is especially advantageous f...
2                                                      ($/FEU)
3                            crucial shipping routes.
4                                                       10,000
5                                                        9,000
6                             Immediate to Short-Term
7                                                        8,000
8   The World Trade Organisation (WTO) projects wo...    7,000
9   1.7% in CY2023, weighed down by the Russia-Ukr...    6,000
10                                                       5,000
11  interest rates and financial uncertainty. Mome...
12                                                       4,000
13  CY2024. Downside risks to the forecast include...
14                                                       3,000
15  instabilities in financial markets, escalating...    2,000
16  slowdown in the ensuing year, it is encouragin...    1,000
17                                                           0
18        key contributor to world trade performance.

Table 7:

,0,1,2,3,4,5,6,7,8,9
0,EBITDA Margin,,,,,,,,,
1,(%),,,,,,,,,Key Downside Risks:
2,35,,,,,,,,,y\nLacklustre growth in consumer
3,30,,,,,,,,,demand for a prolonged period
4,25,,,,,,,,,
5,,,,,,,,,,y\nSupply chain disruptions with
6,20,,,,,,,,,
7,,,,,,,,,,"persistent inflation, globally and"
8,15,,,,,,,,,
9,,,,,,,,,,domestically
10,10,,,,,,,,,
11,05,,,,,,,,,y\nAbrupt ban of PET (polyethylene
12,,,,,,,,,,terephthalate) bottles and other
13,,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,
14,FY19\nFY20,FY21,,FY22,,,,FY23,Beyond,plastic materials

Table 8:

,0,1,2,3,4,5
0,OUTLOOK,,,,,
1,Beverages,y,"Explore new operating models, different market...",,,
2,,,"alternate methods of working, given changing c...",,,
3,The business will continue to focus on develop...,,,,,
4,,and digitisation trends.,,,,
5,"line with evolving market trends, where consum...",,,,,
6,"emphasis on healthy and sustainable products, ...",y\nImplement lean initiatives at factories.,,,,
7,augmented with evolving regulations and restri...,,,,,
8,calorific sugar content in beverages. Accordin...,Frozen Confectionery,,,,
9,carbonated soft drinks (CSD) as a proportion o...,,,,,
10,,,The global frozen confectionery markets have e...,,,
11,envisaged to proportionately diminish in the l...,,,,,
12,,,"growth in recent years, barring the impacts of...",,,
13,"the trends witnessed in recent years. However,...",,,,,
14,,,"rapid urbanisation, rising disposable income, ...",,,
15,beverage industry continue to be promising and...,,,,,
16,,,The overall prospects for the frozen confectio...,,,
17,for growth as these health and eco-conscious c...,,,,,
18,,,remain positive given the industry’s resilienc...,,,
19,beverage options.,,,,,
20,,,conditions. This positive trend is expected to...,,,
21,,,notwithstanding the short-term impacts previou...,,,
22,"Similar trends are witnessed globally, where C...",,,,,
23,worldwide continue to engage in reformulation ...,,,,,
24,,,Ice cream consumption in Sri Lanka at ~3 litre...,,,
25,aim of reducing the sugar content of their pro...,,,,,
26,,,"global averages, demonstrating the significant...",,,
27,"sustainable packaging, whilst extending the po...",,,,,
28,,,this market. In line with global and regional ...,,,
29,CSD beverages which are healthier and more nut...,,,,,
30,,,gradual shift in the bulk to impulse mix towar...,,,
31,Beverage business has already reformulated its...,,,,,
32,,,impulse products being the primary driver of t...,,,
33,~30% – 45% of the CSD portfolio’s calorific su...,,,,,
34,,,per capita ice cream consumption in Sri Lanka....,,,
35,and replaced with stevia; a natural sweetener ...,,,,,
36,,,to invest in expanding its distribution reach ...,,,
37,Low consumption patterns and penetration refle...,,,,,
38,,,The bulk:impulse mix of regional markets is hi...,,,
39,CSD market,,,,,
40,,,"market, demonstrating the significant potentia...",,,
41,Carbonated soft drinks - per capita consumptio...,overall ice cream market of Sri Lanka,,,,
42,,(%),,,,
43,60,,8,,,
44,52,,,,,
45,,30,,,,
46,50,,,,,
47,39,,,,,
48,40,,,44,,
49,31,Sri Lanka,Thailand,,Malaysia,56
50,30,,,,,
51,19,,,,,
52,20,,,,,
53,,70,,,,
54,10,,,,,
55,10,92,,,,
56,,Bulk\nImpluse,,,,
57,0,,,,,

Table 9:

                      0
0               OUTLOOK
1  Supermarkets Margins
2                   (%)
3                    10

Table 10:

,0,1,2,3,4,5,6,7,8,9
0,Supermarkets Margins,,,,,,,,,
1,(%),,,,,,,,,
2,,,,,,,,,,INSIGHTS
3,10,,,,,,,,,
4,,,,,,,,,,The Supermarket business leverages on a
5,,,,,,,,,,standard and an extended ‘iconic’ format
6,02468,,,,,,,,,depending on the maturity of the market.
7,,,,,,,,,,The concept of the extended ‘iconic’
8,,,,,,,,,,"format for select ‘Keells’ outlets, is aimed at"
9,,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,
10,(2),,,,,,,,,enhancing the overall customer experience
11,FY19\nFY20,FY21,,FY22,,,,FY23,Beyond,
12,(4),,,,,,,,,through best-in-class retail technological
13,,,,,,,,,,solutions and a wider offering.
14,EBITDA Margin,PBT Margin,,,,,,,,
15,,,,,,,,,,The selection of an extended ‘iconic’
16,"Given the increase in construction costs, the ...",,,,,,,,,
17,,,,,,,,,,format for outlets typically depends on
18,expansion of its outlet footprint in the short...,,,,,,,,,
19,,,,,,,,,,the level of development in a particular
20,considering the increased investment required ...,,,,,,,,,
21,,,,,,,,,,"area. In most cases, businesses identify"
22,"has seen a significant increase, the business ...",,,,,,,,,
23,,,,,,,,,,existing outlets that can expand their
24,which will have a positive influence on the fe...,,,,,,,,,
25,,,,,,,,,,offerings to accommodate a larger range
26,in furtherance of its selective expansion stra...,,,,,,,,,
27,,,,,,,,,,"of products and services. However, there"
28,"mature stores of its footprint, which has the ...",,,,,,,,,
29,,,,,,,,,,are occasional situations where an outlet
30,,,,,,,,,,with an extended ‘iconic’ format is opened
31,The distribution centre is envisaged to signif...,,,,,,,,,
32,,,,,,,,,,"immediately, without first having an"
33,"efficiencies, enabling better visibility of th...",,,,,,,,,
34,,,,,,,,,,existing outlet to build upon.
35,The business remains committed to prioritising...,,,,,,,,,
36,,,,,,,,,,Technological offerings:
37,"customers, and will continue to take necessary...",,,,,,,,,
38,,,,,,,,,,y\n‘Scan & Go’ technology

Table 11:

,0,1,2
0,positioned to capitalise on this opportunity b...,,incremental performance is attractive.
1,Prospects for the modern trade industry in Sri...,,
2,trade outlets in the country.,,
3,Modern Retail Penetration,,Given the increase in
4,,,
5,(%),,"construction costs, the"
6,,,
7,80\n70,,business will carefully
8,70,,
9,,,evaluate and monitor the
10,60,,
11,49\n48,,
12,50\n43,,expansion of its outlet
13,40,,
14,40,,
15,,,footprint in the short-term to
16,30,,
17,,17,ensure that expected returns
18,20,,
19,,,
20,10,,"are achieved, considering"
21,0,,
22,Singapore\nMalaysia\nHong Kong\nTaiwan\nThailand,Sri Lanka,the increased investment
23,,,required for each outlet.
24,Source: Company analysis,,

Table 12:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,,,,,,,,,,,,Margins of the Supermarket Business,,,,
1,Modern Trade Density,,,,,,,,,,,,,,,
2,Population (’000) per store,,,,,,,,,,(%),,,,,
3,,,,,,,,,,,,,8.0,,,
4,150,,,,,,,,,,,,,7.6,7.8,
5,132.0,,,,,,,,,,,,,,,7.5
6,120,,,,,,,,,,,,,,,
7,90,,,,,,,,,,,5.4,,,,
8,60\n47.0,,,,,,,,,,012345678,,,,,
9,30.0,,,,,,,,,,,,,,,
10,30,21.0,,,,,,,,,,,,,,
11,,,7.3,4.7,4.5,3.7,3.6,3.4,3.0,2.5,,,,,,
12,,,,,,,,,,1.9,0.9,,1.7,,,
13,,,,,,,,,,,,,,,1.3,

Table 13:

                                                    0      1     2
0                                                        (%)
1                                             Leisure
2                                                         20  (69)
3   In terms of fostering economic growth in Sri L...      0
4   potential to place the country as a tourism hu...
5                                                       (20)
6   diversity, rich cultural heritage and proximit...
7                                                       (40)
8   World, India and China. Considering the strate...
9   inflows and receipts to the country is a relat...   (60)
10  material economic benefits. Tourism will be a ...
11                                                      (80)
12  particularly in the context of the positive im...
13                                                     (100)

Table 14:

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,(YoY %),,,,,,,,,,...,,,,,,,,,,"sentiment, is envisaged to offset these"
1,,,,CY20,,,,,,,...,,,CY23,,,,,,,
2,1,,,,,,,,,,...,,,,,,,,,,impacts.
3,Jan\nFeb\n0,Mar\nApr,May,Jun,Jul,Aug\nSep,Oct\nNov,Dec,Jan,Feb\nMar,...,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,
4,(15),,,,,,,,,,...,,,,,,,,,,Sri Lanka
5,(20),,,,,,,,,,...,,,,,,,,,,
6,,,,,,,,,,,...,,,,,,,,,,Sri Lanka is envisaged to recover from the
7,,,,,,,,,,,...,,,,,,,,,,
8,,,,,,,,,,,...,,,,,,,,,,socio-economic crisis on the back of the many
9,(40),,,,,,,,,,...,,,,,,,,,,
10,,,,,,,,,,,...,,,,,,,,,,"difficult, yet necessary, corrective measures"
11,,,,,,,,,,,...,,,,,,,,,,that were undertaken and also proposed for
12,(60),,,,,,,,,,...,,,,,,,,,,
13,,,,,,,,,,,...,,,,,,,,,,implementation to stabilise and revive the
14,(65),,,,,,,,,,...,,,,,,,,,,
15,,,,,,,,,,,...,,,,,,,,,,economy.
16,(80),,,,,(74),,,,,...,,,,,,,,,,
17,,,,,,,(86),,,(87),...,,,,,,,,,,
18,,(90),,,,,,,,,...,,,,,,,,,,The tourism industry recorded an encouraging
19,(100),,,,,,,,,,...,,,,,,,,,,
20,,,,,,,,,,,...,,,,,,,,,,"uptick in tourist arrivals, in tandem with the"

Table 15:

,0,1
0,it is encouraging to witness the month-on-mont...,"is pertinent to note, as mentioned earlier, that"
1,recovery trend in arrivals is expected to cont...,interest rates may ease further once there is
2,The strong economic growth in India and the re...,clarity on the DDR as the risk premia currently
3,"opportunity for Sri Lanka, particularly consid...",attached to domestic debt as a result of this
4,opening of the Chinese borders for internation...,uncertainty will fall away. A portion of the
...,...,...
65,,experiential offerings focused on food and
66,"Given the significant cost pressures, particul...","beverages, lifestyle and entertainment, which"
67,"banqueting, the businesses will continue to ad...",would complement the hotel and gaming
68,"measures, although the price increases underta...","operations, will be considered for the retail"
69,"performance, will help partially offset this i...",space.

Table 16:

,0,1
0,OUTLOOK,
1,Maldivian Resorts,The sales momentum for the residential
2,,apartments at the ‘Cinnamon Life Integrated
3,The performance of the Maldivian Resorts segme...,
4,,Resort’ has been slow in line with the
...,...,...
90,construction work in discussion with the contr...,through various real estate products under
91,timely delivery of project milestones. However...,"Rajawella Holdings (Private) Limited, which"
92,to exert pressure on activity going forward wi...,"include scenic land parcels, townhouses and"
93,The negative perceptions caused due to the eco...,villa developments.
94,"May 2022, has also caused challenges in terms ...",

Table 17:

,0,1
0,The Group will continue to explore investment ...,The Group will leverage on its high-brand
1,Colombo to enter the industry group’s ‘Suburba...,equity and expertise in the industry to exploit
2,and potential in the suburban market on accoun...,such opportunities through projects such as
3,apartments in Colombo.,‘TRI-ZEN’ as well as other projects under the
4,,‘Metropolitan’ and ‘Suburban’ segments. The
...,...,...
77,0,and volatile costs and market
78,Thailand\nMalaysia\nMalaysia\nIndia\nIndia\nGr...,
79,,
80,(Outskirts)\n(Central KL)\n(Greater KL)\n(Chen...,conditions.
81,Apartments\nLanded houses,

Table 18:

,0,1
0,,stability of the banking sector. The impact on...
1,Financial Services,is somewhat less certain given the uncertainty...
2,,be any regulatory forbearance from the insuran...
3,,Assurance PLC (UA) has evaluated multiple scen...
4,Immediate to Short-Term,
...,...,...
56,,Sri Lanka has a relatively low level of insura...
57,economy and the outcome of the DDR process,
58,,Life Insurance Penetration in Regional Markets
59,and restructuring of foreign currency debt.,(%)
60,Nations Trust Bank (NTB) will continue to closely,

Table 19:

,0,1,2,3,4,5,6,7,8
0,sector are closely tied to the state of the,,,,,,,,
1,,,Sri Lanka has a relatively low level of insura...,,,,,,
2,economy and the outcome of the DDR process,,,,,,,,
3,,,Life Insurance Penetration in Regional Markets,,,,,,
4,and restructuring of foreign currency debt.,(%),,,,,,,
5,Nations Trust Bank (NTB) will continue to closely,,,,,,,,
6,"monitor developments in this area, despite",4.0,,,,,,,35
7,having a relatively low exposure to foreign,3.5,,,,,,,
8,,,,,,,,,25
9,,3.0,,,,,,,
10,currency debt in the industry. The Bank has,,,,,,,,
11,,,,,,,,,5
12,,2.5,,,,,,,
13,conducted various stress-tested scenarios on,,,,,,,,51
14,,2.0,,,,,,,
15,its capital and liquidity position and remains,,,,,,,,
16,,1.5,,,,,,,
17,,,,,,,,,(5)
18,confident in its ability to navigate any poten...,1.0,,,,,,,
19,,,,,,,,,(15)
20,impacts. The Governor of the Central Bank of,0.5,,,,,,,
21,Sri Lanka (CBSL) has assured the stability in,0.0,,,,,,,(25)
22,,,Thailand,Malaysia,India,Vietnam,Indonesia,Sri Lanka,Bangladesh
23,the domestic banking system and prioritising,,,,,,,,

Table 20:

,0,1,2
0,PORTFOLIO MANAGEMENT,,
1,y,,
2,,,The ONE JKH initiative is
3,,risk management and quality management in ensu...,
4,,,envisaged to aid the Group
...,...,...,...
57,The capital structure for new ventures is stre...,,
58,,,expectations that interest rates will ease
59,"in the execution of proactive measures, partic...",,
60,,,significantly thereon.
61,during both the development and operating phas...,,

Table 21:

,0,1
0,March 2022 due to the previously pegged exchan...,the investments in building
1,had the following implications on the Group’s ...,
2,,its businesses and bringing
3,stabilised and appreciated by ~10% as a result...,
4,,transformational investments
5,y\nGross debt recorded a significant increase ...,
6,,closer to reality.
7,USD 175 million long-term loan facility at the...,
8,long-term loan facility at Waterfront Properti...,
9,,PERFORMANCE OF THE PORTFOLIO
10,y\nThe translation impact on USD 175 million l...,
11,,Capital employed has significantly increased
12,level as the Holding Company maintained a net ...,
13,,as a result of the ‘Cinnamon Life Integrated
14,the year. The foreign currency cash holdings i...,
15,,"Resort’ project and its gestation period, whilst"
16,infusions of the ‘Cinnamon Life Integrated Res...,
17,,the convertible debenture issuance to HWIC
18,Group’s investment pipeline via the debt drawd...,
19,,"Asia Fund, the long-term financing facility"
20,"International Finance Corporation (IFC), the p...",
21,,obtained from IFC in 2020/21 and the private
22,Development Bank (ADB) as well as the converti...,
23,,placement to ADB has also contributed to
24,"y\nAt a Group level, the translation risk is a...","a notable increase in the capital base, all of"
25,conscious strategy of matching liabilities aga...,which have negative impacts on ROCE. These
26,"revenue streams, to the extent possible.","strategic choices, however, are catalysts for"
27,,future growth and risk mitigation given the
28,y\nIt is pertinent to note that the pressures ...,
29,,unprecedented and sustained economic
30,‘Cinnamon Life Integrated Resort’ project is m...,
31,,and financial stress in the country; while the
32,currency of Waterfront Properties (Private) Li...,
33,,Group is cognisant of the short-term effects
34,"Accordingly, the risk is largely hedged ‘natur...",
35,,"on performance, priority has always been"
36,"linked revenue streams. Similarly, at present,...",
37,,given to striking a balance between short-
38,the IFC loan since the cash is retained in for...,
39,,term performance and the accretive value
40,y\nThe Group will continue to manage its forei...,creation in the long-term. The Group is of the
41,"optimally, by matching liabilities against cor...",view that strengthening the capital base has
42,given the ongoing constraints in the domestic ...,enabled it to navigate the economic crisis and
43,,emerge stronger considering the investments

Table 22:

,0,1
0,PORTFOLIO MANAGEMENT,
1,,The Group is of the view that
2,INSIGHTS,
3,,strengthening the capital base
4,,has enabled it to navigate
...,...,...
82,Cash EPS growth (fully diluted)\n >20 \n (19.4...,
83,Long-term return on capital employed (ROCE)\n1...,
84,Long-term return on equity (ROE)\n18\n 5.6 \n ...,
85,Net debt (cash) to equity (with leases)\n50\n ...,
86,Net debt (cash) to equity (without leases)\n50...,

Table 23:

                                                    0
0                                            ROCE (%)
1                                                 240
2                            Hotel Management - 234.9
3                               Transportation - 35.2
4                           Financial Services - 33.4
5                                                  40
6                          Plantation Services - 32.1
7                       Information Technology - 23.5
8                  Retail - 17.8\nHurdle Rate - 15.0%
9                               Consumer Foods - 14.5
10  Maldivian Resorts - 4.7\nProperty (excl. Cinna...
11                         Sri Lankan Resorts - (2.9)
12  Colombo Hotels - 0.2\nCinnamon Life Integrated...
13                                                  0
14                                            Capital
15  employed\n20\n40\n60\n80\n100\n120\n140\n160\n...
16                                       (Rs.billion)
17                    Destination Management - (28.2)
18                                               (30)
19                     Transportation\nConsumer Foods
20  ROCE\n=\nEBIT \nx\nAsset \nx\nCapital \nROCE\n...
21  (%)\nmargin \nturnover\nstructure \n(%)\nmargi...
22                       (%)\nleverage\n(%)\nleverage
23  2022/23\n35.2\n11.0\n2.72\n1.18\n2022/23\n14.5...
24  2021/22\n2.2\n1.3\n1.40\n1.16\n2021/22\n20.8\n...
25  The significant increase in the ROCE of the Tr...
26  group is attributable to an improvement in mar...
27  and Shipping business, South Asia Gateway Term...
28  Group’s Bunkering business, Lanka Marine Servi...
29  a significant increase in revenue and profitab...
30  margins on account of the steep increase in gl...
31  the first half of the year, as well as higher ...
32  the decline in overall volumes at the Port of ...
33  at SAGT recorded an increase as a result of hi...
34  x\nAsset \nx\nCapital \nROCE\n=\nEBIT \noperat...
35  turnover\nstructure \n(%)\nmargin \nthe steep ...
36  leverage\n(%)\nincrease in tandem with the not...
37                                    industry group.
38                     2022/23\n17.8\n5.3\n2.09\n1.61
39                     2021/22\n17.6\n5.4\n1.88\n1.73
40  If the recurring impacts as discussed under th...
41  section are adjusted for, the adjusted ROCE of...
42  The improvement in the ROCE of the Retail indu...
43  the Supermarket business. The revenue of the S...
44  supported by the substantial price increases u...
45  account of inflation, thereby resulting in a h...
46  During the year, Rs.2.72 billion (~USD 7.5 mil...
47  infused by the Group as its equity contributio...
48  The Supermarket business recorded an increase ...
49  International Terminal (Private) Limited, the ...
50  funding working capital requirements during th...
51  WCT-1, to fund the development costs of the pr...
52  infusions to the project stood at Rs.5.58 bill...
53  Navigating Our Value Creation Journey      Gro...

Table 24:

,0,1
0,"STRATEGY, RESOURCE ALLOCATION AND",
1,PORTFOLIO MANAGEMENT,
2,Leisure,Property
3,ROCE\n=\nEBIT \nx\nAsset \nx\nCapital,ROCE\n=\nEBIT \nx\nAsset \nx\nCapital
4,(%)\nmargin \nturnover\nstructure,(%)\nmargin \nturnover\nstructure
...,...,...
75,,ROCE of the Information Technology sector incr...
76,,18.6%] due to an improvement in EBIT margins. ...
77,,strong growth in profitability on account of o...
78,,expanding the scope of services.
79,John Keells Holdings PLC | Annual Report 202...,

Table 25:

,0,1
0,The notable improvement of the ROCE in the Pla...,
1,to 32.1% [2021/22: 9.8%] was on account of a s...,
2,,INSIGHTS
3,"profitability and margins, driven by improved ...",
4,,"The ROCE of the Other, including Information T..."
5,The ROCE of the Holding Company declined margi...,Plantation Services industry group has been de...
6,an increase in capital employed on account of ...,years primarily on account of the capital rais...
7,debentures to HWIC Asia Fund in August 2022. H...,Company. The foreign currency cash holdings in...
8,supported by an increase in interest income dr...,earmarked for the equity infusions of the ‘Cin...
9,rates and the translation impact on foreign cu...,Resort’ project and the funds raised for the G...
10,which cushioned the impact of the increase in ...,pipeline via the issue of convertible debentur...
11,extent.,the debt drawdown from the IFC term loan facil...
12,,placement of ordinary shares to ADB.
13,Group Return on Capital Employed,
14,,Whilst the cash balance of the Group is curren...
15,ROCE\n=\nEBIT \nx\nAsset \nx\nCapital,below the Group’s hurdle rate exerting pressur...
16,(%)\nmargin \nturnover\nstructure,presence of adequate cash reserves enables the...
17,(%)\nleverage,"its liquidity requirements better, particularl..."
18,,and investments in the event of macroeconomic ...
19,2022/23\n5.5\n10.8\n0.43\n1.20,
20,2021/22\n4.5\n8.7\n0.39\n1.33,
21,,The Group will continue to focus on ensuring t...
22,,preserved with a focus on further enhancing it...
23,Group Return on Equity,proactively ahead of any future requirements.

Table 26:

,0,1,2,3
0,Significant Movements of the Portfolio and Cap...,,,
1,2019/20,2020/21,2021/22,2022/23
2,Invested Rs.10.35 billion in,Invested Rs.8.42 billion in,Invested Rs.13.55 billion in,Invested Rs.80.91 billion in
3,Waterfront Properties (Private),Waterfront Properties (Private),Waterfront Properties (Private),Waterfront Properties (Private)
4,Limited.,Limited.,Limited.,Limited.
5,Invested Rs.95.4 million in,Invested Rs.5.98 billion in JK,Invested Rs.1.94 billion in JK,Invested Rs.2.72 billion in
6,Nations Trust Bank PLC to,"Land (Private) Limited, increasing",Land (Private) Limited. Further,Colombo West International
7,purchase 1.15 million non-,the shareholding in Vauxhall,"to this, JK Land acquired the",Container Terminal (Private)
8,voting shares.,Land Developments (Private),remaining 13.3% equity stake,Limited.
9,,Limited to 86.7% from 60.0%.,in Vauxhall Land Developments,
10,,Committed to infuse a further,(Private) Limited for a,
11,,Rs.2.99 billion by 24 September,consideration of Rs.2.99 billion.,
12,,2021 to fully acquire Vauxhall,,
13,,Land Developments (Private),,
14,,Limited.,,
15,KHL invested Rs.466 million,Invested Rs.215 million in,Invested Rs.2.86 billion in,
16,in Ceylon Holiday Resorts,preference shares in Saffron,Colombo West International,
17,Limited for the refurbishment,Aviation (Private) Limited.,Container Terminal (Private),
18,of ‘Cinnamon Bentota Beach’,,Limited.,
19,Bentota.,,,
20,KHL invested Rs.145 million,KHL further invested Rs.105,Invested Rs.74 million in,
21,in Indra Hotels and Resorts,million in Indra Hotels and,preference shares in Saffron,
22,"Kandy (Private) Limited, for the","Resorts Kandy (Private) Limited,",Aviation (Private) Limited.,
23,preliminary construction work of,for the construction work of,,
24,‘Cinnamon Red Kandy’.,‘Cinnamon Red Kandy’.,,

Table 27:

,0,1,2,3,4,5
0,share-related information.,,,,,
1,,,Regional Market Performance,,,
2,Total number of shares in issue as at 31/03/2023,"1,384,916,632",(%),,,
3,Public shareholding as at 31/03/2023,98.51%,80.5\n100,,,
4,,,80,,,
5,Stock symbol,JKH.N0000,,,,
6,,,60,,,
7,Newswire Codes of the JKH Share,,,,,
8,,,40,25.1,,
9,Bloomberg,JKH.SL,,,,
10,,,(30.6)\n20,(8.1),4.8\n(15.1),(14.1)
11,Dow Jones,P\n.JKH,0,,,
12,Reuters,JKH.CM,(20),,,
13,,,(40),,,
14,Global Depositary Receipts (GDR) balance,"1,320,942",,,,
15,,,(60),,,

Table 28:

,0,1,2,3,4,5
0,"Index fell by 12.8%, representing its lowest p...",,,,,
1,,,,,indices underperformed its regional peers due ...,
2,,,,,,macroeconomic crisis and volatility on the soc...
3,Seismic Shifts in Asset Classes,,,,,
4,"(2022 YTD performance: %, end-of-week)",,,,which contributed to dampened investor sentime...,
5,,,,,foreign funds.,
6,,9.1,,Dollar Index,,
7,,1.6,,Brent Crude Oil,,
8,,,,,"However, the CSE witnessed a gradual reversal ...",
9,,(1.8),,Gold,,
10,,,,,"beginning of CY2023, in tandem with better sta...",
11,(8.6),,,Chinese Yuan,,
12,,,,,the macroeconomic landscape which included the...,
13,(12.5),,,HY Bond Index,,
14,,,,,of certain much needed reforms and the success...,
15,(14.7),,,10Y U.S. Treasury,,
16,,,,,~USD 3 billion bailout package from the Intern...,
17,(15.3),,,JPM EMBI,,
18,,,,,The market also recorded an encouraging increa...,
19,(15.3),,,IG Corporate Bond Index,,
20,,,,,"In this light, the ASPI closed at 9,301 points...",
21,(15.5),,,Copper,,
22,,,,,"2022/23, total net foreign inflows were record...",
23,(15.7),,,Japanese Yen,,
24,,,,,during the year compared to a total net foreig...,
25,(17.9),,,S&P 500,,
26,,,,,billion last year. Market price to earnings ra...,
27,(19.4),,,Nikkei 225,,
28,,,,,times in 2022/23 [2021/22: 8.8 times].,
29,(19.7),,,MSCI AC World,,
30,(20.1),,,EURO STOXX,,
31,,,,,31 March \n31 March,%
32,(22.3),,,MSCI Emerging Markets,,
33,,,,,2023\n2022,
34,(26.5),,,10Y Italian Gov. Bond,,
35,,,,,Overall CSE market capitalisation,
36,(37.6),,,NYSE FANG+,,
37,,,,,"(Rs.billion)\n3,903.54 \n3,826.50",2
38,,,,Bitcoin,,
39,,,,,Net foreign inflows/(outflows),
40,(50.0)\n(40.0)\n(30.0)\n(20.0),(10.0),0,10.0,,

Table 29:

,0,1,2,3,4,5
0,Although further headway needs to be made on t...,,Indices,,,
1,enterprise (SOE) reforms and normalisation of ...,,,,,
2,,,31 March,Value,,
3,"landscape, which may present short-term volati...",,,,,
4,,,,2023,2022,%
5,the Group remains confident in Sri Lanka’s gro...,,,,,
6,"medium to long-term, given the significant ste...",,,,,
7,,,MSCI,,,
8,in the recent past to achieve economic stability.,,,,,
9,,,All Country World Index,646.76,711.56,(9)
10,,Refer the Outlook section for a detailed discu...,All Country World Index,,,
11,,,excluding USA,298.68,323.59,(8)
12,,,World (23 Developed markets),"2,791.44","3,053.07",(9)
13,,Key Regulatory Highlights for the Year,USA,"3,904.80","4,338.85",(10)
14,y,Further to the enactment of the new Securities...,Europe,"1,902.85","1,927.37",(1)
15,,Commission (SEC) Act No. 19 of 2021 and the ai...,,,,
16,,,"Europe, Australasia and Far East","2,092.60","2,181.63",(4)
17,,complex instruments while protecting non-sophi...,,,,
18,,,Emerging Markets,990.28,"1,141.79",(13)
19,,"investors, the SEC released new rules for mark...",,,,
20,,"intermediaries, and a code for collective inve...",Frontier Markets,483.76,608.04,(20)
21,,This covers aspects such as licensing procedur...,,,,
22,,,Peer,,,
23,,"financial and infrastructure requirements, com...",,,,
24,,internal controls.,SENSEX,"58,991.52","58,568.51",1
25,,,JKSE,"6,805.28","7,071.44",(4)
26,y,CSE enacted a change in the S&P SL20 index con...,,,,
27,,2022 year-end rebalance in line with the S&P D...,STI,"3,258.90","3,408.52",(4)
28,y,The CSE Listing Rules were amended to facilita...,KLSE,"1,429.48","1,587.36",(10)
29,,trading of green bonds and perpetual debt secu...,,,,
30,,,Local,,,
31,y,"Effective 1 October 2022, withholding tax (WHT...",ASPI,"9,301.09","8,845.98",5
32,,re-introduced at 15% for dividends paid after ...,,,,
33,,,S&P SL20,"2,682.83","3,031.16",(11)

Table 30:

,0,1,2,3,4,5,6
0,Market Information of the Ordinary Shares of t...,,,,,,
1,,Q4,Q3,Q2,Q1,2022/23,2021/22
2,Share Information,,,,,,
3,High (Rs.),146.00,150.00,157.00,170.00,170.00,167.50
4,Low (Rs.),134.50,127.50,118.50,116.25,116.25,129.00
5,Close (Rs.),140.00,135.25,137.25,122.00,140.00,145.00
6,Dividends paid per share (Rs.),0.50,1.00,-,0.50,2.00,1.50
7,Trading Statistics,,,,,,
8,Number of transactions,"7,244","9,092","15,048","4,797","36,181","65,116"
9,Number of shares traded (‘000),"61,743","45,324","64,801","12,713","184,582","272,599"
10,Value of all shares traded (Rs.million),"8,717","6,152","8,304","1,632","24,805","40,522"
11,Average daily turnover (Rs.million),141,103,128,33,105,169
12,Percentage of total market turnover (%),7.4,5.1,4.3,2.3,5.0,3.5
13,Market capitalisation (Rs.million),"193,888","187,310","190,080","168,960","193,888","200,813"
14,Percentage of total market capitalisation (%),5.0,3.4,4.5,4.9,5.0,5.2

Table 31:

,0,1,2
0,,,convertible debentures amounting to Rs.27.06 b...
1,,,by way of a private placement of LKR denominat...
2,JKH Share Performance vs ASPI (indexed),,
3,(Index),No. of shares (million),"Fund (HWIC), a subsidiary of Fairfax Financial..."
4,,,"Accordingly, 208,125,000 Sri Lankan Rupee deno..."
5,200,150,
6,,,unsecured convertible debentures were issued t...
7,,120,of Rs.130 per debenture.
8,150,,
9,,90,
10,,,The debentures have a maturity period of three...
11,100,,
12,,,interest at a rate of 3% per annum. The date o...
13,,60,
14,,,debentures is 12 August 2025 with HWIC having ...
15,50,,
16,,30,each debenture to one new ordinary share of th...
17,,,conversion period from 12 February 2024 to 12 ...

Table 32:

,0,1
0,JKH SHARE,JKH Beta
1,,The beta of the JKH share as of 31 March 2023 ...
2,The graph below illustrates that the JKH share...,
3,,calculated based on the daily JKH share moveme...
4,"decade-low, barring the period where the equit...",
...,...,...
67,Apr-22\nJun-22\nJul-22\nSep-22\nOct-22\nJan-23...,for a maximum cumulative amount of the LKR equ...
68,Mar-22\nMay-22\nAug-22\nNov-22\nDec-22\nMar-23,"million to ADB in two phases. In January 2022,..."
69,High\nLow\nJKH 30-day moving average,above transaction was completed whereby JKH is...
70,,ordinary shares at Rs.154.50 per share to ADB ...
71,,LKR equivalent of USD 50 million.

Table 33:

,0,1
0,SHARE INFORMATION,
1,"Additionally, in terms of the second phase, th...",EARNINGS PER SHARE
2,"non-tradable/non-transferable options, entitli...",
3,,The fully diluted earnings per share (EPS) for...
4,"for additional 39,025,204 new ordinary shares ...",
...,...,...
59,macroeconomic environment.,"Lanka Act No.36 of 1987, circulated on 16 Nove..."
60,Distributions to Shareholders and Payout Ratio,Market Capitalisation and Enterprise Value
61,(Rs.billion)\n(%),
62,,(Rs.billion)
63,10\n60,

Table 34:

,0,1,2,3,4,5,6,7
0,Distributions to Shareholders and Payout Ratio,,,,,,,
1,(Rs.billion),,,,,,(%),
2,,,,,,,,(Rs.billion)
3,10,,,,,,60,
4,,54,,,,,,
5,,,,,,,,350
6,,,49,,,,,
7,,,,,,,50,
8,8,,,,,,,300
9,,,,41,,,,
10,,,,,,,40,250
11,6,,,,,,,
12,,,,,,,30,200
13,4,,,,,,,
14,,,,,,,,150
15,,,,,,15,20,
16,,,,,10,,,
17,2,,,,,,,100
18,,,,,,,10,
19,,8.2,4.6,2.0,2.0,2.8,,50

Table 35:

,0,1,2,3,4,5,6,7
0,Summary Indicators,,,,,Price Earnings Ratio,,
1,,,2022/23,2021/22,2020/21,,2022/23,2021/22
2,Market capitalisation,(Rs.billion),193.9,200.8,196.0,JKH,10.7,9.9
3,Enterprise value,(Rs.billion),357.6,312.0,244.7,CSE,5.0,8.8
4,EV/EBITDA,(times),8.0,10.7,15.7,SENSEX,22.2,24.8
5,Diluted EPS,(Rs.),13.1,15.1,3.6,KLSE,16.4,16.2
6,PER,(diluted),10.7,9.6,41.0,JCI,11.8,16.7
7,Price to book,(times),0.6,0.6,0.9,STI,12.6,24.8
8,Price/cash earnings,(times),4.6,4.7,13.2,,,
9,Dividend yield,(%),1.4,1.0,1.0,,,
10,Group dividend,,,,,,,
11,payout ratio,(%),15.2,10.0,41.5,,,
12,Net assets per share,(Rs.),248.6,224.8,171.4,,,
13,TSR,(%),(2.4),(1.3),30.0,,,

Table 36:

,0,1,2,3,4,5,6
0,Composition of Shareholders,,,,,,
1,,,31 March 2023,,,31 March 2022,
2,,Number of,Number of,%,Number of,Number of,%
3,,shareholders,shares,,shareholders,shares,
4,Non-Resident,,,,,,
5,Institutions,73,"515,773,768",37,75,"492,439,810",36
6,Individuals,250,"10,240,144",1,237,"6,975,141",1
7,Total Non-Resident,323,"526,013,912",38,312,"499,414,951",36
8,Resident,,,,,,
9,Institutions,720,"477,354,563",34,731,"465,904,849",34
10,Individuals*,"14,061","381,548,157",28,"13,414","419,596,832",30
11,Total Resident,"14,781","858,902,720",62,"14,145","885,501,681",64
12,Total,"15,104","1,384,916,632",100,"14,457","1,384,916,632",100

Table 37:

,0,1,2,3,4,5,6,7,8
0,Distribution of Shareholders,,,,,,,,
1,,,31 March 2023,,,,31 March 2022,,
2,,Number of,%,Number of,%,Number of,%,Number of,%
3,,shareholders,,shares held,,shareholders,,shares held,
4,"Less than or equal to 1,000","10,028",66,"2,139,812",0,"9,494",66,"2,077,696",0
5,"1,001 to 10,000","3,406",23,"12,421,138",1,"3,376",23,"12,204,165",1
6,"10,001 to 100,000","1,297",9,"40,535,936",3,"1,208",8,"38,368,241",3
7,"100,001 to 1,000,000",267,2,"79,734,447",6,274,2,"87,756,601",6
8,"Over 1,000,001",106,1,"1,250,085,299",90,105,1,"1,244,509,929",90
9,Total,"15,104",100,"1,384,916,632",100,"14,457",100,"1,384,916,632",100

Table 38:

,0,1,2,3,4
0,Top Twenty Shareholders of the Company,,,,
1,,31 March 2023,,31 March 2022,
2,,Number of,%,Number of,%
3,,shares,,shares,
4,Mr S E Captain,"134,044,705",9.68,"134,220,895",9.69
5,Melstacorp PLC,"128,917,111",9.31,"128,917,111",9.31
6,HWIC Asia Fund,"119,200,760",8.61,"119,200,760",8.61
7,Paints and General Industries Limited,"100,717,931",7.27,"140,437,428",10.14
8,Asian Development Bank,"65,042,006",4.70,"65,042,006",4.70
9,Citigroup Global Markets Limited Agency Tradin...,"61,904,939",4.47,"61,904,939",4.47
10,Schroder International Selection Fund,"44,418,290",3.21,"41,974,590",3.03
11,CIC Holdings PLC,"35,338,032",2.55,-,-
12,Aberdeen Standard Asia Focus PLC,"33,398,572",2.41,"28,123,572",2.03
13,Norges Bank Account 2,"31,901,605",2.30,"31,901,605",2.30
14,Sri Lanka Insurance Corporation Limited - Life...,"21,846,511",1.58,"12,270,665",0.89
15,Mr Kandiah Balendra,"19,511,476",1.41,"19,511,476",1.41
16,Employees Trust Fund Board,"18,499,897",1.34,"18,499,897",1.34
17,Mrs C S De Fonseka,"17,606,991",1.27,"17,472,745",1.26
18,Edgbaston Asian Equity Trust,"17,520,023",1.27,"15,142,109",1.09
19,Fidelity Fund - Pacific,"15,244,082",1.10,"17,880,904",1.29
20,Mrs S A J De Fonseka,"15,204,230",1.10,"15,204,230",1.10
21,Polypak Secco Limited,"14,937,924",1.08,-,-
22,Chemanex PLC,"13,105,475",0.95,"12,605,234",0.91
23,Sunsuper Superannuation Fund,"11,587,196",0.84,-,-

Table 39:

                                                    0
0                                      Award 2\nOther
1                    1,369,700\n1,369,700\nExecutives
2                                   Total\n48,770,799
3   1  \nGEC comprises of the Executive Directors ...
4   2  \nAdjusted for Bonus Issues/Right Issues/Su...
5   3  \nPlan 9 (Award 3) - 100% of the options ha...
6   4  \nPlan 10 (Award 1) - 75% of the options ha...
7   5  \nPlan 10 (Award 2) - 50% of the options ha...
8   6  \nPlan 10 (Award 3) - 25% of the options ha...
9   7  \nPlan 11 (Award 1) - None of the options h...
10  8  \nPlan 11 (Award 2) - None of the options h...

Table 40:

,0,1,2,3,4,5,6
0,Share Capital,,,"GDR History (in terms of ordinary shares, mill...",,,
1,Year ended 31 March,Number of shares in,Year ended,Opening,Issued*,Converted/,Closing
2,,issue (million),31 March,balance,,repurchased,balance
3,2012,844.12,2012,0.95,0.32,0.08,1.19
4,2013,857.24,2013,1.19,-,0.06,1.13
5,2014,990.29,2014,1.13,-,0.01,1.12
6,2015,997.49,2015,1.12,-,-,1.12
7,2016,"1,189.40",2016,1.12,-,-,1.12
8,2017,"1,387.47",2017,1.12,0.2,-,1.32
9,2018,"1,387.53",2018,1.32,-,-,1.32
10,2019,"1,318.17",2019,1.32,-,-,1.32
11,2020,"1,318.55",2020,1.32,-,-,1.32
12,2021,"1,319.66",2021,1.32,-,-,1.32
13,2022,"1,384.92",2022,1.32,-,-,1.32
14,2023,"1,384.92",2023,1.32,-,-,1.32

Table 41:

,0,1,2,3
0,y,Select Group policies related to ESG areas wer...,y,"In August 2022, the Company concluded"
1,,advocated by internationally reputed instituti...,,"the issuance of unlisted, unsecured, LKR"
2,,"International Finance Corporation, particularl...",,denominated convertible debentures
3,,positive externalities.,,"amounting to Rs.27.06 billion, through a"
4,,,,"private placement to HWIC Asia Fund, a"
...,...,...,...,...
67,,,,managing personal finances in the current
68,,"• \nAs noted in previous Annual Reports, the G...",,"economic climate, emotional support"
69,,participation in its employee cadre up to 40% ...,,with counsellors and employee supplier
70,,participation as at the end of the year stood ...,,catalogues to name a few.
71,,• \nThe Group also adopted gender-neutral term...,,

Table 42:

,0,1
0,CORPORATE GOVERNANCE COMMENTARY,
1,Access to Independent Professional,
2,Advice,Prior to Appointment
3,To preserve the independence of the Board,
4,,y\nNominees are requested to make known their ...
...,...,...
78,integrity of the Board’s independence. Details,"7. \nIs employed, has a material business \nNo..."
79,of companies in which Board members hold,relationship and/or significant shareholding \...
80,Board or Board Committee memberships,in other companies*. Entails other companies \...
81,are available with the Company Secretary for,that have significant shareholding in JKH \nco...
82,"inspection by shareholders, on request.",and/or JKH has a business connection with

Table 43:

,0,1,2,3
0,Report Disclosure,,,
1,MANDATORY PROVISIONS - FULLY COMPLIANT,,,
2,Rule,,Compliance,Reference (within the
3,,,Status,JKH Annual Report)
4,(i),Names of persons who were Directors of the Com...,Yes,Corporate Governance
5,,,,Commentary
6,(ii),Principal activities of the entity and its sub...,Yes,Management Discussion
7,,,,and Analysis
8,(iii),The names and the number of shares held by the...,Yes,
9,,shares and the percentage of such shares held,,
10,(iv),"The float adjusted market capitalisation, publ...",Yes,
11,,shareholders and under which option the Listed...,,
12,,Holding requirement.,,Share Information
13,,The public holding percentage in respect of no...,Not Applicable,
14,(v),A statement of each Director’s holding and Chi...,Yes,
15,,Entity at the beginning and end of each financ...,,
16,(vi),Information pertaining to material foreseeable...,Yes,"Risk, Opportunities and"
17,,,,Internal Controls
18,(vii),Details of material issues pertaining to emplo...,Yes,"Sustainability Integration,"
19,,,,Stakeholder Engagement
20,,,,and Materiality
21,(viii),"Extents, locations, valuations and the number ...",Yes,
22,,,,Group Real Estate Portfolio
23,,investment properties,,
24,(ix),Number of shares representing the Entity’s sta...,Yes,
25,(x),A distribution schedule of the number of holde...,Yes,
26,,,,Share Information
27,,percentage of their total holdings,,
28,(xi),Financial ratios and market price information,Yes,
29,(xii),Significant changes in the Company’s or its su...,Yes,Notes to the Financial
30,,"land, if the value differs substantially from ...",,Statements
31,(xiii),Details of funds raised through a public issue...,Yes,
32,,the year,,Share Information
33,(xiv),Information in respect of Employee Share Owner...,Yes,
34,(xv),Disclosures pertaining to Corporate Governance...,Yes,Corporate Governance
35,,7.10.6 c. of Section 7 of the Listing Rules,,Commentary/Note 44 of
36,(xvi),Related Party transactions exceeding 10% of th...,Yes,the Notes to the Financial
37,,"per audited financial statements, whichever is...",,Statements

Table 44:

,0,1,2
0,,ANNUAL REPORT OF THE BOARD OF DIRECTORS,
1,A final dividend will be paid on or before,STATED CAPITAL,RETIREMENT AND RE-ELECTION OF
2,21 June 2023 to those shareholders on the,Stated Capital as at 31 March 2023 of the,DIRECTORS
3,register as of 31 May 2023.,"Company amounted to Rs.73,188 Mn",Retirement and Re-Election of Directors of the
4,,"(2022 - Rs.73,188 Mn). The movement and",Company as at 31 March 2023 are given in the
5,CAPITAL EXPENDITURE,composition of the Stated Capital is disclosed,Proxy Form.
6,The Company’s and Group’s capital,in the Statement of Changes in Equity and in,
7,"expenditure on property, plant and equipment",Note 34.1 to the Financial Statements.,REVIEW OF THE PERFORMANCE OF THE
8,amounted to Rs.102 Mn (2022 - Rs.14 Mn) and,,BOARD
9,"Rs.7,074 Mn (2022 - Rs.6,627 Mn), respectively,",ISSUE OF UNLISTED CONVERTIBLE,The performance of the board has been
10,and all other related information and,"DEBENTURES TO HWIC ASIA FUND, A","appraised through a formalised process,"
11,movements have been disclosed in Note 22 to,SUBSIDIARY OF FAIRFAX FINANCIAL,where each individual Director anonymously
12,the Financial Statements.,HOLDINGS LIMITED,comments on the dynamics of the Board.
13,,John Keells Holdings PLC raised foreign direct,The process is described in the Corporate
14,Additions of intangible assets of the Company,investments of Rs.27.06 billion by way of an,Governance Commentary section of the
15,and Group during the year amounted to Nil,unlisted convertible debenture issue to HWIC,Annual Report.
16,"(2022 - Rs.30 Mn) and Rs.1,296 Mn (2022 -","Asia Fund, a subsidiary of Fairfax Holdings",
17,"Rs.1,360 Mn), respectively, and all other related","Limited, on 12 August 2022.",BOARD COMMITTEES
18,movements are disclosed in Note 25 to the,,Information relating to members of the
19,Financial Statements.,REVENUE RESERVES,"Audit Committee, Human Resources and"
20,,Revenue reserves as at 31 March 2023 for,"Compensation Committee, Nominations"
21,"VALUATION OF LAND, BUILDINGS AND",the Company and Group amounted to,"Committee, Related Party Transactions Review"
22,INVESTMENT PROPERTIES,"Rs.101,807 Mn (2022 - Rs.90,582 Mn) and",Committee and Project Risk Assessment
23,All land and buildings owned by Group,"Rs.121,743 Mn (2022 - Rs.109,087 Mn),","Committee, including reports of each of the"
24,companies were revalued as at 31 December,respectively. The movement of the revenue,"committees, where applicable, and attendance"
25,2022 and the carrying value amounted to,reserve is disclosed in the Statement of,of Directors for each of the committee
26,"Rs.110,716 Mn (2022 - Rs.101,326 Mn). All",Changes in Equity.,"meetings, are disclosed in the Corporate"
27,information related to revaluation is given in,,Governance Commentary section of the
28,Note 22.3 to the Financial Statements.,SHARE INFORMATION,Annual Report.
29,,The distribution and composition of,
30,"Investment properties of business units, when",shareholders and the information relating,INTERESTS REGISTER AND INTERESTS IN
31,"significantly occupied by Group companies,","to earnings, dividends, net assets, market",CONTRACTS
32,"are classified as property, plant and equipment",value per share and share trading is given,The Company has maintained an Interests
33,in the consolidated financial statements in,in the Share Information section of the,Register as contemplated by the Companies
34,compliance with LKAS 40.,"Annual Report. As additional disclosures, the",Act No 7 of 2007.
35,,Company’s Board of Directors’ (including their,
36,The Group revalued all its investment,"close family members) shareholdings, options",This Annual Report also contains particulars
37,"properties as at 31 December 2022, and the",available under the employee share option,of entries made in the Interests Registers of
38,"carrying value amounted to Rs.33,029 Mn","(ESOP) plans as at 31 March 2023, market",subsidiaries which are public companies or
39,"(2022- Rs.30,608 Mn). All information related","capitalisation, public holding percentage and",private companies which have not dispensed
40,to revaluation of the investment properties,number of public shareholders are given in,with the requirement to maintain an Interests
41,is provided in Note 24 to the Financial,the Share Information section of the Annual,Register as permitted by Section 30 of the
42,Statements.,Report.,Companies Act No 7 of 2007.
43,Details of the Group’s real estate as at 31 March,MAJOR SHAREHOLDERS,The Directors have all made a general
44,"2023, are disclosed in the Group Real Estate",Details of the twenty largest shareholders,disclosure relating to share dealings and
45,Portfolio in the Supplementary Information,of the Company and the percentages held,indemnities and remuneration to the Board
46,section of the Annual Report.,by each of them are disclosed in the Share,of Directors as permitted by Section 192 (2)
47,,Information section of the Annual Report.,of the Companies Act No 7 of 2007 and no
48,INVESTMENTS,,additional interests have been disclosed by
49,Detailed description of the long term,EQUITABLE TREATMENT OF SHAREHOLDERS,any Director. The Interest Register is availab...
50,"investments held as at the reporting date, is",The Company has at all times ensured that all,"the registered head office of the Company, in"
51,"given in Notes 26, 27 and 28 to the Financial",shareholders are treated equitably.,keeping with the requirements of the section
52,Statements.,,119 (1) (d) of the Companies Act No 7 of 2007.
53,,THE BOARD OF DIRECTORS,
54,,The Board of Directors of the Company as at,SHARE DEALINGS
55,,31 March 2023 and their brief profiles are given,"Other than for following entries, particulars of"
56,,in the Corporate Governance section of the,the Company interest register are disclosed in
57,,Annual Report.,the Share Information section of the Annual
58,,,Report.

Table 45:

                                                    0
0   in our audit of the financial statements of th...
1   Key audit matter \nHow our audit addressed the...
2   Our audit procedures were based on the best av...
3   of this report and focused on the valuations p...
4   Property, Plant and Equipment and investment P...
5   engaged by the Group. Our procedures included ...
6   land and buildings carried at fair value. The ...
7   •  Assessed the competency, capability and obj...
8                   engaged by the Group.\nthe Group.
9   • \nRead the external valuer’s report and unde...
10  the approach taken by the valuer in determinin...
11  •  Materiality of the reported fair value of l...
12                                      and building.
13  balances which amounted to Rs.144 Bn and repre...
14  •  Assessed the reasonableness of the signific...
15  valuer and valuation techniques, per perch pri...
16  • \nThe degree of assumptions, judgements and ...
17  used by the valuer in the valuation of each la...
18  uncertainties associated with fair valuation o...
19  We assessed the adequacy of the disclosures ma...
20  to the significant judgements, valuation techn...
21                                   external valuer.
22  Key areas of significant judgments, estimates ...

Table 46:

,0,1
0,"Property, Plant and Equipment amounting to Rs....",of judgments and assessments to estimate the f...
1,represents 31% of total assets of the Group as...,complete the project.
2,This was a key audit matter due to;,• \nPerforming tests of expenditure and alloca...
3,,examination of management’s assessment as to w...
4,• \nThe materiality of the reported balance an...,
5,,the recognition and measurement criteria set f...
6,impairment indicators that may exist due to th...,
7,,of the Group.
8,costs to complete the project and the prevaili...,
9,conditions in the country.,• \nReviewing the project status reports and t...
10,,manager to identify the status of the project ...
11,"• \nThe degree of assumptions, judgements and ...",
12,,costs incurred.
13,associated with deriving the estimated future ...,
14,to ascertain the recoverable amount of the Wat...,• Checking the calculation of the discounted ...
15,,checking the data to relevant underlying accou...

Table 47:

,0,1
0,Key audit matter,How our audit addressed the key audit matter
1,Work In Progress of Waterfront Project,Our procedures performed included;
2,Capital work in progress of Waterfront project...,• Understanding the process followed by the m...
3,"Property, Plant and Equipment amounting to Rs....",of judgments and assessments to estimate the f...
4,represents 31% of total assets of the Group as...,complete the project.
5,This was a key audit matter due to;,• \nPerforming tests of expenditure and alloca...
6,,examination of management’s assessment as to w...
7,• \nThe materiality of the reported balance an...,
8,,the recognition and measurement criteria set f...
9,impairment indicators that may exist due to th...,
10,,of the Group.
11,costs to complete the project and the prevaili...,
12,conditions in the country.,• \nReviewing the project status reports and t...
13,,manager to identify the status of the project ...
14,"• \nThe degree of assumptions, judgements and ...",
15,,costs incurred.
16,associated with deriving the estimated future ...,
17,to ascertain the recoverable amount of the Wat...,• Checking the calculation of the discounted ...
18,,checking the data to relevant underlying accou...
19,,the reasonableness of the significant assumpti...
20,,EBITDA margins and management cost assumptions...
21,,to determine the future recoverable amount of ...
22,,We assessed the adequacy of the Group’s disclo...

Table 48:

,0,1,2,3,4,5
0,For the year ended 31 March,Note,2023,2022,2023,2022
1,In Rs.'000s,,,,,
2,Continuing operations,,,,,
3,Revenue from contracts with customers,,"260,687,372","202,849,175","2,543,712","1,875,722"
4,Revenue from insurance contracts,,"15,952,535","15,225,571",-,-
5,Total revenue,14,"276,639,907","218,074,746","2,543,712","1,875,722"
6,Cost of sales,,"(227,190,277)","(180,430,008)","(1,166,753)","(1,085,049)"
7,Gross profit,,"49,449,630","37,644,738","1,376,959","790,673"
8,Dividend income,15,-,-,"10,635,000","8,007,649"
9,Other operating income,16.1,"3,260,621","2,614,793","41,219","51,344"
10,Selling and distribution expenses,,"(8,266,060)","(5,732,694)",-,-
11,Administrative expenses,,"(21,927,758)","(14,762,643)","(2,087,177)","(1,283,215)"
12,Other operating expenses,16.2,"(9,825,773)","(12,456,008)","(748,154)","(514,478)"
13,Results from operating activities,,"12,690,660","7,308,186","9,217,847","7,051,973"
14,Finance cost,17,"(17,802,868)","(7,034,757)","(8,778,825)","(2,966,139)"
15,Finance income,17,"26,899,776","30,806,179","16,327,902","24,198,282"
16,Change in insurance contract liabilities,36.2,"(7,650,232)","(6,416,299)",-,-
17,Change in fair value of investment property,24,"878,538","(4,084,755)",-,-
18,Share of results of equity accounted investees...,27.3,"7,573,543","6,745,939",-,-
19,Profit before tax,18,"22,589,417","27,324,493","16,766,924","28,284,116"
20,Tax expense,21.1,"(3,693,293)","(6,881,586)","(2,057,640)","(3,902,709)"
21,Profit for the year,,"18,896,124","20,442,907","14,709,284","24,381,407"
22,Attributable to:,,,,,
23,Equity holders of the parent,,"18,173,868","20,212,968",,
24,Non-controlling interests,,"722,256","229,939",,
25,,,"18,896,124","20,442,907",,

Table 49:

,0,1
0,9. \n BASIS OF CONSOLIDATION AND MATERIAL PARTLY,Profit or loss and each component of other com...
1,OWNED SUBSIDIARIES,(OCI) are attributed to the equity holders of ...
2,Accounting policy,"and to the non-controlling interests, even if ..."
3,Basis of consolidation,controlling interests having a deficit balance...
4,The consolidated financial statements comprise...,of the subsidiaries are prepared for the same ...
5,statements of the Group and its subsidiaries a...,"the parent Company, which is 12 months ending ..."
6,period. Control over an investee is achieved w...,consistent accounting policies.
7,"exposed, or has rights, to variable returns fr...",
8,investee and has the ability to affect those r...,Transactions eliminated on Consolidation
9,over the investee.,"All intra-group assets, liabilities, equity, i..."
10,,flows relating to transactions between members...
11,Control over an investee,eliminated in full on consolidation. A change ...
12,"Specifically, the Group controls an investee i...","of a subsidiary, without a loss of control, is..."
13,,transaction.
14,"y\nPower over the investee (i.e., existing rig...",
15,ability to direct the relevant activities of t...,Loss of control
16,,"If the Group loses control over a subsidiary, ..."
17,"y\nExposure, or rights, to variable returns fr...",
18,,"assets (including goodwill), liabilities, non-..."
19,investee,
20,,components of equity while any resultant gain ...
21,y\nThe ability to use its power over the inves...,
22,,the income statement. Any investment retained ...
23,,value. The total profits and losses for the ye...
24,Consolidation of entities in which the Group h...,
25,,its subsidiaries included in consolidation are...
26,majority of voting rights,
27,,income statement and consolidated statement of...
28,When the Group has less than a majority of the...,
29,,income and all assets and liabilities of the C...
30,"of an investee, the Group considers all releva...",
31,,subsidiaries included in consolidation are sho...
32,in assessing whether it has power over an inve...,
33,,Statement of Financial Position.
34,y\nThe contractual arrangement with the other ...,
35,,Non-controlling interest (NCI)
36,investee;,
37,,Non-controlling interest which represents the ...
38,y\nRights arising from other contractual arran...,"and net assets not held by the Group, are show..."
39,,profit for the year in the consolidated income...
40,y\nThe Group’s voting rights and potential vot...,
41,,of comprehensive income and as a component of ...
42,Subsidiaries that are consolidated have been l...,
43,,"consolidated statement of financial position, ..."
44,directory under Supplementary section of the a...,
45,,attributable to the shareholders of the parent.
46,"The following companies, with equity control e...",
47,,The Consolidated Statement of Cash Flow includ...
48,have been consolidated as subsidiaries based o...,
49,,the Company and its subsidiaries.

Table 50:

,0,1
0,"Under Leisure Sector, following companies have...",valued at fair value at the acquisition date. ...
1,owned subsidiaries with effective holding perc...,classified as equity is not remeasured and its...
2,controlling interest ranged from 1.65% - 24.67...,accounted for within equity. Contingent consid...
3,,asset or liability that is a financial instrum...
4,The Leisure Sector subsidiaries include Ahunga...,"SLFRS 9 Financial Instruments, is measured at ..."
5,"Ltd, Asian Hotels and Properties PLC, Beruwala...",in fair value recognised in the Income Stateme...
6,"Ltd, Ceylon Holiday Resorts Ltd, Cinnamon Holi...",SLFRS 9.
7,"World Investments (Pte) Ltd, Habarana Lodge Lt...",
8,"Hikkaduwa Holiday Resorts (Pvt) Ltd, Internati...",Other contingent consideration that is not wit...
9,"Ltd, John Keells Hotels PLC, John Keells Maldi...",measured at fair value at each reporting date ...
10,"Walk Inn Ltd, Nuwara Eliya Holiday Resorts (Pv...",recognised in profit or loss.
11,"Company Ltd, Resort Hotels Ltd, Serene Holiday...",
12,"(Pte) Ltd, Trans Asia Hotels PLC, Travel Club ...","After initial recognition, goodwill is measure..."
13,"Resorts (Pvt) Ltd, Trinco Walk Inn Ltd, Walker...",accumulated impairment losses. Goodwill is rev...
14,Ltd and Yala Village (Pvt) Ltd.,annually or more frequently if events or chang...
15,,indicate that the carrying value may be impaired.
16,Please refer Note 26 for the individual compan...,
17,,"For the purpose of impairment testing, goodwil..."
18,"Accounting judgements,estimates and assumptions","combination is, from the acquisition date, all..."
19,Consolidation of entities in which the Group h...,Group’s cash generating units that are expecte...
20,majority of voting right (de facto control).,"combination, irrespective of whether other ass..."
21,,acquiree are assigned to those units.
22,The Group considers that it controls some subs...,
23,owns less than 50% of the voting rights. This ...,Impairment is determined by assessing the reco...
24,single largest shareholder of those subsidiari...,the cash-generating unit to which the goodwill...
25,remaining equity shares in those subsidiaries ...,recoverable amount of the cash generating unit...
26,"other shareholders, and there is no history of...","amount, an impairment loss is recognised. The ..."
27,collaborating to exercise their votes collecti...,allocated first to reduce the carrying amount ...
28,,to the unit and then to the other assets pro-r...
29,10. \nBUSINESS COMBINATIONS AND ACQUISITIONS O...,of each asset in the unit. Goodwill and fair v...
30,CONTROLLING INTERESTS,the acquisition of a foreign operation are tre...
31,Accounting policy,of the foreign operation and translated at the...
32,Business combinations & goodwill,
33,Business combinations are accounted for using ...,Where goodwill forms part of a cash-generating...
34,of accounting. The Group measures goodwill at ...,"operation within that unit is disposed of, the..."
35,the fair value of the consideration transferre...,with the operation disposed of is included in ...
36,amount of any non-controlling interests in the...,the operation when determining the gain or los...
37,recognised amount (generally fair value) of th...,"operation, goodwill disposed in this circumsta..."
38,"acquired and liabilities assumed, all measured...",the relative values of the operation disposed ...
39,,cash-generating unit retained.
40,When the fair value of the consideration trans...,
41,recognised amount of any non-controlling inter...,Impairment of goodwill
42,lower than the fair value of net assets acquir...,Goodwill is tested for impairment annually (as...
43,immediately in the income statement. The Group...,circumstances indicate that the carrying value...
44,transaction-by-transaction basis whether to me...,Impairment is determined for goodwill by asses...
45,"interests at fair value, or at their proportio...",amount of each cash-generating unit (or group ...
46,"amount of the identifiable net assets, at the ...",to which the goodwill relates. Where the recov...
47,"costs, other than those associated with the is...",generating unit is less than their carrying am...
48,"securities, that the Group incurs in connectio...",recognised. Impairment losses relating to good...
49,combination are expensed as incurred. When the...,future periods.
50,"business, it assesses the financial assets and...",
51,appropriate classification and designation in ...,10.1 \nInvestment in subsidiaries
52,"contractual terms, economic circumstances and ...",Waterfront Properties (Pvt) Ltd (WPL)
53,at the acquisition date. If the business combi...,John Keells Holdings PLC (JKH) further investe...
54,the acquisition date fair value of the acquire...,"- Rs.13,552 Mn) in WPL, a subsidiary of JKH in..."
55,interest in the acquiree is remeasured to fair...,"owning, managing, operating, selling, leasing ..."
56,through profit or loss. Any contingent conside...,multi/mixed use Integrated Resort.
57,by the acquirer will be recognised at fair val...,
58,"Contingent consideration, resulting from busin...",

Table 51:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,,The maximum risk positions of financial assets...,,,,,,,,,,,,,,
1,"collateral, if available). Following table sho...",,,,,,,,,,,,,,,
2,As at 31 March,,,,,,2023,,,,,,2022,,,
3,In Rs.‘000s,Notes,Non-,Cash in,Trade,Short term,Amounts,Total,,Non-,Cash in,Trade,Short term,Amounts,Total,
4,,,current,hand and,and other,investments,due from,,f,current,hand and,and other,investments,due from,,f
5,,,financial,at bank,receivables,,related,,allocation,financial,at bank,receivables,,related,,allocation
6,,,assets,,,,parties,,,assets,,,,parties,,
7,Group,,,,,,,,,,,,,,,
8,Government securities,11.1.2,"45,906,390",-,-,"7,521,144",-,"53,427,534",28%,"31,752,878",-,-,"10,704,129",-,"42,457,007",18%
9,Corporate debt securities,11.1.3,"9,185,289",-,-,"1,653,689",-,"10,838,978",6%,"9,553,315",-,-,"1,454,315",-,"11,007,630",5%
10,Deposits with banks,11.1.4,"803,775",-,-,"69,453,925",-,"70,257,700",37%,"632,491",-,-,"95,936,007",-,"96,569,378",41%
11,Loans to executives,11.1.5,"1,260,602",-,"356,266",-,-,"1,616,868",1%,"1,048,842",-,"326,682",-,-,"1,375,524",1%
12,Loans to life policyholders,11.1.6,"2,199,675",-,-,-,-,"2,199,675",1%,"1,952,394",-,-,-,-,"1,952,394",1%
13,Preference shares,11.1.7,-,-,-,-,-,-,-,"373,701",-,-,-,-,"373,701",0%
14,Interest rate swap,11.1.8,"4,215,838",-,-,-,-,"4,215,838",2%,"2,928,815",-,-,-,-,"2,928,815",1%
15,Trade and other receivables,11.1.9,-,-,"19,940,932",-,-,"19,940,932",11%,-,-,"25,550,066",-,-,"25,550,066",11%
16,Reinsurance receivables,11.1.10,-,-,"590,215",-,-,"590,215",0%,-,-,"1,135,652",-,-,"1,135,652",0%
17,Assets backed securities,11.1.11,"314,276",-,-,-,-,"314,276",0%,"314,304",-,-,-,-,"314,304",0%
18,Premium receivable,11.1.12,-,-,"620,665",-,-,"620,665",0%,-,-,"482,948",-,-,"482,948",0%
19,Amounts due from related parties,11.1.13,-,-,-,-,"317,700","317,700",0%,-,-,-,-,"196,394","196,394",0%
20,Cash in hand and at bank,11.1.14,-,"25,092,977",-,-,-,"25,092,977",14%,-,"52,376,531",-,-,-,"52,376,531",22%
21,Total credit risk exposure,,"63,885,845","25,092,977","21,508,078","78,628,758","317,700","189,433,358",100%,"48,556,740","52,376,531","27,495,348","108,095,331","196,394","236,406,039",100%
22,Financial assets at fair value through P&L,11.3.3.1,-,-,-,"3,593,064",-,,,-,-,-,"2,626,213",-,,
23,Financial assets at fair value through OCI,11.3.3.2,"71,206",-,-,-,-,,,"133,749",-,-,-,-,,
24,Total equity risk exposure,,"71,206",-,-,"3,593,064",-,,,"133,749",-,-,"2,626,213",-,,
25,Total,,"63,957,051","25,092,977","21,508,078","82,221,822","317,700",,,"48,690,489","52,376,531","27,495,348","110,721,544","196,394",,
26,Company,,,,,,,,,,,,,,,
27,Deposits with banks,11.1.4,-,-,-,"57,473,253",-,"57,473,253",80%,-,-,-,"83,972,660",-,"83,972,660",73%
28,Loans to executives,11.1.5,"151,987",-,"20,766",-,-,"172,753",0%,"66,659",-,"23,078",-,-,"89,737",0%
29,Interest rate swap,11.1.8,"4,215,838",-,-,-,-,"4,215,838",6%,"2,928,815",-,-,-,-,"2,928,815",2%
30,Trade and other receivables,11.1.9,-,-,"186,967",-,-,"186,967",0%,-,-,"80,836",-,-,"80,836",0%
31,Amounts due from related parties,11.1.13,-,-,-,-,"1,177,616","1,177,616",2%,-,-,-,-,"660,699","660,699",1%
32,Cash in hand and at bank,11.1.14,-,"8,232,006",-,-,-,"8,232,006",12%,-,"27,362,010",-,-,-,"27,362,010",24%
33,Total credit risk exposure,,"4,367,825","8,232,006","207,733","57,473,253","1,177,616","71,458,433",100%,"2,995,474","27,362,010","103,914","83,972,660","660,699","115,094,757",100%
34,Financial assets at fair value through OCI,11.3.3.2,"37,158",-,-,-,-,,,"87,563",-,-,-,-,,
35,Total equity risk exposure,,"37,158",-,-,-,-,,,"87,563",-,-,-,-,,
36,Total,,"4,404,983","8,232,006","207,733","57,473,253","1,177,616",,,"3,083,037","27,362,010","103,914","83,972,660","660,699",,

Table 52:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,,The maximum risk positions of financial assets...,,,,,,,,,,,,,,
1,"collateral, if available). Following table sho...",,,,,,,,,,,,,,,
2,As at 31 March,,,,,,2023,,,,,,2022,,,
3,In Rs.‘000s,Notes,Non-,Cash in,Trade,Short term,Amounts,Total,,Non-,Cash in,Trade,Short term,Amounts,Total,
4,,,current,hand and,and other,investments,due from,,f,current,hand and,and other,investments,due from,,f
5,,,financial,at bank,receivables,,related,,allocation,financial,at bank,receivables,,related,,allocation
6,,,assets,,,,parties,,,assets,,,,parties,,
7,Group,,,,,,,,,,,,,,,
8,Government securities,11.1.2,"45,906,390",-,-,"7,521,144",-,"53,427,534",28%,"31,752,878",-,-,"10,704,129",-,"42,457,007",18%
9,Corporate debt securities,11.1.3,"9,185,289",-,-,"1,653,689",-,"10,838,978",6%,"9,553,315",-,-,"1,454,315",-,"11,007,630",5%
10,Deposits with banks,11.1.4,"803,775",-,-,"69,453,925",-,"70,257,700",37%,"632,491",-,-,"95,936,007",-,"96,569,378",41%
11,Loans to executives,11.1.5,"1,260,602",-,"356,266",-,-,"1,616,868",1%,"1,048,842",-,"326,682",-,-,"1,375,524",1%
12,Loans to life policyholders,11.1.6,"2,199,675",-,-,-,-,"2,199,675",1%,"1,952,394",-,-,-,-,"1,952,394",1%
13,Preference shares,11.1.7,-,-,-,-,-,-,-,"373,701",-,-,-,-,"373,701",0%
14,Interest rate swap,11.1.8,"4,215,838",-,-,-,-,"4,215,838",2%,"2,928,815",-,-,-,-,"2,928,815",1%
15,Trade and other receivables,11.1.9,-,-,"19,940,932",-,-,"19,940,932",11%,-,-,"25,550,066",-,-,"25,550,066",11%
16,Reinsurance receivables,11.1.10,-,-,"590,215",-,-,"590,215",0%,-,-,"1,135,652",-,-,"1,135,652",0%
17,Assets backed securities,11.1.11,"314,276",-,-,-,-,"314,276",0%,"314,304",-,-,-,-,"314,304",0%
18,Premium receivable,11.1.12,-,-,"620,665",-,-,"620,665",0%,-,-,"482,948",-,-,"482,948",0%
19,Amounts due from related parties,11.1.13,-,-,-,-,"317,700","317,700",0%,-,-,-,-,"196,394","196,394",0%
20,Cash in hand and at bank,11.1.14,-,"25,092,977",-,-,-,"25,092,977",14%,-,"52,376,531",-,-,-,"52,376,531",22%
21,Total credit risk exposure,,"63,885,845","25,092,977","21,508,078","78,628,758","317,700","189,433,358",100%,"48,556,740","52,376,531","27,495,348","108,095,331","196,394","236,406,039",100%
22,Financial assets at fair value through P&L,11.3.3.1,-,-,-,"3,593,064",-,,,-,-,-,"2,626,213",-,,
23,Financial assets at fair value through OCI,11.3.3.2,"71,206",-,-,-,-,,,"133,749",-,-,-,-,,
24,Total equity risk exposure,,"71,206",-,-,"3,593,064",-,,,"133,749",-,-,"2,626,213",-,,
25,Total,,"63,957,051","25,092,977","21,508,078","82,221,822","317,700",,,"48,690,489","52,376,531","27,495,348","110,721,544","196,394",,
26,Company,,,,,,,,,,,,,,,
27,Deposits with banks,11.1.4,-,-,-,"57,473,253",-,"57,473,253",80%,-,-,-,"83,972,660",-,"83,972,660",73%
28,Loans to executives,11.1.5,"151,987",-,"20,766",-,-,"172,753",0%,"66,659",-,"23,078",-,-,"89,737",0%
29,Interest rate swap,11.1.8,"4,215,838",-,-,-,-,"4,215,838",6%,"2,928,815",-,-,-,-,"2,928,815",2%
30,Trade and other receivables,11.1.9,-,-,"186,967",-,-,"186,967",0%,-,-,"80,836",-,-,"80,836",0%
31,Amounts due from related parties,11.1.13,-,-,-,-,"1,177,616","1,177,616",2%,-,-,-,-,"660,699","660,699",1%
32,Cash in hand and at bank,11.1.14,-,"8,232,006",-,-,-,"8,232,006",12%,-,"27,362,010",-,-,-,"27,362,010",24%
33,Total credit risk exposure,,"4,367,825","8,232,006","207,733","57,473,253","1,177,616","71,458,433",100%,"2,995,474","27,362,010","103,914","83,972,660","660,699","115,094,757",100%
34,Financial assets at fair value through OCI,11.3.3.2,"37,158",-,-,-,-,,,"87,563",-,-,-,-,,
35,Total equity risk exposure,,"37,158",-,-,-,-,,,"87,563",-,-,-,-,,
36,Total,,"4,404,983","8,232,006","207,733","57,473,253","1,177,616",,,"3,083,037","27,362,010","103,914","83,972,660","660,699",,

Table 53:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,,The maximum risk positions of financial assets...,,,,,,,,,,,,,,
1,"collateral, if available). Following table sho...",,,,,,,,,,,,,,,
2,As at 31 March,,,,,,2023,,,,,,2022,,,
3,In Rs.‘000s,Notes,Non-,Cash in,Trade,Short term,Amounts,Total,,Non-,Cash in,Trade,Short term,Amounts,Total,
4,,,current,hand and,and other,investments,due from,,f,current,hand and,and other,investments,due from,,f
5,,,financial,at bank,receivables,,related,,allocation,financial,at bank,receivables,,related,,allocation
6,,,assets,,,,parties,,,assets,,,,parties,,
7,Group,,,,,,,,,,,,,,,
8,Government securities,11.1.2,"45,906,390",-,-,"7,521,144",-,"53,427,534",28%,"31,752,878",-,-,"10,704,129",-,"42,457,007",18%
9,Corporate debt securities,11.1.3,"9,185,289",-,-,"1,653,689",-,"10,838,978",6%,"9,553,315",-,-,"1,454,315",-,"11,007,630",5%
10,Deposits with banks,11.1.4,"803,775",-,-,"69,453,925",-,"70,257,700",37%,"632,491",-,-,"95,936,007",-,"96,569,378",41%
11,Loans to executives,11.1.5,"1,260,602",-,"356,266",-,-,"1,616,868",1%,"1,048,842",-,"326,682",-,-,"1,375,524",1%
12,Loans to life policyholders,11.1.6,"2,199,675",-,-,-,-,"2,199,675",1%,"1,952,394",-,-,-,-,"1,952,394",1%
13,Preference shares,11.1.7,-,-,-,-,-,-,-,"373,701",-,-,-,-,"373,701",0%
14,Interest rate swap,11.1.8,"4,215,838",-,-,-,-,"4,215,838",2%,"2,928,815",-,-,-,-,"2,928,815",1%
15,Trade and other receivables,11.1.9,-,-,"19,940,932",-,-,"19,940,932",11%,-,-,"25,550,066",-,-,"25,550,066",11%
16,Reinsurance receivables,11.1.10,-,-,"590,215",-,-,"590,215",0%,-,-,"1,135,652",-,-,"1,135,652",0%
17,Assets backed securities,11.1.11,"314,276",-,-,-,-,"314,276",0%,"314,304",-,-,-,-,"314,304",0%
18,Premium receivable,11.1.12,-,-,"620,665",-,-,"620,665",0%,-,-,"482,948",-,-,"482,948",0%
19,Amounts due from related parties,11.1.13,-,-,-,-,"317,700","317,700",0%,-,-,-,-,"196,394","196,394",0%
20,Cash in hand and at bank,11.1.14,-,"25,092,977",-,-,-,"25,092,977",14%,-,"52,376,531",-,-,-,"52,376,531",22%
21,Total credit risk exposure,,"63,885,845","25,092,977","21,508,078","78,628,758","317,700","189,433,358",100%,"48,556,740","52,376,531","27,495,348","108,095,331","196,394","236,406,039",100%
22,Financial assets at fair value through P&L,11.3.3.1,-,-,-,"3,593,064",-,,,-,-,-,"2,626,213",-,,
23,Financial assets at fair value through OCI,11.3.3.2,"71,206",-,-,-,-,,,"133,749",-,-,-,-,,
24,Total equity risk exposure,,"71,206",-,-,"3,593,064",-,,,"133,749",-,-,"2,626,213",-,,
25,Total,,"63,957,051","25,092,977","21,508,078","82,221,822","317,700",,,"48,690,489","52,376,531","27,495,348","110,721,544","196,394",,
26,Company,,,,,,,,,,,,,,,
27,Deposits with banks,11.1.4,-,-,-,"57,473,253",-,"57,473,253",80%,-,-,-,"83,972,660",-,"83,972,660",73%
28,Loans to executives,11.1.5,"151,987",-,"20,766",-,-,"172,753",0%,"66,659",-,"23,078",-,-,"89,737",0%
29,Interest rate swap,11.1.8,"4,215,838",-,-,-,-,"4,215,838",6%,"2,928,815",-,-,-,-,"2,928,815",2%
30,Trade and other receivables,11.1.9,-,-,"186,967",-,-,"186,967",0%,-,-,"80,836",-,-,"80,836",0%
31,Amounts due from related parties,11.1.13,-,-,-,-,"1,177,616","1,177,616",2%,-,-,-,-,"660,699","660,699",1%
32,Cash in hand and at bank,11.1.14,-,"8,232,006",-,-,-,"8,232,006",12%,-,"27,362,010",-,-,-,"27,362,010",24%
33,Total credit risk exposure,,"4,367,825","8,232,006","207,733","57,473,253","1,177,616","71,458,433",100%,"2,995,474","27,362,010","103,914","83,972,660","660,699","115,094,757",100%
34,Financial assets at fair value through OCI,11.3.3.2,"37,158",-,-,-,-,,,"87,563",-,-,-,-,,
35,Total equity risk exposure,,"37,158",-,-,-,-,,,"87,563",-,-,-,-,,
36,Total,,"4,404,983","8,232,006","207,733","57,473,253","1,177,616",,,"3,083,037","27,362,010","103,914","83,972,660","660,699",,

Table 54:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,,The maximum risk positions of financial assets...,,,,,,,,,,,,,,
1,"collateral, if available). Following table sho...",,,,,,,,,,,,,,,
2,As at 31 March,,,,,,2023,,,,,,2022,,,
3,In Rs.‘000s,Notes,Non-,Cash in,Trade,Short term,Amounts,Total,,Non-,Cash in,Trade,Short term,Amounts,Total,
4,,,current,hand and,and other,investments,due from,,f,current,hand and,and other,investments,due from,,f
5,,,financial,at bank,receivables,,related,,allocation,financial,at bank,receivables,,related,,allocation
6,,,assets,,,,parties,,,assets,,,,parties,,
7,Group,,,,,,,,,,,,,,,
8,Government securities,11.1.2,"45,906,390",-,-,"7,521,144",-,"53,427,534",28%,"31,752,878",-,-,"10,704,129",-,"42,457,007",18%
9,Corporate debt securities,11.1.3,"9,185,289",-,-,"1,653,689",-,"10,838,978",6%,"9,553,315",-,-,"1,454,315",-,"11,007,630",5%
10,Deposits with banks,11.1.4,"803,775",-,-,"69,453,925",-,"70,257,700",37%,"632,491",-,-,"95,936,007",-,"96,569,378",41%
11,Loans to executives,11.1.5,"1,260,602",-,"356,266",-,-,"1,616,868",1%,"1,048,842",-,"326,682",-,-,"1,375,524",1%
12,Loans to life policyholders,11.1.6,"2,199,675",-,-,-,-,"2,199,675",1%,"1,952,394",-,-,-,-,"1,952,394",1%
13,Preference shares,11.1.7,-,-,-,-,-,-,-,"373,701",-,-,-,-,"373,701",0%
14,Interest rate swap,11.1.8,"4,215,838",-,-,-,-,"4,215,838",2%,"2,928,815",-,-,-,-,"2,928,815",1%
15,Trade and other receivables,11.1.9,-,-,"19,940,932",-,-,"19,940,932",11%,-,-,"25,550,066",-,-,"25,550,066",11%
16,Reinsurance receivables,11.1.10,-,-,"590,215",-,-,"590,215",0%,-,-,"1,135,652",-,-,"1,135,652",0%
17,Assets backed securities,11.1.11,"314,276",-,-,-,-,"314,276",0%,"314,304",-,-,-,-,"314,304",0%
18,Premium receivable,11.1.12,-,-,"620,665",-,-,"620,665",0%,-,-,"482,948",-,-,"482,948",0%
19,Amounts due from related parties,11.1.13,-,-,-,-,"317,700","317,700",0%,-,-,-,-,"196,394","196,394",0%
20,Cash in hand and at bank,11.1.14,-,"25,092,977",-,-,-,"25,092,977",14%,-,"52,376,531",-,-,-,"52,376,531",22%
21,Total credit risk exposure,,"63,885,845","25,092,977","21,508,078","78,628,758","317,700","189,433,358",100%,"48,556,740","52,376,531","27,495,348","108,095,331","196,394","236,406,039",100%
22,Financial assets at fair value through P&L,11.3.3.1,-,-,-,"3,593,064",-,,,-,-,-,"2,626,213",-,,
23,Financial assets at fair value through OCI,11.3.3.2,"71,206",-,-,-,-,,,"133,749",-,-,-,-,,
24,Total equity risk exposure,,"71,206",-,-,"3,593,064",-,,,"133,749",-,-,"2,626,213",-,,
25,Total,,"63,957,051","25,092,977","21,508,078","82,221,822","317,700",,,"48,690,489","52,376,531","27,495,348","110,721,544","196,394",,
26,Company,,,,,,,,,,,,,,,
27,Deposits with banks,11.1.4,-,-,-,"57,473,253",-,"57,473,253",80%,-,-,-,"83,972,660",-,"83,972,660",73%
28,Loans to executives,11.1.5,"151,987",-,"20,766",-,-,"172,753",0%,"66,659",-,"23,078",-,-,"89,737",0%
29,Interest rate swap,11.1.8,"4,215,838",-,-,-,-,"4,215,838",6%,"2,928,815",-,-,-,-,"2,928,815",2%
30,Trade and other receivables,11.1.9,-,-,"186,967",-,-,"186,967",0%,-,-,"80,836",-,-,"80,836",0%
31,Amounts due from related parties,11.1.13,-,-,-,-,"1,177,616","1,177,616",2%,-,-,-,-,"660,699","660,699",1%
32,Cash in hand and at bank,11.1.14,-,"8,232,006",-,-,-,"8,232,006",12%,-,"27,362,010",-,-,-,"27,362,010",24%
33,Total credit risk exposure,,"4,367,825","8,232,006","207,733","57,473,253","1,177,616","71,458,433",100%,"2,995,474","27,362,010","103,914","83,972,660","660,699","115,094,757",100%
34,Financial assets at fair value through OCI,11.3.3.2,"37,158",-,-,-,-,,,"87,563",-,-,-,-,,
35,Total equity risk exposure,,"37,158",-,-,-,-,,,"87,563",-,-,-,-,,
36,Total,,"4,404,983","8,232,006","207,733","57,473,253","1,177,616",,,"3,083,037","27,362,010","103,914","83,972,660","660,699",,

Table 55:

                 0            1      2            3     4
0                                GROUP
1   As at 31 March         2023                2022
2    Fitch ratings  In Rs.’000s      %  In Rs.’000s     %
3               AA            -      -      959,461    9%
4              AA-            -      -      863,526    8%
5               A+      607,585     6%      895,622    8%
6                A    1,568,959    14%    2,407,965   22%
7               A-      829,469     8%    2,179,836   20%
8             BBB+    2,596,193    32%    3,212,371   29%
9              BBB    3,471,458    24%      114,312    1%
10            BBB-    1,549,735    14%            -     -
11              B-            -      -      158,934    1%
12              CC      215,579     2%      215,603    2%
13           Total   10,838,978   100%   11,007,630  100%

Table 56:

,0,1,2,3,4,5,6,7,8
0,,,GROUP,,,,COMPANY,,
1,As at 31 March,2023,,2022,,2023,,2022,
2,Fitch ratings,In Rs.,%,In Rs.,%,In Rs.,%,In Rs.,%
3,,’000s,,’000s,,’000s,,’000s,
4,AA-,"2,988,505",4%,"80,016,461",83%,-,-,"54,088,324",64%
5,A+,-,-,"1,120,113",1%,-,-,-,-
6,A,"44,491,946",63%,"6,187,339",7%,"35,629,545",62%,"21,689,059",26%
7,A-,"22,777,249",33%,"985,225",1%,"21,843,708",38%,-,-
8,CC,-,-,"8,260,240",8%,-,-,"8,195,277",10%
9,Total,"70,257,700",100%,"96,569,378",100%,"57,473,253",100%,"83,972,660",100%

Table 57:

                                 0          1      2          3     4
0                                              GROUP
1                   As at 31 March       2023              2022
2                                    Rs.’000s      %   Rs.’000s     %
3             Application Software     49,812     1%     25,258    1%
4                            Banks    396,380    11%    369,346   14%
5                    Capital Goods    906,535    25%    972,803   37%
6      Consumer Durables & Apparel    398,982    11%    653,667   24%
7                Consumer Services    194,454     5%     52,532    2%
8                           Energy    315,951    10%          -     -
9         Food & Staples Retailing     13,018     0%          -     -
10         Food Beverage & Tobacco    440,292    12%    197,718    8%
11   Household & Personal Products          -      -      4,527    0%
12  Investment Banking & Brokerage     36,709     1%          -     -
13                       Materials    641,028    18%     69,533    3%
14                     Real Estate     16,063     0%          -     -
15      Telecommunication Services    183,840     6%    259,743   10%
16                  Transportation          -      -     21,086    1%
17                                  3,593,064   100%  2,626,213  100%

Table 58:

,0,1,2,3
0,,,GROUP,
1,For the year ended 31 March,Change in year-end,Effect on profit,Effect on equity
2,,market price index,before tax Rs.‘000s,Rs.‘000s
3,2023,+10%,"359,306",-
4,,-10%,"(359,306)",-
5,2022,+28%,"735,340",-
6,,- 28%,"(735,340)",-

Table 59:

,0,1
0,,GROUP\nCOMPANY
1,For the year ended 31 March,Note\n2023\n2022\n2023\n2022
2,In Rs.'000s,
3,Timing of revenue recognition,
4,Goods transferred at a point in time,"213,110,409 \n 179,095,601 \n - \n -"
5,Services transferred over time,"47,576,963 \n 23,753,574 \n 2,543,712 \n 1,875..."
6,Total revenue from contracts with customers,"14.1.1\n 260,687,372 \n 202,849,175 \n 2,543,7..."
7,Revenue from insurance contracts,"14.1.2\n 15,952,535 \n 15,225,571 \n - \n -"
8,Total revenue,"276,639,907 \n 218,074,746 \n 2,543,712 \n 1,8..."
9,For the better understanding of the Industry s...,
10,14.3 \nReconciliation of revenue,Contract liabilities
11,Reconciliation between Revenue from contracts ...,Contract liabilities are the Group's obligatio...
12,and revenue for each reportable segment has be...,services to a customer for which the Group has...
13,operating segment information section.,(or the amount is due) from the customer. Cont...
14,,long-term advances received to deliver goods a...
15,14.4 Contract balances,advances received to render certain services a...
16,Contract assets,"allocated to unexpired service warranties, and..."
17,Contract assets are the Group’s right to consi...,redeemed.
18,goods or services that the Group has transferr...,
19,rights that are conditional on some criteria o...,
20,"time. Upon satisfaction of the conditions, the...",
21,contract assets are reclassified to trade rece...,

Table 60:

,0,1
0,Dividend income from investments in subsidiari...,"10,635,000\n 8,007,649"
1,16. \nOTHER OPERATING INCOME AND OTHER OPERAT...,Gains and losses arising from activities incid...
2,Accounting policy,generating activities and those arising from a...
3,Gains and losses,"transactions, which are not material are aggre..."
4,Net gains and losses of a revenue nature arisi...,presented on a net basis.
5,"property, plant and equipment and other non-cu...",
6,,Any losses arising from guaranteed rentals are...
7,"investments in subsidiaries, joint ventures an...",
8,,year of incurring the same. A provision is rec...
9,"in the income statement, after deducting from ...",
10,,indicates a loss.
11,the carrying amount of such assets and the rel...,
12,,Other income and expenses
13,,Other income and expenses are recognised on an...

Table 61:

,0,1,2,3
0,,NOTES TO THE FINANCIAL STATEMENTS,,
1,21.,TAXES (CONTD.),,
2,,21.10 Income tax rates of off-shore subsidiaries,,
3,Country of incorporation,,Company,Rate
4,India,,John Keells Foods India (Pvt)Ltd,30.9%
5,Mauritius,,John Keells BPO International (Pvt) Ltd,15%
6,,,John Keells BPO Holdings (Pvt) Ltd,15%
7,Republic of Maldives,,Fantasea World Investments (Pte) Ltd,15%
8,,,Travel Club (Pte) Ltd,15%
9,,,Tranqulity (Pte) Ltd,15%
10,,,John Keells Maldivian Resorts (Pte) Ltd,15%
11,,,Mack Air Services Maldives (Pte) Ltd,15%
12,Singapore,,John Keells Singapore (Pte) Ltd,17% (Max)

Table 62:

,0,1
0,Singapore\nJohn Keells Singapore (Pte) Ltd,17% (Max)
1,"22. \nPROPERTY, PLANT AND EQUIPMENT",Land and buildings are measured at fair value ...
2,Accounting policy,depreciation on buildings and impairment charg...
3,Basis of recognition,date of the revaluation.
4,"Property, plant and equipment are recognised i...",
5,economic benefits associated with the asset wi...,"The carrying values of property, plant and equ..."
6,the cost of the asset can be reliably measured.,impairment when events or changes in circumsta...
7,,carrying value may not be recoverable.
8,Basis of measurement,
9,"Property, plant and equipment except for land ...",Any revaluation surplus is recognised in other...
10,at cost less accumulated depreciation and any ...,and accumulated in equity under the asset reva...
11,loss. Such cost includes the cost of replacing...,to the extent that it reverses a revaluation d...
12,plant and equipment and borrowing costs for lo...,"previously recognised in the income statement,..."
13,projects if the recognition criteria are met. ...,increase is recognised in the income statement.
14,plant and equipment are required to be replace...,A revaluation deficit is recognised in the inc...
15,"derecognises the replaced part, and recognises...",to the extent that it offsets an existing surp...
16,own associated useful life and depreciation. L...,recognised in the asset revaluation reserve.
17,"inspection is performed, its cost is recognise...",

Table 63:

,0,1,2,3,4,5,6,7
0,,,,,square foot,rate,,
1,Freehold property,,,,,,,
2,Ahungalla Holiday Resort Ltd,S Fernando,DCC,"Rs.275,000 -",-,,-,Positive
3,,,,"Rs.440,000",,,,
4,Asian Hotels and Properties PLC,P B Kalugalagedara,IM,-,-,,6%,Negative
5,Ceylon Cold Stores PLC,-do-,OMV,"Rs.1,800,000","Rs.2,000",,-,Positive
6,Facets (Pvt) Ltd,S Fernando,DCC,"Rs.525,000",-,,-,Positive
7,Glennie Properties (Pvt) Ltd,P B Kalugalagedara,OMV,"Rs.16,000,000",-,,-,Positive
8,John Keells Properties Ja-Ela (Pvt) Ltd,-do-,DCC,"Rs.1,250,000","Rs.4,750",,-,Positive
9,John Keells PLC,-do-,OMV,"Rs.800,000",-,,-,Positive
10,J K Thudella Properties (Pvt) Ltd,P P T Mohideen,OMV,"Rs.300,000",-,,-,Positive
11,Keells Realtors Ltd,P B Kalugalagedara,DCC,"Rs.1,600,000 -",Rs.900,,-,Positive
12,,,,"Rs.2,500,000",,,,

Table 64:

,0,1,2,3,4,5,6
0,,shares,holding %,shares,holding %,In Rs.‘000s,In Rs.‘000s
1,Cost,,,,,,
2,Asian Hotels and Properties PLC,"347,824,190",78.56%,"347,824,190",78.56%,"5,377,344","5,378,525"
3,Ceylon Cold Stores PLC,"773,212,040",81.36%,"671,558,120",70.66%,"1,709,632","1,682,346"
4,John Keells Hotels PLC,"1,169,598,478",80.32%,"1,169,598,478",80.32%,"7,102,140","7,102,140"
5,John Keells PLC,"52,834,784",86.90%,"52,834,784",86.90%,"491,354","488,005"
6,Keells Food Products PLC,"22,937,250",88.63%,"20,364,054",79.86%,"1,241,989","1,241,876"
7,Tea Smallholder Factories PLC,"11,286,000",37.62%,"11,286,000",37.62%,"66,809","66,809"
8,Trans Asia Hotels PLC,"184,107,284",82.74%,"97,284,256",48.64%,"1,619,225","1,617,229"
9,Union Assurance PLC,"530,357,150",90.00%,"530,357,150",90.00%,"2,691,005","2,679,379"
10,,,,,,"20,299,498","20,256,309"

Table 65:

,0,1,2,3,4,5,6
0,,Number of,Effective,Number of,Effective,Cost,Cost
1,,shares,holding %,shares,holding %,In Rs.‘000s,In Rs.‘000s
2,Ahungalla Holiday Resorts (Pvt) Ltd,"13,275,000",80.32,-,-,-,-
3,Beruwala Holiday Resorts (Pvt ) Ltd,"219,725,653",79.78,-,-,"3,586","3,586"
4,British Overseas (Pvt) Ltd,61,61.00,61,61.00,-,-
5,Ceylon Holidays Resorts Ltd,"18,260,784",79.60,-,-,"3,893","3,887"
6,Cinnamon Hotel Management Ltd,"1,000,000",100.00,"1,000,000",100.00,"500,486","455,075"
7,Cinnamon Hotel Management International (Pvt) Ltd,"50,000",100.00,-,-,-,-
8,Cinnamon Holiday (Pvt) Ltd,"20,000",80.32,-,-,-,-
9,Facets (Pvt) Ltd,"15,000",100.00,"15,000",100.00,-,-
10,Fantasea World Investments (Pte) Ltd,"7,299",80.32,-,-,"4,908","4,738"
11,Glennie Properties (Pvt) Ltd,"16,386,140",100.00,"16,386,140",100.00,"163,861","163,861"
12,Habarana Lodge Ltd,"12,981,548",78.99,-,-,"4,312","4,096"
13,Habarana Walk Inn Ltd,"4,321,381",79.34,-,-,"2,719","2,719"
14,Hikkaduwa Holiday Resorts (Pvt) Ltd,"107,596,700",79.60,-,-,"2,874","2,621"
15,Infomate (Pvt) Ltd,"2,000,000",100.00,"2,000,000",100.00,"43,773","41,395"
16,International Tourists and Hoteliers Ltd,"38,490,901",79.78,-,-,-,-
17,J K Land (Pvt) Ltd,"2,302,760,246",,"100.00 2,302,760,246",100.00,"24,964,639","24,964,639"
18,J K Packaging (Pvt) Ltd,"1,450,000",100.00,"1,450,000",100.00,-,-
19,J K Thudella Properties (Pvt) Ltd,"45,346,760",100.00,-,-,-,-
20,JayKay Marketing Services (Pvt) Ltd,"202,239,025",81.36,-,-,"258,114","226,222"
21,John Keells BPO Holdings (Pvt) Ltd,"19,000,000",100.00,-,-,-,-
22,John Keells BPO International (Pvt) Ltd,"1,500,000,000",100.00,-,-,-,-
23,John Keells BPO Solutions Lanka (Pvt) Ltd,"32,843,578",100.00,-,-,-,-
24,John Keells Information Technology (Pvt) Ltd,"9,650,000",100.00,"9,650,000",100.00,"124,665","123,346"
25,John Keells Foods India (Pvt) Ltd,"8,999,990",88.63,-,-,-,-
26,John Keells International (Pvt) Ltd,"199,160,000",100.00,"199,160,000",100.00,"676,747","673,526"
27,John Keells Logistics (Pvt) Ltd,"19,999,998",100.00,"19,999,998",100.00,"232,048","229,930"
28,John Keells Maldivian Resorts (Pte) Ltd,"49,044,238",80.32,-,-,"18,299","18,152"
29,John Keells Office Automation (Pvt) Ltd,"500,000",100.00,"500,000",100.00,"74,813","71,170"
30,John Keells Properties (Pvt) Ltd,"101,804",100.00,"101,804",100.00,-,-
31,John Keells Properties Ja-Ela (Pvt) Ltd,"95,436,000",100.00,-,-,-,-
32,John Keells Residential Properties (Pvt) Ltd,"2,081,698",100.00,"2,081,698",100.00,"20,817","20,817"
33,John Keells Singapore (Pte) Ltd,"160,000",80.00,"160,000",80.00,"4,209","4,209"
34,John Keells Stock Brokers (Pvt) Ltd,"1,500,000",90.04,"360,000",24.00,"90,902","85,187"
35,John Keells Teas (Pvt) Ltd,"12,000",100.00,"12,000",100.00,"26,599","22,424"
36,John Keells Warehousing (Pvt) Ltd,"12,000,000",86.90,-,-,"5,039","5,034"
37,Kandy Walk Inn Ltd,"6,165,484",79.03,-,-,"4,094","4,089"
38,Keells Consultants (Pvt) Ltd,928,100.00,928,100.00,"2,070","2,066"
39,Keells Realtors Ltd,"7,500,000",95.81,"5,100,000",40.00,"119,124","119,124"
40,Keells Shipping (Pvt) Ltd,"50,000",100.00,"50,000",100.00,-,-
41,Lanka Marine Services (Pvt) Ltd,"34,805,470",99.44,"34,805,470",99.44,"1,418,844","1,409,828"
42,Logipark International (Pvt) Ltd,"60,407,698",81.36,-,-,284,-
43,Mack Air (Pvt) Ltd,"89,260",100.00,"89,260",100.00,"40,405","38,149"
44,Mack Air Services Maldives (Pvt) Ltd,"4,900",49.00,"4,700",47.00,"2,022","2,022"
45,Mack Freight Lanka (Pvt) Ltd,"13,000,000",100.00,"13,000,000",100.00,"3,015","2,268"
46,Mackinnon Keells Ltd,"31,966,951",100.00,"31,966,951",100.00,"670,166","670,166"
47,Mackinnon Mackenzie and Company (Shipping) Ltd,"139,092",100.00,"139,092",100.00,"65,844","65,850"

Table 66:

,0,1,2,3,4,5,6
0,As at 31 March,2023,,,2023,,2022
1,,Number of,Effective,Number of,Effective,Cost,Cost
2,,shares,holding %,shares,holding %,In Rs.‘000s,In Rs.‘000s
3,Mackinnon Mackenzie and Company of (Ceylon) Ltd,"1,244",100.00,"1,244",100.00,"29,122","29,122"
4,Mackinnons Travels (Pvt) Ltd,"499,996",100.00,"499,996",100.00,"31,853","31,150"
5,Mortlake (Pvt) Ltd,43,100.00,43,100.00,"20,000","20,000"
6,Nuwara Eliya Holiday Resorts (Pvt) Ltd,"31,606,252",80.32,-,-,-,-
7,Rajawella Holdings Ltd,"13,063,936",49.85,"11,573,339",45.18,"801,707","801,707"
8,Rajawella Hotels Company Ltd,"3,327,595",80.32,-,-,-,-
9,Resort Hotels Ltd,"639,421",79.89,-,-,-,-
10,The Colombo Ice Company (Pvt) Ltd,"169,999,999",81.36,-,-,"1,365","1,155"
11,Tranquility (Pte) Ltd,"637,499",80.32,-,-,"5,879","5,702"
12,Trans-ware Logistics (Pvt) Ltd,"5,539,929",100.00,"5,539,929",100.00,"58,983","58,983"
13,Travel Club (Pte) Ltd,"29,059",80.32,-,-,"3,693","3,690"
14,Trinco Holiday Resorts (Pvt) Ltd,"8,120,005",80.32,-,-,"3,628","3,623"
15,Trinco Walk Inn Ltd,"3,000,007",80.32,-,-,-,-
16,Vauxhall Land Developments (Pvt) Ltd,"2,171,655,391",100.00,-,-,-,-
17,Walkers Tours Ltd,"3,737,634",98.51,"3,737,634",98.05,"200,041","195,291"
18,Waterfront Properties (Pvt) Ltd,"13,996,538,919",,"99.10 13,265,614,492",94.78,"132,745,038","64,169,906"
19,Waterfront Properties (Pvt) Ltd - Preference s...,"1,234,827,544",-,"1,234,827,544",-,"12,348,275",-
20,Whittall Boustead (Pvt) Ltd,"5,341,105",100.00,"5,341,105",100.00,"1,689,049","1,668,721"
21,Whittall Boustead (Travel) Ltd,"22,452,271",100.00,"22,452,271",100.00,"280,558","278,289"
22,Wirawila Walk Inn Ltd,"2,012,822",80.32,-,-,-,-
23,Yala Village (Pvt) Ltd,"28,268,000",75.33,-,-,"2,752","2,752"
24,Yala Village (Pvt) Ltd- Non voting preference ...,"10,000,000",-,-,-,-,-
25,,,,,,"177,775,113","96,710,286"

Table 67:

,0,1
0,27. \nINVESTMENT IN EQUITY ACCOUNTED INVESTEES,The income statement reflects the Group’s shar...
1,Accounting policy,operations of the associate or joint venture. ...
2,An associate is an entity over which the Group...,investees is presented as part of the Group’s ...
3,Significant influence is the power to particip...,has been a change recognised directly in the e...
4,"operating policy decisions of the investee, bu...","or joint venture, the Group recognises its sha..."
...,...,...
59,for using the equity method. Under the equity ...,ventures using their corresponding/matching 12...
60,in an associate or a joint venture is initiall...,"period. In the case of associates, where the r..."
61,carrying amount of the investment is adjusted ...,"to Group reporting dates, adjustments are made..."
62,the Group’s share of net assets of the associa...,transactions or events up to 31 March.
63,acquisition date. Goodwill relating to the ass...,

Table 68:

,0,1,2,3,4,5,6,7,8
0,,shares,Holding,In Rs.,In Rs.,shares,Holding,In Rs.,In Rs.
1,,,%,‘000s,‘000s,,%,‘000s,‘000s
2,27.1 \nInvestments in joint ventures,,,,,,,,
3,Braybrooke Residential Properties (Pvt) Ltd,102,50.00,"1,804,500","1,804,500",-,-,-,-
4,DHL Keells (Pvt) Ltd,"1,000,000",50.00,"10,000","10,000","1,000,000",50.00,"10,000","10,000"
5,Inchcape Mackinnon Mackenzie Shipping (Pvt),"164,520",60.00,"16,452","16,452","164,520",60.00,"16,452","16,452"
6,Ltd,,,,,,,,
7,Sentinel Reality (Pvt) Ltd,"6,958,469",40.16,"65,768","64,949",-,-,-,-
8,27.2 \nInvestments in associates,,,,,,,,
9,Quoted,,,,,,,,
10,Nations Trust Bank PLC- Voting shares,"81,453,184",29.49,"2,215,746","1,954,510","54,483,737",19.72,"1,542,220","1,367,480"
11,Nations Trust Bank PLC- Non voting shares,"22,599,226",52.10,"1,900,681","1,827,923","17,926,596",41.33,"1,397,585","1,339,871"
12,Unquoted,,,,,,,,
13,Capitol Hotel Holdings (Pvt) Ltd,"3,249,232",19.47,"325,483","325,483","3,254,832",19.47,"325,483","325,483"
14,Colombo West International Terminal (Pvt) Ltd,"55,792,426",34.00,"5,579,243","2,855,970","55,792,426",34.00,"5,579,243","2,855,969"
15,Fairfirst Insurance Ltd,"68,902,870",19.80,"689,718","689,718",-,-,-,-
16,Indra Hotels and Resorts (Pvt) Ltd,"67,050,025",32.13,"670,742","670,742",-,-,-,-
17,Maersk Lanka (Pvt) Ltd,"30,000",30.00,150,150,"30,000",30.00,150,150
18,Saffron Aviation (Pvt) Ltd,"24,887,160",40.00,"248,872","248,872","24,887,160",40.00,-,-
19,Saffron Aviation (Pvt) Ltd - Preference shares,"135,530,835",-,"506,247","506,247","135,530,835",-,-,-
20,South Asia Gateway Terminals (Pvt) Ltd,"159,826,750",42.19,"7,346,367","7,346,367","159,826,750",42.19,"7,346,367","7,346,367"
21,Cumulative profit accruing to the Group net of,-,-,"6,088,033","6,194,213",-,-,-,-
22,dividend,,,,,,,,
23,Share of net assets of equity accounted,-,-,"11,018,144","9,349,460",-,-,-,-
24,investees,,,,,,,,
25,,-,-,"38,486,146","33,865,556",,,"16,217,500","13,261,772"

Table 69:

,0,1,2,3,4,5,6,7,8
0,As at/year ended 31 March,2023,2022,2023,2022,2023,2022,2023,2022
1,In Rs.‘000s,,,,,,,,
2,Group share of;,,,,,,,,
3,Revenue,"14,382,232","8,103,449","13,363,535","9,544,444","7,092,226","8,633,085","34,837,993","26,280,978"
4,Operating expenses including,"(6,712,293)","(4,360,150)","(8,369,466)","(6,530,011)","(6,742,137)","(7,194,726)","(21,823,896)","(18,084,887)"
5,cost of sales,,,,,,,,
6,Net finance income,"93,393","151,165","282,176","(45,422)","(625,147)","(107,069)","(249,578)","(1,326)"
7,Tax expense,"(3,092,315)","(491,854)","(1,817,599)","(579,322)","(281,062)","(377,650)","(5,190,976)","(1,448,826)"
8,Share of results of equity,"4,671,017","3,402,610","3,458,646","2,389,689","(556,120)","953,640","7,573,543","6,745,939"
9,accounted investees,,,,,,,,
10,Other comprehensive income,"913,548","4,448,407","748,850","(466,783)","(21,415)","(3,033)","1,640,983","3,978,591"
11,Total Comprehensive Income,"5,584,565","7,851,017","4,207,496","1,922,906","(577,535)","950,607","9,214,526","10,724,530"
12,Group share of;,,,,,,,,
13,Total assets,"14,954,279","16,226,919","168,098,266","169,020,223","15,468,925","12,522,508","198,521,470","197,769,650"
14,Total liabilities,"(4,616,383)","(5,230,466)","(143,023,128)","(149,888,167)","(12,574,972)",,"(8,964,620) (160,214,483) (164,083,253)",
15,Net assets,"10,337,896","10,996,453","25,075,138","19,132,056","2,893,953","3,557,888","38,306,987","33,686,397"
16,Goodwill,-,-,"165,899","165,899","13,260","13,260","179,159","179,159"
17,,"10,337,896","10,996,453","25,241,037","19,297,955","2,907,213","3,571,148","38,486,146","33,865,556"
18,Capital commitments,-,-,-,-,"3,447,202","4,019,277","3,447,202","4,019,277"
19,Other commitments and,-,-,"82,700,599","78,043,531",-,-,"82,700,599","78,043,531"
20,Guarantees,,,,,,,,

Table 70:

,0,1
0,NOTES TO THE FINANCIAL STATEMENTS,
1,34. \nSTATED CAPITAL AND OTHER COMPONENTS OF ...,The cost of equity-settled transactions is rec...
2,(CONTD.),a corresponding increase in other capital rese...
3,The revaluation reserve consists of the net su...,period in which the performance and service co...
4,"property, plant and equipment and present valu...",The cumulative expense recognised for equity-s...
...,...,...
67,"based payment transactions, whereby employees ...",
68,,cash settlement for these share options.
69,consideration for equity instruments (equity-s...,
70,The Group applies SLFRS 2 Share Based Payments...,
71,employee remuneration in the form of shares fr...,

Table 71:

,0,1,2,3,4,5
0,,,,COMPANY,,
1,As at 31 March,2023,2022,2021,2020,2019
2,,Plan no 11,Plan no 10,Plan no 10,Plan no 10,Plan no 9
3,,award 1,award 3,award 2,award 1,award 3
4,Dividend yield (%),2.90,3.28,3.87,3.62,3.76
5,Expected volatility (%),24.15,22.37,21.35,17.47,17.77
6,Risk free interest rate (%),23.10,8.87,6.44,9.83,10.09
7,Expected life of share options (Years),5,5,5,5,5
8,Weighted average share price at the grant date...,119.85,132.63,134.74,138.70,154.10
9,Weighted average remaining contractual life fo...,3,3,3,3,3
10,(Years),,,,,
11,Weighted average fair value of options granted...,39.95,44.21,44.91,46.23,51.37
12,Exercise price for options outstanding at the ...,121.91,136.64,132.86,136.97,154.10
13,Exercise price for options outstanding at the ...,121.91,136.64,132.86,136.97,154.14
14,March 2023),,,,,

Table 72:

,0,1
0,Discretionary participating features (DPF),Estimates are also made for future investment ...
1,"DPF is a contractual right to receive, as a su...",assets backing Life Insurance contracts. These...
2,"benefits, additional benefits that;","current market returns, as well as expectation..."
3,,and financial developments. During the last ye...
4,• are likely to be a significant portion of ...,
...,...,...
79,,December 2015. This is calculated for Particip...
80,"changes to the life style, which could result ...",
81,,"participating funds, separately. Above basis i..."
82,expected future mortality exposure.,
83,,One - off Surplus’ calculation basis provided ...

Table 73:

,0,1,2,3,4
0,38.2 Employee defined benefit plan - gratuity,,,,
1,,GROUP,,COMPANY,
2,As at 31 March,2023,2022,2023,2022
3,In Rs.'000s,,,,
4,At the beginning of the year,"2,439,021","2,330,114","146,903","123,194"
5,Current service cost,"222,064","241,043","15,205","11,678"
6,Past service cost,-,"(15,538)",-,"(1,092)"
7,Transfers,-,-,-,891
8,Interest cost on benefit obligation,"203,311","174,945","12,421","11,088"
9,Payments,"(267,819)","(269,012)","(3,886)","(2,666)"
10,(Gain)/Loss arising from changes in assumptions,"(81,295)","(24,720)","49,113","3,810"
11,Exchange differences,"( 2,189)","2,189",-,-
12,At the end of the year,"2,513,093","2,439,021","219,756","146,903"
13,The expenses are recognised in the income stat...,,,,
14,Cost of sales,"183,435","165,036","3,543","3,591"
15,Selling and distribution expenses,"28,954","34,795",-,-
16,Administrative expenses,"212,986","200,619","24,083","18,083"
17,,"425,375","400,450","27,626","21,674"

Table 74:

,0,1,2,3,4
0,38.4 \nSensitivity of assumptions used,,,,
1,A percentage change in the assumptions would h...,,,,
2,,GROUP,,COMPANY,
3,As at 31 March,2023,2022,2023,2022
4,In Rs.'000s,,,,
5,Discount rate:,,,,
6,1% Increase,"(104,429)","(117,176)","(6,849)","(5,798)"
7,1% Decrease,"91,414","113,434","7,311","6,281"
8,Salary Increment rate:,,,,
9,1% Increase,"100,305","118,799","7,899","6,541"
10,1% Decrease,"(114,064)","(124,005)","(7,504)","(6,141)"

Table 75:

,0,1
0,NOTES TO THE FINANCIAL STATEMENTS,
1,44. \nRELATED PARTY TRANSACTIONS,Non-recurrent related party transactions
2,Terms and conditions of transactions with rela...,There were no non-recurrent related party tran...
3,The Group and the Company carried out transact...,aggregate value exceeds 10% of the equity or 5...
4,course of business with the following related ...,whichever is lower of the company as per 31 Ma...
5,"at each of the subsidiaries, joint venture and...","financial statements, which required additiona..."
6,have been disclosed in the Group Directory und...,2022/2023 Annual Report under Colombo Stock Ex...
7,Information section of the Annual Report.,9.3.2 and Code of Best Practices on Related Pa...
8,,Securities and Exchange Commission Directive i...
9,"Governance structure, nature of the entity’s r...",13(c) of the Securities and Exchange Commissio...
10,of business and the country of incorporation h...,
11,corporate governance section and Group directory.,Recurrent related party transactions
12,,There were no recurrent related party transact...
13,Transactions with related parties are carried ...,exceeds 10% of the consolidated revenue of the...
14,of business. Outstanding current account balan...,"2022 audited financial Statements, which requi..."
15,"unsecured, interest free and settlement occurs...",the 2022/2023 Annual Report under Colombo Stoc...
16,,9.3.2 and Code of Best Practices on Related Pa...
17,The sales to and purchases from related partie...,Securities and Exchange Commission Directive i...
18,equivalent to those that prevail in arm's leng...,of the Securities and Exchange Commission Act.
19,44.1 Amounts due from related parties,
20,,GROUP\nCOMPANY

Table 76:

,0,1,2,3,4,5
0,,,,COMPANY,,
1,,,2023,,2022,
2,Expiry date,Adjusted exercise,Number of shares,Number of shares,Number of shares,Number of shares
3,,price,outstanding at,exercisable at the,outstanding at the,exercisable at the
4,,Rs.,the end of period,end of period,end of period,end of period
5,02.07.2022,173.30,-,-,"725,000","725,000"
6,21.06.2023,154.10,"880,000","880,000","880,000","660,000"
7,30.06.2024,136.97,"880,000","660,000","880,000","440,000"
8,30.06.2025,132.86,"880,000","440,000","880,000","220,000"
9,30.06.2026,136.64,"880,000","220,000","880,000",-
10,30.06.2027,121.91,"880,000",-,-,-

Table 77:

,0,1,2
0,,HISTORY OF THE JOHN KEELLS GROUP,
1,,2005 – The Group launched its hotel brand,"Gregory’s Road, a high end, niche, residential"
2,1870-1970,,
3,,‘Cinnamon Hotels & Resorts’. JKH entered into an,development was completed.
4,"1870 – Two English brothers, George and Edwin",MoU to develop a third resort in the Maldives.,
...,...,...,...
100,created as a holding company for all Group,by way of the largest syndicated debt facility,
101,"resorts. The Group’s CSR arm, the John Keells",obtained by a local firm. A controlling stake in,
102,Social Responsibility Foundation was established,Rajawella Holdings Ltd (RHL) was acquired for,
103,as a non-profit organisation.,Rs. 1.04 billion. The Group raised Rs. 8 billi...,
104,,"converting 50 million warrants, '7th Sense' on",

Table 78:

,0,1,2,3,4,5,6,7,8,9,10
0,31 March,2023,2022,2021,2020,2019,2018,2017,2016,2015,2014
1,Rs. Mn,,,,,,,,,,
2,OPERATING RESULTS,,,,,,,,,,
3,Group revenue,"276,640","218,075","127,676","138,956","135,456","121,215","106,273","93,710","91,852","86,706"
4,EBIT,"40,392","34,359","7,931","15,508","20,198","28,155","23,324","20,192","19,226","16,537"
5,Finance cost,"(17,803)","(7,035)","(4,669)","(3,166)","(2,722)",(521),(436),(994),(668),"(1,217)"
6,Share of results of equity accounted,"7,574","6,746","4,159","4,466","4,727","3,596","3,303","2,781","2,778","3,089"
7,investees (net of tax),,,,,,,,,,
8,Profit before tax,"22,589","27,324","5,445","12,403","18,616","27,634","22,888","19,198","18,557","15,320"
9,Tax expense,"(3,693)","(6,882)","(1,494)","(2,662)","(2,378)","(4,515)","(4,771)","(3,406)","(2,812)","(2,362)"
10,Profit after tax,"18,896","20,443","3,951","9,741","16,237","23,120","18,117","15,792","15,745","12,958"
11,Attributable to:,,,,,,,,,,
12,Equity holders of the parent,"18,174","20,213","4,772","9,414","15,254","21,021","16,275","14,070","14,348","11,721"
13,Non-controlling interests,722,230,(821),327,983,"2,099","1,842","1,722","1,397","1,237"
14,,"18,896","20,443","3,951","9,741","16,237","23,120","18,117","15,792","15,745","12,958"
15,CAPITAL EMPLOYED,,,,,,,,,,
16,Stated capital,"73,188","73,188","63,102","62,881","62,806","62,802","62,790","58,702","50,703","49,749"
17,Capital reserves and other components,"146,091","129,011","72,403","66,085","58,646","49,852","38,652","28,715","24,501","21,845"
18,of equity,,,,,,,,,,
19,Revenue reserves,"121,743","109,087","90,652","87,885","82,834","87,266","77,193","67,565","62,594","51,304"
20,,"341,022","311,286","226,157","216,851","204,286","199,920","178,635","154,982","137,798","122,898"
21,Non-controlling interest,"19,396","18,805","16,830","26,872","26,072","24,944","15,696","13,499","12,279","11,421"
22,Total equity,"360,418","330,091","242,987","243,723","230,358","224,864","194,331","168,481","150,077","134,319"
23,Total debt,"264,060","268,228","172,904","100,907","54,513","29,722","22,766","20,750","23,934","26,139"
24,,"624,478","598,319","415,891","344,630","284,871","254,586","217,097","189,231","174,011","160,458"
25,ASSETS EMPLOYED,,,,,,,,,,
26,"Property, plant and equipment (PP&E)","362,097","124,348","113,077","111,534","97,688","87,260","64,396","52,737","49,563","47,406"
27,Non-current assets other than PP&E,"199,604","354,518","257,226","204,360","170,687","136,427","107,912","93,376","78,030","71,969"
28,Current assets,"182,806","238,929","166,491","121,050","95,421","98,762","104,964","94,863","90,493","82,206"
29,Liabilities net of debt,"(120,028)","(119,476)","(120,903)","(92,314)","(78,925)","(67,862)","(60,175)","(51,745)","(44,075)","(41,123)"
30,,"624,478","598,319","415,891","344,630","284,871","254,587","217,097","189,231","174,011","160,458"
31,CASH FLOW,,,,,,,,,,
32,Net cash flows from operating activities,"13,281","30,440","13,825","(10,350)","(4,743)","16,012","21,020","20,513","20,855","8,041"
33,Net cash flows from / (used in) investing,"(78,889)","39,363","(44,944)","(27,039)","(8,452)","(16,640)","(17,670)","(9,567)","(1,255)","(19,710)"
34,activities,,,,,,,,,,
35,Net cash flows from / (used in) financing,"(28,646)","31,693","55,427","18,431","(11,000)","(4,587)","(4,105)","(7,717)","(4,838)","25,446"
36,activities,,,,,,,,,,
37,Net increase / (decrease) in cash and cash,"(94,254)","101,495","24,308","(18,959)","(14,709)","(5,215)",(755),"3,229","14,762","13,777"
38,equivalents,,,,,,,,,,
39,KEY INDICATORS,,,,,,,,,,
40,Basic earnings per share (Rs.),13.12,15.13,3.62,7.14,11.13,15.2,11.9,10.5,12.6,10.5
41,Interest cover (no. of times),2.3,4.9,1.7,4.9,7.8,54,52.8,51.5,27.7,13.6
42,Net assets per share* (Rs.),246.2,224.8,163.3,156.6,147.5,144.4,129.0,111.9,99.5,88.7
43,Enterprise value (EV),"357,609","311,951","244,679","186,236","210,020","187,926",136.022,"124,182","155,675","124,182"
44,EV / EBITDA,7.7,10.7,15.7,9.2,8.5,5.8,5.0,5.0,6.6,10.0
45,ROE (%),5.6,7.5,2.2,4.5,7.5,11.1,9.8,9.6,11.0,11.0
46,Debt / equity ratio (%),73.3,81.3,71.2,41.4,23.7,13.2,11.7,12.3,15.9,19.5
47,Net debt excl. leases (cash)/Equity (%),35.91,23.5,20.0,14.0,1.9,(14.9),(28.5),(30.8),(28.8),(23.2)
48,Dividend payout (Rs.Mn),"2,770","2,012","1,978","4,614","8,186","8,325","7,280","8,038","3,476","3,267"
49,Current ratio (no. of times),2.0,1.8,2.3,2.1,1.7,3.0,3.7,4.0,2.6,2.4
50,Market price per share unadjusted (Rs.),140.0,145.0,148.5,115.4,156.0,159.6,137.9,148.0,199.4,227.0
51,Market price per share diluted (Rs.),140.0,145.0,148.5,115.4,156.0,159.6,137.9,129.5,152.7,173.8
52,Revenue growth rate (%),26.9,70.8,(8.1),2.6,11.8,14.1,13.4,1.6,5.9,4.1
53,USD closing rate (Rs.),329.5,305.0,200.3,189.6,175.5,155.9,151.9,147.7,133.5,130.7
54,USD average rate (Rs.),360.4,208.3,189.0,179.4,168.6,153.6,148.0,139.2,131.2,130.1

Table 79:

,0,1,2,3,4
0,In USD '000s,,,,
1,Continuing operations,,,,
2,Revenue from contracts with customers,"791,160","665,079","7,720","6,150"
3,Revenue from Insurance Contracts,"48,414","49,920",-,-
4,Total Revenue,"839,574","714,999","7,720","6,150"
5,Cost of sales,"(689,500)","(591,574)","(3,541)","(3,558)"
6,Gross profit,"150,074","123,425","4,179","2,592"
7,Dividend income,-,-,"32,276","26,255"
8,Other operating income,"9,896","8,573",125,168
9,Selling and distribution expenses,"(25,087)","(18,796)",-,-
10,Administrative expenses,"(66,549)","(48,402)","(6,334)","(4,207)"
11,Other operating expenses,"(29,820)","(40,839)","(2,271)","(1,687)"
12,Results from operating activities,"38,514","23,961","27,975","23,121"
13,Finance cost,"(54,030)","(23,065)","(26,643)","(9,725)"
14,Finance income,"81,638","101,004","49,554","79,339"
15,Change in insurance contract liabilities,"(23,218)","(21,037)",-,-
16,Change in fair value of investment property,"2,666","(13,393)",-,-
17,Share of results of equity accounted investees...,"22,985","22,118",-,-
18,Profit before tax,"68,555","89,588","50,886","92,735"
19,Tax expense,"(11,209)","(22,563)","(6,245)","(12,782)"
20,Profit for the year,"57,346","67,025","44,641","79,953"
21,Attributable to:,,,,
22,Equity holders of the parent,"55,154","66,272",,
23,Non-controlling interests,"2,192",753,,
24,,"57,346","67,025",,

Table 80:

,0,1,2
0,GLOSSARY,,
1,ACCRUAL BASIS,EARNINGS PER SHARE (BASIC),PRICE EARNINGS RATIO
2,Recording revenues and expenses in the period,Profit attributable to equity holders of the p...,Market price per share over earnings per share.
3,in which they are earned or incurred regardless,divided by the weighted average number of,
4,,,PRICE TO BOOK RATIO
...,...,...,...
112,shares in issue as a percentage of the share p...,,
113,,the parent divided by total revenue including,
114,(diluted) at the end of the period.,,
115,,equity accounted investees.,
116,John Keells Holdings PLC \n| Annual Report 20...,,

Table 81:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year &,Addresses,Directors,Stated Capital &
1,Group,,Business,,,Country,,,Effective Holding
2,,,,Colombo West International,Ports & Shipping Services,2021,"No. 117, Sir Chittampalam A Gardiner Mawatha,","K N J Balendra, J G A Cooray, S Mehta, S Tripa...","USD 51,960,785"
3,,,,Terminal (Pvt) Ltd**,,(PV00238709),Colombo 2.,"U M Abhyankar, H Sundaram, K A Pathak, J S Khu...",34%
4,,,,,,Sri Lanka,Tel. 2475574,"A Z Hashim, K D Weerasinghe, G U K Algewattage,",
...,...,...,...,...,...,...,...,...,...
59,,,,,,,"26151853, 26147365 Fax: +91-11-2614 5222",,
60,,,Foods,,,,,,
61,,,,Keells Food Products PLC,Manufacturer and distributor of,1982,"P\n.O Box 10,No.16, Minuwangoda Road, Ekala Ja...",K N J Balendra - Chairperson,"Rs.1,294,815,000"
62,,,,,"Processed meat, breaded meat &",(PQ 3),Tel. 2236317/ 2236364,"J G A Cooray, D P Gamlath, S De Silva, A E H S...",88.63%
63,,,,,convenience food products.,Sri Lanka,,"I Samarajiva, P D Samarasinghe, P N Fernando",

Table 82:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year &,Addresses,Directors,Stated Capital &
1,Group,,Business,,,Country,,,Effective Holding
2,,,,Colombo West International,Ports & Shipping Services,2021,"No. 117, Sir Chittampalam A Gardiner Mawatha,","K N J Balendra, J G A Cooray, S Mehta, S Tripa...","USD 51,960,785"
3,,,,Terminal (Pvt) Ltd**,,(PV00238709),Colombo 2.,"U M Abhyankar, H Sundaram, K A Pathak, J S Khu...",34%
4,,,,,,Sri Lanka,Tel. 2475574,"A Z Hashim, K D Weerasinghe, G U K Algewattage,",
...,...,...,...,...,...,...,...,...,...
59,,,,,,,"26151853, 26147365 Fax: +91-11-2614 5222",,
60,,,Foods,,,,,,
61,,,,Keells Food Products PLC,Manufacturer and distributor of,1982,"P\n.O Box 10,No.16, Minuwangoda Road, Ekala Ja...",K N J Balendra - Chairperson,"Rs.1,294,815,000"
62,,,,,"Processed meat, breaded meat &",(PQ 3),Tel. 2236317/ 2236364,"J G A Cooray, D P Gamlath, S De Silva, A E H S...",88.63%
63,,,,,convenience food products.,Sri Lanka,,"I Samarajiva, P D Samarasinghe, P N Fernando",

Table 83:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year &,Addresses,Directors,Stated Capital &
1,Group,,Business,,,Country,,,Effective Holding
2,,,,JayKay Marketing Services (Pvt) Ltd,"Owns and Operates the ""Keells"" chain of",1980,"No.117,Chittampalam A,Gardiner",J G A Cooray - Chairperson,"Rs.1,198,000,000"
3,,,,,"supermarkets and ""Nexus Mobile"" loyalty",(PV 33),"Mawatha,Colombo - 02","A Wanniarachchi, K C Subasinghe, N W Tambiah",81.36%
4,,,,,card programme.,Sri Lanka,Tel. 2316800,,
...,...,...,...,...,...,...,...,...,...
60,,,,,,Sri Lanka,,,
61,,,,Indra Hotel and Resorts Kandy,Owner of Cinnamon Red Kandy,2017,"No. 273, Katugastota Road, Kandy","Y S H I K Silva, Y S H R S Silva, Y S H H K Si...","Rs.1,051,400,493"
62,,,,(Pvt) Ltd*,,(PV 124247),Tel. 081 2234346,C L P Gunawardane,32.13%
63,,,,,,Sri Lanka,,,
64,318,John Keells Holdings PLC,| Annual Report 2022/23,,,,,,

Table 84:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year &,Addresses,Directors,Stated Capital &
1,Group,,Business,,,Country,,,Effective Holding
2,,,,JayKay Marketing Services (Pvt) Ltd,"Owns and Operates the ""Keells"" chain of",1980,"No.117,Chittampalam A,Gardiner",J G A Cooray - Chairperson,"Rs.1,198,000,000"
3,,,,,"supermarkets and ""Nexus Mobile"" loyalty",(PV 33),"Mawatha,Colombo - 02","A Wanniarachchi, K C Subasinghe, N W Tambiah",81.36%
4,,,,,card programme.,Sri Lanka,Tel. 2316800,,
...,...,...,...,...,...,...,...,...,...
60,,,,,,Sri Lanka,,,
61,,,,Indra Hotel and Resorts Kandy,Owner of Cinnamon Red Kandy,2017,"No. 273, Katugastota Road, Kandy","Y S H I K Silva, Y S H R S Silva, Y S H H K Si...","Rs.1,051,400,493"
62,,,,(Pvt) Ltd*,,(PV 124247),Tel. 081 2234346,C L P Gunawardane,32.13%
63,,,,,,Sri Lanka,,,
64,,,,,,,,Navigating Our Value Creation Journey Gro...,

Table 85:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year &,Addresses,Directors,Stated Capital &
1,Group,,Business,,,Country,,,Effective Holding
2,,,,International Tourists and Hoteliers,Owner of Cinnamon Bey,1973,"Moragalla, Beruwala","C L P Gunawardane, K C Subasinghe, M H Singhaw...","Rs.1,939,760,925"
3,,,,Ltd *,,(PB 17),"Tel. 2306600, 2421101-8",M R Svensson,79.78%
4,,,,,,Sri Lanka,,,
5,,,,Kandy Walk Inn Ltd,"Owner & operator of ""Cinnamon Citadel""",1979,"No.124, Srimath Kuda Ratwatte Mawatha, Kandy","C L P Gunawardane, K C Subasinghe, M H Singhaw...","Rs.115,182,009"
6,,,,,in Kandy,(PB 395),Tel. 081 2234365-6/ 081 2237273-4,M R Svensson,79.03%
7,,,,,,Sri Lanka,,,
8,,,,Nuwara Eliya Holiday Resorts (Pvt),Owner of real estate,2014,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, K C Subasinghe, M H Singhaw...","Rs.331,236,820"
9,,,,Ltd *,,(PV98357),"Mawatha,Colombo - 02",M R Svensson,80.32%
10,,,,,,Sri Lanka,Tel. 2306000,,
11,,,,Rajawella Hotels Company Ltd *,Owner of real estate,1992,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, K C Subasinghe, M H Singhaw...","Rs.37,000,585"
12,,,,,,(PB 92),"Mawatha,Colombo - 02",M R Svensson,80.32%
13,,,,,,Sri Lanka,Tel. 2306000,,
14,,,Sri Lankan,Resort Hotels Ltd *,Owner of real estate,1978,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, K C Subasinghe, M H Singhaw...","Rs.8,849,150"
15,,,Resorts,,,(PB 193),"Mawatha,Colombo - 02",M R Svensson,79.60%
16,,,,,,Sri Lanka,"Tel. 2306780, 2421101-8",,
17,,,,Trinco Holiday Resorts (Pvt) Ltd,"Owner & Operator of ""Trinco Blu by",2009,"Sambativu, Uppuvelli, Trincomalee","C L P Gunawardane, K C Subasinghe, M H Singhaw...","Rs.357,000,000"
18,,,,,"Cinnamon"" in Trincomalee",(PV 69908),Tel. 026 2222307 / 026 2221611,M R Svensson,80.32%
19,,,,,,Sri Lanka,,,
20,,,,Trinco Walk Inn Ltd*,Owner of Real Estate,1984,"Alles Garden, Uppuveli,Sampathiv Post,","C L P Gunawardane, K C Subasinghe, M H Singhaw...","Rs.119,850,070"
21,,Cinnamon Hotels & Resorts,,,,(PB 168),Trincomalee,M R Svensson,80.32%
22,,,,,,Sri Lanka,Tel. 026 2222307 / 011 2306600,,
23,,,,Wirawila Walk Inn Ltd*,Owner of Real Estate,1994,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, K C Subasinghe, M H Singhaw...","Rs.22,936,066"
24,,,,,,(PB 89),"Mawatha,Colombo - 02",,80.32%
25,LEISURE,,,,,Sri Lanka,"Tel. 2306780, 2421101-8",,
26,,,,Yala Village (Pvt) Ltd,"Owner & operator of ""Cinnamon Wild"" in",1999,"P\n.O Box 1,Kirinda, Tissamaharama",M A Perera - Chairperson,"Rs.319,427,600"
27,,,,,Yala,(PV 2868),Tel. 047 2239449-52,"C L P Gunawardane, S Rajendra, M H Singhawansa,",75.33%
28,,,,,,Sri Lanka,,"J A Davis, M R Svensson, N W Tambiah",
29,,,,Fantasea World Investments (Pte),"Owner & operator of ""Cinnamon Hakuraa",1997,"Meemu Atoll, Republic of Maldives","C L P Gunawardane, S Rajendra, M H Singhawansa,","Rs.341,573,190"
30,,,,Ltd,"Huraa"" in Maldives",(C 143/97),Tel. +9603336000,M R Svensson,80.32%
31,,,,,,Maldives,,,
32,,,,John Keells Maldivian Resorts (Pte),Hotel holding company in the Maldives,1996,"2nd Floor, H.Maizan Building, Sosun Magu, Male,","S Rajendra,C L P Gunawardane, M H Singhawansa,","Rs.3,978,671,681"
33,,,,Ltd,,(C 208/96),Republic of Maldives,M R Svensson,80.32%
34,,,Maldivian,,,Maldives,Tel. +9603336000,,
35,,,Resorts,Tranquility (Pte) Ltd,"Owner and operator of ""Cinnamon",2004,"North Malé Atoll, Republic of Maldives","C L P Gunawardane, S Rajendra,M H Singhawansa,","Rs.552,519,608"
36,,,,,"Dhoinveli"" and ""Cinnamon Velifushi"" in",(C 344/2004),Tel. +9603336000,M R Svensson,80.32%
37,,,,,Maldives,Maldives,,,
38,,,,Travel Club (Pte) Ltd,"Operator of ""Ellaidhoo Maldives by",1992,"North Ari Atoll, Republic of Maldives","C L P Gunawardane, S Rajendra - Managing Director","Rs.143,172,000"
39,,,,,"Cinnamon"" in Maldives",(C 121/92),Tel. +9603336000,"M H Singhawansa, M R Svensson",80.32%
40,,,,,,Maldives,,,
41,,,,Cinnamon Holidays (Pvt) Ltd,Service providers of Inbound and,2015,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, K C Subasinghe, M H Singhaw...","Rs.200,000"
42,,,,,outbound Tours,(PV 101005) PV107427,"Mawatha,Colombo - 02",M R Svensson,80.32%
43,,,,,,Sri Lanka,Tel. 2306000,,
44,,,,Walkers Tours Ltd,Inbound tour operators,1969,"No.117,Chittampalam A,Gardiner","S Rajendra,C L P Gunawardane, I N Amaratunga","Rs.51,374,200"
45,,Destination Management,,,,(PB 249),"Mawatha,Colombo - 02",,98.05%
46,,,,,,Sri Lanka,Tel. 2306306,,
47,,,,Whittall Boustead (Travel) Ltd,Inbound tour operators,1977,"No.117,Chittampalam A,Gardiner","S Rajendra, C L P Gunawardane, I N Amaratunga","Rs.250,410,000"
48,,,,,,(PB 112),"Mawatha,Colombo - 02",,100%
49,,,,,,Sri Lanka,Tel. 2306746,,
50,,,,Asian Hotels and Properties PLC -,"Developer of 'Crescat Residencies', 'The",1993,"No.89, Galle Road, Colombo 3",K N J Balendra - Chairperson/Managing Director,"Rs.3,345,118,012"
51,,,,"Crescat. Boulevard, The Monarch,",Monarch' & 'The Emperor' Residential,(PQ 2),Tel. 0112152100,"J G A Cooray, C L P Gunawardane, S Rajendra,",78.56%
52,,,,The Emperor.***,Towers Developer and manager of,Sri Lanka,,"M R Svensson, J Durairatnam, A S De Zoysa,",
53,PROPERTY,Property Management,,,'Crescat Boulevard ' shopping Mall,,,A Nanayakkara,
54,,,,John Keells Properties Ja-Ela (Pvt),Developer & Manager of ' K-Zone Ja-Ela',2010,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, K C Subasinghe, N N Mawilmada","Rs.954,360,000"
55,,,,Ltd,Shopping Mall,(PV 76068),Tel. 0112152100,,100%
56,,,,,,Sri Lanka,,,

Table 86:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year &,Addresses,Directors,Stated Capital &
1,Group,,Business,,,Country,,,Effective Holding
2,,,,International Tourists and Hoteliers,Owner of Cinnamon Bey,1973,"Moragalla, Beruwala","C L P Gunawardane, K C Subasinghe, M H Singhaw...","Rs.1,939,760,925"
3,,,,Ltd *,,(PB 17),"Tel. 2306600, 2421101-8",M R Svensson,79.78%
4,,,,,,Sri Lanka,,,
5,,,,Kandy Walk Inn Ltd,"Owner & operator of ""Cinnamon Citadel""",1979,"No.124, Srimath Kuda Ratwatte Mawatha, Kandy","C L P Gunawardane, K C Subasinghe, M H Singhaw...","Rs.115,182,009"
6,,,,,in Kandy,(PB 395),Tel. 081 2234365-6/ 081 2237273-4,M R Svensson,79.03%
7,,,,,,Sri Lanka,,,
8,,,,Nuwara Eliya Holiday Resorts (Pvt),Owner of real estate,2014,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, K C Subasinghe, M H Singhaw...","Rs.331,236,820"
9,,,,Ltd *,,(PV98357),"Mawatha,Colombo - 02",M R Svensson,80.32%
10,,,,,,Sri Lanka,Tel. 2306000,,
11,,,,Rajawella Hotels Company Ltd *,Owner of real estate,1992,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, K C Subasinghe, M H Singhaw...","Rs.37,000,585"
12,,,,,,(PB 92),"Mawatha,Colombo - 02",M R Svensson,80.32%
13,,,,,,Sri Lanka,Tel. 2306000,,
14,,,Sri Lankan,Resort Hotels Ltd *,Owner of real estate,1978,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, K C Subasinghe, M H Singhaw...","Rs.8,849,150"
15,,,Resorts,,,(PB 193),"Mawatha,Colombo - 02",M R Svensson,79.60%
16,,,,,,Sri Lanka,"Tel. 2306780, 2421101-8",,
17,,,,Trinco Holiday Resorts (Pvt) Ltd,"Owner & Operator of ""Trinco Blu by",2009,"Sambativu, Uppuvelli, Trincomalee","C L P Gunawardane, K C Subasinghe, M H Singhaw...","Rs.357,000,000"
18,,,,,"Cinnamon"" in Trincomalee",(PV 69908),Tel. 026 2222307 / 026 2221611,M R Svensson,80.32%
19,,,,,,Sri Lanka,,,
20,,,,Trinco Walk Inn Ltd*,Owner of Real Estate,1984,"Alles Garden, Uppuveli,Sampathiv Post,","C L P Gunawardane, K C Subasinghe, M H Singhaw...","Rs.119,850,070"
21,,Cinnamon Hotels & Resorts,,,,(PB 168),Trincomalee,M R Svensson,80.32%
22,,,,,,Sri Lanka,Tel. 026 2222307 / 011 2306600,,
23,,,,Wirawila Walk Inn Ltd*,Owner of Real Estate,1994,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, K C Subasinghe, M H Singhaw...","Rs.22,936,066"
24,,,,,,(PB 89),"Mawatha,Colombo - 02",,80.32%
25,LEISURE,,,,,Sri Lanka,"Tel. 2306780, 2421101-8",,
26,,,,Yala Village (Pvt) Ltd,"Owner & operator of ""Cinnamon Wild"" in",1999,"P\n.O Box 1,Kirinda, Tissamaharama",M A Perera - Chairperson,"Rs.319,427,600"
27,,,,,Yala,(PV 2868),Tel. 047 2239449-52,"C L P Gunawardane, S Rajendra, M H Singhawansa,",75.33%
28,,,,,,Sri Lanka,,"J A Davis, M R Svensson, N W Tambiah",
29,,,,Fantasea World Investments (Pte),"Owner & operator of ""Cinnamon Hakuraa",1997,"Meemu Atoll, Republic of Maldives","C L P Gunawardane, S Rajendra, M H Singhawansa,","Rs.341,573,190"
30,,,,Ltd,"Huraa"" in Maldives",(C 143/97),Tel. +9603336000,M R Svensson,80.32%
31,,,,,,Maldives,,,
32,,,,John Keells Maldivian Resorts (Pte),Hotel holding company in the Maldives,1996,"2nd Floor, H.Maizan Building, Sosun Magu, Male,","S Rajendra,C L P Gunawardane, M H Singhawansa,","Rs.3,978,671,681"
33,,,,Ltd,,(C 208/96),Republic of Maldives,M R Svensson,80.32%
34,,,Maldivian,,,Maldives,Tel. +9603336000,,
35,,,Resorts,Tranquility (Pte) Ltd,"Owner and operator of ""Cinnamon",2004,"North Malé Atoll, Republic of Maldives","C L P Gunawardane, S Rajendra,M H Singhawansa,","Rs.552,519,608"
36,,,,,"Dhoinveli"" and ""Cinnamon Velifushi"" in",(C 344/2004),Tel. +9603336000,M R Svensson,80.32%
37,,,,,Maldives,Maldives,,,
38,,,,Travel Club (Pte) Ltd,"Operator of ""Ellaidhoo Maldives by",1992,"North Ari Atoll, Republic of Maldives","C L P Gunawardane, S Rajendra - Managing Director","Rs.143,172,000"
39,,,,,"Cinnamon"" in Maldives",(C 121/92),Tel. +9603336000,"M H Singhawansa, M R Svensson",80.32%
40,,,,,,Maldives,,,
41,,,,Cinnamon Holidays (Pvt) Ltd,Service providers of Inbound and,2015,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, K C Subasinghe, M H Singhaw...","Rs.200,000"
42,,,,,outbound Tours,(PV 101005) PV107427,"Mawatha,Colombo - 02",M R Svensson,80.32%
43,,,,,,Sri Lanka,Tel. 2306000,,
44,,,,Walkers Tours Ltd,Inbound tour operators,1969,"No.117,Chittampalam A,Gardiner","S Rajendra,C L P Gunawardane, I N Amaratunga","Rs.51,374,200"
45,,Destination Management,,,,(PB 249),"Mawatha,Colombo - 02",,98.05%
46,,,,,,Sri Lanka,Tel. 2306306,,
47,,,,Whittall Boustead (Travel) Ltd,Inbound tour operators,1977,"No.117,Chittampalam A,Gardiner","S Rajendra, C L P Gunawardane, I N Amaratunga","Rs.250,410,000"
48,,,,,,(PB 112),"Mawatha,Colombo - 02",,100%
49,,,,,,Sri Lanka,Tel. 2306746,,
50,,,,Asian Hotels and Properties PLC -,"Developer of 'Crescat Residencies', 'The",1993,"No.89, Galle Road, Colombo 3",K N J Balendra - Chairperson/Managing Director,"Rs.3,345,118,012"
51,,,,"Crescat. Boulevard, The Monarch,",Monarch' & 'The Emperor' Residential,(PQ 2),Tel. 0112152100,"J G A Cooray, C L P Gunawardane, S Rajendra,",78.56%
52,,,,The Emperor.***,Towers Developer and manager of,Sri Lanka,,"M R Svensson, J Durairatnam, A S De Zoysa,",
53,PROPERTY,Property Management,,,'Crescat Boulevard ' shopping Mall,,,A Nanayakkara,
54,,,,John Keells Properties Ja-Ela (Pvt),Developer & Manager of ' K-Zone Ja-Ela',2010,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, K C Subasinghe, N N Mawilmada","Rs.954,360,000"
55,,,,Ltd,Shopping Mall,(PV 76068),Tel. 0112152100,,100%
56,,,,,,Sri Lanka,,,

Table 87:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year &,Addresses,Directors,Stated Capital &
1,Group,,Business,,,Country,,,Effective Holding
2,,,,Keells Realtors Ltd *,Owner of Real Estates,1977,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, K C Subasinghe, N N Mawilmada","Rs.75,000,000"
3,,,,,,(PB 90),Tel. 0112152100,,95.81%
4,,,,,,Sri Lanka,,,
5,,,,Mackinnons Keells Ltd*,Rental of office spaces,1952,"No. 4, Layden Bastian Road, Colombo 1","K M Thanthirige, N W R Wijewantha, N N Mawilmada","Rs.327,800,000"
6,,Property Management,,,,(PB 8),Tel. 0112152100,,100%
7,,,,,,Sri Lanka,,,
8,,,,Whittall Boustead (Pvt) Ltd - Real,Renting of office space,1958,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, K C Subasinghe, N N Mawilmada","Rs.99,188,800"
9,,,,Estate Division,,(PV 31),Tel. 0112152100,,100%
10,,,,,,Sri Lanka,,,
11,,,,British Overseas (Pvt) Ltd,"Developer of ""7th Sense"" Residential",2011,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, K C Subasinghe, N N Mawilmada,","Rs.1,000"
12,,,,,Tower,(PV 80203),Tel. 0112152100,"S P G N Rajapakse, D P Gamlath",61%
13,,,,,,Sri Lanka,,,
14,,,,Braybrooke Residential Properties,Investor of Braybrooke Residential Towers,1998,"No.186, Vauxhall Street, Colombo - 02",Y S H R S Silva - Chairperson,"Rs.1,403,970,000"
15,,,,(Pvt) Ltd *,(Pvt) Ltd,(PV19165),Tel. 0112152100,"S Rajendra, K C Subasinghe, N N Mawilmada,",50%
16,,,,,,Sri Lanka,,"D P Gamlath, Y S H I K Silva, C P Palansuriya,",
17,,,,,,,,Y S H H K Silva,
18,,,,Braybrooke Residential Towers,Developer of 'TRI-ZEN' Residential Towers,2017,"No.186, Vauxhall Street, Colombo - 02",Y S H R S Silva - Chairperson,"Rs.3,636,900,000"
19,,,,(Pvt) Ltd *,,(PV128387),Tel. 0112152100,"K N J Balendra, J G A Cooray, S Rajendra,",50%
20,,,,,,Sri Lanka,,"N N Mawilmada, Y S H I K Silva, A D B Talwatte,",
21,,,,,,,,C P Palansuriya,
22,PROPERTY,,,Glennie Properties (Pvt) Ltd *,Property Development,2012,"No.186, Vauxhall Street, Colombo - 02","K C Subasinghe, N N Mawilmada, D P Gamlath,","Rs. 163,861,400"
23,,,,,,(PV 84278),Tel. 0112152100,N W R Wijewantha,100%
24,,,,,,Sri Lanka,,,
25,,,,J K Land (Pvt) Ltd *,Investment Company for Property Sector,2012,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, K C Subasinghe, N N Mawilmada","Rs.24,964,638,930"
26,,,,,,(PV 84272),Tel. 0112152100,,100%
27,,Property Development,,,,Sri Lanka,,,
28,,,,J K Thudella Properties (Pvt) Ltd *,Owner of Real Estates,2018,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, N N Mawilmada","Rs.453,467,620"
29,,,,,,(PV 129825),Tel. 0112152100,,100%
30,,,,,,Sri Lanka,,,
31,,,,John Keells Residential Properties,"Developer of ""On320"" Residential Towers",2010,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, K C Subasinghe,N N Mawilmada","Rs.925,200,000"
32,,,,(Pvt) Ltd,,(PV 75050),Tel. 0112152100,,100%
33,,,,,,Sri Lanka,,,
34,,,,Rajawella Holdings Ltd,"Operates an 18 hole, Donald Street",1991,"P O Box 7, Rajawella, Kandy",K N J Balendra - Chairperson,"Rs.784,690,140"
35,,,,,Designed Golf Course in Digana,(PB27),Tel. 0112152100,"J G A Cooray, S Rajendra, N N Mawilmada, C B T...",49.85%
36,,,,,,Sri Lanka,,"(Alt. C J Holloway), G R Bostock Kirk (Alt. E ...",
37,,,,,,,,S E Captain (Alt. R S Captain),
38,,,,Vauxhall Land Developments (Pvt),Owner of Real Estates,2017,"No.186, Vauxhall Street, Colombo - 02",K N J Balendra - Chairperson,"Rs.21,716,553,910"
39,,,,Ltd *,,(PV125587),Tel. 0112152100,"J G A Cooray, N N Mawilmada, N W R Wijewantha",100%
40,,,,,,Sri Lanka,,,
41,,,,Waterfront Properties (Pvt) Ltd***,"Developer of Hotels,Apartments, offices &",2011,"No.186, Vauxhall Street, Colombo - 02",K N J Balendra - Chairperson,"Rs.152,313,664,645"
42,,,,,Shopping Malls,(PV 82153),Tel. 0112152100,"J G A Cooray, S Rajendra, N N Mawilmada",99.10%
43,,,,,,Sri Lanka,,,
44,,,,Fairfirst Insurance Ltd **,Providers of Non Life insurance solutions,2014,"Access Towers II, 14th Floor, No: 278/4, Union",C Ratnaswami - Chairperson,"Rs.3,131,949,000"
45,,,,,,(PB 5180),"Place, Colombo 02","A S Wijesinha, C D Wijegunawardene, S Malhotra,",19.80%
46,,,,,,Sri Lanka,Tel. 0112428428,"J P Gomes, R M Prabhakar",
47,,,Insurance,,,,,,
48,,,,Union Assurance PLC,Providers of Life insurance solutions,1987,"No.20, St. Michaels' Road, Colombo 3",K N J Balendra - Chairperson,"Rs.1,000,000,000"
49,,,,,,(PQ 12),Tel. 0112990990,"S Rajendra, D P Gamlath, D H Fernando, S A App...",90%
50,,,,,,Sri Lanka,,P T Wanigasekara,
51,FINANCIAL SERVICES,,,John Keells Stock Brokers (Pvt) Ltd,Share broking services,1979,"No. 186,Vauxhall street, Colombo 02","S Rajendra, D P Gamlath, R S Cader","Rs.57,750,000"
52,,,Stock Broking,,,(PV 89),"Tel.0112306250, 0112342066-7",,90.04%
53,,,,,,Sri Lanka,,,
54,,,,Nations Trust Bank PLC **,Commercial banking,1999,"No. 242, Union Place, Colombo 2.",J G A Cooray - Chairperson,"Rs.11,426,882,000"
55,,,,,,(PQ 118),Tel. 0114313131,"R S Cader, J C A D'Souza, R D Rajapaksa, N I R...",32.57%
56,,,Banking,,,,,,
57,,,,,,Sri Lanka,,"S L Sebastian, C H A W Wickramasuriya, A R Fer...",
58,,,,,,,,"R Shanmuganathan, C K Hettiarachchi, H D Gunet...",

Table 88:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year &,Addresses,Directors,Stated Capital &
1,Group,,Business,,,Country,,,Effective Holding
2,,,,Keells Realtors Ltd *,Owner of Real Estates,1977,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, K C Subasinghe, N N Mawilmada","Rs.75,000,000"
3,,,,,,(PB 90),Tel. 0112152100,,95.81%
4,,,,,,Sri Lanka,,,
5,,,,Mackinnons Keells Ltd*,Rental of office spaces,1952,"No. 4, Layden Bastian Road, Colombo 1","K M Thanthirige, N W R Wijewantha, N N Mawilmada","Rs.327,800,000"
6,,Property Management,,,,(PB 8),Tel. 0112152100,,100%
7,,,,,,Sri Lanka,,,
8,,,,Whittall Boustead (Pvt) Ltd - Real,Renting of office space,1958,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, K C Subasinghe, N N Mawilmada","Rs.99,188,800"
9,,,,Estate Division,,(PV 31),Tel. 0112152100,,100%
10,,,,,,Sri Lanka,,,
11,,,,British Overseas (Pvt) Ltd,"Developer of ""7th Sense"" Residential",2011,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, K C Subasinghe, N N Mawilmada,","Rs.1,000"
12,,,,,Tower,(PV 80203),Tel. 0112152100,"S P G N Rajapakse, D P Gamlath",61%
13,,,,,,Sri Lanka,,,
14,,,,Braybrooke Residential Properties,Investor of Braybrooke Residential Towers,1998,"No.186, Vauxhall Street, Colombo - 02",Y S H R S Silva - Chairperson,"Rs.1,403,970,000"
15,,,,(Pvt) Ltd *,(Pvt) Ltd,(PV19165),Tel. 0112152100,"S Rajendra, K C Subasinghe, N N Mawilmada,",50%
16,,,,,,Sri Lanka,,"D P Gamlath, Y S H I K Silva, C P Palansuriya,",
17,,,,,,,,Y S H H K Silva,
18,,,,Braybrooke Residential Towers,Developer of 'TRI-ZEN' Residential Towers,2017,"No.186, Vauxhall Street, Colombo - 02",Y S H R S Silva - Chairperson,"Rs.3,636,900,000"
19,,,,(Pvt) Ltd *,,(PV128387),Tel. 0112152100,"K N J Balendra, J G A Cooray, S Rajendra,",50%
20,,,,,,Sri Lanka,,"N N Mawilmada, Y S H I K Silva, A D B Talwatte,",
21,,,,,,,,C P Palansuriya,
22,PROPERTY,,,Glennie Properties (Pvt) Ltd *,Property Development,2012,"No.186, Vauxhall Street, Colombo - 02","K C Subasinghe, N N Mawilmada, D P Gamlath,","Rs. 163,861,400"
23,,,,,,(PV 84278),Tel. 0112152100,N W R Wijewantha,100%
24,,,,,,Sri Lanka,,,
25,,,,J K Land (Pvt) Ltd *,Investment Company for Property Sector,2012,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, K C Subasinghe, N N Mawilmada","Rs.24,964,638,930"
26,,,,,,(PV 84272),Tel. 0112152100,,100%
27,,Property Development,,,,Sri Lanka,,,
28,,,,J K Thudella Properties (Pvt) Ltd *,Owner of Real Estates,2018,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, N N Mawilmada","Rs.453,467,620"
29,,,,,,(PV 129825),Tel. 0112152100,,100%
30,,,,,,Sri Lanka,,,
31,,,,John Keells Residential Properties,"Developer of ""On320"" Residential Towers",2010,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, K C Subasinghe,N N Mawilmada","Rs.925,200,000"
32,,,,(Pvt) Ltd,,(PV 75050),Tel. 0112152100,,100%
33,,,,,,Sri Lanka,,,
34,,,,Rajawella Holdings Ltd,"Operates an 18 hole, Donald Street",1991,"P O Box 7, Rajawella, Kandy",K N J Balendra - Chairperson,"Rs.784,690,140"
35,,,,,Designed Golf Course in Digana,(PB27),Tel. 0112152100,"J G A Cooray, S Rajendra, N N Mawilmada, C B T...",49.85%
36,,,,,,Sri Lanka,,"(Alt. C J Holloway), G R Bostock Kirk (Alt. E ...",
37,,,,,,,,S E Captain (Alt. R S Captain),
38,,,,Vauxhall Land Developments (Pvt),Owner of Real Estates,2017,"No.186, Vauxhall Street, Colombo - 02",K N J Balendra - Chairperson,"Rs.21,716,553,910"
39,,,,Ltd *,,(PV125587),Tel. 0112152100,"J G A Cooray, N N Mawilmada, N W R Wijewantha",100%
40,,,,,,Sri Lanka,,,
41,,,,Waterfront Properties (Pvt) Ltd***,"Developer of Hotels,Apartments, offices &",2011,"No.186, Vauxhall Street, Colombo - 02",K N J Balendra - Chairperson,"Rs.152,313,664,645"
42,,,,,Shopping Malls,(PV 82153),Tel. 0112152100,"J G A Cooray, S Rajendra, N N Mawilmada",99.10%
43,,,,,,Sri Lanka,,,
44,,,,Fairfirst Insurance Ltd **,Providers of Non Life insurance solutions,2014,"Access Towers II, 14th Floor, No: 278/4, Union",C Ratnaswami - Chairperson,"Rs.3,131,949,000"
45,,,,,,(PB 5180),"Place, Colombo 02","A S Wijesinha, C D Wijegunawardene, S Malhotra,",19.80%
46,,,,,,Sri Lanka,Tel. 0112428428,"J P Gomes, R M Prabhakar",
47,,,Insurance,,,,,,
48,,,,Union Assurance PLC,Providers of Life insurance solutions,1987,"No.20, St. Michaels' Road, Colombo 3",K N J Balendra - Chairperson,"Rs.1,000,000,000"
49,,,,,,(PQ 12),Tel. 0112990990,"S Rajendra, D P Gamlath, D H Fernando, S A App...",90%
50,,,,,,Sri Lanka,,P T Wanigasekara,
51,FINANCIAL SERVICES,,,John Keells Stock Brokers (Pvt) Ltd,Share broking services,1979,"No. 186,Vauxhall street, Colombo 02","S Rajendra, D P Gamlath, R S Cader","Rs.57,750,000"
52,,,Stock Broking,,,(PV 89),"Tel.0112306250, 0112342066-7",,90.04%
53,,,,,,Sri Lanka,,,
54,,,,Nations Trust Bank PLC **,Commercial banking,1999,"No. 242, Union Place, Colombo 2.",J G A Cooray - Chairperson,"Rs.11,426,882,000"
55,,,,,,(PQ 118),Tel. 0114313131,"R S Cader, J C A D'Souza, R D Rajapaksa, N I R...",32.57%
56,,,Banking,,,,,,
57,,,,,,Sri Lanka,,"S L Sebastian, C H A W Wickramasuriya, A R Fer...",
58,,,,,,,,"R Shanmuganathan, C K Hettiarachchi, H D Gunet...",

Table 89:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year &,Addresses,Directors,Stated Capital &
1,Group,,Business,,,Country,,,Effective Holding
2,,,,John Keells Information,Software services,1998,"No. 148, Vauxhall Street,Colombo 2.",J G A Cooray - Chairperson,"Rs.96,500,000"
3,,,IT Services,Technology (Pvt) Ltd,,(PV 652),Tel. 2300770-77,"K D Weerasinghe, R Shanmuganathan",100%
4,,,,,,Sri Lanka,,,
5,,,,Infomate (Pvt) Ltd,IT enabled services,2005,"No.4, Leyden Bastian Road, Colombo 1","K D Weerasinghe, R Shanmuganathan","Rs.20,000,000"
6,,,,,,(PV 921),Tel. (94) 112149700,,100%
7,,,,,,Sri Lanka,,,
8,,,,John Keells BPO Holdings Private,Holding company of BPO group,2006,"IFS Court, 28, Cybercity, Ebene,Mauritius","Z H Niamut,K Peerbocus, K D Weerasinghe, K C","Rs.1,988,300,000"
9,,Information Technology,,Ltd *,companies,(C 60882),Tel. (230) 467 3000,Subasinghe,100%
10,,,IT Enabled,,,Mauritius,,,
11,,,Services,John Keells BPO International (Pvt),Investment holding company,2007,"IFS Court, 28, Cybercity,Ebene, Mauritius","Z H Niamut, K Peerbocus, K D Weerasinghe,","Rs.1,616,700,008"
12,,,,Ltd *,,(C 070137),Tel. (230) 467 3000,K C Subasinghe,100%
13,,,,,,Mauritius,,,
14,,,,John Keells BPO Solutions Lanka,BPO operations in Sri Lanka,2006,"No.4, Leyden Bastian Road, Colombo 1","K D Weerasinghe, K C Subasinghe, R Shanmuganathan","Rs.335,797,260"
15,,,,(Pvt) Ltd*,,(PV 3458),Tel. (94) 2300770-77,,100%
16,,,,,,Sri Lanka,,,
17,,,,John Keells PLC,Produce Broking and Real Estate,1960,"No. 186, Vauxhall street,Colombo 02",K N J Balendra - Chairperson,"Rs.152,000,000"
18,,,,,Ownership,(PQ 11),Tel. 2306000,"J G A Cooray, K D Weerasinghe, A K Gunawardhana,",86.90%
19,,,,,,Sri Lanka,,"C N Wijewardene, B A I Rajakarier, A Z Hashim",
20,,,,John Keells Teas (Pvt) Ltd,Manager seven bought leaf tea factories,1979,"No.117,Chittampalam A,Gardiner","K D Weerasinghe, K C Subasinghe, A Z Hashim","Rs.120,000"
21,,,,,,(PV 522),"Mawatha,Colombo - 02",,100%
22,,,,,,Sri Lanka,Tel. 2306546,,
23,,Plantation Services,,John Keells Warehousing (Pvt) Ltd,Warehousing of Tea and Rubber,2001,"No.93,1st Avenue, Muturajawela, Hendala, Wattala","K D Weerasinghe, K C Subasinghe, A Z Hashim","Rs.120,000,000"
24,,,,,,(PV 638),Tel. 4819560,,86.90%
25,,,,,,Sri Lanka,,,
26,"OTHER, INCLUDING INFORMATION TECHNOLOGY AND PL...",,,Tea Smallholder Factories PLC,Owner and operator of Bought Leaf,1991,"No.186, Vauxhall street, Colombo 02",K N J Balendra – Chairperson,"Rs.150,000,000"
27,,,,,factories,(PQ 32),Tel. 2149994 / 2335880,"J G A Cooray, E H Wijenaike, A S Jayatilleke,",37.62%
28,,,,,,Sri Lanka,,"S K L Obeyesekere, A K Gunaratne, A Goonetilleke,",
29,,,,,,,,A Z Hashim,
30,,,,Facets (Pvt) Ltd *,Owner of real estate,1974,"No.117,Sir Chittampalam A Gardiner","K M Thanthirige, D P Gamlath","Rs.150,000"
31,,,,,,(PV1048),"Mawatha,Colombo - 02",,100%
32,,,,,,Sri Lanka,Tel. 2306000,,
33,,,,J K Packaging (Pvt) Ltd*,Printing and packaging services provider,1979,"No 148, Vauxhall street,Colombo 02","K C Subasinghe, K D Weerasinghe, D P Gamlath","Rs.14,500,000"
34,,,,,for the export market,(PV 1265),Tel. 2475308,,100%
35,,,,,,Sri Lanka,,,
36,,,,John Keells Holdings PLC,Group holding company & function,1979,"No.117,Sir Chittampalam A Gardiner",K N J Balendra - Chairperson,"Rs.73,187,861,000"
37,,,,,based services,(PQ 14),"Mawatha,Colombo - 02","J G A Cooray - Deputy Chairperson, D A Cabraal,",98.05%
38,,,,,,Sri Lanka,Tel. 2306000,"A N Fonseka, M P Perera, S S H Wijayasuriya, S...",
39,,,,John Keells International (Pvt) Ltd *,Regional holding company providing,2006,"No.117,Chittampalam A,Gardiner","D P Gamlath, K M Thanthirige, N W Tambiah","Rs.1,991,600,000"
40,,Other,,,administrative & function based services,(PV 46),"Mawatha,Colombo - 02",,100%
41,,,,,,Sri Lanka,Tel. 2306000 /2421101-9,,
42,,,,John Keells Singapore (Pte) Ltd *,International trading services,1992,"No.16 Collyer Quay, Level 21, Office Suit No.2...",J G A Cooray - Chairperson,"Rs.9,638,000"
43,,,,,,(199200499C),Singapore 049318,"K M Thanthirige, K C Subasinghe, D P Gamlath,",80%
44,,,,,,Singapore,Tel. 65 63296409/ 65 68189150/ 65 96346593,R Ponnampalam,
45,,,,Keells Consultants (Pvt) Ltd,Company secretarial services to the,1974,"No.117,Chittampalam A,Gardiner","K M Thanthirige, N W Tambiah, I V Gunasekera, C","Rs.160,000"
46,,,,,group,(PB 3 PV),"Mawatha,Colombo - 02",Subasinghe,100%
47,,,,,,Sri Lanka,Tel. 2421101-9,,
48,,,,Mortlake (Pvt) Ltd *,Investment company,1962,"No. 148, Vauxhall Street,Colombo 2.","K M Thanthirige, K C Subasinghe","Rs.5,500"
49,,,,,,(PV 756),Tel. 2475308,,100%
50,,,,,,Sri Lanka,,,

Table 90:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year &,Addresses,Directors,Stated Capital &
1,Group,,Business,,,Country,,,Effective Holding
2,,,,John Keells Information,Software services,1998,"No. 148, Vauxhall Street,Colombo 2.",J G A Cooray - Chairperson,"Rs.96,500,000"
3,,,IT Services,Technology (Pvt) Ltd,,(PV 652),Tel. 2300770-77,"K D Weerasinghe, R Shanmuganathan",100%
4,,,,,,Sri Lanka,,,
5,,,,Infomate (Pvt) Ltd,IT enabled services,2005,"No.4, Leyden Bastian Road, Colombo 1","K D Weerasinghe, R Shanmuganathan","Rs.20,000,000"
6,,,,,,(PV 921),Tel. (94) 112149700,,100%
7,,,,,,Sri Lanka,,,
8,,,,John Keells BPO Holdings Private,Holding company of BPO group,2006,"IFS Court, 28, Cybercity, Ebene,Mauritius","Z H Niamut,K Peerbocus, K D Weerasinghe, K C","Rs.1,988,300,000"
9,,Information Technology,,Ltd *,companies,(C 60882),Tel. (230) 467 3000,Subasinghe,100%
10,,,IT Enabled,,,Mauritius,,,
11,,,Services,John Keells BPO International (Pvt),Investment holding company,2007,"IFS Court, 28, Cybercity,Ebene, Mauritius","Z H Niamut, K Peerbocus, K D Weerasinghe,","Rs.1,616,700,008"
12,,,,Ltd *,,(C 070137),Tel. (230) 467 3000,K C Subasinghe,100%
13,,,,,,Mauritius,,,
14,,,,John Keells BPO Solutions Lanka,BPO operations in Sri Lanka,2006,"No.4, Leyden Bastian Road, Colombo 1","K D Weerasinghe, K C Subasinghe, R Shanmuganathan","Rs.335,797,260"
15,,,,(Pvt) Ltd*,,(PV 3458),Tel. (94) 2300770-77,,100%
16,,,,,,Sri Lanka,,,
17,,,,John Keells PLC,Produce Broking and Real Estate,1960,"No. 186, Vauxhall street,Colombo 02",K N J Balendra - Chairperson,"Rs.152,000,000"
18,,,,,Ownership,(PQ 11),Tel. 2306000,"J G A Cooray, K D Weerasinghe, A K Gunawardhana,",86.90%
19,,,,,,Sri Lanka,,"C N Wijewardene, B A I Rajakarier, A Z Hashim",
20,,,,John Keells Teas (Pvt) Ltd,Manager seven bought leaf tea factories,1979,"No.117,Chittampalam A,Gardiner","K D Weerasinghe, K C Subasinghe, A Z Hashim","Rs.120,000"
21,,,,,,(PV 522),"Mawatha,Colombo - 02",,100%
22,,,,,,Sri Lanka,Tel. 2306546,,
23,,Plantation Services,,John Keells Warehousing (Pvt) Ltd,Warehousing of Tea and Rubber,2001,"No.93,1st Avenue, Muturajawela, Hendala, Wattala","K D Weerasinghe, K C Subasinghe, A Z Hashim","Rs.120,000,000"
24,,,,,,(PV 638),Tel. 4819560,,86.90%
25,,,,,,Sri Lanka,,,
26,"OTHER, INCLUDING INFORMATION TECHNOLOGY AND PL...",,,Tea Smallholder Factories PLC,Owner and operator of Bought Leaf,1991,"No.186, Vauxhall street, Colombo 02",K N J Balendra – Chairperson,"Rs.150,000,000"
27,,,,,factories,(PQ 32),Tel. 2149994 / 2335880,"J G A Cooray, E H Wijenaike, A S Jayatilleke,",37.62%
28,,,,,,Sri Lanka,,"S K L Obeyesekere, A K Gunaratne, A Goonetilleke,",
29,,,,,,,,A Z Hashim,
30,,,,Facets (Pvt) Ltd *,Owner of real estate,1974,"No.117,Sir Chittampalam A Gardiner","K M Thanthirige, D P Gamlath","Rs.150,000"
31,,,,,,(PV1048),"Mawatha,Colombo - 02",,100%
32,,,,,,Sri Lanka,Tel. 2306000,,
33,,,,J K Packaging (Pvt) Ltd*,Printing and packaging services provider,1979,"No 148, Vauxhall street,Colombo 02","K C Subasinghe, K D Weerasinghe, D P Gamlath","Rs.14,500,000"
34,,,,,for the export market,(PV 1265),Tel. 2475308,,100%
35,,,,,,Sri Lanka,,,
36,,,,John Keells Holdings PLC,Group holding company & function,1979,"No.117,Sir Chittampalam A Gardiner",K N J Balendra - Chairperson,"Rs.73,187,861,000"
37,,,,,based services,(PQ 14),"Mawatha,Colombo - 02","J G A Cooray - Deputy Chairperson, D A Cabraal,",98.05%
38,,,,,,Sri Lanka,Tel. 2306000,"A N Fonseka, M P Perera, S S H Wijayasuriya, S...",
39,,,,John Keells International (Pvt) Ltd *,Regional holding company providing,2006,"No.117,Chittampalam A,Gardiner","D P Gamlath, K M Thanthirige, N W Tambiah","Rs.1,991,600,000"
40,,Other,,,administrative & function based services,(PV 46),"Mawatha,Colombo - 02",,100%
41,,,,,,Sri Lanka,Tel. 2306000 /2421101-9,,
42,,,,John Keells Singapore (Pte) Ltd *,International trading services,1992,"No.16 Collyer Quay, Level 21, Office Suit No.2...",J G A Cooray - Chairperson,"Rs.9,638,000"
43,,,,,,(199200499C),Singapore 049318,"K M Thanthirige, K C Subasinghe, D P Gamlath,",80%
44,,,,,,Singapore,Tel. 65 63296409/ 65 68189150/ 65 96346593,R Ponnampalam,
45,,,,Keells Consultants (Pvt) Ltd,Company secretarial services to the,1974,"No.117,Chittampalam A,Gardiner","K M Thanthirige, N W Tambiah, I V Gunasekera, C","Rs.160,000"
46,,,,,group,(PB 3 PV),"Mawatha,Colombo - 02",Subasinghe,100%
47,,,,,,Sri Lanka,Tel. 2421101-9,,
48,,,,Mortlake (Pvt) Ltd *,Investment company,1962,"No. 148, Vauxhall Street,Colombo 2.","K M Thanthirige, K C Subasinghe","Rs.5,500"
49,,,,,,(PV 756),Tel. 2475308,,100%
50,,,,,,Sri Lanka,,,

In [5]:
keywords_1 = ['for the year ended 31 march','total revenue', 'cost of sales', 'gross profit','other operating income','basic']
keywords_2 = ['net assets per share** (rs.)','net assets per share* (rs.)']
# Loop through all the tables
for i, table in enumerate(tables):

    # Convert all cells to lowercase for matching
    table_lower = table.astype(str).apply(lambda col: col.str.lower())
  
    # Dictionary to store matched values
    matched_rows = {}

    for keyword in keywords_1:
        # Find rows containing the keyword
        row = table[table_lower.apply(lambda r: keyword in ' '.join(r), axis=1)]
        if not row.empty:
            matched_rows[keyword] = row.iloc[0, 3]

    if matched_rows:
        print(f"\n✅ Table {i+1} contains financial rows:")
        for k, v in matched_rows.items():
            print(f"{k.title()} (column 3): {v}")
        #display(table)  # Show the full table (optional)
        break
    else:
        print(f"Table {i+1} does not contain any of the target keywords.")



# Loop through all the tables
for i, table in enumerate(tables):
    # Convert all cells to lowercase for matching
    table_lower = table.astype(str).apply(lambda col: col.str.lower())
  
    # Dictionary to store matched values
    matched_rows = {}

    for keyword in keywords_2:
        # Find rows containing the keyword
        row = table[table_lower.apply(lambda r: keyword in ' '.join(r), axis=1)]
        if not row.empty:
            matched_rows[keyword] = row.iloc[0, 1]

    if matched_rows:
        print(f"\n✅ Table {i+1} contains financial rows:")
        for k, v in matched_rows.items():
            print(f"{k.title()} {type(k.title())}(column 1): {v}")
        #display(table)  # Show the full table (optional)
        break
    else:
        print(f"Table {i+1} does not contain any of the target keywords.")

Table 1 does not contain any of the target keywords.
Table 2 does not contain any of the target keywords.
Table 3 does not contain any of the target keywords.
Table 4 does not contain any of the target keywords.
Table 5 does not contain any of the target keywords.
Table 6 does not contain any of the target keywords.
Table 7 does not contain any of the target keywords.
Table 8 does not contain any of the target keywords.
Table 9 does not contain any of the target keywords.
Table 10 does not contain any of the target keywords.
Table 11 does not contain any of the target keywords.
Table 12 does not contain any of the target keywords.
Table 13 does not contain any of the target keywords.
Table 14 does not contain any of the target keywords.
Table 15 does not contain any of the target keywords.
Table 16 does not contain any of the target keywords.
Table 17 does not contain any of the target keywords.
Table 18 does not contain any of the target keywords.
Table 19 does not contain any of the target keywords.
Table 20 does not contain any of the target keywords.
Table 21 does not contain any of the target keywords.
Table 22 does not contain any of the target keywords.
Table 23 does not contain any of the target keywords.
Table 24 does not contain any of the target keywords.
Table 25 does not contain any of the target keywords.
Table 26 does not contain any of the target keywords.
Table 27 does not contain any of the target keywords.
Table 28 does not contain any of the target keywords.
Table 29 does not contain any of the target keywords.
Table 30 does not contain any of the target keywords.
Table 31 does not contain any of the target keywords.
Table 32 does not contain any of the target keywords.
Table 33 does not contain any of the target keywords.
Table 34 does not contain any of the target keywords.
Table 35 does not contain any of the target keywords.
Table 36 does not contain any of the target keywords.
Table 37 does not contain any of the target keywords.
Table 38 does not contain any of the target keywords.
Table 39 does not contain any of the target keywords.
Table 40 does not contain any of the target keywords.
Table 41 does not contain any of the target keywords.
Table 42 does not contain any of the target keywords.
Table 43 does not contain any of the target keywords.
Table 44 does not contain any of the target keywords.
Table 45 does not contain any of the target keywords.
Table 46 does not contain any of the target keywords.
Table 47 does not contain any of the target keywords.

✅ Table 48 contains financial rows:
For The Year Ended 31 March (column 3): 2022
Total Revenue (column 3): 218,074,746
Cost Of Sales (column 3): (180,430,008)
Gross Profit (column 3): 37,644,738
Other Operating Income (column 3): 2,614,793
Table 1 does not contain any of the target keywords.
Table 2 does not contain any of the target keywords.
Table 3 does not contain any of the target keywords.
Table 4 does not contain any of the target keywords.
Table 5 does not contain any of the target keywords.
Table 6 does not contain any of the target keywords.
Table 7 does not contain any of the target keywords.
Table 8 does not contain any of the target keywords.
Table 9 does not contain any of the target keywords.
Table 10 does not contain any of the target keywords.
Table 11 does not contain any of the target keywords.
Table 12 does not contain any of the target keywords.
Table 13 does not contain any of the target keywords.
Table 14 does not contain any of the target keywords.
Table 15 does not contain any of the target keywords.
Table 16 does not contain any of the target keywords.
Table 17 does not contain any of the target keywords.
Table 18 does not contain any of the target keywords.
Table 19 does not contain any of the target keywords.
Table 20 does not contain any of the target keywords.
Table 21 does not contain any of the target keywords.
Table 22 does not contain any of the target keywords.
Table 23 does not contain any of the target keywords.
Table 24 does not contain any of the target keywords.
Table 25 does not contain any of the target keywords.
Table 26 does not contain any of the target keywords.
Table 27 does not contain any of the target keywords.
Table 28 does not contain any of the target keywords.
Table 29 does not contain any of the target keywords.
Table 30 does not contain any of the target keywords.
Table 31 does not contain any of the target keywords.
Table 32 does not contain any of the target keywords.
Table 33 does not contain any of the target keywords.
Table 34 does not contain any of the target keywords.
Table 35 does not contain any of the target keywords.
Table 36 does not contain any of the target keywords.
Table 37 does not contain any of the target keywords.
Table 38 does not contain any of the target keywords.
Table 39 does not contain any of the target keywords.
Table 40 does not contain any of the target keywords.
Table 41 does not contain any of the target keywords.
Table 42 does not contain any of the target keywords.
Table 43 does not contain any of the target keywords.
Table 44 does not contain any of the target keywords.
Table 45 does not contain any of the target keywords.
Table 46 does not contain any of the target keywords.
Table 47 does not contain any of the target keywords.
Table 48 does not contain any of the target keywords.
Table 49 does not contain any of the target keywords.
Table 50 does not contain any of the target keywords.
Table 51 does not contain any of the target keywords.
Table 52 does not contain any of the target keywords.
Table 53 does not contain any of the target keywords.
Table 54 does not contain any of the target keywords.
Table 55 does not contain any of the target keywords.
Table 56 does not contain any of the target keywords.
Table 57 does not contain any of the target keywords.
Table 58 does not contain any of the target keywords.
Table 59 does not contain any of the target keywords.
Table 60 does not contain any of the target keywords.
Table 61 does not contain any of the target keywords.
Table 62 does not contain any of the target keywords.
Table 63 does not contain any of the target keywords.
Table 64 does not contain any of the target keywords.
Table 65 does not contain any of the target keywords.
Table 66 does not contain any of the target keywords.
Table 67 does not contain any of the target keywords.
Table 68 does not contain any of the target keywords.
Table 69 does not contain any of the target keywords.
Table 70 does not contain any of the target keywords.
Table 71 does not contain any of the target keywords.
Table 72 does not contain any of the target keywords.
Table 73 does not contain any of the target keywords.
Table 74 does not contain any of the target keywords.
Table 75 does not contain any of the target keywords.
Table 76 does not contain any of the target keywords.
Table 77 does not contain any of the target keywords.

✅ Table 78 contains financial rows:
Net Assets Per Share* (Rs.) <class 'str'>(column 1): 246.2

In [6]:
# Initialize a list to store extracted data
data_for_csv = []

for i, table in enumerate(tables):
    # Convert all cells to lowercase and strip spaces
    table_lower = table.astype(str).map(lambda x: x.strip().lower())

    # Flag to track if a matching row was found
    found = False

    # Check each row
    for _, row in table_lower.iterrows():
        row_list = row.tolist()
        number_of_count = sum("number of" in cell for cell in row_list)
        percent_count = sum("%" in cell for cell in row_list)
    
        if number_of_count == 2 and percent_count == 2:
            print("Row has at least two 'number of' and two '%' entries")
            display(table)

            # Extract data starting from row 1 (assuming row 0 is header)
            share_holder_names = table.iloc[1:, 0].astype(str).str.strip().tolist()
            share_percentage = table.iloc[1:, 2].astype(str).str.strip().tolist()
            year = [2020] * len(share_holder_names)

            for name, percentage, yr in zip(share_holder_names, share_percentage, year):
                data_for_csv.append([yr, name, percentage])

            print(year)
            print(share_holder_names)
            print(share_percentage)
        

            found = True
            break  # stop checking more rows in the same table

# Save extracted data to CSV
df_csv = pd.DataFrame(data_for_csv, columns=["Year", "Shareholder Name", "Share Percentage"])
df_csv.to_csv("shareholder_data.csv", index=False, mode='a', header=False)

print("Data has been appended to 'shareholder_data.csv'")

Row has at least two 'number of' and two '%' entries

,0,1,2,3,4
0,Top Twenty Shareholders of the Company,,,,
1,,31 March 2023,,31 March 2022,
2,,Number of,%,Number of,%
3,,shares,,shares,
4,Mr S E Captain,"134,044,705",9.68,"134,220,895",9.69
5,Melstacorp PLC,"128,917,111",9.31,"128,917,111",9.31
6,HWIC Asia Fund,"119,200,760",8.61,"119,200,760",8.61
7,Paints and General Industries Limited,"100,717,931",7.27,"140,437,428",10.14
8,Asian Development Bank,"65,042,006",4.70,"65,042,006",4.70
9,Citigroup Global Markets Limited Agency Tradin...,"61,904,939",4.47,"61,904,939",4.47
10,Schroder International Selection Fund,"44,418,290",3.21,"41,974,590",3.03
11,CIC Holdings PLC,"35,338,032",2.55,-,-
12,Aberdeen Standard Asia Focus PLC,"33,398,572",2.41,"28,123,572",2.03
13,Norges Bank Account 2,"31,901,605",2.30,"31,901,605",2.30
14,Sri Lanka Insurance Corporation Limited - Life...,"21,846,511",1.58,"12,270,665",0.89
15,Mr Kandiah Balendra,"19,511,476",1.41,"19,511,476",1.41
16,Employees Trust Fund Board,"18,499,897",1.34,"18,499,897",1.34
17,Mrs C S De Fonseka,"17,606,991",1.27,"17,472,745",1.26
18,Edgbaston Asian Equity Trust,"17,520,023",1.27,"15,142,109",1.09
19,Fidelity Fund - Pacific,"15,244,082",1.10,"17,880,904",1.29
20,Mrs S A J De Fonseka,"15,204,230",1.10,"15,204,230",1.10
21,Polypak Secco Limited,"14,937,924",1.08,-,-
22,Chemanex PLC,"13,105,475",0.95,"12,605,234",0.91
23,Sunsuper Superannuation Fund,"11,587,196",0.84,-,-

[2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020]
['', '', '', 'Mr S E Captain', 'Melstacorp PLC', 'HWIC Asia Fund', 'Paints and General Industries Limited', 'Asian Development Bank', 'Citigroup Global Markets Limited Agency Trading Prop Securities A/C', 'Schroder International Selection Fund', 'CIC Holdings PLC', 'Aberdeen Standard Asia Focus PLC', 'Norges Bank Account 2', 'Sri Lanka Insurance Corporation Limited - Life Fund', 'Mr Kandiah Balendra', 'Employees Trust Fund Board', 'Mrs C S De Fonseka', 'Edgbaston Asian Equity Trust', 'Fidelity Fund - Pacific', 'Mrs S A J De Fonseka', 'Polypak Secco Limited', 'Chemanex PLC', 'Sunsuper Superannuation Fund']
['', '%', '', '9.68', '9.31', '8.61', '7.27', '4.70', '4.47', '3.21', '2.55', '2.41', '2.30', '1.58', '1.41', '1.34', '1.27', '1.27', '1.10', '1.10', '1.08', '0.95', '0.84']
Data has been appended to 'shareholder_data.csv'