In [1]:
# Import necessary libraries
import camelot
import pandas as pd

In [2]:
# Define the extraction function
def extract_tables_from_pdf(file_path):
    """
    Extract useful financial tables (like income statements) from a PDF.
    We only scan page range 170-end to avoid unnecessary noise.
    """
    try:
        # Focus on financial statements pages
        tables = camelot.read_pdf(file_path, pages='130-end', flavor='stream')

        if tables.n == 0:
            print(f"No tables found in {file_path}")
            return []

        useful_tables = []
        keywords = ['total revenue', 'cost of sales', 'operating expenses', 'gross profit','earnings per share', 'net asset','number of shares','%','top twenty shareholders of the company']

        for i, table in enumerate(tables):  
            df = table.df
            # Flatten table text
            table_text = ' '.join(df.apply(lambda row: ' '.join(row), axis=1).tolist()).lower()

            if any(keyword in table_text for keyword in keywords):
                print(f"Selected table {i} (financial content detected)")
                useful_tables.append(df)
            else:
                print(f"Skipped table {i} (non-financial content)")

        if not useful_tables:
            print(f"No financial tables found in {file_path}")

    
        return useful_tables

    except Exception as e:
        print(f"Error extracting tables from {file_path}: {str(e)}")
        return []

In [3]:
# Now, in your Jupyter Notebook:
# Extract the tables from the PDF (replace 'your_pdf_file.pdf' with your actual file path)
file_path = '508_1716290978705.pdf'
tables = extract_tables_from_pdf(file_path)

C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (127.47999999999999, 271.84400000000005, 479.46280000000024, 525.5045555555556)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P1' is an invalid float value
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (32.5197, 144.96550000000005, 564.2315000000001, 458.2597445652173)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P1' is an invalid float value
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (32.5197, 118.46700000000047, 300.9900000000001, 842.8796153846154)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P1' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P1' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P1' is an invalid float value
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (32.5197, 626.133, 299.05200000000013, 839.5817748091604)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (39.60629999999999, 522.09005, 292.19095, 731.8957040816327)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P1' is an invalid float value
Cannot set gray stroke color because /'P2' is an invalid float value
Cannot set gray stroke color because /'P3' is an invalid float value
Cannot set gray stroke color because /'P4' is an invalid float value
Cannot set gray stroke color because /'P5' is an invalid float value
Cannot set gray stroke color because /'P6' is an invalid float value
Cannot set gray stroke color because /'P7' is an invalid float value
Cannot set gray stroke color because /'P8' is an invalid float value
Cannot set gray stroke color because /'P9' is an invalid float value
Cannot set gray stroke color because /'P10' is an invalid float value
Cannot set gray stroke color because /'P11' is an invalid float value
Cannot set gray stroke color because /'P12' is an invalid float value
Cannot set gray stroke color because /'P13' is an invalid float value
Cannot set gray stroke color because /'P14' is an invalid float value
Cannot set gray stroke color because /'P15' is an invalid float value
Cannot set gray stroke color because /'P16' is an invalid float value
Cannot set gray stroke color because /'P17' is an invalid float value
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (32.5197, 682.366, 563.0628500000005, 840.303932038835)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P1' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (127.47999999999999, 407.2705, 468.19180000000017, 560.55525)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (32.5197, 364.80650000000026, 331.6075999999998, 843.7082352941177)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P1' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (39.6508, 631.9815, 550.0795500000004, 777.0234384765625)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P1' is an invalid float value
Cannot set gray stroke color because /'P2' is an invalid float value
Cannot set gray stroke color because /'P3' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (41.0236, 458.8840000000002, 549.2805000000002, 611.5765000000001)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (41.0236, 410.02050000000025, 560.68285, 785.0210000000001)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P1' is an invalid float value
Cannot set gray stroke color because /'P2' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P1' is an invalid float value
Cannot set gray stroke color because /'P2' is an invalid float value
Cannot set gray stroke color because /'P3' is an invalid float value
Cannot set gray stroke color because /'P4' is an invalid float value
Cannot set gray stroke color because /'P5' is an invalid float value
Cannot set gray stroke color because /'P0' is an invalid float value
Cannot set gray stroke color because /'P1' is an invalid float value
Cannot set gray stroke color because /'P2' is an invalid float value
Cannot set gray stroke color because /'P3' is an invalid float value
Cannot set gray stroke color because /'P4' is an invalid float value
Cannot set gray stroke color because /'P5' is an invalid float value
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:218: UserWarning: No tables found on page-264
  if self._document_has_no_text():
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.276, 841.89)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.276, 841.89)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)

Selected table 0 (financial content detected)
Selected table 1 (financial content detected)
Selected table 2 (financial content detected)
Selected table 3 (financial content detected)
Selected table 4 (financial content detected)
Selected table 5 (financial content detected)
Skipped table 6 (non-financial content)
Skipped table 7 (non-financial content)
Selected table 8 (financial content detected)
Skipped table 9 (non-financial content)
Skipped table 10 (non-financial content)
Skipped table 11 (non-financial content)
Selected table 12 (financial content detected)
Selected table 13 (financial content detected)
Selected table 14 (financial content detected)
Skipped table 15 (non-financial content)
Selected table 16 (financial content detected)
Selected table 17 (financial content detected)
Skipped table 18 (non-financial content)
Selected table 19 (financial content detected)
Selected table 20 (financial content detected)
Skipped table 21 (non-financial content)
Selected table 22 (financial content detected)
Skipped table 23 (non-financial content)
Selected table 24 (financial content detected)
Selected table 25 (financial content detected)
Selected table 26 (financial content detected)
Selected table 27 (financial content detected)
Selected table 28 (financial content detected)
Skipped table 29 (non-financial content)
Selected table 30 (financial content detected)
Selected table 31 (financial content detected)
Skipped table 32 (non-financial content)
Skipped table 33 (non-financial content)
Selected table 34 (financial content detected)
Skipped table 35 (non-financial content)
Selected table 36 (financial content detected)
Selected table 37 (financial content detected)
Skipped table 38 (non-financial content)
Skipped table 39 (non-financial content)
Skipped table 40 (non-financial content)
Selected table 41 (financial content detected)
Selected table 42 (financial content detected)
Selected table 43 (financial content detected)
Selected table 44 (financial content detected)
Skipped table 45 (non-financial content)
Selected table 46 (financial content detected)
Selected table 47 (financial content detected)
Skipped table 48 (non-financial content)
Skipped table 49 (non-financial content)
Selected table 50 (financial content detected)
Skipped table 51 (non-financial content)
Selected table 52 (financial content detected)
Skipped table 53 (non-financial content)
Skipped table 54 (non-financial content)
Selected table 55 (financial content detected)
Selected table 56 (financial content detected)
Selected table 57 (financial content detected)
Selected table 58 (financial content detected)
Selected table 59 (financial content detected)
Selected table 60 (financial content detected)
Selected table 61 (financial content detected)
Selected table 62 (financial content detected)
Selected table 63 (financial content detected)
Selected table 64 (financial content detected)
Selected table 65 (financial content detected)
Selected table 66 (financial content detected)
Selected table 67 (financial content detected)
Selected table 68 (financial content detected)
Selected table 69 (financial content detected)
Selected table 70 (financial content detected)
Skipped table 71 (non-financial content)
Selected table 72 (financial content detected)
Skipped table 73 (non-financial content)
Skipped table 74 (non-financial content)
Skipped table 75 (non-financial content)
Selected table 76 (financial content detected)
Selected table 77 (financial content detected)
Selected table 78 (financial content detected)
Selected table 79 (financial content detected)
Selected table 80 (financial content detected)
Skipped table 81 (non-financial content)
Selected table 82 (financial content detected)
Selected table 83 (financial content detected)
Selected table 84 (financial content detected)
Selected table 85 (financial content detected)
Skipped table 86 (non-financial content)
Skipped table 87 (non-financial content)
Skipped table 88 (non-financial content)
Skipped table 89 (non-financial content)
Skipped table 90 (non-financial content)
Skipped table 91 (non-financial content)
Skipped table 92 (non-financial content)
Skipped table 93 (non-financial content)
Skipped table 94 (non-financial content)
Selected table 95 (financial content detected)
Skipped table 96 (non-financial content)
Selected table 97 (financial content detected)
Selected table 98 (financial content detected)
Selected table 99 (financial content detected)
Selected table 100 (financial content detected)
Selected table 101 (financial content detected)
Selected table 102 (financial content detected)
Skipped table 103 (non-financial content)
Skipped table 104 (non-financial content)
Selected table 105 (financial content detected)
Skipped table 106 (non-financial content)
Skipped table 107 (non-financial content)
Skipped table 108 (non-financial content)
Selected table 109 (financial content detected)
Selected table 110 (financial content detected)
Selected table 111 (financial content detected)
Selected table 112 (financial content detected)
Selected table 113 (financial content detected)
Selected table 114 (financial content detected)
Selected table 115 (financial content detected)
Selected table 116 (financial content detected)
Skipped table 117 (non-financial content)
Selected table 118 (financial content detected)
Selected table 119 (financial content detected)
Selected table 120 (financial content detected)
Selected table 121 (financial content detected)
Selected table 122 (financial content detected)
Selected table 123 (financial content detected)
Selected table 124 (financial content detected)
Selected table 125 (financial content detected)
Selected table 126 (financial content detected)
Selected table 127 (financial content detected)
Selected table 128 (financial content detected)
Selected table 129 (financial content detected)
Selected table 130 (financial content detected)
Selected table 131 (financial content detected)
Skipped table 132 (non-financial content)
Skipped table 133 (non-financial content)
Selected table 134 (financial content detected)
Selected table 135 (financial content detected)
Skipped table 136 (non-financial content)
Skipped table 137 (non-financial content)
Skipped table 138 (non-financial content)
Selected table 139 (financial content detected)
Selected table 140 (financial content detected)
Selected table 141 (financial content detected)
Selected table 142 (financial content detected)
Selected table 143 (financial content detected)
Selected table 144 (financial content detected)
Selected table 145 (financial content detected)
Skipped table 146 (non-financial content)
Skipped table 147 (non-financial content)
Selected table 148 (financial content detected)
Selected table 149 (financial content detected)
Skipped table 150 (non-financial content)
Selected table 151 (financial content detected)
Skipped table 152 (non-financial content)
Skipped table 153 (non-financial content)
Skipped table 154 (non-financial content)
Skipped table 155 (non-financial content)
Skipped table 156 (non-financial content)
Skipped table 157 (non-financial content)
Skipped table 158 (non-financial content)
Skipped table 159 (non-financial content)
Skipped table 160 (non-financial content)
Skipped table 161 (non-financial content)
Skipped table 162 (non-financial content)
Skipped table 163 (non-financial content)
Skipped table 164 (non-financial content)
Skipped table 165 (non-financial content)
Skipped table 166 (non-financial content)
Selected table 167 (financial content detected)
Skipped table 168 (non-financial content)
Skipped table 169 (non-financial content)
Skipped table 170 (non-financial content)
Skipped table 171 (non-financial content)
Skipped table 172 (non-financial content)
Skipped table 173 (non-financial content)
Skipped table 174 (non-financial content)
Skipped table 175 (non-financial content)
Skipped table 176 (non-financial content)
Skipped table 177 (non-financial content)
Skipped table 178 (non-financial content)
Selected table 179 (financial content detected)
Skipped table 180 (non-financial content)
Selected table 181 (financial content detected)
Skipped table 182 (non-financial content)
Selected table 183 (financial content detected)
Skipped table 184 (non-financial content)
Skipped table 185 (non-financial content)
Skipped table 186 (non-financial content)
Skipped table 187 (non-financial content)
Skipped table 188 (non-financial content)
Skipped table 189 (non-financial content)
Skipped table 190 (non-financial content)
Skipped table 191 (non-financial content)
Skipped table 192 (non-financial content)
Skipped table 193 (non-financial content)
Skipped table 194 (non-financial content)
Skipped table 195 (non-financial content)
Skipped table 196 (non-financial content)
Skipped table 197 (non-financial content)
Skipped table 198 (non-financial content)
Skipped table 199 (non-financial content)
Skipped table 200 (non-financial content)
Skipped table 201 (non-financial content)
Skipped table 202 (non-financial content)
Skipped table 203 (non-financial content)
Skipped table 204 (non-financial content)
Skipped table 205 (non-financial content)
Skipped table 206 (non-financial content)
Skipped table 207 (non-financial content)
Skipped table 208 (non-financial content)
Skipped table 209 (non-financial content)
Skipped table 210 (non-financial content)
Skipped table 211 (non-financial content)
Skipped table 212 (non-financial content)
Skipped table 213 (non-financial content)
Skipped table 214 (non-financial content)
Skipped table 215 (non-financial content)
Skipped table 216 (non-financial content)
Skipped table 217 (non-financial content)
Selected table 218 (financial content detected)
Skipped table 219 (non-financial content)
Skipped table 220 (non-financial content)
Skipped table 221 (non-financial content)
Skipped table 222 (non-financial content)
Skipped table 223 (non-financial content)
Skipped table 224 (non-financial content)
Skipped table 225 (non-financial content)
Skipped table 226 (non-financial content)
Skipped table 227 (non-financial content)
Skipped table 228 (non-financial content)
Skipped table 229 (non-financial content)
Skipped table 230 (non-financial content)
Skipped table 231 (non-financial content)
Skipped table 232 (non-financial content)
Selected table 233 (financial content detected)
Skipped table 234 (non-financial content)
Skipped table 235 (non-financial content)
Selected table 236 (financial content detected)
Skipped table 237 (non-financial content)
Skipped table 238 (non-financial content)
Skipped table 239 (non-financial content)
Skipped table 240 (non-financial content)
Skipped table 241 (non-financial content)
Skipped table 242 (non-financial content)
Skipped table 243 (non-financial content)
Skipped table 244 (non-financial content)
Skipped table 245 (non-financial content)
Skipped table 246 (non-financial content)
Selected table 247 (financial content detected)
Skipped table 248 (non-financial content)
Skipped table 249 (non-financial content)
Skipped table 250 (non-financial content)
Skipped table 251 (non-financial content)
Skipped table 252 (non-financial content)
Skipped table 253 (non-financial content)
Skipped table 254 (non-financial content)
Skipped table 255 (non-financial content)
Skipped table 256 (non-financial content)
Skipped table 257 (non-financial content)
Selected table 258 (financial content detected)
Skipped table 259 (non-financial content)
Skipped table 260 (non-financial content)
Skipped table 261 (non-financial content)
Skipped table 262 (non-financial content)
Skipped table 263 (non-financial content)
Skipped table 264 (non-financial content)
Selected table 265 (financial content detected)
Selected table 266 (financial content detected)
Skipped table 267 (non-financial content)
Skipped table 268 (non-financial content)
Skipped table 269 (non-financial content)
Skipped table 270 (non-financial content)
Selected table 271 (financial content detected)
Skipped table 272 (non-financial content)
Skipped table 273 (non-financial content)
Skipped table 274 (non-financial content)
Skipped table 275 (non-financial content)
Skipped table 276 (non-financial content)
Skipped table 277 (non-financial content)
Skipped table 278 (non-financial content)
Skipped table 279 (non-financial content)
Skipped table 280 (non-financial content)
Skipped table 281 (non-financial content)
Skipped table 282 (non-financial content)
Skipped table 283 (non-financial content)
Skipped table 284 (non-financial content)
Skipped table 285 (non-financial content)
Skipped table 286 (non-financial content)
Skipped table 287 (non-financial content)
Skipped table 288 (non-financial content)
Skipped table 289 (non-financial content)
Skipped table 290 (non-financial content)
Selected table 291 (financial content detected)
Skipped table 292 (non-financial content)
Selected table 293 (financial content detected)
Skipped table 294 (non-financial content)
Skipped table 295 (non-financial content)
Selected table 296 (financial content detected)
Selected table 297 (financial content detected)
Selected table 298 (financial content detected)
Selected table 299 (financial content detected)
Skipped table 300 (non-financial content)
Skipped table 301 (non-financial content)
Skipped table 302 (non-financial content)
Skipped table 303 (non-financial content)
Skipped table 304 (non-financial content)
Skipped table 305 (non-financial content)
Skipped table 306 (non-financial content)
Selected table 307 (financial content detected)
Selected table 308 (financial content detected)
Skipped table 309 (non-financial content)
Skipped table 310 (non-financial content)
Skipped table 311 (non-financial content)
Skipped table 312 (non-financial content)
Skipped table 313 (non-financial content)
Skipped table 314 (non-financial content)
Skipped table 315 (non-financial content)
Skipped table 316 (non-financial content)
Skipped table 317 (non-financial content)
Skipped table 318 (non-financial content)
Selected table 319 (financial content detected)
Skipped table 320 (non-financial content)
Selected table 321 (financial content detected)
Selected table 322 (financial content detected)
Skipped table 323 (non-financial content)
Skipped table 324 (non-financial content)
Selected table 325 (financial content detected)
Skipped table 326 (non-financial content)
Skipped table 327 (non-financial content)
Skipped table 328 (non-financial content)
Skipped table 329 (non-financial content)
Skipped table 330 (non-financial content)
Skipped table 331 (non-financial content)
Skipped table 332 (non-financial content)
Selected table 333 (financial content detected)
Selected table 334 (financial content detected)
Skipped table 335 (non-financial content)
Skipped table 336 (non-financial content)
Skipped table 337 (non-financial content)
Skipped table 338 (non-financial content)
Selected table 339 (financial content detected)
Skipped table 340 (non-financial content)
Skipped table 341 (non-financial content)
Skipped table 342 (non-financial content)
Skipped table 343 (non-financial content)
Selected table 344 (financial content detected)
Skipped table 345 (non-financial content)
Skipped table 346 (non-financial content)
Skipped table 347 (non-financial content)
Skipped table 348 (non-financial content)
Skipped table 349 (non-financial content)
Selected table 350 (financial content detected)
Skipped table 351 (non-financial content)
Selected table 352 (financial content detected)
Selected table 353 (financial content detected)
Skipped table 354 (non-financial content)
Selected table 355 (financial content detected)
Selected table 356 (financial content detected)
Selected table 357 (financial content detected)
Skipped table 358 (non-financial content)
Skipped table 359 (non-financial content)
Skipped table 360 (non-financial content)
Skipped table 361 (non-financial content)
Skipped table 362 (non-financial content)
Selected table 363 (financial content detected)
Skipped table 364 (non-financial content)
Selected table 365 (financial content detected)
Selected table 366 (financial content detected)
Skipped table 367 (non-financial content)
Selected table 368 (financial content detected)
Skipped table 369 (non-financial content)
Selected table 370 (financial content detected)
Skipped table 371 (non-financial content)
Selected table 372 (financial content detected)
Skipped table 373 (non-financial content)
Skipped table 374 (non-financial content)
Skipped table 375 (non-financial content)
Skipped table 376 (non-financial content)
Skipped table 377 (non-financial content)
Selected table 378 (financial content detected)
Selected table 379 (financial content detected)
Selected table 380 (financial content detected)
Skipped table 381 (non-financial content)
Skipped table 382 (non-financial content)
Skipped table 383 (non-financial content)
Skipped table 384 (non-financial content)
Selected table 385 (financial content detected)
Skipped table 386 (non-financial content)
Skipped table 387 (non-financial content)
Skipped table 388 (non-financial content)
Skipped table 389 (non-financial content)
Skipped table 390 (non-financial content)
Skipped table 391 (non-financial content)
Skipped table 392 (non-financial content)
Selected table 393 (financial content detected)
Selected table 394 (financial content detected)
Selected table 395 (financial content detected)
Selected table 396 (financial content detected)
Skipped table 397 (non-financial content)
Skipped table 398 (non-financial content)
Skipped table 399 (non-financial content)
Selected table 400 (financial content detected)
Selected table 401 (financial content detected)
Selected table 402 (financial content detected)
Skipped table 403 (non-financial content)
Skipped table 404 (non-financial content)
Skipped table 405 (non-financial content)
Skipped table 406 (non-financial content)
Selected table 407 (financial content detected)
Selected table 408 (financial content detected)
Selected table 409 (financial content detected)
Selected table 410 (financial content detected)
Selected table 411 (financial content detected)
Selected table 412 (financial content detected)
Selected table 413 (financial content detected)
Selected table 414 (financial content detected)
Selected table 415 (financial content detected)
Selected table 416 (financial content detected)
Skipped table 417 (non-financial content)
Skipped table 418 (non-financial content)
Skipped table 419 (non-financial content)
Skipped table 420 (non-financial content)
Skipped table 421 (non-financial content)
Skipped table 422 (non-financial content)
Skipped table 423 (non-financial content)
Skipped table 424 (non-financial content)
Skipped table 425 (non-financial content)
Skipped table 426 (non-financial content)
Skipped table 427 (non-financial content)
Skipped table 428 (non-financial content)
Skipped table 429 (non-financial content)
Skipped table 430 (non-financial content)
Skipped table 431 (non-financial content)
Skipped table 432 (non-financial content)
Skipped table 433 (non-financial content)
Skipped table 434 (non-financial content)
Skipped table 435 (non-financial content)

In [4]:
# Show each table in a DataFrame
if tables:
    for i, table in enumerate(tables):
        print(f"Table {i + 1}:")
        display(table)  # This will display the table in a Jupyter notebook cell
else:
    print("No tables to display.")

Table 1:

,0,1,2,3,4,5
0,SHARE INFORMATION,,,,,
1,Market Capitalisation and Enterprise Value,Summary Indicators,,,,
2,The market capitalisation of the Company incre...,,,,,
3,,,,2023/24,2022/23,2021/22
4,Rs.290.77 billion as at 31 March 2024 [2022/23...,,,,,
5,by a rise in the Company share price. As at th...,Market capitalisation,(Rs.billion),290.8,193.9,201.0
6,represented 6.4% of the total market capitalis...,,,,,
7,,Enterprise value,(Rs.billion),450.0,339.2,312.0
8,[2022/23: 5.0%].,,,,,
9,,EV/EBITDA,(times),10.0,7.6,10.7
10,The enterprise value of the Group increased by...,Diluted EPS,(Rs.),8.0,13.1,15.1
11,as at 31 March 2024 [2022/23: Rs.339.23 billion].,Diluted PER,(times),24.1,10.7,9.6
12,,Price to book,(times),0.8,0.6,0.6
13,"As at 31 March 2024, JKH had a float-adjusted ...",,,,,
14,,Price/cash earnings,(times),13.2,7.3,4.7
15,"Rs.194.00 billion and 14,087 public shareholde...",,,,,
16,is compliant under option 1 of the minimum thr...,Dividend yield,(%),0.8,1.4,1.0
17,"for the Main Board of the CSE, as per the dire...",Group dividend,,,,
18,Section 13 (c) and 13 (cc) of the SEC Act No.3...,payout ratio,(%),18.5,15.2,10.0
19,November 2016.,,,,,
20,,Net assets per share,(Rs.),238.8,246.2,224.8
21,,TSR,(%),40.7,(1.4),(1.8)
22,Market Capitalisation and Enterprise Value,,,,,
23,(Rs.billion),,,,,
24,,Price Earnings Ratio,,,,

Table 2:

,0,1,2,3,4,5,6,7
0,,,,,,Net assets per share\n(Rs.),238.8 \n246.2,224.8
1,,,,,,TSR \n(%),40.7\n(1.4),(1.8)
2,Market Capitalisation and Enterprise Value,,,,,,,
3,(Rs.billion),,,,,,,
4,,,,,,Price Earnings Ratio,,
5,500,,,,450,,,
6,,,,,,,2023/24,2022/23
7,400,,,339,,,,
8,,,312,,291,JKH,24.1,10.7
9,300,245,,,,,,
10,,,,,,CSE,9.9,5.0
11,186,196,201,194,,SENSEX,25.2,22.2
12,152\n200,,,,,,,
13,,,,,,KLSE,21.1,16.4
14,100,,,,,,,
15,,,,,,JCI,26.8,11.8
16,,,,,,STI,17.8,12.6
17,0,,,,,,,
18,FY20,FY21,FY22,FY23,FY24,,,

Table 3:

,0,1,2,3,4,5,6
0,,,31 March 2024,,,31 March 2023,
1,,Number of,Number of,%,Number of,Number of,%
2,,shareholders,shares,,shareholders,shares,
3,Non-Resident,,,,,,
4,Institutions,68,"628,555,219",42,73,"515,773,768",37
5,Individuals,235,"8,224,782",1,250,"10,240,144",1
6,Total Non-Resident,303,"636,780,001",42,323,"526,013,912",38
7,Resident,,,,,,
8,Institutions,660,"484,215,442",32,720,"477,354,563",34
9,Individuals*,"13,128","377,824,264",25,"14,061","381,548,157",28
10,Total Resident,"13,788","862,039,706",58,"14,781","858,902,720",62
11,Total,"14,091","1,498,819,707",100,"15,104","1,384,916,632",100

Table 4:

,0,1,2,3,4,5,6,7,8
0,Distribution of Shareholders,,,,,,,,
1,,,31 March 2024,,,,31 March 2023,,
2,,Number of,%,Number of,%,Number of,%,Number of,%
3,,shareholders,,shares held,,shareholders,,shares held,
4,"Less than or equal to 1,000","9,525",68,"1,863,908",0,"10,028",66,"2,139,812",0
5,"1,001 to 10,000","3,008",21,"10,995,300",1,"3,406",23,"12,421,138",1
6,"10,001 to 100,000","1,195",8,"36,555,791",2,"1,297",9,"40,535,936",3
7,"100,001 to 1,000,000",266,2,"79,979,916",5,267,2,"79,734,447",6
8,"Over 1,000,001",97,1,"1,369,424,792",91,106,1,"1,250,085,299",90
9,Total,"14,091",100,"1,498,819,707",100,"15,104",100,"1,384,916,632",100

Table 5:

,0,1,2,3,4
0,Top Twenty Shareholders of the Company,,,,
1,,31 March 2024,,31 March 2023,
2,,Number of,%,Number of,%
3,,shares,,shares,
4,HWIC Asia Fund,"291,105,699",19.42,"119,200,760",8.61
5,Melstacorp PLC,"128,917,111",8.60,"128,917,111",9.31
6,Mr S E Captain,"122,615,194",8.18,"134,044,705",9.68
7,Paints & General Industries Limited,"87,021,832",5.81,"100,717,931",7.27
8,CIC Holdings PLC,"85,365,926",5.70,"35,338,032",2.55
9,Asian Development Bank,"65,042,006",4.34,"65,042,006",4.70
10,Schroder International Selection Fund,"44,418,290",2.96,"44,418,290",3.21
11,Aberdeen Standard Asia Focus PLC,"35,038,572",2.34,"33,398,572",2.41
12,Norges Bank Account 2,"33,087,774",2.21,"31,901,605",2.30
13,Polypak Secco Limited,"31,587,170",2.11,"14,937,924",1.08
14,Mr Kandiah Balendra,"19,511,476",1.30,"19,511,476",1.41
15,Mrs C S De Fonseka,"17,606,991",1.17,"17,606,991",1.27
16,Emrevival Master Fund LP,"15,983,048",1.07,-,-
17,Mrs S A J De Fonseka,"15,254,730",1.02,"15,204,230",1.10
18,Hostplus Pooled Superannuation Trust,"15,152,416",1.01,"10,393,158",0.75
19,Chemanex PLC,"15,064,515",1.01,"13,105,475",0.95
20,Edgbaston Asian Equity Trust,"14,209,110",0.95,"17,520,023",1.27
21,Employees Trust Fund Board,"12,989,299",0.87,"18,499,897",1.34
22,Sunsuper Superannuation Fund,"12,964,947",0.87,"11,587,196",0.84
23,Mr K N J Balendra,"10,907,628",0.73,"10,907,628",0.79

Table 6:

,0,1,2,3,4,5,6
0,Share Capital,,,"GDR History (in terms of ordinary shares, mill...",,,
1,Year ended 31 March,Number of shares in,Year ended,Opening,Issued*,Converted/,Closing
2,,issue (million),31 March,balance,,repurchased,balance**
3,2012,844.12,2012,0.95,0.32,0.08,1.19
4,2013,857.24,2013,1.19,-,0.06,1.13
5,2014,990.29,2014,1.13,-,0.01,1.12
6,2015,997.49,2015,1.12,-,-,1.12
7,2016,1189.4,2016,1.12,-,-,1.12
8,2017,"1,387.47",2017,1.12,0.2,-,1.32
9,2018,"1,387.53",2018,1.32,-,-,1.32
10,2019,"1,318.17",2019,1.32,-,-,1.32
11,2020,"1,318.55",2020,1.32,-,-,1.32
12,2021,"1,319.66",2021,1.32,-,-,1.32
13,2022,"1,384.92",2022,1.32,-,-,1.32
14,2023,"1,384.92",2023,1.32,-,-,1.32
15,2024,"1,498.82",2024,1.32,-,-,1.32

Table 7:

                                                    0
0                                   Award 2.18\nOther
1                    3,352,465\n3,352,465\nExecutives
2                        Total\n43,904,260\n4,099,048
3   1 \nGEC comprises of the Executive Directors a...
4   2 \nAdjusted for Bonus Issues/Right Issues/Sub...
5   3 \nPlan 10 (Award 1) - 100% of the options ha...
6   4 \nPlan 10 (Award 2) - 75% of the options had...
7   5 \nPlan 10 (Award 3) - 50% of the options had...
8   6 \nPlan 11 (Award 1) - 25% of the options had...
9   7 \nPlan 11 (Award 2) - 25% of the options had...
10  8 \nPlan 11 (Award 2.1) - None of the options ...

Table 8:

,0,1,2,3,4,5,6
0,Ports and Shipping,,,,,,
1,y,Operation of a container terminal at the Port of,,,,,
2,,Colombo as a public-private partnership on a b...,,,,,
3,,operate and transfer basis through South Asia,,,,,
4,,Gateway Terminals (SAGT).,,,,,
...,...,...,...,...,...,...,...
68,,,Social and Relationship Capital,,,,
69,,,Community Services and Infrastructure,,,,
70,,EBIT\n25%,,,,,
71,,,Projects 4,Rs.'000,"11,075","12,051","5,317"
72,,,1.,Revenue is inclusive of the Group's share of e...,,,

Table 9:

,0,1,2,3
0,,,,Social and Relationship Capital
1,,,,Community Services and Infrastructure
2,,25%,EBIT,
3,,,,"Rs.'000\n 11,075\n 12,051 \n 5,317 \nProjects 4"
4,,,,1. \nRevenue is inclusive of the Group's share...
5,,,,
6,4%,,Capital Employed,
7,,,,2. \nExcludes lease liabilities.
8,,,,"3. \nFor equity accounted investees, capital e..."
9,,,,these companies. This is inclusive of lease li...
10,,,,
11,7%,,Carbon Footprint,
12,,,,4. \nOnly the contribution to John Keells Foun...

Table 10:

,0,1,2
0,TRANSPORTATION,,
1,External Environment and Operational Review,,
2,,,• \nThe construction of the second phase of Ea...
3,,,Terminal (ECT) continued during CY2023. Extend...
4,Macroeconomic Update,,
5,,,"hectares and a quay length of 1,320 meters and..."
6,y,Global trade of goods and services witnessed a...,
7,,,"gantry cranes and 40-yard cranes, second phase..."
8,,5% in CY2023 compared to a growth of 12% in CY...,
9,,,to be completed by end CY 2025.
10,,primarily due to decreased demand in developed...,
11,,underperformance of the East Asian economies a...,
12,,,Refer the Ports and Shipping section for a det...
13,,"in commodity prices, which collectively contri...",
14,,contraction in the trade of goods (United Nati...,
15,,on Trade and Development (UNCTAD)).,"• Upon the completion of both terminals, the ..."
16,,,capacity of the POC is expected to enhance by ...
17,y,"Merchandise trade stood at USD 24 trillion, a ...",
18,,,TEUs.
19,,against the previous year with merchandise tra...,
20,,both exports and imports contracting as per UN...,
21,,,Ports and Shipping
22,y,"From the end of CY2023, global maritime trade ...",
23,,marked by major disruptions as ships entering ...,South Asia Gateway Terminal
24,,and sailing through the Red Sea and the Suez C...,
25,,,"During the year under review, the Group's Port..."
26,,attacks by Yemen-based Houthis. The security t...,
27,,,"SAGT, recorded a 7% increase in TEUs to 1.82 m..."
28,,Sea have caused a significant redirection of s...,
29,,,"million TEUs], in line with the volume increas..."
30,,transits through the Cape of Good Hope.,
31,,,POC. The volume increase was mainly driven by ...
32,,"For a detailed discussion, refer the Outlook s...",Volume growth at the POC and SAGT was very str...
33,,page 107.,quarter of the year given the higher vessel mo...
34,,,on account of the Red Sea crisis.
35,,Key Policy and Regulatory Highlights,

Table 11:

,0,1,2,3
0,,,,Domestic:Transshipment volumes
1,,"equivalent units (TEUs) in 2023/24, an 11% inc...",,FY23: 12:88\nFY23: 13:87\nFY23: 13:87\nFY23: 1...
2,,,,FY24: 10:90\nFY24: 11:89\nFY24: 10:90\nFY24: 1...
3,,handled against the previous year [2022/23: de...,,
4,,,,FY21\nFY22\nFY23\nFY24
5,,All terminals of the POC recorded an increase ...,,
6,,handling volumes.,,
7,,,y,Volumes in the first quarter recorded a 1% inc...
8,,• Domestic TEU volumes increased by 11% durin...,,comparison to the same quarter of the previous...
9,,[2022/23: degrowth of 22%] and Transshipment v...,,by an increase in transshipment volumes. Domes...
10,,increased by 10% in 2023/24 [2022/23: degrowth...,,recorded a decline due to the import restricti...
11,,,,in place.
12,,• Domestic: transshipment mix stood at 14:86 ...,,
13,,[2022/23: 14:86].,,
14,,,y,"During the second quarter, SAGT witnessed a 10..."
15,,• Overall POC capacity utilisation was ~86% f...,,in overall volumes surpassing the volume growt...
16,,[2022/23: ~78%].,,"8%, driven by a growth in transshipment volumes."
17,y,Capacity enhancements at the POC:,y,Volumes noted a 3% increase in the third quart...
18,,,,to a growth in transshipment volumes by 5%.
19,,• Construction work of the West Container Ter...,,
20,,at the Colombo Port continued during CY2023 an...,y,As a result of the geopolitical conflict in th...
21,,phase of the project is set to be completed by...,,recorded a 13% increase in volumes in the four...
22,,quarter of 2024/25.,,increase in volumes was driven by transshipmen...

Table 12:

,0,1,2
0,Whilst SAGT recorded a strong volume growth fo...,,
1,,Structure,Completion timelines
2,was impacted due to a change in the volume mix...,,
3,,"y\nBuild, operate and transfer",y\nPhase 1 (800m) –
4,"domestic import volumes, while ancillary reven...",,
5,,(BOT),Q4 2024/25
6,"levels witnessed last year. Further, performan...",,
7,,y\nLease period – 35 years,y\nPhase 2 (600m) –
8,translation impact stemming from the appreciat...,,
9,,,mid-2026
10,"by ~11% on average, both in terms of revenue a...",,
11,It should be noted that SAGT recognised a one-...,,
12,amounting to Rs.1.20 billion in 2023/24 whilst...,,
13,off deferred tax charge amounting to Rs.1.35 b...,,
14,"significant change in income tax rates, as the...",,
15,,Features,Shareholding
16,accounted investees are consolidated net of al...,,
17,,y Deep-water terminal with,y\nAdani Ports & Special
18,,"a quay length of 1,400",Economic Zone - 51%
19,"During the year under review, SAGT updated its...",,
20,,"meters, an alongside",y\nJohn Keells Holdings - 34%
21,to improve functionality resulting in greater ...,,
22,,depth of 20 meters,y\nSri Lanka Ports Authority
23,operations. SAGT also introduced a digital saf...,,
24,,y Handling capacity of,- 15%
25,provides one centralised location to record an...,,
26,,~3.2 million TEUs,
27,within the organisation such as incident repor...,,
28,SAGT is in the process of gate automation whic...,,
29,efficiency and improve truck turnaround times....,,
30,eliminate the risk to staff who presently carr...,,
31,"of containers. Additionally, SAGT plans to ins...",,
32,recognition (OCR) scanners at the quayside and...,,
33,will allow containers to be scanned when enter...,,
34,terminal as well as identify and record the ex...,,
35,containers and the seal's presence and condition.,,

Table 13:

,0,1
0,,250
1,,200
2,Macroeconomic Update - Bunkering,
3,,150
4,y\nThe prices of Brent oil were highly volatil...,
5,,100
6,"year, with prices peaking to a high as USD 95 ...",
7,low as USD 72 per barrel.,50
8,,0
9,y\nDue to geopolitical tensions in the Red Sea...,
10,,Q1\nQ2\nQ3\nQ4
11,"to sail via the Cape of Good Hope, due to whic...",
12,,FY21\nFY22\nFY23\nFY24
13,increase in bunker volumes was witnessed in th...,
14,of the financial year.,y\nDuring the first two quarters of the year u...
15,,"experienced a reduction in volume, with total ..."
16,,"local fuel sales declining by 19% and 11%, res..."
17,Bunkering,
18,,primarily due to increased competition from In...
19,"The Bunkering business of the Group, Lanka Mar...",impacted LMS as well.
20,recorded an encouraging performance during the...,
21,,y\nDuring the third and fourth quarters of the...
22,increase in volumes. It should be noted that i...,
23,,"difference with Indian ports narrowed, positiv..."
24,recorded a substantial increase in profitabili...,
25,,"volumes of the business. Further, the volumes ..."
26,operations driven by higher margins on account...,
27,,fuel sales in the third quarter improved by 10...
28,increase in global fuel oil prices.,
29,,quarter volumes increased significantly by 61%...
30,,Sea crisis.
31,Whilst LMS recorded a volume growth of 2% in c...,
32,"previous financial year [2022/23: 8% growth], ...",

Table 14:

,0,1
0,,quarter volumes increased significantly by 61%...
1,,Sea crisis.
2,Whilst LMS recorded a volume growth of 2% in c...,
3,"previous financial year [2022/23: 8% growth], ...",
4,the previous financial year included local fue...,
5,,"Excluding the local fuel sales, LMS recorded a..."
6,businesses were permitted to import and supply...,
7,,for the year under review. The volume growth w...
8,The temporary approval granted by the Governme...,
9,,significantly higher volumes of 52% recorded i...
10,"to licensed bunkering businesses, including LM...",
11,,the increase in vessels calling the territoria...
12,supplying fuels to local industries was ceased...,
13,,bunker fuel due to the Red Sea crisis.
14,was due to the normalisation of domestic fuel ...,
15,,The volatility of base oil prices during the f...
16,,impacted margins of the business. It should be...
17,,"first half of 2022/23, due to the significant ..."
18,,"prices, the business recorded significantly hi..."
19,,Amidst competition from other suppliers in the...
20,,undertook measures to determine the optimal ca...
21,,import purposes in order to mitigate exposure ...
22,,issues. LMS continued to retain its market lea...
23,,West Coast and the Sri Lankan market.
24,,During the year the business recommenced suppl...
25,LMS continued to retain its market leadership ...,
26,,"(HSFO) to customers. Given, the fact that ther..."
27,Sri Lankan market.,
28,,"fitted with scrubbers, the business envisages ..."
29,,"this product. Further, LMS onboarded a new lub..."
30,“Lanka Marine Services recorded an encouraging,
31,,year and carried out several initiatives to pr...
32,performance during the year driven by an,
33,,collaboratively with their principals within t...
34,increase in volumes. Excluding the local fuel,

Table 15:

,0,1
0,Logistics,
1,"The logistics arm of the Group, John Keells Lo...",
2,,AWARDS
3,to consolidate its warehouse spaces leading to...,
4,,y\nReceived the following awards from 'Great P...
5,operating at 79% capacity by the end of the fi...,
6,"challenging market conditions, the business su...",• Certified as a Great Place To Work in the s...
7,"multiple new customers during the year, to opt...",category.
8,"In addition, JKLL explored new ventures in man...",
9,,• \nTop 15 millennial friendly workplaces in S...
10,customer locations and introduced new fleet ma...,
11,,• \nRecognised as one of the 'Top 40 Best Work...
12,contributing to revenue growth in the fourth q...,
13,,consecutive time.
14,JKLL's third party logistics (3PL) business in...,
15,"reach trucks, the first of its kind in Sri Lan...",
16,technology to reduce operational costs.,Macroeconomic Update - Airlines
17,,"y\nIn CY2023, the performance of the aviation ..."
18,The business continued its digitisation effort...,
19,,with the steady increase of global travel acti...
20,value chain through enhancements to the wareho...,
21,,numbers rebounding strongly close to pre Covid...
22,system (WMS) and the newly upgraded transport ...,
23,,y\n42 international airlines and 3 domestic ai...
24,"(TMS), and real-time key performance indicator...",
25,,operation in the country as at the end of 2023...
26,"such as detailed dashboards, ensuring a custom...",
27,while also focusing on cost saving measures.,
28,,"For a detailed discussion, refer the Outlook s..."
29,,page 107.

Table 16:

,0,1,2,3,4
0,Financial Performance Review,,,,Transportation
1,Income Statement Indicators,,,,y\nLMS recorded a decline in EBITDA and PBT in...
2,,,,,revenue.
3,Rs.million,2023/24,2022/23,%,
4,,,,,Ports and Shipping
5,Revenue*,,,,
6,,,,,y\nThe decrease in EBITDA was due to the decli...
7,Transportation,"54,763","78,189",(30),and the mix change in volumes due to a decline...
8,Ports and Shipping,"14,153","16,092",(12),volumes.
9,Total,"68,916","94,281",(27),
10,,,,,y\nIt should be noted that during the year 202...
11,,,,,a one-off deferred tax credit amounting to Rs....

Table 17:

,0,1,2,3
0,,online operations.,,
1,,,previous year [2022/23: Rs.11.96 billion].,
2,Ports and Shipping,,,
3,,,Balance Sheet Indicators,
4,y,The decrease in revenue in the Ports and Shipp...,,
5,,attributable to SAGT. Despite the growth in vo...,Rs.million,2023/24\n2022/23
6,,SAGT was impacted by the translation impact on...,,
7,,,Debt*,
8,,denominated revenue streams due to the appreci...,,
9,,while ancillary revenue declined from the peak...,Transportation,"6,808 8,610"
10,,during the previous year.,Ports and Shipping,- -
11,,,Total,"6,808 8,610"
12,y,Maersk recorded a 12% decline in revenue as a ...,,
13,,"in imports and exports, as outlined in the Ope...",,

Table 18:

,0,1
0,INDUSTRY GROUP REVIEW,
1,TRANSPORTATION,
2,Financial Performance Review,Transportation
3,Income Statement Indicators,y\nLMS recorded a decline in EBITDA and PBT in...
4,,revenue.
5,Rs.million\n2023/24\n2022/23\n%,
6,,Ports and Shipping
7,Revenue*,
8,,y\nThe decrease in EBITDA was due to the decli...
9,"Transportation \n54,763\n 78,189 \n(30)",and the mix change in volumes due to a decline...
10,"Ports and Shipping\n14,153 \n 16,092 \...",volumes.
11,"Total\n 68,916 \n 94,281 \n(27)",
12,,y\nIt should be noted that during the year 202...
13,,a one-off deferred tax credit amounting to Rs....
14,*Including share of revenue of equity accounte...,
15,,2022/23 recorded a one-off deferred tax charge...
16,,billion on account of the significant change i...
17,Transportation,
18,,the share of results of equity accounted inves...
19,y\nThe decrease in revenue stemmed from the Gr...,
20,,net of all related taxes.
21,"business, Lanka Marine Services (LMS). LMS rec...",
22,in the previous year driven by the significant...,y\nMaersk recorded a 24% decline in EBITDA in ...
23,prices and growth in volumes.,revenue.
24,y\nThe Bunkering business accounts for ~95% of...,
25,,The recurring adjustments for 2023/24 entailed...
26,"industry group, excluding equity accounted inv...",
27,,"performance related initiatives, as articulate..."
28,y\nMackinnons Travels Limited (MTL) recorded a...,"and Manufactured Capital Review. Similarly, th..."
29,account of higher airline frequencies operatin...,"entailed various one-off impacts, which have b..."
30,facilitated more travel and increased capacity.,ensure a like-with-like comparison.
31,y\nMack Air Limited (MAL) also witnessed an in...,
32,,"The recurring EBITDA of the industry group, po..."
33,increase in flight frequencies and the commenc...,
34,,"one-off impacts, stood at Rs.7.57 billion, a 2..."
35,online operations.,
36,,previous year [2022/23: Rs.11.96 billion].
37,Ports and Shipping,
38,,Balance Sheet Indicators
39,y\nThe decrease in revenue in the Ports and Sh...,
40,attributable to SAGT. Despite the growth in vo...,Rs.million\n2023/24\n2022/23\n%
41,SAGT was impacted by the translation impact on...,
42,,Debt*
43,denominated revenue streams due to the appreci...,
44,while ancillary revenue declined from the peak...,"Transportation \n6,808 8,610 ..."
45,during the previous year.,Ports and Shipping\n - ...
46,,"Total\n6,808 8,610 \n(20)"
47,y\nMaersk recorded a 12% decline in revenue as...,
48,"in imports and exports, as outlined in the Ope...",*Excludes lease liabilities.
49,y\nIMMS recorded a 40% decline in revenue due ...,
50,,y\nThe decrease in debt of the industry group ...
51,the port agency industry in Sri Lanka during t...,
52,,reduction in borrowings at LMS.

Table 19:

,0,1
0,Outlook and Risks,Immediate to Short-Term
1,The performance of the Transportation industry...,The World Trade Organisation (WTO) projects wo...
2,a key driver of the Group's performance in the...,volume growth to rebound to 2.6% in CY2024 and...
3,direct and indirect exposures to foreign curre...,following a larger than expected contraction o...
4,streams. The performance of the industry group...,lingering effects of high energy prices and in...
5,with developments globally.,heavily on demand for trade-intensive manufact...
6,,but this is envisaged to recover gradually ove...
7,Sri Lanka stands to benefit significantly from...,the ease in inflationary pressures and improve...
8,"trade in the medium to long run, supported by ...",income. Downside risks to the forecasts includ...
9,"increased consumption, and infrastructure inve...",policy uncertainty and rising protectionism. T...
10,advantageous for the country due to its strate...,resulted in the diversion of shipments between...
11,crucial shipping routes.,prolonged impacts of this crisis may lead to s...
12,,economy and reignite global inflationary press...
13,"Key risks, trends and opportunities relevant t...",tensions elsewhere could lead to trade fragmen...
14,,World merchandise trade volume and GDP growth ...
15,Risks,
16,,(%)
17,,9.6
18,y\nMacroeconomic and political environment*,10.0

Table 20:

,0,1,2,3,4,5,6,7,8,9
0,,,,,World merchandise trade volume and GDP growth ...,,,,,
1,Risks,,,,,,,,,
2,,,,(%),,,,,,
3,,,,,,9.6,,,,
4,y,Macroeconomic and political environment*,,10.0,,,,,,
5,,• Changes in regulatory environment*,,8.0,,,,,,
6,,,,,,6.2,,,,
7,,•,Volatility in fuel prices,6.0,,,,,,
8,y,Supply chain disruptions*,,4.0,3.2 3.3,,,,3.3,
9,,,,,2.6,3.0 3.1,,,,
10,,,,,,,2.7,2.6 2.6,,2.7
11,,•,Trade fragmentation,2.0,,,,,,
12,,,,,0.4,,,,,
13,,•,Potential increase in input costs stemming fro...,0.0,,,,,,
14,,,tensions and global and domestic developments,(2.0),,,(1.2),,,
15,,•,Limited availability of bonded tank space for ...,(4.0),,(3.1),,,,
16,y,,"Financial exposure*, in particular exchange ra...",(6.0),(5.0),,,,,

Table 21:

,0,1
0,near-the-money options contracts.,is largely in foreign currency; should the cur...
1,,"of the Rupee continue, this would translate to..."
2,,"terms, although growth in absolute volumes and..."
3,The Suez Canal Crisis,
4,,foreign currency is likely to cushion the impact.
5,y\nServes as a key maritime route for internat...,
6,of global trade passing through the canal as p...,y\nGiven the increased emphasis on privatisati...
7,,and the resultant benefits accruing to the Sta...
8,"y\nSince November 2023, attacks on commercial ...",
9,,majority of port-related activities will be un...
10,Sea and Gulf of Aden have continued to disrupt...,
11,,the private sector.
12,y\nRerouting through the Cape of Good Hope has...,
13,considerable impact on shipping delays due to ...,Bunkering
14,"longer voyage distances, congestion in ports f...",y\nExperts estimate that the global bunker mar...
15,"loading operations and bunkering operations, p...",demand for bunker fuel on the back of the Red ...
16,Asia-Europe route. As illustrated by the image...,evident from the higher-than-normal increase i...
17,through the Cape of Good Hope has lead to ~8-1...,"Sri Lanka from November 2023 onwards, which pr..."
18,"voyage in the Asia-Europe route, covering an a...",the tensions in the Red Sea; this trend is exp...
19,nautical miles in distance.,"the resolution of the crisis. Going forward, h..."
20,,familiarity with the Sri Lankan market may hel...

Table 22:

,0,1
0,INDUSTRY GROUP REVIEW,
1,TRANSPORTATION,
2,2023/24 was marked with significant volatility...,Ports and Shipping
3,US Energy Information Administration is of the...,
4,,y\nThe Ports and Shipping business recorded an...
...,...,...
83,,y\nFocus will also be placed on expanding capa...
84,nautical miles,
85,8-10 days longer,
86,,trends.
87,Cape of Good Hope,

Table 23:

,0,1,2,3,4,5,6
0,,"• \n'Fit-O', a fruit flavoured drink.",,,,,
1,,• \nFlavoured milk branded under 'Elephant Hou...,,,,,
2,,,,,2023/24,2022/23,2021/22
3,,,Operational Highlights,,,,
4,Frozen Confectionery,,,,,,
...,...,...,...,...,...,...,...
57,,,Community Services and Infrastructure,,,,
58,,,Projects3,Rs.'000,"20,292","8,717","19,611"
59,,,,,,,
60,3%,Capital Employed,,,,,
61,,,1. \nExcludes lease liabilities.,,,,

Table 24:

,0,1,2,3
0,,,Growth (%),
1,y,"In November 2023, the special commodity levy (...",,
2,,on imported sugar was increased from Rs.25 cen...,,
3,,,CSD,(3)\n5\n0\n42\n10\n(7)
4,,kilogram.,,
5,,,y,Q1 – The volume reduction of 3% in the first q...
6,y,The duty waiver on imported skimmed milk powde...,,
7,,,,was an encouraging recovery compared to the st...
8,,removed and a customs import duty (CID) of Rs....,,
9,,,,decline of 40% recorded in the fourth quarter ...
10,,"was imposed in August 2023. Moreover, SMP was ...",,
11,,,,should be noted that the first quarter of the ...
12,,to the port and airport development levy (PAL)...,,
13,,,,"was a strong quarter in terms of performance, ..."
14,,September 2023.,,
15,,,,exceeded pre-pandemic levels.
16,y,The value added tax (VAT) rate was increased f...,,
17,,,y,Q2 – Volumes noted a recovery supported by the...
18,,and excise duty on carbonated soft drinks incr...,,
19,,,,recovery of the economy and consumer activity.
20,,with effect from 1 January 2024.,,
21,,,y,Q3 – The business witnessed encouraging volume...
22,y,Import restrictions imposed from CY2020 onward...,,
23,,,,"seasonal month of December 2023, which was les..."
24,,in three stages during 2023/24. As of October ...,,
25,,,,adverse weather conditions unlike in the month...
26,,"restrictions on all items were removed, other ...",,
27,,,,November 2023.
28,y,Electricity tariffs for industry sectors were ...,,
29,,,y,Q4 – The strong growth in volumes was driven b...
30,,"by ~40% and ~12%, in February and October 2023...",,
31,,,,"coupled with favourable weather conditions, al..."
32,,and subsequently revised downwards by ~9% in J...,,
33,,,,"base in the fourth quarter of 2022/23, as cons..."
34,,in line with the cost reflective pricing mecha...,,
35,,,,income was impacted by the increase in persona...
36,,adopted to reduce the cost of subsidies provid...,,
37,,,,implemented with effect from 1 January 2023. T...
38,,Government. Tariffs were subsequently revised ...,,
39,,,,of the fourth quarter of 2023/24 was encouragi...
40,,"~18%, on average, in March 2024.",,
41,,,,selling price adjustments on some stock keepin...
42,,"For a detailed discussion, refer the Operating...",,account of passing on the higher duty on sugar...
43,,the report on page 41.,,
44,,,,in the VAT from 15% to 18%.

Table 25:

,0,1
0,"For a detailed discussion, refer the Operating...",account of passing on the higher duty on sugar...
1,the report on page 41.,
2,,in the VAT from 15% to 18%.
3,"During the year under review, the Consumer Foo...",In tandem with the recovery of the macroeconom...
4,"an encouraging performance, driven by both the...",returnable glass bottles (RGB) and polyethylen...
5,Frozen Confectionery businesses. Margins recor...,volumes witnessed a recovery in volumes. The P...
6,on account of normalising input costs from the...,"91:9 during the year under review, in comparis..."
7,reductions in overhead costs whilst both busin...,
8,,The smaller pack sizes continued to have tract...
9,"encouraging volume growth, particularly in the...",
10,,the lower price point.

Table 26:

,0,1
0,INDUSTRY GROUP REVIEW,
1,CONSUMER FOODS,
2,Frozen Confectionery,The Bulk:Impulse volume mix for the year stood...
3,,62:38 recorded in the previous year. As envisa...
4,"Similar to the Beverages business, the Frozen ...",
5,,term strategy of the business and trends witne...
6,witnessed a recovery in volumes during the yea...,
7,,the FC business is expected to witness an incr...
8,a growth of 2% in volumes [2022/23: negative 7...,
9,,contribution from the Impulse segment given th...
10,driven by the Bulk segment which recorded a gr...,
11,,lifestyle and convenience aspect of the product.
12,attributable to seasonal demand [2022/23: nega...,
13,segment recorded a marginal decline of 2% in v...,
14,"growth], primarily attributable to adverse wea...",
15,prevailed during most parts of the second half...,64:36
16,,Bulk: Impulse Volume Mix
17,Despite the increase in the VAT rate effective...,[2022/23: 62:38]
18,recovery momentum of volumes continued in both...,
19,the improvement in margins on account of input...,
20,,Export market volumes recorded a growth of 11%...
21,business undertook price reductions in select ...,
22,,underpinned by higher demand arising from incr...
23,particularly in the Impulse segment to pass on...,
24,,the Maldives.
25,consumers while also enabling a stronger recov...,

Table 27:

,0,1,2
0,150,,
1,,,To address the operational cost pressures duri...
2,100,,
3,,,undertook the following initiatives:
4,50,,
5,,,y\nProduction process improvements in factories.
6,0,,
7,,Q1\nQ2\nQ3\nQ4,
8,,,y\nNegotiations with suppliers to enhance work...
9,,FY21\nFY22\nFY23\nFY24,conditions for raw materials and packing mater...
10,,,"y\nInstallation of variable frequency drivers,..."
11,Volume,Q1\nQ2\nQ3\nQ4\n2023/24\n2022/23,
12,,,control initiatives to significantly reduce en...
13,Growth (%),,
14,,,y\nThe 'E2EQuality' extension project was laun...
15,Frozen,,
16,,,product quality of frozen confectioneries. Thi...
17,Confectionery,(10)\n(2)\n(2)\n24\n2\n(7),
18,,,'Beelive – Connected Factory' internet of thin...
19,,,helped monitor key production/storage metrics ...
20,y,Q1 – The volume reduction of 10% was an encour...,
21,,,was successfully implemented previously at the...
22,,compared to the steep volume decline of 30% re...,
23,,,Seethawaka.
24,,the fourth quarter of 2022/23. It should be no...,
25,,quarter of the previous year was a strong quar...,
26,,,As part of its advanced analytics transformati...
27,,"performance, with volumes exceeding pre-pandem...",
28,,,business currently has one use case rolled-out...
29,y,"Q2 – Although volumes declined, the rate of de...",augmenting the efficiency of the distribution ...
30,,continued to moderate supported by the sustain...,are in advanced stages of deployment.
31,,the economy and consumer activity.,
32,,,Products Launched
33,y,Q3 – The business witnessed encouraging volume...,
34,,"the seasonal month of December 2023, which was...",y\nPopsicles:
35,,by adverse weather conditions unlike in the mo...,
36,,,"• \n'Major Max' Freezer Pops in Strawberry, Gr..."
37,,and November 2023 that witnessed a moderated g...,
38,,,and Orange flavours.
39,,factors contributed to the decline in volumes.,
40,,,• \n360 ml 'Fusion Popsicles' in Naarang and S...
41,y,"Q4 – A growth of 24% was recorded, albeit off ...",
42,,,"Chilli, and Siyambala and Honey flavours."
43,,"the fourth quarter of 2022/23, due to seasonal...",
44,,with favourable weather conditions.,
45,,,y\nRelaunched the Pani Kadju and Faluda cones.

Table 28:

,0,1
0,,Convenience
1,,Foods\n(35)\n(18)\n(1)\n42\n(9)\n(22)
2,,y\nQ1 – The decline in volumes was driven by a...
3,,sausage volumes as a result of a moderation in...
4,,"on processed meats, which is a more discretion..."
5,,These products are also at a higher price poin...
6,'Major Max' Freezer Pops and 360 ml 'Fusion Po...,SKUs of the Beverages and Frozen Confectionery...
7,,y\nQ2 and Q3 – The moderation in consumer spen...
8,,meats witnessed a recovery from the second to ...
9,,with the volume decline stabilising from the p...
10,AWARDS,
11,,the end of the third quarter.
12,y\nSLIM Brand Excellence Awards 2023:,
13,,"y\nQ4 – Recovery was driven by seasonal sales,..."
14,• \n'Elephant House' ice cream won Gold for 'P...,base in the fourth quarter of 2022/23.
15,Year'.,
16,• \n'Elephant House' ice cream won Silver for ...,
17,,"During the year under review, the business mai..."
18,Year'.,
19,,the market leader in the processed meats categ...
20,y\nAwarded Gold in the 'Confectionery Products...,and meatballs categories recorded a negative g...
21,Category' at the National Chamber of Exporters...,respectively [2022/23: negative 9% and negativ...
22,Awards 2023.,"However, it is encouraging that retail sausage..."
23,,"during the second half of 2023/24, increasing ..."
24,y\nWon two Gold awards at the SLIM National Sa...,
25,,to the same period of the previous year. The r...
26,in the frozen confectionery category.,
27,,contributed ~27% to the overall volumes. The b...
28,,decrease in prices in these categories during ...
29,,which also aided volume growth. No price incre...
30,Convenience Foods,across all categories due to the increase in V...
31,Keells Food Products PLC (KFP) recorded a 9% d...,
32,,The modern trade channel accounted for 33% of ...
33,during 2023/24 on account of the moderation in...,
34,,"the general trade and hotels, restaurants, cat..."
35,"processed meats, which is more discretionary a...",
36,,"accounted for 40% and 25%, respectively. The H..."
37,compared to the Beverages and FC businesses [2...,
38,,"demonstrated a recovery in volumes, driven by ..."
39,The volumes were also affected on account of t...,
40,,the recovery in the macroeconomic environment ...
41,food prices and the relative prices of protein...,
42,processed meat category. Despite the decline i...,
43,,Supply chain disruptions and changes in suppli...
44,the first half of the year attributable to red...,
45,,previous year posed sourcing challenges for th...
46,"this category, the business experienced a nota...",
47,,"business, similar to the experience of the ove..."
48,"half of the year, driven by an increase in dem...",
49,,challenges had eased to a great extent towards...
50,revisions which improved product affordability.,
51,,"financial year. During the year, the business ..."
52,,"to secure stocks, minimise production disrupti..."
53,Convenience Foods Volumes,
54,,availability of products. It also undertook se...
55,Index: FY21 Q1 = 100,
56,,"working capital requirements, including negoti..."
57,120,to previous letter of credit (LC) terms and re...
58,100,

Table 29:

,0,1,2,3,4
0,CONSUMER FOODS,,,,
1,The business undertook the following process i...,Financial Performance Review,,,
2,y\nImplemented blast freezing to enhance produ...,Income Statement Indicators,,,
3,freshness.,,,,
4,,Rs.million,2023/24,2022/23,%
5,y\nUpgraded the transport fleet to optimise th...,,,,
6,guaranteeing the integrity of products through...,Revenue,,,
7,,Beverages and Frozen,"28,548","26,385",8
8,y\nInitiatives to replace imported input mater...,,,,
9,,Confectionery (FC),,,
10,material.,,,,
11,,Convenience Foods,"4,349","4,884",(11)
12,y\nImplemented capacity bankers to reduce ener...,,,,
13,,Total,"32,897","31,269",5
14,y\nStreamlined operations and costs by impleme...,EBITDA*,,,
15,measures to reduce water treatment expenses.,,,,
16,,Beverages and FC,"4,893","2,854",71
17,y\nDigital transformation through the integrat...,Convenience Foods,117,442,(74)
18,"health, and environment) application, ensuring...",Total,"5,010","3,296",52
19,efficient management of safety protocols.,PBT,,,
20,,Beverages and FC,"3,249","1,108",193
21,y\nEnhanced logistics management with the impl...,,,,
22,(global positioning system) for its distributi...,Convenience Foods,(275),55,(600)
23,"tracking system, enabling real-time monitoring...",Total,"2,974","1,163",156
24,delivery processes.,,,,
25,,,*EBITDA includes interest income but excludes ...,,

Table 30:

,0,1,2,3,4,5
0,y,EBITDA of the FC business was mainly driven by...,Balance Sheet Indicators,,,
1,,given its higher product margins.,,,,
2,,,Rs.million,2023/24,2022/23,%
3,y,The Bulk:Impulse revenue mix was at 47:53 duri...,,,,
4,,"review, compared with 44:56 in 2022/23.",Assets,,,
5,,,Beverages and FC,"21,147","19,429",9
6,y,"During the year under review, the EBITDA margi...",,,,
7,,,Convenience Foods,"3,714","4,009",(7)
8,,and FC businesses increased significantly to 1...,,,,
9,,,Total,"24,861","23,438",6
10,y,The PBT of the Beverages and FC businesses rec...,,,,
11,,,Debt*,,,
12,,"improvement driven by the increase in EBITDA, ...",,,,
13,,,Beverages and FC,"4,163","5,306",(22)
14,,the decline in finance expenses on account of ...,,,,
15,,,Convenience Foods,"1,074","1,230",(13)
16,,rates and normalisation of working capital cyc...,,,,
17,,,Total,"5,237","6,536",(20)
18,Convenience Foods,,,,,

Table 31:

,0,1,2,3
0,,,,"Convenience Foods\n1,074 \n1,230\n(13)"
1,rates and normalisation of working capital cyc...,,,
2,,,Total,"5,237\n6,536\n(20)"
3,Convenience Foods,,,
4,,,*Excludes lease liabilities.,
5,(%)\nQ1\nQ2\nQ3,Q4,,
6,,,y,The Beverages and FC businesses recorded an in...
7,Convenience Foods,,,to:
8,revenue growth \n(12)\n(20)\n(15),14,,
9,,,,• An investment in a PET bottling and can man...
10,Convenience Foods,,,
11,,,,the Beverages business to support the expansio...
12,volume growth \n(35)\n(18)\n(1),42,,
13,,,,product portfolio.
14,Convenience Foods,,,
15,,,,• \nThe Beverages and FC businesses invested i...
16,EBITDA (Rs.million)\n(9)\n18\n53,54,,
17,,,,"the year under review [2022/23: ~1,900]."
18,Convenience Foods,,,
19,EBITDA growth (%)\n(105)\n(89)\n(33),"1,574",,"• During the year under review, working capit..."
20,,,,levels of normalcy resulting in an increase in...
21,y\nAs outlined in the External Environment and...,,,

Table 32:

,0,1,2,3,4,5
0,EBITDA Margin,,,,,Advanced analytics:
1,(%),,,,,
2,,,,,,y\nThe businesses will continue to roll-out ad...
3,25,,,,,
4,,,,,,in the ensuing period which will attempt to op...
5,20,,,,,"planning, further augmenting the businesses' p..."
6,15,,,,,term sustainable growth.
7,10,,,,,
8,,,,,,y\nEmphasis will be placed on six use cases wh...
9,05,,,,,successfully deployed in optimising promotiona...
10,,,,,,modern trade and general trade segments and in...
11,(5),,,,,production planning process. The business will...
12,Q1\nQ2,Q3,Q4\nQ1\nQ2,Q3,Q4,
13,,,,,,"deployment of use cases, which are aimed at au..."
14,FY20\nFY21\nFY22,FY23,,FY24,,
15,,,,,,efficiency of the distribution network of the ...
16,Beverages and Frozen Confectionery,,Convenience Foods,,,

Table 33:

,0,1,2,3,4,5,6,7
0,Beverages,,,,,,,
1,,,,,,,,CSD Portfolio Exposure
2,,,,,,,y,The share of CSD as a proportion of total beve...
3,,INSIGHTS,,,,,,
4,,,,,,,,to proportionately reduce in the long-term in ...
5,,,,,,,,"trends witnessed in recent years. However, the..."
6,,Low consumption patterns and penetration refle...,,,,,,
7,,,,,,,,the beverage industry continue to be promising...
8,,growth in the CSD market,,,,,,
9,,,,,,,,"opportunities for growth as the consumers, mov..."
10,,,,,,,,
11,,Carbonated soft drinks - per capita consumptio...,,,,,,"CSD, seek alternate beverage options."
12,60,,,,,,,
13,,,,,,,y,"For example, CSD manufacturers worldwide conti..."
14,,52,,,,,,
15,50,,,,,,,in reformulation exercises with the aim of red...
16,,,39,,,,,content of their products and adopting sustain...
17,40,,,,,,,
18,,,,31,,,,whilst extending the portfolios to include non...
19,30,,,,,,,
20,,,,,,,,some of which are healthier and more nutritious.
21,,,,,19,,,
22,20,,,,,,,
23,,,,,,10,y,The Beverages business has already reformulate...
24,10,,,,,,,
25,,,,,,,,flavours with ~30% – 45% of the CSD portfolio'...
26,0,,,,,,,
27,,Philippines,Thailand,Singapore,Malaysia,Sri Lanka,,content reformulated and replaced with stevia;...
28,,,,,,,,sweetener with zero calories.
29,,Source: Company analysis,,,,,,

Table 34:

,0,1,2,3
0,,,,Convenience Foods
1,,INSIGHTS,,The Convenience Foods business will continue t...
2,,,,its portfolio offering. Emphasis will also be ...
3,The bulk:impulse mix of regional markets is hi...,,,
4,,,,market trends and changes in the competitive e...
5,"impulse market, demonstrating the significant ...",,,
6,,,,expected to continue seeing the entry of small...
7,category in the overall ice cream market of Sr...,,,
8,,The Bulk:Impulse Mix of Regional Markets,,
9,,,,The strategic priorities for the business are:
10,(%),,,
11,,,8,
12,,,,"y\nDevelopment of product extensions, paving t..."

Table 35:

,0,1,2,3,4,5,6,7,8,9
0,,,,,,,,,,expected to continue seeing the entry of small...
1,category in the overall ice cream market of Sr...,,,,,,,,,
2,,The Bulk:Impulse Mix of Regional Markets,,,,,,,,
3,,,,,,,,,,The strategic priorities for the business are:
4,(%),,,,,,,,,
5,,,,,8,,,,,
6,,,,,,,,,y,"Development of product extensions, paving the ..."
7,30,,,,,,,,,
8,,,,,,,,,,"to increase its market share, particularly thr..."
9,,,,,,44,,,,convenient and affordable meal options.
10,,Sri Lanka,,,Thailand,,,56\nMalaysia,,
11,,,,,,,,,y,Focus on consolidating the dry distribution ne...
12,,,,,,,,,,to ensure readiness to cater to the envisaged ...
13,,,70,,,,,,,
14,,,,,92,,,,,
15,,,,,,,,,y,Emphasis on growing the modern and general tra...
16,Bulk,,Impluse,,,,,,,
17,,,,,,,,,,particularly the organised small and medium en...
18,,,,,,,,,,trade thereby increasing footprint.
19,,Bulk:Impulse Volume Mix of the Frozen Confecti...,,,,,,,,
20,(%),,,,,,,,,
21,,,,,,,,,y,Focus on further augmenting its portfolio offe...
22,100,,,,,,,,,
23,,70,,70,68,,62,64,y,"Expanding presence locally and globally, espec..."
24,80,,,,,,,,,bespoke solutions offered to outlet networks a...
25,,,,,,,,,,augmenting the recent venture to the Australia...
26,60,,,,,,,,,

Table 36:

,0,1,2,3,4,5,6
0,,chilled categories.,,,,,
1,,,Same store footfall growth,%,12.3,28.3,4.5
2,,,Average basket value,%,(0.1),15.1,8.0
3,,"• A warehouse area of ~260,000 sq. ft.",,,,,
4,,,Financial and Manufactured Capital,,,,
5,,• Capacity to cater to over ~250 outlets.,,,,,
6,,,Revenue,Rs.million,"122,502","106,849","90,842"
7,,• \nEmployment for ~550 individuals.,,,,,
8,,,EBITDA,Rs.million,"8,767","8,833","7,549"
9,,,PBT,Rs.million,"2,938",558,7
10,Office Automation,,,,,,
11,,,PAT,Rs.million,"2,056","1,296",(865)
12,y,John Keells Office Automation (JKOA) is the,,,,,
13,,,Total assets,Rs.million,"52,103","49,929","52,476"
14,,authorised distributor for Office Automation and,,,,,
15,,,Total equity,Rs.million,"5,358","3,725","3,487"
16,,"IT enabled, world-renowned brands and a market",,,,,
17,,,Total debt 1,Rs.million,"14,687","20,510","15,342"
18,,leader in providing print solutions for corpor...,,,,,
19,,,Capital employed 2,Rs.million,"31,375","34,587","29,046"
20,,Brands offered include:,,,,,
21,,,Natural Capital,,,,
22,,"• \nSamsung – a range of smartphones, tabs, HT...",Energy consumption,kWh,"79,540,619 67,104,264",,"63,859,456"
23,,digital signage.,,,,,
24,,,Energy consumption per operational,kWh per,,,
25,,,intensity factor,Rs.million,637.37,615.60,701.33
26,,"• \nToshiba – a range of black and white, colo...",,,,,
27,,,Carbon footprint,MT,"44,118","36,359","36,230"
28,,of multifunctional printers.,,,,,
29,,,Carbon footprint per operational,MT per,,,
30,,• Asus – commercial series of notebooks and,intensity factor,Rs.million,0.35,0.33,0.40
31,,desktops.,Water withdrawal,m3,"287,290","309,325","282,480"
32,,,Water withdrawal per operational,m3 per,,,
33,,"• Other products include laser printers, smar...",,,,,
34,,,intensity factor,Rs.million,2.30,2.84,3.10
35,,"and educational solutions, digital duplicators...",,,,,
36,,,Volume of hazardous waste generated,kg,101.00,421.00,0
37,,"counting machines, receipt and label printers,",,,,,
38,,,Volume of non hazardous waste,,,,
39,,multimedia projectors from a variety of world ...,generated,kg,"4,570,915","3,642,918","3,819,863"
40,,brands.,Waste generated per operational,kg per,,,
41,,,intensity factor,Rs.million,36.63,33.42,41.95
42,New Energy Vehicles,,,,,,
43,,,Human Capital,,,,
44,y,John Keells CG Auto (Private) Limited is the,Total Workforce (employees and,,,,
45,,authorised distributor of new energy vehicles ...,contractors' staff ),No.,"7,424","7,703","7,081"
46,,manufactured by BYD Auto Industry Company,EBIT per employee,Rs.million,1,1,1
47,,"Limited, China.",Average training per employee,hours,160.76,19.65,22.76
48,,,Total Attrition,%,94.9,83.2,101.6
49,,,Females employee,%,46,45,48
50,Contribution to the John Keells Group,,Total injuries,No.,176,187,137
51,,,Social and Relationship Capital,,,,
52,,Revenue\n39%,,,,,
53,,,Community Services and Infrastructure,,,,
54,,,Projects3,Rs.'000,"15,234","18,943","16,972"
55,,,,,,,
56,,EBIT\n16%,,,,,
57,,,1. \nExcludes lease liabilities.,,,,

Table 37:

,0,1,2,3,4,5,6
0,Supermarkets,,,,,,
1,y,Jaykay Marketing Services (Private) Limited (J...,,,,,
2,,operates the 'Keells' chain of modern retail o...,,,,,
3,,and the 'Nexus' loyalty programme.,,,,,
4,,• \n134 outlets across the island as at 31 Mar...,,,,,
...,...,...,...,...,...,...,...
68,,,Community Services and Infrastructure,,,,
69,,,Projects3,Rs.'000,"15,234","18,943","16,972"
70,,,,,,,
71,,EBIT\n16%,,,,,
72,,,1. \nExcludes lease liabilities.,,,,

Table 38:

,0,1,2,3,4
0,External Environment and Operational Review,,,Key performance indicators pertaining to the S...,
1,,,%,2023/24,2022/23*
2,Macroeconomic Update,,,,
3,y,The operating environment in the country conti...,Same store footfall growth,12.3,28.3
4,,normalisation supported by sustained improveme...,Average basket value (ABV) growth,(0.1),15.1
5,,country's key macroeconomic indicators. Howeve...,,,
6,,,Same store sales growth,12.3,47.6
7,,"incomes were negatively impacted, particularly...",,,
8,,,,"*Given the pandemic-related disruptions, unpre...",
9,,"half of the year, by the imposition of direct ...",,,
10,,,,shopping patterns resulting in shifts in frequ...,
11,,Based on the statistics of the Central Bank of...,,,
12,,,,"of customers, the KPIs were distorted for the ...",
13,,consumption expenditure estimates at constant ...,,,
14,,,Report 2022/23.,,
15,,"CY2023, have contracted due to decreased purch...",,,

Table 39:

,0,1,2,3
0,,with effect from 1 January 2024.,,
1,,,y,Growth in same store footfall was driven by bo...
2,y,"Removal of mobile phones, notebooks, projector...",,
3,,,,customers.
4,,and point of sale (POS) solutions from the VAT...,,
5,,from January 2024.,,• \nFootfall growth was also driven by improve...
6,,,,items and seasonal sales. The business continu...
7,y,Import restrictions imposed from CY2020 onward...,,
8,,,,"conversion from general trade to modern trade,..."
9,,in three stages during 2023/24. As of October ...,,
10,,,,for modern trade to manage inventory and worki...
11,,"restrictions on all items were removed, other ...",,
12,,,,"effectively, ensuring fewer supply chain disru..."
13,,vehicles.,,
14,,,,pass on benefits to consumers due to the scale...
15,y,Electricity tariffs for industry sectors were ...,,through the 'Nexus' loyalty programme also hel...
16,,"by ~40% and ~12%, in February and October 2023...",,

Table 40:

,0,1,2
0,INDUSTRY GROUP REVIEW,,
1,RETAIL,,
2,"revisions and to a lesser extent, staff costs....",y,Sourcing imported products:
3,see an improvement in energy costs in 2024/25 ...,,
4,,,• Continued with the direct import strategy e...
5,"revision of electricity tariffs in March 2024,...",,
6,,,which aims to offer a range of products at aff...
7,than at the beginning of the previous year.,,
8,,,"by directly liaising with manufacturers, there..."
9,,,"selection of choice for customers, at value, b..."
10,"For a detailed discussion, refer the Outlook a...",,
11,,,intermediary costs.
12,The ensuing section summarises the initiatives...,,• \nRepresenting ~2% of the business's revenue...
13,Supermarket business to drive performance.,,portfolio includes over ~180 products.
14,,y,Marketing and promotions:
15,Product and Process Initiatives,,
16,y\nAdvanced analytics transformation programme:,,• Conducted two major campaigns during the year:

Table 41:

,0,1,2,3
0,,,y,Marketing and promotions:
1,Product and Process Initiatives,,,
2,y,Advanced analytics transformation programme:,,• Conducted two major campaigns during the year:
3,,"• During the year under review, identified us...",,• \n'Freshness that is Affordable' –to emphasi...
4,,rolled-out with the value capture of most of t...,,"value offered by 'Keells' to customers, withou..."
5,,exceeding expectations. The pilot projects of ...,,freshness.
6,,piloted or rolled-out at scale have also demon...,,
7,,,,• \n'Ada Keells Eken Kamu' – an initiative to ...
8,,value that can be unlocked by translating adva...,,
9,,,,prepared food offerings available at selected ...
10,,insights into frontline business interventions.,,
11,,,,which also drove footfall.
12,,"• Use cases related to promotions, pricing, o...",,
13,,,,• Continued with personalised promotions and ...
14,,marketing and procurement have been rolled-out...,,
15,,,,"based on customer needs, such as, bank promoti..."
16,,across several segments of the business. These...,,
17,,,,than Market Price' items from the fresh category.
18,,"contributed to improved margins, operational e...",,
19,,better product positioning while paving the wa...,y,Supply chain management:
20,,customer centricity and servicing.,,
21,,,,• \nSeveral supply-side initiatives were imple...
22,y,Collection centres:,,improving product availability and maintaining...
23,,,,levels.
24,,• \nExpanded sourcing locations to minimise su...,,
25,,enhance the product availability and freshness...,,• \nImplemented a bulk purchasing strategy to ...
26,,consumers with better value.,,procurement costs and ensure a consistent supply.
27,,,,• Maintained safety stock levels at collectio...
28,,"• As a part of these efforts, in April 2023, ...",,
29,,,,in forward buying to ensure timely delivery an...
30,,"centre, with a fully automated vegetable washi...",,
31,,,,disruptions due to supplier shortages.
32,,"machine, was established in Nuwara-Eliya.",,
33,,,,• Automated the ordering process via an 'orde...
34,y,Private label penetration:,,
35,,,,system'.
36,,• \nIncreased penetration of the private label...,,
37,,,y,Distribution Centre (DC):
38,,"prices ~10% lower than comparable brands, to p...",,
39,,with alternative 'value for money' options and...,,• \nThe state-of-the-art centralised DC in Ker...
40,,,,to play a vital role in streamlining operation...
41,,• \nThe private label portfolio consists of ov...,,
42,,,,"optimum inventory management across the fresh,..."
43,,across 88 categories. The private label brand ...,,
44,,,,categories.
45,,"in new categories such as yoghurt, cleaning pr...",,
46,,and frozen ready-to-cook (RTC) meals and re-en...,,• \nThe expansion of commercial operations and...
47,,previously exited on account of macroeconomic ...,,at the DC contributed positively to the perfor...
48,,,,Supermarket business in terms of cost effectiv...
49,,• A rigorous quality control process which mo...,,
50,,and the manufacturing environment has been ini...,,• Growth in efficiencies were driven by the s...
51,,maintain high quality standards.,,"workforce, equipment, transportation and energ..."
52,,,,the flexibility in reallocating resources base...
53,,• \nPrivate label products accounted for ~5% o...,,
54,,,,under each of the separate categories.
55,,[2022/23: ~5%].,,

Table 42:

,0,1
0,y\nThe 'Instore Service' project was initiated...,The 'Keells' online store continued to be patr...
1,the customer service experience at outlets whi...,"base recording ~8,000 monthly orders, on average."
2,consistent standards. The project aims to ensu...,
3,service counters and improved customer service...,
4,,AWARDS
5,"interactions, attentiveness and the accuracy o...",
6,,y\nBronze Award – 'Best search engine optimisa...
7,y\nOther digitisation initiatives:,
8,,engine marketing (SEM) Campaign' at SLIM Digis...
9,• Commenced the roll-out for digital applicat...,
10,,y\nOne of Sri Lanka's 'Most Outstanding Women ...
11,Delivery' and 'Keells Rider App' which facilit...,
12,,Workplaces' by Chartered Institute of Management
13,logistics.,
14,,Accountants (CIMA) and Satyn Magazine.
15,• Digitalised the marketing technology stack ...,
16,provided staff with efficient tools for access...,y\nFirst runner up in the 'Large Scale Enterpr...
17,information.,National Supply Chain Excellence Awards 2023 o...
18,,the Institute of Supply and Materials Manageme...
19,Outlet Expansion,collaboration with the Ministry of Industries ...
20,,Development Board.
21,Although the expansion of the 'Keells' outlet ...,
22,"the first half of the year under review, given...",
23,,y\n'Most Visible Brand Online' by the Asia Pac...
24,and the normalisation of the macroeconomic env...,
25,,Marketing.
26,the business commenced outlet expansions on a ...,
27,"new outlets were opened during the year, whils...",
28,bringing the total count to 134 outlets as at ...,
29,,Office Automation
30,"In expanding its brand and outlet network, the...",The Office Automation business witnessed a rec...
31,on a standard and an extended format depending...,with the gradual easing of inflation and inter...
32,distribution levels of the locality and the ma...,year. The relaxation of import restrictions on...
33,competitive dynamics. In line with its brand e...,mobile phones and laptops during the second ha...
34,were upgraded to the 'iconic' format during th...,supported volume growth. The removal of mobile...
35,"concept for select 'Keells' outlets, is aimed ...","exemptions list, coupled with the simultaneous..."
36,customer experience through best-in-class reta...,"to 18%, effective 1 January 2024, contributed ..."
37,"a wider offering, particularly in the prepared...",prices which had a negative impact on the reco...
38,"range, and improved ambience. Despite the addi...",The copier and printer business segments were ...
39,associated with the conversion of the standard...,costs of usage and maintenance.
40,"the extended format, the payback on these inve...",
41,incremental performance has been attractive.,Despite the highly competitive landscape of th...
42,,market characterised by low-price product offe...
43,Features of 'Iconic' outlets:,
44,,"specifications, the business successfully laun..."
45,,remained competitive during the year. Digitisa...

Table 43:

,0,1,2,3,4
0,INDUSTRY GROUP REVIEW,,,,
1,RETAIL,,,,
2,New Energy Vehicles,Financial Performance Review,,,
3,"In November 2023, JKH partnered with BYD Auto ...",Income Statement Indicators,,,
4,"Limited, the world's leading manufacturer of n...",,,,
5,,Rs.million,2023/24,2022/23,%
6,to provide cutting-edge and eco-friendly vehic...,,,,
7,"market. This new business, John Keells CG Auto...",,,,
8,,Revenue,,,
9,"venture between JKH and Chaudhary Group, Nepal...",,,,
10,,Supermarkets,"110,977","99,773",11
11,the Retail industry group considering its alig...,,,,
12,,Office Automation,"11,525","7,076",63
13,and potential synergies. The prospect for cont...,,,,
14,,New Energy Vehicles,-,-,-
15,environmentally friendly and energy efficient ...,,,,
16,"support the country, is in alignment with the ...",Total,"122,502","106,849",15
17,"agenda. For reporting purposes, John Keells CG...",EBITDA*,,,
18,will be accounted as an equity accounted inves...,Supermarkets,"7,644","7,504",2
19,,Office Automation,"1,147","1,328",(14)
20,"BYD Auto Industry Company Limited, headquarter...",,,,
21,,New Energy Vehicles,(24),-,-
22,renowned globally for its operations in the NE...,,,,
23,,Total,"8,767","8,832",(1)
24,a growing trend in the automotive industry. Le...,,,,
25,,PBT **,,,
26,"and technological advancements, the new ventur...",,,,
27,,Supermarkets,"1,680","1,139",47
28,"importing, distributing and providing after sa...",,,,
29,,Office Automation,"1,283",(581),321
30,vehicles in the Sri Lankan automobile market. ...,,,,
31,,New Energy Vehicles,(24),-,-
32,outlet network and other locations of the Grou...,,,,
33,"the country will generate synergies, enabling ...",Total,"2,938",558,427
34,necessary eco-system required for the NEV busi...,,,,
35,,,*EBITDA includes interest income and the share...,,
36,requirements are anticipated to be minimal ini...,,which is based on the share of profit after ta...,,
37,primarily allocated for the development of sho...,,currency exchange gains and losses (other than...,,
38,,,demonstrate the underlying cash operational pe...,,
39,and charging infrastructure.,,,,
40,,,**Share of results of equity accounted investe...,,

Table 44:

,0,1,2
0,,,"EBITDA (Rs.million)\n1,740\n1,750\n1,997\n2,158"
1,,,EBITDA growth (%)\n(7)\n5\n1\n9
2,,,EBITDA margin (%)\n6.3\n6.4\n6.9\n7.9
3,,y,As outlined in the External Environment and Op...
4,,,Supermarket business recorded a strong perform...
5,,,driven by double-digit growth in same store sa...
6,,,driven by a sustained increase in footfall.
7,,y,"Despite the increase in revenue, EBITDA was of..."
8,,,the significant cost escalations in operations...
9,,,"costs due to the upward revision of tariffs, h..."
10,,,promotional expenses and to a lesser extent st...
11,,y,"Further, during the first half of the financia..."
12,,,impacted by the imposition of the social secur...
13,,,"(SSCL), which came into effect from October 20..."
14,,,revenue-based tax similar to the nation buildi...
15,,,"years ago, where the retail industry is subjec..."
16,,,applicable rate. The business had to absorb th...
17,JKH partnership with BYD Auto Industry Company...,,
18,,,although measures were undertaken to mitigate ...

Table 45:

,0,1,2,3
0,y,"Despite the above mentioned cost increases, th...",Supermarkets,
1,,business sustained EBITDA margins throughout t...,,
2,,,y,The growth in the asset base was driven by the...
3,,"optimising logistics efficiencies, providing a...",,
4,,,,and an increase in cash.
5,,"drive higher revenue, engaging in timely suppl...",,
6,,,y,The depreciation and amortisation expenses of ...
7,,implementing data-led initiatives to improve m...,,
8,,,,recorded an increase on the back of the above ...
9,,,,the asset base.
10,y,The PBT of the Supermarket business significan...,,
11,,"decrease in finance expenses, on account of lo...",,
12,,,y,The significant decrease in debt of the Superm...
13,,reduced borrowings given the generation of hig...,,
14,,,,primarily on account of repayment of debts uti...
15,,the normalisation of working capital and opera...,,
16,,,,"through operations, the normalising of working..."
17,,,,and relatively low capital expenditure during ...
18,Office Automation,,,
19,,,y,"As at 31 March 2024, lease liabilities stood a..."
20,y,The Office Automation business recorded strong...,,
21,,,,8% increase against the Rs.10.32 billion recor...
22,,driven by the increase in mobile phone volumes...,,
23,,,,debt including leases stood at Rs.23.85 billio...
24,,relaxation of import restrictions on non-essen...,,
25,,,,[2022/23: Rs.27.67 billion].
26,,second half of the year.,,
27,y,"Similar to the Supermarket business, EBITDA ma...",Office Automation,
28,,impacted by an increase in staff costs and dis...,,
29,,,y,The increase in the asset base was primarily d...
30,,and the imposition of the SSCL.,,
31,,,,"inventory and trade and other receivables, ref..."
32,,,,of normalised operations.
33,y,The PBT of the business recorded an increase o...,,
34,,exchange gains emanating from the difference b...,,
35,,,y,The Office Automation business witnessed a sig...
36,,rate of products and the settlement of bills g...,,
37,,,,in bank overdrafts during the year under revie...
38,,the Rupee towards the end of the year.,,
39,,,,working capital requirements and the repayment...
40,,,,generated from operations.
41,y,Finance expenses recorded a significant decrea...,,
42,,lower interest rates and reduction of debt lev...,,
43,,,,Return on Capital Employed (ROCE) Analysis
44,,and a normalising of working capital requireme...,,
45,,,,ROCE\n=\nEBIT \nx\nAsset \nx\nCapital
46,New Energy Vehicles,,,
47,,,,(%)\nmargin \nturnover\nstructure
48,y,"As detailed in the Operational Review, with th...",,
49,,,,(%)\nleverage
50,,"Keells CG Auto (Private) Limited, the business...",,
51,,groundwork for the impending commencement of o...,2023/24,16.6\n4.5\n2.40\n1.55
52,,New Energy Vehicle business. For reporting pur...,2022/23,17.8 \n5.3 \n2.09 \n1.61
53,,CG Auto (Private) Limited will be accounted as...,,
54,,investee.,y,The decline in the ROCE in the Retail industry...
55,,,,to the Supermarket business.

Table 46:

                           0        1        2     3
0          Rs.8.78 billion].
1   Balance Sheet Indicators
2                 Rs.million  2023/24  2022/23     %
3                     Assets
4               Supermarkets   47,421   46,566     2
5          Office Automation    4,681    3,364    39
6                      Total   52,102   49,930     4
7                      Debt*
8               Supermarkets   12,660   17,346  (27)
9          Office Automation    2,027    3,164  (36)
10                     Total   14,687   20,510  (28)

Table 47:

,0,1
0,INDUSTRY GROUP REVIEW,
1,RETAIL,
2,Outlook and Risks,Immediate to Short-Term
3,The strong performance of the Supermarket busi...,Supermarkets
4,2023/24 is envisaged to continue going forward...,
5,,Demand and supply dynamics and shopping trends:
6,growth in footfall driven by higher modern tra...,
7,,y\nAnticipates sustained consumer spend given ...
8,initiatives undertaken by 'Keells' to attract ...,
9,,"business, as consumer baskets primarily consis..."
10,been a dampening of consumer discretionary spe...,
11,,"personal care products, and everyday household..."
12,the stabilisation of the economy in combinatio...,
13,demand for essential items is anticipated to s...,y\nWitnessed a sustained increase in footfall ...
14,"business, similar to the trends observed in th...","under review, despite the challenging operatin..."
15,"light, basket values are likely to recover as ...",demonstrating the continued potential for high...
16,the number of items purchased in a basket – re...,certain customer segments. This is envisaged t...
17,recovery of the economy and improving consumer...,performance driven primarily by a growth in fo...
18,,short-term.
19,The performance of the Office Automation busin...,
20,,y\nAlthough there has been a decrease in deman...
21,continue its recovery in tandem with the stabi...,
22,,a result of the impact on consumer spending an...
23,Group is optimistic about the potential opport...,
24,,particularly for non-essential and luxury prod...
25,"(NEV) in Sri Lanka, and envisages the NEV busi...",
26,,balanced by shifts in consumer preferences tow...
27,"growth to the industry group, once the busines...",
28,,alternatives within consumer shopping baskets ...
29,,witnessed in the previous two years.
30,"Key risks, trends and opportunities relevant t...",
31,,• \nThe increase in value added tax (VAT) from...

Table 48:

,0,1,2
0,"(NEV) in Sri Lanka, and envisages the NEV busi...",,
1,,,balanced by shifts in consumer preferences tow...
2,"growth to the industry group, once the busines...",,
3,,,alternatives within consumer shopping baskets ...
4,,,witnessed in the previous two years.
5,"Key risks, trends and opportunities relevant t...",,
6,,,• \nThe increase in value added tax (VAT) from...
7,Risks,,"1 January 2024, coupled with the removal of VA..."
8,,,"several items such as dairy, tea, coconut, oil..."
9,y\nMacroeconomic and political environment*,,
10,,,a considerable impact on prices. This may cont...
11,• Changes in regulatory environment,,spending on non-essential items in the backdro...
12,,,direct taxes in the prior year.
13,y\nSupply chain disruptions*,,
14,"y\nFinancial exposure*, in particular exchange...",y,The conversion from general trade to modern tr...
15,,,"to continue, given the ability of modern trade..."
16,y\nClimate risks*,,
17,,,better availability and fewer disruptions thro...
18,• \nIncreasingly volatile weather patterns imp...,,
19,,,of its inventory and working capital. The abil...
20,fresh produce,,
21,,,customers stemming from economies of scale is ...
22,y\nGlobal competitiveness* and evolving prefer...,,
23,,,for growth in modern trade.
24,• \nStrong competition at the entry-level mark...,,
25,,y,The private label portfolio will be further di...
26,Automation,,
27,,,"tiers, with ventures already made into new cat..."
28,y\nHuman resources and talent management*,,
29,,,the reinstatement of certain categories which ...
30,y\nEnvironment and health & safety*,,discontinued due to economic challenges. The p...
31,,,aims to provide customers with better choice a...
32,y\nInformation technology*,,
33,,,both of which are important decision drivers f...
34,y\nReputation and brand image*,,
35,,,particularly at this juncture.

Table 49:

,0,1,2
0,y,The recent reduction in electricity tariffs wi...,Managing stakeholders:
1,,business in the short-term. Power and energy c...,
2,,,y\nThe business will continue to prioritise tr...
3,,components of the business's cost structure.,
4,,,with customers and active engagement with supp...
...,...,...,...
67,,to build upon.,exemptions in CY2023 for sectors such as healt...
68,,It is pertinent to note that despite the addit...,
69,,associated with the conversion of the standard...,
70,,"the extended format, the payback on these inve...",
71,,incremental performance is attractive.,

Table 50:

,0,1,2,3,4,5,6
0,business is uniquely positioned to capitalise ...,,,,,,
1,leveraging on its high brand equity.,,,,,,
2,,Prospects for the modern trade industry in Sri...,,,,,
3,,given the low penetration of modern trade outl...,,,,,
4,,,,,,,The Supermarket business will continue to focu...
5,Modern Retail Penetration,,,,,,
6,(%),,,,,,
7,,,,,,,• \nEmphasis will primarily be on expansion th...
8,80,,,,,,
9,,,,,,,"outlet format, which optimises capital expendi..."
10,70,,,,,,
11,70,,,,,,
12,,,,,,,costs until such time these earmarked markets ...
13,60,,,,,,
14,,,,,,,business will also evaluate opportunities to g...
15,49,48,,,,,
16,50,,,,,,
17,,,43,,,,outlet format.
18,,,,40,,,
19,40,,,,,,
20,30,,,,,,• \nKey challenges include securing lease of l...
21,20,,,,17,,locations which are in conformity with brand s...
22,10,,,,,,
23,,,,,,y,Further augmenting the DC in Kerawalapitiya wi...
24,0,,,,,,
25,Singapore\nMalaysia,Hong Kong,Taiwan,Thailand,Sri Lanka,,"expansion plans, particularly given its abilit..."
26,Source: Company Analysis,,,,,,of outlets well beyond the medium-term. As out...
27,,,,,,,operation of the DC is expected to result in s...
28,Modern Trade Density,,,,,,
29,,,,,,,"efficiencies, particularly given the centralis..."
30,Population (’000) per Store,,,,,,
31,,,,,,,of the dry and fresh range of the current mode...
32,150,,,,,,
33,132.0,,,,,,
34,,,,,,y,The business will continue to focus on retaini...
35,120,,,,,,"augmenting its recruitment processes, empoweri..."
36,,,,,,,and focusing on the employer brand.
37,90,,,,,,
38,,,,,,y,Continued emphasis will also be placed on high...
39,,,,,,,"penetration, through diversification across pr..."
40,60,,,,,,
41,47.0,,,,,,
42,,,,,,,enhance customer choice and drive margins.
43,30.0,,,,,,
44,30,,,,,,

Table 51:

,0,1,2,3,4,5,6,7,8
0,,City of Dreams Sri Lanka*,,,,,,,
1,,The first fully-fledged integrated resort in t...,,,,,,,
2,South Asia.,,,,,,,,
3,y,,"'Cinnamon Life', a luxurious 687-key hotel which",,,,,,
4,,,"includes 3 ballrooms, 7 meeting rooms, an exhi...",,,,,,
...,...,...,...,...,...,...,...,...,...
72,,,,,Community Services and Infrastructure,,,,
73,,,,,,,,,
74,,10%,,,EBIT,,,,
75,,,,,Projects 6,Rs.'000,"15,076",-,974
76,,,,,1.,Both Occupancy and ARRs exclude 'Cinnamon Red ...,,,

Table 52:

,0,1,2,3,4,5,6,7,8
0,y,,"'Nuwa', a 113-key ultra high-end luxury-standa...",,,,,,
1,,,managed by Melco Resorts & Entertainment (Melco).,,,,,,
2,y,,"~500,000 sq. ft. retail and entertainment space.",,,,,,
3,,,,,,,2023/24,2022/23,2021/22
4,y,,"Lease of 180,000 sq. ft. for a luxury-standard...",,,,,,
...,...,...,...,...,...,...,...,...,...
65,,,,,Community Services and Infrastructure,,,,
66,,,,,,,,,
67,,10%,,,EBIT,,,,
68,,,,,Projects 6,Rs.'000,"15,076",-,974
69,,,,,1.,Both Occupancy and ARRs exclude 'Cinnamon Red ...,,,

Table 53:

,0,1,2,3
0,Revenue,,,
1,,Social and Relationship Capital,,
2,,Community Services and Infrastructure,,
3,EBIT,,,
4,,"Rs.'000\n 15,076\nProjects 6",-,974
5,1.,Both Occupancy and ARRs exclude 'Cinnamon Red ...,,
6,,,,
7,Capital Employed\n57%\n2.,Net of green tax and allocation (F&B charge).,,
8,3.,Revenue is inclusive of the Group's share of e...,,
9,4.,Excludes lease liabilities.,,
10,,,,
11,Carbon Footprint\n5. \n35%,,"For equity accounted investees, capital employ...",
12,,these companies. This is inclusive of lease li...,,
13,6.,Only the contribution to John Keells Foundation.,,
14,John Keells Holdings PLC Annual Report 2023/24,,,

Table 54:

,0,1,2
0,External Environment and Operational Review,,
1,,Macroeconomic Update – Sri Lanka,
2,y,Sri Lanka's cumulative tourist arrivals for th...,y\nThe industry recorded total tourism earning...
3,,"reached close to 1.5 million arrivals, broadly...",CY2023 [CY2022: USD 1.14 billion].
4,,the Sri Lanka Tourism Development Authority (S...,
5,,,y\nHotel room pipeline of Colombo:
6,,"the month of December 2023 crossed 200,000 for...",
7,,,"• \nIn April 2024, the ITC Hotel Group, India,..."
8,,"CY2019, and the momentum was sustained in the ...",
9,,,"in Colombo, a luxury five-star hotel featuring..."
10,,"CY2024, as illustrated below. The financial ye...",
11,,the strongest winter season since the Covid-19...,• \nThe 687 room hotel at the 'City of Dreams ...
12,,,room 'InterContinental' hotel are due to be op...
13,y,Although below pre-pandemic and the peak level...,
14,,,The 113 room ultra high-end luxury-standard ho...
15,,are expected to be over the target of 2.3 mill...,
16,,,Dreams Sri Lanka' is due to be opened in mid-2...
17,,by the increased air connectivity to the count...,
18,,commencement of a concerted destination market...,Key Policy and Regulatory Highlights
19,,"• \nTourist arrivals to Sri Lanka stood at 1,4...",y\nThe value added tax (VAT) rate was increase...

Table 55:

,0,1
0,,The 113 room ultra high-end luxury-standard ho...
1,are expected to be over the target of 2.3 mill...,
2,,Dreams Sri Lanka' is due to be opened in mid-2...
3,by the increased air connectivity to the count...,
4,commencement of a concerted destination market...,Key Policy and Regulatory Highlights
5,"• \nTourist arrivals to Sri Lanka stood at 1,4...",y\nThe value added tax (VAT) rate was increase...
6,marking a twofold increase against the previou...,with effect from 1 January 2024.
7,"719,978 arrivals].",
8,,y\nSLTDA published an Extraordinary Gazette st...
9,• \nTotal arrivals from January to April 2024 ...,
10,,room rates (MRRs) to be charged by tourist hot...
11,which is ~90% of the arrivals recorded in the ...,
12,,"limits of the Colombo Municipal Council, effec..."
13,CY2018.,
14,,• \nRates (excluding service charges and taxes...
15,• \nKey source markets driving arrivals during...,
16,"followed by Russia, the United Kingdom and Ger...",establishment:
17,,• \n5-star tourist hotels – USD 100
18,"• \nFor 2023/24, tourist arrivals stood at 1,7...",
19,,• \n4-star tourist hotels – USD 75
20,"770,323 arrivals recorded in 2022/23.",
21,,• \n3-star tourist hotels – USD 50
22,Tourist Arrivals to Sri Lanka,• \n2-star tourist hotels – USD 35
23,Arrivals (’000),
24,,• \n1-star tourist hotels – USD 20
25,250,
26,218,
27,210\n208\n209,

Table 56:

,0,1,2,3
0,INDUSTRY GROUP REVIEW,,,
1,LEISURE,,,
2,,,,Colombo Hotels\n2023/24\n2023/24\n2022/23
3,,,,Q1\nQ2\nQ3\nQ4
4,,,,Average Room Rate
...,...,...,...,...
63,,,,both occupancy and room rates on the back of a
64,although overall occupancies were marginally i...,,,
65,,,,sustained recovery in tourist arrivals to the ...
66,the peak months of December and January.,,,
67,168,John Keells Holdings PLC Annual Report 2023/24,,

Table 57:

,0,1
0,,Maldivian Resorts
1,,"During the year under review, performance of t..."
2,AWARDS,
3,,segment was encouraging as occupancies and ARR...
4,y\n'Cinnamon Lodge Habarana' was awarded 'Sri ...,
5,,particularly in the second half of the year in...
6,Resort' at the World Travel Awards.,
7,,during the winter season. The appreciation of ...
8,y\nSouth Asian Travel Awards (SATA) 2023:,~11% on average in 2023/24 had an offsetting i...
9,,"especially during the fourth quarter, which is..."
10,• \n'Cinnamon Wild Yala' received Gold for 'Le...,
11,,commanded the highest ARR.
12,– Tented Camp'.,
13,• \n'Cinnamon Citadel Kandy' received Silver f...,
14,,Occupancy levels of the Maldivian Resorts segm...
15,Riverfront Hotel/Resort'.,
16,,comparison to the previous year given a change...
17,,"overall arrivals to the Maldives, where arriva..."
18,,higher yields were lower. While higher volumes...
19,Macroeconomic Update – The Maldives,"also impacted business, to an extent, this was..."
20,,period. It is encouraging to note that occupan...
21,y\nThe gross domestic product (GDP) of the Mal...,
22,,Resorts segment outperformed the industry aver...
23,to increase by 8.7% during CY2023 [CY2022: 13....,
24,,"in 2023/24, although the industry average comp..."
25,y\nThe Maldives recorded a 12% increase in arr...,
26,,varying segments as well.
27,"1.9 million tourist arrivals in CY2023, in com...",
28,"million arrivals in CY2022, which surpasses pr...",
29,,"During the year, the Maldivian tourism industr..."
30,observed in CY2019 of 1.7 million arrivals.,
31,,stemming from a higher cost base as a result o...
32,,"such as the goods and services tax (GST), and ..."
33,Tourist Arrivals to the Maldives,
34,Arrivals (’000),comparison to the previous financial year.
35,250,
36,217,
37,194\n195\n192,
38,200\n178\n174,
39,169\n172\n164\n159\n164\n155,"Despite the increase in ARRs, margins were imp..."
40,146,
41,131\n150,
42,121,
43,120,occupancy levels in the first half of the year...
44,100,
45,,seen in the second half of the year as occupan...
46,50,
47,,with the decrease in fuel costs during the year.
48,January\nMarch\nApril\nMay\nJune\nJuly\nAugust\n0,

Table 58:

,0,1,2,3,4,5,6,7,8
0,,100,,,,,,,
1,,,,seen in the second half of the year as occupan...,,,,,
2,,50,,,,,,,
3,,,,with the decrease in fuel costs during the year.,,,,,
4,,March\nApril\nMay\nJune\nJuly\nAugust\n0,,,,,,,
5,,January\nFebruary\nSeptember\nOctober\nNovembe...,Maldivian Resorts,,2023/24,,,2023/24,2022/23
6,,CY23\nCY24,,,,,,,
7,,,,Q1,Q2,Q3,Q4,,
8,y,Key source markets driving arrivals during CY2...,,,,,,,
9,,,Average Room Rate,,,,,,
10,,"followed by Russia, China, the United Kingdom ...",,,,,,,
11,,,(USD)*,235,212,282,362,275,255
12,y,Occupancy rates at tourist establishments by t...,Occupancy (%),82,82,88,90,86,88
13,,,Average LKR/USD,,,,,,
14,%,CY2023\nCY2022,exchange rate,310,322,323,313,318,360

Table 59:

,0,1,2
0,y,Occupancy rates at tourist establishments by t...,
1,%,CY2023,CY2022
2,Resort,66,71
3,Hotel,35,36
4,Guest houses,43,31
5,Tourist vessels,24,24
6,Average occupancy,58,59
7,Source: Ministry of Tourism - Maldives,,

Table 60:

,0,1
0,LEISURE,
1,,"During the year under review, the business com..."
2,Spillover Benefits to Hotels within Integrated...,of onboarding new employees with the requisite...
3,,'Cinnamon Life' in line with international hos...
4,y\nThe expectation that the two integrated res...,
...,...,...
65,,recognition of recurring revenue from the ten ...
66,'Cinnamon Life' Hotel,Cinnamon Life' that are leased out continued d...
67,The 687-key 'Cinnamon Life' hotel and related ...,review. The business continued to engage with ...
68,"stages of fit-out and completion, with the fit...",occupy the remaining office space.
69,rooms nearing completion. 'Cinnamon Life' is s...,

Table 61:

,0,1,2
0,Financial Performance Review,y,The primary drivers for the improvement in EBI...
1,,,aforementioned factors driving revenue.
2,Income Statement Indicators,,
3,,y,The EBITDA of 'City of Dreams Sri Lanka' inclu...
4,Rs.million\n2023/24\n2022/23\n%,,
...,...,...,...
78,"Maldivian Resorts\n 299 \n 1,017 \n...",,the recurring EBITDA of the industry group exc...
79,Destination Management\n 63 \n (147...,,"amounted to Rs.9.06 billion, a 5% increase aga..."
80,"Hotel Management \n 805 \n 1,142 \n...",,[2022/23: Rs.8.60 billion]. The recurring PAT ...
81,"Total \n 3,410 \n (429)\n895",,excluding the deferred tax asset write-off of ...
82,*EBITDA includes interest income and the share...,,

Table 62:

,0,1,2,3,4,5,6,7,8,9,10
0,LEISURE,,,,,,,,,,
1,Balance Sheet Indicators,,,,Lease liabilities as at 31 March 2024 stood at...,,,,,,
2,,,,,"Rs.22.81 billion], with ~97% stemming from the...",,,,,,
3,Rs.million,2023/24,2022/23,%,,,,,,,
4,,,,,segment. Total debt including leases stood at ...,,,,,,
5,,,,,March 2024 [2022/23: Rs.125.25 billion].,,,,,,
6,Assets,,,,,,,,,,
7,City of Dreams Sri Lanka,"250,261","235,452",6,,,,,,,
8,,,,,Return on Capital Employed (ROCE) Analysis,,,,,,
9,Colombo Hotels,"41,865","39,269",7,,,,,,,
10,Sri Lankan Resorts,"23,979","23,236",3,,,,,,,
11,,,,,ROCE,=,EBIT,x,Asset,x,Capital
12,Maldivian Resorts,"53,242","61,916",(14),,,,,,,
13,,,,,(%),,margin,,turnover,,structure
14,Destination Management,"3,214","1,807",78,,,,,,,
15,,,,,,,(%),,,,leverage
16,Hotel Management,"3,164","2,401",32,,,,,,,
17,Total,"375,725","364,081",2023/24\n3,1.0,,7.3,,0.13,,1.06
18,,,,2022/23,1.2,,6.6,,0.16,,1.06

Table 63:

,0,1,2,3
0,Destination Management,"3,214 \n1,807\n78",,
1,,,,(%)\nleverage
2,Hotel Management,"3,164 \n2,401\n32",,
3,Total,"375,725 \n364,081\n3",2023/24,1.0\n7.3\n0.13\n1.06
4,,,2022/23,1.2\n6.6\n0.16\n1.06
5,y,Given the near completion of the construction ...,,
6,,"Sri Lanka', capitalisation of construction cos...",y,The ROCE of the Leisure industry group is dist...
7,,gaming spaces was undertaken based on the comp...,,"operational costs, capital and asset recogniti..."
8,,project.,,"Sri Lanka' project, which is under constructio..."
9,,,,"revenue generation, thereby adversely impactin..."
10,y,No significant capital expenditure was underta...,,
11,,,,industry group.
12,,"Leisure industry group, apart from maintenance...",,
13,,,y,"Excluding 'City of Dreams Sri Lanka', the ROCE..."
14,y,The trade receivables of the Destination Manag...,,
15,,,,"group was 1.3%, driven by both higher rates an..."
16,,increased due to enhanced operations in compar...,,
17,,,,EBIT margin for the Maldivian Resorts declined...
18,,previous year.,,
19,,,,impact resulting from the appreciation of the ...
20,y,The growth in assets of the Hotel Management s...,,
21,,,y,"During the year, Rs.19.58 billion of cash equi..."
22,,an increase in investments in associates from ...,,
23,,,,Dreams Sri Lanka' to finance the development c...
24,,"the development of the 215-key hotel in Kandy,...",,
25,,John Keells Hotels PLC (KHL) and Indra Traders...,y,"As at 31 March 2024, the cumulative figures fo..."
26,,an increase in cash.,,at Rs.172.03 billion. The cumulative equity in...
27,,,,of Dreams Sri Lanka' includes the land transfe...
28,,,,subsidiaries at the inception of the project. ...
29,Rs.million,2023/24\n2022/23\n%,,
30,,,,"costs including interest costs, unless explici..."
31,Debt*,,,
32,,,,in accordance with Sri Lanka Accounting Standa...
33,City of Dreams Sri Lanka,"66,164 \n74,423\n(11)",,

Table 64:

,0,1
0,"pandemic, and thereafter the macroeconomic cri...",
1,significant pressure on performance. Tourism w...,
2,propelling the ongoing recovery of the economy...,
3,momentum and encouraging contribution witnesse...,
4,,Immediate to Short-Term
5,continued to drive economic performance quarte...,
6,,Global Tourism
7,witnessed historically.,
8,,The United Nations World Tourism Organisation ...
9,"Sri Lanka recorded 1,787,408 tourist arrivals ...",international tourism in CY2023 stood at 88% o...
10,tourist arrivals from December 2023 onwards ex...,with ~1.3 billion arrivals globally. UNWTO pro...
11,mark consecutively. Growth was primarily drive...,"pandemic levels in CY2024, estimating a 2% gro..."
12,"countries such as India, Russia, Germany, the ...",underpinned by the release of the residual pen...
13,Australia. The industry is envisaged to sustai...,connectivity and the robust rebound of the Asi...
14,on the back of accommodative travel policies a...,World Travel and Tourism Council (WTTC) has pr...
15,a destination in terms of the diverse and uniq...,"year for travel and leisure, with tourism esti..."
16,"Additionally, although the local currency has ...",high of USD 11.1 trillion to the global econom...
17,"average since 2022/23, Sri Lanka continues to ...",
18,,International tourist arrivals
19,advantage from a pricing perspective due to th...,(millions)
20,"of the Rupee in 2022. Against this backdrop, t...","1,462"
21,,Global Economic Crisis (CY09)

Table 65:

,0,1
0,Outlook and Risks,
1,,Trends and Opportunities
2,Tourism has been a key driver of Sri Lanka's e...,
3,"past, generating significant foreign exchange ...",
4,,"y\nRising demand for tourism, especially from ..."
5,"opportunities, whilst also fostering cultural ...",
6,,y\nShifting traveller preferences with particu...
7,conservation. It is a low-hanging fruit that h...,
8,,"eco-friendly, sustainable and experiential tra..."
9,the country as a tourism hub in the South Asia...,
10,,'green holiday destinations'
11,"given its geographical diversity, rich cultura...",
12,,y\nDigital nomadism
13,two of the largest outbound travel markets in ...,
14,,y\nDigital transformation in travel planning a...
15,The tourism industry in Sri Lanka underwent un...,
16,,y\nDiversification of tourism offerings
17,across four consecutive years since the Easter...,
18,,"y\nIncreasing opportunities for meetings, ince..."
19,"April 2019, the subsequent global and local ou...",
20,,and exhibitions (MICE)
21,"pandemic, and thereafter the macroeconomic cri...",
22,significant pressure on performance. Tourism w...,
23,propelling the ongoing recovery of the economy...,
24,momentum and encouraging contribution witnesse...,
25,,Immediate to Short-Term
26,continued to drive economic performance quarte...,
27,,Global Tourism
28,witnessed historically.,
29,,The United Nations World Tourism Organisation ...
30,"Sri Lanka recorded 1,787,408 tourist arrivals ...",international tourism in CY2023 stood at 88% o...
31,tourist arrivals from December 2023 onwards ex...,with ~1.3 billion arrivals globally. UNWTO pro...
32,mark consecutively. Growth was primarily drive...,"pandemic levels in CY2024, estimating a 2% gro..."
33,"countries such as India, Russia, Germany, the ...",underpinned by the release of the residual pen...
34,Australia. The industry is envisaged to sustai...,connectivity and the robust rebound of the Asi...
35,on the back of accommodative travel policies a...,World Travel and Tourism Council (WTTC) has pr...
36,a destination in terms of the diverse and uniq...,"year for travel and leisure, with tourism esti..."
37,"Additionally, although the local currency has ...",high of USD 11.1 trillion to the global econom...
38,"average since 2022/23, Sri Lanka continues to ...",
39,,International tourist arrivals
40,advantage from a pricing perspective due to th...,(millions)
41,"of the Rupee in 2022. Against this backdrop, t...","1,462"
42,,Global Economic Crisis (CY09)
43,,"1,286"
44,that the prospects for tourism remain extremel...,
45,,SARS (CY03)
46,"Key risks, trends and opportunities relevant t...",960
47,,Covid-19 (CY20)

Table 66:

,0,1,2,3,4,5,6,7,8,9,10,11
0,,,,,,,Covid-19 (CY20),,,,,
1,Risks,,,,,,,,,,,
2,,,,,,,,,,,457,
3,,,,,,,,,407,,,
4,y,Macroeconomic and political environment*,,,,,,,,,,
5,,• \nLower than planned growth in tourist arrivals,CY00\nCY02\nCY04\nCY06\nCY08,CY10,CY12\nCY14,,CY16\nCY18,,CY20,,CY22,CY24
6,,,Source: UNWTO (January 2024).,,,,,,,,,
7,,• Changes in regulatory environment*,,,,,,,,,,
8,,,Note: CY23 - provisional data.,,,,,,,,,
9,y,Supply chain disruptions*,,,,,,,,,,
10,,• \nPotential increase in input costs stemming...,,,,,,,,,,
11,,,,International tourist arrivals from CY2020 to ...,,,,,,,,
12,,"tensions, global impacts and domestic developm...","(Monthly change over CY19, %)",,,,,,,,,
13,,,CY20\nCY21,,CY22,,CY23*,,,,CY24*,
14,y,"Financial exposure*, in particular exchange ra...",,,,,,,,,,
15,,,0,,,,,,,,,
16,y,Global competitiveness* and evolving consumer ...,Jan\nMar\nMay\nJul\nSep\nNov\nJan\nMar\nMay\nJ...,Jan,Mar\nMay\nJul\nSep\nNov,Jan,Mar\nMay\nJul\nSep,Nov,Jan,Mar,May\nJul,Sep\nNov
17,,,(16),,,,,(11),,,,
18,,,(20),,,,,,,,,
19,,,,,,,,,,,,
20,y,Human resources and talent management*,(72)%\n(69)%,,,,(19),,,,,
21,,,,,(24),,,,,,,
22,,,Annual change\nAnnual change,,,,,,,,,
23,,,,,,,,,,,,
24,y,Climate risks*,(over CY19)\n(over CY19)\n(40),,,,,,,,,
25,y,Environment and health & safety*,,,,,,,,,,
26,,,(60),,,,,,,,,
27,,,,,,,,,,,,
28,,• \nImpact on eco-systems and biodiversity,(64),63),(34)%,,(12)%,,,,,
29,,,,,Annual change,,Annual change,,,,,
30,,,(74)\n(80),,,,,,,,,
31,,• Waste generation and management,,,(over CY19),,(over CY19),,,,,
32,,,(87)\n(86),,,,,,,,,
33,,,(90),,,,,,,,,
34,,• Health and safety of employees and guests,(100),,,,,,,,,
35,y,Information technology*,,,,,,,,,,
36,,,+2%\nProjection:\nCY24 change,,,,,,,,,
37,,,(Over CY19)\nActual data*,,,,,,,,,
38,y,Reputation and brand image*,,,,,,,,,,
39,,,Source: UNWTO (January 2024).,,,,,,,,,

Table 67:

,0,1,2
0,Demand and supply dynamics:,,y\nConstruction work at 'City of Dreams Sri La...
1,,,as 'Cinnamon Life Integrated Resort') is progr...
2,y,The Sri Lankan Leisure businesses will continu...,
3,,,"hotel, retail and entertainment components in ..."
4,,"rate strategy to ensure optimum returns, takin...",
...,...,...,...
80,,,'pent-up' demand and demonstrating the potenti...
81,,operations in the third quarter of 2024/25 and...,
82,,,recent rise in alternative accommodation chann...
83,,such as an expansive rooftop bar and a swimmin...,
84,,others.,

Table 68:

,0,1,2,3,4,5
0,,,,2023/24,2022/23,2021/22
1,• \nThe development and sale/rental of units o...,,,,,
2,"office tower, 'The Offices at Cinnamon Life'.",,,,,
3,,Operational Highlights,,,,
4,,City of Dreams Sri Lanka,,,,
5,"y\n'TRI-ZEN', a residential apartment developm...",,,,,
6,,The Residence at Cinnamon Life,No. of units,147,151,152
7,on smart living in the heart of the city.,,,,,
8,,The Suites at Cinnamon Life,No. of units,109,115,115
9,"y\n'VIMAN', a suburban residential apartment",TRI-ZEN,No. of SPAs,700,655,652
10,development located in the heart of Ja-Ela.,VIMAN,No. of SPAs,100,N/A,N/A
11,,Financial and Manufactured Capital,,,,
12,y\nDevelopment of holiday homes at 'Victoria Golf,,,,,
13,,Revenue 1,Rs.million,"5,234","4,577","41,476"
14,"Resort' in Rajawella, Kandy.",,,,,
15,,EBITDA,Rs.million,(822),(215),"2,965"
16,y\nPrevious residential apartment projects: 'O...,PBT,Rs.million,(857),"(2,135)",(847)
17,"'7th Sense on Gregory's Road', 'Monarch', and",PAT,Rs.million,(569),"(2,350)",(986)
18,'Emperor'.,Total assets,Rs.million,"84,519","94,321","276,754"
19,,Total equity,Rs.million,"77,713","88,347","166,895"
20,"Note: The hotel, retail and gaming spaces with...",,,,,
21,,Total debt 2,Rs.million,"1,033","1,161","102,260"
22,Sri Lanka' is captured under the Leisure indus...,,,,,
23,,Capital employed 3,Rs.million,"78,746","89,509","269,155"
24,,Natural Capital,,,,
25,Property Management,,,,,
26,,Energy consumption,kWh,"2,208,306","1,096,365","1,045,212"
27,y\nRental of commercial office space.,Energy consumption per operational,kWh per,,,
28,,intensity factor,Rs.million,895.50,388.37,28.75
29,y\nManagement of the Group's real estate portf...,,,,,
30,,Carbon footprint,MT,"1,600.67",831.72,801.57
31,y\nOwnership and operation of the 'Crescat Bou...,Carbon footprint per operational,MT per,,,
32,,intensity factor,Rs.million,0.65,0.29,0.02
33,mall and management of the 'K-Zone' mall in,,,,,
34,Moratuwa.,Water withdrawal,m3,"188,789","145,336","230,110"
35,,Water withdrawal per operational,m3 per,,,
36,y\nOperation of the 18-hole championship golf ...,,,,,
37,,intensity factor,Rs.million,76.56,51.48,6.33
38,"and resort, and development and management of",,,,,
39,,Volume of hazardous waste generated,kg,0,0,0
40,"the land bank in Rajawella, Kandy.",,,,,
41,,Volume of non hazardous waste,,,,
42,,generated,kg,"55,596","40,381","38,225"
43,,Waste generated per operational,kg per,,,
44,,intensity factor,Rs.million,22.55,14.30,1.05
45,,Human Capital,,,,
46,,Total Workforce (employees and,,,,
47,,contractors' staff ),No.,303,299,270
48,,EBIT per employee,Rs.million,(3),(1),11
49,,Average training per employee,hours,5.85,2.59,0.94
50,Contribution to the John Keells Group,Total Attrition,%,24.3,23.2,24.6
51,,Females employee,%,26.8,22.5,25.7
52,Revenue\n2%,,,,,
53,,Total injuries,No.,2,0,0
54,,Social and Relationship Capital,,,,
55,,,,,,
56,EBIT\n(3%),Community Services and Infrastructure,,,,
57,,Projects4,Rs.'000,473,"6,697",-
58,,,,,,
59,Capital Employed\n13%,1.,Revenue is inclusive of the Group's share of e...,,,

Table 69:

,0,1,2,3,4,5
0,"y\nThe Group's integrated resort, branded 'Cit...",,,,,
1,"Dreams Sri Lanka', which comprises of:",,,,,
2,• \nThe development and sale of two residential,,,,,
3,apartment towers; 'The Suites at Cinnamon Life',,,,,
4,and 'The Residence at Cinnamon Life'.,,,,,
...,...,...,...,...,...,...
60,,,,,,
61,EBIT\n(3%),Community Services and Infrastructure,,,,
62,,Projects4,Rs.'000,473,"6,697",-
63,,,,,,
64,Capital Employed\n13%,1.,Revenue is inclusive of the Group's share of e...,,,

Table 70:

,0,1
0,External Environment and Operational Review,The year under review witnessed an encouraging...
1,,in the real estate industry of Sri Lanka on th...
2,Macroeconomic Update,interest rates and overall construction costs ...
3,,supported by a stabilising exchange rate. This...
4,y\nThe construction sector accounted for 6.2% ...,
...,...,...
70,open in October 2024. The highway will connect...,"the 'Cinnamon Life' hotel, due to be launched ..."
71,"economic centre, Colombo, via the Colombo Port...",
72,,2024/25. The remainder of the integrated resor...
73,Colombo and the Bandaranaike International Air...,
74,,"key 'Nuwa' hotel, casino and the mall is slate..."

Table 71:

,0,1,2,3,4
0,,,,,"Colombo Port Access highway, while retaining t..."
1,,'The Suites,'The Residence,'The Offices at,
2,,,,,town setting.
3,,at Cinnamon,at Cinnamon,Cinnamon Life',
4,,Life',Life',,
5,,,,,The project is built on the land which was pre...
6,,,,,the 'K-Zone Ja-Ela' mall. The mall was permane...
7,Structure,y\n39-storey,y\n45-storey,y\n30-storey tower,
8,,tower,tower,,January 2024 to facilitate the impending const...
9,,,,y\n24 floors,
10,,,,,residential development project. The closure i...
11,,y\nTotal of 196,y\nTotal of 231,allocated for,
12,,,,,"asset write-off, as detailed in the ensuing Fi..."
13,,apartment,apartments,outright sales,
14,,,,,section. Given the demand for suburban living ...
15,,units,units,and rent,
16,,,,,of the view that the project is an optimum mon...
17,,,,y\nFeatures five,
18,,,,,through development and sales.
19,,,,floors reserved,
20,,,,for car parking,
21,,,,,The preliminary sales interest for the project...
22,Number of,109 units sold,147 units sold,y\nFour floors sold,
23,,,,,with the first phase of the project consisting...
24,units sold/,(57% of total,(70% of total,outright,
25,,,,,sold out within six months since the launch of...
26,occupied as,sellable area),sellable area),,
27,,,,y\n10 floors rented,
28,,,,,"2023. Given the traction for the project, the ..."
29,at 31 March,,,,
30,,,,(58% of floors,
31,,,,,in March 2024. The construction of the first p...

Table 72:

,0,1
0,INDUSTRY GROUP REVIEW,
1,PROPERTY,
2,Residential and Office,
3,,'TRI-ZEN' Cumulative Sales and Purchase Agreem...
4,The sales momentum for the residential apartme...,
...,...,...
57,,in March 2024. The construction of the first p...
58,2024,
59,sold/occupied in,
60,,expected to commence mid-2024.
61,total),

Table 73:

,0,1,2
0,total),,
1,The sales of 'The Suites at Cinnamon Life' and...,,
2,,INSIGHTS,
3,Life' stood at 65% of the total sellable area....,,
4,of the residential units sold were handed over...,Features,Details
5,recognised in lieu of residential sales during...,,"Ja-Ela, a suburban area in close proximity"
6,,Location,
7,were no new sales.,,to Colombo
8,,Land extent,6 acres
9,The recognition of recurring revenue from the ...,,
10,Cinnamon Life' that are leased out continued d...,,418 units – with equal distribution
11,,Units,
12,The business continued to engage with prospect...,,between 2 and 3 bedroom units
13,remaining office space.,,Total of 10 blocks (G+4 floors) and each
14,,Structure,
15,,,block will comprise between 36 to 60 units
16,TRI-ZEN,,
17,,,"In phases – Phase 1: 114 units (80% sold),"
18,"'TRI-ZEN', a residential development project w...",Launch,"Phase 2 and 3: 76 units each, Phase 4: 152"
19,"the city, capitalises on the increasing demand...",,units
20,and efficient living solutions. Positioned wit...,Cumulative SPAs,Phase 1: 94 SPAs of 114 units
21,"segment, the project leverages on innovative d...",(as at 31 March 2024),
22,,,Phase 2: 6 SPAs of 76 units
23,"points, space efficiency and the need for mode...",,
24,,Completion,Q3 2026/27 (all phases)
25,Marking a milestone for John Keells Properties...,,
26,,,Will be in a phased-out manner.
27,891-unit residential development comprising of...,,
28,,Collection,"Upon signing the SPA, an upfront payment of"
29,"required clearances, including the Certificate...",,
30,,,"10%, subsequently 10%, 25%, 30% and 25%."
31,over of units has commenced from April 2024. '...,,
32,,Revenue,
33,encouraging momentum in sales during the curre...,,Based on the percentage of completion.
34,,recognition,
35,the cumulative sales and purchase agreements (...,,
36,,,"Swimming pool, gymnasium, meditation"
37,'TRI-ZEN' residential development project incr...,,
38,,,"courts, clubhouse, a kids play area, cycling"
39,,Amenities,
40,units. Further traction in sales is expected g...,,
41,,,and walking spaces and a multipurpose
42,"project, the market adjusting to the new price...",,outdoor sports court.
43,"the relatively higher replacement costs, and t...",,

Table 74:

,0,1,2
0,Offerings at RHL,y Operation of a golf course in partnership with,9 land plots \n16 land plots \n4 land plots \n...
1,,Troon International.,(100% sold)\nwith villas (80% \n(100% sold)
2,,,sold)
3,,y Management of the 'Victoria Golf Resort'.,
4,Performance during,y Operations noted an improvement,y\nRHL rebranded the development project named...
5,the year,with increases in room nights and other,"'Rigdeview', which offers 18 exclusive land pl..."
6,,supplementary services aided by higher footfall.,
7,,,y\nThe construction of 'Sunrise Ridge' villas ...
8,,,year with hotel operations for the 16 villas e...
9,,,in Q1 2024/25. The sale of land plots was chal...
10,,,high construction costs. The sales of the rema...
11,,,expected to pick up in tandem with the commenc...
12,,,operations at 'Sunrise Ridge'.

Table 75:

,0,1,2
0,PROPERTY,,
1,Financial Performance Review,,"y\nAlthough recording a negative EBITDA, the i..."
2,,,"of the Property Development sector, as against..."
3,Income Statement Indicators,,
4,,,primarily stemmed from higher revenue recognit...
5,Rs.million\n2023/24\n2022/23,%,"profitability of 'TRI-ZEN', which records the ..."
6,,,after tax as it is an equity accounted investe...
7,Revenue*,,higher finance expenses on account of higher t...
8,"Property Development \n4,688 \n 3,926",19,"capital requirements. In addition, profitabili..."
9,,,"approved cost escalations in the project, whic..."
10,Property Management\n546\n 651,(16),
11,,,profit recognition in the fourth quarter of th...
12,"Total\n5,234 \n 4,577",14,
13,,,y\nDiscussions on EBITDA for the Property indu...
14,*Including share of revenue of equity accounte...,,
15,,,of fair value gains/losses on investment prope...
16,,,the view that fair value gains/losses on IP ar...
17,Property Development,,
18,,,"group's core operations, given the land bankin..."
19,y\n'TRI-ZEN' recognised revenue during the yea...,,
20,,,intention of monetising such land through deve...
21,sales and the completion of construction work....,,
22,an encouraging momentum during the year in tan...,,• \nThe fair value gains/losses on IP for the ...
23,recovery in the macroeconomic environment with...,,to a gain of Rs.233 million in 2023/24 in comp...
24,purchase agreements (SPAs) signed.,,Rs.525 million recorded in 2022/23.
25,y\nThe revenue of the Property Development sec...,,y\nThe PBT of the industry group increased on ...
26,income from the leasing of ten floors of 'The ...,,gains recognised at Waterfront Properties (Pri...
27,,,on contractor settlements due to the appreciat...
28,y\nThe previous year includes revenue recognit...,,
29,,,subsequent to the accounting treatment post co...
30,"in Digana, through Rajawella Holdings (Private...",,
31,,,functional reporting currency of WPL to Rupees.
32,sales were recorded during the year under review.,,
33,,,"It should be noted that in 2022/23, the PBT of..."
34,Property Management,,
35,,,was impacted on account of the one-off exchang...
36,y\nMall operations witnessed a recovery driven...,,"collections at 'City of Dreams Sri Lanka', for..."
37,"the year under review, with the easing of macr...",,revenue was recognised in 2021/22.
38,in comparison to the previous year. Occupancy ...,,
39,,,Balance Sheet Indicators
40,Boulevard' increased to 85% as at the end of 2...,,
41,to 73% in 2022/23.,,
42,,,Rs.million\n2023/24\n2022/23\n%
43,"y\nThe 'K-Zone' mall in Ja-Ela, held under Joh...",,
44,,,Assets
45,"(Private) Limited, was permanently shut down i...",,
46,,,"Property Development \n 73,041 \n82,578\n(12)"
47,facilitate the impending construction work for...,,
48,,,"Property Management\n 11,478 \n11,743 \n(2)"
49,"development project 'VIMAN', which is being bu...",,
50,,,"Total\n 84,519 \n94,321\n(10)"
51,occupied by the mall.,,
52,,,Debt*
53,Rs.million\n2023/24\n2022/23,%,Property Development \n714 \n763\n(6)
54,,,Property Management\n319 \n398\n(20)
55,EBITDA*,,
56,,,"Total\n1,033 \n 1,161 \n(11)"
57,Property Development \n(105)\n(440),76,

Table 76:

,0,1,2
0,,,"is notably higher than its regional peers, ind..."
1,y,The Group will continue to explore investment ...,
2,,,potential for smart housing solutions at affor...
3,,emerging suburban areas of Colombo to expand i...,
4,,given the growing demand and potential of the ...,
5,,account of the high prices associated with res...,~60-70 per cent of housing in regional mega ci...
6,,Colombo. The Group is evaluating the potential...,"and mid-tier, are predominantly apartments. Ho..."
7,,at the 12-acre land bank in Thudella (a part o...,"living in Colombo is ~10 per cent, despite the..."
8,,portfolio) to venture further into this segment.,"the city, representing an opportunity within t..."
9,y,The Group is of the view that the existing lan...,Mix of apartments and landed housing in region...
10,,,(%)
11,,to sustain a steady pipeline of projects in th...,
12,,given the 9.38 acre property held under Vauxha...,100

Table 77:

,0,1,2,3
0,PROPERTY,,,
1,y,Construction of the first phase of the Group's...,y,The market for vertical and middle-income hous...
2,,"suburban market, 'VIMAN' which is located in J...",,"expected to experience significant growth, in ..."
3,,commence mid-2024. The project comprises of fo...,,"of its regional peers, given increasing land p..."
4,,expectation that the entirety will be conclude...,,high costs associated with the construction of...
5,,of 2026/27.,,The proportion of landed housing to apartments...
6,,,,"is notably higher than its regional peers, ind..."
7,y,The Group will continue to explore investment ...,,
8,,,,potential for smart housing solutions at affor...
9,,emerging suburban areas of Colombo to expand i...,,
10,,given the growing demand and potential of the ...,,
11,,account of the high prices associated with res...,,~60-70 per cent of housing in regional mega ci...
12,,Colombo. The Group is evaluating the potential...,,"and mid-tier, are predominantly apartments. Ho..."
13,,at the 12-acre land bank in Thudella (a part o...,,"living in Colombo is ~10 per cent, despite the..."
14,,portfolio) to venture further into this segment.,,"the city, representing an opportunity within t..."
15,y,The Group is of the view that the existing lan...,,Mix of apartments and landed housing in region...
16,,,,(%)
17,,to sustain a steady pipeline of projects in th...,,
18,,given the 9.38 acre property held under Vauxha...,,100
19,,,,90\n5\n20\n40\n30\n50\n45\n35
20,,"(Private) Limited (VLDL). As such, the Group w...",,
21,,,,80
22,,on the monetisation of this extensive land ban...,,
23,,,,60
24,,"circumstances, the Group does not foresee the ...",,
25,,significant capital in the Property industry g...,,40
26,y,Strategic land parcels at VLDL have already be...,,20
27,,,,10\n95\n80\n60\n70\n50\n55\n65
28,,capitalise on monetising opportunities.,,
29,,,,0
30,,,,Thailand\nMalaysia\nMalaysia\nIndia\nIndia\nGr...
31,,,,
32,y,The Group has already commenced the gradual mo...,,(Outskirts)\n(Central KL)\n(Greater KL)\n(Chen...
33,,,,Bangkok)
34,,"the land bank in Digana, through various real ...",,
35,,,,Apartments\nLanded houses
36,,"Rajawella Holdings (Private) Limited, which in...",,
37,,,,Source: Company Analysis
38,,"parcels, townhouses and villa developments, as...",,
39,,Operational Review.,,
40,,,y,The Group will leverage on its high brand equi...

Table 78:

,0,1,2,3,4,5,6
0,Banking,,,,,,
1,,,,,2023/24,2022/23,2021/22
2,y,End-to-end banking solutions through Nations T...,,,,,
3,,,Operational Highlights 1,,,,
4,,Bank PLC (NTB).,,,,,
5,,,UA - Market share,%,12,12,12
6,,• Network of branches for commercial banking.,GWP growth,%,13,8,18
7,,• \nSole acquirer of the flagship centurion pr...,NTB - Loan growth,%,12,(3),18
8,,range of 'American Express' cards in Sri Lanka.,Net interest margins,%,7.7,7.0,3.9
9,,,Stage 3 loan ratio (net),%,2.3,2.6,2.1
10,,,Financial and Manufactured Capital,,,,
11,Stockbroking,,,,,,
12,,,Revenue 2,Rs.million,"33,336","27,770","24,149"
13,y,Stockbroking services through John Keells Stock,,,,,
14,,,EBITDA,Rs.million,"9,296","6,802","5,024"
15,,Brokers (Private) Limited (JKSB).,,,,,
16,,,PBT,Rs.million,"9,293","6,751","4,995"
17,,,PAT,Rs.million,"7,794","5,673","4,314"
18,,,Total assets,Rs.million,"104,453","86,475","74,248"
19,,,Total equity,Rs.million,"28,263","22,184","17,100"
20,,,Total debt 3,Rs.million,75,141,161
21,,,Capital employed 4,Rs.million,"28,745","22,743","17,705"
22,,,Natural Capital,,,,
23,,,Energy consumption,kWh,"1,516,760","1,391,813","1,259,467"
24,,,Energy consumption per operational,kWh per,,,
25,,,intensity factor,Rs.million,81.26,85.89,80.29
26,,,Carbon footprint,MT,1061.00,988.65,884.75
27,,,Carbon footprint per operational,MT per,,,
28,,,intensity factor,Rs.million,0.06,0.06,0.06
29,,,Water withdrawal,m3,"15,994","14,519","14,818"
30,,,Water withdrawal per operational,m3 per,,,
31,,,intensity factor,Rs.million,0.86,0.90,0.94
32,,,Volume of hazardous waste generated,kg,0,0,0
33,,,Volume of non hazardous waste,,,,
34,,,generated,kg,"4,155","4,205","4,043"
35,,,Waste generated per operational,kg per,,,
36,,,intensity factor,Rs.million,0.22,0.26,0.26
37,,,Human Capital,,,,
38,,,Total Workforce (employees and,,,,
39,,,contractors' staff ),No.,"4,190","4,515","4,708"
40,,,EBIT per employee,Rs.million,12,8,6
41,,,Average training per employee,hours,13.89,13.60,2.00
42,,,Total Attrition,%,44,35,42.3
43,Contribution to the John Keells Group,,,,,,
44,,,Females employee,%,50.4,48.8,47.5
45,,,Total injuries,No.,0,0,9
46,,Revenue\n11%,,,,,
47,,,Social and Relationship Capital,,,,
48,,,Community Services and Infrastructure,,,,
49,,,,,,,
50,,EBIT\n27%,Projects5,Rs.'000,"8,813","5,546","3,511"
51,,,1. \nKey performance indicators for the calend...,,,,

Table 79:

,0,1,2,3,4,5
0,,11%,,Revenue,,
1,,,,,,Social and Relationship Capital
2,,,,,,Community Services and Infrastructure
3,,,,,,
4,,,27%,EBIT,Projects5,"Rs.'000\n 8,813\n 5,546 \n 3,511"
5,,,,,1.,Key performance indicators for the calender year
6,,,,Capital Employed,,
7,5%,,,,2.,Revenue is inclusive of the Group's share of e...
8,,,,,3.,Excludes lease liabilities.
9,,,,,4.,"For equity accounted investees, capital employ..."
10,,,,,,
11,1%,,,Carbon Footprint,,these companies. This is inclusive of lease li...
12,,,,,5.,Only the contribution to John Keells Foundation.

Table 80:

,0,1,2
0,,of Sri Lanka decided to reduce the Standing De...,"GWP during CY2023, which amounted to Rs.152.80..."
1,,Rate (SDFR) and the Standing Lending Facility ...,[CY2022: Rs.135.37 billion].
2,,"basis points each to 8.50% and 9.50%, respecti...",
3,,"year under review, five downward revisions wer...",
4,,,Insurance
5,,reducing rates by a total of 700 basis points ...,
6,,,UA recorded a strong performance during CY2023...
7,y,The Statutory Reserve Ratio (SRR) applicable o...,
8,,,"in gross written premium (GWP), supported by a..."
9,,deposit liabilities of Licensed Commercial Ban...,
10,,,"new business premiums and renewal premiums, as..."
11,,"reduced by 200 basis points, from 4% to 2%, wi...",
12,,,Annualised new business premium (ANBP) increas...
13,,reserve maintenance period commencing on 16 Au...,
14,,,billion [CY2022: 6.4 billion]. Improvement in ...
15,y,The Insurance Regulatory Commission of Sri Lan...,"was driven by growth across agency, bancassura..."
16,,issued several directions to strengthen the re...,distribution channels.
17,,framework. These directives included enactment...,

Table 81:

,0,1,2
0,y,The Insurance Regulatory Commission of Sri Lan...,"was driven by growth across agency, bancassura..."
1,,issued several directions to strengthen the re...,distribution channels.
2,,framework. These directives included enactment...,
3,,"appointment, election or nomination of directo...",
4,,,GWP \nTotal \nGrowth
5,,to reporting framework and roles and responsib...,
6,,,CY2023\n(Rs.million)\n(%)
7,,principal officer.,
8,,,First year premium
9,y,The effective date for the implementation of t...,
10,,,"(regular new business premium)\n5,501\n18"
11,,"accounting standard on Insurance Contracts, wa...",
12,,,"Renewal premium\n12,625\n11"
13,,1 January 2026.,
14,,,Single premium\n60\n(68)
15,y,The corporate tax rate on financial services r...,
16,,,"Individual policies\n18,186\n12"
17,,whilst the standard value added tax (VAT) rate...,
18,,from 15% to 18% during the year under review.,

Table 82:

,0,1,2
0,External Environment and Operational Review,,
1,Macroeconomic Update,,
2,,,Macroeconomic Update - Insurance
3,y,Sri Lanka's financial services industry record...,
4,,,y\nThe insurance industry recorded total asset...
...,...,...,...
65,,,Net investment income increased by 45% [CY2022...
66,,"• Amendment, restructure and re-titling of St...","[CY2022: Rs.7.5 billion], supported by both th..."
67,,as trading participant rules and implementatio...,and higher interest rates that prevailed durin...
68,,resolution rules.,
69,,,"Despite the challenging market conditions, the..."

Table 83:

,0,1,2
0,Rs.2.80 billion [CY2022: Rs.2.30 billion]. Dis...,,
1,,,operational efficiencies with straight through...
2,"of Rs.3.38 billion, attributable to non-partic...",,
3,,,and one-day claim settlements at 94%. Enhanced...
4,"of unit-linked business, was transferred from ...",,
5,,were facilitated through:,
6,to the life shareholder fund in 2017/18 based ...,,
7,,y,digital end-to-end selling platform – digital ...
8,March 2018 issued by IRCSL. This continues to ...,,
9,,,enhanced with added features to further simpli...
10,to meeting governance requirements stipulated ...,,
11,,,and
12,only be released upon receiving approval from ...,,
13,,y,"upgraded 'FAME', a web-enabled sales force man..."
14,UA's SLFRS-17 steering committee continued to ...,,
15,,,facilitate digitally streamlined activity mana...
16,"to ensure strategic, tactical, and operational...",,
17,,,customer journey. 'FAME' provides crucial insi...
18,"implementation of SLFRS-17. During the year, t...",,
19,,,"performance, projecting business outcomes and ..."
20,committee examined the implementation roadmap ...,,
21,,,valuable tool for the sales force.
22,new effective date of 1 January 2026.,,

Table 84:

,0,1
0,Total assets stood at Rs.95.67 billion as at C...,"The 'Clicklife' self-servicing app, a turnkey ..."
1,"billion], recording a growth rate of 26%. UA's...","solution, continued its encouraging performanc..."
2,at Rs.83.42 billion [CY2022: Rs.64.46 billion]...,customers greater remote accessibility and add...
3,"CY2023. The life fund, which is backed by repu...",artificial intelligence (AI) powered calorie c...
4,"international credit rating of 'A+' and above,...",tracker were included and the loyalty programm...
5,Rs.64.13 billion [CY2022: Rs.54.52 billion].,"cover over 129 partner outlets. Moreover, a se..."
6,,"features were introduced during the year, such..."
7,Underwriting and net acquisition costs (net of...,"loan, requesting e-policy documents, and recei..."
8,to a 12% increase amounting to Rs.3.54 billion...,letters. This is in addition to the existing s...
9,through the implementation of a new incentive ...,"paying premiums, downloading policy-related do..."
10,"and profitability. Other operating, administra...","policy details, submitting claims, and policy ..."
11,growth was curtailed to 10% despite significan...,cashless hospitalisation and channelling physi...
12,of CY2023. This was enabled by the rigorous mo...,'Clicklife' a one-stop shop eco-system for ins...
13,and implementation of cost-saving and optimisa...,of UA's customers.
14,and benefits to policyholders recorded an 18% ...,
15,[CY2022: Rs.5.70 billion] mainly due to an inc...,"UA launched the product, 'Smart Wealth Builder..."
16,stemming largely from adverse macroeconomic co...,universal life product with a loyalty bonus at...
17,maturity payouts was in line with contractual ...,premium payment spread over five years.
18,The Life Insurance business recorded a life in...,
19,,UA also continued to digitise its processes wh...
20,Rs.2.80 billion [CY2022: Rs.2.30 billion]. Dis...,
21,,operational efficiencies with straight through...
22,"of Rs.3.38 billion, attributable to non-partic...",
23,,and one-day claim settlements at 94%. Enhanced...
24,"of unit-linked business, was transferred from ...",
25,,were facilitated through:
26,to the life shareholder fund in 2017/18 based ...,
27,,y\ndigital end-to-end selling platform – digit...
28,March 2018 issued by IRCSL. This continues to ...,
29,,enhanced with added features to further simpli...
30,to meeting governance requirements stipulated ...,
31,,and
32,only be released upon receiving approval from ...,
33,,"y\nupgraded 'FAME', a web-enabled sales force ..."
34,UA's SLFRS-17 steering committee continued to ...,
35,,facilitate digitally streamlined activity mana...
36,"to ensure strategic, tactical, and operational...",
37,,customer journey. 'FAME' provides crucial insi...
38,"implementation of SLFRS-17. During the year, t...",
39,,"performance, projecting business outcomes and ..."
40,committee examined the implementation roadmap ...,
41,,valuable tool for the sales force.
42,new effective date of 1 January 2026.,
43,,Further to the completion of the contractual t...
44,"During the year, UA proactively took steps to ...",
45,,"as Chief Executive Officer, Mr. Senath Jayatil..."
46,requirements of the Personal Data Protection A...,
47,,"new Chief Executive Officer, effective 1 Janua..."
48,"(PDPA), given the substantial volume of person...",
49,relation to insurance service provision. In th...,
50,"roadmap in CY2021, and preliminary measures we...",
51,"CY2022, including raising awareness on PDPA am...",
52,"Recognising the necessity for further action, ...",
53,assessment on PDPA compliance was initiated du...,
54,full compliance by the PDPA's effective date o...,

Table 85:

,0,1,2
0,FINANCIAL SERVICES,,
1,,,Total operating expenses of the Bank were reco...
2,,AWARDS,CY2023 in comparison to Rs.11.59 billion recor...
3,,,attributable to increases in personnel and oth...
4,y,Among the 'Top 100 Most Valuable Brands in Sri...,
5,,,"which increased by 24% and 25%, respectively. ..."
6,,'LMD Awards' in partnership with 'Brand Financ...,
7,,,increased during the year due to the Bank's co...
8,,consecutive year.,
9,,,compensation to employees and other operating ...
10,,,predominantly due to adjustments to electricit...
11,y,'Best Brand of the Year' award at 'Pinnacles S...,
12,,,"rise in operating expenses, the Bank maintaine..."
13,,,"of 31:69 in CY2023, which was a marginal incre..."
14,,,recorded in CY2022.
15,,Macroeconomic Update - Banking,
16,y,Total banking assets of the industry noted a 5...,The Bank's digital transactions increased by 1...
17,,CY2023 in comparison to the 15% growth recorde...,of total transactions [CY2022: 92%]. The Bank ...
18,,mainly due to the conversion of foreign curren...,customers with value added services and upgrad...
19,,loans and receivables and investments to Rupee...,services through the 'Nations Direct' mobile b...
20,,appreciation of the exchange rate. Net interes...,banking services. NTB also launched the 'Natio...
21,,5% contraction during the year.,"Platform' to accommodate end-to-end, unassiste..."
22,,,across multiple platforms. This is in line wit...
23,y,The banking sector stage 3 (credit-impaired) l...,
24,,,entire customer lifecycle management process. ...
25,,12.8% in CY2023 in comparison to 11.3% recorde...,
26,,,"fully fledged digital banking experience, cont..."
27,,,market leadership position through innovative ...
28,,,deepening relationships across the value chain.
29,Banking,,
30,NTB recorded a strong performance whilst maint...,,
31,,,The Group currently holds a 19.72% stake of vo...
32,"quality and liquidity, notwithstanding the vol...",,
33,,,Director of Bank Supervision of the CBSL had c...
34,conditions that prevailed particularly in the ...,,
35,,,pursuant to a decision by the Monetary Board o...
36,Bank's strategic focus during the recent years...,,
37,,,Keells Group was required to reduce its shareh...
38,"model, which involved de-risking selected asse...",,
39,,,on or before 31 December 2022. Until sharehold...
40,cost efficiencies and expanding digital bankin...,,
41,,,restriction on voting rights on any shares hel...
42,robust performance in CY2023.,,
43,,,applies to the Group. JKH has requested for an...
44,,,from the CBSL and is awaiting a formal respons...
45,"During the year, interest income increased by ...",,
46,driven by loan growth and increased returns on...,,
47,,,Mr. Gihan Cooray retired as a Director and Cha...
48,Government securities due to higher interest r...,,
49,,,having served the stipulated maximum nine-year...
50,the first half of CY2023. The Bank's loan port...,,
51,,,of the Bank in compliance with Direction No. 3...
52,"at 12%, versus a 5% contraction in industry lo...",,
53,,,Corporate Governance for Licensed Commercial B...
54,"manage funding costs, the Bank undertook proac...",,
55,,,CBSL. Ms. Sherin Cader took over as the Chairp...
56,limiting exposure to high interest-bearing tim...,,
57,,,"Directors, with effect from 1 May 2023."
58,which facilitated a swift downward re-pricing ...,,

Table 86:

,0,1,2
0,which facilitated a swift downward re-pricing ...,,
1,interest rates declined towards the latter hal...,,
2,even though interest expenses increased from R...,,
3,,,AWARDS
4,"to Rs.35.61 billion in CY2023, the Bank record...",,
5,(NII) growth of 19% to Rs.34.60 billion. The n...,y,'FriMi' was ranked amongst the top 3 'Most Lov...
6,increased from 7.0% in CY2022 to 7.7% in CY2023.,,FINTECH category by LMD Brand Finance for the ...
7,,,year.
8,The Bank maintained asset quality by adopting ...,,
9,,y,The Bank received the following awards at the ...
10,"to provisioning, resulting in a notable 46% lo...",,
11,,,of Information Technology Industry Sri Lanka (...
12,totalling to Rs.7.50 billion in CY2023 [CY2022...,,
13,,,Excellence Awards 2023:
14,strategy for preserving portfolio quality is c...,,
15,,,• Gold award – 'Nations Direct' mobile and on...
16,"a selective and data-driven lending approach, ...",,
17,,,platform in the Consumer Digital Engagement ca...
18,"through data analytics, personalised engagemen...",,

Table 87:

,0,1
0,,25% recorded in 2022/23. The expense ratio rem...
1,y\nThe settlement cycle for equity transaction...,
2,,"on-year given prudent expense management, cost..."
3,"from the current T+3 to T+2, effective May 2024.",
4,,optimisation initiatives implemented by the bu...
5,,y\nLife insurance contract liabilities includi...
6,Stock Broking,
7,,by 18% to Rs.69.50 billion in line with growth...
8,"JKSB, the stock broking arm of the Group, expe...",
9,,y\nUA recorded an annual life insurance surplu...
10,of operations on account of the lacklustre per...,
11,,2023/24 compared to Rs.2.30 billion in 2022/23.
12,Stock Exchange (CSE) during the year. Market p...,
13,"foreign participation, was adversely affected ...",Banking
14,uncertainty and limited participation by forei...,
15,,y\nNTB recorded a strong increase in profitabi...
16,,"of 12% and net interest income growth of 5%, s..."
17,"During the year, the business continued to foc...",
18,,management of its cost of funds.
19,processes and systems to improve alignment wit...,
20,Several initiatives were introduced in this re...,y\nThe Stage 3 loan ratio improved to 2.2% [20...
21,and cost management across both front and back...,Bank's focused risk management strategies and ...
22,"In order to enhance client engagements, the bu...",leading to a lower impairment charge on loans ...
23,conduct various investor fora via online platf...,
24,,y\nDespite the efficiency focused culture and ...
25,"media platforms on Facebook and LinkedIn, and ...",
26,,"established, the cost to income (CI) ratio inc..."
27,WhatsApp channel to disseminate information to...,
28,,"the previous year, primarily due to the slowdo..."
29,,growth on account of the reduction in market i...
30,Financial Performance Review,
31,,y\nProfitability also benefited from the absen...
32,As the key businesses within the industry grou...,Sri Lankan Government foreign securities given...
33,"and Insurance sectors, the ensuing discussion ...","adopted by NTB, relative to its peers, in the ..."
34,"on PBT and PAT, in order to capture the net ea...",
35,,Stock Broking
36,reflected in the financial statements of the G...,
37,,y\nThe stock market displayed subdued performa...

Table 88:

,0,1
0,,y\nUnderwriting and net acquisition costs incr...
1,Macroeconomic Update - Stock Broking,billion in line with growth in GWP.
2,y\nThe All Share Price Index (ASPI) of the CSE...,y\nThe Insurance sector witnessed an increase ...
3,"in CY2023 [CY2022: 31% decline], whilst the St...",which grew by 31% [2022/23: 57%]. This was dri...
4,Sri Lanka 20 (S&P SL20) index also noted a 16%...,in interest income from Government securities ...
...,...,...
60,"Insurance\n3,767\n2,948\n28",
61,"Banking\n4,056\n 2,710 \n50",
62,,"The recurring PBT of the industry group, post ..."
63,Stock Broking\n(29)\n15\n(293),tax provisions of equity accounted investees a...
64,"Total\n7,794\n5,673\n37",performance related initiatives stood at Rs.9....

Table 89:

,0,1,2
0,* Share of results of equity accounted investe...,,
1,,,Return on Capital Employed (ROCE) Analysis
2,Insurance,,x\nAsset \nx\nCapital \nROCE\n=\nEBIT
3,,,turnover\nstructure \n(%)\nmargin
4,y,The business witnessed a strong performance in...,
5,,,leverage\n(%)
6,,"premium (GWP), recording a growth of 16% durin...",
7,,review [2022/23: 6%]. The growth in GWP was pr...,
8,,,2023/24\n36.1\n27.9\n0.35\n3.71
9,,"12% increase in renewal premiums, a 23% increa...",
10,,,2022/23 \n33.4\n24.3\n0.35 \n3.97
11,,premiums and 50% growth in group life and surg...,
12,,,The increase in the ROCE and EBIT margin of th...
13,y,Claims and benefits increased by 11% to Rs.6.7...,
14,,,industry group was driven by an increase in re...
15,,billion] on account of expansion of the insura...,
16,,increase in surrender payouts due to macroecon...,
17,,,The capital structure leverage was impacted by...
18,,maturity payouts in accordance with the contra...,levels relative to higher average debt levels ...

Table 90:

,0,1,2
0,,upholding superior asset quality.,
1,,,"Assurance is ideally placed to capitalise on, ..."
2,y,Delivering customer-centric financial solution...,diversified portfolio of products and digital ...
3,,"approach throughout the customer lifecycle, ta...",
4,,customer needs.,
5,,,Sri Lanka has a relatively low level of insura...
6,y,"Utilising technology to spearhead innovations,...",
7,,,comparison to regional markets.
8,,"value offerings, and streamline operational pr...",
9,,,Life Insurance Penetration in Regional Markets
10,y,"Fostering an agile, dedicated, and forward-loo...",(%)
11,y,,

Table 91:

,0,1,2,3,4,5,6
0,Banking,Medium to Long-Term,,,,,
1,NTB will continue to proactively manage its op...,Insurance,,,,,
2,market opportunities as demand for credit rise...,,,,,,
3,,,Domestic conditions are envisaged to remain re...,,,,
4,managing risks. The Bank will focus its effort...,,,,,,
5,,,growth trajectory in the medium-term in tandem...,,,,
6,"sustainability by prioritising credit quality,...",,,,,,
7,,,revival of the economy. The significantly lowe...,,,,
8,"focused lending and financial stability, whils...",,,,,,
9,,,"penetration in comparison to regional peers, a...",,,,
10,"stringent cost management culture in place, in...",,,,,,
11,,,the increasing prevalence of non-communicable ...,,,,
12,,,to aid growth in the life insurance industry i...,,,,
13,y\nSeizing market opportunities through carefu...,,,,,,
14,,,growth potential for the industry will hinge o...,,,,
15,upholding a robust liquidity position.,,,,,,
16,,,"as raising awareness, developing a well-suited...",,,,
17,y\nPrioritising profitability by effectively m...,,,,,,
18,,,"solutions, and establishing a robust service p...",,,,
19,upholding superior asset quality.,,,,,,
20,,,"Assurance is ideally placed to capitalise on, ...",,,,
21,y\nDelivering customer-centric financial solut...,,diversified portfolio of products and digital ...,,,,
22,"approach throughout the customer lifecycle, ta...",,,,,,
23,customer needs.,,,,,,
24,,,Sri Lanka has a relatively low level of insura...,,,,
25,y\nUtilising technology to spearhead innovatio...,,,,,,
26,,,comparison to regional markets.,,,,
27,"value offerings, and streamline operational pr...",,,,,,
28,,,Life Insurance Penetration in Regional Markets,,,,
29,"y\nFostering an agile, dedicated, and forward-...",(%),,,,,
30,y\nIntegrating environmental and social factor...,,,,,,
31,,4.0,,,,,
32,implementation of a well-structured environmen...,,,,,,
33,,3.5,,,,,
34,governance (ESG) strategy.,3.0,,,,,
35,,2.5,,,,,
36,,2.0,,,,,
37,Potential headwinds stem from the overall econ...,,,,,,
38,,1.5,,,,,
39,that the banking industry is closely intertwin...,,,,,,
40,,1.0,,,,,
41,"economy. To this end, the Bank will closely mo...",0.5,,,,,
42,"the economic and political front, especially t...",0.0,,,,,
43,,Thailand\nMalaysia,India,Vietnam,Indonesia,Sri Lanka,Bangladesh
44,currency denominated debt restructure due in t...,,,,,,

Table 92:

,0,1,2,3,4,5
0,transform businesses to be relevant in the data-,,,,,
1,driven experience economy.,,,,,
2,y\nKey value stacks:,,,,,
3,• \nJKIT Strategy – experiencing a data-driven,,,,,
4,economy through design thinking.,,,,,
...,...,...,...,...,...,...
57,,Total injuries,No.,4,4,5
58,,Social and Relationship Capital,,,,
59,Contribution to the John Keells Group,,,,,
60,,Community Services and Infrastructure,,,,
61,Revenue\n2%,Projects4,Rs.'000,"65,893","133,627","34,298"

Table 93:

,0,1,2
0,,,Social and Relationship Capital
1,Contribution to the John Keells Group,,
2,,,Community Services and Infrastructure
3,Revenue,Projects4,"Rs.'000\n 65,893\n133,627\n34,298"
4,,1.,Revenue is inclusive of the Group's share of e...
5,,2.,Excludes lease liabilities.
6,EBIT\n14%,,
7,,3.,"For equity accounted investees, capital employ..."
8,,,these companies. This is inclusive of lease li...
9,,4.,Only the contribution to John Keells Foundation.
10,,,
11,Capital Employed\n14%,,

Table 94:

,0,1
0,"OTHER, INCLUDING INFORMATION TECHNOLOGY AND PL...",
1,External Environment and Operational Review,JKIT continued to focus on delivering innovati...
2,,by providing holistic and transformative solut...
3,Information Technology,
4,,the aforementioned five value stacks and packa...
...,...,...
82,,(excluding field latex and raw scrap) industri...
83,"continued to be well received, with the soluti...",
84,,1 January 2024. The industries were previously...
85,"Strategy', 'JKIT-Core', 'JKIT-Cloud', 'JKIT-Pl...",
86,yielding positive results throughout the finan...,

Table 95:

,0,1,2
0,"During the year under review, the Sri Lankan t...",Other,
1,"a series of formidable obstacles, characterise...",,
2,,In addition to the Information Technology and ...,
3,"costs and dwindling auction values, compounded...",,
4,,,"sectors, the industry group also entails the H..."
...,...,...,...
80,,,facilities obtained are in line with Group
81,business signed up with a solar developer to i...,,
82,,,norms.
83,installation at the warehouse on a revenue sha...,,
84,,John Keells,y A subset of sustainability which manages

Table 96:

,0,1,2
0,,operational decision-making.,
1,decline in the low grown region was also influ...,,
2,fertiliser application by smallholders. Despit...,,
3,,The Centre Functions of the Group entail:,
4,managed to sustain production volumes at level...,,
...,...,...,...
61,,,norms.
62,installation at the warehouse on a revenue sha...,,
63,,John Keells,y A subset of sustainability which manages
64,,Foundation,strategic CSR initiatives in line with the
65,,,Sustainability Development Goals.

Table 97:

,0,1,2,3,4,5
0,John Keells X*,y Group's corporate start-up accelerator,,,,
1,,,Financial Performance Review,,,
2,Legal and Secretarial,y\nProvides legal and secretarial support to all,,,,
3,,,Information Technology,,,
4,,Group companies.,,,,
5,New Business,y Development of new business opportunities,Rs.million,2023/24,2022/23,%
6,Development,for the Group.,,,,
7,,,Income Statement Indicators,,,
8,"Sustainability,",y Operationalisation of Group Sustainability,,,,
9,,,Revenue,"2,243","2,273",(1)
10,Enterprise Risk,Management Framework under which,,,,
11,,,EBITDA*,415,769,(46)
12,Management and,Group Companies carry out their specific,,,,
13,,,PBT,244,731,(67)
14,Group Initiatives,sustainability strategies and initiatives.,,,,
15,,,Balance Sheet Indicators,,,
16,,y Manages the Enterprise Risk Management,,,,
17,,,Debt**,78,158,(51)
18,,system for the value creation process.,,,,

Table 98:

,0,1,2,3,4,5,6
0,"OTHER, INCLUDING INFORMATION TECHNOLOGY AND PL...",,,,,,
1,,,,"In February 2024, HWIC exercised its option to...",,,
2,Centre Function/,Activities,,,,,
3,,,,"Debentures, with a face value of Rs.14.30 bill...",,,
4,Division,,,,,,
5,,,,"issued and listed 110,000,000 new ordinary sha...",,,
6,,,,The remaining outstanding Debentures post this...,,,
7,John Keells,y Generates scientific research ideas and,,,,,
8,,,,"to 98,125,000 Debentures with a face value of ...",,,
9,Research*,develop such ideas into Intellectual Property,,,,,
10,,,,remaining Debentures are eligible for conversi...,,,
11,,(IP) either to commence commercial,,,,,
12,,production or monetise the IPs itself to,,,,,
13,,,,,Refer Share Information section for a discussi...,,
14,,generate revenue.,,during the year - page 124,,,
15,John Keells X*,y Group's corporate start-up accelerator,,,,,
16,,,,Financial Performance Review,,,
17,Legal and Secretarial,y\nProvides legal and secretarial support to all,,,,,
18,,,,Information Technology,,,
19,,Group companies.,,,,,
20,New Business,y Development of new business opportunities,Rs.million,,2023/24,2022/23,%
21,Development,for the Group.,,,,,
22,,,,Income Statement Indicators,,,
23,"Sustainability,",y Operationalisation of Group Sustainability,,,,,
24,,,Revenue,,"2,243","2,273",(1)
25,Enterprise Risk,Management Framework under which,,,,,
26,,,EBITDA*,,415,769,(46)
27,Management and,Group Companies carry out their specific,,,,,
28,,,PBT,,244,731,(67)
29,Group Initiatives,sustainability strategies and initiatives.,,,,,
30,,,,Balance Sheet Indicators,,,
31,,y Manages the Enterprise Risk Management,,,,,
32,,,Debt**,,78,158,(51)
33,,system for the value creation process.,,,,,
34,,,,*EBITDA includes interest income but excludes ...,,,
35,,y Manages Group-wide synergetic initiatives.,,,,,
36,,,,"exchange gains and losses, to demonstrate the ...",,,
37,Social,"y\nSpearheads 'Plasticcycle', Group's social",performance of businesses.,,,,
38,Entrepreneurship**,entrepreneurship initiative.,**Excludes lease liabilities.,,,,

Table 99:

,0,1,2
0,y\nThe increase in debt of the Plantation Serv...,y,Lease liabilities for the year stood at Rs.116...
1,to an increase in bank overdrafts to manage wo...,,including lease liabilities amounted to Rs.95....
2,requirements.,,in comparison to Rs.90.11 billion in 2022/23.
3,Other,,The industry group recorded fair value gains o...
4,,,of Rs.72 million which stemmed from the Planta...
5,Rs.million\n2023/24\n2022/23\n%,,
6,,,the investments at the Holding Company [2022/2...
7,Income Statement Indicators,,
8,,,The recurring adjustments for 2023/24 entailed...
9,Revenue \n 57 \n ...,,
10,,,articulated in detail in the Financial Perform...
11,"EBITDA*\n (4,198) \n 4,847 \n(130)",,
12,,,"Similarly, the comparative year also entailed ..."
13,"PBT\n (7,862) \n 5,465 \n(244)",,which have been adjusted in order to ensure a ...
14,Balance Sheet Indicators,,
15,"Debt**\n 95,134 \n 90,109 \n6",,The recurring PBT of the industry group stood ...
16,,,a decrease against the previous year [2022/23:...
17,"Net Debt***\n36,572 \n23,295 \n57",,
18,*EBITDA includes interest income but excludes ...,,
19,,,Return on Capital Employed (ROCE) Analysis
20,"exchange gains and losses, to demonstrate the ...",,

Table 100:

    0                                                  1
0      account of planned utilisation for equity infu...
1   y  The PBT of the Holding Company was impacted by...
2                            finance expenses driven by:
3      • \nThe notional non-cash interest of Rs.3.02 ...
4      with market rates on the convertible debenture...
5      Rs.1.83 billion], in line with the accounting ...
6      significant difference between the market rate...
7                                           coupon rate.
8      •  An increase in Rupee borrowing costs due to...
9      debt in line with the planned funding strategy...
10     this juncture, to this end, total debt (includ...
11     decreased by Rs.5.14 billion to Rs.95.25 billion.

Table 101:

,0,1,2
0,,,Outsourcing\nImplementation\nServices
1,"Key risks, trends and opportunities relevant t...",,
2,,,Notes: Data shown is using current exchange ra...
3,,Russia-Ukraine war.,
4,Risks,,
5,,Most recent update: April 2024,
6,y\nMacroeconomic and political environment*,Source: Statista Market Insights,
7,• Changes in regulatory environment*,,
8,y\nSupply chain disruptions*,Immediate to Short-Term,
9,"y\nFinancial exposure*, in particular exchange...",y,The information technology and communication i...
10,y\nGlobal competitiveness*,,Sri Lanka is recognised as a thrust sector in ...
11,,,export strategy. The industry has a target of ...
12,y\nHuman resources and talent management*,,
13,,,billion to the digital economy and achieving U...
14,y\nEnvironment and health & safety*,,
15,,,revenue by CY2030.
16,y\nInformation technology*,,
17,,y,"In CY2023, ICT/BPM exports increased by 13.2% ..."
18,• Cybersecurity threats,,
19,,,reflecting the significant growth potential of...
20,• Commoditisation of services,,
21,,,growth momentum is envisaged to continue going...
22,• Disruptive innovation,,
23,,y,Digital literacy among the populace is ever-gr...
24,y\nReputation and brand image*,,
25,,,"increased digital adoption, creating ample opp..."
26,,,industry to leverage on.
27,*Identified as a risk across the Group through...,,
28,,y,The Group's IT businesses are well positioned ...
29,framework. Refer Key Risks section under Outlo...,,
30,,,strategic partnerships and capabilities to off...
31,,,"solutions, especially in the areas of cloud co..."
32,Trends and Opportunities,,"a service (SaaS) and automation, whilst concur..."
33,,,"potential opportunities for managed services, ..."
34,y\nTraction for cloud computing,,
35,,,offshoring.
36,y\nIncreased demand for emerging technologies ...,,
37,,y,The businesses will look to consolidate its po...
38,"intelligence (AI), blockchain, and the Interne...",,
39,,,markets and also strengthen its partnerships w...
40,y\nData analytics,,
41,y\nGrowing digital literacy in the country,y,Improving the contract management and operatio...
42,y\nHigh literacy rates in the country,,in overseas markets with the right onsite/offs...
43,,,disciplined change management process will be ...
44,y\nIncreased adoption of digital solutions and...,,
45,,,John Keells IT (JKIT) in the short-term.
46,businesses,,
47,"y\nOpportunities for managed services, outsour...",y,Attrition and sourcing talent remain a critica...
48,offshoring,,"Group's IT businesses, with the issue of human..."
49,y\nEnvisaged growth in the business process ma...,,'brain drain'. Every effort will be made to at...
50,industry,,offering opportunities for career development ...
51,y\nIncreased investment in technology infrastr...,,of roles offering diverse learning and exposure.

Table 102:

,0,1,2,3
0,,,,1.3 Key Announcements to the
1,1.2 Corporate Governance Highlights for 2023/24,,,
2,,,,Colombo Stock Exchange in
3,y,JKH was ranked first in the Transparency in Co...,,
4,,,,2023/24
...,...,...,...,...
87,,operates in.,,
88,,,,Debentures with a face value of Rs.12.76
89,y,The Group strengthened its internal policy uni...,,billion. The remaining Debentures are
90,,"the revised CSE Listing Rules, including revie...",,eligible for conversion till 12 August 2025.
91,,and ensuring improved alignment in terms of it...,,

Table 103:

,0,1
0,3.1.10 Time Dedicated by Non-Executive,The scoring and open comments are collated by ...
1,Directors,independent evaluation process. The results ar...
2,,effectiveness as well as areas that require ad...
3,The Board has dedicated adequate time for,
4,,"anonymity of the remarks, the open and frank d..."
5,the fulfilment of their duties as Directors of...,
6,,identifying themselves as the person making th...
7,Group. It is estimated that each Non-Executive,
8,,This process has led to an improvement in the ...
9,Directors devoted ~30 full time equivalent,
10,,"deliberations in the past, including the 2022/..."
11,days to the Group during the year. The general,
12,,around the completion of the large ticket inve...
13,time allocation is illustrated below.,
14,,the approach to proactively managing identific...
15,Time Commitment,"risks, business resilience and enterprise risk..."
16,(%),
17,15,3.1.12 Ensuring Independence and Managing Co...
18,,"As at 21 May 2024, the Board comprised of seve..."
19,,"Executive Directors, ensuring a strong element..."
20,50,The Group takes necessary steps to ensure that...
21,,"could have, a direct or indirect interest whic..."
22,,interests of the Group.
23,35,
24,,In order to avoid such potential conflicts or ...
25,,"interests, as illustrated below, at appointmen..."
26,Strategy and performance,
27,,"during the year, as required. Such potential c..."
28,Assurance and risk management,
29,,to ensure the integrity of the Board's indepen...
30,Other board matters,
31,,members hold Board or Board Committee membersh...
32,,"for inspection by shareholders, on request."
33,In addition to attending Board meetings,
34,"and Pre-Board meetings, the Directors have",

Table 104:

,0,1
0,summarised as follows. The Non-Executive Indep...,
1,below.,
2,Criteria for defining independence,Status of conformity of NEDs
3,1. Shareholding carrying not less than 10% of...,None of the individual EDs' or NED/IDs' shareh...
4,2. Director of another company*,None of the NED/IDs are Directors of another r...
5,3. \nIncome/non-cash benefit equivalent to 20%...,NED/ID income/cash benefits are less than 20% ...
6,excluding income/non-cash benefits received wh...,Director's annual income.
7,uniform basis to all non-executive Directors o...,
8,4. \nEmployment at JKH and/or material busines...,None of the NED/IDs are employed or have been ...
9,or in the three years immediately preceding ap...,
10,"5. Close family member is a Director, Chief E...",No family member of the EDs or NED/ IDs is a D...
11,Management Personnel,Key Management Personnel of a related party co...
12,6. Has served on the Board continuously for a...,"All NEDs, except Mr. A Cabraal and Mr. N Fonse..."
13,from the date of the first appointment,criteria for the year 2023/24. The Board deter...
14,,Mr. A Cabraal and Mr. N Fonseka did not satisf...
15,,"did, in the opinion of the Board, satisfy the ..."
16,,in terms of independence. Having also consider...
17,,the Board is of the view that Mr. A Cabraal an...
18,,Independent.
19,"7. \nIs employed, is a Director, has a materia...","None of the NED/IDs are employed, are Director..."
20,significant shareholding in other companies*. ...,business relationship or a significant shareho...
21,that have significant shareholding in JKH and/...,party company as defined.
22,connection with,

Table 105:

,0,1,2,3,4,5,6,7,8,9
0,* Retired from the Board with effect from 1 Ju...,,,,Granted \n(Adjusted),Immediately,To be vested,Granted \n(Adjusted),Immediately,To be vested
1,**Includes shareholding of spouse.,,,,shares,vesting,,shares,vesting,
2,Executive Directors',Number of Shares as at,,2024/25,"450,000","450,000",-,"430,000","430,000",-
3,Shareholding in Listed,31 March 2024,,2025/26,"450,000","337,500","112,500","430,000","322,500","107,500"
4,Group Companies*:,,,2026/27,"450,000","225,000","225,000","430,000","215,000","215,000"
5,,K Balendra,G Cooray,,,,,,,
6,,,,2027/28,"450,000","112,500","337,500","412,000","103,000","309,000"
7,Ceylon Cold Stores PLC,"802,320",-,2028/29,"360,000",-,"360,000","329,600",-,"329,600"
8,Asian Hotels and Properties PLC,-,"10,600",Total,"2,160,000","1,125,000","1,035,000","2,031,600","1,070,500","961,100"
9,Trans Asia Hotels PLC,-,"1,200",,,,,,,

Table 106:

,0,1
0,All other material and price sensitive informa...,lens and Internal and External Sustainability
1,to the CSE and such information is also releas...,Assurance and Standard Operating Procedures
2,"Shareholders may, at any time, direct question...",are in place to review the effectiveness of
3,provide comments and suggestions to Directors ...,the procedures embodied by the group on a
4,and comments should be addressed to the Compan...,needs basis.
5,The Group focuses on open communication and fa...,The Group has in place a sound sustainability
6,timeliness and relevance of the information pr...,"integration process, management framework"
7,communicated accurately and in a manner that w...,and sustainability organisational structure
8,,through which sustainable practices are
9,4.6.1.3 Annual General Meeting,embedded to the Group's operations.
10,Year of the AGM\nNumber of \nShareholding \n% ...,
11,,4.7.2 Sustainability Integration Process
12,attendees/ \n(No. of shares)\nshareholding,

Table 107:

,0,1
0,6 \nGOVERNANCE OUTLOOK AND,When looking at criteria for defining independ...
1,EMERGING CHALLENGES,that the intended outcome of achieving improve...
2,,be achieved through various checks and balance...
3,The need for maintaining a robust and,
4,,operating model of a corporate. These checks a...
...,...,...
70,,"related financial information, while IFRS S2 d..."
71,interest.,
72,,Sri Lanka issued the localised standard based ...
73,,The standards will be effective from 1 January...
74,,to assess alignment with the new standard to r...

Table 108:

,0,1,2,3
0,7.1,Statement of Compliance under Section 7.6 of t...,,
1,Disclosures,,,
2,MANDATORY PROVISIONS - FULLY COMPLIANT,,,
3,Rule,,Compliance,Reference (within the
4,,,Status,JKH Annual Report)
5,(i),Names of persons who were Directors of the Com...,Yes,Corporate Governance
6,,,,Commentary
7,(ii),Principal activities of the entity and its sub...,Yes,Management Discussion
8,,,,and Analysis
9,(iii),The names and the number of shares held by the...,Yes,
10,,voting shares and the percentage of such share...,,
11,(iv),"a) The float adjusted market capitalisation, p...",Yes,
12,,shareholders and under which option the Listed...,,
13,,Holding requirement,,
14,,,,Share Information
15,,The public holding percentage in respect of no...,Not Applicable,
16,,b) The public holding percentage in respect of...,Not Applicable,
17,(v),A statement of each Director's holding and CEO...,Yes,
18,,beginning and end of each financial year,,
19,(vi),Information pertaining to material foreseeable...,Yes,"Risk, Opportunities and"
20,,,,Internal Controls
21,(vii),Details of material issues pertaining to emplo...,Yes,Stakeholder Engagement
22,,,,and Determining
23,,,,Materiality
24,(viii),"Extents, locations, valuations and the number ...",Yes,
25,,,,Group Real Estate Portfolio
26,,investment properties,,
27,(ix),Number of shares representing the Entity's sta...,Yes,
28,(x),A distribution schedule of the number of holde...,Yes,
29,,,,Share Information
30,,percentage of their total holdings,,
31,(xi),Financial ratios and market price information,Yes,
32,(xii),Significant changes in the Company's or its su...,Yes,Notes to the Financial
33,,"of land, if the value differs substantially fr...",,Statements
34,(xiii),Details of funds raised through a public issue...,Yes,
35,,the year,,Share Information
36,(xiv),Information in respect of Employee Share Owner...,Yes,
37,(xv),Disclosures pertaining to Corporate Governance...,Yes,Corporate Governance
38,,Listing Rules,,Commentary/Note 44 of
39,(xvi),Related Party transactions exceeding 10% of th...,Yes,the Notes to the Financial
40,,"Entity as per audited financial statements, wh...",,Statements
41,(xvii) to,Disclosures pertaining to Foreign Currency den...,Not Applicable,
42,(xxi),Perpetual debt Securities. Infrastructure Bond...,,
43,,listed on the CSE,,

Table 109:

,0,1,2
0,,,
1,assess and monitor progress against key,,Environmental\nSocial\nGovernance
2,sustainability concerns.,,
3,,,Internal\nExternal
4,IMPROVEMENTS CARRIED OUT TO THE MATERIALITY,,
5,ASSESSMENT PROCESS,,y\nSuppliers/Vendors
6,,y,All mid-junior management
7,,,y\nCustomers
8,Double materiality: During the year under revi...,,level Employees
9,,,y\nInvestors
10,"implemented a double materiality process, whic...",y,100% of board and sector
11,,,y\nCommunity
12,"positive and negative impacts, as well as pote...",,management
13,,,y\nRegulators
14,"implications on the organisation, the environm...",,
15,including their human rights.,,Stakeholder
16,,,Engagement
17,To enhance the clarity of the Group's material...,,Study
18,identified in the previous years under overarc...,,
19,themes were consolidated. These themes will se...,,Results of assessment
20,"within the Group's ESG framework, encompassing...",,
21,"(E), Social (S), and Governance (G) considerat...",,

Table 110:

,0,1,2
0,,ANNUAL REPORT OF THE BOARD OF DIRECTORS,
1,CAPITAL EXPENDITURE,STATED CAPITAL,REVIEW OF THE PERFORMANCE OF THE
2,The Company’s and Group’s capital,Stated Capital as at 31 March 2024 of the,BOARD
3,"expenditure on property, plant and equipment","Company amounted to Rs. 90,602 Mn",The performance of the board has been
4,amounted to Rs. 23 Mn (2023 - Rs.102 Mn),"(2023 - Rs.73,188 Mn). The movement and","appraised through a formalised process,"
5,"and Rs. 35,773 Mn (2023 - Rs.7,074 Mn),",composition of the Stated Capital is disclosed,where each individual Director anonymously
6,"respectively, and all other related information",in the Statement of Changes in Equity and in,comments on the dynamics of the Board.
7,and movements have been disclosed in Note,Note 34.1 to the Financial Statements.,The process is described in the Corporate
8,22 to the Financial Statements.,,Governance Commentary section of the
9,,REVENUE RESERVES,Annual Report.
10,Additions of intangible assets of the Company,Revenue reserves as at 31 March 2024 for the,
11,and Group during the year amounted to Nil,"Company and Group amounted to Rs. 103,933",BOARD COMMITTEES
12,"(2023 - Nil) and Rs. 1,523 Mn (2023 - Rs.1,296","Mn (2023 - Rs.101,807 Mn) and Rs. 130,812",Information relating to members of the
13,"Mn), respectively, and all other related","Mn (2023 - Rs.121,743 Mn), respectively. The","Audit Committee, Human Resources and"
14,movements are disclosed in Note 25 to the,movement of the revenue reserve is disclosed,"Compensation Committee, Nominations"
15,Financial Statements.,in the Statement of Changes in Equity.,"Committee, Related Party Transactions Review"
16,,,Committee and Project Risk Assessment
17,"VALUATION OF LAND, BUILDINGS AND",SHARE INFORMATION,"Committee, including reports of each of the"
18,INVESTMENT PROPERTIES,The distribution and composition of,"committees, where applicable, and attendance"
19,All land and buildings owned by Group,shareholders and the information relating,of Directors for each of the committee
20,companies were revalued as at 31 December,"to earnings, dividends, net assets, market","meetings, are disclosed in the Corporate"
21,2023 and the carrying value amounted to,value per share and share trading is given,Governance Commentary section of the
22,"Rs. 113,313 Mn (2023 - Rs.110,716 Mn). All",in the Share Information section of the,Annual Report.
23,information related to revaluation is given in,"Annual Report. As additional disclosures, the",
24,Note 22.3 to the Financial Statements.,Company’s Board of Directors’ (including their,INTERESTS REGISTER AND INTERESTS IN
25,,"close family members) shareholdings, options",CONTRACTS
26,"Investment properties of business units, when",available under the employee share option,The Company has maintained an Interests
27,"significantly occupied by Group companies,","(ESOP) plans as at 31 March 2024, market",Register as contemplated by the Companies
28,"are classified as property, plant and equipment","capitalisation, public holding percentage and",Act No 7 of 2007.
29,in the consolidated financial statements in,number of public shareholders are given in,
30,compliance with LKAS 40.,the Share Information section of the Annual,This Annual Report also contains particulars
31,,Report.,of entries made in the Interests Registers of
32,The Group revalued all its investment,,subsidiaries which are public companies or
33,"properties as at 31 December 2023, and the",MAJOR SHAREHOLDERS,private companies that have not dispensed
34,"carrying value amounted to Rs.31,519 Mn",Details of the twenty largest shareholders,with the requirement to maintain an Interests
35,"(2023- Rs.33,029 Mn). All information related",of the Company and the percentages held,Register as permitted by Section 30 of the
36,to revaluation of the investment properties,by each of them are disclosed in the Share,Companies Act No 7 of 2007.
37,is provided in Note 24 to the Financial,Information section of the Annual Report.,
38,Statements.,,The Directors have all made a general
39,,EQUITABLE TREATMENT OF SHAREHOLDERS,disclosure relating to share dealings and
40,Details of the Group’s real estate portfolio as,The Company has at all times ensured that all,indemnities and remuneration to the Board
41,"at 31 March 2024, are disclosed in the Group",shareholders are treated equitably.,of Directors as permitted by Section 192 (2)
42,Real Estate Portfolio within the Supplementary,,of the Companies Act No 7 of 2007 and no
43,Information section of the Annual Report.,THE BOARD OF DIRECTORS,additional interests have been disclosed by
44,,The Board of Directors of the Company as at,any Director. The Interest Register is availab...
45,INVESTMENTS,31 March 2024 and their brief profiles are given,"the registered head office of the Company, in"
46,Detailed description of the long term,in the Corporate Governance section of the,keeping with the requirements of the section
47,"investments held as at the reporting date, is",Annual Report.,119 (1) (d) of the Companies Act No 7 of 2007.
48,"given in Notes 26, 27 and 28 to the Financial",,
49,Statements.,RETIREMENT AND RE-ELECTION OF,SHARE DEALINGS
50,,DIRECTORS,"Other than for the following entries, particulars"
51,,Retirement and Re-Election of Directors of the,of the Company interest register are disclosed
52,,Company as at 31 March 2024 are given in the,in the Share Information section of the Annual
53,,Proxy Form.,Report.

Table 111:

                                                    0
0   professional judgment, were of most significan...
1   Key audit matter\nHow our audit addressed the ...
2   Our audit procedures included the following ke...
3   •  Assessed the competence, capability and obj...
4   engaged by the Group.\ninclude land and buildi...
5   of land and buildings were determined by exter...
6   • \nRead the external valuer’s report and unde...
7                               engaged by the Group.
8   the valuation approaches taken by the valuer i...
9   each property.\nThis was a key audit matter du...
10  •  Assessed the reasonableness of significant ...
11  estimates made by the valuer such as per perch...
12  market rent per square foot, occupancy rates, ...
13  as relevant in assessing the fair value of eac...
14  • \nThe degree of assumptions, judgements and ...
15  We also assessed the adequacy of the disclosur...
16  the financial statements.\nbuildings using the...
17             depreciated replacement cost approach.
18  Key areas of significant judgments, estimates ...

Table 112:

,0,1
0,Key audit matter,How our audit addressed the key audit matter
1,Assessing the carrying value of capital work i...,Our audit procedures included the following ke...
2,"As disclosed in Note 22, capital work in progr...",• Obtained an understanding of the process fo...
3,"Property, Plant and Equipment amounting to Rs....",including the basis of judgments and assumptio...
4,represents 32% of total assets of the Group as...,to complete the projects.
5,This was a key audit matter due to the materia...,• \nPerformed test of expenditure and allocati...
6,balance which includes the ongoing constructio...,examination of management’s assessment as to w...
7,Waterfront Properties (Pvt) Ltd and the possib...,the recognition and measurement criteria set f...
8,cost escalations to complete the project due t...,of the Group.
9,conditions in the country.,
10,,• \nReviewed the project status reports and th...
11,,manager to identify the status of the project ...
12,,costs incurred as of reporting date.
13,,We also assessed the adequacy of the disclosur...

Table 113:

,0,1,2,3,4,5
0,In Rs.'000s,,GROUP,,COMPANY,
1,For the year ended 31 March,Note,2024,2023,2024,2023
2,Continuing operations,,,,,
3,Revenue from contracts with customers,,"262,338,375","260,687,372","2,916,390","2,543,712"
4,Revenue from insurance contracts,,"18,434,229","15,952,535",-,-
5,Total revenue,14,"280,772,604","276,639,907","2,916,390","2,543,712"
6,Cost of sales,,"(226,490,684)","(227,534,456)","(1,782,895)","(1,510,932)"
7,Gross profit,,"54,281,920","49,105,451","1,133,495","1,032,780"
8,Dividend income,15,-,-,"11,503,190","10,635,000"
9,Other operating income,16.1,"4,510,417","3,260,621","125,268","41,219"
10,Selling and distribution expenses,,"(10,062,663)","(8,266,060)",-,-
11,Administrative expenses,,"(25,172,004)","(21,583,579)","(2,233,541)","(1,742,998)"
12,Other operating expenses,16.2,"(8,188,312)","(9,825,773)","(86,595)","(748,154)"
13,Results from operating activities,,"15,369,358","12,690,660","10,441,817","9,217,847"
14,Finance cost,17,"(19,668,851)","(17,802,868)","(11,970,541)","(8,778,825)"
15,Finance income,17,"22,567,639","26,899,776","5,787,333","16,327,902"
16,Change in insurance contract liabilities,36.2,"(10,833,328)","(7,650,232)",-,-
17,Change in fair value of investment properties,24,"450,092","878,538",-,-
18,Share of results of equity accounted investees...,27.3,"10,129,014","7,573,543",-,-
19,Profit before tax,18,"18,013,924","22,589,417","4,258,609","16,766,924"
20,Tax expense,21.1,"(5,886,390)","(3,693,293)","(6,296)","(2,057,640)"
21,Profit for the year,,"12,127,534","18,896,124","4,252,313","14,709,284"
22,Attributable to:,,,,,
23,Equity holders of the parent,,"11,248,152","18,173,868",,
24,Non-controlling interests,,"879,382","722,256",,
25,,,"12,127,534","18,896,124",,
26,,,Rs.,Rs.,,
27,Earnings per share,,,,,
28,Basic,19.1,8.06,13.12,,
29,Diluted,19.2,8.04,13.12,,
30,Dividend per share,20,1.50,2.00,,

Table 114:

,0,1
0,9. \n BASIS OF CONSOLIDATION AND MATERIAL PARTLY,The Group re-assesses whether or not it contro...
1,OWNED SUBSIDIARIES,and circumstances indicate that there are chan...
2,Accounting policy,the three elements of control. Consolidation o...
3,Basis of consolidation,when the Group obtains control over the subsid...
4,The consolidated financial statements comprise...,the Group loses control of the subsidiary. Ass...
...,...,...
58,,of comprehensive income and as a component of ...
59,Tea Smallholder Factories PLC\n37.62,"consolidated statement of financial position, ..."
60,,attributable to the shareholders of the parent.
61,,The Consolidated Statement of Cash Flow includ...
62,,the Company and its subsidiaries.

Table 115:

,0,1
0,Names of material partly-owned subsidiaries an...,10. \nBUSINESS COMBINATIONS AND ACQUISITIONS O...
1,owned by non-controlling interest:,CONTROLLING INTERESTS
2,"Considering the Group balances, none of the in...",Accounting policy
3,subsidiaries have material non-controlling int...,Business combinations & goodwill
4,information has been presented on the aggregat...,Business combinations are accounted for using ...
5,"entities namely, the Leisure, Consumer Foods a...",of accounting. The Group measures goodwill at ...
6,on the nature and risks of the products and se...,the fair value of the consideration transferre...
7,,amount of any non-controlling interests in the...
8,John Keells Holdings has material partly owned...,recognised amount (generally fair value) of th...
9,"Foods, Retail and Leisure sectors.","acquired and liabilities assumed, all measured..."
10,"In Consumer Foods Sector, Ceylon Cold Stores P...",When the fair value of the consideration trans...
11,PLC and The Colombo Ice Company (Pvt) Ltd has ...,recognised amount of any non-controlling inter...
12,owned by non-controlling interest ranging from...,lower than the fair value of net assets acquir...
13,31 March 2024 (2023 - 11.37% - 18.64 %).,immediately in the income statement. The Group...
14,,transaction-by-transaction basis whether to me...
15,"In Retail Sector, JayKay Marketing Services (P...","interests at fair value, or at their proportio..."
16,International (Pvt) Ltd both have 18.64% effec...,"amount of the identifiable net assets, at the ..."
17,non-controlling interest as at 31 March 2024 (...,"costs, other than those associated with the is..."
18,,"securities, that the Group incurs in connectio..."
19,"Under Leisure Sector, following companies have...",combination are expensed as incurred. When the...
20,owned subsidiaries with effective holding perc...,"business, it assesses the financial assets and..."
21,controlling interest ranged from 1.65% - 24.67...,appropriate classification and designation in ...
22,,"contractual terms, economic circumstances and ..."
23,The Leisure Sector subsidiaries include Ahunga...,at the acquisition date. If the business combi...
24,"Ltd, Asian Hotels and Properties PLC, Beruwala...",the acquisition date fair value of the acquire...
25,"Ltd, Ceylon Holiday Resorts Ltd, Cinnamon Holi...",interest in the acquiree is remeasured to fair...
26,"World Investments (Pte) Ltd, Habarana Lodge Lt...",through profit or loss. Any contingent conside...
27,"Hikkaduwa Holiday Resorts (Pvt) Ltd, Internati...",by the acquirer will be recognised at fair val...
28,"Ltd, John Keells Hotels PLC, John Keells Maldi...","Contingent consideration, resulting from busin..."
29,"Walk Inn Ltd, Nuwara Eliya Holiday Resorts (Pv...",valued at fair value at the acquisition date. ...
30,"Company Ltd, Resort Hotels Ltd, Tranquility (P...",classified as equity is not remeasured and its...
31,"PLC, Travel Club (Pte) Ltd, Trinco Holiday Res...",accounted for within equity. Contingent consid...
32,"Ltd, Walkers Tours Ltd, Wirawila Walk Inn Ltd ...",asset or liability that is a financial instrum...
33,,"SLFRS 9 Financial Instruments, is measured at ..."
34,Please refer Note 26 for the individual compan...,in fair value recognised in the Income Stateme...
35,,SLFRS 9.
36,"Accounting judgements,estimates and assumptions",
37,Consolidation of entities in which the Group h...,Other contingent consideration that is not wit...
38,majority of voting right (de facto control).,measured at fair value at each reporting date ...
39,,recognised in profit or loss.
40,The Group considers that it controls some subs...,
41,owns less than 50% of the voting rights. This ...,"After initial recognition, goodwill is measure..."
42,single largest shareholder of those subsidiari...,accumulated impairment losses. Goodwill is rev...
43,remaining equity shares in those subsidiaries ...,annually or more frequently if events or chang...
44,"other shareholders, and there is no history of...",indicate that the carrying value may be impaired.
45,collaborating to exercise their votes collecti...,

Table 116:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,"collateral, if available). Following table sho...",,,,,,,,,,,,,,,
1,In Rs.'000s,,,,,,,,,,,,,,,
2,As at 31 March,,,,,,2024,,,,,,2023,,,
3,,Notes,Non-,Cash in,Trade,Short term,Amounts,Total,,Non-,Cash in,Trade,Short term,Amounts,Total,
4,,,current,hand and,and other,investments,due from,,f,current,hand and,and other,investments,due from,,f
5,,,financial,at bank,receivables,,related,,allocation,financial,at bank,receivables,,related,,allocation
6,,,assets,,,,parties,,,assets,,,,parties,,
7,Group,,,,,,,,,,,,,,,
8,Government securities,11.1.2,"59,500,492",-,-,"8,404,134",-,"67,904,626",35%,"45,906,390",-,-,"7,521,144",-,"53,427,534",28%
9,Corporate debt securities,11.1.3,"7,458,459",-,-,"3,752,741",-,"11,211,200",6%,"9,185,289",-,-,"1,653,689",-,"10,838,978",6%
10,Deposits with bank,11.1.4,"230,495",-,-,"62,907,725",-,"63,138,220",33%,"803,775",-,-,"69,453,925",-,"70,257,700",37%
11,Loans to executives,11.1.5,"1,491,012",-,"415,865",-,-,"1,906,877",1%,"1,260,602",-,"356,266",-,-,"1,616,868",1%
12,Loans to life policyholders,11.1.6,"2,310,660",-,"114,677",-,-,"2,425,337",1%,"2,199,675",-,-,-,-,"2,199,675",1%
13,Interest rate swap,11.1.7,"3,294,625",-,-,-,-,"3,294,625",2%,"4,215,838",-,-,-,-,"4,215,838",2%
14,Trade and other receivables,11.1.8,-,-,"26,652,427",-,-,"26,652,427",14%,-,-,"19,940,932",-,-,"19,940,932",11%
15,Reinsurance receivables,11.1.9,"116,444",-,"313,050",-,-,"429,494",0%,-,-,"590,215",-,-,"590,215",0%
16,Assets backed securities,11.1.10,-,-,-,-,-,-,-,"314,276",-,-,-,-,"314,276",0%
17,Premium receivable,11.1.11,-,-,"881,186",-,-,"881,186",0%,-,-,"620,665",-,-,"620,665",0%
18,Amounts due from related parties,11.1.12,-,-,-,-,"674,179","674,179",0%,-,-,-,-,"317,700","317,700",0%
19,Cash in hand and at bank,11.1.13,-,"15,417,894",-,-,-,"15,417,894",8%,-,"25,092,977",-,-,-,"25,092,977",14%
20,Total credit risk exposure,,"74,402,187","15,417,894","28,377,205","75,064,600","674,179","193,936,065",100%,"63,885,845","25,092,977","21,508,078","78,628,758","317,700","189,433,358",100%
21,Financial assets at fair value through P&L,11.3.3.1,-,-,-,"4,966,042",-,,,-,-,-,"3,593,064",-,,
22,Financial assets at fair value through OCI,11.3.3.2,"79,629",-,-,-,-,,,"71,206",-,-,-,-,,
23,Total equity risk exposure,,"79,629",-,-,"4,966,042",-,,,"71,206",-,-,"3,593,064",-,,
24,Total,,"74,481,816","15,417,894","28,377,205","80,030,642","674,179",,,"63,957,051","25,092,977","21,508,078","82,221,822","317,700",,
25,Company,,,,,,,,,,,,,,,
26,Deposits with bank,11.1.4,-,-,-,"57,805,464",-,"57,805,464",91%,-,-,-,"57,473,253",-,"57,473,253",80%
27,Loans to executives,11.1.5,"173,401",-,"20,802",-,-,"194,203",0%,"151,987",-,"20,766",-,-,"172,753",0%
28,Interest rate swap,11.1.7,"3,294,625",-,-,-,-,"3,294,625",5%,"4,215,838",-,-,-,-,"4,215,838",6%
29,Trade and other receivables,11.1.8,-,-,"439,880",-,-,"439,880",1%,-,-,"186,967",-,-,"186,967",0%
30,Amounts due from related parties,11.1.12,-,-,-,-,"1,290,846","1,290,846",2%,-,-,-,-,"1,177,616","1,177,616",2%
31,Cash in hand and at bank,11.1.13,-,"556,930",-,-,-,"556,930",1%,-,"8,232,006",-,-,-,"8,232,006",12%
32,Total credit risk exposure,,"3,468,026","556,930","460,682","57,805,464","1,290,846","63,581,948",100%,"4,367,825","8,232,006","207,733","57,473,253","1,177,616","71,458,433",100%
33,Financial assets at fair value through OCI,11.3.3.2,"43,666",-,-,-,-,,,"37,158",-,-,-,-,,
34,Total equity risk exposure,,"43,666",-,-,-,-,,,"37,158",-,-,-,-,,
35,Total,,"3,511,692","556,930","460,682","57,805,464","1,290,846",,,"4,404,983","8,232,006","207,733","57,473,253","1,177,616",,

Table 117:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,"collateral, if available). Following table sho...",,,,,,,,,,,,,,,
1,In Rs.'000s,,,,,,,,,,,,,,,
2,As at 31 March,,,,,,2024,,,,,,2023,,,
3,,Notes,Non-,Cash in,Trade,Short term,Amounts,Total,,Non-,Cash in,Trade,Short term,Amounts,Total,
4,,,current,hand and,and other,investments,due from,,f,current,hand and,and other,investments,due from,,f
5,,,financial,at bank,receivables,,related,,allocation,financial,at bank,receivables,,related,,allocation
6,,,assets,,,,parties,,,assets,,,,parties,,
7,Group,,,,,,,,,,,,,,,
8,Government securities,11.1.2,"59,500,492",-,-,"8,404,134",-,"67,904,626",35%,"45,906,390",-,-,"7,521,144",-,"53,427,534",28%
9,Corporate debt securities,11.1.3,"7,458,459",-,-,"3,752,741",-,"11,211,200",6%,"9,185,289",-,-,"1,653,689",-,"10,838,978",6%
10,Deposits with bank,11.1.4,"230,495",-,-,"62,907,725",-,"63,138,220",33%,"803,775",-,-,"69,453,925",-,"70,257,700",37%
11,Loans to executives,11.1.5,"1,491,012",-,"415,865",-,-,"1,906,877",1%,"1,260,602",-,"356,266",-,-,"1,616,868",1%
12,Loans to life policyholders,11.1.6,"2,310,660",-,"114,677",-,-,"2,425,337",1%,"2,199,675",-,-,-,-,"2,199,675",1%
13,Interest rate swap,11.1.7,"3,294,625",-,-,-,-,"3,294,625",2%,"4,215,838",-,-,-,-,"4,215,838",2%
14,Trade and other receivables,11.1.8,-,-,"26,652,427",-,-,"26,652,427",14%,-,-,"19,940,932",-,-,"19,940,932",11%
15,Reinsurance receivables,11.1.9,"116,444",-,"313,050",-,-,"429,494",0%,-,-,"590,215",-,-,"590,215",0%
16,Assets backed securities,11.1.10,-,-,-,-,-,-,-,"314,276",-,-,-,-,"314,276",0%
17,Premium receivable,11.1.11,-,-,"881,186",-,-,"881,186",0%,-,-,"620,665",-,-,"620,665",0%
18,Amounts due from related parties,11.1.12,-,-,-,-,"674,179","674,179",0%,-,-,-,-,"317,700","317,700",0%
19,Cash in hand and at bank,11.1.13,-,"15,417,894",-,-,-,"15,417,894",8%,-,"25,092,977",-,-,-,"25,092,977",14%
20,Total credit risk exposure,,"74,402,187","15,417,894","28,377,205","75,064,600","674,179","193,936,065",100%,"63,885,845","25,092,977","21,508,078","78,628,758","317,700","189,433,358",100%
21,Financial assets at fair value through P&L,11.3.3.1,-,-,-,"4,966,042",-,,,-,-,-,"3,593,064",-,,
22,Financial assets at fair value through OCI,11.3.3.2,"79,629",-,-,-,-,,,"71,206",-,-,-,-,,
23,Total equity risk exposure,,"79,629",-,-,"4,966,042",-,,,"71,206",-,-,"3,593,064",-,,
24,Total,,"74,481,816","15,417,894","28,377,205","80,030,642","674,179",,,"63,957,051","25,092,977","21,508,078","82,221,822","317,700",,
25,Company,,,,,,,,,,,,,,,
26,Deposits with bank,11.1.4,-,-,-,"57,805,464",-,"57,805,464",91%,-,-,-,"57,473,253",-,"57,473,253",80%
27,Loans to executives,11.1.5,"173,401",-,"20,802",-,-,"194,203",0%,"151,987",-,"20,766",-,-,"172,753",0%
28,Interest rate swap,11.1.7,"3,294,625",-,-,-,-,"3,294,625",5%,"4,215,838",-,-,-,-,"4,215,838",6%
29,Trade and other receivables,11.1.8,-,-,"439,880",-,-,"439,880",1%,-,-,"186,967",-,-,"186,967",0%
30,Amounts due from related parties,11.1.12,-,-,-,-,"1,290,846","1,290,846",2%,-,-,-,-,"1,177,616","1,177,616",2%
31,Cash in hand and at bank,11.1.13,-,"556,930",-,-,-,"556,930",1%,-,"8,232,006",-,-,-,"8,232,006",12%
32,Total credit risk exposure,,"3,468,026","556,930","460,682","57,805,464","1,290,846","63,581,948",100%,"4,367,825","8,232,006","207,733","57,473,253","1,177,616","71,458,433",100%
33,Financial assets at fair value through OCI,11.3.3.2,"43,666",-,-,-,-,,,"37,158",-,-,-,-,,
34,Total equity risk exposure,,"43,666",-,-,-,-,,,"37,158",-,-,-,-,,
35,Total,,"3,511,692","556,930","460,682","57,805,464","1,290,846",,,"4,404,983","8,232,006","207,733","57,473,253","1,177,616",,

Table 118:

                 0      1            2     3            4     5
0                   GROUP
1   As at 31 March                2024               2023
2    Fitch ratings         In Rs.’000s     %  In Rs.’000s     %
3              AAA             101,177    0%            -     -
4               A+             628,247    6%      607,585    6%
5                A           1,435,654   12%    1,568,959   14%
6               A-             867,523    8%      829,469    8%
7             BBB+           2,640,002   24%    2,596,193   24%
8              BBB           3,775,936   34%    3,471,458   32%
9             BBB-           1,445,202   13%    1,549,735   14%
10             BB+             101,857    1%            -     -
11              CC             215,602    2%      215,579    2%
12           Total          11,211,200  100%   10,838,978  100%

Table 119:

,0,1,2,3,4,5,6,7,8
0,,,GROUP,,,,,COMPANY,
1,As at 31 March,,,,,,,,
2,,2024,,2023,,2024,,2023,
3,Fitch ratings,,,,,,,,
4,,In Rs.’000s,%,In Rs.’000s,%,In Rs.’000s,%,In Rs.’000s,%
5,AAA,"1,112,648",2%,-,-,-,-,-,-
6,AA-,"15,405",0%,"2,988,505",4%,-,-,-,-
7,A,"41,335,052",65%,"44,491,946",63%,"37,198,346",64%,"35,629,545",62%
8,A-,"20,675,115",33%,"22,777,249",33%,"20,607,118",36%,"21,843,708",38%
9,Total,"63,138,220",100%,"70,257,700",100%,"57,805,464",100%,"57,473,253",100%

Table 120:

,0,1,2,3,4
0,11. \n FINANCIAL RISK MANAGEMENT OBJECTIVES A...,,,,
1,11.3.3.1 Financial assets at fair value throug...,,,,
2,,,GROUP,,
3,As at 31 March,2024,,2023,
4,,Rs.’000s,%,Rs.’000s,%
5,Application Software,-,-,"49,812",1%
6,Banks,"1,528,273",31%,"396,380",11%
7,Capital Goods,"1,555,137",31%,"906,535",25%
8,Consumer Durables and Apparel,"387,599",8%,"398,982",11%
9,Consumer Services,"45,360",1%,"194,454",5%
10,Diversified Financials,"39,738",1%,-,-
11,Energy,-,-,"315,951",10%
12,Food and Staples Retailing,-,-,"13,018",0%
13,Food Beverage and Tobacco,"645,106",13%,"440,292",12%
14,Investment Banking and Brokerage,-,-,"36,709",1%
15,Materials,"561,046",11%,"641,028",18%
16,Real Estate,-,-,"16,063",0%
17,Telecommunication Services,"203,783",4%,"183,840",6%
18,,"4,966,042",100%,"3,593,064",100%

Table 121:

,0,1,2,3
0,,Company's profit before tax and equity due to ...,,
1,,,GROUP,
2,For the year ended 31 March,Change in year-end,Effect on profit,Effect on equity
3,,market price index,before tax Rs.‘000s,Rs.‘000s
4,2024,+21%,"1,042,869",-
5,,-21%,"(1,042,869)",-
6,2023,+10%,"359,306",-
7,,-10%,"(359,306)",-

Table 122:

,0,1
0,In Rs.'000s,GROUP\nCOMPANY
1,For the year ended 31 March,Note\n2024\n2023\n2024\n2023
2,Timing of revenue recognition,
3,Goods transferred at a point in time,"207,061,370 \n 213,110,409 \n - \n -"
4,Services transferred over time,"55,277,005 \n 47,576,963 \n 2,916,390 \n 2,543..."
5,Total revenue from contracts with customers,"14.1.1\n 262,338,375 \n 260,687,372 \n 2,916,3..."
6,Revenue from insurance contracts,"14.1.2\n 18,434,229 \n 15,952,535 \n - \n -"
7,Total revenue,"280,772,604 \n 276,639,907 \n 2,916,390 \n 2,5..."
8,For the better understanding of the Industry s...,
9,14.3 \nReconciliation of revenue,Contract liabilities
10,Reconciliation between Revenue from contracts ...,Contract liabilities are the Group's obligatio...
11,and revenue for each reportable segment has be...,services to a customer for which the Group has...
12,operating segment information section.,(or the amount is due) from the customer. Cont...
13,,long-term advances received to deliver goods a...
14,14.4 Contract balances,advances received to render certain services a...
15,Contract assets,"allocated to unexpired service warranties, and..."
16,Contract assets are the Group’s right to consi...,redeemed.
17,goods or services that the Group has transferr...,
18,rights that are conditional on some criteria o...,
19,"time. Upon satisfaction of the conditions, the...",
20,contract assets are reclassified to trade rece...,

Table 123:

,0,1
0,Dividend income from investments in subsidiari...,"11,503,190\n 10,635,000"
1,16. \nOTHER OPERATING INCOME AND OTHER OPERAT...,Gains and losses arising from activities incid...
2,Accounting policy,generating activities and those arising from a...
3,Gains and losses,"transactions, which are not material are aggre..."
4,Net gains and losses of a revenue nature arisi...,presented on a net basis.
5,"property, plant and equipment and other non-cu...",
6,,Any losses arising from guaranteed rentals are...
7,"investments in subsidiaries, joint ventures an...",
8,,year of incurring the same. A provision is rec...
9,"in the income statement, after deducting from ...",
10,,indicates a loss.
11,the carrying amount of such assets and the rel...,
12,,Other income and expenses
13,,Other income and expenses are recognised on an...

Table 124:

                                  0          1          2        3        4
0   16.2   Other operating expenses
1                       In Rs.'000s      GROUP             COMPANY
2       For the year ended 31 March       2024       2023     2024     2023
3  Provisions and impairment losses    638,900  1,106,367        -  684,451
4             Heat, light and power  2,959,811  2,479,316        -        -
5                     Exchange loss          -  2,829,548        -        -
6                   Other overheads  4,589,601  3,410,542   86,595   63,703
7                                    8,188,312  9,825,773   86,595  748,154

Table 125:

,0,1
0,NOTES TO THE FINANCIAL STATEMENTS,
1,19. \nEARNINGS PER SHARE,parent (after adjusting for outstanding share ...
2,Accounting policy,average number of ordinary shares outstanding ...
3,Basic EPS is calculated by dividing the profit...,the weighted average number of ordinary shares...
4,ordinary equity holders of the parent by the w...,on conversion of all the dilutive potential or...
5,of ordinary shares outstanding during the year...,shares.
6,by dividing the profit attributable to ordinar...,
7,19.1 \nBasic earnings per share,
8,In Rs.'000s,GROUP
9,For the year ended 31 March,Note\n2024\n2023
10,Profit attributable to equity holders of the p...,"11,248,152 \n 18,173,868"
11,Weighted average number of ordinary shares,"19.3\n 1,395,945 \n 1,384,917"
12,Basic earnings per share,8.06\n 13.12
13,19.2 Diluted earnings per share,
14,Profit attributable to equity holders of the p...,"11,248,152 \n 18,173,868"
15,Adjusted weighted average number of ordinary s...,"19.3\n 1,399,003 \n 1,384,948"
16,Diluted earnings per share,8.04\n 13.12
17,19.3 Amount used as denominator,
18,In Rs.'000s,GROUP

Table 126:

,0,1,2,3
0,,NOTES TO THE FINANCIAL STATEMENTS,,
1,21.,TAXES (CONTD.),,
2,,21.10 Income tax rates of off-shore subsidiaries,,
3,,Country of incorporation,Company,Rate
4,India,,John Keells Foods India (Pvt) Ltd,25%
5,Mauritius,,John Keells BPO International (Pvt) Ltd,15%
6,,,John Keells BPO Holdings (Pvt) Ltd,15%
7,Republic of Maldives,,Fantasea World Investments (Pte) Ltd,15%
8,,,Travel Club (Pte) Ltd,15%
9,,,Tranqulity (Pte) Ltd,15%
10,,,John Keells Maldivian Resorts (Pte) Ltd,15%
11,,,Mack Air Services Maldives (Pte) Ltd,15%
12,Singapore,,John Keells Singapore (Pte) Ltd,17% (Max)

Table 127:

                                                    0
0           Mack Air Services Maldives (Pte) Ltd\n15%
1   Singapore\nJohn Keells Singapore (Pte) Ltd\n17...
2   22. \nPROPERTY, PLANT AND EQUIPMENT \nAccumula...
3   Accounting policy \nagainst the gross carrying...
4   Basis of recognition\nis restated to the reval...
5   Property, plant and equipment are recognised i...
6   economic benefits associated with the asset wi...
7   the cost of the asset can be reliably measured...
8   value on the date of revaluation. The Group ha...
9   Basis of measurement\nrevaluing assets by prof...
10  Property, plant and equipment except for land ...
11  at cost less accumulated depreciation and any ...
12  loss. Such cost includes the cost of replacing...
13  plant and equipment and borrowing costs for lo...
14  projects if the recognition criteria are met. ...
15  plant and equipment are required to be replace...
16  derecognises the replaced part, and recognises...
17  own associated useful life and depreciation. L...
18  inspection is performed, its cost is recognise...
19  the plant and equipment as a replacement if th...
20  satisfied. All other repair and maintenance co...
21  income statement as incurred.\nDepreciation is...
22  valuation of all property, plant and equipment...
23  Land and buildings are measured at fair value ...
24  depreciation on buildings and impairment charg...
25                           date of the revaluation.
26  The estimated useful life of assets is as foll...
27  The carrying values of property, plant and equ...
28  impairment when events or changes in circumsta...
29                                      Assets\nYears
30             carrying value may not be recoverable.
31                  Buildings (other than hotels)\n50
32  Any revaluation surplus is recognised in other...
33                          Hotel buildings\nup to 70
34  and accumulated in equity under the revaluatio...
35                       Plant and machinery\n10 – 25
36  the extent that it reverses a revaluation decr...
37                                   Equipment\n2– 15
38  previously recognised in the income statement,...
39  Furniture and fittings\n2– 15\nincrease is rec...
40  recognised in the income statement, except to ...
41                             Motor vehicles\n4 – 10
42  an existing surplus on the same asset recognis...
43                          Returnable containers\n10
44                                           reserve.
45                                    Vessels \n10-25
46                                        Other\n3-20

Table 128:

,0,1,2,3,4,5,6,7
0,,Surveyor,valuation,,,,,
1,,,,per perch,square foot,,discount,to fair
2,,,,,,rate,,value
3,Land and Building,,,,,,,
4,Asian Hotels & Properties PLC,P B Kalugalagedara,CMA,"Rs. 18,000,000 -","Rs. 3,500 - Rs. 16,000",,-,Positive
5,,,,"Rs. 21,000,000",,,,
6,Beruwala Holiday Resorts (Pvt ) Ltd,-do-,CMA,"Rs. 1,200,000 -","Rs. 2,000 - Rs. 8,200",,-,Positive
7,,,,"Rs. 1,600,000",,,,
8,Ceylon Cold Stores PLC,-do-,CMA,"Rs. 275,000 -","Rs. 500 - Rs. 5,000",,-,Positive
9,,,,"Rs. 310,000",,,,
10,Ceylon Holiday Resorts Ltd,-do-,CMA,"Rs. 250,000 -","Rs. 2,000 - Rs. 4,000",,-,Positive
11,,,,"Rs. 1,400,000",,,,
12,Hikkaduwa Holiday Resort (Pvt) Ltd,-do-,CMA,"Rs. 1,200,000","Rs. 1,750 - Rs. 3,600",,-,Positive
13,Kandy Walk Inn Ltd,S Fernando,CMA,"Rs. 15,000 -","Rs. 1,500 - Rs. 9,500",,-,Positive
14,,,,"Rs. 1,500,000",,,,
15,Keells Food Products PLC,P B Kalugalagedara,CMA,"Rs. 70,000 -","Rs. 400 - Rs. 3,500",,-,Positive
16,,,,"Rs. 725,000",,,,
17,Keells Realtors Ltd,-do-,CMA,"Rs. 2,000,000","Rs. 500 - Rs. 1,500",,-,Positive
18,Mackinnons Keells Ltd,-do-,CMA,"Rs. 11,000,000","Rs. 1,850",,-,Positive
19,Tea Smallholder Factories PLC,K.T.D. Tissera,CMA,"Rs. 5,000 -","Rs. 500 - Rs. 3,000",,-,Positive
20,,,,"Rs. 43,750",,,,
21,Trinco Holiday Resort (Pvt) Ltd,P B Kalugalagedara,CMA,"Rs. 400,000 -","Rs. 1,000 - Rs. 8,750",,-,Positive
22,,,,"Rs. 600,000",,,,
23,Union Assurance PLC,-do-,CMA,"Rs. 9,000,000 -","Rs. 17,000 - Rs. 22,000",,-,Positive
24,,,,"Rs. 21,000,000",,,,
25,Vauxhall Land Developments (Pvt) Ltd,-do-,CMA,"Rs. 18,250,000",-,,-,Positive
26,Buildings on leasehold land,,,,,,,
27,Ceylon Cold Stores PLC,P B Kalugalagedara,CMA,-,"Rs. 500 - Rs. 5,500",,-,Positive
28,Ceylon Holiday Resorts Ltd,-do-,CMA,-,"Rs. 9,300 - Rs. 17,500",,-,Positive
29,Colombo Ice Company (Pvt) Ltd,-do-,CMA,-,"Rs. 2,500 - Rs. 9,000",,-,Positive
30,Keells Food Products PLC,-do-,CMA,-,"Rs. 150 - Rs. 10,000",,-,Positive
31,Habarana Lodge Ltd.,S Fernando,CMA,-,"Rs. 1,000 - Rs. 12,000",,-,Positive
32,Habarana Walk Inn Ltd,-do-,CMA,-,"Rs. 3,200 - Rs. 9,500",,-,Positive
33,Hikkaduwa Holiday Resort (Pvt) Ltd,P B Kalugalagedara,CMA,-,"Rs. 3,000 - Rs. 9,000",,-,Positive
34,Jaykay Marketing Service (Pvt) Ltd,-do-,IA,-,Rs. 30 - Rs. 300,,6%,Negative
35,John Keells Warehousing (Pvt) Ltd,K T D Tissera,DRC,-,"Rs. 800 - Rs. 5,500",,-,Positive
36,Rajawella Holdings Ltd,P B Kalugalagedara,CMA,-,"Rs. 2000 - Rs. 9,500",,-,Positive
37,Trans Asia Hotels PLC,-do-,CMA,-,"Rs. 475 - Rs. 10,000",,-,Positive
38,Yala Village (Pvt ) Ltd,-do-,CMA,-,"Rs. 2,500 - Rs. 9,200",,-,Positive

Table 129:

,0,1,2,3,4,5,6
0,,,,,,rate,
1,Freehold property,,,,,,
2,Ahungalla Holiday Resort Ltd,S Fernando,CMA,"Rs. 275,000 -",-,-,Positive
3,,,,"Rs. 500,000",,,
4,Asian Hotels and Properties PLC,P B Kalugalagedara,IA,-,-,6%,Negative
5,Ceylon Cold Stores PLC,-do-,CMA,"Rs. 1,900,000","Rs. 2,000",-,Positive
6,Facets (Pvt) Ltd,S Fernando,CMA,"Rs. 550,000",-,-,Positive
7,Glennie Properties (Pvt) Ltd,P B Kalugalagedara,CMA,"Rs. 18,000,000",-,-,Positive
8,John Keells Properties Ja-Ela (Pvt) Ltd,-do-,CMA,"Rs. 1,400,000","Rs. 4,000",-,Positive
9,John Keells PLC,-do-,CMA,"Rs. 850,000",-,-,Positive
10,J K Thudella Properties (Pvt) Ltd,P P T Mohideen,CMA,"Rs. 375,000",-,-,Positive
11,Keells Realtors Ltd,P B Kalugalagedara,CMA,"Rs. 750,000 -",Rs. 500,-,Positive
12,,,,"Rs. 2,750,000",,,
13,Resort Hotels Ltd,S Fernando,CMA,"Rs. 130,000 -",-,-,Positive
14,,,,"Rs. 300,000",,,
15,Trinco Walk Inn Ltd,-do-,CMA,"Rs. 160,000 -",-,-,Positive
16,,,,"Rs. 400,000",,,
17,Waterfront Properties (Pvt) Ltd,P B Kalugalagedara,IA,-,-,6%,Negative
18,Whittall Boustead (Pvt) Ltd,-do-,CMA,"Rs. 2,800,000","Rs. 500 - Rs. 2,200",-,Positive
19,Wirawila Walk Inn Ltd,S Fernando,CMA,"Rs. 26,250",-,-,Positive
20,Vauxhall Land Developments (Pvt),P B Kalugalagedara,CMA,"Rs. 18,250,000",-,-,Positive
21,Ltd,,,,,,
22,Leasehold property,,,,,,
23,Jaykay Marketing Service (Pvt) Ltd,P B Kalugalagedara,IA,"Rs. 270,000 -",-,6%,Negative
24,,,,"Rs. 400,000",,,
25,Tea Smallholder Factories PLC,-do-,CMA,"Rs. 2,500,000 -","Rs. 500 - Rs. 3,000",-,Positive
26,,,,"Rs. 3,500,000",,,

Table 130:

,0,1,2,3,4,5,6
0,26.2 Group quoted investments,,,,,,
1,,GROUP,,,COMPANY,,
2,As at 31 March,Number of,Effective,Number of,Effective,2024,2023
3,,shares,holding %,shares,holding %,In Rs.’000s,In Rs.’000s
4,Cost,,,,,,
5,Asian Hotels and Properties PLC,"347,824,190",78.56%,"347,824,190",78.56%,"5,379,784","5,377,344"
6,Ceylon Cold Stores PLC,"773,245,440",81.36%,"671,558,120",70.66%,"1,744,507","1,709,632"
7,John Keells Hotels PLC,"1,169,598,478",80.32%,"1,169,598,478",80.32%,"7,102,140","7,102,140"
8,John Keells PLC,"52,834,784",86.90%,"52,834,784",86.90%,"495,396","491,354"
9,Keells Food Products PLC,"22,937,250",88.63%,"20,364,054",79.86%,"1,244,012","1,241,989"
10,Tea Smallholder Factories PLC,"11,286,000",37.62%,"11,286,000",37.62%,"66,809","66,809"
11,Trans Asia Hotels PLC,"184,107,284",82.74%,"97,284,256",48.64%,"1,621,485","1,619,225"
12,Union Assurance PLC,"530,357,150",90.00%,"530,357,150",90.00%,"2,707,024","2,691,005"
13,,,,,,"20,361,157","20,299,498"

Table 131:

,0,1,2,3,4,5,6
0,As at 31 March,2024,,,2024,,2023
1,,,,,,,Cost
2,,Number of,Effective,Number of,Effective,Cost,
3,,,,,,,In Rs.’000s
4,,shares,holding %,shares,holding %,In Rs.’000s,
5,Ahungalla Holiday Resorts (Pvt) Ltd,"13,633,282",80.32,-,-,-,-
6,Beruwala Holiday Resorts (Pvt ) Ltd,"219,725,653",79.78,-,-,"3,586","3,586"
7,British Overseas (Pvt) Ltd,61,61.00,61,61.00,-,-
8,Ceylon Holidays Resorts Ltd,"18,260,784",79.60,-,-,"3,893","3,893"
9,Cinnamon Hotel Management Ltd,"1,000,000",100.00,"1,000,000",100.00,"547,329","500,486"
10,Cinnamon Hotel Management International (Pvt) Ltd,"50,000",100.00,-,-,-,-
11,Cinnamon Holiday (Pvt) Ltd,"20,000",80.32,-,-,-,-
12,Facets (Pvt) Ltd,"15,000",100.00,"15,000",100.00,-,-
13,Fantasea World Investments (Pte) Ltd,"7,299",80.32,-,-,"5,245","4,908"
14,Glennie Properties (Pvt) Ltd,"16,386,140",100.00,"16,386,142",100.00,"163,861","163,861"
15,Habarana Lodge Ltd,"12,981,548",78.99,-,-,"4,794","4,312"
16,Habarana Walk Inn Ltd,"4,321,381",79.34,-,-,"2,719","2,719"
17,Hikkaduwa Holiday Resorts (Pvt) Ltd,"107,596,700",79.60,-,-,"3,428","2,874"
18,Infomate (Pvt) Ltd,"2,000,000",100.00,"2,000,000",100.00,"46,720","43,773"
19,International Tourists and Hoteliers Ltd,"38,490,901",79.78,-,-,-,-
20,J K Land (Pvt) Ltd,"2,302,760,246",100.00,"2,302,760,246",100.00,"24,964,639","24,964,639"
21,J K Packaging (Pvt) Ltd,"1,450,000",100.00,"1,450,000",100.00,-,-
22,J K Thudella Properties (Pvt) Ltd,"45,346,760",100.00,-,-,-,-
23,JayKay Marketing Services (Pvt) Ltd,"202,239,025",81.36,-,-,"298,009","258,114"
24,John Keells BPO Holdings (Pvt) Ltd,"19,000,000",100.00,-,-,-,-
25,John Keells BPO International (Pvt) Ltd,"1,500,000,000",100.00,-,-,-,-
26,John Keells BPO Solutions Lanka (Pvt) Ltd,"32,843,578",100.00,-,-,-,-
27,John Keells Information Technology (Pvt) Ltd,"9,650,000",100.00,"9,650,000",100.00,"126,362","124,665"
28,John Keells Foods India (Pvt) Ltd,"8,999,990",88.63,-,-,-,-
29,John Keells International (Pvt) Ltd,"199,160,000",100.00,"199,160,000",100.00,"680,895","676,747"
30,John Keells Logistics (Pvt) Ltd,"19,999,998",100.00,"19,999,998",100.00,"233,839","232,048"
31,John Keells Maldivian Resorts (Pte) Ltd,"49,044,238",80.32,-,-,"18,587","18,299"
32,John Keells Office Automation (Pvt) Ltd,"500,000",100.00,"500,000",100.00,"79,426","74,813"
33,John Keells Properties (Pvt) Ltd,"101,804",100.00,"101,804",100.00,-,-
34,John Keells Properties Ja-Ela (Pvt) Ltd,"95,436,000",100.00,-,-,-,-
35,John Keells Residential Properties (Pvt) Ltd,"2,081,698",100.00,"2,681,698",100.00,"20,817","20,817"
36,John Keells Singapore (Pte) Ltd,"160,000",80.00,"160,000",80.00,"4,209","4,209"
37,John Keells Stock Brokers (Pvt) Ltd,"1,500,000",90.04,"360,000",24.00,"98,245","90,902"
38,John Keells Teas (Pvt) Ltd,"12,000",100.00,"12,000",100.00,"30,897","26,599"
39,John Keells Warehousing (Pvt) Ltd,"12,000,000",86.90,-,-,"5,039","5,039"
40,Kandy Walk Inn Ltd,"6,165,484",79.03,-,-,"4,094","4,094"
41,Keells Consultants (Pvt) Ltd,928,100.00,928,100.00,"2,070","2,070"
42,Keells Realtors Ltd,"7,500,000",95.81,"5,100,000",40.00,"119,124","119,124"
43,Keells Shipping (Pvt) Ltd,"50,000",100.00,"50,000",100.00,-,-
44,Lanka Marine Services (Pvt) Ltd,"34,805,470",99.44,"34,805,470",99.44,"1,426,805","1,418,844"
45,Logipark International (Pvt) Ltd,"60,407,698",81.36,-,-,894,284
46,Mack Air (Pvt) Ltd,"89,260",100.00,"89,260",100.00,"50,174","40,405"
47,Mack Air Services Maldives (Pvt) Ltd,"4,900",49.00,"4,700",47.00,"2,022","2,022"
48,Mack International Freight (Pvt) Ltd,"13,000,000",100.00,"13,000,000",100.00,"3,547","3,015"
49,Mackinnon Keells Ltd,"31,966,951",100.00,"31,966,951",100.00,"670,166","670,166"
50,Mackinnon Mackenzie and Company (Shipping) Ltd,"139,092",100.00,"139,092",100.00,"65,844","65,844"

Table 132:

,0,1,2,3,4,5,6
0,As at 31 March,2024,,,2024,,2023
1,,,,,,,Cost
2,,Number of,Effective,Number of,Effective,Cost,
3,,,,,,,In Rs.’000s
4,,shares,holding %,shares,holding %,In Rs.’000s,
5,Mackinnon Mackenzie and Company of (Ceylon) Ltd,"1,244",100.00,"1,244",100.00,"29,122","29,122"
6,Mackinnons Travels (Pvt) Ltd,"499,996",100.00,"499,996",100.00,"31,736","31,853"
7,Mortlake (Pvt) Ltd,43,100.00,43,100.00,"20,000","20,000"
8,Nuwara Eliya Holiday Resorts (Pvt) Ltd,"33,123,682",80.32,-,-,-,-
9,Rajawella Holdings Ltd,"13,063,936",49.85,"11,573,339",45.18,"801,707","801,707"
10,Rajawella Hotels Company Ltd,"3,342,035",80.32,-,-,-,-
11,Resort Hotels Ltd,"639,421",79.89,-,-,-,-
12,The Colombo Ice Company (Pvt) Ltd,"169,999,999",81.36,-,-,"1,786","1,365"
13,Tranquility (Pte) Ltd,"637,499",80.32,-,-,"6,300","5,879"
14,Trans-Ware Logistics (Pvt) Ltd,"5,539,929",100.00,"5,539,929",100.00,"58,983","58,983"
15,Travel Club (Pte) Ltd,"29,059",80.32,-,-,"3,693","3,693"
16,Trinco Holiday Resorts (Pvt) Ltd,"8,120,005",80.32,-,-,"3,628","3,628"
17,Trinco Walk Inn Ltd,"3,000,007",80.32,-,-,-,-
18,Vauxhall Land Developments (Pvt) Ltd,"2,171,655,391",100.00,-,-,-,-
19,Walkers Tours Ltd,"3,737,634",98.51,"3,737,634",98.05,"206,357","200,041"
20,Waterfront Properties (Pvt) Ltd,"14,383,027,448",99.27,"13,652,103,021",95.75,"132,758,242","132,745,038"
21,Waterfront Properties (Pvt) Ltd - Preference s...,"2,806,022,014",-,"2,806,022,014",-,"31,933,105","12,348,275"
22,Whittall Boustead (Pvt) Ltd,"5,341,105",100.00,"5,341,105",100.00,"1,716,841","1,689,049"
23,Whittall Boustead (Travel) Ltd,"22,452,271",100.00,"22,452,271",100.00,"283,179","280,558"
24,Wirawila Walk Inn Ltd,"2,028,078",80.32,-,-,-,-
25,Yala Village (Pvt) Ltd,"28,268,000",75.33,-,-,"2,752","2,752"
26,Yala Village (Pvt) Ltd- Non voting preference ...,"10,000,000",-,-,-,-,-
27,,,,,,"197,544,710","177,775,113"

Table 133:

,0,1
0,27. \nINVESTMENT IN EQUITY ACCOUNTED INVESTEES,The income statement reflects the Group’s shar...
1,Accounting policy,operations of the associate or joint venture. ...
2,An associate is an entity over which the Group...,investees is presented as part of the Group’s ...
3,Significant influence is the power to particip...,has been a change recognised directly in the e...
4,"operating policy decisions of the investee, bu...","or joint venture, the Group recognises its sha..."
...,...,...
60,The Group’s investments in its associate and j...,ventures using their corresponding/matching 12...
61,for using the equity method. Under the equity ...,"period. In the case of associates, where the r..."
62,in an associate or a joint venture is initiall...,"to Group reporting dates, adjustments are made..."
63,carrying amount of the investment is adjusted ...,transactions or events up to 31 March.
64,the Group’s share of net assets of the associa...,

Table 134:

,0,1,2,3,4,5,6,7,8
0,27.,INVESTMENT IN EQUITY ACCOUNTED INVESTEES (CONTD.),,,,,,,
1,,,GROUP,,,,COMPANY,,
2,As at 31 March,Number,Effective,2024,2023,Number,Effective,2024,2023
3,,of shares,Holding,In Rs.,In Rs.,of shares,Holding,In Rs.,In Rs.
4,,,%,‘000s,‘000s,,%,‘000s,‘000s
5,27.1 \nInvestments in joint ventures,,,,,,,,
6,Braybrooke Residential Properties (Pvt) Ltd,102,50.00,"1,804,500","1,804,500",-,-,-,-
7,DHL Keells (Pvt) Ltd,"1,000,000",50.00,"10,000","10,000","1,000,000",50.00,"10,000","10,000"
8,Inchcape Mackinnon Mackenzie Shipping,"164,520",60.00,"16,452","16,452","164,520",60.00,"16,452","16,452"
9,(Pvt) Ltd,,,,,,,,
10,Sentinel Reality (Pvt) Ltd,"7,054,938",40.16,"66,668","65,768",-,-,-,-
11,27.2 \nInvestments in associates,,,,,,,,
12,Quoted,,,,,,,,
13,Nations Trust Bank PLC- Voting shares,"83,139,277",29.49,"2,388,956","2,215,746","55,611,559",19.72,"1,658,080","1,542,220"
14,Nations Trust Bank PLC- Non voting shares,"23,049,754",52.10,"1,948,738","1,900,681","18,283,973",41.33,"1,435,705","1,397,585"
15,Unquoted,,,,,,,,
16,Capitol Hotel Holdings (Pvt) Ltd,"3,249,232",19.47,"325,483","325,483","3,254,832",19.47,"325,483","325,483"
17,Colombo West International Terminal,"107,488,547",34.00,"10,748,855","5,579,243","107,488,547",34.00,"10,748,855","5,579,243"
18,(Pvt) Ltd,,,,,,,,
19,Fairfirst Insurance Ltd,"68,902,870",19.80,"689,718","689,718",-,-,-,-
20,Indra Hotels and Resorts (Pvt) Ltd,"125,170,025",32.13,"1,137,570","670,742",-,-,-,-
21,Maersk Lanka (Pvt) Ltd,"30,000",30.00,150,150,"30,000",30.00,150,150
22,Saffron Aviation (Pvt) Ltd,"24,887,160",40.00,"248,872","248,872","24,887,160",40.00,-,-
23,Saffron Aviation (Pvt) Ltd - Preference,"135,530,835",-,"506,247","506,247","135,530,835",-,-,-
24,shares,,,,,,,,
25,South Asia Gateway Terminals (Pvt) Ltd,"159,826,750",42.19,"7,346,367","7,346,367","159,826,750",42.19,"7,346,367","7,346,367"
26,Cumulative profit accruing to the Group,,,"10,307,388","6,088,033",,,,
27,net of dividend,,,,,,,,
28,Share of net assets of equity accounted,,,"10,605,240","11,018,144",,,,
29,investees,,,,,,,,

Table 135:

,0,1,2,3,4,5,6,7,8
0,As at/year ended 31 March,2024,2023,2024,2023,2024,2023,2024,2023
1,Group share of;,,,,,,,,
2,Revenue,"12,663,859","14,382,232","16,390,797","13,363,535","7,282,133","7,092,226","36,336,789","34,837,993"
3,Operating expenses including,"(6,893,824)","(6,712,293)","(8,980,371)","(8,369,466)","(6,169,415)","(6,742,137)","(22,043,610)","(21,823,896)"
4,cost of sales,,,,,,,,
5,Net finance income,"63,934","93,393","61,181","282,176","(801,326)","(625,147)","(676,211)","(249,578)"
6,Tax expense,"(551,101)","(3,092,315)","(2,695,359)","(1,817,599)","(241,494)","(281,062)","(3,487,954)","(5,190,976)"
7,Share of results of equity,"5,282,868","4,671,017","4,776,248","3,458,646","69,898","(556,120)","10,129,014","7,573,543"
8,accounted investees,,,,,,,,
9,Other comprehensive income,"(1,087,942)","913,548","674,844","748,850",195,"(21,415)","(412,903)","1,640,983"
10,Total Comprehensive Income,"4,194,926","5,584,565","5,451,092","4,207,496","70,093","(577,535)","9,716,111","9,214,526"
11,Group share of;,,,,,,,,
12,Total assets,"13,636,693","14,954,279","205,697,451","168,098,266","15,577,813","15,468,925","234,911,957","198,521,470"
13,Total liabilities,"(3,123,833)","(4,616,383)","(170,766,467)","(143,023,128)","(13,049,612)",,"(12,574,972) (186,939,912) (160,214,483)",
14,Net assets,"10,512,860","10,337,896","34,930,984","25,075,138","2,528,201","2,893,953","47,972,045","38,306,987"
15,Goodwill,-,-,"165,899","165,899","13,260","13,260","179,159","179,159"
16,,"10,512,860","10,337,896","35,096,883","25,241,037","2,541,461","2,907,213","48,151,204","38,486,146"

Table 136:

,0,1,2,3,4,5,6
0,,,Number of shares,Cost,,Market value,
1,As at 31st March,2024,2023,2024,2023,2024,2023
2,,,,In Rs. ’000s,In Rs. ’000s,In Rs. ’000s,In Rs. ’000s
3,Access Engineering PLC,"10,418,795","504,769","183,226","8,105","235,465","7,168"
4,Agstar PLC,-,"12,726,104",-,"224,993",-,"142,532"
5,Aitken Spence Hotel Holdings PLC,"63,958","1,105,257","2,997","51,929","4,234","66,205"
6,Aitken Spence PLC,"2,284,705","2,684,367","244,201","285,761","297,583","351,652"
7,Alumex PLC,-,"9,440,274",-,"77,455",-,"77,410"
8,Capital Alliance PLC,-,"1,126,043",-,"34,067",-,"36,709"
9,Ceylon Cold Stores PLC,-,"974,844",-,"36,212",-,"38,994"
10,Ceylon Tobacco Company PLC,"197,619","307,316","170,180","250,799","242,726","209,205"
11,Chevron Lubricants Lanka PLC,"1,593,824","4,000","154,032",374,"171,735",366
12,CIC Holdings PLC,-,"6,161,257",-,"497,655",-,"413,328"
13,Commercial Bank of Ceylon PLC,"2,484,034",-,"225,507",-,"242,690",-
14,Dialog Axiata PLC,"17,417,713","17,676,940","194,511","200,978","203,787","183,840"
15,Distilleries Company of Sri Lanka PLC,"3,903,677","2,623,258","99,474","54,557","105,009","51,416"
16,Hayleys Fabric PLC,"6,044,803","3,367,985","235,429","109,239","248,441","84,874"
17,Hatton National Bank PLC,"5,832,821","2,917,710","784,714","339,427","1,045,564","377,843"
18,Hela Apparel Holdings PLC,"15,871,596","10,305,776","143,935","126,838","96,817","82,446"
19,Hemas Holdings PLC,"4,897,886","5,788,039","294,000","347,330","393,790","376,223"
20,Hsenid Business Solutions PLC,-,"3,365,679",-,"56,207",-,"49,812"
21,JAT Holdings PLC,"529,945",-,"7,926",-,"9,168",-
22,John Keells Holdings PLC,"3,238,657","1,224,949","508,109","157,387","628,299","171,493"
23,John Keells Hotels PLC,"2,211,127","6,785,692","30,188","81,748","41,127","128,250"
24,Lanka IOC PLC,-,"1,842,280",-,"350,722",-,"315,951"
25,Lion Brewery (Ceylon) PLC,-,"3,149",-,"1,968",-,"2,251"
26,Pan Asia Banking Corporation PLC,-,"1,145,638",-,"16,268",-,"14,320"
27,Peoples Leasing and Finance PLC,"3,612,531",-,"41,177",-,"39,738",-
28,Piramal Glass Ceylon PLC,"2,388,666",-,"64,880",-,"70,466",-
29,Prime Lands Residencies PLC,-,"2,007,801",-,"14,441",-,"16,062"
30,Sampath Bank PLC,"3,000,220","80,298","207,649","4,493","240,018","4,216"
31,Singer Sri Lanka PLC,-,"867,838",-,"9,039",-,"13,018"
32,Sunshine Holdings PLC,"4,997,813","3,076,136","208,327","113,216","297,370","138,426"
33,Textured Jersey Lanka PLC,"1,126,043","7,239,468","42,640","260,647","42,339","231,663"
34,Tokyo Cement Company (Lanka) PLC,"6,406,203","147,826","311,075","5,219","309,676","7,391"
35,,,,"4,154,177","3,717,074","4,966,042","3,593,064"

Table 137:

,0,1
0,Fair value reserve of financial assets at FVOCI,"5,579,169 \n (1,323,092)\n 15,147 \n (1,340)"
1,,"136,452,778\n146,091,034\n 11,804,788 \n 18,05..."
2,The revaluation reserve consists of the net su...,"shareholders, held as part of the Restricted T..."
3,"property, plant and equipment and present valu...",subject to meeting governance requirements sti...
4,business (PVIB).,and can only be released upon receiving approv...
5,,one-off surplus in the SHF is represented by g...
6,The foreign currency translation reserve compr...,as per the direction of the IRCSL.
7,movement arising from the currency translation...,
8,and equity accounted investees into Sri Lankan...,Nations Trust Bank PLC (NTB)
9,,The statutory reserve fund is maintained as pe...
10,The other capital reserve is used to recognise...,terms of Section 20 of the Banking Act No 30 o...
11,settled share-based payments provided to emplo...,equivalent to 5% of profit after tax transferr...
12,"management personnel, as part of their remuner...",the reserve fund is equal to 50% of the Bank’s...
13,,a further 2% of profits will be transferred un...
14,Restricted regulatory reserve,equal to the Bank’s stated Capital.
15,Union Assurance PLC (UA),
16,,Cash flow hedge reserve includes the fair valu...
17,Based on the direction issued by the Insurance...,
18,,portion of interest rate swaps designated as c...
19,"of Sri Lanka (IRCSL) dated 20 March 2018, and ...",
20,"has transferred Rs.3,382 Mn attributable to no...",
21,,The fair value reserve of financial assets at ...
22,unit fund of unit linked business from the lif...,
23,,value of financial instruments designated as f...
24,life shareholder fund (SHF). The distribution ...,

Table 138:

,0,1
0,NOTES TO THE FINANCIAL STATEMENTS,
1,35. \nSHARE-BASED PAYMENT PLANS,Where the terms of an equity-settled transacti...
2,Accounting Policy,the minimum expense recognised is the expense ...
3,Employee share option plan - Equity-settled tr...,"been modified, if the original terms of the aw..."
4,Employees of the Group receive remuneration in...,expense is recognised for any modification tha...
5,"based payment transactions, whereby employees ...","value of the share-based payment transaction, ..."
6,consideration for equity instruments (equity-s...,to the employee as measured at the date of mod...
7,The Group applies SLFRS 2 Share Based Payments...,The dilutive effect of outstanding options is ...
8,employee remuneration in the form of shares fr...,dilution in the computation of diluted earning...
9,,are given in Note 19.2).
10,The cost of equity-settled transactions is rec...,
11,a corresponding increase in other capital rese...,Employee share option scheme
12,period in which the performance and service co...,Under the John Keells Group’s Employees share ...
13,The cumulative expense recognised for equity-s...,share options of the parent are granted to exe...
14,each reporting date until the vesting date ref...,generally with more than 12 months of service....
15,the vesting period has expired and the Group’s...,share options is equal to the 30 days volume w...
16,number of equity instruments that will ultimat...,price of the underlying shares on the date of ...
17,credit to the income statement for a period re...,vest over a period of four years and is depend...
18,in cumulative expense recognised as at the beg...,criteria and a service criteria. The performan...
19,period and is recognised in employee benefits ...,performance achievement of “Met Expectations” ...
20,,being that the employee has to be in employmen...
21,No expense is recognised for awards that do no...,options vest. The fair value of the share opti...
22,except for equity-settled transactions where v...,"date using a binomial option pricing model, ta..."
23,"upon a market or non-vesting condition, which ...",terms and conditions upon which the share opti...
24,irrespective of whether or not the market or n...,
25,"satisfied, provided that all other performance...",The contractual term for each option granted i...
26,satisfied.,cash settlement alternatives. The Group does n...
27,,cash settlement for these share options.

Table 139:

,0,1,2,3,4,5,6
0,the historical volatility over a period simila...,,The following information was used and results...,,,,
1,,,binomial model for ESOP.,,,,
2,,,,COMPANY,,,
3,As at 31st March,2024,2024,2023,2022,2021,2020
4,,Plan no 11,Plan no 11,Plan no 11,Plan no 10,Plan no 10,Plan no 10
5,,Award 2.1,Award 2,Award 1,Award 3,Award 2,Award 1
6,Dividend yield (%),2.07,2.54,2.90,3.28,3.87,3.62
7,Expected volatility (%),25.05,24.99,24.15,22.37,21.35,17.47
8,Risk free interest rate (%),14.49,26.92,23.10,8.87,6.44,9.83
9,Expected life of share options (Years),5,5,5,5,5,5
10,Weighted average share price at the grant date...,158.36,137.83,119.85,132.63,134.74,138.70
11,Weighted average remaining contractual life fo...,3,3,3,3,3,3
12,outstanding (Years),,,,,,
13,Weighted average fair value of options granted...,52.79,45.94,39.95,44.21,44.91,46.23
14,Exercise price for options outstanding at the ...,145.59,137.86,121.91,136.64,132.86,136.97
15,Exercise price for options outstanding at the ...,145.59,137.86,121.91,136.34,132.86,136.97
16,(Adjusted as at 31 March 2024),,,,,,

Table 140:

,0,1
0,36. \nINSURANCE CONTRACT LIABILITIES (CONTD.),
1,"Accounting judgements, estimates and assumptions",IRCSL regulations and the terms and conditions...
2,Product classification,set out the bases for the determination of the...
3,SLFRS 4 requires contracts written by insurers...,additional discretionary benefits are based (t...
4,insurance contracts or investment contracts de...,and within which the company may exercise its ...
...,...,...
68,,Assumptions on future expenses are based on cu...
69,Derivatives embedded in an insurance contract ...,"adjusted for expected expense inflation, if ap..."
70,contract with DPF are separated and fair value...,surrender rates are based on the company’s his...
71,statement unless the embedded derivative itsel...,lapses and surrenders.
72,or investment contract with DPF. The derivativ...,

Table 141:

,0,1
0,NOTES TO THE FINANCIAL STATEMENTS,
1,36. \nINSURANCE CONTRACT LIABILITIES (CONTD.),
2,Liability adequacy test (LAT) - Life insurance...,36.2 Change in life insurance contract liabi...
3,"As at 31 December 2023, liability adequacy tes...",The results of Union Assurance PLC’s (UA) life...
4,"appointed actuary Mr. Vivek Jalan FIA, FIAI of...",consolidated into the Group’s Consolidated Inc...
5,"Private Limited who concluded that, the liabil...",change in life insurance contract liabilities ...
6,"meet future benefits and expenses. Hence, no p...","the Life Fund, the difference between all inco..."
7,be made for any premium deficiency.,attributable to life policy holders during the...
8,SUMMARISED FINANCIAL INFORMATION,
9,In Rs.'000s,
10,For the year ended 31 March,2024\n2023
11,Total Revenue,"18,434,229 \n 15,952,535"
12,Cost of sales,"(10,340,332)\n (9,172,168)"
13,Gross profit,"8,093,897 \n 6,780,367"
14,Operating expenses including distribution and ...,"(6,605,230)\n (5,341,994)"
15,Net finance income,"12,837,204 \n 8,923,960"
16,Profit attributable to shareholders of UA,"(3,492,543)\n (2,712,101)"
17,Change in insurance contract liabilities,"10,833,328 \n 7,650,232"
18,Union Assurance PLC follows a risk mitigation ...,
19,liabilities.,
20,The following table describes headline risks a...,
21,Product\nKey risks,Risk mitigation
22,Traditional participating\n• Market risk: Inv...,• Management discretion to determine amount ...
23,falling below guaranteed minimum rates,policyholder bonuses (within limits)
24,• Policyholder behaviour risk,• Surrender penalties
25,Non-Participating\n• Market risk: Insufficien...,• Derivative hedging programme
26,guarantees and expenses,• Surrender penalties
27,• \nPolicyholder behaviour risk,
28,Universal life\n• \nInterest rate risk: Differ...,• Matching of asset and liability cash flows
29,assets and liabilities,• \nInvesting in investment grade assets
30,• \nInvestment credit risk,
31,Unit linked product\n• Market risk: Insuffici...,• Product repricing
32,• \nPolicyholder behaviour risk,• \nSurrender penalties

Table 142:

,0,1,2,3,4,5
0,"Accounting judgements, estimates and assumptions",,The Management tested several scenarios based ...,,,
1,Employee benefit liability - gratuity,,changes of the assumptions due to the prevaili...,,,
2,The employee benefit liability of the Group is...,,"conditions. Based on those calculations, the m...",,,
3,valuation carried out by independent actuarial...,,concluded that there is no material impact to ...,,,
4,valuations are involve in making assumptions a...,obligation liability of the Group.,,,,
5,future salary increases. The complexity of the...,,,,,
6,"assumptions and its long term nature, the defi...",,,,,
7,highly sensitive to changes in these assumptio...,,,,,
8,reviewed at each reporting date.,,,,,
9,The principal assumptions used in determining ...,,,,,
10,For the year ended 31 March,,,2024,,2023
11,Discount rate,,,11.00% - 13.00%,,18.00% -19.00%
12,Future salary increases,,,11.00% - 12.00%,,11.00% -15.00%
13,The adjusted treasury bond rate for the credit...,,,,,
14,38.4 \nSensitivity of assumptions used,,,,,
15,A percentage change in the assumptions would h...,,,,,
16,In Rs.'000s,GROUP,,,COMPANY,
17,As at 31 March,2024,2023,,2024,2023
18,Discount rate:,,,,,
19,1% Increase,"(159,683)","(104,429)",,"(10,507)","(6,849)"
20,1% Decrease,"138,798","91,414",,"11,256","7,311"
21,Salary Increment rate:,,,,,
22,1% Increase,"145,586","100,305",,"11,689","7,899"
23,1% Decrease,"(261,347)","(114,064)",,"(11,096)","(7,504)"
24,38.5 Maturity analysis of the payments,,,,,
25,The following payments are expected on employe...,,,,,
26,In Rs.'000s,GROUP,,,COMPANY,
27,As at 31 March,2024,2023,,2024,2023
28,Within the next 12 months,"244,365","151,479",,"22,222",-
29,Between 1 and 2 years,"227,810","236,076",,-,"18,323"
30,Between 2 and 5 years,"2,012,204","1,042,794",,"304,704","176,201"
31,Between 5 and 10 years,"968,710","1,009,765",,-,"25,232"
32,Beyond 10 years,"115,294","72,979",,-,-
33,Total expected payments,"3,568,383","2,513,093",,"326,926","219,756"
34,Weighted average duration (years) of defined b...,6.33,6.72,,4.30,4.93
35,39. \nNON CURRENT FINANCIAL LIABILITIES,,,,,
36,Accounting policy,,,,,
37,Group classifies all financial non current lia...,,,,,
38,retention liabilities of the Waterfront integr...,,,,,

Table 143:

,0,1
0,NOTES TO THE FINANCIAL STATEMENTS,
1,39. \nNON CURRENT FINANCIAL LIABILITIES (CONTD.),
2,39.1 \nIssue of unlisted convertible debentur...,The remaining outstanding debentures post this...
3,subsidiary of Fairfax Financial Holdings Ltd,"98,125,000 debentures of Rs. 12.76 billion. Th..."
4,The Company raised foreign direct investments ...,eligible for conversion till 12 August 2025.
5,"through a private placement of unrated, unlist...",
6,debentures on 12 August 2022 at an issue price...,"Accordinly, JKH has issued and listed 110,000,..."
7,to certain controlled affiliates (subsidiaries...,the Company. Stated capital was increased by t...
8,Limited. As per the SLFRS 9 Financial Instrume...,the converted number of shares from the liabil...
9,debentures were contrasted against an equivale...,under Non current Financial Libilities and the...
10,order to segregate the liability and equity co...,recognised under Other Capital Reserve.
11,the transaction. HWIC has exercised its option...,
12,debentures of Rs.14.30 billion.,
13,40. \nOTHER NON CURRENT LIABILITIES,
14,Accounting policy,
15,Group classifies all non-financial non current...,
16,In Rs.'000s,GROUP
17,AS at 31 March,2024\n2023
18,Contract liabilities,"395,686\n 158,640"
19,Deposits,"111,259\n 103,366"
20,Other deferred liabilities,"108,500\n 24,230"
21,,"615,445\n 286,236"
22,41. \nTRADE AND OTHER PAYABLES,
23,Accounting policy,
24,Trade payables are the aggregate amount of obl...,
25,payables are classified as current liabilities...,
26,In Rs.'000s,GROUP\nCOMPANY
27,As at 31 March,2024\n2023\n2024\n2023
28,Trade and other payables,"41,764,296\n 28,570,126 \n1,463,935\n 631,405"
29,Contract liabilities,"179,618\n 186,264 \n-\n -"
30,Reinsurance payables,"317,748\n 626,885 \n-\n -"
31,Advances and deposits,"320,934\n 483,007 \n-\n -"
32,,"42,582,596\n 29,866,282 \n1,463,935\n 631,405"
33,Trade and other payables are non-interest bear...,
34,on the Group’s liquidity risk management proce...,
35,42. \nSHORT TERM BORROWINGS,
36,Accounting policy,
37,Short term borrowings are the interest bearing...,
38,obtained for working capital requirements.,
39,In Rs.'000s,GROUP\nCOMPANY
40,As at 31 March,2024\n2023\n2024\n2023
41,Bank borrowings,"21,062,456\n 8,701,652 \n13,909,261\n 1,300,000"
42,,"21,062,456\n 8,701,652 \n13,909,261\n 1,300,000"

Table 144:

,0,1
0,Other tax payables,"2,732,341\n2,469,758\n21,441\n 17,811"
1,,"6,668,511\n 5,191,579 \n21,441\n 17,811"
2,44. \nRELATED PARTY TRANSACTIONS,Non-recurrent related party transactions
3,Terms and conditions of transactions with rela...,There were no non-recurrent related party tran...
4,The Group and the Company carried out transact...,aggregate value exceeds 10% of the equity or 5...
5,course of business with the following related ...,whichever is lower of the company as per 31 Ma...
6,"at each of the subsidiaries, joint venture and...","financial statements, which required additiona..."
7,have been disclosed in the Group Directory und...,2023/24 Annual Report under Colombo Stock Exch...
8,Information section of the Annual Report.,Rule 9.14.8 and Code of Best Practices on Rela...
9,,under the Securities and Exchange Commission D...
10,"Governance structure, nature of the entity’s r...",Section 13(c) of the Securities and Exchange C...
11,of business and the country of incorporation h...,
12,“Report of the Related Party Transaction Revie...,Recurrent related party transactions
13,directory.,There were no recurrent related party transact...
14,,exceeds 10% of the consolidated revenue of the...
15,Transactions with related parties are carried ...,"2023 audited financial Statements, which ..."
16,of business. Outstanding current account balan...,in the 2023/24 Annual Report under Colom...
17,"unsecured, interest free and settlement occurs...",Rule 9.14.8 and Code of Best Practices on Rela...
18,,the Securities and Exchange Commission Di...
19,The sales to and purchases from related partie...,13(c) of the Securities and Exchange Commissio...
20,equivalent to those that prevail in arm's leng...,

Table 145:

,0,1,2,3,4,5
0,as follows;,,,,,
1,COMPANY,,2024,,2023,
2,Expiry date,Adjusted exercise,Number of shares,Number of shares,Number of shares,Number of shares
3,,price,outstanding at,exercisable at the,outstanding at the,exercisable at the
4,,Rs.,the end of period,end of period,end of period,end of period
5,31.06.2023,154.10,-,-,"880,000","880,000"
6,30.06.2024,136.97,"880,000","880,000","880,000","660,000"
7,30.06.2025,132.86,"880,000","660,000","880,000","440,000"
8,30.06.2026,136.64,"880,000","440,000","880,000","220,000"
9,30.06.2027,121.91,"862,000","215,500","880,000",-
10,30.06.2028,145.59,"689,600",-,-,-

Table 146:

,0,1,2,3,4,5,6,7,8,9,10
0,In Rs. Mn,,,,,,,,,,
1,31 March,2024,2023,2022,2021,2020,2019,2018,2017,2016,2015
2,OPERATING RESULTS,,,,,,,,,,
3,Group revenue,"280,773","276,640","218,075","127,676","138,956","135,456","121,215","106,273","93,710","91,852"
4,EBIT,"37,683","40,392","34,359","7,931","15,508","20,198","28,155","23,324","20,192","19,226"
5,Finance cost,"(19,669)","(17,803)","(7,035)","(4,669)","(3,166)","(2,722)",(521),(436),(994),(668)
6,Share of results of equity accounted,"10,129","7,574","6,746","4,159","4,466","4,727","3,596","3,303","2,781","2,778"
7,investees (net of tax),,,,,,,,,,
8,Profit before tax,"18,014","22,589","27,324","5,445","12,403","18,616","27,634","22,888","19,198","18,557"
9,Tax expense,"(5,886)","(3,693)","(6,882)","(1,494)","(2,662)","(2,378)","(4,515)","(4,771)","(3,406)","(2,812)"
10,Profit after tax,"12,128","18,896","20,443","3,951","9,741","16,237","23,120","18,117","15,792","15,745"
11,Attributable to:,,,,,,,,,,
12,Equity holders of the parent,"11,249","18,174","20,213","4,772","9,414","15,254","21,021","16,275","14,070","14,348"
13,Non-controlling interests,879,722,230,(821),327,983,"2,099","1,842","1,722","1,397"
14,,"12,128","18,896","20,443","3,951","9,741","16,237","23,120","18,117","15,792","15,745"
15,CAPITAL EMPLOYED,,,,,,,,,,
16,Stated capital,"90,602","73,188","73,188","63,102","62,881","62,806","62,802","62,790","58,702","50,703"
17,Capital reserves and other components,"136,453","146,091","129,011","72,403","66,085","58,646","49,852","38,652","28,715","24,501"
18,of equity,,,,,,,,,,
19,Revenue reserves,"130,812","121,743","109,087","90,652","87,885","82,834","87,266","77,193","67,565","62,594"
20,,"357,867","341,022","311,286","226,157","216,851","204,286","199,920","178,635","154,982","137,798"
21,Non-controlling interest,"19,609","19,396","18,805","16,830","26,872","26,072","24,944","15,696","13,499","12,279"
22,Total equity,"377,476","360,418","330,091","242,987","243,723","230,358","224,864","194,331","168,481","150,077"
23,Total debt,"246,065","264,060","268,228","172,904","100,907","54,513","29,722","22,766","20,750","23,934"
24,,"623,541","624,478","598,319","415,891","344,630","284,871","254,586","217,097","189,231","174,011"
25,ASSETS EMPLOYED,,,,,,,,,,
26,"Property, plant and equipment (PP&E)","382,989","362,097","124,348","113,077","111,534","97,688","87,260","64,396","52,737","49,563"
27,Non-current assets other than PP&E,"214,092","199,604","354,518","257,226","204,360","170,687","136,427","107,912","93,376","78,030"
28,Current assets,"174,110","182,806","238,929","166,491","121,050","95,421","98,762","104,964","94,863","90,493"
29,Liabilities net of debt,"(147,650)","(120,028)","(119,476)","(120,903)","(92,314)","(78,925)","(67,862)","(60,175)","(51,745)","(44,075)"
30,,"623,541","624,478","598,319","415,891","344,630","284,871","254,587","217,097","189,231","174,011"
31,CASH FLOW,,,,,,,,,,
32,Net cash flows from operating activities,"32,751","11,444","30,440","13,825","(10,350)","(4,743)","16,012","21,020","20,513","20,855"
33,Net cash flows from / (used in) investing,"(60,081)","(78,889)","39,363","(44,944)","(27,039)","(8,452)","(16,640)","(17,670)","(9,567)","(1,255)"
34,activities,,,,,,,,,,
35,Net cash flows from / (used in) financing,"(3,040)","(26,810)","31,693","55,427","18,431","(11,000)","(4,587)","(4,105)","(7,717)","(4,838)"
36,activities,,,,,,,,,,
37,Net increase / (decrease) in cash and cash,"(30,370)","(94,254)","101,495","24,308","(18,959)","(14,709)","(5,215)",(755),"3,229","14,762"
38,equivalents,,,,,,,,,,
39,KEY INDICATORS,,,,,,,,,,
40,Basic earnings per share (Rs.),8.06,13.12,15.13,3.62,7.14,11.13,15.2,11.9,10.5,12.6
41,Interest cover (no. of times),1.9,2.3,4.9,1.7,4.9,7.8,54,52.8,51.5,27.7
42,Net assets per share* (Rs.),238.8,227.5,207.7,150.9,144.7,136.3,133.4,119.2,103.4,91.9
43,Enterprise value (EV) (Rs.),"450,008","357,609","311,951","244,679","186,236","210,020","187,926","136,022","124,182","155,675"
44,EV / EBITDA,11,7.7,10.7,15.7,9.2,8.5,5.8,5.0,5.0,6.6
45,ROE (%),3.2,5.6,7.5,2.2,4.5,7.5,11.1,9.8,9.6,11.0
46,Debt / equity ratio (%),65.2,73.3,81.3,71.2,41.4,23.7,13.2,11.7,12.3,15.9
47,Net debt excl. leases (cash)/Equity (%),33.7,35.9,23.5,20.0,14.0,1.9,(14.9),(28.5),(30.8),(28.8)
48,Dividend payout (Rs.Mn),"2,080","2,770","2,012","1,978","4,614","8,186","8,325","7,280","8,038","3,476"
49,Current ratio (no. of times),1.3,2.0,1.8,2.3,2.1,1.7,3.0,3.7,4.0,2.6
50,Market price per share unadjusted (Rs.),194.0,140.0,145.0,148.5,115.4,156.0,159.6,137.9,148.0,199.4
51,Market price per share diluted (Rs.),194.0,140.0,145.0,148.5,115.4,156.0,159.6,137.9,129.5,152.7
52,Revenue growth rate (%),1.5,26.9,70.8,(8.1),2.6,11.8,14.1,13.4,1.6,5.9
53,USD closing rate (Rs.),300.4,329.5,305.0,200.3,189.6,175.5,155.9,151.9,147.7,133.5
54,USD average rate (Rs.),318.1,360.4,208.3,189.0,179.4,168.6,153.6,148.0,139.2,131.2

Table 147:

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,,2024,2023,2024,2023,2024,2023,2024,2023,2024,...,2024,2023,2024,2023,2024,2023,2024,%,2023,%
1,Direct economic value,,,,,,,,,,...,,,,,,,,,,
2,generated,,,,,,,,,,...,,,,,,,,,,
3,Revenue,"51,556","74,538","35,920","34,143","124,795","109,006","51,441","43,032","2,466",...,"9,519","10,537","294,363","290,284","(13,590)","(13,644)","280,773",88.17,"276,640",87.75
4,Finance income,330,265,"1,182",884,77,315,"4,311","1,726",528,...,"17,205","27,362","36,674","40,173","(14,107)","(13,273)","22,567",7.09,"26,900",8.53
5,Share of results of,"6,207","5,775",-,-,(24),-,25,(20),(409),...,-,-,"10,129","7,574",-,-,"10,129",3.18,"7,574",2.40
6,associates,,,,,,,,,,...,,,,,,,,,,
7,Profit on sale of assets,203,192,856,832,"3,367","2,396","1,047",785,440,...,291,246,"6,232","4,558","(1,722)","(1,297)","4,510",1.42,"3,261",1.03
8,& other income,,,,,,,,,,...,,,,,,,,,,
9,Valuation gain/loss,-,-,17,24,5,(3),98,201,233,...,97,132,450,879,-,-,450,0.14,879,0.28
10,on IP,,,,,,,,,,...,,,,,,,,,,
11,,"58,296","80,770","37,975","35,883","128,220","111,714","56,922","45,724","3,258",...,"27,112","38,277","347,848","343,468","(29,419)","(28,214)","318,429",100.00,"315,254",100.00

Table 148:

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,,2024,2023,2024,2023,2024,2023,2024,2023,2024,...,2024,2023,2024,2023,2024,2023,2024,%,2023,%
1,Direct economic value,,,,,,,,,,...,,,,,,,,,,
2,generated,,,,,,,,,,...,,,,,,,,,,
3,Revenue,"51,556","74,538","35,920","34,143","124,795","109,006","51,441","43,032","2,466",...,"9,519","10,537","294,363","290,284","(13,590)","(13,644)","280,773",88.17,"276,640",87.75
4,Finance income,330,265,"1,182",884,77,315,"4,311","1,726",528,...,"17,205","27,362","36,674","40,173","(14,107)","(13,273)","22,567",7.09,"26,900",8.53
5,Share of results of,"6,207","5,775",-,-,(24),-,25,(20),(409),...,-,-,"10,129","7,574",-,-,"10,129",3.18,"7,574",2.40
6,associates,,,,,,,,,,...,,,,,,,,,,
7,Profit on sale of assets,203,192,856,832,"3,367","2,396","1,047",785,440,...,291,246,"6,232","4,558","(1,722)","(1,297)","4,510",1.42,"3,261",1.03
8,& other income,,,,,,,,,,...,,,,,,,,,,
9,Valuation gain/loss,-,-,17,24,5,(3),98,201,233,...,97,132,450,879,-,-,450,0.14,879,0.28
10,on IP,,,,,,,,,,...,,,,,,,,,,
11,,"58,296","80,770","37,975","35,883","128,220","111,714","56,922","45,724","3,258",...,"27,112","38,277","347,848","343,468","(29,419)","(28,214)","318,429",100.00,"315,254",100.00

Table 149:

,0,1,2,3,4
0,In USD '000s,GROUP,,COMPANY,
1,For the year ended 31 March,2024,2023,2024,2023
2,Continuing operations,,,,
3,Revenue from contracts with customers,"873,297","791,160","9,708","7,720"
4,Revenue from Insurance Contracts,"61,366","48,414",-,-
5,Total Revenue,"934,663","839,574","9,708","7,720"
6,Cost of sales,"(753,964)","(689,500)","(5,935)","(3,541)"
7,Gross profit,"180,699","150,074","3,773","4,179"
8,Dividend income,-,-,"38,293","32,276"
9,Other operating income,"15,015","9,896",417,125
10,Selling and distribution expenses,"(33,498)","(25,087)",-,-
11,Administrative expenses,"(83,795)","(66,549)","(7,435)","(6,334)"
12,Other operating expenses,"(27,258)","(29,820)",(288),"(2,271)"
13,Results from operating activities,"51,163","38,514","34,760","27,975"
14,Finance cost,"(65,476)","(54,030)","(39,849)","(26,643)"
15,Finance income,"75,125","81,638","19,265","49,554"
16,Change in insurance contract liabilities,"(36,063)","(23,218)",-,-
17,Change in fair value of investment property,"1,498","2,666",-,-
18,Share of results of equity accounted investees...,"33,718","22,985",-,-
19,Profit before tax,"59,965","68,555","14,176","50,886"
20,Tax expense,"(19,595)","(11,209)",(21),"(6,245)"
21,Profit for the year,"40,370","57,346","14,155","44,641"
22,Attributable to:,,,,
23,Equity holders of the parent,"37,443","55,154",,
24,Non-controlling interests,"2,927","2,192",,
25,,"40,370","57,346",,
26,Earnings per share,,,,
27,Basic earnings per ordinary share,0.03,0.04,,
28,Diluted earnings per ordinary share,0.03,0.04,,

Table 150:

,0,1
0,GLOSSARY,
1,ACCRUAL BASIS \nEARNINGS PER SHARE (BASIC),PRICE EARNINGS RATIO
2,Recording revenues and expenses in the period ...,Market price per share over earnings per share.
3,in which they are earned or incurred regardles...,
4,,PRICE TO BOOK RATIO
...,...,...
110,Profit after tax attributable to equity holder...,
111,(diluted) at the end of the period.,
112,the parent divided by total revenue including,
113,equity accounted investees.,
114,John Keells Holdings PLC Annual Report 2023/...,

Table 151:

,0,1,2
0,other information that may be published,,
1,,,Compliance with legal requirements is not
2,outside of the Report and/or on Company’s,,
3,,The assurance scope has the following,"within the scope of this assurance, and"
4,website for the current reporting period.,,
5,,limitations:,the Company is responsible for ensuring
6,,,adherence to relevant laws.
7,RESPONSIBILITIES OF THE MANAGEMENT OF,,
8,,• \nThe assurance engagement considers an,
9,JOHN KEELLS HOLDINGS PLC AND OF THE,,DNV expressly disclaims any liability or co-
10,,uncertainty of ±5% based on materiality,
11,ASSURANCE PROVIDER,threshold for estimation/measurement,responsibility for any decision a person or an
12,The Management of JKH has the sole,errors and omissions.,entity may make based on this Independent
13,responsibility for the preparation of the Report,,Assurance Statement.
14,and is responsible for all information disclosed,,
15,,• DNV has not been involved in evaluation,
16,in the Report. The company is responsible,,
17,,or assessment of any financial data/,ASSURANCE PROCESS
18,for maintaining processes and procedures,,
19,,performance of the company. DNV opinion,"As part of the assurance process, a multi-"
20,"for collecting, analyzing and reporting the",,
21,,on specific indicators (ref- all sections of,disciplinary team of assurance specialists
22,"information and also, ensuring the quality and",,
23,,core indicators where currency; LKR has,performed assurance work for selected sites of
24,consistency of the information presented in,,
25,,been applied)relies on the third party,"JKH. We adopted a risk-based approach, that"
26,the Report. JKH is also responsible for ensuring,,
27,,audited financial reports of the Company.,"is, we concentrated our assurance efforts on"
28,the maintenance and integrity of its website,,
29,,,the issues of high material relevance to the

Table 152:

,0,1,2
0,,INDEPENDENT ASSURANCE STATEMENT,
1,INTRODUCTION,"In performing this assurance work, DNV’s",• \nThe assessment is limited to data and
2,DNV Business Assurance India Private Limited,responsibility is to the Management of the,information within the defined Reporting
3,"(‘DNV’), has been commissioned by John","Company; however, this statement represents",Period. Any data outside this period is not
4,Keells Holdings PLC (Corporate Identity,our independent opinion and is intended to,considered within the scope of assurance.
...,...,...,...
96,,financial data reported in the audited financial,We carried out the following activities:
97,,reports of the Company.,
98,"DNV Headquarters, Veritasveien 1, P.O.Box 300,...",,
99,,,
100,DNV-2004-ASR-695670,,

Table 153:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year & Country,Addresses,Directors,Stated Capital &
1,Group,,Business,,,,,,Effective Holding
2,,,,Colombo West International,Ports & Shipping Services,2021,"No. 117, Sir Chittampalam A Gardiner Mawatha,","K N J Balendra, J G A Cooray, S Mehta, S Tripa...","USD 51,960,785"
3,,,,Terminal (Pvt) Ltd**,,(PV00238709),Colombo 2.,"H Sundaram, K A Pathak, J S Khurana, A Z Hashi...",34%
4,,,,,,Sri Lanka,Tel. 2475574,"U K Algewattage, K D Bernard",
...,...,...,...,...,...,...,...,...,...
57,,,,,,,"26151853, 26147365 Fax: +91-11-2614 5222",,
58,,,Foods,,,,,,
59,,,,Keells Food Products PLC,Manufacturer and distributor of,1982,"P\n.O Box 10,No.16, Minuwangoda Road, Ekala Ja...","K N J Balendra - Chairperson, J G A Cooray, D ...","Rs.1,294,815,000"
60,,,,,"Processed meat, breaded meat &",(PQ 3),Tel. 2236317/ 2236364,"I Samarajiva, P D Samarasinghe, P N Fernando",88.63%
61,,,,,convenience food products.,Sri Lanka,,,

Table 154:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year & Country,Addresses,Directors,Stated Capital &
1,Group,,Business,,,,,,Effective Holding
2,,,,Colombo West International,Ports & Shipping Services,2021,"No. 117, Sir Chittampalam A Gardiner Mawatha,","K N J Balendra, J G A Cooray, S Mehta, S Tripa...","USD 51,960,785"
3,,,,Terminal (Pvt) Ltd**,,(PV00238709),Colombo 2.,"H Sundaram, K A Pathak, J S Khurana, A Z Hashi...",34%
4,,,,,,Sri Lanka,Tel. 2475574,"U K Algewattage, K D Bernard",
...,...,...,...,...,...,...,...,...,...
57,,,,,,,"26151853, 26147365 Fax: +91-11-2614 5222",,
58,,,Foods,,,,,,
59,,,,Keells Food Products PLC,Manufacturer and distributor of,1982,"P\n.O Box 10,No.16, Minuwangoda Road, Ekala Ja...","K N J Balendra - Chairperson, J G A Cooray, D ...","Rs.1,294,815,000"
60,,,,,"Processed meat, breaded meat &",(PQ 3),Tel. 2236317/ 2236364,"I Samarajiva, P D Samarasinghe, P N Fernando",88.63%
61,,,,,convenience food products.,Sri Lanka,,,

Table 155:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year & Country,Addresses,Directors,Stated Capital &
1,Group,,Business,,,,,,Effective Holding
2,,,,JayKay Marketing Services (Pvt) Ltd,"Owns and Operates the ""Keells"" chain",1980,"No.117,Chittampalam A,Gardiner","J G A Cooray - Chairperson, A Wanniarachchi, K...","Rs.1,198,000,000"
3,,,,,"of supermarkets and ""Nexus Mobile""",(PV 33),"Mawatha,Colombo - 02",N W Tambiah,81.36%
4,,,,,loyalty card programme.,Sri Lanka,Tel. 2316800,,
...,...,...,...,...,...,...,...,...,...
58,,,,Ltd,"Cinnamon"" in Hikkaduwa",(PV 71747),Tel. 091-2277023,,79.60%
59,,,,,,Sri Lanka,,,
60,,,,Indra Hotel and Resorts Kandy,Owner of 216 - Key Hotel in Kandy,2017,"No. 273, Katugastota Road, Kandy","Y S H I K Silva, Y S H R S Silva, Y S H H K Si...","Rs.1,051,400,493"
61,,,,(Pvt) Ltd*,,(PV 124247),Tel. 081 2234346,C L P Gunawardane,32.13%
62,,,,,,Sri Lanka,,,

Table 156:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year & Country,Addresses,Directors,Stated Capital &
1,Group,,Business,,,,,,Effective Holding
2,,,,JayKay Marketing Services (Pvt) Ltd,"Owns and Operates the ""Keells"" chain",1980,"No.117,Chittampalam A,Gardiner","J G A Cooray - Chairperson, A Wanniarachchi, K...","Rs.1,198,000,000"
3,,,,,"of supermarkets and ""Nexus Mobile""",(PV 33),"Mawatha,Colombo - 02",N W Tambiah,81.36%
4,,,,,loyalty card programme.,Sri Lanka,Tel. 2316800,,
...,...,...,...,...,...,...,...,...,...
58,,,,Ltd,"Cinnamon"" in Hikkaduwa",(PV 71747),Tel. 091-2277023,,79.60%
59,,,,,,Sri Lanka,,,
60,,,,Indra Hotel and Resorts Kandy,Owner of 216 - Key Hotel in Kandy,2017,"No. 273, Katugastota Road, Kandy","Y S H I K Silva, Y S H R S Silva, Y S H H K Si...","Rs.1,051,400,493"
61,,,,(Pvt) Ltd*,,(PV 124247),Tel. 081 2234346,C L P Gunawardane,32.13%
62,,,,,,Sri Lanka,,,

Table 157:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year & Country,Addresses,Directors,Stated Capital &
1,Group,,Business,,,,,,Effective Holding
2,,,,International Tourists and Hoteliers,Owner of Cinnamon Bey,1973,"Moragalla, Beruwala","C L P Gunawardane, M H Singhawansa, M R Svensson","Rs.1,939,760,925"
3,,,,Ltd *,,(PB 17),"Tel. 2306600, 2421101-8",,79.78%
4,,,,,,Sri Lanka,,,
5,,,,Kandy Walk Inn Ltd,"Owner & operator of ""Cinnamon",1979,"No.124, Srimath Kuda Ratwatte Mawatha, Kandy","C L P Gunawardane, M H Singhawansa, M R Svensson","Rs.115,182,009"
6,,,,,"Citadel"" in Kandy",(PB 395),Tel. 081 2234365-6/ 081 2237273-4,,79.03%
7,,,,,,Sri Lanka,,,
8,,,,Nuwara Eliya Holiday Resorts (Pvt),Owner of real estate,2014,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, M H Singhawansa, M R Svensson","Rs.331,236,820"
9,,,,Ltd *,,(PV 98357),"Mawatha,Colombo - 02",,80.32%
10,,,,,,Sri Lanka,Tel. 2306000,,
11,,,,Rajawella Hotels Company Ltd *,Owner of real estate,1992,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, M H Singhawansa, M R Svensson","Rs.37,000,585"
12,,,,,,(PB 92),"Mawatha,Colombo - 02",,80.32%
13,,,,,,Sri Lanka,Tel. 2306000,,
14,,,Sri Lankan,Resort Hotels Ltd *,Owner of real estate,1978,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, M H Singhawansa, M R Svensson","Rs.8,849,150"
15,,,Resorts,,,(PB 193),"Mawatha,Colombo - 02",,79.60%
16,,,,,,Sri Lanka,"Tel. 2306780, 2421101-8",,
17,,,,Trinco Holiday Resorts (Pvt) Ltd,"Owner & Operator of ""Trinco Blu by",2009,"Sambativu, Uppuvelli, Trincomalee","C L P Gunawardane, M H Singhawansa, M R Svensson","Rs.357,000,000"
18,,,,,"Cinnamon"" in Trincomalee",(PV 69908),Tel. 026 2222307 / 026 2221611,,80.32%
19,,,,,,Sri Lanka,,,
20,,,,Trinco Walk Inn Ltd*,Owner of Real Estate,1984,"Alles Garden, Uppuveli,Sampathiv Post,","C L P Gunawardane, M H Singhawansa, M R Svensson","Rs.119,850,070"
21,,Cinnamon Hotels & Resorts,,,,(PB 168),Trincomalee,,80.32%
22,,,,,,Sri Lanka,Tel. 026 2222307 / 011 2306600,,
23,,,,Wirawila Walk Inn Ltd*,Owner of Real Estate,1994,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, M H Singhawansa, M R Svensson","Rs.22,936,066"
24,,,,,,(PB 89),"Mawatha,Colombo - 02",,80.32%
25,LEISURE,,,,,Sri Lanka,"Tel. 2306780, 2421101-8",,
26,,,,Yala Village (Pvt) Ltd,"Owner & operator of ""Cinnamon",1999,"P\n.O Box 1,Kirinda, Tissamaharama","M A Perera - Chairperson, C L P Gunawardane, S...","Rs.319,427,600"
27,,,,,"Wild"" in Yala",(PV 2868),Tel. 047 2239449-52,"Singhawansa, J A Davis, M R Svensson, N W Tambiah",75.33%
28,,,,,,Sri Lanka,,,
29,,,,Fantasea World Investments (Pte),"Owner & operator of ""Cinnamon",1997,"Meemu Atoll, Republic of Maldives","C L P Gunawardane, S Rajendra , M H Singhawans...","Rs.341,573,190"
30,,,,Ltd,"Hakuraa Huraa"" in Maldives",(C 143/97),Tel. +9603336000,,80.32%
31,,,,,,Maldives,,,
32,,,,John Keells Maldivian Resorts (Pte),Hotel holding company in the Maldives,1996,"2nd Floor, H.Maizan Building, Sosun Magu, Male,","S Rajendra, C L P Gunawardane, M H Singhawansa...","Rs..3,978,671,681"
33,,,,Ltd,,(C 208/96),Republic of Maldives,,80.32%
34,,,Maldivian,,,Maldives,Tel. +9603336000,,
35,,,Resorts,Tranquility (Pte) Ltd,"Owner and operator of ""Cinnamon",2004,"North Malé Atoll, Republic of Maldives","C L P Gunawardane, S Rajendra, M H Singhawansa...","Rs..552,519,608"
36,,,,,"Dhoinveli"" and ""Cinnamon Velifushi"" in",(C 344/2004),Tel. +9603336000,,80.32%
37,,,,,Maldives,Maldives,,,
38,,,,Travel Club (Pte) Ltd,"Operator of ""Ellaidhoo Maldives by",1992,"North Ari Atoll, Republic of Maldives","C L P Gunawardane, S Rajendra, M H Singhawansa...","Rs.. 143,172,000"
39,,,,,"Cinnamon"" in Maldives",(C 121/92),Tel. +9603336000,,80.32%
40,,,,,,Maldives,,,
41,,,,Cinnamon Holidays (Pvt) Ltd,Service providers of Inbound and,2015,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, M H Singhawansa, M R Svensson","Rs.200,000"
42,,,,,outbound Tours,(PV 107427),"Mawatha,Colombo - 02",,80.32%
43,,,,,,Sri Lanka,Tel. 2306000,,
44,,,,Walkers Tours Ltd,Inbound tour operators,1969,"No.117,Chittampalam A,Gardiner","S Rajendra,C L P Gunawardane, I N Amaratunga","Rs.51,374,200"
45,,Destination Management,,,,(PB 249),"Mawatha,Colombo - 02",,98.05%
46,,,,,,Sri Lanka,Tel. 2306306,,
47,,,,Whittall Boustead (Travel) Ltd,Inbound tour operators,1977,"No.117,Chittampalam A,Gardiner","S Rajendra, C L P Gunawardane, I N Amaratunga","Rs.250,410,000"
48,,,,,,(PB 112),"Mawatha,Colombo - 02",,100%
49,,,,,,Sri Lanka,Tel. 2306746,,
50,,,,Asian Hotels and Properties PLC -,"Developer of 'Crescat Residencies', 'The",1993,"No.89, Galle Road, Colombo 3","K N J Balendra- Chairperson, J G A Cooray, C L...","Rs.3,345,118,012"
51,,,,"Crescat. Boulevard, The Monarch,",Monarch' & 'The Emperor' Residential,(PQ 2),Tel. 0112152100,"S Rajendra, M R Svensson, J Durairatnam, A S D...",78.56%
52,,,,The Emperor.***,Towers Developer and manager of,Sri Lanka,,,
53,PROPERTY,Property Management,,,'Crescat Boulevard ' shopping Mall,,,,
54,,,,John Keells Properties Ja-Ela (Pvt),Developer of “Viman” Ja-Ela,2010,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, N N Mawilmada","Rs.954,360,000"
55,,,,Ltd,,(PV 76068),Tel. 0112152100,,100%
56,,,,,,Sri Lanka,,,

Table 158:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year & Country,Addresses,Directors,Stated Capital &
1,Group,,Business,,,,,,Effective Holding
2,,,,International Tourists and Hoteliers,Owner of Cinnamon Bey,1973,"Moragalla, Beruwala","C L P Gunawardane, M H Singhawansa, M R Svensson","Rs.1,939,760,925"
3,,,,Ltd *,,(PB 17),"Tel. 2306600, 2421101-8",,79.78%
4,,,,,,Sri Lanka,,,
5,,,,Kandy Walk Inn Ltd,"Owner & operator of ""Cinnamon",1979,"No.124, Srimath Kuda Ratwatte Mawatha, Kandy","C L P Gunawardane, M H Singhawansa, M R Svensson","Rs.115,182,009"
6,,,,,"Citadel"" in Kandy",(PB 395),Tel. 081 2234365-6/ 081 2237273-4,,79.03%
7,,,,,,Sri Lanka,,,
8,,,,Nuwara Eliya Holiday Resorts (Pvt),Owner of real estate,2014,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, M H Singhawansa, M R Svensson","Rs.331,236,820"
9,,,,Ltd *,,(PV 98357),"Mawatha,Colombo - 02",,80.32%
10,,,,,,Sri Lanka,Tel. 2306000,,
11,,,,Rajawella Hotels Company Ltd *,Owner of real estate,1992,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, M H Singhawansa, M R Svensson","Rs.37,000,585"
12,,,,,,(PB 92),"Mawatha,Colombo - 02",,80.32%
13,,,,,,Sri Lanka,Tel. 2306000,,
14,,,Sri Lankan,Resort Hotels Ltd *,Owner of real estate,1978,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, M H Singhawansa, M R Svensson","Rs.8,849,150"
15,,,Resorts,,,(PB 193),"Mawatha,Colombo - 02",,79.60%
16,,,,,,Sri Lanka,"Tel. 2306780, 2421101-8",,
17,,,,Trinco Holiday Resorts (Pvt) Ltd,"Owner & Operator of ""Trinco Blu by",2009,"Sambativu, Uppuvelli, Trincomalee","C L P Gunawardane, M H Singhawansa, M R Svensson","Rs.357,000,000"
18,,,,,"Cinnamon"" in Trincomalee",(PV 69908),Tel. 026 2222307 / 026 2221611,,80.32%
19,,,,,,Sri Lanka,,,
20,,,,Trinco Walk Inn Ltd*,Owner of Real Estate,1984,"Alles Garden, Uppuveli,Sampathiv Post,","C L P Gunawardane, M H Singhawansa, M R Svensson","Rs.119,850,070"
21,,Cinnamon Hotels & Resorts,,,,(PB 168),Trincomalee,,80.32%
22,,,,,,Sri Lanka,Tel. 026 2222307 / 011 2306600,,
23,,,,Wirawila Walk Inn Ltd*,Owner of Real Estate,1994,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, M H Singhawansa, M R Svensson","Rs.22,936,066"
24,,,,,,(PB 89),"Mawatha,Colombo - 02",,80.32%
25,LEISURE,,,,,Sri Lanka,"Tel. 2306780, 2421101-8",,
26,,,,Yala Village (Pvt) Ltd,"Owner & operator of ""Cinnamon",1999,"P\n.O Box 1,Kirinda, Tissamaharama","M A Perera - Chairperson, C L P Gunawardane, S...","Rs.319,427,600"
27,,,,,"Wild"" in Yala",(PV 2868),Tel. 047 2239449-52,"Singhawansa, J A Davis, M R Svensson, N W Tambiah",75.33%
28,,,,,,Sri Lanka,,,
29,,,,Fantasea World Investments (Pte),"Owner & operator of ""Cinnamon",1997,"Meemu Atoll, Republic of Maldives","C L P Gunawardane, S Rajendra , M H Singhawans...","Rs.341,573,190"
30,,,,Ltd,"Hakuraa Huraa"" in Maldives",(C 143/97),Tel. +9603336000,,80.32%
31,,,,,,Maldives,,,
32,,,,John Keells Maldivian Resorts (Pte),Hotel holding company in the Maldives,1996,"2nd Floor, H.Maizan Building, Sosun Magu, Male,","S Rajendra, C L P Gunawardane, M H Singhawansa...","Rs..3,978,671,681"
33,,,,Ltd,,(C 208/96),Republic of Maldives,,80.32%
34,,,Maldivian,,,Maldives,Tel. +9603336000,,
35,,,Resorts,Tranquility (Pte) Ltd,"Owner and operator of ""Cinnamon",2004,"North Malé Atoll, Republic of Maldives","C L P Gunawardane, S Rajendra, M H Singhawansa...","Rs..552,519,608"
36,,,,,"Dhoinveli"" and ""Cinnamon Velifushi"" in",(C 344/2004),Tel. +9603336000,,80.32%
37,,,,,Maldives,Maldives,,,
38,,,,Travel Club (Pte) Ltd,"Operator of ""Ellaidhoo Maldives by",1992,"North Ari Atoll, Republic of Maldives","C L P Gunawardane, S Rajendra, M H Singhawansa...","Rs.. 143,172,000"
39,,,,,"Cinnamon"" in Maldives",(C 121/92),Tel. +9603336000,,80.32%
40,,,,,,Maldives,,,
41,,,,Cinnamon Holidays (Pvt) Ltd,Service providers of Inbound and,2015,"No.117,Chittampalam A,Gardiner","C L P Gunawardane, M H Singhawansa, M R Svensson","Rs.200,000"
42,,,,,outbound Tours,(PV 107427),"Mawatha,Colombo - 02",,80.32%
43,,,,,,Sri Lanka,Tel. 2306000,,
44,,,,Walkers Tours Ltd,Inbound tour operators,1969,"No.117,Chittampalam A,Gardiner","S Rajendra,C L P Gunawardane, I N Amaratunga","Rs.51,374,200"
45,,Destination Management,,,,(PB 249),"Mawatha,Colombo - 02",,98.05%
46,,,,,,Sri Lanka,Tel. 2306306,,
47,,,,Whittall Boustead (Travel) Ltd,Inbound tour operators,1977,"No.117,Chittampalam A,Gardiner","S Rajendra, C L P Gunawardane, I N Amaratunga","Rs.250,410,000"
48,,,,,,(PB 112),"Mawatha,Colombo - 02",,100%
49,,,,,,Sri Lanka,Tel. 2306746,,
50,,,,Asian Hotels and Properties PLC -,"Developer of 'Crescat Residencies', 'The",1993,"No.89, Galle Road, Colombo 3","K N J Balendra- Chairperson, J G A Cooray, C L...","Rs.3,345,118,012"
51,,,,"Crescat. Boulevard, The Monarch,",Monarch' & 'The Emperor' Residential,(PQ 2),Tel. 0112152100,"S Rajendra, M R Svensson, J Durairatnam, A S D...",78.56%
52,,,,The Emperor.***,Towers Developer and manager of,Sri Lanka,,,
53,PROPERTY,Property Management,,,'Crescat Boulevard ' shopping Mall,,,,
54,,,,John Keells Properties Ja-Ela (Pvt),Developer of “Viman” Ja-Ela,2010,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, N N Mawilmada","Rs.954,360,000"
55,,,,Ltd,,(PV 76068),Tel. 0112152100,,100%
56,,,,,,Sri Lanka,,,

Table 159:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year & Country,Addresses,Directors,Stated Capital &
1,Group,,Business,,,,,,Effective Holding
2,,,,Keells Realtors Ltd *,Owner of Real Estates and rental of,1977,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, N N Mawilmada","Rs.75,000,000"
3,,,,,properties,(PB 90),Tel. 0112152100,,95.81%
4,,,,,,Sri Lanka,,,
5,,,,Mackinnons Keells Ltd*,Rental of office spaces,1952,"No. 4, Layden Bastian Road, Colombo 1","K M Thanthirige, N W R Wijewantha, N N Mawilmada","Rs.327,800,000"
6,,Property Management,,,,(PB 8),Tel. 0112152100,,100%
7,,,,,,Sri Lanka,,,
8,,,,Whittall Boustead (Pvt) Ltd - Real,Renting of office space,1958,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, K C Subasinghe, N N Mawilmada","Rs.99,188,800"
9,,,,Estate Division,,(PV 31),Tel. 0112152100,,100%
10,,,,,,Sri Lanka,,,
11,,,,British Overseas (Pvt) Ltd,"Developer of ""7th Sense"" Residential",2011,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, K C Subasinghe, N N Mawilmad...","Rs.1,000"
12,,,,,Tower,(PV 80203),Tel. 0112152100,D P Gamlath,61%
13,,,,,,Sri Lanka,,,
14,,,,Braybrooke Residential Properties,Investor of Braybrooke Residential,1998,"No.186, Vauxhall Street, Colombo - 02","Y S H R S Silva - Chairperson, S Rajendra, N N...","Rs.1,403,970,000"
15,,,,(Pvt) Ltd *,Towers (Pvt) Ltd,(PV 19165),Tel. 0112152100,"Y S H I K Silva, C P Palansuriya, Y S H H K Silva",50%
16,,,,,,Sri Lanka,,,
17,,,,Braybrooke Residential Towers,Developer of 'TRI-ZEN' Residential,2017,"No.186, Vauxhall Street, Colombo - 02","Y S H R S Silva - Chairperson, K N J Balendra,...","Rs.3,636,900,000"
18,,,,(Pvt) Ltd *,Towers,(PV 128387),Tel. 0112152100,"N N Mawilmada, Y S H I K Silva, A D B Talwatte...",50%
19,,,,,,Sri Lanka,,,
20,,,,Glennie Properties (Pvt) Ltd *,Property Development,2012,"No.186, Vauxhall Street, Colombo - 02","N N Mawilmada, D P Gamlath, N W R Wijewantha","Rs. 163,861,400"
21,PROPERTY,,,,,(PV 84278),Tel. 0112152100,,100%
22,,,,,,Sri Lanka,,,
23,,,,J K Land (Pvt) Ltd *,Investment Company for Property,2012,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, K C Subasinghe, N N Mawilmada","Rs.24,964,638,930"
24,,,,,Sector,(PV 84272),Tel. 0112152100,,100%
25,,Property Development,,,,Sri Lanka,,,
26,,,,J K Thudella Properties (Pvt) Ltd *,Owner of Real Estates and Rental of,2018,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, N N Mawilmada","Rs.453,467,620"
27,,,,,Properties,(PV 129825),Tel. 0112152100,,100%
28,,,,,,Sri Lanka,,,
29,,,,John Keells Residential Properties,"Developer of ""On320"" Residential",2010,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, N N Mawilmada","Rs.925,200,000"
30,,,,(Pvt) Ltd,Towers,(PV 75050),Tel. 0112152100,,100%
31,,,,,,Sri Lanka,,,
32,,,,Rajawella Holdings Ltd,"Operates an 18 hole, Donald Street",1991,"P O Box 7, Rajawella, Kandy","K N J Balendra - Chairperson, J G A Cooray, S ...","Rs.784,690,140"
33,,,,,Designed Golf Course in Digana,(PB 27),Tel. 0112152100,"C B Thornton (Alt. C J Holloway), G R Bostock ...",49.85%
34,,,,,,Sri Lanka,,"S E Captain (Alt. R S Captain), B D N Jayatilake",
35,,,,Vauxhall Land Developments (Pvt),Owner of Real Estates,2017,"No.186, Vauxhall Street, Colombo - 02","K N J Balendra - Chairperson, J G A Cooray, N ...","Rs.21,716,553,910"
36,,,,Ltd *,,(PV 125587),Tel. 0112152100,N W R Wijewantha,100%
37,,,,,,Sri Lanka,,,
38,,,,Waterfront Properties (Pvt) Ltd***,"Developer of Hotels,Apartments,",2011,"No.186, Vauxhall Street, Colombo - 02","K N J Balendra - Chairperson, J G A Cooray, S ...","Rs.225,511,899,875"
39,,,,,offices & Shopping Malls,(PV 82153),Tel. 0112152100,,99.10%
40,,,,,,Sri Lanka,,,
41,,,,Fairfirst Insurance Ltd **,Providers of Non Life insurance,2014,"Access Towers II, 14th Floor, No: 278/4, Union","C Ratnaswami - Chairperson, A S Wijesinha, C D...","Rs.3,131,949,000"
42,,,,,solutions,(PV 99666/PB),"Place, Colombo 02","S Malhotra, R M Prabhakar, S A J S Jayatilake",19.80%
43,,,,,,Sri Lanka,Tel. 0112428428,,
44,,,Insurance,,,,,,
45,,,,Union Assurance PLC,Providers of Life insurance solutions,1987,"No.20, St. Michaels' Road, Colombo 3","K N J Balendra - Chairperson, S Rajendra, D P ...","Rs.1,000,000,000"
46,,,,,,(PQ 12),Tel. 0112990990,"S A Appleyard, P T Wanigasekara",90%
47,,,,,,Sri Lanka,,,
48,FINANCIAL SERVICES,,,John Keells Stock Brokers (Pvt) Ltd,Share broking services,1979,"No. 186,Vauxhall street, Colombo 02","S Rajendra, D P Gamlath, R S Cader, A M Ali","Rs.57,750,000"
49,,,Stock Broking,,,(PV 89),"Tel.0112306250, 0112342066-7",,90.04%
50,,,,,,Sri Lanka,,,
51,,,,Nations Trust Bank PLC **,Commercial banking,1999,"No. 242, Union Place, Colombo 2.","R S Cader - Chairperson, J C A D'Souza, R D Ra...","Rs.11,426,882,000"
52,,,,,,(PQ 118),Tel. 0114313131,"S L Sebastian, C H A W Wickramasuriya, A R Fer...",32.57%
53,,,Banking,,,,,,
54,,,,,,Sri Lanka,,"R Shanmuganathan, C K Hettiarachchi, H D Gunet...",
55,,,,,,,,K C Subasinghe,

Table 160:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year & Country,Addresses,Directors,Stated Capital &
1,Group,,Business,,,,,,Effective Holding
2,,,,Keells Realtors Ltd *,Owner of Real Estates and rental of,1977,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, N N Mawilmada","Rs.75,000,000"
3,,,,,properties,(PB 90),Tel. 0112152100,,95.81%
4,,,,,,Sri Lanka,,,
5,,,,Mackinnons Keells Ltd*,Rental of office spaces,1952,"No. 4, Layden Bastian Road, Colombo 1","K M Thanthirige, N W R Wijewantha, N N Mawilmada","Rs.327,800,000"
6,,Property Management,,,,(PB 8),Tel. 0112152100,,100%
7,,,,,,Sri Lanka,,,
8,,,,Whittall Boustead (Pvt) Ltd - Real,Renting of office space,1958,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, K C Subasinghe, N N Mawilmada","Rs.99,188,800"
9,,,,Estate Division,,(PV 31),Tel. 0112152100,,100%
10,,,,,,Sri Lanka,,,
11,,,,British Overseas (Pvt) Ltd,"Developer of ""7th Sense"" Residential",2011,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, K C Subasinghe, N N Mawilmad...","Rs.1,000"
12,,,,,Tower,(PV 80203),Tel. 0112152100,D P Gamlath,61%
13,,,,,,Sri Lanka,,,
14,,,,Braybrooke Residential Properties,Investor of Braybrooke Residential,1998,"No.186, Vauxhall Street, Colombo - 02","Y S H R S Silva - Chairperson, S Rajendra, N N...","Rs.1,403,970,000"
15,,,,(Pvt) Ltd *,Towers (Pvt) Ltd,(PV 19165),Tel. 0112152100,"Y S H I K Silva, C P Palansuriya, Y S H H K Silva",50%
16,,,,,,Sri Lanka,,,
17,,,,Braybrooke Residential Towers,Developer of 'TRI-ZEN' Residential,2017,"No.186, Vauxhall Street, Colombo - 02","Y S H R S Silva - Chairperson, K N J Balendra,...","Rs.3,636,900,000"
18,,,,(Pvt) Ltd *,Towers,(PV 128387),Tel. 0112152100,"N N Mawilmada, Y S H I K Silva, A D B Talwatte...",50%
19,,,,,,Sri Lanka,,,
20,,,,Glennie Properties (Pvt) Ltd *,Property Development,2012,"No.186, Vauxhall Street, Colombo - 02","N N Mawilmada, D P Gamlath, N W R Wijewantha","Rs. 163,861,400"
21,PROPERTY,,,,,(PV 84278),Tel. 0112152100,,100%
22,,,,,,Sri Lanka,,,
23,,,,J K Land (Pvt) Ltd *,Investment Company for Property,2012,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, K C Subasinghe, N N Mawilmada","Rs.24,964,638,930"
24,,,,,Sector,(PV 84272),Tel. 0112152100,,100%
25,,Property Development,,,,Sri Lanka,,,
26,,,,J K Thudella Properties (Pvt) Ltd *,Owner of Real Estates and Rental of,2018,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, N N Mawilmada","Rs.453,467,620"
27,,,,,Properties,(PV 129825),Tel. 0112152100,,100%
28,,,,,,Sri Lanka,,,
29,,,,John Keells Residential Properties,"Developer of ""On320"" Residential",2010,"No.186, Vauxhall Street, Colombo - 02","N W R Wijewantha, N N Mawilmada","Rs.925,200,000"
30,,,,(Pvt) Ltd,Towers,(PV 75050),Tel. 0112152100,,100%
31,,,,,,Sri Lanka,,,
32,,,,Rajawella Holdings Ltd,"Operates an 18 hole, Donald Street",1991,"P O Box 7, Rajawella, Kandy","K N J Balendra - Chairperson, J G A Cooray, S ...","Rs.784,690,140"
33,,,,,Designed Golf Course in Digana,(PB 27),Tel. 0112152100,"C B Thornton (Alt. C J Holloway), G R Bostock ...",49.85%
34,,,,,,Sri Lanka,,"S E Captain (Alt. R S Captain), B D N Jayatilake",
35,,,,Vauxhall Land Developments (Pvt),Owner of Real Estates,2017,"No.186, Vauxhall Street, Colombo - 02","K N J Balendra - Chairperson, J G A Cooray, N ...","Rs.21,716,553,910"
36,,,,Ltd *,,(PV 125587),Tel. 0112152100,N W R Wijewantha,100%
37,,,,,,Sri Lanka,,,
38,,,,Waterfront Properties (Pvt) Ltd***,"Developer of Hotels,Apartments,",2011,"No.186, Vauxhall Street, Colombo - 02","K N J Balendra - Chairperson, J G A Cooray, S ...","Rs.225,511,899,875"
39,,,,,offices & Shopping Malls,(PV 82153),Tel. 0112152100,,99.10%
40,,,,,,Sri Lanka,,,
41,,,,Fairfirst Insurance Ltd **,Providers of Non Life insurance,2014,"Access Towers II, 14th Floor, No: 278/4, Union","C Ratnaswami - Chairperson, A S Wijesinha, C D...","Rs.3,131,949,000"
42,,,,,solutions,(PV 99666/PB),"Place, Colombo 02","S Malhotra, R M Prabhakar, S A J S Jayatilake",19.80%
43,,,,,,Sri Lanka,Tel. 0112428428,,
44,,,Insurance,,,,,,
45,,,,Union Assurance PLC,Providers of Life insurance solutions,1987,"No.20, St. Michaels' Road, Colombo 3","K N J Balendra - Chairperson, S Rajendra, D P ...","Rs.1,000,000,000"
46,,,,,,(PQ 12),Tel. 0112990990,"S A Appleyard, P T Wanigasekara",90%
47,,,,,,Sri Lanka,,,
48,FINANCIAL SERVICES,,,John Keells Stock Brokers (Pvt) Ltd,Share broking services,1979,"No. 186,Vauxhall street, Colombo 02","S Rajendra, D P Gamlath, R S Cader, A M Ali","Rs.57,750,000"
49,,,Stock Broking,,,(PV 89),"Tel.0112306250, 0112342066-7",,90.04%
50,,,,,,Sri Lanka,,,
51,,,,Nations Trust Bank PLC **,Commercial banking,1999,"No. 242, Union Place, Colombo 2.","R S Cader - Chairperson, J C A D'Souza, R D Ra...","Rs.11,426,882,000"
52,,,,,,(PQ 118),Tel. 0114313131,"S L Sebastian, C H A W Wickramasuriya, A R Fer...",32.57%
53,,,Banking,,,,,,
54,,,,,,Sri Lanka,,"R Shanmuganathan, C K Hettiarachchi, H D Gunet...",
55,,,,,,,,K C Subasinghe,

Table 161:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year & Country,Addresses,Directors,Stated Capital &
1,Group,,Business,,,,,,Effective Holding
2,,,,John Keells Information,IT Consultancy & Professional Service,1998,"No. 148, Vauxhall Street,Colombo 2.","J G A Cooray - Chairperson, K D Weerasinghe, R...","Rs.96,500,000"
3,,,IT Services,Technology (Pvt) Ltd,,(PV 652),Tel. 2300770-77,,100%
4,,,,,,Sri Lanka,,,
5,,,,Infomate (Pvt) Ltd,IT enabled services,2005,"No.4, Leyden Bastian Road, Colombo 1","K D Weerasinghe, R Shanmuganathan","Rs.20,000,000"
6,,,,,,(PV 921),Tel. (94) 112149700,,100%
7,,,,,,Sri Lanka,,,
8,,,,John Keells BPO Holdings Private,Holding company of BPO group,2006,"IFS Court, 28, Cybercity, Ebene,Mauritius","Z H Niamut, K Peerbocus, K D Weerasinghe","Rs.1,988,300,000"
9,,Information Technology,,Ltd *,companies,(C 60882),Tel. (230) 467 3000,,100%
10,,,IT Enabled,,,Mauritius,,,
11,,,Services,John Keells BPO International (Pvt),Investment holding company,2007,"IFS Court, 28, Cybercity,Ebene, Mauritius","Z H Niamut, K Peerbocus, K D Weerasinghe","Rs.1,616,700,008"
12,,,,Ltd *,,(C 070137),Tel. (230) 467 3000,,100%
13,,,,,,Mauritius,,,
14,,,,John Keells BPO Solutions Lanka,BPO operations in Sri Lanka,2006,"No.4, Leyden Bastian Road, Colombo 1","K D Weerasinghe, R Shanmuganathan","Rs.335,797,260"
15,,,,(Pvt) Ltd*,,(PV 3458),Tel. (94) 2300770-77,,100%
16,,,,,,Sri Lanka,,,
17,,,,John Keells PLC,Produce Broking and Real Estate,1960,"No. 186, Vauxhall street, Colombo 02","K N J Balendra - Chairperson, J G A Cooray, K ...","Rs.152,000,000"
18,,,,,Ownership,(PQ 11),Tel. 2306000,"A K Gunawardhana, C N Wijewardene, B A I Rajak...",86.90%
19,,,,,,Sri Lanka,,,
20,,,,John Keells Teas (Pvt) Ltd,Manager seven bought leaf tea,1979,"No.117,Chittampalam A,Gardiner Mawatha,","K D Weerasinghe, K C Subasinghe, A Z Hashim","Rs.120,000"
21,,,,,factories,(PV 522),Colombo - 02,,100%
22,,Plantation Services,,,,Sri Lanka,Tel. 2306546,,
23,,,,John Keells Warehousing (Pvt) Ltd,Warehousing of Tea and Rubber,2001,"No.93,1st Avenue, Muturajawela, Hendala, Wattala","K D Weerasinghe, K C Subasinghe, A Z Hashim","Rs.120,000,000"
24,,,,,,(PV 638),Tel. 4819560,,86.90%
25,"OTHER, INCLUDING INFORMATION TECHNOLOGY AND PL...",,,,,Sri Lanka,,,
26,,,,Tea Smallholder Factories PLC,Owner and operator of Bought Leaf,1991,"No.186, Vauxhall street, Colombo 02","K N J Balendra – Chairperson, J G A Cooray, E ...","Rs.150,000,000"
27,,,,,factories,(PQ 32),Tel. 2149994 / 2335880,"A S Jayatilleke, S K L Obeyesekere, A K Gunara...",37.62%
28,,,,,,Sri Lanka,,A Z Hashim,
29,,,,Facets (Pvt) Ltd *,Owner of real estate,1974,"No.117,Sir Chittampalam A Gardiner Mawatha","K M Thanthirige, D P Gamlath","Rs.150,000"
30,,,,,,(PV 1048),",Colombo - 02",,100%
31,,,,,,Sri Lanka,Tel. 2306000,,
32,,,,J K Packaging (Pvt) Ltd*,Printing and packaging services,1979,"No 148, Vauxhall street, Colombo 02","K C Subasinghe, K D Weerasinghe, D P Gamlath","Rs.14,500,000"
33,,,,,provider for the export market,(PV 1265),Tel. 2475308,,100%
34,,,,,,Sri Lanka,,,
35,,,,John Keells Holdings PLC,Group holding company & function,1979,"No.117,Sir Chittampalam A Gardiner Mawatha,","K N J Balendra - Chairperson, J G A Cooray - D...","Rs.90,602,453,241"
36,,,,,based services,(PQ 14),Colombo - 02,"D A Cabraal ,A N Fonseka, S S H Wijayasuriya, ...",99.24%
37,,,,,,Sri Lanka,Tel. 2306000,D V R S Fernando,
38,,,,John Keells International (Pvt) Ltd *,Regional holding company providing,2006,"No.117,Chittampalam A,Gardiner Mawatha,","D P Gamlath, K M Thanthirige, N W Tambiah","Rs.1,991,600,000"
39,,Other,,,administrative & function based,(PV 46),Colombo - 02,,100%
40,,,,,services,Sri Lanka,Tel. 2306000 /2421101-9,,
41,,,,John Keells Singapore (Pte) Ltd *,International trading services,1992,"No.16 Collyer Quay, Level 21, Office Suit No.2...","J G A Cooray - Chairperson, K M Thanthirige, K...","Rs.9,638,000"
42,,,,,,(199200499C),Singapore 049318,"D P Gamlath, R Ponnampalam",80%
43,,,,,,Singapore,Tel. 65 63296409/ 65 68189150/ 65 96346593,,
44,,,,Keells Consultants (Pvt) Ltd,Company secretarial services to the,1974,"No.117,Chittampalam A,Gardiner Mawatha,","K M Thanthirige, N W Tambiah, I V Gunasekera","Rs.160,000"
45,,,,,group,(PB3 / PV),Colombo - 02,,100%
46,,,,,,Sri Lanka,Tel. 2421101-9,,
47,,,,Mortlake (Pvt) Ltd *,Investment company,1962,"No. 148, Vauxhall Street,Colombo 2.","K M Thanthirige, K C Subasinghe","Rs.5,500"
48,,,,,,(PV 756),Tel. 2475308,,100%
49,,,,,,Sri Lanka,,,

Table 162:

,0,1,2,3,4,5,6,7,8
0,Industry,Sector,Segment/,Company Name,Nature,Incorporated Year & Country,Addresses,Directors,Stated Capital &
1,Group,,Business,,,,,,Effective Holding
2,,,,John Keells Information,IT Consultancy & Professional Service,1998,"No. 148, Vauxhall Street,Colombo 2.","J G A Cooray - Chairperson, K D Weerasinghe, R...","Rs.96,500,000"
3,,,IT Services,Technology (Pvt) Ltd,,(PV 652),Tel. 2300770-77,,100%
4,,,,,,Sri Lanka,,,
5,,,,Infomate (Pvt) Ltd,IT enabled services,2005,"No.4, Leyden Bastian Road, Colombo 1","K D Weerasinghe, R Shanmuganathan","Rs.20,000,000"
6,,,,,,(PV 921),Tel. (94) 112149700,,100%
7,,,,,,Sri Lanka,,,
8,,,,John Keells BPO Holdings Private,Holding company of BPO group,2006,"IFS Court, 28, Cybercity, Ebene,Mauritius","Z H Niamut, K Peerbocus, K D Weerasinghe","Rs.1,988,300,000"
9,,Information Technology,,Ltd *,companies,(C 60882),Tel. (230) 467 3000,,100%
10,,,IT Enabled,,,Mauritius,,,
11,,,Services,John Keells BPO International (Pvt),Investment holding company,2007,"IFS Court, 28, Cybercity,Ebene, Mauritius","Z H Niamut, K Peerbocus, K D Weerasinghe","Rs.1,616,700,008"
12,,,,Ltd *,,(C 070137),Tel. (230) 467 3000,,100%
13,,,,,,Mauritius,,,
14,,,,John Keells BPO Solutions Lanka,BPO operations in Sri Lanka,2006,"No.4, Leyden Bastian Road, Colombo 1","K D Weerasinghe, R Shanmuganathan","Rs.335,797,260"
15,,,,(Pvt) Ltd*,,(PV 3458),Tel. (94) 2300770-77,,100%
16,,,,,,Sri Lanka,,,
17,,,,John Keells PLC,Produce Broking and Real Estate,1960,"No. 186, Vauxhall street, Colombo 02","K N J Balendra - Chairperson, J G A Cooray, K ...","Rs.152,000,000"
18,,,,,Ownership,(PQ 11),Tel. 2306000,"A K Gunawardhana, C N Wijewardene, B A I Rajak...",86.90%
19,,,,,,Sri Lanka,,,
20,,,,John Keells Teas (Pvt) Ltd,Manager seven bought leaf tea,1979,"No.117,Chittampalam A,Gardiner Mawatha,","K D Weerasinghe, K C Subasinghe, A Z Hashim","Rs.120,000"
21,,,,,factories,(PV 522),Colombo - 02,,100%
22,,Plantation Services,,,,Sri Lanka,Tel. 2306546,,
23,,,,John Keells Warehousing (Pvt) Ltd,Warehousing of Tea and Rubber,2001,"No.93,1st Avenue, Muturajawela, Hendala, Wattala","K D Weerasinghe, K C Subasinghe, A Z Hashim","Rs.120,000,000"
24,,,,,,(PV 638),Tel. 4819560,,86.90%
25,"OTHER, INCLUDING INFORMATION TECHNOLOGY AND PL...",,,,,Sri Lanka,,,
26,,,,Tea Smallholder Factories PLC,Owner and operator of Bought Leaf,1991,"No.186, Vauxhall street, Colombo 02","K N J Balendra – Chairperson, J G A Cooray, E ...","Rs.150,000,000"
27,,,,,factories,(PQ 32),Tel. 2149994 / 2335880,"A S Jayatilleke, S K L Obeyesekere, A K Gunara...",37.62%
28,,,,,,Sri Lanka,,A Z Hashim,
29,,,,Facets (Pvt) Ltd *,Owner of real estate,1974,"No.117,Sir Chittampalam A Gardiner Mawatha","K M Thanthirige, D P Gamlath","Rs.150,000"
30,,,,,,(PV 1048),",Colombo - 02",,100%
31,,,,,,Sri Lanka,Tel. 2306000,,
32,,,,J K Packaging (Pvt) Ltd*,Printing and packaging services,1979,"No 148, Vauxhall street, Colombo 02","K C Subasinghe, K D Weerasinghe, D P Gamlath","Rs.14,500,000"
33,,,,,provider for the export market,(PV 1265),Tel. 2475308,,100%
34,,,,,,Sri Lanka,,,
35,,,,John Keells Holdings PLC,Group holding company & function,1979,"No.117,Sir Chittampalam A Gardiner Mawatha,","K N J Balendra - Chairperson, J G A Cooray - D...","Rs.90,602,453,241"
36,,,,,based services,(PQ 14),Colombo - 02,"D A Cabraal ,A N Fonseka, S S H Wijayasuriya, ...",99.24%
37,,,,,,Sri Lanka,Tel. 2306000,D V R S Fernando,
38,,,,John Keells International (Pvt) Ltd *,Regional holding company providing,2006,"No.117,Chittampalam A,Gardiner Mawatha,","D P Gamlath, K M Thanthirige, N W Tambiah","Rs.1,991,600,000"
39,,Other,,,administrative & function based,(PV 46),Colombo - 02,,100%
40,,,,,services,Sri Lanka,Tel. 2306000 /2421101-9,,
41,,,,John Keells Singapore (Pte) Ltd *,International trading services,1992,"No.16 Collyer Quay, Level 21, Office Suit No.2...","J G A Cooray - Chairperson, K M Thanthirige, K...","Rs.9,638,000"
42,,,,,,(199200499C),Singapore 049318,"D P Gamlath, R Ponnampalam",80%
43,,,,,,Singapore,Tel. 65 63296409/ 65 68189150/ 65 96346593,,
44,,,,Keells Consultants (Pvt) Ltd,Company secretarial services to the,1974,"No.117,Chittampalam A,Gardiner Mawatha,","K M Thanthirige, N W Tambiah, I V Gunasekera","Rs.160,000"
45,,,,,group,(PB3 / PV),Colombo - 02,,100%
46,,,,,,Sri Lanka,Tel. 2421101-9,,
47,,,,Mortlake (Pvt) Ltd *,Investment company,1962,"No. 148, Vauxhall Street,Colombo 2.","K M Thanthirige, K C Subasinghe","Rs.5,500"
48,,,,,,(PV 756),Tel. 2475308,,100%
49,,,,,,Sri Lanka,,,

In [5]:
# Initialize a list to store extracted data
data_for_csv = []

for i, table in enumerate(tables):
    # Convert all cells to lowercase and strip spaces
    table_lower = table.astype(str).map(lambda x: x.strip().lower())

    # Flag to track if a matching row was found
    found = False

    # Check each row
    for _, row in table_lower.iterrows():
        row_list = row.tolist()
        number_of_count = sum("number of" in cell for cell in row_list)
        percent_count = sum("%" in cell for cell in row_list)
    
        if number_of_count == 2 and percent_count == 2:
            print("Row has at least two 'number of' and two '%' entries")
            display(table)

            # Extract data starting from row 1 (assuming row 0 is header)
            share_holder_names = table.iloc[1:, 0].astype(str).str.strip().tolist()
            share_percentage = table.iloc[1:, 2].astype(str).str.strip().tolist()
            year = [2020] * len(share_holder_names)

            for name, percentage, yr in zip(share_holder_names, share_percentage, year):
                data_for_csv.append([yr, name, percentage])

            print(year)
            print(share_holder_names)
            print(share_percentage)
        

            found = True
            break  # stop checking more rows in the same table

# Save extracted data to CSV
df_csv = pd.DataFrame(data_for_csv, columns=["Year", "Shareholder Name", "Share Percentage"])
df_csv.to_csv("shareholder_data.csv", index=False, mode='a', header=False)

print("Data has been appended to 'shareholder_data.csv'")

Row has at least two 'number of' and two '%' entries

,0,1,2,3,4
0,Top Twenty Shareholders of the Company,,,,
1,,31 March 2024,,31 March 2023,
2,,Number of,%,Number of,%
3,,shares,,shares,
4,HWIC Asia Fund,"291,105,699",19.42,"119,200,760",8.61
5,Melstacorp PLC,"128,917,111",8.60,"128,917,111",9.31
6,Mr S E Captain,"122,615,194",8.18,"134,044,705",9.68
7,Paints & General Industries Limited,"87,021,832",5.81,"100,717,931",7.27
8,CIC Holdings PLC,"85,365,926",5.70,"35,338,032",2.55
9,Asian Development Bank,"65,042,006",4.34,"65,042,006",4.70
10,Schroder International Selection Fund,"44,418,290",2.96,"44,418,290",3.21
11,Aberdeen Standard Asia Focus PLC,"35,038,572",2.34,"33,398,572",2.41
12,Norges Bank Account 2,"33,087,774",2.21,"31,901,605",2.30
13,Polypak Secco Limited,"31,587,170",2.11,"14,937,924",1.08
14,Mr Kandiah Balendra,"19,511,476",1.30,"19,511,476",1.41
15,Mrs C S De Fonseka,"17,606,991",1.17,"17,606,991",1.27
16,Emrevival Master Fund LP,"15,983,048",1.07,-,-
17,Mrs S A J De Fonseka,"15,254,730",1.02,"15,204,230",1.10
18,Hostplus Pooled Superannuation Trust,"15,152,416",1.01,"10,393,158",0.75
19,Chemanex PLC,"15,064,515",1.01,"13,105,475",0.95
20,Edgbaston Asian Equity Trust,"14,209,110",0.95,"17,520,023",1.27
21,Employees Trust Fund Board,"12,989,299",0.87,"18,499,897",1.34
22,Sunsuper Superannuation Fund,"12,964,947",0.87,"11,587,196",0.84
23,Mr K N J Balendra,"10,907,628",0.73,"10,907,628",0.79

[2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020]
['', '', '', 'HWIC Asia Fund', 'Melstacorp PLC', 'Mr S E Captain', 'Paints & General Industries Limited', 'CIC Holdings PLC', 'Asian Development Bank', 'Schroder International Selection Fund', 'Aberdeen Standard Asia Focus PLC', 'Norges Bank Account 2', 'Polypak Secco Limited', 'Mr Kandiah Balendra', 'Mrs C S De Fonseka', 'Emrevival Master Fund LP', 'Mrs S A J De Fonseka', 'Hostplus Pooled Superannuation Trust', 'Chemanex PLC', 'Edgbaston Asian Equity Trust', 'Employees Trust Fund Board', 'Sunsuper Superannuation Fund', 'Mr K N J Balendra']
['', '%', '', '19.42', '8.60', '8.18', '5.81', '5.70', '4.34', '2.96', '2.34', '2.21', '2.11', '1.30', '1.17', '1.07', '1.02', '1.01', '1.01', '0.95', '0.87', '0.87', '0.73']
Data has been appended to 'shareholder_data.csv'