In [1]:
# Import necessary libraries
import camelot
import pandas as pd

In [2]:
# Define the extraction function
def extract_tables_from_pdf(file_path):
    """
    Extract useful financial tables (like income statements) from a PDF.
    We only scan page range 170-end to avoid unnecessary noise.
    """
    try:
        # Focus on financial statements pages
        tables = camelot.read_pdf(file_path, pages='170-end', flavor='stream')

        if tables.n == 0:
            print(f"No tables found in {file_path}")
            return []

        useful_tables = []
        keywords = ['total revenue', 'cost of sales', 'operating expenses', 'gross profit','earnings per share', 'net asset']

        for i, table in enumerate(tables):
            df = table.df
            # Flatten table text
            table_text = ' '.join(df.apply(lambda row: ' '.join(row), axis=1).tolist()).lower()

            if any(keyword in table_text for keyword in keywords):
                print(f"Selected table {i} (financial content detected)")
                useful_tables.append(df)
            else:
                print(f"Skipped table {i} (non-financial content)")

        if not useful_tables:
            print(f"No financial tables found in {file_path}")

    
        return useful_tables

    except Exception as e:
        print(f"Error extracting tables from {file_path}: {str(e)}")
        return []

In [3]:
# Now, in your Jupyter Notebook:
# Extract the tables from the PDF (replace 'your_pdf_file.pdf' with your actual file path)
file_path = '508_1653300092463.pdf'
tables = extract_tables_from_pdf(file_path)

C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (109.378, 478.37110000000024, 482.6092000000002, 685.148230952381)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (32.5197, 669.7071, 442.73684999999995, 841.9275521932515)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (32.5197, 663.2771499999999, 533.7208499999999, 841.3362696428571)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (40.8239, 188.11250000000004, 431.7512500000001, 289.098195754717)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.276, 841.89)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.276, 841.89)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)

Selected table 0 (financial content detected)
Selected table 1 (financial content detected)
Skipped table 2 (non-financial content)
Skipped table 3 (non-financial content)
Skipped table 4 (non-financial content)
Skipped table 5 (non-financial content)
Skipped table 6 (non-financial content)
Skipped table 7 (non-financial content)
Skipped table 8 (non-financial content)
Skipped table 9 (non-financial content)
Skipped table 10 (non-financial content)
Skipped table 11 (non-financial content)
Skipped table 12 (non-financial content)
Skipped table 13 (non-financial content)
Skipped table 14 (non-financial content)
Skipped table 15 (non-financial content)
Skipped table 16 (non-financial content)
Skipped table 17 (non-financial content)
Skipped table 18 (non-financial content)
Skipped table 19 (non-financial content)
Skipped table 20 (non-financial content)
Skipped table 21 (non-financial content)
Skipped table 22 (non-financial content)
Skipped table 23 (non-financial content)
Skipped table 24 (non-financial content)
Skipped table 25 (non-financial content)
Skipped table 26 (non-financial content)
Skipped table 27 (non-financial content)
Skipped table 28 (non-financial content)
Skipped table 29 (non-financial content)
Skipped table 30 (non-financial content)
Skipped table 31 (non-financial content)
Skipped table 32 (non-financial content)
Skipped table 33 (non-financial content)
Skipped table 34 (non-financial content)
Skipped table 35 (non-financial content)
Skipped table 36 (non-financial content)
Skipped table 37 (non-financial content)
Skipped table 38 (non-financial content)
Skipped table 39 (non-financial content)
Skipped table 40 (non-financial content)
Skipped table 41 (non-financial content)
Skipped table 42 (non-financial content)
Skipped table 43 (non-financial content)
Skipped table 44 (non-financial content)
Skipped table 45 (non-financial content)
Skipped table 46 (non-financial content)
Skipped table 47 (non-financial content)
Skipped table 48 (non-financial content)
Skipped table 49 (non-financial content)
Skipped table 50 (non-financial content)
Skipped table 51 (non-financial content)
Selected table 52 (financial content detected)
Skipped table 53 (non-financial content)
Skipped table 54 (non-financial content)
Skipped table 55 (non-financial content)
Skipped table 56 (non-financial content)
Skipped table 57 (non-financial content)
Skipped table 58 (non-financial content)
Skipped table 59 (non-financial content)
Skipped table 60 (non-financial content)
Skipped table 61 (non-financial content)
Skipped table 62 (non-financial content)
Skipped table 63 (non-financial content)
Selected table 64 (financial content detected)
Skipped table 65 (non-financial content)
Skipped table 66 (non-financial content)
Skipped table 67 (non-financial content)
Skipped table 68 (non-financial content)
Skipped table 69 (non-financial content)
Skipped table 70 (non-financial content)
Skipped table 71 (non-financial content)
Skipped table 72 (non-financial content)
Skipped table 73 (non-financial content)
Skipped table 74 (non-financial content)
Skipped table 75 (non-financial content)
Skipped table 76 (non-financial content)
Skipped table 77 (non-financial content)
Skipped table 78 (non-financial content)
Skipped table 79 (non-financial content)
Skipped table 80 (non-financial content)
Skipped table 81 (non-financial content)
Selected table 82 (financial content detected)
Skipped table 83 (non-financial content)
Selected table 84 (financial content detected)
Skipped table 85 (non-financial content)
Skipped table 86 (non-financial content)
Skipped table 87 (non-financial content)
Skipped table 88 (non-financial content)
Skipped table 89 (non-financial content)
Skipped table 90 (non-financial content)
Skipped table 91 (non-financial content)
Skipped table 92 (non-financial content)
Skipped table 93 (non-financial content)
Skipped table 94 (non-financial content)
Skipped table 95 (non-financial content)
Skipped table 96 (non-financial content)
Skipped table 97 (non-financial content)
Skipped table 98 (non-financial content)
Skipped table 99 (non-financial content)
Skipped table 100 (non-financial content)
Skipped table 101 (non-financial content)
Skipped table 102 (non-financial content)
Skipped table 103 (non-financial content)
Skipped table 104 (non-financial content)
Skipped table 105 (non-financial content)
Selected table 106 (financial content detected)
Skipped table 107 (non-financial content)
Selected table 108 (financial content detected)
Selected table 109 (financial content detected)
Selected table 110 (financial content detected)
Selected table 111 (financial content detected)
Skipped table 112 (non-financial content)
Skipped table 113 (non-financial content)
Skipped table 114 (non-financial content)
Skipped table 115 (non-financial content)
Skipped table 116 (non-financial content)
Skipped table 117 (non-financial content)
Skipped table 118 (non-financial content)
Skipped table 119 (non-financial content)
Skipped table 120 (non-financial content)
Skipped table 121 (non-financial content)
Skipped table 122 (non-financial content)
Skipped table 123 (non-financial content)
Skipped table 124 (non-financial content)
Skipped table 125 (non-financial content)
Skipped table 126 (non-financial content)
Skipped table 127 (non-financial content)
Skipped table 128 (non-financial content)
Skipped table 129 (non-financial content)
Skipped table 130 (non-financial content)
Skipped table 131 (non-financial content)
Skipped table 132 (non-financial content)
Skipped table 133 (non-financial content)
Skipped table 134 (non-financial content)
Skipped table 135 (non-financial content)
Skipped table 136 (non-financial content)
Skipped table 137 (non-financial content)
Skipped table 138 (non-financial content)
Skipped table 139 (non-financial content)
Skipped table 140 (non-financial content)
Skipped table 141 (non-financial content)
Selected table 142 (financial content detected)
Skipped table 143 (non-financial content)
Skipped table 144 (non-financial content)
Skipped table 145 (non-financial content)
Selected table 146 (financial content detected)
Skipped table 147 (non-financial content)
Skipped table 148 (non-financial content)
Skipped table 149 (non-financial content)
Selected table 150 (financial content detected)
Skipped table 151 (non-financial content)
Skipped table 152 (non-financial content)
Skipped table 153 (non-financial content)
Skipped table 154 (non-financial content)
Skipped table 155 (non-financial content)
Selected table 156 (financial content detected)
Skipped table 157 (non-financial content)
Skipped table 158 (non-financial content)
Skipped table 159 (non-financial content)
Skipped table 160 (non-financial content)
Skipped table 161 (non-financial content)
Skipped table 162 (non-financial content)
Skipped table 163 (non-financial content)
Skipped table 164 (non-financial content)
Skipped table 165 (non-financial content)
Skipped table 166 (non-financial content)
Skipped table 167 (non-financial content)
Skipped table 168 (non-financial content)
Skipped table 169 (non-financial content)
Skipped table 170 (non-financial content)
Skipped table 171 (non-financial content)
Skipped table 172 (non-financial content)
Skipped table 173 (non-financial content)
Selected table 174 (financial content detected)
Skipped table 175 (non-financial content)
Skipped table 176 (non-financial content)
Selected table 177 (financial content detected)
Skipped table 178 (non-financial content)
Skipped table 179 (non-financial content)
Skipped table 180 (non-financial content)
Selected table 181 (financial content detected)
Skipped table 182 (non-financial content)
Skipped table 183 (non-financial content)
Skipped table 184 (non-financial content)
Skipped table 185 (non-financial content)
Skipped table 186 (non-financial content)
Skipped table 187 (non-financial content)
Skipped table 188 (non-financial content)
Skipped table 189 (non-financial content)
Skipped table 190 (non-financial content)
Skipped table 191 (non-financial content)
Skipped table 192 (non-financial content)
Skipped table 193 (non-financial content)
Skipped table 194 (non-financial content)
Skipped table 195 (non-financial content)
Skipped table 196 (non-financial content)
Skipped table 197 (non-financial content)
Skipped table 198 (non-financial content)
Skipped table 199 (non-financial content)
Skipped table 200 (non-financial content)
Skipped table 201 (non-financial content)
Skipped table 202 (non-financial content)
Skipped table 203 (non-financial content)
Skipped table 204 (non-financial content)
Skipped table 205 (non-financial content)
Skipped table 206 (non-financial content)
Skipped table 207 (non-financial content)
Skipped table 208 (non-financial content)
Skipped table 209 (non-financial content)
Skipped table 210 (non-financial content)
Skipped table 211 (non-financial content)

In [4]:
# Show each table in a DataFrame
if tables:
    for i, table in enumerate(tables):
        print(f"Table {i + 1}:")
        display(table)  # This will display the table in a Jupyter notebook cell
else:
    print("No tables to display.")

Table 1:

,0,1,2,3,4
0,Share Information,,,,
1,Earnings Per Share,,,,
2,,,Market Capitalisation and Enterprise Value,,
3,The fully diluted earnings per share (EPS) for...,(Rs.bn),,,
4,by 318.0 per cent to Rs.15.12 per share [2020/...,,,,
5,,350,,,
6,increase in total profit attributable to equit...,,,,
7,,300,,,
8,"earnings basis, the diluted EPS increased to R...",,,,
9,,250,221,,
10,financial year from Rs.3.59 recorded in the pr...,,,206\n210,
11,representing a 324.9 per cent increase.,200,188,,152\n186
12,,150,,,
13,"However, it is noted that the benefit of highe...",,,,
14,,100,,,
15,partially offset through an increase in the is...,,,,
16,,50,,,
17,"Company in January 2022, in lieu of the privat...",,,,
18,,0,,,
19,"shares to ADB, as discussed above.",,,,
20,,,FY18,FY19,FY20

Table 2:

,0,1,2,3,4,5,6,7,8
0,,,,,,Summary Company Indicators,,,
1,Total Shareholder Return,,,,,,,,
2,,,,,,,2021/22,2020/21,2019/20
3,The total shareholder return (TSR) of the JKH ...,,,,,,,,
4,,,,,Market capitalisation,(Rs.billion),200.8,196.0,152.2
5,"for the period under review, while the total r...",,,,,,,,
6,,,,,Enterprise value,(Rs.billion),312.0,244.7,186.2
7,recorded a return of 11.2 per cent. On a cumul...,,,,,,,,
8,"holding period, the share inclusive of dividen...",,,,EV/EBITDA,(times),10.7,15.7,9.2
9,total return of 4.5 per cent.,,,,,,,,
10,,,,,Diluted EPS,(Rs.),15.1,3.6,7.1
11,,,,,PER,(diluted),9.6,41.0,16.2
12,Total Shareholder Return,,,,,,,,
13,(%),,,,,,,,
14,,,,,Price to book,(times),0.6,0.9,0.7
15,50,,,,Price/cash earnings,(times),4.7,13.2,10.7
16,40,,,,,,,,
17,,,,,Dividend yield,(%),1.0,1.0,3.0
18,,,30.0,,,,,,
19,30,27.5,,,,,,,
20,,,,24.6,,,,,
21,,,,,Group dividend,,,,
22,19.7,,,,,,,,
23,20,,,,,,,,
24,,,,26.3,payout ratio,(%),10.0,41.5,49.0
25,10,6.5,,,,,,,
26,,,,,Net assets per share,(Rs.),224.8,171.4,164.5
27,0,,,,,,,,
28,,,(2.8),(1.3),TSR,(%),(1.3),30.0,(23.8)
29,(10),,,,,,,,
30,(20),,,,,,,,

Table 3:

,0,1
0,Annual Report of the Board of Directors,
1,Capital Expenditure\nPrivate placement of ordi...,number of public shareholders are given in
2,The Company’s and Group’s capital \nIn Novembe...,the Share Information section of the Annual
3,"expenditure on property, plant and equipment \...",Report.
4,amounted to Rs.14 Mn (2021 - Rs.9 Mn) and \nor...,
...,...,...
106,,private companies which have not dispensed
107,Note 34.1 to the Financial Statements.,
108,"capitalisation, public holding percentage and",
109,,with the requirement to maintain an Interests
110,John Keells Holdings PLC | Annual Report 202...,

Table 4:

,0,1,2,3,4,5
0,For the year ended 31 March,Note,2022,2021,2022,2021
1,In Rs.'000s,,,,,
2,Continuing operations,,,,,
3,Revenue from contracts with customers,,"202,849,175","114,454,483","1,875,722","1,637,063"
4,Revenue from insurance contracts,,"15,225,571","13,221,167",-,-
5,Total revenue,14,"218,074,746","127,675,650","1,875,722","1,637,063"
6,Cost of sales,,"(180,430,008)","(108,747,058)","(1,085,049)","(957,490)"
7,Gross profit,,"37,644,738","18,928,592","790,673","679,573"
8,Dividend income,15,-,-,"8,007,649","8,346,260"
9,Other operating income,16.1,"2,614,793","2,626,544","51,344","40,610"
10,Selling and distribution expenses,,"(5,732,694)","(4,761,037)",-,-
11,Administrative expenses,,"(14,762,643)","(12,927,716)","(1,283,215)","(1,050,270)"
12,Other operating expenses,16.2,"(12,456,008)","(1,314,409)","(514,478)","(21,473)"
13,Results from operating activities,,"7,308,186","2,551,974","7,051,973","7,994,700"
14,Finance cost,17,"(7,034,757)","(4,669,206)","(2,966,139)","(1,244,941)"
15,Finance income,17,"30,806,179","10,688,722","24,198,282","4,617,329"
16,Change in insurance contract liabilities,36.2,"(6,416,299)","(7,031,692)",-,-
17,Change in fair value of investment property,24,"(4,084,755)","(253,425)",-,-
18,Share of results of equity accounted investees...,27.3,"6,745,939","4,158,793",-,-
19,Profit before tax,,"27,324,493","5,445,166","28,284,116","11,367,088"
20,Tax expense,21.1,"(6,881,586)","(1,494,275)","(3,902,709)","(801,201)"
21,Profit for the year,,"20,442,907","3,950,891","24,381,407","10,565,887"
22,Attributable to:,,,,,
23,Equity holders of the parent,,"20,212,968","4,772,100",,
24,Non-controlling interests,,"229,939","(821,209)",,
25,,,"20,442,907","3,950,891",,

Table 5:

,0,1
0,9. \n Basis of consolidation and material part...,Profit or loss and each component of other com...
1,subsidiaries,(OCI) are attributed to the equity holders of ...
2,Accounting policy,"and to the non-controlling interests, even if ..."
3,,controlling interests having a deficit balance...
4,Basis of consolidation,
5,,of the subsidiaries are prepared for the same ...
6,The consolidated financial statements comprise...,
7,,"parent Company, which is 12 months ending 31 M..."
8,statements of the Group and its subsidiaries a...,
9,,accounting policies.
10,period. Control over an investee is achieved w...,
11,"exposed, or has rights, to variable returns fr...",
12,,Transactions eliminated on consolidation
13,investee and has the ability to affect those r...,
14,,"All intra-group assets, liabilities, equity, i..."
15,over the investee.,
16,,flows relating to transactions between members...
17,,eliminated in full on consolidation. A change ...
18,Control over an investee,
19,,"of a subsidiary, without a loss of control, is..."
20,"Specifically, the Group controls an investee i...",
21,,transaction.
22,"• \nPower over the investee (i.e., existing ri...",
23,,Loss of control
24,ability to direct the relevant activities of t...,
25,,"If the Group loses control over a subsidiary, ..."
26,"• \nExposure, or rights, to variable returns f...","assets (including goodwill), liabilities, nonc..."
27,investee,components of equity while any resultant gain ...
28,,the income statement. Any investment retained ...
29,• \nThe ability to use its power over the inve...,
30,,value.
31,returns,
32,Consolidation of entities in which the Group h...,The total profits and losses for the year of t...
33,majority of voting rights,subsidiaries included in consolidation are sho...
34,,income statement and consolidated statement of...
35,When the Group has less than a majority of the...,
36,,income and all assets and liabilities of the C...
37,"of an investee, the Group considers all releva...",
38,,subsidiaries included in consolidation are sho...
39,in assessing whether it has power over an inve...,
40,,Statement of Financial Position.
41,• \nThe contractual arrangement with the other...,
42,investee;,Non-controlling interest (NCI)
43,,Non-controlling interest which represents the ...
44,• \nRights arising from other contractual arra...,
45,,"and net assets not held by the Group, are show..."
46,• \nThe Group’s voting rights and potential vo...,profit for the year in the consolidated income...
47,,of comprehensive income and as a component of ...
48,Subsidiaries that are consolidated have been l...,
49,,"consolidated statement of financial position, ..."
50,directory under Supplementary section of the a...,
51,,attributable to the shareholders of the parent.
52,"The following companies, with equity control e...",
53,,The Consolidated Statement of Cash Flow includ...
54,have been consolidated as subsidiaries based o...,
55,,Company and its subsidiaries.

Table 6:

,0,1,2,3,4
0,Names of material partly-owned subsidiaries an...,,,,"Accounting judgements,estimates and assumptions"
1,owned by non-controlling interest:,,,,Consolidation of entities in which the Group h...
2,,,,majority of voting right (de facto control).,
3,Material partly-owned subsidiary,2022,2021,,
4,,,,,The Group considers that it controls some subs...
...,...,...,...,...,...
67,,,,,asset or liability that is a financial instrum...
68,Yala Village (Pvt) Ltd,24.67%,24.67%,,
69,,,,,"SLFRS 9 Financial Instruments, is measured at ..."
70,,,,,in fair value recognised in the Income Stateme...
71,,,,SLFRS 9.,

Table 7:

,0,1
0,"115,182,320\n 71,088,127\n72,723,502\n 47,582,533",
1,"Notes to the Income Statement, Statement of Co...",Services transferred over time
2,Income and Statement of Financial Position,"Under SLFRS 15, the Group determines, at contr..."
3,14. \nRevenue,satisfies the performance obligation over time...
4,Accounting policy,each performance obligation satisfied over tim...
5,14.1 Total revenue,the revenue over time by measuring the progres...
6,14.1.1 Revenue from contract with customers,satisfaction of that performance obligation.
7,Revenue from contracts with customers is recog...,
8,the goods or services is transferred to the cu...,14.1.2 Revenue from insurance contracts
9,reflects the consideration to which the Group ...,Revenue from insurance contracts comprise of g...
10,exchange for those goods or services.,net of premium ceded to reinsurers.
11,Goods transferred at a point in time,14.2 Disaggregation of revenue
12,"Under SLFRS 15, revenue is recognised upon sat...",The Group presented disaggregated revenue with...
13,performance obligation. The revenue recognitio...,segments based on timing of revenue recognitio...
14,time when control of the asset is transferred ...,region in the operating segment information se...
15,on delivery of the goods.,

Table 8:

,0,1
0,Property,Others
1,Property segment concentrates primarily on pro...,Others represents companies in the Plantation ...
2,"renting of commercial office spaces,selling co...","Technology, Management and Investments compani..."
3,management of the Group’s real estate.,"streams of revenue; Management fees, BPO servi..."
4,,"fees, are recognised over a period of time, de..."
5,"At inception of the contract, the entity deter...",agreements.
6,the performance obligation over time or at a p...,
7,amount of cashflow will be determined accordin...,Some contracts include multiple deliverables. ...
8,,"include multiple performance obligations, the ..."
9,Financial Services,be allocated to each performance obligation ba...
10,Financial Services provides a complete range o...,alone selling prices. Where these are not dire...
11,"including commercial banking, insurance, stock...",estimated based on expected cost plus margin.
12,fund management and leasing. The services unde...,
13,identified as one performance obligation.,Remaining performance obligations
14,,The Group applies the practical expedient and ...
15,Entity determines at contract inception whethe...,amount of the transaction price allocated to t...
16,performance obligation over time or at a point...,obligations and an explanation of when the Gro...
17,"performance obligation satisfied overtime, the...",that amount as revenue for the year ended 31 M...
18,revenue over time by measuring the progress to...,
19,satisfaction of that performance obligation. T...,
20,provide a faithful depiction in recognising re...,
21,15. \nDividend income,
22,Accounting policy,
23,Dividend,
24,Dividend income is recognised when right to re...,
25,,COMPANY
26,For the year ended 31 March,2022\n2021
27,In Rs.‘000s,
28,Dividend income from investments in subsidiari...,"8,007,649\n 8,346,260"
29,16. \nOther operating income and other operat...,Gains and losses arising from activities incid...
30,Accounting policy,generating activities and those arising from a...
31,Gains and losses,"transactions, which are not material are aggre..."
32,Net gains and losses of a revenue nature arisi...,presented on a net basis.
33,"property, plant and equipment and other non-cu...",
34,,Any losses arising from guaranteed rentals are...
35,"investments in subsidiaries, joint ventures an...",
36,,year of incurring the same. A provision is rec...
37,"in the income statement, after deducting from ...",
38,,indicates a loss.
39,the carrying amount of such assets and the rel...,
40,,Other income and expenses

Table 9:

,0,1
0,Notes to the Financial Statements,
1,16. \nOther operating income and other operat...,
2,16.2 Other operating expenses,
3,,GROUP\nCOMPANY
4,For the year ended 31 March,2022\n2021\n2022\n2021
5,In Rs.'000s,
6,Provision for impairment,"4,886,733\n 69,660 \n 506,246 \n -"
7,"Loss on sale of property, plan and equipment","-\n6,005\n-\n-"
8,"Heat, light and power","800,684 \n 472,037 \n - \n -"
9,Exchange loss,"5,738,298 \n - \n - \n-"
10,Other overheads,"1,030,293\n 766,707 \n 8,232 \n 21,473"
11,,"12,456,008\n 1,314,409 \n 514,478 \n 21,473"
12,The Group has recognised Rs.4.7 Bn impairment ...,
13,investment.,
14,The Company has recognized Rs.506 Mn impairmen...,
15,17. \nNet finance income,Finance costs
16,Accounting policy,Finance costs comprise interest expense on bor...
17,Finance income,"the discount on provisions, losses on disposal..."
18,Finance income comprises of interest income on...,"financial assets, fair value losses on financi..."
19,"dividend income, gains on the disposal of fair...","profit or loss, impairment losses recognised o..."
20,"financial assets, fair value gains on financia...",than trade receivables) that are recognised in...
21,"profit or loss, gains on the remeasurement to ...",
22,existing interest in an acquiree that are reco...,Interest expense is recorded as it accrues usi...
23,statement.,"rate (EIR), which is the rate that exactly dis..."
24,,cash payments through the expected life of the...
25,Interest income is recorded as it accrues usin...,"a shorter period, where appropriate, to the ne..."
26,"rate (EIR), which is the rate that exactly dis...",financial liability.
27,cash receipts through the expected life of the...,
28,"a shorter period, where appropriate, to the ne...",Borrowing costs directly attributable to the a...
29,financial asset. Interest income is included i...,production of an asset that necessarily takes ...
30,income statement.,to get ready for its intended use or sale are ...
31,,of the respective assets. All other borrowing ...
32,,period they occur. Borrowing costs consist of ...
33,,that the Group incurs in connection with the b...

Table 10:

,0,1,2,3,4,5
0,,,GROUP,,COMPANY,
1,For the year ended 31 March,,2022,2021,2022,2021
2,In Rs.'000s,,,,,
3,Finance cost,,,,,
4,Interest expense on borrowings,,"(5,199,990)","(2,891,345)","(2,966,139)","(1,244,941)"
5,Finance charge on lease liabilities,,"(1,511,437)","(1,503,908)",-,-
6,Realised loss on financial assets at fair valu...,,-,"(273,953)",-,-
7,Unrealised loss on financial assets at fair va...,,"(323,330)",-,-,-
8,Total finance cost,,"(7,034,757)","(4,669,206)","(2,966,139)","(1,244,941)"
9,Net finance income,,"23,771,422","6,019,516","21,232,143","3,372,388"
10,18. \nProfit before tax,,For the purpose of presentation of the income ...,,,
11,Accounting policy,,"of expenses” method has been adopted, on the b...",,,
12,Expenditure recognition,,fairly the elements of the Company’s and Group...,,,
13,Expenses are recognised in the income statemen...,,,,,
14,direct association between the cost incurred a...,,,,,
15,items of income. All expenditure incurred in t...,,,,,
16,"and in maintaining the property, plant and equ...",,,,,
17,efficiency has been charged to the income stat...,,,,,
18,,,GROUP,,COMPANY,
19,For the year ended 31 March,,2022,2021,2022,2021
20,In Rs.'000s,,,,,
21,Profit before tax,,,,,
22,Profit before tax is stated after charging all...,,,,,
23,Remuneration to executive directors,,"391,034","346,453","106,238","103,808"
24,Remuneration to non executive directors,,"45,795","34,749","15,960","11,460"
25,Costs of defined employee benefits,,,,,
26,Defined benefit plan cost,,"400,450","438,382","22,766","21,709"
27,Defined contribution plan cost - EPF and ETF,,"1,182,147","1,068,968","72,880","56,332"
28,Other long term employee benefits cost,,"183,704","213,027","42,891","44,043"
29,Staff expenses,,"15,568,605","13,621,362","587,596","476,165"
30,Share based payments,,"204,618","225,007","61,117","66,035"
31,Auditors’ remuneration,,,,,
32,Audit,,"52,604","49,352","7,048","6,712"
33,Non-audit,,"10,733","6,202","4,565","1,018"
34,"Depreciation of property, plant and equipment",,"5,014,204","4,725,534","38,590","42,629"
35,Amortisation of intangible assets,,"703,906","641,563","33,324","30,631"
36,Amortisation of right of use assets,,"2,841,789","2,619,179",-,-
37,Provision for impairment,,"4,886,733","69,660","506,246",-
38,"(Gain) / Loss on sale of property, plant and e...",,"(62,198)","6,005","(2,532)",-
39,Donations,,"8,511","7,074","3,386","5,000"
40,19. \nEarnings per share,,parent (after adjusting for outstanding share ...,,,
41,,,average number of ordinary shares outstanding ...,,,
42,Accounting policy,,the weighted average number of ordinary shares...,,,
43,Basic EPS is calculated by dividing the profit...,,on conversion of all the dilutive potential or...,,,
44,ordinary equity holders of the parent by the w...,shares.,,,,
45,of ordinary shares outstanding during the year...,,,,,
46,by dividing the profit attributable to ordinar...,,,,,

Table 11:

,0,1,2,3,4,5
0,Notes to the Financial Statements,,,,,
1,19.1 Basic earnings per share,,,,,
2,,,,,GROUP,
3,For the year ended 31 March,,,Note,2022,2021
4,Profit attributable to equity holders of the p...,,,,"20,212,968","4,772,100"
5,Weighted average number of ordinary shares,,,19.3,"1,336,027","1,318,805"
6,Basic earnings per share,,,,15.13,3.62
7,19.2 Diluted earnings per share,,,,,
8,Profit attributable to equity holders of the p...,,,,"20,212,968","4,772,100"
9,Adjusted weighted average number of ordinary s...,,,19.3,"1,336,427","1,318,805"
10,Diluted earnings per share,,,,15.12,3.62
11,19.3 Amount used as denominator,,,,,
12,,,,,GROUP,
13,For the year ended 31 March,,,,2022,2021
14,Number of shares,,,,,
15,In '000s,,,,,
16,Ordinary shares at the beginning of the year,,,,"1,319,664","1,318,551"
17,Effect of share options exercised,,,,103,254
18,Private placement of ordinary shares,,,,"16,260",-
19,Weighted average number of ordinary shares in ...,,,,"1,336,027","1,318,805"
20,Effects of dilution from:,,,,,
21,Share option scheme,,,,400,-
22,Adjusted weighted average number of ordinary s...,,,,"1,336,427","1,318,805"
23,20. \nDividend per share,,,,,
24,,,,,COMPANY,
25,For the year ended 31 March,,,2022,,2021
26,,,Rs,In Rs.‘000s,Rs,In Rs.‘000s
27,Equity dividend on ordinary shares declared an...,,,,,
28,Final dividend (Previous years’ final dividend...,,0.50,,"659,869 \n-",-
29,Interim dividends,,1.00,"1,352,323",1.50,"1,978,317"
30,Total dividend,,1.50,"2,012,192",1.50,"1,978,317"
31,21. \nTaxes,,,,,
32,Accounting policy,,,,,
33,Current tax,,,,,
34,Current tax assets and liabilities for the cur...,,Management has used its judgment on the applic...,,,
35,measured at the amount expected to be recovere...,,including transfer pricing regulations involvi...,,,
36,the taxation authorities. The tax rates and ta...,,"associated undertakings, estimation of the res...",,,
37,the amount are those that are enacted or subst...,,and selection of appropriate pricing mechanisms.,,,
38,reporting date in the countries where the Grou...,,,,,
39,taxable income.,,The Group has complied with the arm’s length p...,,,
40,,,transfer pricing as prescribed in the Inland R...,,,
41,Current income tax relating to items recognise...,,,,,
42,recognised in equity and for items recognised ...,Deferred tax,,,,
43,income shall be recognised in other comprehens...,,Deferred tax is provided using the liability m...,,,
44,the income statement. Management periodically ...,,differences at the reporting date between the ...,,,
45,taken in the tax returns with respect to situa...,,liabilities and their carrying amounts for fin...,,,
46,tax regulations are subject to interpretation ...,,,,,
47,where appropriate.,,,,,

Table 12:

,0,1,2,3,4,5,6,7,8
0,As at/year ended 31 March,2022,2021,2022,2021,2022,2021,2022,2021
1,In Rs.‘000s,,,,,,,,
2,Group share of;,,,,,,,,
3,Revenue,"8,103,449","6,639,452","9,544,444","7,777,167","8,633,085","3,353,506","26,280,978","17,770,125"
4,Operating expenses including,"(4,360,150)","(4,171,084)","(6,530,011)","(4,925,057)","(7,194,726)","(2,993,364)","(18,084,887)","(12,089,505)"
5,cost of sales,,,,,,,,
6,Net finance income,"151,165","137,887","(45,422)","2,304","(107,069)","(71,809)","(1,326)","68,382"
7,Tax expense,"(491,854)","(420,612)","(579,322)","(1,098,006)","(377,650)","(71,591)","(1,448,826)","(1,590,209)"
8,Share of results of equity,"3,402,610","2,185,643","2,389,689","1,756,408","953,640","216,742","6,745,939","4,158,793"
9,accounted investees,,,,,,,,
10,Other comprehensive income,"4,448,407","381,701","(466,783)","(121,007)","(3,033)","2,525","3,978,591","263,219"
11,Total Comprehensive Income,"7,851,017","2,567,344","1,922,906","1,635,401","950,607","219,267","10,724,530","4,422,012"
12,Group share of;,,,,,,,,
13,Total assets,"16,226,919","10,429,627","169,020,223","123,638,695","12,522,508","6,912,727","197,769,650","140,981,049"
14,Total liabilities,"(5,230,466)","(3,921,435)","(149,888,167)","(108,995,412)","(8,964,620)",,"(4,287,703) (164,083,253) (117,204,550)",
15,Net assets,"10,996,453","6,508,192","19,132,056","14,643,283","3,557,888","2,625,024","33,686,397","23,776,499"
16,Goodwill,-,"4,674,278","165,899","165,899","13,260","13,260","179,159","4,853,437"
17,,"10,996,453","11,182,470","19,297,955","14,809,182","3,571,148","2,638,284","33,865,556","28,629,936"
18,Capital commitments,-,-,-,"142,202","4,019,277","5,776,691","4,019,277","5,918,893"
19,Other commitments and,-,-,"78,043,531","54,475,196",-,-,"78,043,531","54,475,196"
20,Guarantees,,,,,,,,

Table 13:

,0,1,2,3
0,28.4 Loans to life policyholders,,,
1,,,GROUP,
2,As at 31 March,,2022,2021
3,In Rs.'000s,,,
4,At the beginning of the year,,"1,840,841","1,627,555"
5,Loans granted / transfers,,"878,410","885,798"
6,Recoveries,,"(766,857)","(672,512)"
7,At the end of the year,,"1,952,394","1,840,841"
8,29. \nOther non current assets,,,
9,,GROUP,COMPANY,
10,As at 31 March,2022\n2021\nNote,2022,2021
11,In Rs.'000s,,,
12,Pre paid cost,"282,339 \n341,600","119,755","92,668"
13,Work-in-progress - Waterfront project,"29.1\n 179,669,639 \n 103,260,711",-,-
14,Non current advances,"968,001 \n977,904",-,-
15,,"180,919,979 \n 104,580,215","119,755","92,668"
16,29.1 Work-in-progress - Waterfront project,,,
17,,,GROUP,
18,As at 31 March,,2022,2021
19,In Rs.'000s,,,
20,Freehold property*,,"19,345,604","12,703,071"
21,Leasehold property*,,"7,584,983","5,106,604"
22,Other constructions in progress,,"152,739,052","82,275,284"
23,Contractor advances,,-,"3,175,752"
24,,,"179,669,639","103,260,711"
25,* The freehold and leasehold property are loca...,,,
26,,Other non current assets represents the constr...,,
27,,and oth er project cost incurred. Freehold lan...,,
28,,prepayment made to obtaining the lease land ri...,,
29,incurred on the project and borrowing cost cap...,,,
30,,,"During the year ended 31 March 2022, Rs.57 Mn ...",
31,30. \nInventories,,,
32,,,recognised as an expense for inventories carri...,
33,Accounting policy,,,
34,,,This is recognised in cost of sales and other ...,
35,Inventories are valued at the lower of cost an...,,,
36,realisable value is the estimated selling pric...,,,
37,,,GROUP,
38,completion and the estimated costs necessary t...,,,
39,,As at 31 March,2022,2021
40,The costs incurred in bringing inventories to ...,,,
41,,In Rs.'000s,,
42,"condition, are accounted for as follows:",,,
43,,Inventories,,
44,• \nRaw materials - On a weighted average basis,,,
45,,Raw materials,"1,353,492","628,872"
46,• \nFinished goods and work-in-progress - At t...,,,
47,,Finished goods,"12,581,519","7,391,309"
48,direct labour and an appropriate proportion of...,,,
49,,Produce stocks,"241,284","253,605"
50,overheads based on normal operating capacity b...,,,
51,borrowing costs,Other stocks,"3,028,486","2,168,124"
52,,Apartments and commercial space,"19,020,106","43,854,213"
53,• Other inventories – At actual cost,,,
54,,,"36,224,887","54,296,123"

Table 14:

,0,1
0,35. \nShare-based payment plans,Where the terms of an equity-settled transacti...
1,Accounting Policy,the minimum expense recognised is the expense ...
2,Employee share option plan - Equity-settled tr...,"been modified, if the original terms of the aw..."
3,Employees of the Group receive remuneration in...,expense is recognised for any modification tha...
4,"based payment transactions, whereby employees ...","value of the share-based payment transaction, ..."
5,consideration for equity instruments (equity-s...,to the employee as measured at the date of mod...
6,The Group applies SLFRS 2 Share Based Payments...,The dilutive effect of outstanding options is ...
7,employee remuneration in the form of shares fr...,dilution in the computation of diluted earning...
8,,are given in Note 19.2).
9,The cost of equity-settled transactions is rec...,
10,a corresponding increase in other capital rese...,Employee share option scheme
11,period in which the performance and service co...,Under the John Keells Group’s Employees share ...
12,The cumulative expense recognised for equity-s...,share options of the parent are granted to exe...
13,each reporting date until the vesting date ref...,generally with more than 12 months of service....
14,the vesting period has expired and the Group’s...,share options is equal to the 30 days volume w...
15,number of equity instruments that will ultimat...,price of the underlying shares on the date of ...
16,credit to the income statement for a period re...,vest over a period of four years and is depend...
17,in cumulative expense recognised as at the beg...,criteria and a service criteria. The performan...
18,period and is recognised in employee benefits ...,performance achievement of “Met Expectations” ...
19,,being that the employee has to be in employmen...
20,No expense is recognised for awards that do no...,options vest. The fair value of the share opti...
21,except for equity-settled transactions where v...,"date using a binomial option pricing model, ta..."
22,"upon a market or non-vesting condition, which ...",terms and conditions upon which the share opti...
23,irrespective of whether or not the market or n...,
24,"satisfied, provided that all other performance...",The contractual term for each option granted i...
25,satisfied.,cash settlement alternatives. The Group does n...
26,,cash settlement for these share options.
27,Share-based payment plans,
28,,GROUP\nCOMPANY
29,For the year ended 31 March,2022\n2021\n2022\n2021
30,In Rs.'000s,
31,Total expense arising from share-based payment...,"204,618\n225,007\n 61,117\n 66,035"
32,Movements in the year,
33,The following table illustrates the number (No...,
34,GROUP,COMPANY
35,2022\nAs at 31 March,2021\n2022\n2021
36,No.\nWAEP,No.\nWAEP\nNo.\nWAEP\nNo.\nWAEP
37,Outstanding at the beginning of the year \n 38...,"41,563,469 \n 152.67 \n 12,771,300 \n 150.82 \..."
38,"Granted during the year\n6,585,800\n136.64","6,557,100 \n 132.86 \n2,017,300\n136.64\n 1,81..."
39,Transfers\n-\n-,"-\n-\n-\n-\n (56,195)\n159.13"
40,"Exercised during the year\n(210,675)\n137.28","(1,113,183)\n 142.81 \n-\n-\n (363,100)\n142.83"
41,"Expired during the year\n(7,633,609)\n143.93","(8,960,243)\n 150.47 \n(2,700,363)\n143.06 \n ..."
42,"Outstanding at the end of the year\n36,788,659...","38,047,143 \n 150.06 \n12,088,237 \n150.18\n 1..."
43,"Exercisable at the end of the year\n21,929,305...","22,717,896 \n 155.17 \n7,412,529 \n158.31\n 8,..."

Table 15:

,0,1
0,Liability adequacy test (LAT) - Life insurance...,36.2 Change in life insurance contract liabi...
1,"As at 31 December 2021, liability adequacy tes...",The results of Union Assurance PLC’s (UA) life...
2,"appointed actuary Mr. Vivek Jalan FIA, FIAI of...",consolidated into the Group’s Consolidated Inc...
3,"Private Limited who concluded that, the liabil...",change in life insurance contract liabilities ...
4,"meet future benefits and expenses. Hence, no p...","the Life Fund, the difference between all inco..."
5,be made for any premium deficiency.,attributable to life policy holders during the...
6,Summarised financial information,
7,For the year ended 31 March,2022\n2021
8,In Rs.'000s,
9,Total Revenue,"15,225,571 \n 13,221,167"
10,Cost of sales,"(7,829,465)\n (6,168,801)"
11,Gross profit,"7,396,106 \n 7,052,366"
12,Operating expenses including distribution and ...,"(4,377,144)\n (4,192,748)"
13,Net finance income,"5,281,652 \n 5,023,000"
14,Profit attributable to shareholders of UA,"(1,884,315)\n (850,926)"
15,Change in insurance contract liabilities,"6,416,299 \n 7,031,692"
16,Union Assurance PLC follows a risk mitigation ...,
17,liabilities.,
18,The following table describes headline risks a...,
19,Headline risk,Risk response
20,Investment return on underlying items failing ...,Management discretion to determine amount and ...
21,rates,holders bonuses (within limits)
22,Insufficient fees to cover cost of guarantees ...,Hedging programme
23,Differences in duration and yield of assets an...,• Matching of assets and liabilities cash flows
24,,• Investing in investment grade assets
25,Policy holder behavioural risk,Surrender penalty
26,37. \nInterest-bearing loans and borrowings,
27,37.1 Movement,
28,,GROUP\nCOMPANY
29,As at 31 March,2022\n2021\n2022\n2021
30,In Rs.'000s,
31,At the beginning of the year,"128,473,113 \n 56,131,366 \n 47,186,858 \n 605..."
32,Cash movement,
33,Loans obtained,"53,876,802 \n 71,729,856 \n 3,000,000 \n 43,88..."
34,Repayments,"(34,946,688)\n(6,753,731)\n (1,474,806)\n (540..."
35,Non cash movement,
36,Accrued Interest,"948,393 \n 1,138,330 \n134,057\n 428,650"
37,Exchange differences,"51,194,726 \n6,227,292\n 18,350,918 \n 2,803,320"
38,At the end of the year,"199,546,346 \n 128,473,113 \n 67,197,027 \n 47..."
39,Repayable within one year,"40,624,448\n 9,507,473 \n 2,562,994 \n 3,007,368"
40,Repayable after one year,"158,921,898\n 118,965,640 \n 64,634,033 \n 44,..."
41,,"199,546,346 \n 128,473,113 \n 67,197,027 \n 47..."

Table 16:

,0,1,2,3,4,5,6,7,8,9,10
0,31 March,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013
1,Rs. Mn,,,,,,,,,,
2,OPERATING RESULTS,,,,,,,,,,
3,Group revenue,"218,075","127,676","138,956","135,456","121,215","106,273","93,710","91,852","86,706","85,408"
4,EBIT,"34,359","7,931","15,508","20,198","28,155","23,324","20,192","19,226","16,537","16,677"
5,Finance cost,"(7,035)","(4,669)","(3,166)","(2,722)",(521),(436),(994),(668),"(1,217)","(1,081)"
6,Share of results of equity accounted,"6,746","4,159","4,466","4,727","3,596","3,303","2,781","2,778","3,089","3,440"
7,investees (net of tax),,,,,,,,,,
8,Profit before tax,"27,324","5,445","12,403","18,616","27,634","22,888","19,198","18,557","15,320","15,595"
9,Tax expense,"(6,882)","(1,494)","(2,662)","(2,378)","(4,515)","(4,771)","(3,406)","(2,812)","(2,362)","(2,162)"
10,Profit after tax,"20,443","3,951","9,741","16,237","23,120","18,117","15,792","15,745","12,958","13,433"
11,Attributable to:,,,,,,,,,,
12,Equity holders of the parent,"20,213","4,772","9,414","15,254","21,021","16,275","14,070","14,348","11,721","12,113"
13,Non-controlling interests,230,(821),327,983,"2,099","1,842","1,722","1,397","1,237","1,320"
14,,"20,443","3,951","9,741","16,237","23,120","18,117","15,792","15,745","12,958","13,433"
15,CAPITAL EMPLOYED,,,,,,,,,,
16,Stated capital,"73,188","63,102","62,881","62,806","62,802","62,790","58,702","50,703","49,749","26,480"
17,Capital reserves and other components,"129,011","72,403","66,085","58,646","49,852","38,652","28,715","24,501","21,845","20,635"
18,of equity,,,,,,,,,,
19,Revenue reserves,"109,087","90,652","87,885","82,834","87,266","77,193","67,565","62,594","51,304","42,704"
20,,"311,286","226,157","216,851","204,286","199,920","178,635","154,982","137,798","122,898","89,819"
21,Non-controlling interest,"18,805","16,830","26,872","26,072","24,944","15,696","13,499","12,279","11,421","11,152"
22,Total equity,"330,091","242,987","243,723","230,358","224,864","194,331","168,481","150,077","134,319","100,971"
23,Total debt,"268,228","172,904","100,907","54,513","29,722","22,766","20,750","23,934","26,139","20,107"
24,,"598,319","415,891","344,630","284,871","254,586","217,097","189,231","174,011","160,458","121,078"
25,ASSETS EMPLOYED,,,,,,,,,,
26,"Property, plant and equipment (PP&E)","124,348","113,077","111,534","97,688","87,260","64,396","52,737","49,563","47,406","49,200"
27,Non-current assets other than PP&E,"354,518","257,226","204,360","170,687","136,427","107,912","93,376","78,030","71,969","59,787"
28,Current assets,"238,929","166,491","121,050","95,421","98,762","104,964","94,863","90,493","82,206","49,934"
29,Liabilities net of debt,"(119,476)","(120,903)","(92,314)","(78,925)","(67,862)","(60,175)","(51,745)","(44,075)","(41,123)","(37,843)"
30,,"598,319","415,891","344,630","284,871","254,587","217,097","189,231","174,011","160,458","121,078"
31,CASH FLOW,,,,,,,,,,
32,Net cash flows from operating activities,"30,440","13,825","(10,350)","(4,743)","16,012","21,020","20,513","20,855","8,041","14,568"
33,Net cash flows from / (used in) investing,"39,363","(44,944)","(27,039)","(8,452)","(16,640)","(17,670)","(9,567)","(1,255)","(19,710)","(16,199)"
34,activities,,,,,,,,,,
35,Net cash flows from / (used in) financing,"31,693","55,427","18,431","(11,000)","(4,587)","(4,105)","(7,717)","(4,838)","25,446","(1,320)"
36,activities,,,,,,,,,,
37,Net increase / (decrease) in cash and cash,"101,495","24,308","(18,959)","(14,709)","(5,215)",(755),"3,229","14,762","13,777","(2,951)"
38,equivalents,,,,,,,,,,
39,KEY INDICATORS,,,,,,,,,,
40,Basic earnings per share (Rs.),15.13,3.62,7.14,11.13,15.2,11.9,10.5,12.6,10.5,10.7
41,Interest cover (no. of times),4.9,1.7,4.9,7.8,54,52.8,51.5,27.7,13.6,15.4
42,Net assets per share* (Rs.),224.8,163.3,156.6,147.5,144.4,129.0,111.9,99.5,88.7,64.9
43,Enterprise value (EV),"311,951","244,679","186,236","210,020","187,926",136.022,"124,182","155,675","124,182","203,615"
44,EV / EBITDA,10.7,15.7,9.2,8.5,5.8,5.0,5.0,6.6,10.0,10.0
45,ROE (%),7.5,2.2,4.5,7.5,11.1,9.8,9.6,11.0,11.0,15.0
46,Debt / equity ratio (%),81.3,71.2,41.4,23.7,13.2,11.7,12.3,15.9,19.5,19.9
47,Net debt excl. leases (cash)/Equity (%),23.5,20.0,14.0,1.9,(14.9),(28.5),(30.8),(28.8),(23.2),(8.0)
48,Dividend payout (Rs.Mn),"2,012","1,978","4,614","8,186","8,325","7,280","8,038","3,476","3,267","2,982"
49,Current ratio (no. of times),1.8,2.3,2.1,1.7,3.0,3.7,4.0,2.6,2.4,2.0
50,Market price per share unadjusted (Rs.),145.0,148.5,115.4,156.0,159.6,137.9,148.0,199.4,227.0,247.0
51,Market price per share diluted (Rs.),145.0,148.5,115.4,156.0,159.6,137.9,129.5,152.7,173.8,238.2
52,Revenue growth rate (%),70.8,(8.1),2.6,11.8,14.1,13.4,1.6,5.9,4.1,9.7
53,USD closing rate (Rs.),305.0,200.3,189.6,175.5,155.9,151.9,147.7,133.5,130.7,126.8
54,USD average rate (Rs.),208.3,189.0,179.4,168.6,153.6,148.0,139.2,131.2,130.1,129.9

Table 17:

,0,1,2,3,4
0,In USD '000s,,,,
1,Continuing operations,,,,
2,Revenue from contracts with customers,"665,079","571,415","6,150","8,173"
3,Revenue from Insurance Contracts,"49,920","66,007",-,-
4,Total Revenue,"714,999","637,422","6,150","8,173"
5,Cost of sales,"(591,574)","(542,921)","(3,558)","(4,780)"
6,Gross profit,"123,425","94,501","2,592","3,393"
7,Dividend income,-,-,"26,255","41,669"
8,Other operating income,"8,573","13,113",168,203
9,Selling and distribution expenses,"(18,796)","(23,770)",-,-
10,Administrative expenses,"(48,402)","(64,542)","(4,207)","(5,243)"
11,Other operating expenses,"(40,839)","(6,562)","(1,687)",(107)
12,Results from operating activities,"23,961","12,740","23,121","39,915"
13,Finance cost,"(23,065)","(23,311)","(9,725)","(6,215)"
14,Finance income,"101,004","53,364","79,339","23,052"
15,Change in insurance contract liabilities,"(21,037)","(35,106)",-,-
16,Change in fair value of investment property,"(13,393)","(1,265)",-,-
17,Share of results of equity accounted investees...,"22,118","20,763",-,-
18,Profit before tax,"89,588","27,185","92,735","56,752"
19,Tax expense,"(22,563)","(7,460)","(12,782)","(4,000)"
20,Profit for the year,"67,025","19,725","79,953","52,752"
21,Attributable to:,,,,
22,Equity holders of the parent,"66,272","23,825",,
23,Non-controlling interests,753,"(4,100)",,

Table 18:

,0,1,2
0,Glossary,,
1,ACCRUAL BASIS,DIVIDEND YIELD,NET PROFIT MARGIN
2,Recording revenues and expenses in the period,Dividends adjusted for changes in number of,Profit after tax attributable to equity holder...
3,in which they are earned or incurred regardless,shares in issue as a percentage of the share p...,the parent divided by total revenue including
4,of whether cash is received or disbursed in that,(diluted) at the end of the period.,equity accounted investees.
...,...,...,...
99,,,Shareholders’ funds plus non-controlling inter...
100,,regulatory fund at UA and customer advances at,
101,,the Property Development sector.,
102,,,WORKING CAPITAL
103,,,Current assets minus current liabilities.

In [5]:
keywords_1 = ['for the year ended 31 march','total revenue', 'cost of sales', 'gross profit','other operating income','basic']
keywords_2 = ['net assets per share** (rs.)','net assets per share* (rs.)']
# Loop through all the tables
for i, table in enumerate(tables):

    # Convert all cells to lowercase for matching
    table_lower = table.astype(str).apply(lambda col: col.str.lower())
  
    # Dictionary to store matched values
    matched_rows = {}

    for keyword in keywords_1:
        # Find rows containing the keyword
        row = table[table_lower.apply(lambda r: keyword in ' '.join(r), axis=1)]
        if not row.empty:
            matched_rows[keyword] = row.iloc[0, 3]

    if matched_rows:
        print(f"\n✅ Table {i+1} contains financial rows:")
        for k, v in matched_rows.items():
            print(f"{k.title()} (column 3): {v}")
        #display(table)  # Show the full table (optional)
        break
    else:
        print(f"Table {i+1} does not contain any of the target keywords.")



# Loop through all the tables
for i, table in enumerate(tables):
    # Convert all cells to lowercase for matching
    table_lower = table.astype(str).apply(lambda col: col.str.lower())
  
    # Dictionary to store matched values
    matched_rows = {}

    for keyword in keywords_2:
        # Find rows containing the keyword
        row = table[table_lower.apply(lambda r: keyword in ' '.join(r), axis=1)]
        if not row.empty:
            matched_rows[keyword] = row.iloc[0, 1]

    if matched_rows:
        print(f"\n✅ Table {i+1} contains financial rows:")
        for k, v in matched_rows.items():
            print(f"{k.title()} {type(k.title())}(column 1): {v}")
        #display(table)  # Show the full table (optional)
        break
    else:
        print(f"Table {i+1} does not contain any of the target keywords.")

Table 1 does not contain any of the target keywords.
Table 2 does not contain any of the target keywords.
Table 3 does not contain any of the target keywords.

✅ Table 4 contains financial rows:
For The Year Ended 31 March (column 3): 2021
Total Revenue (column 3): 127,675,650
Cost Of Sales (column 3): (108,747,058)
Gross Profit (column 3): 18,928,592
Other Operating Income (column 3): 2,626,544
Table 1 does not contain any of the target keywords.
Table 2 does not contain any of the target keywords.
Table 3 does not contain any of the target keywords.
Table 4 does not contain any of the target keywords.
Table 5 does not contain any of the target keywords.
Table 6 does not contain any of the target keywords.
Table 7 does not contain any of the target keywords.
Table 8 does not contain any of the target keywords.
Table 9 does not contain any of the target keywords.
Table 10 does not contain any of the target keywords.
Table 11 does not contain any of the target keywords.
Table 12 does not contain any of the target keywords.
Table 13 does not contain any of the target keywords.
Table 14 does not contain any of the target keywords.
Table 15 does not contain any of the target keywords.

✅ Table 16 contains financial rows:
Net Assets Per Share* (Rs.) <class 'str'>(column 1): 224.8