In [1]:
# Import necessary libraries
import camelot
import pandas as pd

In [2]:
# Define the extraction function
def extract_tables_from_pdf(file_path):
    """
    Extract useful financial tables (like income statements) from a PDF.
    We only scan page range 170-end to avoid unnecessary noise.
    """
    try:
        # Focus on financial statements pages
        tables = camelot.read_pdf(file_path, pages='130-end', flavor='stream')

        if tables.n == 0:
            print(f"No tables found in {file_path}")
            return []

        useful_tables = []
        keywords = ['total revenue', 'cost of sales', 'operating expenses', 'gross profit','earnings per share', 'net asset','number of shares','%','top twenty shareholders of the company']

        for i, table in enumerate(tables):  
            df = table.df
            # Flatten table text
            table_text = ' '.join(df.apply(lambda row: ' '.join(row), axis=1).tolist()).lower()

            if any(keyword in table_text for keyword in keywords):
                print(f"Selected table {i} (financial content detected)")
                useful_tables.append(df)
            else:
                print(f"Skipped table {i} (non-financial content)")

        if not useful_tables:
            print(f"No financial tables found in {file_path}")

    
        return useful_tables

    except Exception as e:
        print(f"Error extracting tables from {file_path}: {str(e)}")
        return []

In [3]:
# Now, in your Jupyter Notebook:
# Extract the tables from the PDF (replace 'your_pdf_file.pdf' with your actual file path)
file_path = '508_1653300092463.pdf'
tables = extract_tables_from_pdf(file_path)

C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (32.5197, 49.603300000000196, 564.4347499999999, 785.2814079439255)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (32.5197, 662.741, 468.2141000000004, 841.4164119266055)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (109.378, 478.37110000000024, 482.6092000000002, 685.148230952381)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (32.5197, 669.7071, 442.73684999999995, 841.9275521932515)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (32.5197, 663.2771499999999, 533.7208499999999, 841.3362696428571)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (40.8239, 188.11250000000004, 431.7512500000001, 289.098195754717)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.276, 841.89)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
C:\Users\Sula\AppData\Roaming\Python\Python312\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.276, 841.89)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)

Selected table 0 (financial content detected)
Skipped table 1 (non-financial content)
Selected table 2 (financial content detected)
Skipped table 3 (non-financial content)
Skipped table 4 (non-financial content)
Skipped table 5 (non-financial content)
Skipped table 6 (non-financial content)
Selected table 7 (financial content detected)
Selected table 8 (financial content detected)
Skipped table 9 (non-financial content)
Selected table 10 (financial content detected)
Selected table 11 (financial content detected)
Skipped table 12 (non-financial content)
Skipped table 13 (non-financial content)
Selected table 14 (financial content detected)
Skipped table 15 (non-financial content)
Skipped table 16 (non-financial content)
Skipped table 17 (non-financial content)
Skipped table 18 (non-financial content)
Skipped table 19 (non-financial content)
Skipped table 20 (non-financial content)
Selected table 21 (financial content detected)
Skipped table 22 (non-financial content)
Selected table 23 (financial content detected)
Skipped table 24 (non-financial content)
Skipped table 25 (non-financial content)
Skipped table 26 (non-financial content)
Skipped table 27 (non-financial content)
Selected table 28 (financial content detected)
Skipped table 29 (non-financial content)
Selected table 30 (financial content detected)
Selected table 31 (financial content detected)
Selected table 32 (financial content detected)
Skipped table 33 (non-financial content)
Skipped table 34 (non-financial content)
Selected table 35 (financial content detected)
Skipped table 36 (non-financial content)
Skipped table 37 (non-financial content)
Skipped table 38 (non-financial content)
Selected table 39 (financial content detected)
Selected table 40 (financial content detected)
Selected table 41 (financial content detected)
Skipped table 42 (non-financial content)
Skipped table 43 (non-financial content)
Skipped table 44 (non-financial content)
Skipped table 45 (non-financial content)
Skipped table 46 (non-financial content)
Skipped table 47 (non-financial content)
Skipped table 48 (non-financial content)
Skipped table 49 (non-financial content)
Selected table 50 (financial content detected)
Selected table 51 (financial content detected)
Selected table 52 (financial content detected)
Selected table 53 (financial content detected)
Skipped table 54 (non-financial content)
Skipped table 55 (non-financial content)
Selected table 56 (financial content detected)
Selected table 57 (financial content detected)
Selected table 58 (financial content detected)
Selected table 59 (financial content detected)
Skipped table 60 (non-financial content)
Skipped table 61 (non-financial content)
Selected table 62 (financial content detected)
Selected table 63 (financial content detected)
Selected table 64 (financial content detected)
Selected table 65 (financial content detected)
Selected table 66 (financial content detected)
Selected table 67 (financial content detected)
Selected table 68 (financial content detected)
Skipped table 69 (non-financial content)
Selected table 70 (financial content detected)
Selected table 71 (financial content detected)
Skipped table 72 (non-financial content)
Selected table 73 (financial content detected)
Skipped table 74 (non-financial content)
Skipped table 75 (non-financial content)
Skipped table 76 (non-financial content)
Skipped table 77 (non-financial content)
Skipped table 78 (non-financial content)
Skipped table 79 (non-financial content)
Skipped table 80 (non-financial content)
Skipped table 81 (non-financial content)
Skipped table 82 (non-financial content)
Skipped table 83 (non-financial content)
Skipped table 84 (non-financial content)
Skipped table 85 (non-financial content)
Skipped table 86 (non-financial content)
Skipped table 87 (non-financial content)
Skipped table 88 (non-financial content)
Skipped table 89 (non-financial content)
Skipped table 90 (non-financial content)
Skipped table 91 (non-financial content)
Skipped table 92 (non-financial content)
Skipped table 93 (non-financial content)
Skipped table 94 (non-financial content)
Skipped table 95 (non-financial content)
Skipped table 96 (non-financial content)
Selected table 97 (financial content detected)
Skipped table 98 (non-financial content)
Skipped table 99 (non-financial content)
Skipped table 100 (non-financial content)
Skipped table 101 (non-financial content)
Skipped table 102 (non-financial content)
Skipped table 103 (non-financial content)
Skipped table 104 (non-financial content)
Skipped table 105 (non-financial content)
Skipped table 106 (non-financial content)
Skipped table 107 (non-financial content)
Skipped table 108 (non-financial content)
Skipped table 109 (non-financial content)
Skipped table 110 (non-financial content)
Skipped table 111 (non-financial content)
Skipped table 112 (non-financial content)
Skipped table 113 (non-financial content)
Skipped table 114 (non-financial content)
Skipped table 115 (non-financial content)
Skipped table 116 (non-financial content)
Selected table 117 (financial content detected)
Skipped table 118 (non-financial content)
Skipped table 119 (non-financial content)
Skipped table 120 (non-financial content)
Skipped table 121 (non-financial content)
Skipped table 122 (non-financial content)
Skipped table 123 (non-financial content)
Skipped table 124 (non-financial content)
Skipped table 125 (non-financial content)
Selected table 126 (financial content detected)
Skipped table 127 (non-financial content)
Skipped table 128 (non-financial content)
Selected table 129 (financial content detected)
Skipped table 130 (non-financial content)
Skipped table 131 (non-financial content)
Skipped table 132 (non-financial content)
Skipped table 133 (non-financial content)
Skipped table 134 (non-financial content)
Skipped table 135 (non-financial content)
Skipped table 136 (non-financial content)
Skipped table 137 (non-financial content)
Skipped table 138 (non-financial content)
Skipped table 139 (non-financial content)
Skipped table 140 (non-financial content)
Skipped table 141 (non-financial content)
Skipped table 142 (non-financial content)
Skipped table 143 (non-financial content)
Skipped table 144 (non-financial content)
Skipped table 145 (non-financial content)
Skipped table 146 (non-financial content)
Selected table 147 (financial content detected)
Skipped table 148 (non-financial content)
Selected table 149 (financial content detected)
Selected table 150 (financial content detected)
Skipped table 151 (non-financial content)
Selected table 152 (financial content detected)
Selected table 153 (financial content detected)
Selected table 154 (financial content detected)
Selected table 155 (financial content detected)
Skipped table 156 (non-financial content)
Skipped table 157 (non-financial content)
Skipped table 158 (non-financial content)
Skipped table 159 (non-financial content)
Skipped table 160 (non-financial content)
Selected table 161 (financial content detected)
Selected table 162 (financial content detected)
Selected table 163 (financial content detected)
Skipped table 164 (non-financial content)
Skipped table 165 (non-financial content)
Skipped table 166 (non-financial content)
Skipped table 167 (non-financial content)
Skipped table 168 (non-financial content)
Skipped table 169 (non-financial content)
Skipped table 170 (non-financial content)
Selected table 171 (financial content detected)
Skipped table 172 (non-financial content)
Selected table 173 (financial content detected)
Selected table 174 (financial content detected)
Selected table 175 (financial content detected)
Selected table 176 (financial content detected)
Skipped table 177 (non-financial content)
Skipped table 178 (non-financial content)
Skipped table 179 (non-financial content)
Skipped table 180 (non-financial content)
Skipped table 181 (non-financial content)
Selected table 182 (financial content detected)
Selected table 183 (financial content detected)
Selected table 184 (financial content detected)
Selected table 185 (financial content detected)
Skipped table 186 (non-financial content)
Skipped table 187 (non-financial content)
Skipped table 188 (non-financial content)
Skipped table 189 (non-financial content)
Skipped table 190 (non-financial content)
Skipped table 191 (non-financial content)
Skipped table 192 (non-financial content)
Skipped table 193 (non-financial content)
Skipped table 194 (non-financial content)
Selected table 195 (financial content detected)
Skipped table 196 (non-financial content)
Skipped table 197 (non-financial content)
Skipped table 198 (non-financial content)
Skipped table 199 (non-financial content)
Skipped table 200 (non-financial content)
Selected table 201 (financial content detected)
Selected table 202 (financial content detected)
Selected table 203 (financial content detected)
Selected table 204 (financial content detected)
Skipped table 205 (non-financial content)
Selected table 206 (financial content detected)
Selected table 207 (financial content detected)
Skipped table 208 (non-financial content)
Skipped table 209 (non-financial content)
Skipped table 210 (non-financial content)
Selected table 211 (financial content detected)
Skipped table 212 (non-financial content)
Skipped table 213 (non-financial content)
Selected table 214 (financial content detected)
Selected table 215 (financial content detected)
Selected table 216 (financial content detected)
Selected table 217 (financial content detected)
Skipped table 218 (non-financial content)
Skipped table 219 (non-financial content)
Skipped table 220 (non-financial content)
Selected table 221 (financial content detected)
Skipped table 222 (non-financial content)
Skipped table 223 (non-financial content)
Skipped table 224 (non-financial content)
Skipped table 225 (non-financial content)
Selected table 226 (financial content detected)
Skipped table 227 (non-financial content)
Selected table 228 (financial content detected)
Skipped table 229 (non-financial content)
Skipped table 230 (non-financial content)
Skipped table 231 (non-financial content)
Skipped table 232 (non-financial content)
Skipped table 233 (non-financial content)
Selected table 234 (financial content detected)
Skipped table 235 (non-financial content)
Skipped table 236 (non-financial content)
Skipped table 237 (non-financial content)
Skipped table 238 (non-financial content)
Selected table 239 (financial content detected)
Skipped table 240 (non-financial content)
Skipped table 241 (non-financial content)
Selected table 242 (financial content detected)
Skipped table 243 (non-financial content)
Skipped table 244 (non-financial content)
Skipped table 245 (non-financial content)
Selected table 246 (financial content detected)
Skipped table 247 (non-financial content)
Skipped table 248 (non-financial content)
Skipped table 249 (non-financial content)
Skipped table 250 (non-financial content)
Selected table 251 (financial content detected)
Selected table 252 (financial content detected)
Selected table 253 (financial content detected)
Selected table 254 (financial content detected)
Selected table 255 (financial content detected)
Selected table 256 (financial content detected)
Selected table 257 (financial content detected)
Skipped table 258 (non-financial content)
Selected table 259 (financial content detected)
Selected table 260 (financial content detected)
Selected table 261 (financial content detected)
Selected table 262 (financial content detected)
Selected table 263 (financial content detected)
Selected table 264 (financial content detected)
Selected table 265 (financial content detected)
Selected table 266 (financial content detected)
Selected table 267 (financial content detected)
Skipped table 268 (non-financial content)
Skipped table 269 (non-financial content)
Skipped table 270 (non-financial content)
Skipped table 271 (non-financial content)
Skipped table 272 (non-financial content)
Skipped table 273 (non-financial content)
Skipped table 274 (non-financial content)
Skipped table 275 (non-financial content)
Skipped table 276 (non-financial content)

In [4]:
# Show each table in a DataFrame
if tables:
    for i, table in enumerate(tables):
        print(f"Table {i + 1}:")
        display(table)  # This will display the table in a Jupyter notebook cell
else:
    print("No tables to display.")

Table 1:

,0,1,2
0,Financial Services,,
1,Indicators,,
2,,,Community development
3,Training (Hours),,
4,,,Relevance: Impact on brand reputation and poss...
...,...,...,...
59,UA produced 300 'Million Dollar Round Table' (...,,towards ensuring uninterrupted learning
60,qualifiers which was the highest ever in the Sri,,support during the pandemic.
61,Lankan insurance industry in CY2021. This show...,,
62,a high standard of excellence including providing,,
63,outstanding client service and strict ethical ...,,

Table 2:

,0,1,2,3,4,5
0,broker.,,,,,
1,Tea Smallholder Factories PLC (TSF):\n (cid:121),,,,,
2,Operates six factories.\n (cid:121),,,,,
3,Leading manufacturer of low grown Orthodox \n ...,,,,,
4,,Inputs (Rs.million),2021/22,2020/21,%,2019/20
5,and CTC teas in the country.,,,,,
6,,Total assets,"134,622","81,241",66,"43,096"
7,John Keells Warehousing (JKW) – operates a sta...,,,,,
8,,Total equity,"54,578","30,367",80,"38,495"
9,of-the-art warehouse for pre-auction produce.,,,,,
10,,Total debt1,"72,510","47,562",52,"2,705"
11,,Capital employed2,"127,088","77,930",63,"41,200"
12,,Employees (No.)3,"1,227","1,196",3,"1,335"
13,Other,,,,,
14,JKH (Holding Company) and other businesses \n ...,,,,,
15,,Outputs (Rs.million),2021/22,2020/21,%,2019/20
16,(Centre functions/divisions).,,,,,
17,,Turnover,"4,041","3,949",2,"3,803"
18,,EBIT,"5,291","2,907",82,"1,178"
19,Contribution to,,,,,
20,,PBT,"21,090","3,291",541,"2,817"
21,the John Keells Group,,,,,
22,,PAT,"16,625","2,356",606,"2,065"
23,,,,,,
24,2%\n25%,EBIT per employee,4,2,77,1
25,,Carbon footprint (MT),"2,202","2,543",(13),"3,012"
26,Revenue\nEBIT,,,,,
27,,1. Excludes lease liabilities.,,,,
28,,,,,,
29,21%\n2%,2. Includes lease liabilities.,,,,
30,,3. As per the sustainability reporting boundary.,,,,
31,Capital Employed\nCarbon Footprint,,,,,

Table 3:

,0,1
0,Industry Group Review,
1,"Other, including Information Technology and Pl...",
2,"ordinary shares of the Company, for an investm...",
3,,Rs.million\n2021/22\n2020/21\n%
4,maximum of the LKR equivalent of USD 30 millio...,
5,,EBITDA*
6,price would be based on the volume weighted av...,
7,,Information Technology \n451 \n368 \n23
8,Company's ordinary shares as quoted on the CSE...,
9,days ending immediately prior to the option ex...,285 \n369 \n(23)\nPlantation Services
10,the floor price of Rs.165.00 and cap price of ...,"Other\n 4,753 \n 2,363 \n101"
11,between 19 October 2022 and 18 January 2023. O...,
12,,"Total\n 5,489 \n 3,100 \n77"
13,maximum number of ordinary shares that would p...,
14,,PBT
15,"under the entire transaction, assuming all opt...",
16,,Information Technology \n518 \n350 \n48
17,"104,067,210, thereby capping the post-issue di...",
18,,170 \n249 \n(32)\nPlantation Services
19,of both phases to a maximum of 7.31 per cent.,
20,,"Other\n20,402 \n2,692 \n658"
21,The proceeds from this transaction will be uti...,"Total \n21,090 \n3,291 \n541"
22,corporate level balance sheet support towards ...,
23,,*Note that EBITDA includes interest income but...
24,in the Supermarket business and will afford th...,
25,,"currency exchange gains and losses, to demonst..."
26,agility to fund its investments in an optimal ...,performance of businesses.
27,additional support to the Group's liquidity po...,
28,terms of providing further leeway to manage th...,The EBITDA of the industry group recorded a si...
29,commitments of the Group's landmark projects s...,in lieu of the Holding Company. The Holding Co...
30,Life Integrated Resort' and the West Container...,higher interest income mainly due to an increa...
31,"Colombo. Additionally, given ADB's investment ...",equivalents as a result of the entire USD 175 ...
32,which private sector projects must have clear ...,from the IFC being available throughout the cu...
33,"and positive externalities, particularly in en...",as opposed to approximately six to nine months...
34,"governance (ESG) aspects, JKH will leverage on...",financial year.
35,and advisory to enhance and further strengthen...,
36,,The PBT of the Holding Company recorded a sign...
37,ESG processes and frameworks to reach best in ...,
38,,due to exchange gains recorded on its net fore...
39,,holdings:
40,,The foreign currency cash holdings includes th...
41,,for the equity infusions of the 'Cinnamon Life...
42,Capital Management Review,Resort' project and the funds raised for the G...
43,The section that ensues discusses the performa...,pipeline via the debt drawdown from the Intern...
44,"during the year under review, under the key fo...",Corporation (IFC) term loan facility and the p...
45,for the industry group.,ordinary shares to ADB.

Table 4:

,0,1,2,3,4,5
0,,,,,,aided the business in navigating through cost ...
1,,Financial and Manufactured Capital,,,,
2,,,,,(cid:121),Profitability in the Plantation Services secto...
3,Income Statement Indicators,,,,,
4,,,,,,the aforementioned decline in revenue. Perform...
5,Rs.million,2021/22,2020/21,%,,impacted by a bad debt provision for debtors a...
6,,,,,,considering the stresses faced by tea producer...
7,Revenue,,,,,
8,,,,,,year-on-year comparison.
9,Information Technology,"1,456","1,088",34,,
10,Plantation Services,"2,496","2,782",(10),(cid:121),The industry group recorded fair value gains o...
11,,,,,,(IP) of Rs.81 million which stemmed from the P...
12,Other,89,79,14,,
13,,,,,,sector and investments at the Holding Company ...
14,Total,"4,041","3,949",2,,
15,,,,,,million].

Table 5:

,0,1,2,3,4,5
0,Balance Sheet Indicators,,,,,
1,,,,,,Energy and emissions management
2,Rs.million,2021/22,2020/21,%,,
3,,,,,,"Relevance: Financial, regulatory and brand rep..."
4,Debt,,,,,
5,,,,,implications,
6,Information Technology,63,61,2,,
7,,,,,Approach,
8,Plantation Services,311,304,2,,
9,,,,,(cid:121),Implementing and improving energy efficiency.
10,Other,"72,136","47,197",53,,
11,,,,,(cid:121),Use of renewable energy sources.
12,Total,"72,510","47,562",52,,
13,,,,,(cid:121),Alignment with international standards and best
14,Net Debt/(Cash)*,,,,,
15,,,,,,practice.
16,Information Technology,"(2,389)","(1,245)",92,,
17,,,,,Initiatives,
18,Plantation Services,(85),(0),"28,787",,
19,,,,,(cid:121),Replacement of existing fluorescent lamps with
20,Other,"(40,095)","(22,324)",80,,
21,,,,,,"LED lighting on an ongoing basis at TSF, leadi..."
22,Total,"(42,569)","(23,569)",81,,
23,,,,,,savings in energy consumption.
24,,*Net debt is arrived by subtracting the Holdin...,,,(cid:121),~5.3 million kWh of renewable energy utilised
25,,"equivalents, including its short-term investme...",,,,
26,,,,,,through the generation of solar power by JKW and
27,,,,,,utilisation of biomass at TSF.
28,(cid:121),Borrowings of the Holding Company increased du...,,,,
29,,,,,(cid:121),Tea dryer inlet temperature was maintained by
30,,to an increase in LKR borrowings in line with ...,,,,
31,,,,,,installing a cyclone type drier and renovating...
32,,strategy of the Company. Whilst borrowings not...,,,,
33,,,,,,"furnace at Neluwa tea factory, resulting in ef..."
34,,"increase, on a net debt basis, the Holding Com...",,,,
35,,,,,,energy usage and minimising risk of fire related
36,,per increase amounting to Rs.39.83 billion. Th...,,,,
37,,,,,,hazards.
38,,the increase in cash from the private placemen...,,,,
39,,,,,(cid:121),TSF conducted awareness sessions for its emplo...
40,,ADB for a consideration of the LKR equivalent ...,,,,
41,,,,,,on the topic of energy conservation at tea fac...
42,(cid:121),The increase in debt of the Information Techno...,,,,
43,,Services sectors are attributable to an increa...,,,,
44,manage working capital requirements.,,,,,
45,,,,,,Waste and effluent management

Table 6:

,0,1
0,2021/22\n148\n18%,Information \nPlantation \nOther\nEmployees
1,,Technology\nServices
2,Note: Waste generated excludes the Information...,
3,not considered material.,
4,,Health and safety
5,Carbon footprint scope 1 and 2 per operational...,Relevance: HR related risks directly affect brand
6,,reputation and employee well-being and have a ...
7,2021/22\n2020/21,
8,,impact on the long-term sustainability of the ...
9,0.60\n0.56 \nTSF PLC CO2 (kg per kg of tea pro...,
10,,Approach
11,JK PLC & JKW CO2 (kg per sq.ft. of floor area)...,
12,,Maintaining health and safety related processe...
13,,practices.
14,,Training and creating awareness.\n (cid:121)
15,,Initiatives
16,,TSF conducted 14 fire evacuation drills and \n...
17,Human Capital,demonstrations at factories.
18,,The ISO 22000:2005 certificate was maintained ...
19,"As a service-oriented industry, emphasis is pl...",
20,,"factories, achieving zero product quality clai..."
21,"management of Human Capital, through continuou...",
22,,improving product safety in terms of good hygiene
23,development and skill enhancement of employees.,
24,,practises.
25,,Maintenance of the ISO 45001:2018 certificatio...
26,"During the year under review, the businesses c...",
27,"the COVID-19 safety guidelines, whilst also fa...",Conducting frequent assessments of risks and \...
28,"options to selected staff categories. Further,...","hazards associated in the manufacturing process,"
29,sanitation practices were implemented whilst c...,resulting in fewer accidents and lower attrition.
30,adhering to health and safety conditions withi...,
31,,Conducted COVID-19 awareness sessions for \n (...
32,,employees on health and safety guidelines.
33,The IT sector in collaboration with universiti...,

Table 7:

,0,1
0,Outlook,
1,The section that ensues entails a discussion o...,
2,to navigating through the current macroeconomi...,
3,the political and social volatility. The secti...,
4,specific implications as well as the outlook b...,
...,...,...
71,,"ensuring law and order, free of"
72,World Bank\nAll forecasts withdrawn,
73,IMF\n2.6,"corruption, and transparency is"
74,,critical.
75,ADB\n2.4,

Table 8:

,0,1,2,3,4,5,6,7
0,has laid a strong platform for growth and is n...,,,,,,,
1,,,,,,,,Transportation industry group is envisaged
2,"in building capacity, capability and process e...",,,,,,,
3,,,,,,,,to be a key driver of the Group's performance
4,"year, and beyond.",,,,,,,
5,,,,,,,,"in the immediate-term, particularly given"
6,,,,,,,,its direct and indirect exposures to foreign
7,,2021/22,2020/21,2019/20,2018/19*,YoY Change (%),,
8,,,,,,,,currency denominated income streams.
9,Rs.million,,,,FY22,FY21,FY20,
10,,,,,,,,The revival of global trade in the medium
11,Recurring EBITDA,,,,,,,to long-term on the back of economic
12,,,,,,,,"recovery, improvements in consumption, and"
13,Transportation,"6,141","3,610","4,375","4,598 \n70",(17),(5),
14,,,,,,,,investments in infrastructure will augur well
15,Consumer Foods,"3,485","3,318","3,366","2,864 \n5",(1),18,
16,,,,,,,,"for Sri Lanka, particularly given its strategic"
17,Retail,"7,549","5,523","5,108","2,988 \n37",8,71,
18,,,,,,,,location on key shipping routes. While
19,Leisure,"3,785","(3,588)","2,306","5,431 \n205",(256),(58),
20,,,,,,,,"short-term uncertainty exists for the POC,"
21,Property,"7,867",(17),641,"378 45,451",(103),70,it should be noted that operations of the
22,Financial Services,"5,024","3,645","2,988","3,359 \n38",22,(11),"Port continued unhindered, with capacity"
23,"Other, incl. Information",,,,,,,"recording a growth, even during the 30-year"
24,Technology &,,,,,,,conflict in the country which ended in CY2009.
25,Plantation Services,"5,408","3,082","1,286","4,106 \n75",140,(69),
26,,,,,,,,Immediate to Short-Term
27,,"39,259","15,572","20,069","23,724 \n152",(22),(15),
28,Recurring PBT,,,,,,,The World Trade Organisation (WTO) expects
29,,,,,,,,merchandise trade volume to grow at 3.0
30,Transportation,"5,712","3,269","4,044","4,281 \n75",(19),(6),
31,,,,,,,,"per cent in CY2022, and 3.4 per cent in"
32,Consumer Foods,"2,319","2,304","2,284","1,885 \n1",1,21,
33,,,,,,,,"CY2023, post adjusting for the impacts of the"
34,Retail,"3,056","1,608","1,490",351 \n90,8,324,
35,,,,,,,,Russia-Ukraine conflict. Although the outlook
36,Leisure,"(1,512)","(8,546)","(1,597)","1,945 \n82",(435),(182),
37,,,,,,,,at the onset of the calendar year was more
38,Property,"7,650",(109),535,"245 \n7,102",(120),118,"positive, where the envisaged growth at the"
39,Financial Services,"4,995","3,360","2,755","2,966 \n49",22,(7),"time was 4.7 per cent for CY2022, this has"
40,"Other, incl. Information",,,,,,,moderated since then to 3.0 per cent on the
41,Technology &,,,,,,,back of increased uncertainty worldwide –
42,Plantation Services,"2,213","1,612",787,"3,632 \n37",105,(78),from escalating tensions between Russia and
43,,,,,,,,"Ukraine, supply chain disruptions, increased"
44,,"24,432","3,498","10,299","15,305 \n599",(66),(33),
45,,,,,,,,inflationary pressures and lockdowns in China
46,"*Adjusted for SLFRS 16 - Leases, for compariso...",,,,,,,"which has disrupted seaborne trade. However,"
47,,,,,,,,it is encouraging to note that the Asian region

Table 9:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,,,,,,,,,,,,,,,,,,The Ports and Shipping business is envisaged
1,,Volume of world merchandise trade is envisaged...,,,,,,,,,,,,,,,,
2,,,,,,,,,,,,,,,,,,to remain resilient and continue its recovery
3,in the first quarter of CY2022,,,,,,,,,,,,,,,,,
4,,,,,,,,,,,,,,,,,,"momentum in line with regional trends,"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,,,,,,,,,,,,,,,,,,given the foreign currency shortage in the
88,,,,,,,,,,,,,,,,,,"country. However, this impact is expected to"
89,Source: UNCTAD Global Trade Update February 2022.,,,,,,,,,,,,,,,,,gradually diminish once the current liquidity
90,,,,,,,,,,,,,,,,,,"challenges faced by the country are resolved,"
91,,,,,,,,,,,,,,,,,,as articulated previously.

Table 10:

,0,1
0,Outlook,
1,lifestyles of consumers. Given evolving regula...,Convenience Foods
2,"towards environmentally friendly packaging, co...",
3,,The Convenience Foods business will continue
4,"alternate forms of packaging, where feasible.",
5,,to innovate and expand on its portfolio
6,,offering. Similar to the Beverages and Frozen
7,"Given changing market dynamics, the Beverages ...",
8,,"Confectionery businesses, the Convenience"
9,Focus on consolidating its current CSD portfol...,Foods business will also place emphasis
10,keeping units (SKUs).,on staying abreast of market trends and
11,,delivering products in line with consumer
12,Prioritise the extension of the current non-CS...,
13,,preferences.
14,Manage the composition of the portfolio to ens...,
15,Consolidate and stabilise distributor networks...,
16,,The strategic priorities for the business for the
17,digital means.,
18,,medium-term are:
19,"Explore new operating models, different market...",
20,,"Development of product extensions, \n (cid:121)"
21,"working, given changing consumer behaviour and...",
22,,paving way for the business to increase its
23,Implement lean initiatives at factories. \n (c...,
24,,market share particularly through emphasis
25,,on 'convenient' and affordable meal
26,Frozen Confectionery,
27,,options.
28,Rapid urbanisation and increasing disposable i...,
29,,Focus on consolidating the dry distribution \n...
30,have fuelled growth in global frozen confectio...,
31,,network and sales force to ensure readiness
32,"has witnessed notable growth, even amidst chal...",
33,,to cater to the envisaged growth in
34,"aforementioned short-term impacts, this positi...",
35,,volumes.
36,Ice cream consumption in Sri Lanka at ~3 litre...,Emphasis on growing the modern and \n (cid:121)
37,demonstrating the significant potential for gr...,"general trade channels, particularly the"
38,"peers, the business expects a gradual shift in...",organised small and medium entities
39,with impulse products being the primary driver...,under general trade thereby increasing
40,consumption in Sri Lanka. The business will co...,footprint.
41,in an optimal manner.,
42,,Focus on further augmenting its portfolio \n (...
43,,offering.
44,The bulk:impulse mix of regional markets is hi...,
45,the significant potential for the impulse cate...,
46,(%),
47,,
48,8,The introduction of concepts

Table 11:

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,Outlook,,,,,,,,,,,,
1,Office Automation,,,,,,,,,,,,
2,,Modern Trade Density,,,,,,,,,,,
3,The performance of the Office Automation,Population (’000) per store,,,,,,,,,,,
4,business is expected to undergo challenges,,,,,,,,,,,,
5,,150,,,,,,,,,,,
6,,132.0,,,,,,,,,,,
7,as a result of the current constraints in the,,,,,,,,,,,,
8,foreign exchange market. Given the retail,120,,,,,,,,,,,
9,"nature of the Office Automation business,",,,,,,,,,,,,
10,the business is expected to face pressures in,90,,,,,,,,,,,
11,importing office automation products and,,,,,,,,,,,,
12,,60\n47.0,,,,,,,,,,,
13,"mobile phones, given challenges in opening",,,,,,,,,,,,
14,,30.0,,,,,,,,,,,
15,letters of credit due to the foreign currency,,,,,,,,,,,,
16,,30,21.0,,,,,,,,,,
17,"shortage in the country, till such time the",,,7.3,,,,,,,,,
18,,,,,4.7,4.5,3.7,3.6,3.4,3.0,2.5,1.9,0.9
19,foreign currency and liquidity position of the,0,,,,,,,,,,,
20,country is stabilised.,India\nVietnam\nSri Lanka,Philippines,Indonesia,Thailand,Malaysia,Singapore,China,Hong Kong,Australia,New Zealand,Taiwan,Korea
21,Medium to Long-Term,,,,,,,,,,,,
22,,,Source: Retail and shopper trends in the Asia ...,,,,,,,,,,
23,Supermarkets,,,,,,,,,,,,
24,The prospects for the modern trade industry,,,,,,,,,,,,
25,,,The Supermarket business will continue to plac...,,,,,,,,,,
26,"in Sri Lanka remains promising, given the low",,,,,,,,,,,,
27,,,experience for its customers through its 'fres...,,,,,,,,,,
28,penetration of modern trade outlets in the,,,,,,,,,,,,
29,,,"activity pillars; product, price, place, peopl...",,,,,,,,,,
30,"country, growth expectations for consumer",,,,,,,,,,,,
31,,,continually expanding its footprint to capital...,,,,,,,,,,
32,demand and the steady conversion from,,,,,,,,,,,,
33,,,industry given its low density and penetration...,,,,,,,,,,
34,general trade to modern trade driven by,,,,,,,,,,,,
35,,,be the key driver of growth going forward for ...,,,,,,,,,,
36,"demand for better quality, convenience",,,,,,,,,,,,
37,,,increase its contribution over the years. Cons...,,,,,,,,,,
38,and 'value for money' by consumers. The,,,,,,,,,,,,
39,,,physical stores; a reversal in online trends w...,,,,,,,,,,
40,Supermarket business is uniquely positioned,,,,,,,,,,,,
41,,,'brick and motor' sales noting a corresponding...,,,,,,,,,,
42,to capitalise on this opportunity by leveraging,,,,,,,,,,,,
43,,impacted by the pandemic.,,,,,,,,,,,
44,on its high brand equity.,,,,,,,,,,,,
45,,,"In this light, the business will continue the ...",,,,,,,,,,
46,Prospects for the modern trade industry in Sri,,,,,,,,,,,,
47,,,"urban and suburban areas, timing such expansio...",,,,,,,,,,
48,"Lanka is promising, given the low penetration",,,,,,,,,,,,
49,,,and the maturity of these markets. In addition...,,,,,,,,,,
50,of modern trade outlets in the country.,,,,,,,,,,,,
51,,,rolled-out a modular store format in pursuing ...,,,,,,,,,,
52,Modern Retail Penetration,,,,,,,,,,,,
53,,,"capital expenditure and operational costs, unt...",,,,,,,,,,
54,(%),,,,,,,,,,,,
55,,,by which time the store can be expanded to a s...,,,,,,,,,,

Table 12:

,0,1,2,3,4,5,6,7
0,,,,,,,,and the maturity of these markets. In addition...
1,of modern trade outlets in the country.,,,,,,,
2,,,,,,,,rolled-out a modular store format in pursuing ...
3,Modern Retail Penetration,,,,,,,
4,,,,,,,,"capital expenditure and operational costs, unt..."
5,(%),,,,,,,
6,,,,,,,,by which time the store can be expanded to a s...
7,80,,,,,,,challenges faced during expansion include secu...
8,,70,,,,,,
9,70,,,,,,,are in conformity with brand specifications an...
10,60,,,,,,,focus on retaining its labour force by augment...
11,,,49,48,,,,
12,50,,,,,,,individuals and focusing on the employer brand.
13,,,,,43,,,
14,,,,,,40,,
15,40,,,,,,,
16,30,,,,,,,The DC in Kerawalapitiya will augment the busi...
17,20,,,,,,16,cater to the number of outlets well beyond the...
18,10,,,,,,,operation of the new DC is expected to result ...
19,0,,,,,,,given the centralisation of almost the entiret...

Table 13:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,The business will continue with the,,,,,,,,,,,,,
1,development and implementation of,,,,,,,,,,,,,
2,advanced analytics 'use cases' in order to,,,,,,,,,,,,,
3,,,,Leisure,,,,,,,,,,
4,foster data-driven decision-making. The,,,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,,,,,,,,,,,,,,
99,and distribution network.,,,,,,,,(84),(81),,,,
100,,,,,,(85),,(85),,,,,,
101,,,,(91),,,(87),,,,,,,
102,,(100),,(95),,,,,,,,,,

Table 14:

,0,1
0,Given the significant increase in prices on the,"In terms of portfolio expansion, 'Cinnamon Red..."
1,"back of supply chain constraints, particularly","(KHL) and Indra Traders (Private) Limited, is ..."
2,for restaurant operations and events and,"opened in the second half of 2022/23, notwiths..."
3,"banqueting, the businesses will continue to",prevailing ground situation. At a total invest...
4,adopt stringent expense control and cost,hold a 40 per cent stake of the equity compone...
...,...,...
85,"integrated global promotion campaign, which",
86,,15
87,is envisaged to be launched for the first time,
88,,10
89,since the end of the conflict in CY2009.,05

Table 15:

,0,1
0,Outlook,
1,macroeconomic landscape and the fiscal consoli...,Commercial Real Estate
2,"demand for commercial and residential spaces, ...",
3,,The opportunity for high-end 'A-Grade' office
4,"of public infrastructure projects, increasing ...",
...,...,...
72,supply dynamics.,Vauxhall Land Developments
73,,"(Private) Limited, and"
74,,"accordingly, will continue to"
75,,focus on the monetisation of
76,,its extensive land bank.

Table 16:

,0,1
0,,"brand equity, diversified portfolio of product..."
1,Nations Trust Bank PLC (NTB) will focus its ef...,
2,on building resilience and sustainability through,Sri Lanka has a relatively low level of insura...
3,,Life insurance premium as a percentage of GDP (%)
4,"prioritising credit quality, margin management,",
5,return focused lending and financial stability.,4.0
6,,Global average: 3.35%
7,The Bank's Tier I Capital and Total Capital,3.5
8,Adequacy ratios as at 31 March 2022 were,3.0
9,satisfactorily above regulatory levels at 11.8...,2.5
10,"cent and 14.1 per cent, respectively. Supported",2.0
11,"by a strong capital base, healthy liquidity bu...",1.5
12,"and robust risk management models, the Bank",1.0
13,is confident that it has the required resources,0.5
14,to withstand the potential impacts arising from,0.0
15,,Malaysia\nThailand\nIndia\nVietnam\nIndonesia\...
16,the current macroeconomic environment. To,

Table 17:

,0,1
0,,The tightening monetary policy stance and the ...
1,,in lacklustre credit growth on the back of red...
2,,loan growth. Prolonged stresses may also resul...
3,Financial Services,
4,,"impairments, although the Bank will continue t..."
...,...,...
76,,"convenience, achieving operational excellence ..."
77,return focused lending and,
78,,"on the vast data reserve, emphasis will be pla..."
79,financial stability.,"the market, developing innovative products and..."
80,,enhance decision-making capability.

Table 18:

,0,1,2,3,4,5
0,,,,,,'Cinnamon Life' will contribute towards a
1,thereafter. The Group believes these targets a...,,,,,
2,,,,,,positive ROCE along with the recovery in
3,confident of reaching these targets in such a ...,,,,,
4,,,,,,"tourists arrivals, particularly since the Group"
5,,,,,,is poised to benefit from having its full
6,Indicator (%),Goal,,Achievement,,complement of hotels available to cater to the
7,,,2021/22,2020/21,2019/20*,"'pent up' demand, once the current situation"
8,,,,,,in the country stabilises.
9,EBIT growth**,>20,166.7,(41.3),(25.5),
10,EPS growth (fully diluted),>20,318.0,(49.3),(35.9),
11,Cash EPS growth (fully diluted),>20,172.0,4.5,(24.7),Capital employed has
12,Long-term return on capital employed (ROCE),15,4.2,2.1,4.2,significantly increased as a
13,Long-term return on equity (ROE),18,7.5,2.2,4.5,result of the 'Cinnamon Life
14,Net debt (cash) to equity***,50,23.5,20.0,14.0,Integrated Resort' project and
15,,,,,,"its gestation period, whilst"

Table 19:

,0,1
0,Long-Term Aspirations,"As seen in the portfolio graph below, a"
1,,significant portion of capital is deployed in
2,The Group continually endeavours to deliver va...,
3,,Leisure and the 'Cinnamon Life Integrated
4,"To this end, the Group has in place long-term ...",
5,,Resort'. Whilst these have resulted in a
6,ensure that the Group is moving progressively ...,
7,,"significant 'drag' on the ROCE of the Group,"
8,"performance has been impacted, and, to an exte...",
9,,the commencement of operations at
10,"expenditure cycle of the Group, the Easter Sun...",
11,,'Cinnamon Life' will contribute towards a
12,thereafter. The Group believes these targets a...,
13,,positive ROCE along with the recovery in
14,confident of reaching these targets in such a ...,
15,,"tourists arrivals, particularly since the Group"
16,,is poised to benefit from having its full
17,Indicator (%)\nGoal\nAchievement,complement of hotels available to cater to the
18,2021/22\n2020/21\n2019/20*,"'pent up' demand, once the current situation"
19,,in the country stabilises.
20,EBIT growth**\n>20\n166.7\n(41.3)\n(25.5),
21,EPS growth (fully diluted)\n>20\n318.0\n(49.3)...,
22,Cash EPS growth (fully diluted)\n>20\n172.0\n4...,Capital employed has
23,Long-term return on capital employed (ROCE)\n1...,significantly increased as a
24,Long-term return on equity (ROE)\n18\n7.5\n2.2...,result of the 'Cinnamon Life
25,Net debt (cash) to equity***\n50\n23.5\n20.0\n...,Integrated Resort' project and
26,* Growth rates for 2019/20 have been adjusted ...,"its gestation period, whilst"
27,,
28,2018/19 has been adjusted in arriving at the a...,the long-term financing
29,**EBIT growth excludes the impact of exchange ...,
30,,facility obtained from IFC
31,***Excludes lease liabilities.,
32,,in 2020/21 and the recent
33,Performance of the Portfolio,private placement to ADB has
34,Capital employed has significantly increased a...,also contributed to a notable
35,,
36,"project and its gestation period, whilst the l...","increase in the capital base,"
37,2020/21 and the recent private placement to AD...,
38,,all of which have negative
39,"the capital base, all of which have negative i...",
40,,impacts on ROCE.
41,are catalysts for future growth and risk mitig...,
42,"effects on performance, priority has always be...",

Table 20:

,0,1
0,(%)\nmargin \nturnover\nstructure,
1,,"interest costs, unless explicitly mentioned, a..."
2,(%)\nleverage,
3,,with Sri Lanka Accounting Standards (SLFRS/LKAS).
4,2021/22\n17.6\n5.4\n1.88\n1.73,
5,2020/21\n13.5\n4.7\n1.83\n1.58,
6,,Insights
7,The EBIT margin of the Supermarket business no...,"Waterfront Properties (Private) Limited (WPL),..."
8,driven by a notable increase in same store sal...,of 'Cinnamon Life Integrated Resort' refinance...
9,by stringent expense management procedures rol...,syndicated loan in December 2021 through a USD...
10,,long-term loan facility and a six-month bridgi...
11,The Office Automation business also noted an i...,"million, which was structured in order to alig..."
12,due to the implementation of stringent cost co...,date of July 2022 of the original USD 395 mill...
13,"faced on restrictions on imports, constraints ...",
14,,The USD 225 million facility was concluded at ...
15,and foreign currency liquidity pressures in th...,
16,,the previous facility taking into account step...
17,,mechanisms based on pre-agreed triggers.
18,,The facility is a 5-year loan with a 2-year gr...
19,,back-ended capital payments.

Table 21:

,0,1
0,Financial Services,
1,ROCE\n=\nEBIT \nx\nAsset \nx\nCapital,Insights
2,(%)\nmargin \nturnover\nstructure,
3,,"The ROCE of the Other, including Information T..."
4,(%)\nleverage,
5,,Plantation Services industry group has been de...
6,2021/22\n26.6\n20.7\n0.32\n4.00,years primarily on account of the capital rais...
7,,Company. The foreign currency cash holdings in...
8,2020/21\n17.3\n16.1\n0.31\n3.50,
9,,earmarked for the equity infusions of the 'Cin...
10,Improvement in ROCE was driven by higher EBIT ...,Resort' project and the funds raised for the G...
11,business as a result of various cost optimisat...,pipeline via the debt drawdown from the IFC te...
12,enhancing initiatives whilst the Insurance bus...,the private placement of ordinary shares to ADB.
13,"growth in gross written premiums, despite the ...",
14,,Whilst the cash balance of the Group is curren...
15,landscape.,
16,,below the Group's hurdle rate exerting pressur...
17,,the presence of adequate cash reserves enables...
18,"Other, including Information Technology and Pl...",
19,,"manage its liquidity requirements better, part..."
20,Services,
21,,operations and investments in the current vola...
22,ROCE\n=\nEBIT \nx\nAsset \nx\nCapital,environment.
23,(%)\nmargin \nturnover\nstructure,
24,,The Group will continue to focus on ensuring t...
25,(%)\nleverage,
26,,preserved with a focus on further enhancing it...
27,2021/22\n5.2\n130.9\n0.04\n1.05,
28,,proactively ahead of any future requirements.
29,2020/21\n4.9\n73.6\n0.06\n1.04,

Table 22:

,0,1,2
0,share-related information.,,
1,,,The All Share Price Index (ASPI) and the Stand...
2,Total number of shares in issue as at 31/03/2022,"1,384,916,632",SL20) Index of the Colombo Stock Exchange (CSE...
3,Public shareholding as at 31/03/2022,98.74%,"and regional peers. As at the end of 2021, the..."
4,,,"at 12,226 points, whilst the S&P SL20 reached ..."
5,Stock symbol,JKH.N0000,
6,,,for the calendar year resulted in the ASPI and...
7,Newswire codes of the JKH Share,,
8,,,"80.0 per cent and 60.0 per cent, respectively...."
9,Bloomberg,JKH.SL,investor participation and the low interest ra...
10,,,"during most parts of the year, drove demand to..."
11,Dow Jones,P\n.JKH,
12,Reuters,JKELF.PK,
13,,,"However, the macroeconomic volatility and unce..."
14,Global Depositary Receipts (GDR) balance,"1,320,942","beginning of CY2022, including multiple rating..."
15,,,"interest rates, steep depreciation in the curr..."
16,,,uncertainty resulted in the CSE recording stee...
17,Global and Local Market Review,,selling pressure from local investors. This wa...
18,,,suspension of Sri Lanka's external debt servic...
19,"Despite the impacts of the COVID-19 pandemic, ...",,
20,,,there will be short-term challenges in the equ...
21,recorded an encouraging performance with most ...,,
22,,,"macroeconomic situation, the Group remains con..."
23,growth in CY2021. With major Central Banks acr...,,
24,,,growth prospects in the medium to long-term.
25,to adopt somewhat expansionary monetary polici...,,
26,one of the preferred asset classes for investo...,,

Table 23:

,0,1,2
0,"Index gaining 4.8 per cent, and Europe's STOXX...",decreased to 8.8 times in 2021/22 [2020/21: 15...,
1,per cent in CY2021.,,
2,,ASPI and S&P20SL Market Performance,
3,,(Index),(Index)
4,Regional Market Performance,,
5,(%),"15,000","4,500"
6,100,,
7,80.5,"13,000","4,000"
8,80,,
9,,"11,000","3,500"
10,60,,
11,35.7,"9,000","3,000"
12,25.1\n24.1\n40,,
13,10.4\n14.4,"7,000","2,500"
14,4.8\n9.7\n20,,
15,0,"5,000","2,000"
16,(3.7)\n(0.2),Mar-21\nMay-21\nJul-21\nSep-21\nNov-21\nJan-22,Mar-22
17,(20),,

Table 24:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,,,,,,from Rs.148.50 as at 31 March 2021.,,,,,,,,,,
1,,31 March,31 March,%,,,,,,,,,,,,
2,,2022,2021,,,,,,,,,,,,,
3,,,,,,JKH Share Performance vs ASPI (Indexed),,,,,,,,,,
4,MSCI,,,,Index,,,,,,,,,,,No. of shares (mn)
5,All Country World Index,711.56,673.29,6,200,,,,,,,,,,,100
6,All Country World Index,,,,,,,,,,,,,,,
7,,,,,,,,,,,,,,,,80
8,excluding USA,323.59,336.07,(4),150,,,,,,,,,,,
9,World (23 Developed Markets),"3,053.07","2,811.70",9,,,,,,,,,,,,60
10,,,,,100,,,,,,,,,,,
11,USA,"4,338.85","3,854.97",13,,,,,,,,,,,,
12,,,,,,,,,,,,,,,,40
13,Europe,"1,927.37","1,905.02",1,,,,,,,,,,,,
14,,,,,50,,,,,,,,,,,
15,,,,,,,,,,,,,,,,20
16,"Europe, Australasia and Far East","2,181.63","2,208.32",(1),,,,,,,,,,,,
17,,,,,0,,,,,,,,,,,0
18,Emerging Markets,"1,141.79","1,316.43",(13),,,,,,,,,,,,
19,,,,,Apr-21,May-21,Jun-21,Jul-21,Aug-21,Sep-21,Oct-21,Nov-21,Dec-21,Jan-22,Feb-22,Mar-22
20,Frontier Markets,608.04,573.31,6,,,,,,,,,,,,

Table 25:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,Indices,,,,JKH Share,,,,,,,,,,,
1,,Value,,,,The JKH share decreased by 2.4 per cent to Rs....,,,,,,,,,,
2,,,,,,from Rs.148.50 as at 31 March 2021.,,,,,,,,,,
3,,31 March,31 March,%,,,,,,,,,,,,
4,,2022,2021,,,,,,,,,,,,,
5,,,,,,JKH Share Performance vs ASPI (Indexed),,,,,,,,,,
6,MSCI,,,,Index,,,,,,,,,,No. of shares (mn),
7,All Country World Index,711.56,673.29,6,200,,,,,,,,,,,100
8,All Country World Index,,,,,,,,,,,,,,,
9,,,,,,,,,,,,,,,,80
10,excluding USA,323.59,336.07,(4),150,,,,,,,,,,,
11,World (23 Developed Markets),"3,053.07","2,811.70",9,,,,,,,,,,,,60
12,,,,,100,,,,,,,,,,,
13,USA,"4,338.85","3,854.97",13,,,,,,,,,,,,
14,,,,,,,,,,,,,,,,40
15,Europe,"1,927.37","1,905.02",1,,,,,,,,,,,,
16,,,,,50,,,,,,,,,,,
17,,,,,,,,,,,,,,,,20
18,"Europe, Australasia and Far East","2,181.63","2,208.32",(1),,,,,,,,,,,,
19,,,,,0,,,,,,,,,,,0
20,Emerging Markets,"1,141.79","1,316.43",(13),,,,,,,,,,,,
21,,,,,Apr-21,May-21,Jun-21,Jul-21,Aug-21,Sep-21,Oct-21,Nov-21,Dec-21,Jan-22,Feb-22,Mar-22
22,Frontier Markets,608.04,573.31,6,,,,,,,,,,,,
23,,,,,,JKH shares traded,,,,ASPI (indexed),,,JKH (indexed),,,
24,Peer,,,,,,,,,,,,,,,
25,SENSEX,"58,568.51","49,509.15",18,,,,,,,,,,,,
26,,,,,,"As illustrated in the graph above, 80,657,771 ...",,,,,,,,,,
27,JKSE,"7,071.44","5,985.52",18,,cent of the issued share capital of the Compan...,,,,,,,,,,
28,,,,,,on 24 January 2022. It is noted that this was ...,,,,,,,,,,
29,STI,"3,408.52","3,165.34",8,,,,,,,,,,,,
30,,,,,,and does not represent a change in beneficial ...,,,,,,,,,,
31,KLSE,"1,587.36","1,573.51",1,,,,,,,,,,,,
32,Local,,,,,,,,,,,,,,,
33,,,,,,JKH High/Low Share Prices per Month,,,,,,,,,,
34,,,,,(Rs.),,,,,,,,,,,
35,ASPI,"8,845.98","7,121.28",24,,,,,,,,,,,,
36,,,,,180,,,,,,,,,,,
37,S&P SL20,"3,031.16","2,850.12",6,,,,,,,,,,,,
38,,,,,160,,,,,,,,,,,

Table 26:

,0,1,2,3,4,5,6
0,Market Information of the Ordinary Shares of t...,,,,,,
1,,Q1,Q2,Q3,Q4,2021/22,2020/21
2,Share Information,,,,,,
3,High (Rs.),151.50,153.00,158.00,167.50,167.50,187.00
4,Low (Rs.),133.00,129.00,140.00,140.25,129.00,79.90
5,Close (Rs.),132.25,149.75,150.00,145.00,145.00,148.50
6,Dividends paid per share (Rs.),0.50,-,0.50,0.50,1.50,1.50
7,Trading Statistics,,,,,,
8,Number of transactions,"13,259","18,975","19,559","13,323","65,116","86,930"
9,Number of shares traded ('000),"38,380","72,698","44,922","116,598","272,599","390,995"
10,Value of all shares traded (Rs.million),"5,459","9,901","6,641","18,521","40,522","52,017"
11,Average daily turnover (Rs.million),96,157,107,319,169,238
12,Percentage of total market turnover (%),4,3,2,6,4,8
13,Market capitalisation (Rs.million),"178,495","197,631","197,966","200,813","200,813","195,970"
14,Percentage of total market capitalisation (%),5.1,4.7,3.6,5.2,5.2,6.3

Table 27:

,0,1
0,"Market capitalisation (Rs.million)\n178,495","200,813\n195,970\n197,631\n197,966\n200,813"
1,Percentage of total market capitalisation (%)\...,4.7\n3.6\n5.2\n5.2\n6.3
2,Issued Share Capital,Dividend
3,The number of shares in issue by the Company i...,"During the year under review, the Company paid..."
4,"1,384,916,632 as at 31 March 2022 from 1,319,6...","of Rs.0.50 per share, each, in November 2021 a..."
5,"2021, primarily due to the private placement o...",
6,"the Asian Development Bank (ADB), with the rem...",Whilst the Group recorded a strong recovery mo...
7,from the exercise of employee share options (E...,"growth in core operating profits, in addition ..."
8,of the Company's ESOP plans are found in the e...,"exchange gains for 2021/22, given the prevaili..."
9,discussion. The Global Depository Receipts (GD...,macroeconomic environment which could result i...
10,"share equivalent remained at 1,320,942.","performance, cashflows and the pipeline of str..."
11,,"as the WCT-1 project, the final dividend for 2..."
12,,Rs.0.50 per share.
13,Private Placement of Ordinary Shares to the Asian,
14,Development Bank,
15,,"Accordingly, the dividend declared for 2021/22..."
16,"In November 2021, the Company resolved to rais...",
17,,[2020/21: Rs.2.00 per share]. The final divide...
18,private placement of ordinary shares for a max...,
19,,before 22 June 2022. The Company payout ratio ...
20,of the LKR equivalent of USD 80 million to ADB...,
21,,with a total dividend outlay of ~Rs.2.01 billi...
22,"2022, the first phase of the above transaction...",
23,,The payout ratio is distorted due to the signi...
24,"JKH issued 65,042,006 ordinary shares at Rs.15...",
25,,exchange gains. Excluding the impact of the ex...
26,consideration of the LKR equivalent of USD 50 ...,
27,,ratio would be 35 per cent. The Group payout r...
28,issue dilution of 4.70 per cent post the first...,
29,,during the year [2020/21: 42 per cent].
30,"Additionally, in terms of the second phase, th...",
31,,The Group will follow its dividend policy whic...
32,"tradable/non-transferable options, entitling A...",
33,,"in profits, whilst ensuring that the Company m..."
34,"39,025,204 new ordinary shares of the Company,...",
35,,"ensure business continuity, particularly given..."
36,amount of up to a maximum of the LKR equivalen...,
37,,"circumstances, and fund its pipeline of strate..."
38,options exercise price would be based on the v...,
39,price of the Company's ordinary shares as quot...,
40,,Distributions to Shareholders and Payout Ratio
41,90 calendar days ending immediately prior to t...,(Rs.Bn)\nPayout (%)
42,subject to the floor price of Rs.165.00 and ca...,
43,,10\n60

Table 28:

,0,1,2,3,4,5,6,7
0,,,"circumstances, and fund its pipeline of strate...",,,,,
1,options exercise price would be based on the v...,,,,,,,
2,price of the Company's ordinary shares as quot...,,,,,,,
3,,,Distributions to Shareholders and Payout Ratio,,,,,
4,90 calendar days ending immediately prior to t...,(Rs.Bn),,,,,,Payout (%)
5,subject to the floor price of Rs.165.00 and ca...,,,,,,,
6,,10,,,,,,60
7,,,,54,,,,
8,exercisable between 19 October 2022 and 18 Jan...,,40,,,,,
9,,,,,49,,,
10,,,,,,,,50
11,,8,,,,,,
12,,,,,,41,,
13,"Based on the above, the maximum number of ordi...",,,,,,,40
14,,6,,,,,,
15,would potentially be issued under the entire t...,,,,,,,
16,,,,,,,,30
17,"options are subscribed for, will be 104,067,21...",,,,,,,
18,,4,,,,,,
19,,,,,,,,20
20,post-issue dilution on the conclusion of both ...,,,,,,,
21,,,,,,,10,
22,7.31 per cent.,2,,,,,,
23,,,,,,,,10
24,,,8.3,8.2,4.6,2.0,2.0,

Table 29:

,0,1,2,3,4
0,Share Information,,,,
1,Earnings Per Share,,,,
2,,,Market Capitalisation and Enterprise Value,,
3,The fully diluted earnings per share (EPS) for...,(Rs.bn),,,
4,by 318.0 per cent to Rs.15.12 per share [2020/...,,,,
5,,350,,,
6,increase in total profit attributable to equit...,,,,
7,,300,,,
8,"earnings basis, the diluted EPS increased to R...",,,,
9,,250,221,,
10,financial year from Rs.3.59 recorded in the pr...,,,206\n210,
11,representing a 324.9 per cent increase.,200,188,,152\n186
12,,150,,,
13,"However, it is noted that the benefit of highe...",,,,
14,,100,,,
15,partially offset through an increase in the is...,,,,
16,,50,,,
17,"Company in January 2022, in lieu of the privat...",,,,
18,,0,,,
19,"shares to ADB, as discussed above.",,,,
20,,,FY18,FY19,FY20

Table 30:

,0,1,2,3,4,5,6,7,8
0,,,,,,Summary Company Indicators,,,
1,Total Shareholder Return,,,,,,,,
2,,,,,,,2021/22,2020/21,2019/20
3,The total shareholder return (TSR) of the JKH ...,,,,,,,,
4,,,,,Market capitalisation,(Rs.billion),200.8,196.0,152.2
5,"for the period under review, while the total r...",,,,,,,,
6,,,,,Enterprise value,(Rs.billion),312.0,244.7,186.2
7,recorded a return of 11.2 per cent. On a cumul...,,,,,,,,
8,"holding period, the share inclusive of dividen...",,,,EV/EBITDA,(times),10.7,15.7,9.2
9,total return of 4.5 per cent.,,,,,,,,
10,,,,,Diluted EPS,(Rs.),15.1,3.6,7.1
11,,,,,PER,(diluted),9.6,41.0,16.2
12,Total Shareholder Return,,,,,,,,
13,(%),,,,,,,,
14,,,,,Price to book,(times),0.6,0.9,0.7
15,50,,,,Price/cash earnings,(times),4.7,13.2,10.7
16,40,,,,,,,,
17,,,,,Dividend yield,(%),1.0,1.0,3.0
18,,,30.0,,,,,,
19,30,27.5,,,,,,,
20,,,,24.6,,,,,
21,,,,,Group dividend,,,,
22,19.7,,,,,,,,
23,20,,,,,,,,
24,,,,26.3,payout ratio,(%),10.0,41.5,49.0
25,10,6.5,,,,,,,
26,,,,,Net assets per share,(Rs.),224.8,171.4,164.5
27,0,,,,,,,,
28,,,(2.8),(1.3),TSR,(%),(1.3),30.0,(23.8)
29,(10),,,,,,,,
30,(20),,,,,,,,

Table 31:

,0,1,2,3,4,5,6
0,Composition of Shareholders,,,,,,
1,,,31 March 2022,,,31 March 2021,
2,,Number of,Number of,%,Number of,Number of,%
3,,shareholders,shares,,shareholders,shares,
4,Non-Resident,,,,,,
5,Institutions,75,"492,439,810",36,89,"485,528,066",36
6,Individuals,237,"6,975,141",1,243,"6,952,365",1
7,Total Non-Resident,312,"499,414,951",36,332,"492,480,431",37
8,Resident,,,,,,
9,Institutions,731,"465,904,849",34,692,"408,263,803",31
10,Individuals*,"13,414","419,596,832",30,"13,182","418,919,717",32
11,Total Resident,"14,145","885,501,681",64,"13,874","827,183,520",63
12,Total,"14,457","1,384,916,632",100,"14,206","1,319,663,951",100

Table 32:

,0,1,2,3,4,5,6,7,8
0,Distribution of Shareholders,,,,,,,,
1,,,31 March 2022,,,,31 March 2021,,
2,,Number of,%,Number of,%,Number of,%,Number of,%
3,,shareholders,,shares held,,shareholders,,shares held,
4,"Less than or equal to 1,000","9,494",66,"2,077,696",0,"9,178",64,"2,086,693",0
5,"1,001 to 10,000","3,376",23,"12,204,165",1,"3,422",24,"12,270,037",1
6,"10,001 to 100,000","1,208",8,"38,368,241",3,"1,237",9,"38,224,468",3
7,"100,001 to 1,000,000",274,2,"87,756,601",6,256,2,"80,702,749",6
8,"Over 1,000,001",105,1,"1,244,509,929",90,113,1,"1,186,380,004",90
9,Total,"14,457",100,"1,384,916,632",100,"14,206",100,"1,319,663,951",100

Table 33:

,0,1,2,3,4,5
0,Director's Shareholding,,,Executive Director's Shareholding in Group Com...,,
1,,31 March 2022,31 March 2021,,Number of shares as at,
2,,,,,31 March 2022,
3,K Balendra*,"10,914,400","10,914,400",,,
4,,,,,K Balendra*,G Cooray
5,G Cooray,"208,587","207,105",,,
6,A Omar*,"100,000",-,Ceylon Cold Stores PLC,"802,320",-
7,N Fonseka,-,-,Asian Hotels and Properties PLC,-,"10,600"
8,A Cabraal,"150,137","45,137",Trans Asia Hotels PLC,-,"1,200"
9,P Perera,-,-,*Includes shareholding of spouse.,,
10,H Wijayasuriya,-,-,,,
11,*Includes shareholding of spouse.,,,,,

Table 34:

,0,1,2,3,4
0,,31 March 2022,,31 March 2021,
1,,Number of,%,Number of,%
2,,shares,,shares,
3,Paints and General Industries Limited,"140,437,428",10.14,"114,977,303",8.71
4,Mr S E Captain,"134,220,895",9.69,"150,769,641",11.42
5,Melstacorp PLC,"128,917,111",9.31,"128,917,111",9.77
6,HWIC Asia Fund,"119,200,760",8.61,"39,250,982",2.97
7,Asian Development Bank,"65,042,006",4.70,-,-
8,Citigroup Global Markets Limited Agency Tradin...,"61,904,939",4.47,"141,854,717",10.75
9,Schroder International Selection Fund,"41,974,590",3.03,"42,475,806",3.22
10,Mr R S Captain,"34,405,091",2.48,"35,544,282",2.69
11,Norges Bank Account 2,"31,901,605",2.30,"31,706,807",2.40
12,Aberdeen Standard Asia Focus PLC,"28,123,572",2.03,"23,873,572",1.81
13,Mr Kandiah Balendra,"19,511,476",1.41,"19,511,476",1.48
14,Employees Trust Fund Board,"18,499,897",1.34,"18,709,833",1.42
15,Fidelity Fund - Pacific,"17,880,904",1.29,"17,880,904",1.35
16,Mrs C S De Fonseka,"17,472,745",1.26,"16,952,586",1.28
17,Mrs S A J De Fonseka,"15,204,230",1.10,"15,204,230",1.15
18,Edgbaston Asian Equity Trust,"15,142,109",1.09,"14,809,382",1.12
19,Chemanex PLC,"12,605,234",0.91,"11,417,835",0.87
20,Sri Lanka Insurance Corporation Limited - Life...,"12,270,665",0.89,-,-
21,Mr K N J Balendra,"10,907,628",0.79,"10,907,628",0.83
22,Schroder Asian Growth Fund,"10,328,047",0.75,"10,328,047",0.78

Table 35:

,0,1,2,3,4,5,6
0,Share Capital,,,"GDR History (in terms of ordinary shares, mill...",,,
1,Year ended 31 March,Number of shares in,Year ended,Opening,Issued*,Converted/,Closing
2,,issue (million),31 March,balance,,repurchased,balance
3,2012,844.12,2012,0.95,0.32,0.08,1.19
4,2013,857.24,2013,1.19,-,0.06,1.13
5,2014,990.29,2014,1.13,-,0.01,1.12
6,2015,997.49,2015,1.12,-,-,1.12
7,2016,"1,189.40",2016,1.12,-,-,1.28
8,2017,"1,387.47",2017,1.12,0.2,-,1.32
9,2018,"1,387.53",2018,1.32,-,-,1.32
10,2019,"1,318.17",2019,1.32,-,-,1.32
11,2020,"1,318.55",2020,1.32,-,-,1.32
12,2021,"1,319.66",2021,1.32,-,-,1.32
13,2022,"1,384.92",2022,1.32,-,-,1.32

Table 36:

,0,1,2,3
0,Statement of Compliance under Section 7.6 of t...,,,
1,Disclosure,,,
2,MANDATORY PROVISIONS - FULLY COMPLIANT,,,
3,Rule,,Compliance,Reference (within the
4,,,Status,JKH Annual Report)
5,(i),Names of persons who were Directors of the Com...,Yes,Corporate Governance
6,,,,Commentary
7,(ii),Principal activities of the entity and its sub...,Yes,Management Discussion
8,,,,and Analysis
9,(iii),The names and the number of shares held by the...,Yes,
10,,shares and the percentage of such shares held,,
11,(iv),"The float adjusted market capitalisation, publ...",Yes,
12,,shareholders and under which option the Listed...,,
13,,,,Share Information
14,,Holding requirement.,,
15,,The public holding percentage in respect of no...,Not Applicable,
16,(v),A statement of each Director's holding and Chi...,Yes,
17,,Entity at the beginning and end of each financ...,,
18,(vi),Information pertaining to material foreseeable...,Yes,"Risk, Opportunities and"
19,,,,Internal Controls
20,(vii),Details of material issues pertaining to emplo...,Yes,"Sustainability Integration,"
21,,,,Stakeholder Engagement
22,,,,and Materiality
23,(viii),"Extents, locations, valuations and the number ...",Yes,
24,,,,Group Real Estate Portfolio
25,,investment properties,,
26,(ix),Number of shares representing the Entity's sta...,Yes,
27,(x),A distribution schedule of the number of holde...,Yes,
28,,,,Share Information
29,,percentage of their total holdings,,
30,(xi),Financial ratios and market price information,Yes,
31,(xii),Significant changes in the Company's or its su...,Yes,Notes to the Financial
32,,"land, if the value differs substantially from ...",,Statements
33,,(xiii) Details of funds raised through a publi...,Yes,
34,,the year,,Share Information
35,(xiv),Information in respect of Employee Share Owner...,Yes,
36,(xv),Disclosures pertaining to Corporate Governance...,Yes,Corporate Governance
37,,7.10.6 c. of Section 7 of the Listing Rules,,Commentary/Note 44 of
38,(xvi),Related Party transactions exceeding 10 per ce...,Yes,the Notes to the Financial
39,,the Entity as per audited financial statements...,,Statements

Table 37:

,0,1
0,Annual Report of the Board of Directors,
1,Capital Expenditure\nPrivate placement of ordi...,number of public shareholders are given in
2,The Company’s and Group’s capital \nIn Novembe...,the Share Information section of the Annual
3,"expenditure on property, plant and equipment \...",Report.
4,amounted to Rs.14 Mn (2021 - Rs.9 Mn) and \nor...,
...,...,...
106,,private companies which have not dispensed
107,Note 34.1 to the Financial Statements.,
108,"capitalisation, public holding percentage and",
109,,with the requirement to maintain an Interests
110,John Keells Holdings PLC | Annual Report 202...,

Table 38:

,0,1
0,Key audit matter,How our audit addressed the key audit matter
1,Assessment of fair value of land and buildings,Our audit procedures were based on the best av...
2,,at date of this report and focused on the valu...
3,"Property, Plant and Equipment and Investment P...",
4,,external valuer engaged by the Group. Our proc...
5,and buildings carried at fair value. The fair ...,
6,,following;
7,were determined by an external valuer engaged ...,
8,,"• We assessed the competency, capability and ..."
9,This was a key audit matter due to:,
10,,external valuer engaged by the Group.
11,• Materiality of the reported land & building...,
12,,• We read the external valuer’s report and un...
13,to Rs. 132 Bn and represent 18% of the total a...,
14,,made and the approach taken by the valuer in d...
15,"• \nThe degree of assumptions, judgements and ...",
16,,valuation of each land and building.
17,associated with fair valuation of land and bui...,
18,,• We assessed the reasonableness of the signi...
19,"comparable market transactions, and current ma...",
20,,"by the valuer and valuation techniques, per pe..."
21,"Key areas of significant judgments, estimates ...",
22,,per square foot used by the valuer in the valu...
23,the valuation of the land and buildings includ...,
24,,building.
25,• \nEstimate of per perch value of the land,
26,,We have also assessed the adequacy of the disc...
27,• \nEstimate of the per square foot value of t...,
28,,and 24 to the financial statements relating to...
29,,valuation techniques and estimates used by the...
30,Life insurance contract liabilities,To assess the reasonableness of the Life Insur...
31,,our audit procedures included amongst others t...
32,Life Insurance Contract Liabilities amounting ...,
33,,based on the best information available up to ...
34,represent 13% of total liabilities of the Grou...,
35,are determined based on an actuarial valuation...,• We involved the component auditor of the su...
36,to the financial statements.,perform the audit procedures to assess the rea...
37,,assumptions and test the controls on sample ba...
38,This was a key audit matter due to:,
39,,estimating the insurance contract liabilities.
40,• Materiality of the reported Life Insurance ...,
41,,• We involved the internal expert of componen...
42,"• \nThe degree of assumptions, judgements and ...",
43,,subsidiary company to assess the reasonablenes...
44,associated with the actuarial valuation of Lif...,
45,,used in the valuations of the insurance contra...
46,Liabilities; and,
47,,We assessed the adequacy of the disclosures ma...
48,• \nLiability adequacy test carried out to ens...,
49,,in the insurance contract liabilities.
50,carrying value of Life Insurance Contract Liab...,

Table 39:

,0,1,2,3,4,5
0,For the year ended 31 March,Note,2022,2021,2022,2021
1,In Rs.'000s,,,,,
2,Continuing operations,,,,,
3,Revenue from contracts with customers,,"202,849,175","114,454,483","1,875,722","1,637,063"
4,Revenue from insurance contracts,,"15,225,571","13,221,167",-,-
5,Total revenue,14,"218,074,746","127,675,650","1,875,722","1,637,063"
6,Cost of sales,,"(180,430,008)","(108,747,058)","(1,085,049)","(957,490)"
7,Gross profit,,"37,644,738","18,928,592","790,673","679,573"
8,Dividend income,15,-,-,"8,007,649","8,346,260"
9,Other operating income,16.1,"2,614,793","2,626,544","51,344","40,610"
10,Selling and distribution expenses,,"(5,732,694)","(4,761,037)",-,-
11,Administrative expenses,,"(14,762,643)","(12,927,716)","(1,283,215)","(1,050,270)"
12,Other operating expenses,16.2,"(12,456,008)","(1,314,409)","(514,478)","(21,473)"
13,Results from operating activities,,"7,308,186","2,551,974","7,051,973","7,994,700"
14,Finance cost,17,"(7,034,757)","(4,669,206)","(2,966,139)","(1,244,941)"
15,Finance income,17,"30,806,179","10,688,722","24,198,282","4,617,329"
16,Change in insurance contract liabilities,36.2,"(6,416,299)","(7,031,692)",-,-
17,Change in fair value of investment property,24,"(4,084,755)","(253,425)",-,-
18,Share of results of equity accounted investees...,27.3,"6,745,939","4,158,793",-,-
19,Profit before tax,,"27,324,493","5,445,166","28,284,116","11,367,088"
20,Tax expense,21.1,"(6,881,586)","(1,494,275)","(3,902,709)","(801,201)"
21,Profit for the year,,"20,442,907","3,950,891","24,381,407","10,565,887"
22,Attributable to:,,,,,
23,Equity holders of the parent,,"20,212,968","4,772,100",,
24,Non-controlling interests,,"229,939","(821,209)",,
25,,,"20,442,907","3,950,891",,

Table 40:

,0,1
0,9. \n Basis of consolidation and material part...,Profit or loss and each component of other com...
1,subsidiaries,(OCI) are attributed to the equity holders of ...
2,Accounting policy,"and to the non-controlling interests, even if ..."
3,,controlling interests having a deficit balance...
4,Basis of consolidation,
5,,of the subsidiaries are prepared for the same ...
6,The consolidated financial statements comprise...,
7,,"parent Company, which is 12 months ending 31 M..."
8,statements of the Group and its subsidiaries a...,
9,,accounting policies.
10,period. Control over an investee is achieved w...,
11,"exposed, or has rights, to variable returns fr...",
12,,Transactions eliminated on consolidation
13,investee and has the ability to affect those r...,
14,,"All intra-group assets, liabilities, equity, i..."
15,over the investee.,
16,,flows relating to transactions between members...
17,,eliminated in full on consolidation. A change ...
18,Control over an investee,
19,,"of a subsidiary, without a loss of control, is..."
20,"Specifically, the Group controls an investee i...",
21,,transaction.
22,"• \nPower over the investee (i.e., existing ri...",
23,,Loss of control
24,ability to direct the relevant activities of t...,
25,,"If the Group loses control over a subsidiary, ..."
26,"• \nExposure, or rights, to variable returns f...","assets (including goodwill), liabilities, nonc..."
27,investee,components of equity while any resultant gain ...
28,,the income statement. Any investment retained ...
29,• \nThe ability to use its power over the inve...,
30,,value.
31,returns,
32,Consolidation of entities in which the Group h...,The total profits and losses for the year of t...
33,majority of voting rights,subsidiaries included in consolidation are sho...
34,,income statement and consolidated statement of...
35,When the Group has less than a majority of the...,
36,,income and all assets and liabilities of the C...
37,"of an investee, the Group considers all releva...",
38,,subsidiaries included in consolidation are sho...
39,in assessing whether it has power over an inve...,
40,,Statement of Financial Position.
41,• \nThe contractual arrangement with the other...,
42,investee;,Non-controlling interest (NCI)
43,,Non-controlling interest which represents the ...
44,• \nRights arising from other contractual arra...,
45,,"and net assets not held by the Group, are show..."
46,• \nThe Group’s voting rights and potential vo...,profit for the year in the consolidated income...
47,,of comprehensive income and as a component of ...
48,Subsidiaries that are consolidated have been l...,
49,,"consolidated statement of financial position, ..."
50,directory under Supplementary section of the a...,
51,,attributable to the shareholders of the parent.
52,"The following companies, with equity control e...",
53,,The Consolidated Statement of Cash Flow includ...
54,have been consolidated as subsidiaries based o...,
55,,Company and its subsidiaries.

Table 41:

,0,1,2,3,4
0,Names of material partly-owned subsidiaries an...,,,,"Accounting judgements,estimates and assumptions"
1,owned by non-controlling interest:,,,,Consolidation of entities in which the Group h...
2,,,,majority of voting right (de facto control).,
3,Material partly-owned subsidiary,2022,2021,,
4,,,,,The Group considers that it controls some subs...
...,...,...,...,...,...
67,,,,,asset or liability that is a financial instrum...
68,Yala Village (Pvt) Ltd,24.67%,24.67%,,
69,,,,,"SLFRS 9 Financial Instruments, is measured at ..."
70,,,,,in fair value recognised in the Income Stateme...
71,,,,SLFRS 9.,

Table 42:

,0,1
0,Notes to the Financial Statements,
1,10. \nBusiness combinations and acquisitions ...,
2,interests (Contd.),
3,Other contingent consideration that is not wit...,10.1 \nInvestment in subsidiaries
4,measured at fair value at each reporting date ...,Waterfront Properties (Pvt) Ltd (WPL)
5,recognised in profit or loss.,John Keells Holdings PLC (JKH) further investe...
6,,"Rs.8,418 Mn) in WPL, a subsidiary of JKH invol..."
7,"After initial recognition, goodwill is measure...","managing, operating, selling, leasing and rent..."
8,accumulated impairment losses. Goodwill is rev...,use Integrated Resort.
9,annually or more frequently if events or chang...,
10,indicate that the carrying value may be impaired.,J K Land (Pvt) Ltd (J K Land)
11,,John Keells Holdings PLC (JKH) further investe...
12,"For the purpose of impairment testing, goodwil...",increase its shareholding in Vauxhall Land Dev...
13,"combination is, from the acquisition date, all...",
14,Group’s cash generating units that are expecte...,Vauxhall Land Developments (Pvt) Ltd (VLD)
15,"combination, irrespective of whether other ass...","John Keells Holdings PLC, through JK Land (Pvt..."
16,acquiree are assigned to those units.,committed consideration to acquire the remaini...
17,,VLD from Finlays Colombo Limited for a conside...
18,Impairment is determined by assessing the reco...,
19,the cash-generating unit to which the goodwill...,John Keells Property Developments (Pvt) Ltd
20,recoverable amount of the cash generating unit...,John Keells Property Developments (Pvt) Ltd di...
21,"amount, an impairment loss is recognised. The ...","land in Tickell Road, Colombo 8 for a consider..."
22,allocated first to reduce the carrying amount ...,company is under liquidation.
23,to the unit and then to the other assets pro-r...,
24,of each asset in the unit. Goodwill and fair v...,10.2 Investment in equity accounted investees
25,the acquisition of a foreign operation are tre...,Colombo West International Container Terminal ...
26,of the foreign operation and translated at the...,"John Keells Holdings PLC invested Rs.2,856 Mn ..."
27,,"Build, Own and Transfer (BOT) Agreement betwee..."
28,Where goodwill forms part of a cash-generating...,Authority and CWIT. JKH has a 34% stake in CWI...
29,"operation within that unit is disposed of, the...",investor Adani Ports and Special Economic Zone...
30,with the operation disposed of is included in ...,of 51%.
31,the operation when determining the gain or los...,
32,"operation, goodwill disposed in this circumsta...",Inchcape Mackinnon Mackenzie Shipping (Pvt) Lt...
33,the relative values of the operation disposed ...,John Keells Holdings PLC invested Rs.16 Mn in ...
34,cash-generating unit retained.,venture agreement entered into with ISS Group ...
35,,investment gives JKH the right to 60% of the s...
36,Impairment of goodwill,
37,Goodwill is tested for impairment annually (as...,Saffron Aviation (Pvt) Ltd (Saffron)
38,circumstances indicate that the carrying value...,John Keells Holdings PLC (JKH) further investe...
39,Impairment is determined for goodwill by asses...,operating company of the domestic aviation ope...
40,amount of each cash-generating unit (or group ...,
41,to which the goodwill relates. Where the recov...,
42,generating unit is less than their carrying am...,
43,recognised. Impairment losses relating to good...,
44,future periods.,

Table 43:

,0,1,2,3,4,5,6,7,8
0,,The maximum risk positions of financial assets...,,,,,,,
1,,"(without consideration of collateral, if avail...",,,,,,,
2,As at 31 March,,,,,2022,,,
3,In Rs.‘000s,Notes,Non,Cash in,Trade,Short term,Amounts,Total,
4,,,current,hand and,and other,investments,due from,,f
5,,,financial,at bank,receivables,,related,,allocation
6,,,assets,,,,parties,,
7,Group,,,,,,,,
8,Government securities,11.1.2,"31,752,878",-,-,"10,704,129",-,"42,457,007",18%
9,Corporate debt securities,11.1.3,"9,553,315",-,-,"1,454,315",-,"11,007,630",5%
10,Deposits with banks,11.1.4,"632,491",-,-,"95,936,007",-,"96,569,378",41%
11,Loans to executives,11.1.5,"1,048,842",-,"326,682",-,-,"1,375,524",1%
12,Loans to life policyholders,11.1.6,"1,952,394",-,-,-,-,"1,952,394",1%
13,Preference Shares,11.1.7,"373,701",-,-,-,-,"373,701",0%
14,Interest rate swap,11.1.8,"2,928,815",-,-,-,-,"2,928,815",1%
15,Trade and other receivables,11.1.9,-,-,"25,550,066",-,-,"25,550,066",11%
16,Reinsurance receivables,11.1.10,-,-,"1,135,652",-,-,"1,135,652",0%
17,Assets backed securities,11.1.11,"314,304",-,-,-,-,"314,304",0%
18,Premium receivable,11.1.12,-,-,"482,948",-,-,"482,948",0%
19,Amounts due from related parties,11.1.13,-,-,-,-,"196,394","196,394",0%
20,Cash in hand and at bank,11.1.14,-,"52,376,531",-,-,-,"52,376,531",22%
21,Total credit risk exposure,,"48,556,740","52,376,531","27,495,348","108,095,331","196,394","236,406,039",100%

Table 44:

,0,1,2,3,4,5,6
0,,,,2021,,,
1,Non,Cash in,Trade,Short term,Amounts,Total,
2,current,hand and,and other,investments,due from,,f
3,financial,at bank,receivables,,related,,allocation
4,assets,,,,parties,,
5,"29,703,638",-,-,"10,455,199",-,"40,158,837",24%
6,"9,955,243",-,-,"1,290,325",-,"11,245,568",7%
7,"18,871,021",-,-,"54,045,971",-,"72,916,992",44%
8,"990,562",-,"341,838",-,-,"1,332,400",1%
9,"1,840,841",-,-,-,-,"1,840,841",1%
10,"351,430",-,-,-,-,"351,430",0%
11,"729,316",-,-,-,-,"729,316",1%
12,-,-,"16,192,825",-,-,"16,192,825",10%
13,-,-,"589,306",-,-,"589,306",0%
14,-,-,-,-,-,-,-
15,-,-,"332,729",-,-,"332,729",0%
16,-,-,-,-,"123,553","123,553",0%
17,-,"19,432,579",-,-,-,"19,432,579",12%
18,"62,442,051","19,432,579","17,456,698","65,791,495","123,553","165,246,376",100%

Table 45:

                 0            1      2            3     4
0                                GROUP
1   As at 31 March         2022                2021
2    Fitch ratings  In Rs.’000s      %  In Rs.’000s     %
3              AAA            -      -      158,965    1%
4               AA      959,461     9%    1,307,864   12%
5              AA-      863,526     8%    1,074,244   10%
6               A+      895,622     8%      665,947    6%
7                A    2,407,965    22%    2,665,685   24%
8               A-    2,179,836    20%    2,128,541   19%
9              BBB      114,312     1%      168,264    1%
10            BBB+    3,212,371    29%    3,076,058   27%
11              B-      158,934     1%            -     -
12              CC      215,603     2%            -     -
13           Total   11,007,630   100%   11,245,568  100%

Table 46:

,0,1,2,3,4,5,6,7,8
0,,,GROUP,,,,COMPANY,,
1,As at 31 March,2022,,2021,,2022,,2021,
2,Fitch ratings,In Rs.,%,In Rs.,%,In Rs.,%,In Rs.,%
3,,’000s,,’000s,,’000s,,’000s,
4,AAA,-,-,"2,358,274",3%,-,-,-,-
5,AA+,-,-,"367,612",0%,-,-,-,-
6,AA-,"80,016,461",83%,"64,608,594",89%,"54,088,324",64%,"62,764,844",97%
7,A+,"1,120,113",1%,"4,238,545",6%,-,-,"2,216,480",3%
8,A,"6,187,339",7%,"591,766",1%,"21,689,059",26%,-,-
9,A-,"985,225",1%,-,-,-,-,-,-
10,B,-,-,"752,201",1%,-,-,-,-
11,CC,"8,260,240",8%,-,-,"8,195,277",10%,-,-
12,Total,"96,569,378",100%,"72,916,992",100%,"83,972,660",100%,"64,981,324",100%

Table 47:

                                                    0
0   11.3.2  \n Foreign currency risk \n11.3.2.1 Ef...
1   Foreign currency risk is the risk that the fai...
2   of a financial instrument will fluctuate becau...
3   exchange rates. The Group has exposure to fore...
4   has cash flows in overseas operations and fore...
5   which are affected by foreign exchange movemen...
6   analyses the market condition of foreign excha...
7   updates to the Group Executive Committee (GEC)...
8   external consultants' advice. Based on the sug...
9   treasury the GEC takes decisions on whether to...
10  forward bookings of foreign currency as per de...
11                                Board of Directors.
12                                     GROUP\nCOMPANY
13  For the year ended 31 March\nIncrease/(decreas...
14  in exchange rate USD\nbefore tax \nRs.‘000s\nb...
15                                 Rs.‘000s\nRs.‘000s
16  2022\n+52%\n23,158,974\n88,861,968\n27,672,121...
17  -52%\n(23,158,974)\n(88,861,968)\n(27,672,121)...
18   + 7%\n 2,186,890 \n7,286,362\n 763,078 \n-\n2021
19     - 7%\n (2,186,890)\n(7,286,362)\n (763,078)\n-
20  Assumptions\na Group level, the translation ri...
21  The assumed spread of the exchange rate is bas...
22  observable market environment.\nUS Dollar cash...
23  obligations can be managed through US Dollar d...
24  The Sri Lankan Rupee witnessed significant vol...
25  the latter part of the year. Whilst the exchan...
26  level during the year, as per the guidelines i...
27  Central Bank of Sri Lanka (CBSL), the currency...
28  March 2022 once the CBSL allowed a free float ...
29  resulted in a steep depreciation of the Rs. by...
30  to the depreciation of the currency, there wer...
31  in the foreign currency market on the back of ...
32  in liquidity amidst declining confidence and a...
33  currency reserves in the country. This resulte...
34  such as the continuation of certain import con...
35  foreign currency conversions and remittances. ...
36  in the market however resulted in a sharp redu...
37  employment remittances which exacerbated the l...
38  Group adopted prudent measures, as and when re...
39  the financial impacts arising from the liquidi...
40  fluctuations by matching liabilities with corr...

Table 48:

                                  0          1      2          3     4
0                                               GROUP
1                    As at 31 March       2022              2021
2                                     Rs.’000s      %   Rs.’000s     %
3                             Banks    369,346    14%  1,400,564   40%
4                     Capital goods    972,803    37%    675,286   20%
5     Consumer durables and apparel    653,667    25%    347,799   10%
6                 Consumer services     52,532     2%     23,841    1%
7        Food and staples retailing          -      -    269,082    8%
8         Food beverage and tobacco    197,718     7%    565,561   16%
9                         Materials     69,533     3%          -     -
10       Telecommunication services    259,743    10%    189,133    5%
11             Application Software     25,258     1%          -     -
12  Household and Personal Products      4,527     0%          -     -
13                    Transpotation     21,086     1%          -     -
14                                   2,626,213   100%  3,471,266  100%

Table 49:

,0,1,2,3
0,,Company's profit before tax and equity due to ...,,
1,,,GROUP,
2,For the year ended 31 March,Change in year-end,Effect on profit,Effect on equity
3,,market price index,before tax Rs.‘000s,Rs.‘000s
4,2022,+28%,"1,103,009",-
5,,- 28%,"(1,103,009)",-
6,2021,+42%,"1,457,932",-
7,,-42%,"(1,457,932)",-

Table 50:

,0,1
0,"115,182,320\n 71,088,127\n72,723,502\n 47,582,533",
1,"Notes to the Income Statement, Statement of Co...",Services transferred over time
2,Income and Statement of Financial Position,"Under SLFRS 15, the Group determines, at contr..."
3,14. \nRevenue,satisfies the performance obligation over time...
4,Accounting policy,each performance obligation satisfied over tim...
5,14.1 Total revenue,the revenue over time by measuring the progres...
6,14.1.1 Revenue from contract with customers,satisfaction of that performance obligation.
7,Revenue from contracts with customers is recog...,
8,the goods or services is transferred to the cu...,14.1.2 Revenue from insurance contracts
9,reflects the consideration to which the Group ...,Revenue from insurance contracts comprise of g...
10,exchange for those goods or services.,net of premium ceded to reinsurers.
11,Goods transferred at a point in time,14.2 Disaggregation of revenue
12,"Under SLFRS 15, revenue is recognised upon sat...",The Group presented disaggregated revenue with...
13,performance obligation. The revenue recognitio...,segments based on timing of revenue recognitio...
14,time when control of the asset is transferred ...,region in the operating segment information se...
15,on delivery of the goods.,

Table 51:

,0,1
0,Property,Others
1,Property segment concentrates primarily on pro...,Others represents companies in the Plantation ...
2,"renting of commercial office spaces,selling co...","Technology, Management and Investments compani..."
3,management of the Group’s real estate.,"streams of revenue; Management fees, BPO servi..."
4,,"fees, are recognised over a period of time, de..."
5,"At inception of the contract, the entity deter...",agreements.
6,the performance obligation over time or at a p...,
7,amount of cashflow will be determined accordin...,Some contracts include multiple deliverables. ...
8,,"include multiple performance obligations, the ..."
9,Financial Services,be allocated to each performance obligation ba...
10,Financial Services provides a complete range o...,alone selling prices. Where these are not dire...
11,"including commercial banking, insurance, stock...",estimated based on expected cost plus margin.
12,fund management and leasing. The services unde...,
13,identified as one performance obligation.,Remaining performance obligations
14,,The Group applies the practical expedient and ...
15,Entity determines at contract inception whethe...,amount of the transaction price allocated to t...
16,performance obligation over time or at a point...,obligations and an explanation of when the Gro...
17,"performance obligation satisfied overtime, the...",that amount as revenue for the year ended 31 M...
18,revenue over time by measuring the progress to...,
19,satisfaction of that performance obligation. T...,
20,provide a faithful depiction in recognising re...,
21,15. \nDividend income,
22,Accounting policy,
23,Dividend,
24,Dividend income is recognised when right to re...,
25,,COMPANY
26,For the year ended 31 March,2022\n2021
27,In Rs.‘000s,
28,Dividend income from investments in subsidiari...,"8,007,649\n 8,346,260"
29,16. \nOther operating income and other operat...,Gains and losses arising from activities incid...
30,Accounting policy,generating activities and those arising from a...
31,Gains and losses,"transactions, which are not material are aggre..."
32,Net gains and losses of a revenue nature arisi...,presented on a net basis.
33,"property, plant and equipment and other non-cu...",
34,,Any losses arising from guaranteed rentals are...
35,"investments in subsidiaries, joint ventures an...",
36,,year of incurring the same. A provision is rec...
37,"in the income statement, after deducting from ...",
38,,indicates a loss.
39,the carrying amount of such assets and the rel...,
40,,Other income and expenses

Table 52:

,0,1
0,Notes to the Financial Statements,
1,16. \nOther operating income and other operat...,
2,16.2 Other operating expenses,
3,,GROUP\nCOMPANY
4,For the year ended 31 March,2022\n2021\n2022\n2021
5,In Rs.'000s,
6,Provision for impairment,"4,886,733\n 69,660 \n 506,246 \n -"
7,"Loss on sale of property, plan and equipment","-\n6,005\n-\n-"
8,"Heat, light and power","800,684 \n 472,037 \n - \n -"
9,Exchange loss,"5,738,298 \n - \n - \n-"
10,Other overheads,"1,030,293\n 766,707 \n 8,232 \n 21,473"
11,,"12,456,008\n 1,314,409 \n 514,478 \n 21,473"
12,The Group has recognised Rs.4.7 Bn impairment ...,
13,investment.,
14,The Company has recognized Rs.506 Mn impairmen...,
15,17. \nNet finance income,Finance costs
16,Accounting policy,Finance costs comprise interest expense on bor...
17,Finance income,"the discount on provisions, losses on disposal..."
18,Finance income comprises of interest income on...,"financial assets, fair value losses on financi..."
19,"dividend income, gains on the disposal of fair...","profit or loss, impairment losses recognised o..."
20,"financial assets, fair value gains on financia...",than trade receivables) that are recognised in...
21,"profit or loss, gains on the remeasurement to ...",
22,existing interest in an acquiree that are reco...,Interest expense is recorded as it accrues usi...
23,statement.,"rate (EIR), which is the rate that exactly dis..."
24,,cash payments through the expected life of the...
25,Interest income is recorded as it accrues usin...,"a shorter period, where appropriate, to the ne..."
26,"rate (EIR), which is the rate that exactly dis...",financial liability.
27,cash receipts through the expected life of the...,
28,"a shorter period, where appropriate, to the ne...",Borrowing costs directly attributable to the a...
29,financial asset. Interest income is included i...,production of an asset that necessarily takes ...
30,income statement.,to get ready for its intended use or sale are ...
31,,of the respective assets. All other borrowing ...
32,,period they occur. Borrowing costs consist of ...
33,,that the Group incurs in connection with the b...

Table 53:

,0,1,2,3,4,5
0,,,GROUP,,COMPANY,
1,For the year ended 31 March,,2022,2021,2022,2021
2,In Rs.'000s,,,,,
3,Finance cost,,,,,
4,Interest expense on borrowings,,"(5,199,990)","(2,891,345)","(2,966,139)","(1,244,941)"
5,Finance charge on lease liabilities,,"(1,511,437)","(1,503,908)",-,-
6,Realised loss on financial assets at fair valu...,,-,"(273,953)",-,-
7,Unrealised loss on financial assets at fair va...,,"(323,330)",-,-,-
8,Total finance cost,,"(7,034,757)","(4,669,206)","(2,966,139)","(1,244,941)"
9,Net finance income,,"23,771,422","6,019,516","21,232,143","3,372,388"
10,18. \nProfit before tax,,For the purpose of presentation of the income ...,,,
11,Accounting policy,,"of expenses” method has been adopted, on the b...",,,
12,Expenditure recognition,,fairly the elements of the Company’s and Group...,,,
13,Expenses are recognised in the income statemen...,,,,,
14,direct association between the cost incurred a...,,,,,
15,items of income. All expenditure incurred in t...,,,,,
16,"and in maintaining the property, plant and equ...",,,,,
17,efficiency has been charged to the income stat...,,,,,
18,,,GROUP,,COMPANY,
19,For the year ended 31 March,,2022,2021,2022,2021
20,In Rs.'000s,,,,,
21,Profit before tax,,,,,
22,Profit before tax is stated after charging all...,,,,,
23,Remuneration to executive directors,,"391,034","346,453","106,238","103,808"
24,Remuneration to non executive directors,,"45,795","34,749","15,960","11,460"
25,Costs of defined employee benefits,,,,,
26,Defined benefit plan cost,,"400,450","438,382","22,766","21,709"
27,Defined contribution plan cost - EPF and ETF,,"1,182,147","1,068,968","72,880","56,332"
28,Other long term employee benefits cost,,"183,704","213,027","42,891","44,043"
29,Staff expenses,,"15,568,605","13,621,362","587,596","476,165"
30,Share based payments,,"204,618","225,007","61,117","66,035"
31,Auditors’ remuneration,,,,,
32,Audit,,"52,604","49,352","7,048","6,712"
33,Non-audit,,"10,733","6,202","4,565","1,018"
34,"Depreciation of property, plant and equipment",,"5,014,204","4,725,534","38,590","42,629"
35,Amortisation of intangible assets,,"703,906","641,563","33,324","30,631"
36,Amortisation of right of use assets,,"2,841,789","2,619,179",-,-
37,Provision for impairment,,"4,886,733","69,660","506,246",-
38,"(Gain) / Loss on sale of property, plant and e...",,"(62,198)","6,005","(2,532)",-
39,Donations,,"8,511","7,074","3,386","5,000"
40,19. \nEarnings per share,,parent (after adjusting for outstanding share ...,,,
41,,,average number of ordinary shares outstanding ...,,,
42,Accounting policy,,the weighted average number of ordinary shares...,,,
43,Basic EPS is calculated by dividing the profit...,,on conversion of all the dilutive potential or...,,,
44,ordinary equity holders of the parent by the w...,shares.,,,,
45,of ordinary shares outstanding during the year...,,,,,
46,by dividing the profit attributable to ordinar...,,,,,

Table 54:

,0,1,2,3,4,5
0,Notes to the Financial Statements,,,,,
1,19.1 Basic earnings per share,,,,,
2,,,,,GROUP,
3,For the year ended 31 March,,,Note,2022,2021
4,Profit attributable to equity holders of the p...,,,,"20,212,968","4,772,100"
5,Weighted average number of ordinary shares,,,19.3,"1,336,027","1,318,805"
6,Basic earnings per share,,,,15.13,3.62
7,19.2 Diluted earnings per share,,,,,
8,Profit attributable to equity holders of the p...,,,,"20,212,968","4,772,100"
9,Adjusted weighted average number of ordinary s...,,,19.3,"1,336,427","1,318,805"
10,Diluted earnings per share,,,,15.12,3.62
11,19.3 Amount used as denominator,,,,,
12,,,,,GROUP,
13,For the year ended 31 March,,,,2022,2021
14,Number of shares,,,,,
15,In '000s,,,,,
16,Ordinary shares at the beginning of the year,,,,"1,319,664","1,318,551"
17,Effect of share options exercised,,,,103,254
18,Private placement of ordinary shares,,,,"16,260",-
19,Weighted average number of ordinary shares in ...,,,,"1,336,027","1,318,805"
20,Effects of dilution from:,,,,,
21,Share option scheme,,,,400,-
22,Adjusted weighted average number of ordinary s...,,,,"1,336,427","1,318,805"
23,20. \nDividend per share,,,,,
24,,,,,COMPANY,
25,For the year ended 31 March,,,2022,,2021
26,,,Rs,In Rs.‘000s,Rs,In Rs.‘000s
27,Equity dividend on ordinary shares declared an...,,,,,
28,Final dividend (Previous years’ final dividend...,,0.50,,"659,869 \n-",-
29,Interim dividends,,1.00,"1,352,323",1.50,"1,978,317"
30,Total dividend,,1.50,"2,012,192",1.50,"1,978,317"
31,21. \nTaxes,,,,,
32,Accounting policy,,,,,
33,Current tax,,,,,
34,Current tax assets and liabilities for the cur...,,Management has used its judgment on the applic...,,,
35,measured at the amount expected to be recovere...,,including transfer pricing regulations involvi...,,,
36,the taxation authorities. The tax rates and ta...,,"associated undertakings, estimation of the res...",,,
37,the amount are those that are enacted or subst...,,and selection of appropriate pricing mechanisms.,,,
38,reporting date in the countries where the Grou...,,,,,
39,taxable income.,,The Group has complied with the arm’s length p...,,,
40,,,transfer pricing as prescribed in the Inland R...,,,
41,Current income tax relating to items recognise...,,,,,
42,recognised in equity and for items recognised ...,Deferred tax,,,,
43,income shall be recognised in other comprehens...,,Deferred tax is provided using the liability m...,,,
44,the income statement. Management periodically ...,,differences at the reporting date between the ...,,,
45,taken in the tax returns with respect to situa...,,liabilities and their carrying amounts for fin...,,,
46,tax regulations are subject to interpretation ...,,,,,
47,where appropriate.,,,,,

Table 55:

,0,1
0,21.7 Economic Service Charge (ESC),
1,,GROUP
2,For the year ended 31 March,2022\n2021
3,In Rs.'000s,
4,Irrecoverable Economic Service Charge (ESC),"245,821\n 163,682"
5,,"245,821\n 163,682"
6,21.8 Tax losses carried forward,
7,,GROUP\nCOMPANY
8,For the year ended 31 March,2022\n2021\n2022\n2021
9,In Rs.'000s,
10,Tax losses brought forward,"11,302,534 \n 6,643,853 \n 1,230,471 \n 1,230,471"
11,Adjustments on finalisation of liability,"189,281 \n (113,857)\n - \n -"
12,Tax losses arising during the year,"6,486,569 \n 7,430,517 \n - \n -"
13,Utilisation of tax losses,"(1,820,782)\n (2,657,979)\n - \n -"
14,,"16,157,602 \n11,302,534\n 1,230,471 \n 1,230,471"
15,"The Group has tax losses amounting to Rs.16,15...",
16,which the tax losses arose.,
17,21.9 Applicable rates of income tax,
18,The tax liability of resident companies are co...,
19,exemptions and concessions.,
20,Company / Sector,Basis\nExemptions \nPeriod
21,,or
22,,concessions
23,Exemptions / concessions granted under the Inl...,
24,John Keells Properties Ja-Ela (Pvt) Ltd,New undertaking engaged in construction of \nE...
25,,commercial buildings
26,Saffron Aviation (Pvt) Ltd,Domestic airline \n- do -\n8 years from 1st ye...
27,,years from operations
28,Sancity Hotels & Properties Ltd (Subsidiary of,Construction and operation of a tourist hotel\...
29,Capitol Hotel Holdings (Pvt) Ltd),years from operations
30,John Keells Information Technology (Pvt) Ltd,Information technology services \n- do -\nOpen...
31,John Keells International (Pvt) Ltd,Exporting services \n- do -\n- do -
32,Infomate (Pvt) Ltd,Exporting services \n- do -\n- do -
33,Ceylon Cold Stores PLC,Foreign sourced income\n- do -\n- do -
34,John Keells Office Automation (Pvt) Ltd,Off shore business income\n- do -\n- do -
35,Tea Smallholder Factories PLC,Agro Processing\n14%\n- do -
36,Lanka Marine Services (Pvt) Ltd,Qualified export profits \n- do -\n- do -
37,Leisure sector,Promotion of tourism \n- do -\n- do -
38,Mackinnons Mackenzie shipping (Pvt) Ltd,Shipping agent\n- do -\n- do -
39,Consumer Foods sector,Manufacturing\n18%\nOpen ended

Table 56:

,0,1,2,3
0,21. \nTaxes (Contd.),,,
1,21.9 Applicable rates of income tax (Contd.),,,
2,Company / Sector,Basis,Exemptions,Period
3,,,or,
4,,,concessions,
5,Asian Hotels and Properties PLC,"Construction and operation of office, apartment",2% of,15 years from 1 April 2014
6,,complex and a hotel,turnover,
7,Beruwala Holiday Resorts (Pvt) Ltd,Construction and operation of a tourist hotel,Exempt,8 years from 1 year of profit or 2
8,,,,years from operations
9,John Keells Logistics (Pvt) Ltd (Sites covered,Warehousing,- do -,- do -
10,by the BOI agreement),,,
11,Waterfront Properties (Pvt) Ltd,Integrated super luxury tourist resort,Exempt,10 years from 1st year of profit or 3
12,,,,years from operations
13,Capital gains from sale of listed shares are e...,,,
14,exempt from income tax. Effective from 1 Janua...,,,
15,"opened with the approval of the Central Bank, ...",,,
16,the payments is received in foreign currency t...,,,
17,tax at a concessionary rate of 14% and an exem...,,,
18,"attributable to, or derived from, another divi...",,,

Table 57:

,0,1,2
0,"attributable to, or derived from, another divi...",,
1,21.10 Income tax rates of off-shore subsidiaries,,
2,Country of incorporation,Company,Rate
3,India,John Keells Foods India (Pvt) Ltd,30.9%
4,Mauritius,John Keells BPO Holdings (Pvt) Ltd,3%(Effective)
5,,John Keells BPO International (Pvt) Ltd,3%(Effective)
6,Republic of Maldives,Fantasea World Investments (Pte) Ltd,15%
7,,Tranquility (Pte) Ltd,15%
8,,Travel Club (Pte) Ltd,15%
9,,John Keells Maldivian Resorts (Pte) Ltd,15%
10,,Mack Air Services Maldives (Pte) Ltd,15%
11,Singapore,John Keells Singapore (Pte) Ltd,17% (Max)

Table 58:

,0,1
0,Singapore\nJohn Keells Singapore (Pte) Ltd,17% (Max)
1,"22. \nProperty, plant and equipment",plant and equipment and borrowing costs for lo...
2,Accounting policy,projects if the recognition criteria are met. ...
3,Basis of recognition,plant and equipment are required to be replace...
4,"Property, plant and equipment are recognised i...","derecognises the replaced part, and recognises..."
5,economic benefits associated with the asset wi...,own associated useful life and depreciation. L...
6,the cost of the asset can be reliably measured.,"inspection is performed, its cost is recognise..."
7,,the plant and equipment as a replacement if th...
8,Basis of measurement,satisfied. All other repair and maintenance co...
9,"Property, plant and equipment except for land ...",income statement as incurred.
10,at cost less accumulated depreciation and any ...,

Table 59:

,0,1,2,3,4,5,6,7
0,,,,,square foot,rate,,
1,Freehold property,,,,,,,
2,Ahungalla Holiday Resort Ltd,S Fernando,DCC,"Rs.260,000 -",-,,-,Positive
3,,,,"Rs.420,000",,,,
4,Asian Hotels and Properties PLC,P B Kalugalagedara,IM,-,-,,6%,Negative
5,Ceylon Cold Stores PLC,-do-,OMV,"Rs.1,650,000","Rs.1,000 -",,-,Positive
6,,,,,"Rs.2,000",,,
7,Facets (Pvt) Ltd,S Fernando,DCC,"Rs.475,000",-,,-,Positive
8,Glennie Properties (Pvt) Ltd,P B Kalugalagedara,OMV,"Rs.16,000,000",-,,-,Positive
9,John Keells Properties Ja-Ela (Pvt) Ltd,-do-,DCC,"Rs.1,300,000","Rs.4,500",,-,Positive
10,John Keells PLC,-do-,OMV,"Rs. 700,000",-,,-,Positive
11,J K Thudella Properties (Pvt) Ltd,P P T Mohideen,OMV,"Rs.300,000",-,,-,Positive
12,Keells Realtors Ltd,P B Kalugalagedara,DCC,"Rs.1,600,000 -",Rs.500 -,,-,Positive
13,,,,"Rs.2,500,000","Rs.1,500",,,

Table 60:

,0,1,2
0,"- \n 738,596 \n 1,260,734","4,852,978","97,522"
1,"Accounting judgments, estimates and assumptions",Gross margins,
2,,,The basis used to determine the value assigned...
3,Impairment of goodwill,,
4,,,gross margins is the gross margins achieved in...
5,Impairment exists when the carrying value of a...,,
6,,,budgeted year adjusted for projected market co...
7,generating unit exceeds its recoverable amount...,,
8,of its fair value less costs to sell and its v...,,
9,,Discount rates,
10,less costs to sell calculation is based on ava...,,
11,,,"The discount rate used is the risk free rate, ..."
12,"market, in an arm’s length transaction, of sim...",,
13,,appropriate risk premium.,
14,market prices less incremental costs for dispo...,,
15,in use calculation is based on a discounted ca...,,
16,,Inflation,
17,flows are derived from the budget for the next...,,
18,,,The basis used to determine the value assigned...
19,include restructuring activities that the Grou...,,
20,,,"inflation, is the inflation rate, based on pro..."
21,significant future investments that will enhan...,,
22,of the cash generating unit being tested. The ...,,
23,,Volume growth,
24,most sensitive to the discount rate used for t...,,
25,,,Volume growth has been budgeted on a reasonabl...
26,model as well as the expected future cash infl...,,
27,,,by taking into account the industry growth rat...
28,used for extrapolation purposes.,,
29,,,immediately subsequent to the budgeted year. C...
30,,five year period are extrapolated using 0% gro...,
31,The key assumptions used to determine the reco...,,
32,"different cash generating units, are as follows;",,

Table 61:

,0,1,2,3,4,5,6
0,,Notes to the Financial Statements,,,,,
1,26. \nInvestment in subsidiaries,,,,,,
2,Accounting policy,,,,,,
3,,Investment in subsidiaries is initially recogn...,,,,,
4,,investment in subsidiaries is immediately reco...,,,,,
5,cost less any accumulated impairment losses.,,,,,,
6,26.1 Carrying value,,,,,,
7,,,,,,COMPANY,
8,As at 31 March,,,,,2022,2021
9,In Rs.'000s,,,,,,
10,Quoted,,,,26.2,"20,256,309","20,228,019"
11,Unquoted,,,,26.3,"96,710,286","81,106,517"
12,,,,,,"116,966,595","101,334,536"
13,26.2 Group quoted investments,,,,,,
14,,GROUP,,,COMPANY,,
15,As at 31 March,Number of,Effective,Number of,Effective,2022,2021
16,,shares,holding %,shares,holding %,In Rs.‘000s,In Rs.‘000s
17,Cost,,,,,,
18,Asian Hotels and Properties PLC,"347,824,190",78.56%,"347,824,190",78.56%,"5,378,525","5,381,562"
19,Ceylon Cold Stores PLC,"773,245,440",81.36%,"671,558,120",70.66%,"1,682,346","1,662,908"
20,John Keells Hotels PLC,"1,169,598,478",80.32%,"1,169,598,478",80.32%,"7,102,140","7,102,140"
21,John Keells PLC,"52,834,784",86.90%,"52,834,784",86.90%,"488,005","485,455"
22,Keells Food Products PLC,"22,937,250",88.63%,"20,364,054",79.86%,"1,241,876","1,239,768"
23,Tea Smallholder Factories PLC,"11,286,000",37.62%,"11,286,000",37.62%,"66,809","66,809"
24,Trans Asia Hotels PLC,"184,107,284",82.74%,"97,284,256",48.64%,"1,617,229","1,616,425"
25,Union Assurance PLC,"53,035,715",90.00%,"53,035,715",90.00%,"2,679,379","2,672,952"
26,,,,,,"20,256,309","20,228,019"

Table 62:

,0,1,2,3,4,5,6
0,As at 31 March,2022,,,2022,,2021
1,,Number of,Effective,Number of,Effective,Cost,Cost
2,,shares,holding %,shares,holding %,In Rs.‘000s,In Rs.‘000s
3,Ahungalla Holiday Resort (Pvt) Ltd,"13,275,000",80.32,-,-,-,-
4,Beruwala Holiday Resorts (Pvt ) Ltd,"219,725,653",79.78,-,-,"3,586","3,586"
5,British Overseas (Pvt) Ltd,61,61.00,61,61.00,-,-
6,Ceylon Holiday Resorts Ltd,"18,260,784",79.60,-,-,"3,887","3,850"
7,Cinnamon Hotels Management Ltd,"1,000,000",100.00,"1,000,000",100.00,"455,075","410,826"
8,Cinnamon Hotels Management International (Pvt)...,"50,000",100.00,-,-,-,-
9,Cinnamon Holidays (Pvt) Ltd,"20,000",80.32,-,-,-,-
10,Facets (Pvt) Ltd,"15,000",100.00,"15,000",100.00,-,-
11,Fantasea World Investments (Pte) Ltd,"7,299",80.32,-,-,"4,738","4,540"
12,Glennie Properties (Pvt) Ltd,"16,386,140",100.00,"16,386,140",100.00,"163,861","163,861"
13,Habarana Lodge Ltd,"12,981,548",78.99,-,-,"4,096","4,125"
14,Habarana Walk Inn Ltd,"4,321,381",79.34,-,-,"2,719","2,758"
15,Hikkaduwa Holiday Resorts (Pvt) Ltd,"107,596,700",79.60,-,-,"2,621","2,604"
16,InfoMate (Pvt) Ltd,"2,000,000",100.00,"2,000,000",100.00,"41,395","39,590"
17,International Tourists and Hoteliers Ltd,"38,490,901",79.78,-,-,-,-
18,J K Land (Pvt) Ltd,"2,302,760,246",,"100.00 2,302,760,246",100.00,"24,964,639","23,027,602"
19,J K Packaging (Pvt) Ltd,"1,450,000",100.00,"1,450,000",100.00,-,-
20,J K Thudella Properties (Pvt) Ltd,"45,346,760",100.00,-,-,-,-
21,JayKay Marketing Services (Pvt) Ltd,"202,239,025",81.36,-,-,"226,222","204,958"
22,John Keells BPO Holdings (Pvt) Ltd,"19,000,000",100.00,-,-,-,-
23,John Keells BPO International (Pvt) Ltd,"1,500,000,000",100.00,-,-,-,-
24,John Keells BPO Solutions Lanka (Pvt) Ltd,"32,843,578",100.00,-,-,-,-
25,John Keells Information Technologies (Pvt) Ltd,"9,650,000",100.00,"9,650,000",100.00,"123,346","122,958"
26,John Keells Foods India (Pvt) Ltd,"8,999,990",88.63,-,-,-,-
27,John Keells International (Pvt) Ltd,"199,160,000",100.00,"199,160,000",100.00,"673,526","671,655"
28,John Keells Logistics (Pvt) Ltd,"19,999,998",100.00,"19,999,998",100.00,"229,930","228,503"
29,John Keells Maldivian Resorts (Pte) Ltd,"49,044,238",80.32,-,-,"18,152","17,932"
30,John Keells Office Automation (Pvt) Ltd,"500,000",100.00,"500,000",100.00,"71,170","68,263"
31,John Keells Properties (Pvt) Ltd,"101,804",100.00,"101,804",100.00,-,-
32,John Keells Properties Ja-ela (Pvt) Ltd,"95,436,000",100.00,-,-,-,-
33,John Keells Residential Properties (Pvt) Ltd,"2,081,698",100.00,"2,081,698",100.00,"20,817","20,817"
34,John Keells Singapore (Pte) Ltd,"160,000",80.00,"160,000",80.00,"4,209","4,209"
35,John Keells Stock Brokers (Pvt) Ltd,"1,500,000",90.04,"360,000",24.00,"85,187","80,666"
36,John Keells Teas Ltd,"12,000",100.00,"12,000",100.00,"22,424","20,902"
37,John Keells Warehousing (Pvt) Ltd,"12,000,000",86.90,-,-,"5,034","5,006"
38,Kandy Walk Inn Ltd,"6,165,484",79.03,-,-,"4,089","4,105"
39,Keells Consultants (Pvt) Ltd,928,100.00,928,100.00,"2,066","2,032"
40,Keells Realtors Ltd,"7,500,000",95.81,"5,100,000",40.00,"119,124","119,124"
41,Keells Shipping (Pvt) Ltd,"50,000",100.00,"50,000",100.00,-,-
42,Lanka Marine Services (Pvt) Ltd,"34,805,470",99.44,"34,805,470",99.44,"1,409,828","1,403,053"
43,Logipark International (Pvt) Ltd,"60,407,698",81.36,-,-,-,-
44,Mack Air (Pvt) Ltd,"89,260",100.00,"89,260",100.00,"38,149","36,981"
45,Mack Air Services Maldives (Pte) Ltd,"4,900",49.00,"4,700",47.00,"2,021","2,021"
46,Mack International Freight (Pvt) Ltd,"13,000,000",100.00,"13,000,000",100.00,"2,268","1,792"
47,Mackinnon Keells Ltd,"31,966,951",100.00,"31,966,951",100.00,"670,166","670,166"

Table 63:

,0,1,2,3,4,5,6
0,As at 31 March,2022,,,2022,,2021
1,,Number of,Effective,Number of,Effective,Cost,Cost
2,,shares,holding %,shares,holding %,In Rs.‘000s,In Rs.‘000s
3,Mackinnon Mackenzie and Company (Shipping) Ltd,"139,092",100.00,"139,092",100.00,"65,850","65,848"
4,Mackinnon Mackenzie and Company of (Ceylon) Ltd,"1,244",100.00,"1,244",100.00,"29,122","29,122"
5,Mackinnons Travels (Pvt) Ltd,"499,996",100.00,"499,996",100.00,"31,150","30,583"
6,Mortlake (Pvt) Ltd,43,100.00,43,100.00,"20,000","20,000"
7,Nuwara Eliya Holiday Resort (Pvt) Ltd,"31,606,252",80.32,-,-,-,-
8,Rajawella Holdings Ltd,"13,063,936",49.85,"11,573,339",45.18,"801,707","801,707"
9,Rajawella Hotels Company Ltd,"3,157,384",80.32,-,-,-,-
10,Resort Hotels Ltd,"106,107",79.60,-,-,-,-
11,The Colombo Ice Company (Pvt) Ltd,"169,999,999",81.36,"169,999,999",81.36,"1,155",819
12,Tranquility (Pte) Ltd,"637,499",80.32,-,-,"5,702","5,616"
13,Trans-ware Logistics (Pvt) Ltd,"5,539,929",100.00,"5,539,929",100.00,"58,983","58,983"
14,Travel Club (Pte) Ltd,"29,059",80.32,-,-,"3,690","3,667"
15,Trinco Holiday Resort (Pvt) Ltd,"8,120,005",80.32,-,-,"3,623","3,590"
16,Trinco Walk Inn Ltd,"3,000,007",80.32,-,-,-,-
17,Vauxhall Land Developments (Pvt) Ltd,"2,171,655,391",100.00,-,-,-,-
18,Walkers Tours Ltd,"3,737,634",98.51,"3,737,634",98.05,"195,291","191,018"
19,Waterfront Properties (Pvt) Ltd,"7,140,071,956",,"98.59 5,053,995,419",87.37,"64,169,906","50,612,655"
20,Whittall Boustead (Pvt) Ltd,"5,341,105",100.00,"5,341,105",100.00,"1,668,721","1,655,358"
21,Whittall Boustead (Travel) Ltd,"22,452,271",100.00,"22,452,271",100.00,"278,289","276,325"
22,Wirawila Walk Inn Ltd,"1,706,750",80.32,-,-,-,-
23,Yala Village (Pvt) Ltd,"28,268,000",75.33,-,-,"2,752","2,740"
24,Yala Village (Pvt) Ltd- Non voting preference ...,"10,000,000",80.32,-,-,-,-
25,,,,,,"96,710,286","81,106,517"

Table 64:

,0,1,2,3,4,5,6,7,8
0,,shares,Holding,In Rs.,In Rs.,shares,Holding,In Rs.,In Rs.
1,,,%,‘000s,‘000s,,%,‘000s,‘000s
2,27.1 \nInvestments in joint ventures,,,,,,,,
3,Braybrooke Residential Properties (Pvt) Ltd,102,50.00,"1,804,500","1,804,500",-,-,-,-
4,DHL Keells (Pvt) Ltd,"1,000,000",50.00,"10,000","10,000","1,000,000",50.00,"10,000","10,000"
5,Inchcape Mackinnon Mackenzie Shipping,"164,520",60.00,"16,452",-,"164,520",60.00,"16,452",-
6,(Pvt) Ltd,,,,,,,,
7,Sentinel Reality (Pvt) Ltd,"6,863,673",40.16,"64,949","64,199",-,-,-,-
8,27.2 \nInvestments in associates,,,,,,,,
9,Quoted,,,,,,,,
10,Nations Trust Bank PLC- Voting shares,"76,788,257",29.49,"1,954,510","1,699,620","51,363,384",19.72,"1,367,480","1,198,265"
11,Nations Trust Bank PLC- Non voting shares,"21,386,596",52.10,"1,827,923","1,759,237","16,964,690",41.33,"1,339,871","1,283,868"
12,Unquoted,,,,,,,,
13,Capitol Hotel Holdings (Pvt) Ltd,"3,249,232",19.47,"325,483","325,483","3,254,832",19.47,"325,483","325,483"
14,Colombo West International Terminal,"28,559,696",34.00,"2,855,970",-,"28,559,696",34.00,"2,855,969",-
15,(Pvt) Ltd,,,,,,,,
16,Fairfirst Insurance Ltd,"68,902,870",19.80,"689,718","689,718",-,-,-,-
17,Indra Hotels and Resorts (Pvt) Ltd,"67,050,025",32.13,"670,742","670,742",-,-,-,-
18,Maersk Lanka (Pvt) Ltd,"30,000",30.00,150,150,"30,000",30.00,150,150
19,Saffron Aviation (Pvt) Ltd,"24,887,160",40.00,"248,872","248,872","24,887,160",40.00,-,-
20,Saffron Aviation (Pvt) Ltd - Preference,"135,530,835",-,"506,247","432,747","135,530,835",-,-,"432,747"
21,shares,,,,,,,,

Table 65:

,0,1,2,3,4,5,6,7,8
0,As at/year ended 31 March,2022,2021,2022,2021,2022,2021,2022,2021
1,In Rs.‘000s,,,,,,,,
2,Group share of;,,,,,,,,
3,Revenue,"8,103,449","6,639,452","9,544,444","7,777,167","8,633,085","3,353,506","26,280,978","17,770,125"
4,Operating expenses including,"(4,360,150)","(4,171,084)","(6,530,011)","(4,925,057)","(7,194,726)","(2,993,364)","(18,084,887)","(12,089,505)"
5,cost of sales,,,,,,,,
6,Net finance income,"151,165","137,887","(45,422)","2,304","(107,069)","(71,809)","(1,326)","68,382"
7,Tax expense,"(491,854)","(420,612)","(579,322)","(1,098,006)","(377,650)","(71,591)","(1,448,826)","(1,590,209)"
8,Share of results of equity,"3,402,610","2,185,643","2,389,689","1,756,408","953,640","216,742","6,745,939","4,158,793"
9,accounted investees,,,,,,,,
10,Other comprehensive income,"4,448,407","381,701","(466,783)","(121,007)","(3,033)","2,525","3,978,591","263,219"
11,Total Comprehensive Income,"7,851,017","2,567,344","1,922,906","1,635,401","950,607","219,267","10,724,530","4,422,012"
12,Group share of;,,,,,,,,
13,Total assets,"16,226,919","10,429,627","169,020,223","123,638,695","12,522,508","6,912,727","197,769,650","140,981,049"
14,Total liabilities,"(5,230,466)","(3,921,435)","(149,888,167)","(108,995,412)","(8,964,620)",,"(4,287,703) (164,083,253) (117,204,550)",
15,Net assets,"10,996,453","6,508,192","19,132,056","14,643,283","3,557,888","2,625,024","33,686,397","23,776,499"
16,Goodwill,-,"4,674,278","165,899","165,899","13,260","13,260","179,159","4,853,437"
17,,"10,996,453","11,182,470","19,297,955","14,809,182","3,571,148","2,638,284","33,865,556","28,629,936"
18,Capital commitments,-,-,-,"142,202","4,019,277","5,776,691","4,019,277","5,918,893"
19,Other commitments and,-,-,"78,043,531","54,475,196",-,-,"78,043,531","54,475,196"
20,Guarantees,,,,,,,,

Table 66:

,0,1,2,3
0,28.4 Loans to life policyholders,,,
1,,,GROUP,
2,As at 31 March,,2022,2021
3,In Rs.'000s,,,
4,At the beginning of the year,,"1,840,841","1,627,555"
5,Loans granted / transfers,,"878,410","885,798"
6,Recoveries,,"(766,857)","(672,512)"
7,At the end of the year,,"1,952,394","1,840,841"
8,29. \nOther non current assets,,,
9,,GROUP,COMPANY,
10,As at 31 March,2022\n2021\nNote,2022,2021
11,In Rs.'000s,,,
12,Pre paid cost,"282,339 \n341,600","119,755","92,668"
13,Work-in-progress - Waterfront project,"29.1\n 179,669,639 \n 103,260,711",-,-
14,Non current advances,"968,001 \n977,904",-,-
15,,"180,919,979 \n 104,580,215","119,755","92,668"
16,29.1 Work-in-progress - Waterfront project,,,
17,,,GROUP,
18,As at 31 March,,2022,2021
19,In Rs.'000s,,,
20,Freehold property*,,"19,345,604","12,703,071"
21,Leasehold property*,,"7,584,983","5,106,604"
22,Other constructions in progress,,"152,739,052","82,275,284"
23,Contractor advances,,-,"3,175,752"
24,,,"179,669,639","103,260,711"
25,* The freehold and leasehold property are loca...,,,
26,,Other non current assets represents the constr...,,
27,,and oth er project cost incurred. Freehold lan...,,
28,,prepayment made to obtaining the lease land ri...,,
29,incurred on the project and borrowing cost cap...,,,
30,,,"During the year ended 31 March 2022, Rs.57 Mn ...",
31,30. \nInventories,,,
32,,,recognised as an expense for inventories carri...,
33,Accounting policy,,,
34,,,This is recognised in cost of sales and other ...,
35,Inventories are valued at the lower of cost an...,,,
36,realisable value is the estimated selling pric...,,,
37,,,GROUP,
38,completion and the estimated costs necessary t...,,,
39,,As at 31 March,2022,2021
40,The costs incurred in bringing inventories to ...,,,
41,,In Rs.'000s,,
42,"condition, are accounted for as follows:",,,
43,,Inventories,,
44,• \nRaw materials - On a weighted average basis,,,
45,,Raw materials,"1,353,492","628,872"
46,• \nFinished goods and work-in-progress - At t...,,,
47,,Finished goods,"12,581,519","7,391,309"
48,direct labour and an appropriate proportion of...,,,
49,,Produce stocks,"241,284","253,605"
50,overheads based on normal operating capacity b...,,,
51,borrowing costs,Other stocks,"3,028,486","2,168,124"
52,,Apartments and commercial space,"19,020,106","43,854,213"
53,• Other inventories – At actual cost,,,
54,,,"36,224,887","54,296,123"

Table 67:

,0,1
0,Notes to the Financial Statements,
1,The number of shares in issue as at 31...,"Additionally, \nin terms of second phase, ..."
2,which \ninclude global depository \nreceipts...,"39,025,204 non-tradable/non-transferable opt..."
3,"-1,320,942 ). Further information on the compo...",subscribe for additional new ordinary sha...
4,given under the Share Information section of t...,investment amount of up to a maximum of...
5,,30 million. The options exercise price w...
6,"A quantum of 36,788,659 shares (2021 - 38,047,...",weighted average price of the Company’s ordina...
7,to be issued under the employee share option p...,the CSE during the 90 calendar days end...
8,,"option exercise date, subject to the floor pri..."
9,Private placement of ordinary shares,of Rs.200.00 and is exercisable between 19 Oct...
10,"In November 2021, the Company resolved t...",2023.
11,private placement of ordinary shares for a max...,
12,of the Rs. equivalent of USD 80 million to the...,"Based on the above, the maximum number of ordi..."
13,"two phases. In January 2022, the first phase o...",potentially be issued under the entire transac...
14,"completed, where JKH issued 65,042,006 ordinar...","are subscribed for, will be 104,067,210, ..."
15,share to ADB for a consideration of the Rs. eq...,dilution on the conclusion of both phases to a...
16,resulting in a post-issue dilution of 4.70 per...,
17,phase.,
18,34.2 \nOther components of equity,
19,,GROUP\nCOMPANY
20,As at 31 March,2022\n2021\n2022\n2021
21,In Rs.'000s,
22,Revaluation reserve,"41,012,553 \n 37,777,543 \n - \n -"
23,Foreign currency translation reserve,"79,185,589 \n 26,424,124 \n - \n -"
24,Other capital reserve,"3,060,095 \n 2,863,766 \n 3,060,095 \n 2,863,766"
25,Restricted regulatory reserve,"3,626,604 \n 3,626,604 \n - \n -"
26,Cash flow hedge reserve,"2,928,815 \n 349,024 \n 2,928,815 \n 729,316"
27,Fair value reserve of financial assets at FVOCI,"(802,243)\n1,362,079\n 21,171 \n 28,094"
28,,"129,011,413 \n72,403,140\n 6,010,081 \n 3,621,176"
29,The revaluation reserve consists of the net su...,"The regulatory Reserve, is subject to meeting ..."
30,"property, plant and equipment and present valu...",stipulated by the IRCSL and can only be releas...
31,business (PVIB).,approval from the IRCSL. The one-off surplus i...
32,,government debt securities as per the directio...
33,The foreign currency translation reserve compr...,
34,movement arising from the currency translation...,Nations Trust Bank PLC (NTB)
35,and equity accounted investees into Sri Lankan...,The statutory reserve fund is maintained as pe...
36,,terms of Section 20 of the Banking Act No 30 o...
37,The other capital reserve is used to recognise...,equivalent to 5% of proﬁt after tax transferre...
38,settled share-based payments provided to emplo...,the reserve fund is equal to 50% of the Bank’s...
39,"management personnel, as part of their remuner...",a further 2% of proﬁts will be transferred unt...
40,,equal to the Bank’s stated Capital.
41,Restricted regulatory reserve,
42,,Cash flow hedge reserve includes the fair valu...
43,Union Assurance PLC (UA),
44,,portion of interest rate swaps designated as c...
45,Based on the direction issued by the IRCSL dat...,
46,"subsequent approval, UA has transferred Rs.. 3...",
47,,The fair value reserve of financial assets at ...
48,non-participating and non unit fund of unit li...,
49,,value of financial instruments designated as f...
50,life policyholder fund to the life shareholder...,
51,"of the one-off surplus to shareholders, held a...",

Table 68:

,0,1
0,35. \nShare-based payment plans,Where the terms of an equity-settled transacti...
1,Accounting Policy,the minimum expense recognised is the expense ...
2,Employee share option plan - Equity-settled tr...,"been modified, if the original terms of the aw..."
3,Employees of the Group receive remuneration in...,expense is recognised for any modification tha...
4,"based payment transactions, whereby employees ...","value of the share-based payment transaction, ..."
5,consideration for equity instruments (equity-s...,to the employee as measured at the date of mod...
6,The Group applies SLFRS 2 Share Based Payments...,The dilutive effect of outstanding options is ...
7,employee remuneration in the form of shares fr...,dilution in the computation of diluted earning...
8,,are given in Note 19.2).
9,The cost of equity-settled transactions is rec...,
10,a corresponding increase in other capital rese...,Employee share option scheme
11,period in which the performance and service co...,Under the John Keells Group’s Employees share ...
12,The cumulative expense recognised for equity-s...,share options of the parent are granted to exe...
13,each reporting date until the vesting date ref...,generally with more than 12 months of service....
14,the vesting period has expired and the Group’s...,share options is equal to the 30 days volume w...
15,number of equity instruments that will ultimat...,price of the underlying shares on the date of ...
16,credit to the income statement for a period re...,vest over a period of four years and is depend...
17,in cumulative expense recognised as at the beg...,criteria and a service criteria. The performan...
18,period and is recognised in employee benefits ...,performance achievement of “Met Expectations” ...
19,,being that the employee has to be in employmen...
20,No expense is recognised for awards that do no...,options vest. The fair value of the share opti...
21,except for equity-settled transactions where v...,"date using a binomial option pricing model, ta..."
22,"upon a market or non-vesting condition, which ...",terms and conditions upon which the share opti...
23,irrespective of whether or not the market or n...,
24,"satisfied, provided that all other performance...",The contractual term for each option granted i...
25,satisfied.,cash settlement alternatives. The Group does n...
26,,cash settlement for these share options.
27,Share-based payment plans,
28,,GROUP\nCOMPANY
29,For the year ended 31 March,2022\n2021\n2022\n2021
30,In Rs.'000s,
31,Total expense arising from share-based payment...,"204,618\n225,007\n 61,117\n 66,035"
32,Movements in the year,
33,The following table illustrates the number (No...,
34,GROUP,COMPANY
35,2022\nAs at 31 March,2021\n2022\n2021
36,No.\nWAEP,No.\nWAEP\nNo.\nWAEP\nNo.\nWAEP
37,Outstanding at the beginning of the year \n 38...,"41,563,469 \n 152.67 \n 12,771,300 \n 150.82 \..."
38,"Granted during the year\n6,585,800\n136.64","6,557,100 \n 132.86 \n2,017,300\n136.64\n 1,81..."
39,Transfers\n-\n-,"-\n-\n-\n-\n (56,195)\n159.13"
40,"Exercised during the year\n(210,675)\n137.28","(1,113,183)\n 142.81 \n-\n-\n (363,100)\n142.83"
41,"Expired during the year\n(7,633,609)\n143.93","(8,960,243)\n 150.47 \n(2,700,363)\n143.06 \n ..."
42,"Outstanding at the end of the year\n36,788,659...","38,047,143 \n 150.06 \n12,088,237 \n150.18\n 1..."
43,"Exercisable at the end of the year\n21,929,305...","22,717,896 \n 155.17 \n7,412,529 \n158.31\n 8,..."

Table 69:

,0,1
0,Notes to the Financial Statements,
1,35. \nShare-based payment plans (Contd.),The expected life of the share options is base...
2,,current expectations and is not necessarily in...
3,"Accounting judgements, estimates and assumptions",
4,,that may occur. The expected volatility reflec...
5,The Group measures the cost of equity-settled ...,
6,,the historical volatility over a period simila...
7,employees by reference to the fair value of th...,
8,,"is indicative of future trends, which may not ..."
9,the date at which they are granted. Estimating...,
10,,outcome either.
11,payment transactions require determination of ...,
12,"valuation model, which is dependent on the ter...",
13,,The following information was used and results...
14,the grant. This estimate also requires the det...,
15,,binomial model for ESOP.
16,"appropriate inputs to the valuation model, inc...",
17,"the share option, volatility and dividend yiel...",
18,about them.,
19,,COMPANY
20,As at 31 March,2022\n2021\n2020\n2019\n2018
21,,Plan no 10\nPlan no 10\nPlan no 10\nPlan no 9\...
22,,award 3\naward 2\naward 1\naward 3\naward 2
23,Dividend yield (%),3.28\n3.87\n 3.62 \n 3.76 \n 3.99
24,Expected volatility (%),22.37\n21.35\n 17.47 \n 17.77 \n 17.54
25,Risk free interest rate (%),8.87\n6.44\n 9.83 \n 10.09 \n 11.48
26,Expected life of share options (Years),5\n5\n5\n5\n5
27,Weighted average share price at the grant date...,132.63\n134.74\n 138.70 \n 154.10 \n 173.25
28,Weighted average remaining contractual life fo...,3\n3\n3\n3\n3
29,(Years),
30,Weighted average fair value of options granted...,44.21\n44.91\n 46.23 \n51.37\n 56.27
31,Exercise price for options outstanding at the ...,136.64\n132.86\n 136.97 \n 154.10 \n 173.25
32,Exercise price for options outstanding at the ...,136.64\n132.86\n 136.97 \n154.14\n173.30
33,March 2022),
34,36. \nInsurance contract liabilities,
35,Accounting policy,
36,Insurance contract liabilities,
37,The long term and unit linked insurance busine...,
38,annual valuation of the life insurance busines...,
39,assumptions recommended by the actuary.,
40,36.1 \nInsurance contract liabilities,
41,,GROUP
42,As at 31 March,2022\n2021
43,In Rs.'000s,
44,Insurance contract liabilities,"50,939,495 \n 44,791,714"
45,Unclaimed benefits,"409,828 \n 368,897"
46,,"51,349,323 \n 45,160,611"
47,Life insurance contract liabilities,participating liabilities are discounted using...
48,Life insurance contract liabilities are recogn...,value of participating policy liabilities is t...
49,entered into and premiums are charged. These l...,guaranteed benefits liability and the total be...
50,by using the gross premium valuation method as...,the participating insurance fund level. In cal...
51,"Regulation of Insurance Industry Act, No. 43 o...","benefits liability, only the guaranteed benefi..."
52,determined as the discounted value of the expe...,cashflows are discounted using the risk free i...
53,outflows less the discounted value of the expe...,Total benefits liability includes all the guar...
54,assumptions are derived based on the best esti...,"benefits, and discount the cash flows using th..."
55,with a prescribed risk margin to allow for adv...,participating insurance fund. The Liability is...
56,John Keells Holdings PLC | Annual Report 202...,

Table 70:

,0,1
0,contract expenses is discharged or is cancelle...,• are likely to be a significant portion of ...
1,an assessment is made of whether the recognise...,
2,,• \nthe amount or timing of which is contract...
3,"are adequate, by using a liability adequacy test.",
4,,issuer; and contractually based on:
...,...,...
57,with or without discretionary participating fe...,valuation of insurance contract liabilities. F...
58,,"risk related to longevity, prudent allowance i..."
59,Discretionary participating features (DPF),"mortality improvements, as well as wide rangin..."
60,"DPF is a contractual right to receive, as a su...","style, which could result in significant chang..."
61,"benefits, additional benefits that;",mortality exposure.

Table 71:

,0,1
0,Liability adequacy test (LAT) - Life insurance...,36.2 Change in life insurance contract liabi...
1,"As at 31 December 2021, liability adequacy tes...",The results of Union Assurance PLC’s (UA) life...
2,"appointed actuary Mr. Vivek Jalan FIA, FIAI of...",consolidated into the Group’s Consolidated Inc...
3,"Private Limited who concluded that, the liabil...",change in life insurance contract liabilities ...
4,"meet future benefits and expenses. Hence, no p...","the Life Fund, the difference between all inco..."
5,be made for any premium deficiency.,attributable to life policy holders during the...
6,Summarised financial information,
7,For the year ended 31 March,2022\n2021
8,In Rs.'000s,
9,Total Revenue,"15,225,571 \n 13,221,167"
10,Cost of sales,"(7,829,465)\n (6,168,801)"
11,Gross profit,"7,396,106 \n 7,052,366"
12,Operating expenses including distribution and ...,"(4,377,144)\n (4,192,748)"
13,Net finance income,"5,281,652 \n 5,023,000"
14,Profit attributable to shareholders of UA,"(1,884,315)\n (850,926)"
15,Change in insurance contract liabilities,"6,416,299 \n 7,031,692"
16,Union Assurance PLC follows a risk mitigation ...,
17,liabilities.,
18,The following table describes headline risks a...,
19,Headline risk,Risk response
20,Investment return on underlying items failing ...,Management discretion to determine amount and ...
21,rates,holders bonuses (within limits)
22,Insufficient fees to cover cost of guarantees ...,Hedging programme
23,Differences in duration and yield of assets an...,• Matching of assets and liabilities cash flows
24,,• Investing in investment grade assets
25,Policy holder behavioural risk,Surrender penalty
26,37. \nInterest-bearing loans and borrowings,
27,37.1 Movement,
28,,GROUP\nCOMPANY
29,As at 31 March,2022\n2021\n2022\n2021
30,In Rs.'000s,
31,At the beginning of the year,"128,473,113 \n 56,131,366 \n 47,186,858 \n 605..."
32,Cash movement,
33,Loans obtained,"53,876,802 \n 71,729,856 \n 3,000,000 \n 43,88..."
34,Repayments,"(34,946,688)\n(6,753,731)\n (1,474,806)\n (540..."
35,Non cash movement,
36,Accrued Interest,"948,393 \n 1,138,330 \n134,057\n 428,650"
37,Exchange differences,"51,194,726 \n6,227,292\n 18,350,918 \n 2,803,320"
38,At the end of the year,"199,546,346 \n 128,473,113 \n 67,197,027 \n 47..."
39,Repayable within one year,"40,624,448\n 9,507,473 \n 2,562,994 \n 3,007,368"
40,Repayable after one year,"158,921,898\n 118,965,640 \n 64,634,033 \n 44,..."
41,,"199,546,346 \n 128,473,113 \n 67,197,027 \n 47..."

Table 72:

,0,1,2,3,4,5
0,Notes to the Financial Statements,,,,,
1,38. \nEmployee benefit liabilities (Contd.),,,,,
2,38.3 Other long term employee benefits,,,,,
3,,GROUP,,,COMPANY,
4,As at 31 March,2022,2021,,2022,2021
5,In Rs.'000s,,,,,
6,At the beginning of the year,"483,892","270,865",,"108,175","64,132"
7,Current service cost,"152,048","192,058",,"35,290","37,701"
8,Interest cost,"31,656","20,969",,"7,601","6,342"
9,At the end of the year,"667,596","483,892",,"151,066","108,175"
10,"Accounting judgements , estimates and assumptions",,,,,
11,Employee benefit liability - gratuity,,,,,
12,,The employee benefit liability of the Group is...,,,,
13,,are involve in making assumptions about discou...,,,,
14,,"its long term nature, the defined benefit obli...",,,,
15,date.,,,,,
16,,Under the Minimum Retirement Age of Workers Ac...,,,,
17,increase in retirement age.,,,,,
18,,The Management tested several scenarios based ...,,,,
19,,"conditions. Based on those calculations, the m...",,,,
20,the Group.,,,,,
21,The principal assumptions used in determining ...,,,,,
22,As at 31 March,,,2022,,2021
23,Discount rate,,,8.00% -10.00%,,7.00% -9.00%
24,Future salary increases,,,7.00% -9.00%,,6.00% -8.00%
25,38.4 Sensitivity of assumptions used,,,,,
26,,A percentage change in the assumptions would h...,,,,
27,,GROUP,,,COMPANY,
28,As at 31 March,2022,2021,,2022,2021
29,Discount rate:,,,,,
30,1% Increase,"(117,176)","(100,137)",,"(5,798)","(6,955)"
31,1% Decrease,"113,434","110,514",,"6,281","7,673"
32,Salary Increment rate:,,,,,
33,1% Increase,"118,799","111,402",,"6,541","7,867"

Table 73:

,0,1
0,Notes to the Financial Statements,
1,42. \nShort term borrowings,
2,Accounting policy,
3,Short term borrowings are the interest bearing...,
4,obtained for working capital requirements.,
5,,GROUP\nCOMPANY
6,As at 31 March,2022\n2021\n2022\n2021
7,In Rs.'000s,
8,Bank borrowings,"14,833,056 \n 6,903,737 \n 2,000,000 \n-"
9,,"14,833,056 \n 6,903,737 \n 2,000,000 \n-"
10,43. \nOther current liabilities,
11,Accounting policy,
12,The Group classifies all non financial current...,
13,,GROUP\nCOMPANY
14,As at 31 March,2022\n2021\n2022\n2021
15,In Rs.'000s,
16,Non refundable deposits,"627,277 \n 518,057 \n-\n -"
17,Contract liabilities,"- \n 2,093,394 \n 758,085 \n-"
18,Other tax payables,"20,796 \n 1,559,716 \n 457,256 \n-"
19,,"20,796 \n 4,280,387 \n 1,733,398 \n-"
20,44. \nRelated party transactions,Non-recurrent related party transactions
21,Terms and conditions of transactions with rela...,There were no non-recurrent related party tran...
22,The Group and the Company carried out transact...,aggregate value exceeds 10% of the equity or 5...
23,course of business with the following related ...,whichever is lower of the company as per 31 Ma...
24,"at each of the subsidiaries, joint venture and...","financial statements, which required additiona..."
25,have been disclosed in the Group Directory und...,2021/22 Annual Report under Colombo Stock Exch...
26,Information section of the Annual Report.,9.3.2 and Code of Best Practices on Related Pa...
27,,Securities and Exchange Commission Directive i...
28,"Governance structure, nature of the entity’s r...",13(c) of the Securities and Exchange Commissio...
29,of business and the country of incorporation h...,
30,“Report of the Related Party Transaction Revie...,Recurrent related party transactions
31,directory.,There were no recurrent related party transact...
32,,value exceeds 10% of the consolidated revenue ...
33,Transactions with related parties are carried ...,"March 2021 audited financial Statements, which..."
34,of business. Outstanding current account balan...,disclosures in the 2021/22 Annual Report under...
35,"unsecured, interest free and settlement occurs...",Exchange listing Rule 9.3.2 and Code of Best P...
36,,Transactions under the Securities and Exchange...
37,The sales to and purchases from related partie...,issued under Section 13(c) of the Securities a...
38,equivalent to those that prevail in arm's leng...,Act.
39,44.1 Amounts due from related parties,
40,,GROUP\nCOMPANY
41,As at 31 March,Note\n2022\n2021\n2022\n2021
42,In Rs.'000s,
43,Subsidiaries,"44.5\n - \n - \n 531,375 \n 1,379,839"
44,Equity accounted investees,"196,394 \n 123,553 \n 129,324 \n 85,977"
45,Key management personnel,- \n - \n - \n -
46,,"196,394 \n 123,553 \n 660,699 \n 1,465,816"

Table 74:

,0,1,2,3,4,5
0,,,,COMPANY,,
1,,,2022,,2021,
2,Expiry date,Adjusted exercise,Number of shares,Number of shares,Number of shares,Number of shares
3,,price,outstanding at,exercisable at the,outstanding at the,exercisable at the
4,,Rs.,the end of period,end of period,end of period,end of period
5,14.08.2021,,,,"600,000","600,000"
6,02.07.2022,173.30,"725,000","725,000","725,000","543,750"
7,21.06.2023,154.14,"880,000","660,000","880,000","440,000"
8,30.06.2024,136.97,"880,000","440,000","880,000","220,000"
9,30.06.2025,132.86,"880,000","220,000","880,000",-
10,30.06.2026,136.64,"880,000",-,-,-

Table 75:

,0,1,2,3,4,5,6,7,8,9,10
0,31 March,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013
1,Rs. Mn,,,,,,,,,,
2,OPERATING RESULTS,,,,,,,,,,
3,Group revenue,"218,075","127,676","138,956","135,456","121,215","106,273","93,710","91,852","86,706","85,408"
4,EBIT,"34,359","7,931","15,508","20,198","28,155","23,324","20,192","19,226","16,537","16,677"
5,Finance cost,"(7,035)","(4,669)","(3,166)","(2,722)",(521),(436),(994),(668),"(1,217)","(1,081)"
6,Share of results of equity accounted,"6,746","4,159","4,466","4,727","3,596","3,303","2,781","2,778","3,089","3,440"
7,investees (net of tax),,,,,,,,,,
8,Profit before tax,"27,324","5,445","12,403","18,616","27,634","22,888","19,198","18,557","15,320","15,595"
9,Tax expense,"(6,882)","(1,494)","(2,662)","(2,378)","(4,515)","(4,771)","(3,406)","(2,812)","(2,362)","(2,162)"
10,Profit after tax,"20,443","3,951","9,741","16,237","23,120","18,117","15,792","15,745","12,958","13,433"
11,Attributable to:,,,,,,,,,,
12,Equity holders of the parent,"20,213","4,772","9,414","15,254","21,021","16,275","14,070","14,348","11,721","12,113"
13,Non-controlling interests,230,(821),327,983,"2,099","1,842","1,722","1,397","1,237","1,320"
14,,"20,443","3,951","9,741","16,237","23,120","18,117","15,792","15,745","12,958","13,433"
15,CAPITAL EMPLOYED,,,,,,,,,,
16,Stated capital,"73,188","63,102","62,881","62,806","62,802","62,790","58,702","50,703","49,749","26,480"
17,Capital reserves and other components,"129,011","72,403","66,085","58,646","49,852","38,652","28,715","24,501","21,845","20,635"
18,of equity,,,,,,,,,,
19,Revenue reserves,"109,087","90,652","87,885","82,834","87,266","77,193","67,565","62,594","51,304","42,704"
20,,"311,286","226,157","216,851","204,286","199,920","178,635","154,982","137,798","122,898","89,819"
21,Non-controlling interest,"18,805","16,830","26,872","26,072","24,944","15,696","13,499","12,279","11,421","11,152"
22,Total equity,"330,091","242,987","243,723","230,358","224,864","194,331","168,481","150,077","134,319","100,971"
23,Total debt,"268,228","172,904","100,907","54,513","29,722","22,766","20,750","23,934","26,139","20,107"
24,,"598,319","415,891","344,630","284,871","254,586","217,097","189,231","174,011","160,458","121,078"
25,ASSETS EMPLOYED,,,,,,,,,,
26,"Property, plant and equipment (PP&E)","124,348","113,077","111,534","97,688","87,260","64,396","52,737","49,563","47,406","49,200"
27,Non-current assets other than PP&E,"354,518","257,226","204,360","170,687","136,427","107,912","93,376","78,030","71,969","59,787"
28,Current assets,"238,929","166,491","121,050","95,421","98,762","104,964","94,863","90,493","82,206","49,934"
29,Liabilities net of debt,"(119,476)","(120,903)","(92,314)","(78,925)","(67,862)","(60,175)","(51,745)","(44,075)","(41,123)","(37,843)"
30,,"598,319","415,891","344,630","284,871","254,587","217,097","189,231","174,011","160,458","121,078"
31,CASH FLOW,,,,,,,,,,
32,Net cash flows from operating activities,"30,440","13,825","(10,350)","(4,743)","16,012","21,020","20,513","20,855","8,041","14,568"
33,Net cash flows from / (used in) investing,"39,363","(44,944)","(27,039)","(8,452)","(16,640)","(17,670)","(9,567)","(1,255)","(19,710)","(16,199)"
34,activities,,,,,,,,,,
35,Net cash flows from / (used in) financing,"31,693","55,427","18,431","(11,000)","(4,587)","(4,105)","(7,717)","(4,838)","25,446","(1,320)"
36,activities,,,,,,,,,,
37,Net increase / (decrease) in cash and cash,"101,495","24,308","(18,959)","(14,709)","(5,215)",(755),"3,229","14,762","13,777","(2,951)"
38,equivalents,,,,,,,,,,
39,KEY INDICATORS,,,,,,,,,,
40,Basic earnings per share (Rs.),15.13,3.62,7.14,11.13,15.2,11.9,10.5,12.6,10.5,10.7
41,Interest cover (no. of times),4.9,1.7,4.9,7.8,54,52.8,51.5,27.7,13.6,15.4
42,Net assets per share* (Rs.),224.8,163.3,156.6,147.5,144.4,129.0,111.9,99.5,88.7,64.9
43,Enterprise value (EV),"311,951","244,679","186,236","210,020","187,926",136.022,"124,182","155,675","124,182","203,615"
44,EV / EBITDA,10.7,15.7,9.2,8.5,5.8,5.0,5.0,6.6,10.0,10.0
45,ROE (%),7.5,2.2,4.5,7.5,11.1,9.8,9.6,11.0,11.0,15.0
46,Debt / equity ratio (%),81.3,71.2,41.4,23.7,13.2,11.7,12.3,15.9,19.5,19.9
47,Net debt excl. leases (cash)/Equity (%),23.5,20.0,14.0,1.9,(14.9),(28.5),(30.8),(28.8),(23.2),(8.0)
48,Dividend payout (Rs.Mn),"2,012","1,978","4,614","8,186","8,325","7,280","8,038","3,476","3,267","2,982"
49,Current ratio (no. of times),1.8,2.3,2.1,1.7,3.0,3.7,4.0,2.6,2.4,2.0
50,Market price per share unadjusted (Rs.),145.0,148.5,115.4,156.0,159.6,137.9,148.0,199.4,227.0,247.0
51,Market price per share diluted (Rs.),145.0,148.5,115.4,156.0,159.6,137.9,129.5,152.7,173.8,238.2
52,Revenue growth rate (%),70.8,(8.1),2.6,11.8,14.1,13.4,1.6,5.9,4.1,9.7
53,USD closing rate (Rs.),305.0,200.3,189.6,175.5,155.9,151.9,147.7,133.5,130.7,126.8
54,USD average rate (Rs.),208.3,189.0,179.4,168.6,153.6,148.0,139.2,131.2,130.1,129.9

Table 76:

,0,1,2,3,4
0,In USD '000s,,,,
1,Continuing operations,,,,
2,Revenue from contracts with customers,"665,079","571,415","6,150","8,173"
3,Revenue from Insurance Contracts,"49,920","66,007",-,-
4,Total Revenue,"714,999","637,422","6,150","8,173"
5,Cost of sales,"(591,574)","(542,921)","(3,558)","(4,780)"
6,Gross profit,"123,425","94,501","2,592","3,393"
7,Dividend income,-,-,"26,255","41,669"
8,Other operating income,"8,573","13,113",168,203
9,Selling and distribution expenses,"(18,796)","(23,770)",-,-
10,Administrative expenses,"(48,402)","(64,542)","(4,207)","(5,243)"
11,Other operating expenses,"(40,839)","(6,562)","(1,687)",(107)
12,Results from operating activities,"23,961","12,740","23,121","39,915"
13,Finance cost,"(23,065)","(23,311)","(9,725)","(6,215)"
14,Finance income,"101,004","53,364","79,339","23,052"
15,Change in insurance contract liabilities,"(21,037)","(35,106)",-,-
16,Change in fair value of investment property,"(13,393)","(1,265)",-,-
17,Share of results of equity accounted investees...,"22,118","20,763",-,-
18,Profit before tax,"89,588","27,185","92,735","56,752"
19,Tax expense,"(22,563)","(7,460)","(12,782)","(4,000)"
20,Profit for the year,"67,025","19,725","79,953","52,752"
21,Attributable to:,,,,
22,Equity holders of the parent,"66,272","23,825",,
23,Non-controlling interests,753,"(4,100)",,

Table 77:

,0,1,2
0,Glossary,,
1,ACCRUAL BASIS,DIVIDEND YIELD,NET PROFIT MARGIN
2,Recording revenues and expenses in the period,Dividends adjusted for changes in number of,Profit after tax attributable to equity holder...
3,in which they are earned or incurred regardless,shares in issue as a percentage of the share p...,the parent divided by total revenue including
4,of whether cash is received or disbursed in that,(diluted) at the end of the period.,equity accounted investees.
...,...,...,...
99,,,Shareholders’ funds plus non-controlling inter...
100,,regulatory fund at UA and customer advances at,
101,,the Property Development sector.,
102,,,WORKING CAPITAL
103,,,Current assets minus current liabilities.

Table 78:

,0,1,2,3,4,5,6
0,,Company Name,Nature,Incorporated,Addresses,Directors,Stated Capital &
1,,,,Year,,,Effective Holding
2,,Colombo West,Ports & Shipping Services,2021,"No. 117,","K.N.J.Balendra,","USD 30,000,000"
3,,International,,(PV 00238709),Sir Chittampalam A. Gardiner,,34%
4,,,,,,"J.G.A.Cooray, S.Mehta,",
...,...,...,...,...,...,...,...
62,Air Lines,Mackinnons Travels,IATA accredited travel,1971,"No. 11, York Street,","K.D.Weerasinghe,","Rs.5,000,000"
63,,(Pvt) Ltd,,(PV 1261),Colombo 1,"K.C.Subasinghe, A.Z.Hashim",100%
64,,,agent and travel related,,,,
65,,,,,T. 2318600,,
66,,,services,,,,

Table 79:

,0,1,2,3,4,5,6
0,,Company Name,Nature,Incorporated,Addresses,Directors,Stated Capital &
1,,,,Year,,,Effective Holding
2,,Ceylon Cold Stores,Manufacture & Marketing,1926,"No.117,Chittampalam A","K.N.J.Balendra- Chairman,","Rs.918,200,000"
3,,PLC,of Beverages and frozen,(PQ 4),"Gardiner Mawatha,","J.G.A.Cooray, D.P.Gamlath,",81.36%
4,,,confectionery and the,,Colombo 02,"M.Hamza, S.T.Ratwatte,",
...,...,...,...,...,...,...,...
63,,,resort hotel companies in,,,,
64,,,,,Colombo 02,"M.R.Svensson,",
65,,,Sri Lanka & Maldives,,,,
66,,,,,T. 2306600,"J.E.P.Kehelpannala,",
67,,,,,,"M.H.Singhawansa,",

Table 80:

,0,1,2,3,4,5,6
0,Company Name,Nature,,Incorporated,Addresses,Directors,Stated Capital &
1,,,,Year,,,Effective Holding
2,Asian Hotels and,Owner & operator of the five,1993,,"No.77, Galle Road,",K.N.J.Balendra -,"Rs.3,345,118,012"
3,Properties PLC -,"star city hotel ""Cinnamon",(PQ 2),,Colombo 3,Chairman/ Managing,78.56%
4,Cinnamon Grand.,"Grand""",,,T. 2437437 /2497206,"Director, J.G.A.Cooray,",
...,...,...,...,...,...,...,...
71,,,,,T. 2306000,M.R.Svensson,
72,Rajawella Hotels,Owner of real estate,1992,,"No.117, Chittampalam","C.L.P.Gunawardane,","Rs.35,701,762"
73,Company Ltd*,,(PB 92),,"A Gardiner Mawatha,","K.C.Subasinghe, M.H",80.32%
74,,,,,Colombo 02,"Singhawansa, M.R.Svensson",
75,,,,,T. 2306000,,

Table 81:

,0,1,2,3,4,5
0,Company Name,Nature,Incorporated,Addresses,Directors,Stated Capital &
1,,,Year,,,Effective Holding
2,Resort Hotels Ltd*,Owner of real estate,1978,"No.117,Chittampalam","C.L.P.Gunawardane,","Rs.8,849,150"
3,,,(PB 193),"A Gardiner Mawatha,","K.C.Subasinghe,",79.60%
4,,,,Colombo 02,"M.H Singhawansa ,",
...,...,...,...,...,...,...
59,,,(PB 249),"A Gardiner Mawatha,","C.L.P.Gunawardane,",98.05%
60,,,,Colombo 02. T. 2306306,I.N.Amaratunga,
61,Whittall Boustead,Inbound tour operators,1977,"No.117, Chittampalam","S.Rajendra ,","Rs.250,410,000"
62,(Travel) Ltd,,(PB 112),"A Gardiner Mawatha,","C.L.P.Gunawardane,",100%
63,,,,Colombo 02. T. 2306746,I.N.Amaratunga,

Table 82:

,0,1,2,3,4,5,6
0,,Company Name,Nature,Incorporated,Addresses,Directors,Stated Capital &
1,,,,Year,,,Effective Holding
2,,Asian Hotels and,Developer of 'Crescat,1993,"No.77 Galle Road,",K.N.J.Balendra-,"Rs.3,345,118,012"
3,,Properties PLC -,"Residencies', 'The Monarch'",(PQ 2),Colombo. 03,Chairman/Managing,78.56%
4,,"Crescat. Boulevard,",& 'The Emperor' Residential,,T. 0112152100,"Director, J.G.A.Cooray,",
...,...,...,...,...,...,...,...
61,,(Pvt) Ltd,"Apartments, offices &",(PV 82153),Colombo 02,"G.A.Cooray, S Rajendra ,",98.59%
62,,,Shoping Malls,,T. 0112152100,N.N.Mawilmada,
63,,Whittall Boustead,Renting of office space,1958,"No.186, Vauxhall Street,","N.W.R.Wijewantha,","Rs.99,188,800"
64,,(Pvt) Ltd - Real Estate,,(PV 31),Colombo 02,"K.C.Subasinghe,",100%
65,,Division*,,,T. 0112152100,"N.N.Mawilmada,",

Table 83:

,0,1,2,3,4,5,6
0,,Company Name,Nature,Incorporated,Addresses,Directors,Stated Capital &
1,,,,Year,,,Effective Holding
2,,Fairfirst Insurance,Providers of Non Life,2014,"Access Towers II, 14th Floor,","R.Athappan-Chairman,","Rs.3,131,949,000"
3,,Ltd**,insurance solutions,(PB 5180),"No: 278/4, Union Place,","C.Ratnaswami,",19.80%
4,,,,,Colombo 02,"A.S.Wijesinha,",
5,,,,,T. 0112 428 428,"C.D.Wijegunawardene,",
6,,,,,,"S.Malhotra, J.P.Gomes,",
7,,,,,,R.M.Prabhakar,
8,,John Keells Stock,Share broking services,1979,"No. 186, Vauxhall Street,","S.Rajendra, D.P.Gamlath,","Rs.57,750,000"
9,,Brokers (Pvt) Ltd,,(PV 89),Colombo 02,R.S.Cader,90.04%
10,,,,,"T. +94(0)11230 6250,",,
11,,,,,+94(0)11234 2066 -7,,
12,,Nations Trust Bank,Commercial banking and,1999,"No. 242, Union Place,","J.G.A.Cooray-Chairman,","Rs.9,408,135,000"
13,,PLC**,leasing operations,(PQ 118),Colombo 2,"R.S.Cader, J.C.A.D'Souza,",32.57%
14,,,,,T.114313131,"R.D.Rajapaksa, N.I.R.De",
15,,,,,,"Mel, S.Maheshwari,",
16,,,,,,"S.L.Sebastian,",
17,,,,,,"C.H.A.W.Wickramasuriya,",
18,,,,,,"A.R.Fernando, P.Talwatte,",
19,,,,,,"R.Shanmuganathan,",
20,,,,,,C.K.Hettiarachchi,
21,,Union Assurance PLC Providers of Life insurance,,1987,"No.20, St. Michaels' Road,","K.N.J.Balendra -Chairman,","Rs.1,000,000,000"
22,,,solutions,(PQ 12),Colombo 03,"S.Rajendra, D.P.Gamlath,",90%
23,,,,,T. #1330,"D.H.Fernando,",
24,,,,,,"S.A.Appleyard, W.M De",
25,,,,,,Fonseka Arsakularatne,
26,,John Keells,Software services,1998,"No. 148, Vauxhall Street,","J.G.A.Cooray -Chairman,","Rs.96,500,000"
27,Services,Information,,(PV 652),Colombo 02.,"K.D.Weerasinghe,",100%
28,,Technology (Pvt) Ltd,,,T. 2300770-77,R.Shanmuganathan,
29,,InfoMate (Pvt) Ltd,IT enabled services,2005,"No.4, Leyden Bastian Road,","K.D.Weerasinghe,","Rs.20,000,000"
30,,,,(PV 921),Colombo 1,R.Shanmuganathan,100%
31,,,,,T. (94) 112149700,,
32,,John Keells BPO,Holding company of BPO,2006,"IFS Court, 28, Cybercity,","Z.H.Niamut, K.Peerbocus,","Rs.1,988,300,000"
33,,Holdings (Pvt) Ltd*,group companies,(C 60882),"Ebene, Mauritius","K.D.Weerasinghe,",100%
34,Services,,,,T. (230) 467 3000,K.C.Subasinghe,
35,,John Keells BPO,Investment holding,2007,"IFS Court, 28, Cybercity,","Z.H.Niamut, K.Peerbocus,","Rs.1,616,700,008"
36,,International (Pvt),company,(C 070137),"Ebene, Mauritius","K.D.Weerasinghe,",100%
37,,Ltd*,,,T. (230) 467 3000,K.C.Subasinghe,
38,,John Keells BPO,BPO operations in Sri Lanka,2006,"No.4, Leyden Bastian Road,","K.D.Weerasinghe,","Rs.335,797,260"
39,,Solutions Lanka (Pvt),,(PV 3458),Colombo 01,"K.C.Subasinghe,",100%
40,,Ltd*,,,T. (94) 2300770-77,R.Shanmuganathan,
41,,John Keells PLC,Produce Broking and Real,1960,"No 186, Vauxhall Street,",K.N.J.Balendra-,"Rs.152,000,000"
42,,,Estate Ownership,(PQ 11),Colombo 02,"Chairman, J.G.A.Cooray,",86.90%
43,,,,,T. 2306000,"K.D.Weerasinghe,",
44,,,,,,"A.K.Gunawardhana,",
45,,,,,,"C.N.Wijewardene,",
46,,,,,,"B.A.I.Rajakarier, A.Z.Hashim",
47,,John Keells (Teas) Ltd Manager of seven bought,,1979,"No.117,Chittampalam A","K.D.Weerasinghe,","Rs.120,000"
48,,,leaf tea factories,(PV 522),"Gardiner Mawatha,","K.C.Subasinghe, A.Z Hashim",100%
49,,,,,Colombo 02 T. 2306518,,
50,Plantation Services,John Keells,Warehousing of Tea and,2001,"No.93,1st Avenue,","K.D.Weerasinghe,","Rs.120,000,000"
51,,Warehousing (Pvt),Rubber,(PV 638),"Muturajawela, Hendala,","K.C.Subasinghe, A.Z.Hashim",86.90%
52,,Ltd,,,Wattala,,
53,,,,,T. 4819560,,
54,,Tea Smallholder,Owner and operator of,1991,"No.4, Leyden Bastian Road,","K.N.J.Balendra–Chairman,","Rs.150,000,000"
55,,Factories PLC,Bought Leaf factories,(PQ 32),Colombo 1,"J.G.A.Cooray, E.H.Wijenaike,",37.62%
56,,,,,T. 2149994 / 2335880,"A.S.Jayatilleke,",
57,,,,,,"S.K.L.Obeyesekere,",
58,,,,,,"A.K.Gunaratne,",
59,,,,,,"A.Goonetilleke, A.Z.Hashim",

Table 84:

,0,1,2,3,4,5,6
0,,Company Name,Nature,Incorporated,Addresses,Directors,Stated Capital &
1,,,,Year,,,Effective Holding
2,,Facets (Pvt) Ltd*,Owner of real estate,1974,"No.117,Sir Chittampalam A","K.M.Thanthirige,","Rs.150,000"
3,,,,(PV1048),"Gardiner Mawatha,",D.P.Gamlath,100%
4,,,,,Colombo 02 T. 2306000,,
5,,J K Packaging (Pvt),Printing and packaging,1979,"No. 4, Leyden Bastian Road,","K.C.Subasinghe,","Rs.14,500,000"
6,,Ltd*,services provider for the,(PV 1265),Colombo 1,"K.D.Weerasinghe,",100%
7,,,export market,,T. 2475308,D.P.Gamlath,
8,,John Keells Holdings,Group holding company &,1979,"No.117, Sir Chittampalam A",K.N.J.Balendra-,"Rs.73,187,860,511"
9,,PLC,function based services,(PQ 14),"Gardiner Mawatha, Colombo","Chairman, J.G.A.Cooray-",
10,,,,,02,"Deputy Chairman,",
11,,,,,T. 2306000,"M.A.Omar, D.A.Cabraal,",
12,,,,,,"A.N.Fonseka, M.P Perera,",
13,,,,,,S.S.H.Wijayasuriya,
14,,John Keells,Regional holding company,2006,"No.117, Chittampalam A","D.P.Gamlath, K,M.","Rs.1,991,600,000"
15,Centre & Others,International (Pvt),providing administrative &,(PV 46),"Gardiner Mawatha, Colombo","Thanthirige, N.W.Tambiah",100%
16,,Ltd*,function based services,,02,,
17,,,,,T. 2306000 /2421101-9,,
18,,John Keells,International trading services 1992,,"No.16 Collyer Quay, Level","J.G.A.Cooray-Chairman,","Rs.9,638,000"
19,,Singapore (Pte) Ltd*,,(199200499C),"21, Office Suit No.21-38,","K.M .Thanthirige,",80%
20,,,,,Singapore 049318,"K.C.Subasinghe,",
21,,,,,T. 65 63296409/ 65,"D.P.Gamlath,",
22,,,,,68189150/ 65 96346593,R.Ponnampalam,
23,,Keells Consultants,Company secretarial services,1974,"No.117, Chittampalam A","K.M.Thanthirige,","Rs.160,000"
24,,(Pvt) Ltd,to the group,(PB 3),"Gardiner Mawatha, Colombo","N.W.Tambiah,",100%
25,,,,,02,"I.V.Gunasekera,",
26,,,,,T. 2421101-9,C.Subasinghe,
27,,Mortlake (Pvt) Ltd*,Investment company,1961,"No. 4, Leyden Bastian Road,","K.M.Thanthirige,","Rs.. 5,500"
28,,,,(PV 756),Colombo 1,K.C.Subasinghe,100%
29,,,,,T. 2475308,,
30,* The company is a non-operational company/ in...,,,,,,

Table 85:

,0,1,2
0,GRI 101: Foundation 2016,,
1,GRI 102: General Disclosures 2016,,
2,Organizational Profile,,
3,,102-1 Name of the organisation,5
4,,"102-2 Activities, brands, products, and","5, 62"
5,,services,
6,,102-3 Location of headquarters,5
7,,102-4 Location of operations,5
8,,102-5 Ownership and legal form,5
9,,102-6 Markets served,5
10,,102-7 Scale of the organisation,"5, 51, 56"
11,,102-8 Information on employees and,56 - 61
12,,other workers,
13,,102-9 Supply chain,11 of https://keells.com/resource/Management_A...
14,,,"Disclosures_2021_22.pdf, 78, 87-88, 98-99, 112..."
15,,102-10 Significant changes to the,19 - 34
16,,organisation and its supply chain,
17,,102-11 Precautionary Principle or,"3 of Risks, Opportunities and Internal Control..."
18,,approach,resource/governance/John-Keells-Holdings-PLC-A...
19,,102-12 External initiatives,"3, 175, 192"
20,,102-13 Membership of associations,https://keells.com/resource/governance/John-Ke...
21,,,AR-2021_22-Profiles.pdf
22,Strategy,,
23,,102-14 Statement from senior decision-,8 -18
24,,maker,
25,Ethics and integrity,,
26,,"102-16 Values, principles, standards, and",175
27,,norms of behaviour,
28,Governance,,
29,,102-18 Governance structure,177
30,Stakeholder engagement,,
31,,102-40 List of stakeholder groups,"4-5 of Sustainability Integration, Stakeholder..."
32,,,https://keells.com/resource/governance/John-Ke...
33,,,AR%202021_22- Sustainability-and-Materiality.pdf
34,,102-41 Collective bargaining,61
35,,agreements,
36,,102-42 Identifying and selecting,"4 of Sustainability Integration, Stakeholder E..."
37,,stakeholders,at https://keells.com/resource/governance/John...
38,,,PLC%20 AR%202021_22- Sustainability-and-Materi...
39,,102-43 Approach to stakeholder,"4-5 of Sustainability Integration, Stakeholder..."
40,,engagement,Materiality at https://keells.com/resource/gov...
41,,,Holdings-PLC%20 AR%202021_22- Sustainability-a...
42,,102-44 Key topics and concerns raised,"5-6 of Sustainability Integration, Stakeholder..."
43,,,Materiality at https://keells.com/resource/gov...

Table 86:

,0,1
0,102-45 Entities included in the,306 - 312
1,consolidated financial statements,
2,102-46 Defining report content and,"4-5 , 6-7 of Sustainability Integration, Stake..."
3,topic Boundaries,Materiality at https://keells.com/resource/gov...
4,,Holdings-PLC%20 AR%202021_22- Sustainability-a...
5,102-47 List of material topics,"6-7 of Sustainability Integration, Stakeholder..."
6,,Materiality at https://keells.com/resource/gov...
7,,Holdings-PLC%20 AR%202021_22- Sustainability-a...
8,102-48 Restatements of information,"3-4 of Sustainability Integration, Stakeholder..."
9,,Materiality at https://keells.com/resource/gov...
10,,Holdings-PLC%20 AR%202021_22- Sustainability-a...
11,102-49 Changes in reporting,"3-4 of Sustainability Integration, Stakeholder..."
12,,Materiality at https://keells.com/resource/gov...
13,,Holdings-PLC%20 AR%202021_22- Sustainability-a...
14,102-50 Reporting period,3
15,102-51 Date of most recent report,"3 of Sustainability Integration, Stakeholder E..."
16,,at https://keells.com/resource/governance/John...
17,,PLC%20 AR%202021_22- Sustainability-and-Materi...
18,102-52 Reporting cycle,"3 of Sustainability Integration, Stakeholder E..."
19,,at https://keells.com/resource/governance/John...
20,,PLC%20 AR%202021_22- Sustainability-and-Materi...
21,102-53 Contact point for questions,IBC
22,regarding the report,
23,102-54 Claims of reporting in,3
24,accordance with the GRI Standards,
25,102-55 GRI content index,303 - 310
26,102-56 External assurance,293 - 295

Table 87:

,0,1,2
0,GRI 201:,201-1 Direct economic value,296 - 297
1,Economic,generated and distributed,
2,Performance,,
3,,201-3 Defined benefit plan obligations,61
4,2016,,
5,,and other retirement plans,
6,Indirect Economic Impacts,,
7,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
8,,,https://keells.com/resource/governance/John-Ke...
9,Management,topic and its Boundary,
10,,,AR%202021_22- Sustainability-and-Materiality.pdf
11,Approach 2016,,
12,,103-2 The management approach and,4 of https://keells.com/resource/Management_Ap...
13,,its components,Disclosures_2021_22.pdf
14,,103-3 Evaluation of the management,4 of https://keells.com/resource/Management_Ap...
15,,approach,Disclosures_2021_22.pdf
16,GRI 203: Indirect,203-1 Infrastructure investments and,62
17,Economic,services supported,
18,Impacts 2016,,
19,Procurement Practices,,
20,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
21,,,https://keells.com/resource/governance/John-Ke...
22,Management,topic and its Boundary,
23,,,AR%202021_22- Sustainability-and-Materiality.pdf
24,Approach 2016,,
25,,103-2 The management approach and,4 of https://keells.com/resource/Management_Ap...
26,,its components,Disclosures_2021_22.pdf
27,,103-3 Evaluation of the management,4 of https://keells.com/resource/Management_Ap...
28,,approach,Disclosures_2021_22.pdf
29,GRI 204:,204-1 Proportion of spending on local,62
30,Procurement,suppliers,
31,Practices 2016,,
32,Tax,,
33,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
34,Management,topic and its Boundary,Materiality at https://keells.com/resource/gov...
35,Approach 2016,,Holdings-PLC%20 AR%202021_22- Sustainability-a...
36,,103-2 The management approach and,4 of https://keells.com/resource/Management_Ap...
37,,its components,Disclosures_2021_22.pdf
38,,103-3 Evaluation of the management,4 of https://keells.com/resource/Management_Ap...
39,,approach,Disclosures_2021_22.pdf
40,GRI 207: Tax 2019,207-1 Approach to tax,24-25 of https://keells.com/resource/governanc...
41,,,KeellsHoldings-PLC-AR-2021_22-Corporate-Govern...
42,,"207-2 Tax governance, control, and risk",24-25 of https://keells.com/resource/governanc...
43,,management,KeellsHoldings-PLC-AR-2021_22-Corporate-Govern...
44,,207-3 Stakeholder engagement and,24-25 of https://keells.com/resource/governanc...
45,,management of concerns related to,KeellsHoldings-PLC-AR-2021_22-Corporate-Govern...
46,,tax,
47,,207-4 Country-by-country reporting,313

Table 88:

,0,1,2
0,GRI 300: Environment Standard Series,,
1,Energy,,
2,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
3,Management,,https://keells.com/resource/governance/John-Ke...
4,,topic and its Boundary,
5,Approach 2016,,AR%202021_22- Sustainability-and-Materiality.pdf
6,,103-2 The management approach and,5 of https://keells.com/resource/Management_Ap...
7,,its components,Disclosures_2021_22.pdf
8,,103-3 Evaluation of the management,6 of https://keells.com/resource/Management_Ap...
9,,approach,Disclosures_2021_22.pdf
10,GRI 302: Energy,302-1 Energy consumption within the,51 - 52
11,2016,organisation,
12,,302-4 Reduction of energy,51 - 52
13,,consumption,
14,Water and Effluents,,
15,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
16,Management,,https://keells.com/resource/governance/John-Ke...
17,,topic and its Boundary,
18,Approach 2016,,AR%202021_22- Sustainability-and-Materiality.pdf
19,,103-2 The management approach and,5 of https://keells.com/resource/Management_Ap...
20,,its components,Disclosures_2021_22.pdf
21,,103-3 Evaluation of the management,6 of https://keells.com/resource/Management_Ap...
22,,approach,Disclosures_2021_22.pdf
23,GRI 303: Water,303-1 Interactions with water as a,5-6 of https://keells.com/resource/Management_...
24,and Effluents,shared resource,Disclosures_2021_22.pdf
25,2018,303-2 Management of water,5-6 of https://keells.com/resource/Management_...
26,,discharge-related impacts,Disclosures_2021_22.pdf
27,,303-3 Water withdrawal,52 - 53
28,,303-4 Water discharge,53
29,Biodiversity,,
30,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
31,Management,,https://keells.com/resource/governance/John-Ke...
32,,topic and its Boundary,
33,Approach 2016,,AR%202021_22- Sustainability-and-Materiality.pdf
34,,103-2 The management approach and,5 of https://keells.com/resource/Management_Ap...
35,,its components,Disclosures_2021_22.pdf
36,,103-3 Evaluation of the management,6 of https://keells.com/resource/Management_Ap...
37,,approach,Disclosures_2021_22.pdf
38,GRI 304:,"304-1 Operational sites owned, leased,",109 - 110
39,Biodiversity 2016,"managed in, or adjacent to,",
40,,protected areas and areas of high,
41,,biodiversity value outside protected,
42,,areas,
43,Emissions,,
44,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
45,Management,,https://keells.com/resource/governance/John-Ke...
46,,topic and its Boundary,
47,Approach 2016,,AR%202021_22- Sustainability-and-Materiality.pdf
48,,103-2 The management approach and,5 of https://keells.com/resource/Management_Ap...
49,,its components,Disclosures_2021_22.pdf
50,,103-3 Evaluation of the management,6 of https://keells.com/resource/Management_Ap...
51,,approach,Disclosures_2021_22.pdf

Table 89:

,0,1,2
0,GRI 305:,305-1 Direct (Scope 1) GHG emissions,51
1,Emissions 2016,305-2 Energy indirect (Scope 2) GHG,51
2,,emissions,
3,Effluents and Waste,,
4,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
5,Management,,https://keells.com/resource/governance/John-Ke...
6,,topic and its Boundary,
7,Approach 2016,,AR%202021_22- Sustainability-and-Materiality.pdf
8,,103-2 The management approach and,5 of https://keells.com/resource/Management_Ap...
9,,its components,Disclosures_2021_22.pdf
10,,103-3 Evaluation of the management,6 of https://keells.com/resource/Management_Ap...
11,,approach,Disclosures_2021_22.pdf
12,GRI 306: Effluents,306-3 Significant spills,77
13,and Waste 2016,,
14,Waste,,
15,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
16,Management,topic and its Boundary,Materiality at https://keells.com/resource/gov...
17,Approach 2016,,Holdings-PLC%20 AR%202021_22- Sustainability-a...
18,,103-2 The management approach and,5 of https://keells.com/resource/Management_Ap...
19,,its components,Disclosures_2021_22.pdf
20,,103-3 Evaluation of the management,6 of https://keells.com/resource/Management_Ap...
21,,approach,Disclosures_2021_22.pdf
22,GRI 306:,306-1 Waste generation and,6 of https://keells.com/resource/Management_Ap...
23,Waste 2020,significant waste-related impacts,Disclosures_2021_22.pdf
24,,306-2 Management of significant,6 of https://keells.com/resource/Management_Ap...
25,,waste-related impacts,Disclosures_2021_22.pdf
26,,306-3 Waste generated,54 - 55
27,Environmental Compliance,,
28,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
29,Management,,https://keells.com/resource/governance/John-Ke...
30,,topic and its Boundary,
31,Approach 2016,,AR%202021_22- Sustainability-and-Materiality.pdf
32,,103-2 The management approach and,5 of https://keells.com/resource/Management_Ap...
33,,its components,Disclosures_2021_22.pdf
34,,103-3 Evaluation of the management,6 of https://keells.com/resource/Management_Ap...
35,,approach,Disclosures_2021_22.pdf
36,GRI 307:,307-1 Non-compliance with,51
37,Environmental,environmental laws and regulations,
38,compliance 2016,,
39,Supplier Environmental Assessment,,
40,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
41,Management,topic and its Boundary,Materiality at https://keells.com/resource/gov...
42,Approach 2016,,Holdings-PLC%20 AR%202021_22- Sustainability-a...
43,,103-2 The management approach and,5 of https://keells.com/resource/Management_Ap...
44,,its components,Disclosures_2021_22.pdf
45,,103-3 Evaluation of the management,6 of https://keells.com/resource/Management_Ap...
46,,approach,Disclosures_2021_22.pdf
47,GRI 308: Supplier,308-1 New suppliers that were,62
48,Environmental,screened using environmental criteria,
49,Assessment 2016,,

Table 90:

,0,1,2
0,GRI 400: Social Standard Series,,
1,Employment,,
2,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
3,Management,,https://keells.com/resource/governance/John-Ke...
4,,topic and its Boundary,
5,Approach 2016,,AR%202021_22- Sustainability-and-Materiality.pdf
6,,103-2 The management approach and,7-8 of https://keells.com/resource/Management_...
7,,its components,Disclosures_2021_22.pdf
8,,103-3 Evaluation of the management,10 of https://keells.com/resource/Management_A...
9,,approach,Disclosures_2021_22.pdf
10,GRI 401:,401-1 New employee hires and,"52, 59"
11,Employment,employee turnover,
12,2016,,
13,Occupational Health and Safety,,
14,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
15,Management,,https://keells.com/resource/governance/John-Ke...
16,,topic and its Boundary,
17,Approach 2016,,AR%202021_22- Sustainability-and-Materiality.pdf
18,,103-2 The management approach and,7-8 of https://keells.com/resource/Management_...
19,,its components,Disclosures_2021_22.pdf
20,,103-3 Evaluation of the management,10 of https://keells.com/resource/Management_A...
21,,approach,Disclosures_2021_22.pdf
22,GRI 403:,403-1 Occupational health and safety,8-9 of https://keells.com/resource/Management_...
23,Occupational,management system,Disclosures_2021_22.pdf
24,Health and Safety,"403-2 Hazard identification, risk",8-9 of https://keells.com/resource/Management_...
25,2018,"assessment, and incident investigation",Disclosures_2021_22.pdf
26,,403-3 Occupational health services,8-9 of https://keells.com/resource/Management_...
27,,,Disclosures_2021_22.pdf
28,,"403-4 Worker participation,",8-9 of https://keells.com/resource/Management_...
29,,"consultation, and communication on",Disclosures_2021_22.pdf
30,,occupational health and safety,
31,,403-5 Worker training on occupational,8-9 of https://keells.com/resource/Management_...
32,,health and safety,Disclosures_2021_22.pdf
33,,403-6 Promotion of worker health,8-9 of https://keells.com/resource/Management_...
34,,,Disclosures_2021_22.pdf
35,,403-7 Prevention and mitigation,8-9 of https://keells.com/resource/Management_...
36,,of occupational health and safety,Disclosures_2021_22.pdf
37,,impacts directly linked by business,
38,,relationships,
39,,403-9 Work-related injuries,61

Table 91:

,0,1,2
0,Training and Education,,
1,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
2,Management,,https://keells.com/resource/governance/John-Ke...
3,,topic and its Boundary,
4,Approach 2016,,AR%202021_22- Sustainability-and-Materiality.pdf
5,,103-2 The management approach and,7-8 of https://keells.com/resource/Management_...
6,,its components,Disclosures_2021_22.pdf
7,,103-3 Evaluation of the management,10 of https://keells.com/resource/Management_A...
8,,approach,Disclosures_2021_22.pdf
9,GRI 404: Training,404-1 Average hours of training per,60
10,and Education,year per employee,
11,2016,"""404-3 Percentage of employees",56
12,,receiving regular performance and,
13,,"career development reviews""",
14,Diversity and equal opportunity,,
15,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
16,Management,,https://keells.com/resource/governance/John-Ke...
17,,topic and its Boundary,
18,Approach 2016,,AR%202021_22- Sustainability-and-Materiality.pdf
19,,103-2 The management approach and,7-8 of https://keells.com/resource/Management_...
20,,its components,Disclosures_2021_22.pdf
21,,103-3 Evaluation of the management,10 of https://keells.com/resource/Management_A...
22,,approach,Disclosures_2021_22.pdf
23,GRI 405: Diversity,405-1 Diversity of governance bodies,57 - 58
24,and equal,and employees,
25,opportunity 2016,,
26,Freedom of association and collective bargaining,,
27,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
28,Management,,https://keells.com/resource/governance/John-Ke...
29,,topic and its Boundary,
30,Approach 2016,,AR%202021_22- Sustainability-and-Materiality.pdf
31,,103-2 The management approach and,7-8 of https://keells.com/resource/Management_...
32,,its components,Disclosures_2021_22.pdf
33,,103-3 Evaluation of the management,10 of https://keells.com/resource/Management_A...
34,,approach,Disclosures_2021_22.pdf
35,GRI 407: Freedom,407-1 Operations and suppliers,57
36,of association,in which the right to freedom of,
37,and collective,association,
38,bargaining 2016,and collective bargaining may be at,
39,,risk,
40,Child Labour,,
41,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
42,Management,,https://keells.com/resource/governance/John-Ke...
43,,topic and its Boundary,
44,Approach 2016,,AR%202021_22- Sustainability-and-Materiality.pdf
45,,103-2 The management approach and,7-10 of https://keells.com/resource/Management...
46,,its components,Disclosures_2021_22.pdf
47,,103-3 Evaluation of the management,10 of https://keells.com/resource/Management_A...
48,,approach,Disclosures_2021_22.pdf
49,GRI 408: Child,408-1 Operations and suppliers at,56
50,Labour 2016,significant risk for incidents of child,
51,,labour,

Table 92:

,0,1,2
0,Forced or Compulsory Labor,,
1,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
2,Management,topic and its Boundary,Materiality at https://keells.com/resource/gov...
3,Approach 2016,,Holdings-PLC%20 AR%202021_22- Sustainability-a...
4,,103-2 The management approach and,7-10 of https://keells.com/resource/Management...
5,,its components,Disclosures_2021_22.pdf
6,,103-3 Evaluation of the management,10 of https://keells.com/resource/Management_A...
7,,approach,Disclosures_2021_22.pdf
8,GRI 409: Forced,409-1 Operations and suppliers at,56
9,or Compulsory,significant risk for incidents of forced,
10,Labor,or compulsory labor,
11,Local Communities,,
12,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
13,Management,,https://keells.com/resource/governance/John-Ke...
14,,topic and its Boundary,
15,Approach 2016,,AR%202021_22- Sustainability-and-Materiality.pdf
16,,103-2 The management approach and,12-13 of https://keells.com/resource/Managemen...
17,,its components,Disclosures_2021_22.pdf
18,,103-3 Evaluation of the management,13 of https://keells.com/resource/Management_A...
19,,approach,Disclosures_2021_22.pdf
20,GRI 413: Local,"""413-1 Operations with local community",62 - 66
21,communities,"engagement, \nimpact \nassessments,",
22,2016,"and development programs""",

Table 93:

,0,1,2
0,Marketing and Labelling,,
1,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
2,,,https://keells.com/resource/governance/John-Ke...
3,Management,topic and its Boundary,
4,,,AR%202021_22- Sustainability-and-Materiality.pdf
5,Approach 2016,,
6,,103-2 The management approach and,14 of https://keells.com/resource/Management_A...
7,,its components,Disclosures_2021_22.pdf
8,,103-3 Evaluation of the management,14 of https://keells.com/resource/Management_A...
9,,approach,Disclosures_2021_22.pdf
10,GRI 417:,417-1 Requirements for product and,62
11,Marketing and,service information and labelling,
12,Labelling 2016,417-3 Incidents of non-,62
13,,compliance concerning marketing,
14,,communications,
15,Socioeconomic Compliance,,
16,GRI 103,103-1 Explanation of the material,"6-7 of Sustainability Integration, Stakeholder..."
17,Management,,https://keells.com/resource/governance/John-Ke...
18,,topic and its Boundary,
19,Approach 2016,,AR%202021_22- Sustainability-and-Materiality.pdf
20,,103-2 The management approach and,14 of https://keells.com/resource/Management_A...
21,,its components,Disclosures_2021_22.pdf
22,,103-3 Evaluation of the management,14 of https://keells.com/resource/Management_A...
23,,approach,Disclosures_2021_22.pdf
24,GRI 419:,419-1 Non-compliance with laws and,62
25,Socioeconomic,regulations in the social and economic,
26,Compliance 2016,area,

In [5]:
keywords_1 = ['for the year ended 31 march','total revenue', 'cost of sales', 'gross profit','other operating income','basic']
keywords_2 = ['net assets per share** (rs.)','net assets per share* (rs.)']
# Loop through all the tables
for i, table in enumerate(tables):

    # Convert all cells to lowercase for matching
    table_lower = table.astype(str).apply(lambda col: col.str.lower())
  
    # Dictionary to store matched values
    matched_rows = {}

    for keyword in keywords_1:
        # Find rows containing the keyword
        row = table[table_lower.apply(lambda r: keyword in ' '.join(r), axis=1)]
        if not row.empty:
            matched_rows[keyword] = row.iloc[0, 3]

    if matched_rows:
        print(f"\n✅ Table {i+1} contains financial rows:")
        for k, v in matched_rows.items():
            print(f"{k.title()} (column 3): {v}")
        #display(table)  # Show the full table (optional)
        break
    else:
        print(f"Table {i+1} does not contain any of the target keywords.")



# Loop through all the tables
for i, table in enumerate(tables):
    # Convert all cells to lowercase for matching
    table_lower = table.astype(str).apply(lambda col: col.str.lower())
  
    # Dictionary to store matched values
    matched_rows = {}

    for keyword in keywords_2:
        # Find rows containing the keyword
        row = table[table_lower.apply(lambda r: keyword in ' '.join(r), axis=1)]
        if not row.empty:
            matched_rows[keyword] = row.iloc[0, 1]

    if matched_rows:
        print(f"\n✅ Table {i+1} contains financial rows:")
        for k, v in matched_rows.items():
            print(f"{k.title()} {type(k.title())}(column 1): {v}")
        #display(table)  # Show the full table (optional)
        break
    else:
        print(f"Table {i+1} does not contain any of the target keywords.")

Table 1 does not contain any of the target keywords.
Table 2 does not contain any of the target keywords.
Table 3 does not contain any of the target keywords.
Table 4 does not contain any of the target keywords.
Table 5 does not contain any of the target keywords.
Table 6 does not contain any of the target keywords.
Table 7 does not contain any of the target keywords.
Table 8 does not contain any of the target keywords.
Table 9 does not contain any of the target keywords.
Table 10 does not contain any of the target keywords.
Table 11 does not contain any of the target keywords.
Table 12 does not contain any of the target keywords.
Table 13 does not contain any of the target keywords.
Table 14 does not contain any of the target keywords.
Table 15 does not contain any of the target keywords.
Table 16 does not contain any of the target keywords.
Table 17 does not contain any of the target keywords.
Table 18 does not contain any of the target keywords.
Table 19 does not contain any of the target keywords.
Table 20 does not contain any of the target keywords.
Table 21 does not contain any of the target keywords.
Table 22 does not contain any of the target keywords.
Table 23 does not contain any of the target keywords.
Table 24 does not contain any of the target keywords.
Table 25 does not contain any of the target keywords.
Table 26 does not contain any of the target keywords.
Table 27 does not contain any of the target keywords.
Table 28 does not contain any of the target keywords.
Table 29 does not contain any of the target keywords.
Table 30 does not contain any of the target keywords.
Table 31 does not contain any of the target keywords.
Table 32 does not contain any of the target keywords.
Table 33 does not contain any of the target keywords.
Table 34 does not contain any of the target keywords.
Table 35 does not contain any of the target keywords.
Table 36 does not contain any of the target keywords.
Table 37 does not contain any of the target keywords.
Table 38 does not contain any of the target keywords.

✅ Table 39 contains financial rows:
For The Year Ended 31 March (column 3): 2021
Total Revenue (column 3): 127,675,650
Cost Of Sales (column 3): (108,747,058)
Gross Profit (column 3): 18,928,592
Other Operating Income (column 3): 2,626,544
Table 1 does not contain any of the target keywords.
Table 2 does not contain any of the target keywords.
Table 3 does not contain any of the target keywords.
Table 4 does not contain any of the target keywords.
Table 5 does not contain any of the target keywords.
Table 6 does not contain any of the target keywords.
Table 7 does not contain any of the target keywords.
Table 8 does not contain any of the target keywords.
Table 9 does not contain any of the target keywords.
Table 10 does not contain any of the target keywords.
Table 11 does not contain any of the target keywords.
Table 12 does not contain any of the target keywords.
Table 13 does not contain any of the target keywords.
Table 14 does not contain any of the target keywords.
Table 15 does not contain any of the target keywords.
Table 16 does not contain any of the target keywords.
Table 17 does not contain any of the target keywords.
Table 18 does not contain any of the target keywords.
Table 19 does not contain any of the target keywords.
Table 20 does not contain any of the target keywords.
Table 21 does not contain any of the target keywords.
Table 22 does not contain any of the target keywords.
Table 23 does not contain any of the target keywords.
Table 24 does not contain any of the target keywords.
Table 25 does not contain any of the target keywords.
Table 26 does not contain any of the target keywords.
Table 27 does not contain any of the target keywords.
Table 28 does not contain any of the target keywords.
Table 29 does not contain any of the target keywords.
Table 30 does not contain any of the target keywords.
Table 31 does not contain any of the target keywords.
Table 32 does not contain any of the target keywords.
Table 33 does not contain any of the target keywords.
Table 34 does not contain any of the target keywords.
Table 35 does not contain any of the target keywords.
Table 36 does not contain any of the target keywords.
Table 37 does not contain any of the target keywords.
Table 38 does not contain any of the target keywords.
Table 39 does not contain any of the target keywords.
Table 40 does not contain any of the target keywords.
Table 41 does not contain any of the target keywords.
Table 42 does not contain any of the target keywords.
Table 43 does not contain any of the target keywords.
Table 44 does not contain any of the target keywords.
Table 45 does not contain any of the target keywords.
Table 46 does not contain any of the target keywords.
Table 47 does not contain any of the target keywords.
Table 48 does not contain any of the target keywords.
Table 49 does not contain any of the target keywords.
Table 50 does not contain any of the target keywords.
Table 51 does not contain any of the target keywords.
Table 52 does not contain any of the target keywords.
Table 53 does not contain any of the target keywords.
Table 54 does not contain any of the target keywords.
Table 55 does not contain any of the target keywords.
Table 56 does not contain any of the target keywords.
Table 57 does not contain any of the target keywords.
Table 58 does not contain any of the target keywords.
Table 59 does not contain any of the target keywords.
Table 60 does not contain any of the target keywords.
Table 61 does not contain any of the target keywords.
Table 62 does not contain any of the target keywords.
Table 63 does not contain any of the target keywords.
Table 64 does not contain any of the target keywords.
Table 65 does not contain any of the target keywords.
Table 66 does not contain any of the target keywords.
Table 67 does not contain any of the target keywords.
Table 68 does not contain any of the target keywords.
Table 69 does not contain any of the target keywords.
Table 70 does not contain any of the target keywords.
Table 71 does not contain any of the target keywords.
Table 72 does not contain any of the target keywords.
Table 73 does not contain any of the target keywords.
Table 74 does not contain any of the target keywords.

✅ Table 75 contains financial rows:
Net Assets Per Share* (Rs.) <class 'str'>(column 1): 224.8

In [7]:
# Initialize a list to store extracted data
data_for_csv = []

for i, table in enumerate(tables):
    # Convert all cells to lowercase and strip spaces
    table_lower = table.astype(str).map(lambda x: x.strip().lower())

    # Flag to track if a matching row was found
    found = False

    # Check each row
    for _, row in table_lower.iterrows():
        row_list = row.tolist()
        number_of_count = sum("number of" in cell for cell in row_list)
        percent_count = sum("%" in cell for cell in row_list)
    
        if number_of_count == 2 and percent_count == 2:
            print("Row has at least two 'number of' and two '%' entries")
            display(table)

            # Extract data starting from row 1 (assuming row 0 is header)
            share_holder_names = table.iloc[1:, 0].astype(str).str.strip().tolist()
            share_percentage = table.iloc[1:, 2].astype(str).str.strip().tolist()
            year = [2020] * len(share_holder_names)

            for name, percentage, yr in zip(share_holder_names, share_percentage, year):
                data_for_csv.append([yr, name, percentage])

            print(year)
            print(share_holder_names)
            print(share_percentage)
        

            found = True
            break  # stop checking more rows in the same table

# Save extracted data to CSV
df_csv = pd.DataFrame(data_for_csv, columns=["Year", "Shareholder Name", "Share Percentage"])
df_csv.to_csv("shareholder_data.csv", index=False, mode='a', header=False)

print("Data has been appended to 'shareholder_data.csv'")

Row has at least two 'number of' and two '%' entries

,0,1,2,3,4
0,,31 March 2022,,31 March 2021,
1,,Number of,%,Number of,%
2,,shares,,shares,
3,Paints and General Industries Limited,"140,437,428",10.14,"114,977,303",8.71
4,Mr S E Captain,"134,220,895",9.69,"150,769,641",11.42
5,Melstacorp PLC,"128,917,111",9.31,"128,917,111",9.77
6,HWIC Asia Fund,"119,200,760",8.61,"39,250,982",2.97
7,Asian Development Bank,"65,042,006",4.70,-,-
8,Citigroup Global Markets Limited Agency Tradin...,"61,904,939",4.47,"141,854,717",10.75
9,Schroder International Selection Fund,"41,974,590",3.03,"42,475,806",3.22
10,Mr R S Captain,"34,405,091",2.48,"35,544,282",2.69
11,Norges Bank Account 2,"31,901,605",2.30,"31,706,807",2.40
12,Aberdeen Standard Asia Focus PLC,"28,123,572",2.03,"23,873,572",1.81
13,Mr Kandiah Balendra,"19,511,476",1.41,"19,511,476",1.48
14,Employees Trust Fund Board,"18,499,897",1.34,"18,709,833",1.42
15,Fidelity Fund - Pacific,"17,880,904",1.29,"17,880,904",1.35
16,Mrs C S De Fonseka,"17,472,745",1.26,"16,952,586",1.28
17,Mrs S A J De Fonseka,"15,204,230",1.10,"15,204,230",1.15
18,Edgbaston Asian Equity Trust,"15,142,109",1.09,"14,809,382",1.12
19,Chemanex PLC,"12,605,234",0.91,"11,417,835",0.87
20,Sri Lanka Insurance Corporation Limited - Life...,"12,270,665",0.89,-,-
21,Mr K N J Balendra,"10,907,628",0.79,"10,907,628",0.83
22,Schroder Asian Growth Fund,"10,328,047",0.75,"10,328,047",0.78

[2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020]
['', '', 'Paints and General Industries Limited', 'Mr S E Captain', 'Melstacorp PLC', 'HWIC Asia Fund', 'Asian Development Bank', 'Citigroup Global Markets Limited Agency Trading Prop Securities A/C', 'Schroder International Selection Fund', 'Mr R S Captain', 'Norges Bank Account 2', 'Aberdeen Standard Asia Focus PLC', 'Mr Kandiah Balendra', 'Employees Trust Fund Board', 'Fidelity Fund - Pacific', 'Mrs C S De Fonseka', 'Mrs S A J De Fonseka', 'Edgbaston Asian Equity Trust', 'Chemanex PLC', 'Sri Lanka Insurance Corporation Limited - Life Fund', 'Mr K N J Balendra', 'Schroder Asian Growth Fund']
['%', '', '10.14', '9.69', '9.31', '8.61', '4.70', '4.47', '3.03', '2.48', '2.30', '2.03', '1.41', '1.34', '1.29', '1.26', '1.10', '1.09', '0.91', '0.89', '0.79', '0.75']
Data has been appended to 'shareholder_data.csv'